"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/devtools/cloudbuild/v2/repositories.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.devtools.cloudbuild.v2 import cloudbuild_pb2 as google_dot_devtools_dot_cloudbuild_dot_v2_dot_cloudbuild__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0google/devtools/cloudbuild/v2/repositories.proto\x12\x1dgoogle.devtools.cloudbuild.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/httpbody.proto\x1a\x19google/api/resource.proto\x1a.google/devtools/cloudbuild/v2/cloudbuild.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xdd\x07\n\nConnection\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x05\x124\n\x0bcreate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12D\n\rgithub_config\x18\x05 \x01(\x0b2+.google.devtools.cloudbuild.v2.GitHubConfigH\x00\x12Y\n\x18github_enterprise_config\x18\x06 \x01(\x0b25.google.devtools.cloudbuild.v2.GitHubEnterpriseConfigH\x00\x12D\n\rgitlab_config\x18\x07 \x01(\x0b2+.google.devtools.cloudbuild.v2.GitLabConfigH\x00\x12`\n\x1cbitbucket_data_center_config\x18\x08 \x01(\x0b28.google.devtools.cloudbuild.v2.BitbucketDataCenterConfigH\x00\x12U\n\x16bitbucket_cloud_config\x18\t \x01(\x0b23.google.devtools.cloudbuild.v2.BitbucketCloudConfigH\x00\x12Q\n\x12installation_state\x18\x0c \x01(\x0b20.google.devtools.cloudbuild.v2.InstallationStateB\x03\xe0A\x03\x12\x10\n\x08disabled\x18\r \x01(\x08\x12\x18\n\x0breconciling\x18\x0e \x01(\x08B\x03\xe0A\x03\x12O\n\x0bannotations\x18\x0f \x03(\x0b2:.google.devtools.cloudbuild.v2.Connection.AnnotationsEntry\x12\x0c\n\x04etag\x18\x10 \x01(\t\x1a2\n\x10AnnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01:\x88\x01\xeaA\x84\x01\n$cloudbuild.googleapis.com/Connection\x12@projects/{project}/locations/{location}/connections/{connection}*\x0bconnections2\nconnectionR\x01\x01B\x13\n\x11connection_config"\x85\x02\n\x11InstallationState\x12J\n\x05stage\x18\x01 \x01(\x0e26.google.devtools.cloudbuild.v2.InstallationState.StageB\x03\xe0A\x03\x12\x14\n\x07message\x18\x02 \x01(\tB\x03\xe0A\x03\x12\x17\n\naction_uri\x18\x03 \x01(\tB\x03\xe0A\x03"u\n\x05Stage\x12\x15\n\x11STAGE_UNSPECIFIED\x10\x00\x12\x16\n\x12PENDING_CREATE_APP\x10\x01\x12\x16\n\x12PENDING_USER_OAUTH\x10\x02\x12\x17\n\x13PENDING_INSTALL_APP\x10\x03\x12\x0c\n\x08COMPLETE\x10\n"\x8b\x01\n FetchLinkableRepositoriesRequest\x12@\n\nconnection\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"}\n!FetchLinkableRepositoriesResponse\x12?\n\x0crepositories\x18\x01 \x03(\x0b2).google.devtools.cloudbuild.v2.Repository\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"z\n\x0cGitHubConfig\x12M\n\x15authorizer_credential\x18\x01 \x01(\x0b2..google.devtools.cloudbuild.v2.OAuthCredential\x12\x1b\n\x13app_installation_id\x18\x02 \x01(\x03"\xb7\x03\n\x16GitHubEnterpriseConfig\x12\x15\n\x08host_uri\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x14\n\x07api_key\x18\x0c \x01(\tB\x03\xe0A\x02\x12\x0e\n\x06app_id\x18\x02 \x01(\x03\x12\x10\n\x08app_slug\x18\r \x01(\t\x12S\n\x1aprivate_key_secret_version\x18\x04 \x01(\tB/\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12V\n\x1dwebhook_secret_secret_version\x18\x05 \x01(\tB/\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12\x1b\n\x13app_installation_id\x18\t \x01(\x03\x12W\n\x18service_directory_config\x18\n \x01(\x0b25.google.devtools.cloudbuild.v2.ServiceDirectoryConfig\x12\x0e\n\x06ssl_ca\x18\x0b \x01(\t\x12\x1b\n\x0eserver_version\x18\x0e \x01(\tB\x03\xe0A\x03"\xaf\x03\n\x0cGitLabConfig\x12\x10\n\x08host_uri\x18\x01 \x01(\t\x12\\\n\x1dwebhook_secret_secret_version\x18\x02 \x01(\tB5\xe0A\x02\xe0A\x05\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12V\n\x1aread_authorizer_credential\x18\x03 \x01(\x0b2-.google.devtools.cloudbuild.v2.UserCredentialB\x03\xe0A\x02\x12Q\n\x15authorizer_credential\x18\x04 \x01(\x0b2-.google.devtools.cloudbuild.v2.UserCredentialB\x03\xe0A\x02\x12W\n\x18service_directory_config\x18\x05 \x01(\x0b25.google.devtools.cloudbuild.v2.ServiceDirectoryConfig\x12\x0e\n\x06ssl_ca\x18\x06 \x01(\t\x12\x1b\n\x0eserver_version\x18\x07 \x01(\tB\x03\xe0A\x03"\xcb\x03\n\x19BitbucketDataCenterConfig\x12\x15\n\x08host_uri\x18\x01 \x01(\tB\x03\xe0A\x02\x12\\\n\x1dwebhook_secret_secret_version\x18\x02 \x01(\tB5\xe0A\x02\xe0A\x05\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12V\n\x1aread_authorizer_credential\x18\x03 \x01(\x0b2-.google.devtools.cloudbuild.v2.UserCredentialB\x03\xe0A\x02\x12Q\n\x15authorizer_credential\x18\x04 \x01(\x0b2-.google.devtools.cloudbuild.v2.UserCredentialB\x03\xe0A\x02\x12\\\n\x18service_directory_config\x18\x05 \x01(\x0b25.google.devtools.cloudbuild.v2.ServiceDirectoryConfigB\x03\xe0A\x01\x12\x13\n\x06ssl_ca\x18\x06 \x01(\tB\x03\xe0A\x01\x12\x1b\n\x0eserver_version\x18\x07 \x01(\tB\x03\xe0A\x03"\xb4\x02\n\x14BitbucketCloudConfig\x12\x16\n\tworkspace\x18\x01 \x01(\tB\x03\xe0A\x02\x12Y\n\x1dwebhook_secret_secret_version\x18\x02 \x01(\tB2\xe0A\x02\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12V\n\x1aread_authorizer_credential\x18\x03 \x01(\x0b2-.google.devtools.cloudbuild.v2.UserCredentialB\x03\xe0A\x02\x12Q\n\x15authorizer_credential\x18\x04 \x01(\x0b2-.google.devtools.cloudbuild.v2.UserCredentialB\x03\xe0A\x02"Z\n\x16ServiceDirectoryConfig\x12@\n\x07service\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'servicedirectory.googleapis.com/Service"\xf6\x03\n\nRepository\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x05\x12\x17\n\nremote_uri\x18\x02 \x01(\tB\x03\xe0A\x02\x124\n\x0bcreate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x05 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12O\n\x0bannotations\x18\x06 \x03(\x0b2:.google.devtools.cloudbuild.v2.Repository.AnnotationsEntry\x12\x0c\n\x04etag\x18\x07 \x01(\t\x12\x17\n\nwebhook_id\x18\x08 \x01(\tB\x03\xe0A\x03\x1a2\n\x10AnnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01:\xa3\x01\xeaA\x9f\x01\n$cloudbuild.googleapis.com/Repository\x12Zprojects/{project}/locations/{location}/connections/{connection}/repositories/{repository}*\x0crepositories2\nrepositoryR\x01\x01"}\n\x0fOAuthCredential\x12S\n\x1aoauth_token_secret_version\x18\x01 \x01(\tB/\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12\x15\n\x08username\x18\x02 \x01(\tB\x03\xe0A\x03"~\n\x0eUserCredential\x12U\n\x19user_token_secret_version\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12\x15\n\x08username\x18\x02 \x01(\tB\x03\xe0A\x03"\xb7\x01\n\x17CreateConnectionRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Connection\x12B\n\nconnection\x18\x02 \x01(\x0b2).google.devtools.cloudbuild.v2.ConnectionB\x03\xe0A\x02\x12\x1a\n\rconnection_id\x18\x03 \x01(\tB\x03\xe0A\x02"R\n\x14GetConnectionRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection"}\n\x16ListConnectionsRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Connection\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"r\n\x17ListConnectionsResponse\x12>\n\x0bconnections\x18\x01 \x03(\x0b2).google.devtools.cloudbuild.v2.Connection\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb3\x01\n\x17UpdateConnectionRequest\x12B\n\nconnection\x18\x01 \x01(\x0b2).google.devtools.cloudbuild.v2.ConnectionB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask\x12\x15\n\rallow_missing\x18\x03 \x01(\x08\x12\x0c\n\x04etag\x18\x04 \x01(\t"z\n\x17DeleteConnectionRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection\x12\x0c\n\x04etag\x18\x02 \x01(\t\x12\x15\n\rvalidate_only\x18\x03 \x01(\x08"\xb7\x01\n\x17CreateRepositoryRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection\x12B\n\nrepository\x18\x02 \x01(\x0b2).google.devtools.cloudbuild.v2.RepositoryB\x03\xe0A\x02\x12\x1a\n\rrepository_id\x18\x03 \x01(\tB\x03\xe0A\x02"\xad\x01\n\x1eBatchCreateRepositoriesRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection\x12M\n\x08requests\x18\x02 \x03(\x0b26.google.devtools.cloudbuild.v2.CreateRepositoryRequestB\x03\xe0A\x02"b\n\x1fBatchCreateRepositoriesResponse\x12?\n\x0crepositories\x18\x01 \x03(\x0b2).google.devtools.cloudbuild.v2.Repository"R\n\x14GetRepositoryRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository"\x8e\x01\n\x17ListRepositoriesRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Repository\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t"t\n\x18ListRepositoriesResponse\x12?\n\x0crepositories\x18\x01 \x03(\x0b2).google.devtools.cloudbuild.v2.Repository\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"z\n\x17DeleteRepositoryRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository\x12\x0c\n\x04etag\x18\x02 \x01(\t\x12\x15\n\rvalidate_only\x18\x03 \x01(\x08"^\n\x1aFetchReadWriteTokenRequest\x12@\n\nrepository\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository"Y\n\x15FetchReadTokenRequest\x12@\n\nrepository\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository"\\\n\x16FetchReadTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x123\n\x0fexpiration_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp"a\n\x1bFetchReadWriteTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x123\n\x0fexpiration_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp"\x8e\x01\n\x15ProcessWebhookRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Connection\x12"\n\x04body\x18\x02 \x01(\x0b2\x14.google.api.HttpBody\x12\x13\n\x0bwebhook_key\x18\x03 \x01(\t"\xdf\x01\n\x13FetchGitRefsRequest\x12@\n\nrepository\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository\x12L\n\x08ref_type\x18\x02 \x01(\x0e2:.google.devtools.cloudbuild.v2.FetchGitRefsRequest.RefType"8\n\x07RefType\x12\x18\n\x14REF_TYPE_UNSPECIFIED\x10\x00\x12\x07\n\x03TAG\x10\x01\x12\n\n\x06BRANCH\x10\x02")\n\x14FetchGitRefsResponse\x12\x11\n\tref_names\x18\x01 \x03(\t2\xc2\x1b\n\x11RepositoryManager\x12\x91\x02\n\x10CreateConnection\x126.google.devtools.cloudbuild.v2.CreateConnectionRequest\x1a\x1d.google.longrunning.Operation"\xa5\x01\xcaA=\n\nConnection\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x1fparent,connection,connection_id\x82\xd3\xe4\x93\x02="//v2/{parent=projects/*/locations/*}/connections:\nconnection\x12\xaf\x01\n\rGetConnection\x123.google.devtools.cloudbuild.v2.GetConnectionRequest\x1a).google.devtools.cloudbuild.v2.Connection">\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v2/{name=projects/*/locations/*/connections/*}\x12\xc2\x01\n\x0fListConnections\x125.google.devtools.cloudbuild.v2.ListConnectionsRequest\x1a6.google.devtools.cloudbuild.v2.ListConnectionsResponse"@\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v2/{parent=projects/*/locations/*}/connections\x12\x93\x02\n\x10UpdateConnection\x126.google.devtools.cloudbuild.v2.UpdateConnectionRequest\x1a\x1d.google.longrunning.Operation"\xa7\x01\xcaA=\n\nConnection\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x16connection,update_mask\x82\xd3\xe4\x93\x02H2:/v2/{connection.name=projects/*/locations/*/connections/*}:\nconnection\x12\xf5\x01\n\x10DeleteConnection\x126.google.devtools.cloudbuild.v2.DeleteConnectionRequest\x1a\x1d.google.longrunning.Operation"\x89\x01\xcaAH\n\x15google.protobuf.Empty\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x021*//v2/{name=projects/*/locations/*/connections/*}\x12\xa0\x02\n\x10CreateRepository\x126.google.devtools.cloudbuild.v2.CreateRepositoryRequest\x1a\x1d.google.longrunning.Operation"\xb4\x01\xcaA=\n\nRepository\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x1fparent,repository,repository_id\x82\xd3\xe4\x93\x02L">/v2/{parent=projects/*/locations/*/connections/*}/repositories:\nrepository\x12\xb6\x02\n\x17BatchCreateRepositories\x12=.google.devtools.cloudbuild.v2.BatchCreateRepositoriesRequest\x1a\x1d.google.longrunning.Operation"\xbc\x01\xcaAR\n\x1fBatchCreateRepositoriesResponse\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x0fparent,requests\x82\xd3\xe4\x93\x02O"J/v2/{parent=projects/*/locations/*/connections/*}/repositories:batchCreate:\x01*\x12\xbe\x01\n\rGetRepository\x123.google.devtools.cloudbuild.v2.GetRepositoryRequest\x1a).google.devtools.cloudbuild.v2.Repository"M\xdaA\x04name\x82\xd3\xe4\x93\x02@\x12>/v2/{name=projects/*/locations/*/connections/*/repositories/*}\x12\xd4\x01\n\x10ListRepositories\x126.google.devtools.cloudbuild.v2.ListRepositoriesRequest\x1a7.google.devtools.cloudbuild.v2.ListRepositoriesResponse"O\xdaA\x06parent\x82\xd3\xe4\x93\x02@\x12>/v2/{parent=projects/*/locations/*/connections/*}/repositories\x12\x84\x02\n\x10DeleteRepository\x126.google.devtools.cloudbuild.v2.DeleteRepositoryRequest\x1a\x1d.google.longrunning.Operation"\x98\x01\xcaAH\n\x15google.protobuf.Empty\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02@*>/v2/{name=projects/*/locations/*/connections/*/repositories/*}\x12\xff\x01\n\x13FetchReadWriteToken\x129.google.devtools.cloudbuild.v2.FetchReadWriteTokenRequest\x1a:.google.devtools.cloudbuild.v2.FetchReadWriteTokenResponse"q\xdaA\nrepository\x82\xd3\xe4\x93\x02^"Y/v2/{repository=projects/*/locations/*/connections/*/repositories/*}:accessReadWriteToken:\x01*\x12\xeb\x01\n\x0eFetchReadToken\x124.google.devtools.cloudbuild.v2.FetchReadTokenRequest\x1a5.google.devtools.cloudbuild.v2.FetchReadTokenResponse"l\xdaA\nrepository\x82\xd3\xe4\x93\x02Y"T/v2/{repository=projects/*/locations/*/connections/*/repositories/*}:accessReadToken:\x01*\x12\xf7\x01\n\x19FetchLinkableRepositories\x12?.google.devtools.cloudbuild.v2.FetchLinkableRepositoriesRequest\x1a@.google.devtools.cloudbuild.v2.FetchLinkableRepositoriesResponse"W\x82\xd3\xe4\x93\x02Q\x12O/v2/{connection=projects/*/locations/*/connections/*}:fetchLinkableRepositories\x12\xdf\x01\n\x0cFetchGitRefs\x122.google.devtools.cloudbuild.v2.FetchGitRefsRequest\x1a3.google.devtools.cloudbuild.v2.FetchGitRefsResponse"f\xdaA\nrepository\x82\xd3\xe4\x93\x02S\x12Q/v2/{repository=projects/*/locations/*/connections/*/repositories/*}:fetchGitRefs\x1aM\xcaA\x19cloudbuild.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xc9\x02\n\x18com.google.cloudbuild.v2B\x16RepositoryManagerProtoP\x01Z>cloud.google.com/go/cloudbuild/apiv2/cloudbuildpb;cloudbuildpb\xa2\x02\x03GCB\xaa\x02\x1aGoogle.Cloud.CloudBuild.V2\xca\x02\x15Google\\Cloud\\Build\\V2\xea\x02\x18Google::Cloud::Build::V2\xeaA|\n\'servicedirectory.googleapis.com/Service\x12Qprojects/{project}/locations/{location}/namespaces/{namespace}/services/{service}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.devtools.cloudbuild.v2.repositories_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b"\n\x18com.google.cloudbuild.v2B\x16RepositoryManagerProtoP\x01Z>cloud.google.com/go/cloudbuild/apiv2/cloudbuildpb;cloudbuildpb\xa2\x02\x03GCB\xaa\x02\x1aGoogle.Cloud.CloudBuild.V2\xca\x02\x15Google\\Cloud\\Build\\V2\xea\x02\x18Google::Cloud::Build::V2\xeaA|\n'servicedirectory.googleapis.com/Service\x12Qprojects/{project}/locations/{location}/namespaces/{namespace}/services/{service}"
    _globals['_CONNECTION_ANNOTATIONSENTRY']._loaded_options = None
    _globals['_CONNECTION_ANNOTATIONSENTRY']._serialized_options = b'8\x01'
    _globals['_CONNECTION'].fields_by_name['name']._loaded_options = None
    _globals['_CONNECTION'].fields_by_name['name']._serialized_options = b'\xe0A\x05'
    _globals['_CONNECTION'].fields_by_name['create_time']._loaded_options = None
    _globals['_CONNECTION'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_CONNECTION'].fields_by_name['update_time']._loaded_options = None
    _globals['_CONNECTION'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_CONNECTION'].fields_by_name['installation_state']._loaded_options = None
    _globals['_CONNECTION'].fields_by_name['installation_state']._serialized_options = b'\xe0A\x03'
    _globals['_CONNECTION'].fields_by_name['reconciling']._loaded_options = None
    _globals['_CONNECTION'].fields_by_name['reconciling']._serialized_options = b'\xe0A\x03'
    _globals['_CONNECTION']._loaded_options = None
    _globals['_CONNECTION']._serialized_options = b'\xeaA\x84\x01\n$cloudbuild.googleapis.com/Connection\x12@projects/{project}/locations/{location}/connections/{connection}*\x0bconnections2\nconnectionR\x01\x01'
    _globals['_INSTALLATIONSTATE'].fields_by_name['stage']._loaded_options = None
    _globals['_INSTALLATIONSTATE'].fields_by_name['stage']._serialized_options = b'\xe0A\x03'
    _globals['_INSTALLATIONSTATE'].fields_by_name['message']._loaded_options = None
    _globals['_INSTALLATIONSTATE'].fields_by_name['message']._serialized_options = b'\xe0A\x03'
    _globals['_INSTALLATIONSTATE'].fields_by_name['action_uri']._loaded_options = None
    _globals['_INSTALLATIONSTATE'].fields_by_name['action_uri']._serialized_options = b'\xe0A\x03'
    _globals['_FETCHLINKABLEREPOSITORIESREQUEST'].fields_by_name['connection']._loaded_options = None
    _globals['_FETCHLINKABLEREPOSITORIESREQUEST'].fields_by_name['connection']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection'
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['host_uri']._loaded_options = None
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['host_uri']._serialized_options = b'\xe0A\x02'
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['api_key']._loaded_options = None
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['api_key']._serialized_options = b'\xe0A\x02'
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['private_key_secret_version']._loaded_options = None
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['private_key_secret_version']._serialized_options = b'\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['webhook_secret_secret_version']._loaded_options = None
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['webhook_secret_secret_version']._serialized_options = b'\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['server_version']._loaded_options = None
    _globals['_GITHUBENTERPRISECONFIG'].fields_by_name['server_version']._serialized_options = b'\xe0A\x03'
    _globals['_GITLABCONFIG'].fields_by_name['webhook_secret_secret_version']._loaded_options = None
    _globals['_GITLABCONFIG'].fields_by_name['webhook_secret_secret_version']._serialized_options = b'\xe0A\x02\xe0A\x05\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_GITLABCONFIG'].fields_by_name['read_authorizer_credential']._loaded_options = None
    _globals['_GITLABCONFIG'].fields_by_name['read_authorizer_credential']._serialized_options = b'\xe0A\x02'
    _globals['_GITLABCONFIG'].fields_by_name['authorizer_credential']._loaded_options = None
    _globals['_GITLABCONFIG'].fields_by_name['authorizer_credential']._serialized_options = b'\xe0A\x02'
    _globals['_GITLABCONFIG'].fields_by_name['server_version']._loaded_options = None
    _globals['_GITLABCONFIG'].fields_by_name['server_version']._serialized_options = b'\xe0A\x03'
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['host_uri']._loaded_options = None
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['host_uri']._serialized_options = b'\xe0A\x02'
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['webhook_secret_secret_version']._loaded_options = None
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['webhook_secret_secret_version']._serialized_options = b'\xe0A\x02\xe0A\x05\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['read_authorizer_credential']._loaded_options = None
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['read_authorizer_credential']._serialized_options = b'\xe0A\x02'
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['authorizer_credential']._loaded_options = None
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['authorizer_credential']._serialized_options = b'\xe0A\x02'
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['service_directory_config']._loaded_options = None
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['service_directory_config']._serialized_options = b'\xe0A\x01'
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['ssl_ca']._loaded_options = None
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['ssl_ca']._serialized_options = b'\xe0A\x01'
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['server_version']._loaded_options = None
    _globals['_BITBUCKETDATACENTERCONFIG'].fields_by_name['server_version']._serialized_options = b'\xe0A\x03'
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['workspace']._loaded_options = None
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02'
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['webhook_secret_secret_version']._loaded_options = None
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['webhook_secret_secret_version']._serialized_options = b'\xe0A\x02\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['read_authorizer_credential']._loaded_options = None
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['read_authorizer_credential']._serialized_options = b'\xe0A\x02'
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['authorizer_credential']._loaded_options = None
    _globals['_BITBUCKETCLOUDCONFIG'].fields_by_name['authorizer_credential']._serialized_options = b'\xe0A\x02'
    _globals['_SERVICEDIRECTORYCONFIG'].fields_by_name['service']._loaded_options = None
    _globals['_SERVICEDIRECTORYCONFIG'].fields_by_name['service']._serialized_options = b"\xe0A\x02\xfaA)\n'servicedirectory.googleapis.com/Service"
    _globals['_REPOSITORY_ANNOTATIONSENTRY']._loaded_options = None
    _globals['_REPOSITORY_ANNOTATIONSENTRY']._serialized_options = b'8\x01'
    _globals['_REPOSITORY'].fields_by_name['name']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['name']._serialized_options = b'\xe0A\x05'
    _globals['_REPOSITORY'].fields_by_name['remote_uri']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['remote_uri']._serialized_options = b'\xe0A\x02'
    _globals['_REPOSITORY'].fields_by_name['create_time']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['update_time']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['webhook_id']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['webhook_id']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY']._loaded_options = None
    _globals['_REPOSITORY']._serialized_options = b'\xeaA\x9f\x01\n$cloudbuild.googleapis.com/Repository\x12Zprojects/{project}/locations/{location}/connections/{connection}/repositories/{repository}*\x0crepositories2\nrepositoryR\x01\x01'
    _globals['_OAUTHCREDENTIAL'].fields_by_name['oauth_token_secret_version']._loaded_options = None
    _globals['_OAUTHCREDENTIAL'].fields_by_name['oauth_token_secret_version']._serialized_options = b'\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_OAUTHCREDENTIAL'].fields_by_name['username']._loaded_options = None
    _globals['_OAUTHCREDENTIAL'].fields_by_name['username']._serialized_options = b'\xe0A\x03'
    _globals['_USERCREDENTIAL'].fields_by_name['user_token_secret_version']._loaded_options = None
    _globals['_USERCREDENTIAL'].fields_by_name['user_token_secret_version']._serialized_options = b'\xe0A\x02\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_USERCREDENTIAL'].fields_by_name['username']._loaded_options = None
    _globals['_USERCREDENTIAL'].fields_by_name['username']._serialized_options = b'\xe0A\x03'
    _globals['_CREATECONNECTIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECONNECTIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Connection'
    _globals['_CREATECONNECTIONREQUEST'].fields_by_name['connection']._loaded_options = None
    _globals['_CREATECONNECTIONREQUEST'].fields_by_name['connection']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECONNECTIONREQUEST'].fields_by_name['connection_id']._loaded_options = None
    _globals['_CREATECONNECTIONREQUEST'].fields_by_name['connection_id']._serialized_options = b'\xe0A\x02'
    _globals['_GETCONNECTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCONNECTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection'
    _globals['_LISTCONNECTIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCONNECTIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Connection'
    _globals['_UPDATECONNECTIONREQUEST'].fields_by_name['connection']._loaded_options = None
    _globals['_UPDATECONNECTIONREQUEST'].fields_by_name['connection']._serialized_options = b'\xe0A\x02'
    _globals['_DELETECONNECTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECONNECTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository_id']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository_id']._serialized_options = b'\xe0A\x02'
    _globals['_BATCHCREATEREPOSITORIESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_BATCHCREATEREPOSITORIESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Connection'
    _globals['_BATCHCREATEREPOSITORIESREQUEST'].fields_by_name['requests']._loaded_options = None
    _globals['_BATCHCREATEREPOSITORIESREQUEST'].fields_by_name['requests']._serialized_options = b'\xe0A\x02'
    _globals['_GETREPOSITORYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETREPOSITORYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Repository'
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository'
    _globals['_FETCHREADWRITETOKENREQUEST'].fields_by_name['repository']._loaded_options = None
    _globals['_FETCHREADWRITETOKENREQUEST'].fields_by_name['repository']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository'
    _globals['_FETCHREADTOKENREQUEST'].fields_by_name['repository']._loaded_options = None
    _globals['_FETCHREADTOKENREQUEST'].fields_by_name['repository']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository'
    _globals['_PROCESSWEBHOOKREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_PROCESSWEBHOOKREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$cloudbuild.googleapis.com/Connection'
    _globals['_FETCHGITREFSREQUEST'].fields_by_name['repository']._loaded_options = None
    _globals['_FETCHGITREFSREQUEST'].fields_by_name['repository']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudbuild.googleapis.com/Repository'
    _globals['_REPOSITORYMANAGER']._loaded_options = None
    _globals['_REPOSITORYMANAGER']._serialized_options = b'\xcaA\x19cloudbuild.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_REPOSITORYMANAGER'].methods_by_name['CreateConnection']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['CreateConnection']._serialized_options = b'\xcaA=\n\nConnection\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x1fparent,connection,connection_id\x82\xd3\xe4\x93\x02="//v2/{parent=projects/*/locations/*}/connections:\nconnection'
    _globals['_REPOSITORYMANAGER'].methods_by_name['GetConnection']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['GetConnection']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v2/{name=projects/*/locations/*/connections/*}'
    _globals['_REPOSITORYMANAGER'].methods_by_name['ListConnections']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['ListConnections']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v2/{parent=projects/*/locations/*}/connections'
    _globals['_REPOSITORYMANAGER'].methods_by_name['UpdateConnection']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['UpdateConnection']._serialized_options = b'\xcaA=\n\nConnection\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x16connection,update_mask\x82\xd3\xe4\x93\x02H2:/v2/{connection.name=projects/*/locations/*/connections/*}:\nconnection'
    _globals['_REPOSITORYMANAGER'].methods_by_name['DeleteConnection']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['DeleteConnection']._serialized_options = b'\xcaAH\n\x15google.protobuf.Empty\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x021*//v2/{name=projects/*/locations/*/connections/*}'
    _globals['_REPOSITORYMANAGER'].methods_by_name['CreateRepository']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['CreateRepository']._serialized_options = b'\xcaA=\n\nRepository\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x1fparent,repository,repository_id\x82\xd3\xe4\x93\x02L">/v2/{parent=projects/*/locations/*/connections/*}/repositories:\nrepository'
    _globals['_REPOSITORYMANAGER'].methods_by_name['BatchCreateRepositories']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['BatchCreateRepositories']._serialized_options = b'\xcaAR\n\x1fBatchCreateRepositoriesResponse\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x0fparent,requests\x82\xd3\xe4\x93\x02O"J/v2/{parent=projects/*/locations/*/connections/*}/repositories:batchCreate:\x01*'
    _globals['_REPOSITORYMANAGER'].methods_by_name['GetRepository']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['GetRepository']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02@\x12>/v2/{name=projects/*/locations/*/connections/*/repositories/*}'
    _globals['_REPOSITORYMANAGER'].methods_by_name['ListRepositories']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['ListRepositories']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02@\x12>/v2/{parent=projects/*/locations/*/connections/*}/repositories'
    _globals['_REPOSITORYMANAGER'].methods_by_name['DeleteRepository']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['DeleteRepository']._serialized_options = b'\xcaAH\n\x15google.protobuf.Empty\x12/google.devtools.cloudbuild.v2.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02@*>/v2/{name=projects/*/locations/*/connections/*/repositories/*}'
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchReadWriteToken']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchReadWriteToken']._serialized_options = b'\xdaA\nrepository\x82\xd3\xe4\x93\x02^"Y/v2/{repository=projects/*/locations/*/connections/*/repositories/*}:accessReadWriteToken:\x01*'
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchReadToken']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchReadToken']._serialized_options = b'\xdaA\nrepository\x82\xd3\xe4\x93\x02Y"T/v2/{repository=projects/*/locations/*/connections/*/repositories/*}:accessReadToken:\x01*'
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchLinkableRepositories']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchLinkableRepositories']._serialized_options = b'\x82\xd3\xe4\x93\x02Q\x12O/v2/{connection=projects/*/locations/*/connections/*}:fetchLinkableRepositories'
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchGitRefs']._loaded_options = None
    _globals['_REPOSITORYMANAGER'].methods_by_name['FetchGitRefs']._serialized_options = b'\xdaA\nrepository\x82\xd3\xe4\x93\x02S\x12Q/v2/{repository=projects/*/locations/*/connections/*/repositories/*}:fetchGitRefs'
    _globals['_CONNECTION']._serialized_start = 407
    _globals['_CONNECTION']._serialized_end = 1396
    _globals['_CONNECTION_ANNOTATIONSENTRY']._serialized_start = 1186
    _globals['_CONNECTION_ANNOTATIONSENTRY']._serialized_end = 1236
    _globals['_INSTALLATIONSTATE']._serialized_start = 1399
    _globals['_INSTALLATIONSTATE']._serialized_end = 1660
    _globals['_INSTALLATIONSTATE_STAGE']._serialized_start = 1543
    _globals['_INSTALLATIONSTATE_STAGE']._serialized_end = 1660
    _globals['_FETCHLINKABLEREPOSITORIESREQUEST']._serialized_start = 1663
    _globals['_FETCHLINKABLEREPOSITORIESREQUEST']._serialized_end = 1802
    _globals['_FETCHLINKABLEREPOSITORIESRESPONSE']._serialized_start = 1804
    _globals['_FETCHLINKABLEREPOSITORIESRESPONSE']._serialized_end = 1929
    _globals['_GITHUBCONFIG']._serialized_start = 1931
    _globals['_GITHUBCONFIG']._serialized_end = 2053
    _globals['_GITHUBENTERPRISECONFIG']._serialized_start = 2056
    _globals['_GITHUBENTERPRISECONFIG']._serialized_end = 2495
    _globals['_GITLABCONFIG']._serialized_start = 2498
    _globals['_GITLABCONFIG']._serialized_end = 2929
    _globals['_BITBUCKETDATACENTERCONFIG']._serialized_start = 2932
    _globals['_BITBUCKETDATACENTERCONFIG']._serialized_end = 3391
    _globals['_BITBUCKETCLOUDCONFIG']._serialized_start = 3394
    _globals['_BITBUCKETCLOUDCONFIG']._serialized_end = 3702
    _globals['_SERVICEDIRECTORYCONFIG']._serialized_start = 3704
    _globals['_SERVICEDIRECTORYCONFIG']._serialized_end = 3794
    _globals['_REPOSITORY']._serialized_start = 3797
    _globals['_REPOSITORY']._serialized_end = 4299
    _globals['_REPOSITORY_ANNOTATIONSENTRY']._serialized_start = 1186
    _globals['_REPOSITORY_ANNOTATIONSENTRY']._serialized_end = 1236
    _globals['_OAUTHCREDENTIAL']._serialized_start = 4301
    _globals['_OAUTHCREDENTIAL']._serialized_end = 4426
    _globals['_USERCREDENTIAL']._serialized_start = 4428
    _globals['_USERCREDENTIAL']._serialized_end = 4554
    _globals['_CREATECONNECTIONREQUEST']._serialized_start = 4557
    _globals['_CREATECONNECTIONREQUEST']._serialized_end = 4740
    _globals['_GETCONNECTIONREQUEST']._serialized_start = 4742
    _globals['_GETCONNECTIONREQUEST']._serialized_end = 4824
    _globals['_LISTCONNECTIONSREQUEST']._serialized_start = 4826
    _globals['_LISTCONNECTIONSREQUEST']._serialized_end = 4951
    _globals['_LISTCONNECTIONSRESPONSE']._serialized_start = 4953
    _globals['_LISTCONNECTIONSRESPONSE']._serialized_end = 5067
    _globals['_UPDATECONNECTIONREQUEST']._serialized_start = 5070
    _globals['_UPDATECONNECTIONREQUEST']._serialized_end = 5249
    _globals['_DELETECONNECTIONREQUEST']._serialized_start = 5251
    _globals['_DELETECONNECTIONREQUEST']._serialized_end = 5373
    _globals['_CREATEREPOSITORYREQUEST']._serialized_start = 5376
    _globals['_CREATEREPOSITORYREQUEST']._serialized_end = 5559
    _globals['_BATCHCREATEREPOSITORIESREQUEST']._serialized_start = 5562
    _globals['_BATCHCREATEREPOSITORIESREQUEST']._serialized_end = 5735
    _globals['_BATCHCREATEREPOSITORIESRESPONSE']._serialized_start = 5737
    _globals['_BATCHCREATEREPOSITORIESRESPONSE']._serialized_end = 5835
    _globals['_GETREPOSITORYREQUEST']._serialized_start = 5837
    _globals['_GETREPOSITORYREQUEST']._serialized_end = 5919
    _globals['_LISTREPOSITORIESREQUEST']._serialized_start = 5922
    _globals['_LISTREPOSITORIESREQUEST']._serialized_end = 6064
    _globals['_LISTREPOSITORIESRESPONSE']._serialized_start = 6066
    _globals['_LISTREPOSITORIESRESPONSE']._serialized_end = 6182
    _globals['_DELETEREPOSITORYREQUEST']._serialized_start = 6184
    _globals['_DELETEREPOSITORYREQUEST']._serialized_end = 6306
    _globals['_FETCHREADWRITETOKENREQUEST']._serialized_start = 6308
    _globals['_FETCHREADWRITETOKENREQUEST']._serialized_end = 6402
    _globals['_FETCHREADTOKENREQUEST']._serialized_start = 6404
    _globals['_FETCHREADTOKENREQUEST']._serialized_end = 6493
    _globals['_FETCHREADTOKENRESPONSE']._serialized_start = 6495
    _globals['_FETCHREADTOKENRESPONSE']._serialized_end = 6587
    _globals['_FETCHREADWRITETOKENRESPONSE']._serialized_start = 6589
    _globals['_FETCHREADWRITETOKENRESPONSE']._serialized_end = 6686
    _globals['_PROCESSWEBHOOKREQUEST']._serialized_start = 6689
    _globals['_PROCESSWEBHOOKREQUEST']._serialized_end = 6831
    _globals['_FETCHGITREFSREQUEST']._serialized_start = 6834
    _globals['_FETCHGITREFSREQUEST']._serialized_end = 7057
    _globals['_FETCHGITREFSREQUEST_REFTYPE']._serialized_start = 7001
    _globals['_FETCHGITREFSREQUEST_REFTYPE']._serialized_end = 7057
    _globals['_FETCHGITREFSRESPONSE']._serialized_start = 7059
    _globals['_FETCHGITREFSRESPONSE']._serialized_end = 7100
    _globals['_REPOSITORYMANAGER']._serialized_start = 7103
    _globals['_REPOSITORYMANAGER']._serialized_end = 10625