"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/redis/v1/cloud_redis.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .....google.type import dayofweek_pb2 as google_dot_type_dot_dayofweek__pb2
from .....google.type import timeofday_pb2 as google_dot_type_dot_timeofday__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'google/cloud/redis/v1/cloud_redis.proto\x12\x15google.cloud.redis.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a#google/longrunning/operations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/type/dayofweek.proto\x1a\x1bgoogle/type/timeofday.proto".\n\x08NodeInfo\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04zone\x18\x02 \x01(\tB\x03\xe0A\x03"\x85\x13\n\x08Instance\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x14\n\x0cdisplay_name\x18\x02 \x01(\t\x12;\n\x06labels\x18\x03 \x03(\x0b2+.google.cloud.redis.v1.Instance.LabelsEntry\x12\x18\n\x0blocation_id\x18\x04 \x01(\tB\x03\xe0A\x01\x12$\n\x17alternative_location_id\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rredis_version\x18\x07 \x01(\tB\x03\xe0A\x01\x12\x1e\n\x11reserved_ip_range\x18\t \x01(\tB\x03\xe0A\x01\x12\x1f\n\x12secondary_ip_range\x18\x1e \x01(\tB\x03\xe0A\x01\x12\x11\n\x04host\x18\n \x01(\tB\x03\xe0A\x03\x12\x11\n\x04port\x18\x0b \x01(\x05B\x03\xe0A\x03\x12 \n\x13current_location_id\x18\x0c \x01(\tB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\r \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x129\n\x05state\x18\x0e \x01(\x0e2%.google.cloud.redis.v1.Instance.StateB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x0f \x01(\tB\x03\xe0A\x03\x12M\n\rredis_configs\x18\x10 \x03(\x0b21.google.cloud.redis.v1.Instance.RedisConfigsEntryB\x03\xe0A\x01\x127\n\x04tier\x18\x11 \x01(\x0e2$.google.cloud.redis.v1.Instance.TierB\x03\xe0A\x02\x12\x1b\n\x0ememory_size_gb\x18\x12 \x01(\x05B\x03\xe0A\x02\x12\x1f\n\x12authorized_network\x18\x14 \x01(\tB\x03\xe0A\x01\x12%\n\x18persistence_iam_identity\x18\x15 \x01(\tB\x03\xe0A\x03\x12F\n\x0cconnect_mode\x18\x16 \x01(\x0e2+.google.cloud.redis.v1.Instance.ConnectModeB\x03\xe0A\x01\x12\x19\n\x0cauth_enabled\x18\x17 \x01(\x08B\x03\xe0A\x01\x12C\n\x0fserver_ca_certs\x18\x19 \x03(\x0b2%.google.cloud.redis.v1.TlsCertificateB\x03\xe0A\x03\x12[\n\x17transit_encryption_mode\x18\x1a \x01(\x0e25.google.cloud.redis.v1.Instance.TransitEncryptionModeB\x03\xe0A\x01\x12I\n\x12maintenance_policy\x18\x1b \x01(\x0b2(.google.cloud.redis.v1.MaintenancePolicyB\x03\xe0A\x01\x12M\n\x14maintenance_schedule\x18\x1c \x01(\x0b2*.google.cloud.redis.v1.MaintenanceScheduleB\x03\xe0A\x03\x12\x1a\n\rreplica_count\x18\x1f \x01(\x05B\x03\xe0A\x01\x123\n\x05nodes\x18  \x03(\x0b2\x1f.google.cloud.redis.v1.NodeInfoB\x03\xe0A\x03\x12\x1a\n\rread_endpoint\x18! \x01(\tB\x03\xe0A\x03\x12\x1f\n\x12read_endpoint_port\x18" \x01(\x05B\x03\xe0A\x03\x12Q\n\x12read_replicas_mode\x18# \x01(\x0e20.google.cloud.redis.v1.Instance.ReadReplicasModeB\x03\xe0A\x01\x12!\n\x14customer_managed_key\x18$ \x01(\tB\x03\xe0A\x01\x12I\n\x12persistence_config\x18% \x01(\x0b2(.google.cloud.redis.v1.PersistenceConfigB\x03\xe0A\x01\x12Q\n\x12suspension_reasons\x18& \x03(\x0e20.google.cloud.redis.v1.Instance.SuspensionReasonB\x03\xe0A\x01\x12 \n\x13maintenance_version\x18\' \x01(\tB\x03\xe0A\x01\x12+\n\x1eavailable_maintenance_versions\x18( \x03(\tB\x03\xe0A\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01\x1a3\n\x11RedisConfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\x94\x01\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08UPDATING\x10\x03\x12\x0c\n\x08DELETING\x10\x04\x12\r\n\tREPAIRING\x10\x05\x12\x0f\n\x0bMAINTENANCE\x10\x06\x12\r\n\tIMPORTING\x10\x08\x12\x10\n\x0cFAILING_OVER\x10\t"8\n\x04Tier\x12\x14\n\x10TIER_UNSPECIFIED\x10\x00\x12\t\n\x05BASIC\x10\x01\x12\x0f\n\x0bSTANDARD_HA\x10\x03"[\n\x0bConnectMode\x12\x1c\n\x18CONNECT_MODE_UNSPECIFIED\x10\x00\x12\x12\n\x0eDIRECT_PEERING\x10\x01\x12\x1a\n\x16PRIVATE_SERVICE_ACCESS\x10\x02"i\n\x15TransitEncryptionMode\x12\'\n#TRANSIT_ENCRYPTION_MODE_UNSPECIFIED\x10\x00\x12\x19\n\x15SERVER_AUTHENTICATION\x10\x01\x12\x0c\n\x08DISABLED\x10\x02"m\n\x10ReadReplicasMode\x12"\n\x1eREAD_REPLICAS_MODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16READ_REPLICAS_DISABLED\x10\x01\x12\x19\n\x15READ_REPLICAS_ENABLED\x10\x02"U\n\x10SuspensionReason\x12!\n\x1dSUSPENSION_REASON_UNSPECIFIED\x10\x00\x12\x1e\n\x1aCUSTOMER_MANAGED_KEY_ISSUE\x10\x01:`\xeaA]\n\x1dredis.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}"\x8f\x04\n\x11PersistenceConfig\x12W\n\x10persistence_mode\x18\x01 \x01(\x0e28.google.cloud.redis.v1.PersistenceConfig.PersistenceModeB\x03\xe0A\x01\x12Y\n\x13rdb_snapshot_period\x18\x02 \x01(\x0e27.google.cloud.redis.v1.PersistenceConfig.SnapshotPeriodB\x03\xe0A\x01\x12?\n\x16rdb_next_snapshot_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12@\n\x17rdb_snapshot_start_time\x18\x05 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x01"J\n\x0fPersistenceMode\x12 \n\x1cPERSISTENCE_MODE_UNSPECIFIED\x10\x00\x12\x0c\n\x08DISABLED\x10\x01\x12\x07\n\x03RDB\x10\x02"w\n\x0eSnapshotPeriod\x12\x1f\n\x1bSNAPSHOT_PERIOD_UNSPECIFIED\x10\x00\x12\x0c\n\x08ONE_HOUR\x10\x03\x12\r\n\tSIX_HOURS\x10\x04\x12\x10\n\x0cTWELVE_HOURS\x10\x05\x12\x15\n\x11TWENTY_FOUR_HOURS\x10\x06"\xdd\x02\n\x1cRescheduleMaintenanceRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance\x12`\n\x0freschedule_type\x18\x02 \x01(\x0e2B.google.cloud.redis.v1.RescheduleMaintenanceRequest.RescheduleTypeB\x03\xe0A\x02\x126\n\rschedule_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x01"n\n\x0eRescheduleType\x12\x1f\n\x1bRESCHEDULE_TYPE_UNSPECIFIED\x10\x00\x12\r\n\tIMMEDIATE\x10\x01\x12\x19\n\x15NEXT_AVAILABLE_WINDOW\x10\x02\x12\x11\n\rSPECIFIC_TIME\x10\x03"\xf1\x01\n\x11MaintenancePolicy\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x18\n\x0bdescription\x18\x03 \x01(\tB\x03\xe0A\x01\x12V\n\x19weekly_maintenance_window\x18\x04 \x03(\x0b2..google.cloud.redis.v1.WeeklyMaintenanceWindowB\x03\xe0A\x01"\xa6\x01\n\x17WeeklyMaintenanceWindow\x12(\n\x03day\x18\x01 \x01(\x0e2\x16.google.type.DayOfWeekB\x03\xe0A\x02\x12/\n\nstart_time\x18\x02 \x01(\x0b2\x16.google.type.TimeOfDayB\x03\xe0A\x02\x120\n\x08duration\x18\x03 \x01(\x0b2\x19.google.protobuf.DurationB\x03\xe0A\x03"\xda\x01\n\x13MaintenanceSchedule\x123\n\nstart_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x1a\n\x0ecan_reschedule\x18\x03 \x01(\x08B\x02\x18\x01\x12?\n\x16schedule_deadline_time\x18\x05 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03"x\n\x14ListInstancesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"y\n\x15ListInstancesResponse\x122\n\tinstances\x18\x01 \x03(\x0b2\x1f.google.cloud.redis.v1.Instance\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"I\n\x12GetInstanceRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance"S\n\x1cGetInstanceAuthStringRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance")\n\x12InstanceAuthString\x12\x13\n\x0bauth_string\x18\x01 \x01(\t"\xa4\x01\n\x15CreateInstanceRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x18\n\x0binstance_id\x18\x02 \x01(\tB\x03\xe0A\x02\x126\n\x08instance\x18\x03 \x01(\x0b2\x1f.google.cloud.redis.v1.InstanceB\x03\xe0A\x02"\x85\x01\n\x15UpdateInstanceRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x126\n\x08instance\x18\x02 \x01(\x0b2\x1f.google.cloud.redis.v1.InstanceB\x03\xe0A\x02"i\n\x16UpgradeInstanceRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance\x12\x1a\n\rredis_version\x18\x02 \x01(\tB\x03\xe0A\x02"L\n\x15DeleteInstanceRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance"\x1d\n\tGcsSource\x12\x10\n\x03uri\x18\x01 \x01(\tB\x03\xe0A\x02"O\n\x0bInputConfig\x126\n\ngcs_source\x18\x01 \x01(\x0b2 .google.cloud.redis.v1.GcsSourceH\x00B\x08\n\x06source"i\n\x15ImportInstanceRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12=\n\x0cinput_config\x18\x03 \x01(\x0b2".google.cloud.redis.v1.InputConfigB\x03\xe0A\x02""\n\x0eGcsDestination\x12\x10\n\x03uri\x18\x01 \x01(\tB\x03\xe0A\x02"_\n\x0cOutputConfig\x12@\n\x0fgcs_destination\x18\x01 \x01(\x0b2%.google.cloud.redis.v1.GcsDestinationH\x00B\r\n\x0bdestination"k\n\x15ExportInstanceRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12?\n\routput_config\x18\x03 \x01(\x0b2#.google.cloud.redis.v1.OutputConfigB\x03\xe0A\x02"\x9c\x02\n\x17FailoverInstanceRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance\x12d\n\x14data_protection_mode\x18\x02 \x01(\x0e2A.google.cloud.redis.v1.FailoverInstanceRequest.DataProtectionModeB\x03\xe0A\x01"f\n\x12DataProtectionMode\x12$\n DATA_PROTECTION_MODE_UNSPECIFIED\x10\x00\x12\x15\n\x11LIMITED_DATA_LOSS\x10\x01\x12\x13\n\x0fFORCE_DATA_LOSS\x10\x02"\xd6\x01\n\x11OperationMetadata\x12/\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0c\n\x04verb\x18\x04 \x01(\t\x12\x15\n\rstatus_detail\x18\x05 \x01(\t\x12\x18\n\x10cancel_requested\x18\x06 \x01(\x08\x12\x13\n\x0bapi_version\x18\x07 \x01(\t"\xc9\x01\n\x10LocationMetadata\x12Y\n\x0favailable_zones\x18\x01 \x03(\x0b2;.google.cloud.redis.v1.LocationMetadata.AvailableZonesEntryB\x03\xe0A\x03\x1aZ\n\x13AvailableZonesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x122\n\x05value\x18\x02 \x01(\x0b2#.google.cloud.redis.v1.ZoneMetadata:\x028\x01"\x0e\n\x0cZoneMetadata"\xbb\x01\n\x0eTlsCertificate\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x0c\n\x04cert\x18\x02 \x01(\t\x124\n\x0bcreate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bexpire_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x18\n\x10sha1_fingerprint\x18\x05 \x01(\t2\xa8\x15\n\nCloudRedis\x12\xaa\x01\n\rListInstances\x12+.google.cloud.redis.v1.ListInstancesRequest\x1a,.google.cloud.redis.v1.ListInstancesResponse">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/instances\x12\x97\x01\n\x0bGetInstance\x12).google.cloud.redis.v1.GetInstanceRequest\x1a\x1f.google.cloud.redis.v1.Instance"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/instances/*}\x12\xc0\x01\n\x15GetInstanceAuthString\x123.google.cloud.redis.v1.GetInstanceAuthStringRequest\x1a).google.cloud.redis.v1.InstanceAuthString"G\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/instances/*}/authString\x12\x89\x02\n\x0eCreateInstance\x12,.google.cloud.redis.v1.CreateInstanceRequest\x1a\x1d.google.longrunning.Operation"\xa9\x01\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x1bparent,instance_id,instance\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/instances:\x08instance\x12\x8b\x02\n\x0eUpdateInstance\x12,.google.cloud.redis.v1.UpdateInstanceRequest\x1a\x1d.google.longrunning.Operation"\xab\x01\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x14update_mask,instance\x82\xd3\xe4\x93\x02B26/v1/{instance.name=projects/*/locations/*/instances/*}:\x08instance\x12\x83\x02\n\x0fUpgradeInstance\x12-.google.cloud.redis.v1.UpgradeInstanceRequest\x1a\x1d.google.longrunning.Operation"\xa1\x01\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x12name,redis_version\x82\xd3\xe4\x93\x02:"5/v1/{name=projects/*/locations/*/instances/*}:upgrade:\x01*\x12\xff\x01\n\x0eImportInstance\x12,.google.cloud.redis.v1.ImportInstanceRequest\x1a\x1d.google.longrunning.Operation"\x9f\x01\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x11name,input_config\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/instances/*}:import:\x01*\x12\x80\x02\n\x0eExportInstance\x12,.google.cloud.redis.v1.ExportInstanceRequest\x1a\x1d.google.longrunning.Operation"\xa0\x01\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x12name,output_config\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/instances/*}:export:\x01*\x12\x8d\x02\n\x10FailoverInstance\x12..google.cloud.redis.v1.FailoverInstanceRequest\x1a\x1d.google.longrunning.Operation"\xa9\x01\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x19name,data_protection_mode\x82\xd3\xe4\x93\x02;"6/v1/{name=projects/*/locations/*/instances/*}:failover:\x01*\x12\xde\x01\n\x0eDeleteInstance\x12,.google.cloud.redis.v1.DeleteInstanceRequest\x1a\x1d.google.longrunning.Operation"\x7f\xcaA@\n\x15google.protobuf.Empty\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/instances/*}\x12\xaf\x02\n\x15RescheduleMaintenance\x123.google.cloud.redis.v1.RescheduleMaintenanceRequest\x1a\x1d.google.longrunning.Operation"\xc1\x01\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA$name, reschedule_type, schedule_time\x82\xd3\xe4\x93\x02H"C/v1/{name=projects/*/locations/*/instances/*}:rescheduleMaintenance:\x01*\x1aH\xcaA\x14redis.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformBh\n\x19com.google.cloud.redis.v1B\x18CloudRedisServiceV1ProtoP\x01Z/cloud.google.com/go/redis/apiv1/redispb;redispbb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.redis.v1.cloud_redis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x19com.google.cloud.redis.v1B\x18CloudRedisServiceV1ProtoP\x01Z/cloud.google.com/go/redis/apiv1/redispb;redispb'
    _globals['_NODEINFO'].fields_by_name['id']._loaded_options = None
    _globals['_NODEINFO'].fields_by_name['id']._serialized_options = b'\xe0A\x03'
    _globals['_NODEINFO'].fields_by_name['zone']._loaded_options = None
    _globals['_NODEINFO'].fields_by_name['zone']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE_LABELSENTRY']._loaded_options = None
    _globals['_INSTANCE_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_INSTANCE_REDISCONFIGSENTRY']._loaded_options = None
    _globals['_INSTANCE_REDISCONFIGSENTRY']._serialized_options = b'8\x01'
    _globals['_INSTANCE'].fields_by_name['name']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_INSTANCE'].fields_by_name['location_id']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['location_id']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['alternative_location_id']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['alternative_location_id']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['redis_version']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['redis_version']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['reserved_ip_range']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['reserved_ip_range']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['secondary_ip_range']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['secondary_ip_range']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['host']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['host']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['port']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['port']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['current_location_id']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['current_location_id']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['create_time']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['state']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['status_message']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['redis_configs']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['redis_configs']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['tier']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['tier']._serialized_options = b'\xe0A\x02'
    _globals['_INSTANCE'].fields_by_name['memory_size_gb']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['memory_size_gb']._serialized_options = b'\xe0A\x02'
    _globals['_INSTANCE'].fields_by_name['authorized_network']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['authorized_network']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['persistence_iam_identity']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['persistence_iam_identity']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['connect_mode']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['connect_mode']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['auth_enabled']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['auth_enabled']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['server_ca_certs']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['server_ca_certs']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['transit_encryption_mode']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['transit_encryption_mode']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['maintenance_policy']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['maintenance_policy']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['maintenance_schedule']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['maintenance_schedule']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['replica_count']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['replica_count']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['nodes']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['nodes']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['read_endpoint']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['read_endpoint']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['read_endpoint_port']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['read_endpoint_port']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['read_replicas_mode']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['read_replicas_mode']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['customer_managed_key']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['customer_managed_key']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['persistence_config']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['persistence_config']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['suspension_reasons']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['suspension_reasons']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['maintenance_version']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['maintenance_version']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['available_maintenance_versions']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['available_maintenance_versions']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE']._loaded_options = None
    _globals['_INSTANCE']._serialized_options = b'\xeaA]\n\x1dredis.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}'
    _globals['_PERSISTENCECONFIG'].fields_by_name['persistence_mode']._loaded_options = None
    _globals['_PERSISTENCECONFIG'].fields_by_name['persistence_mode']._serialized_options = b'\xe0A\x01'
    _globals['_PERSISTENCECONFIG'].fields_by_name['rdb_snapshot_period']._loaded_options = None
    _globals['_PERSISTENCECONFIG'].fields_by_name['rdb_snapshot_period']._serialized_options = b'\xe0A\x01'
    _globals['_PERSISTENCECONFIG'].fields_by_name['rdb_next_snapshot_time']._loaded_options = None
    _globals['_PERSISTENCECONFIG'].fields_by_name['rdb_next_snapshot_time']._serialized_options = b'\xe0A\x03'
    _globals['_PERSISTENCECONFIG'].fields_by_name['rdb_snapshot_start_time']._loaded_options = None
    _globals['_PERSISTENCECONFIG'].fields_by_name['rdb_snapshot_start_time']._serialized_options = b'\xe0A\x01'
    _globals['_RESCHEDULEMAINTENANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESCHEDULEMAINTENANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance'
    _globals['_RESCHEDULEMAINTENANCEREQUEST'].fields_by_name['reschedule_type']._loaded_options = None
    _globals['_RESCHEDULEMAINTENANCEREQUEST'].fields_by_name['reschedule_type']._serialized_options = b'\xe0A\x02'
    _globals['_RESCHEDULEMAINTENANCEREQUEST'].fields_by_name['schedule_time']._loaded_options = None
    _globals['_RESCHEDULEMAINTENANCEREQUEST'].fields_by_name['schedule_time']._serialized_options = b'\xe0A\x01'
    _globals['_MAINTENANCEPOLICY'].fields_by_name['create_time']._loaded_options = None
    _globals['_MAINTENANCEPOLICY'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_MAINTENANCEPOLICY'].fields_by_name['update_time']._loaded_options = None
    _globals['_MAINTENANCEPOLICY'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_MAINTENANCEPOLICY'].fields_by_name['description']._loaded_options = None
    _globals['_MAINTENANCEPOLICY'].fields_by_name['description']._serialized_options = b'\xe0A\x01'
    _globals['_MAINTENANCEPOLICY'].fields_by_name['weekly_maintenance_window']._loaded_options = None
    _globals['_MAINTENANCEPOLICY'].fields_by_name['weekly_maintenance_window']._serialized_options = b'\xe0A\x01'
    _globals['_WEEKLYMAINTENANCEWINDOW'].fields_by_name['day']._loaded_options = None
    _globals['_WEEKLYMAINTENANCEWINDOW'].fields_by_name['day']._serialized_options = b'\xe0A\x02'
    _globals['_WEEKLYMAINTENANCEWINDOW'].fields_by_name['start_time']._loaded_options = None
    _globals['_WEEKLYMAINTENANCEWINDOW'].fields_by_name['start_time']._serialized_options = b'\xe0A\x02'
    _globals['_WEEKLYMAINTENANCEWINDOW'].fields_by_name['duration']._loaded_options = None
    _globals['_WEEKLYMAINTENANCEWINDOW'].fields_by_name['duration']._serialized_options = b'\xe0A\x03'
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['start_time']._loaded_options = None
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['start_time']._serialized_options = b'\xe0A\x03'
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['end_time']._loaded_options = None
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['can_reschedule']._loaded_options = None
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['can_reschedule']._serialized_options = b'\x18\x01'
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['schedule_deadline_time']._loaded_options = None
    _globals['_MAINTENANCESCHEDULE'].fields_by_name['schedule_deadline_time']._serialized_options = b'\xe0A\x03'
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance'
    _globals['_GETINSTANCEAUTHSTRINGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEAUTHSTRINGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_UPGRADEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UPGRADEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance'
    _globals['_UPGRADEINSTANCEREQUEST'].fields_by_name['redis_version']._loaded_options = None
    _globals['_UPGRADEINSTANCEREQUEST'].fields_by_name['redis_version']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance'
    _globals['_GCSSOURCE'].fields_by_name['uri']._loaded_options = None
    _globals['_GCSSOURCE'].fields_by_name['uri']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_IMPORTINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTINSTANCEREQUEST'].fields_by_name['input_config']._loaded_options = None
    _globals['_IMPORTINSTANCEREQUEST'].fields_by_name['input_config']._serialized_options = b'\xe0A\x02'
    _globals['_GCSDESTINATION'].fields_by_name['uri']._loaded_options = None
    _globals['_GCSDESTINATION'].fields_by_name['uri']._serialized_options = b'\xe0A\x02'
    _globals['_EXPORTINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_EXPORTINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_EXPORTINSTANCEREQUEST'].fields_by_name['output_config']._loaded_options = None
    _globals['_EXPORTINSTANCEREQUEST'].fields_by_name['output_config']._serialized_options = b'\xe0A\x02'
    _globals['_FAILOVERINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_FAILOVERINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dredis.googleapis.com/Instance'
    _globals['_FAILOVERINSTANCEREQUEST'].fields_by_name['data_protection_mode']._loaded_options = None
    _globals['_FAILOVERINSTANCEREQUEST'].fields_by_name['data_protection_mode']._serialized_options = b'\xe0A\x01'
    _globals['_LOCATIONMETADATA_AVAILABLEZONESENTRY']._loaded_options = None
    _globals['_LOCATIONMETADATA_AVAILABLEZONESENTRY']._serialized_options = b'8\x01'
    _globals['_LOCATIONMETADATA'].fields_by_name['available_zones']._loaded_options = None
    _globals['_LOCATIONMETADATA'].fields_by_name['available_zones']._serialized_options = b'\xe0A\x03'
    _globals['_TLSCERTIFICATE'].fields_by_name['create_time']._loaded_options = None
    _globals['_TLSCERTIFICATE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_TLSCERTIFICATE'].fields_by_name['expire_time']._loaded_options = None
    _globals['_TLSCERTIFICATE'].fields_by_name['expire_time']._serialized_options = b'\xe0A\x03'
    _globals['_CLOUDREDIS']._loaded_options = None
    _globals['_CLOUDREDIS']._serialized_options = b'\xcaA\x14redis.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_CLOUDREDIS'].methods_by_name['ListInstances']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['ListInstances']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/instances'
    _globals['_CLOUDREDIS'].methods_by_name['GetInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['GetInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/instances/*}'
    _globals['_CLOUDREDIS'].methods_by_name['GetInstanceAuthString']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['GetInstanceAuthString']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/instances/*}/authString'
    _globals['_CLOUDREDIS'].methods_by_name['CreateInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['CreateInstance']._serialized_options = b'\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x1bparent,instance_id,instance\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/instances:\x08instance'
    _globals['_CLOUDREDIS'].methods_by_name['UpdateInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['UpdateInstance']._serialized_options = b"\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12'google.cloud.redis.v1.OperationMetadata\xdaA\x14update_mask,instance\x82\xd3\xe4\x93\x02B26/v1/{instance.name=projects/*/locations/*/instances/*}:\x08instance"
    _globals['_CLOUDREDIS'].methods_by_name['UpgradeInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['UpgradeInstance']._serialized_options = b'\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x12name,redis_version\x82\xd3\xe4\x93\x02:"5/v1/{name=projects/*/locations/*/instances/*}:upgrade:\x01*'
    _globals['_CLOUDREDIS'].methods_by_name['ImportInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['ImportInstance']._serialized_options = b'\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x11name,input_config\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/instances/*}:import:\x01*'
    _globals['_CLOUDREDIS'].methods_by_name['ExportInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['ExportInstance']._serialized_options = b'\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x12name,output_config\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/instances/*}:export:\x01*'
    _globals['_CLOUDREDIS'].methods_by_name['FailoverInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['FailoverInstance']._serialized_options = b'\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA\x19name,data_protection_mode\x82\xd3\xe4\x93\x02;"6/v1/{name=projects/*/locations/*/instances/*}:failover:\x01*'
    _globals['_CLOUDREDIS'].methods_by_name['DeleteInstance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['DeleteInstance']._serialized_options = b"\xcaA@\n\x15google.protobuf.Empty\x12'google.cloud.redis.v1.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/instances/*}"
    _globals['_CLOUDREDIS'].methods_by_name['RescheduleMaintenance']._loaded_options = None
    _globals['_CLOUDREDIS'].methods_by_name['RescheduleMaintenance']._serialized_options = b'\xcaAI\n\x1egoogle.cloud.redis.v1.Instance\x12\'google.cloud.redis.v1.OperationMetadata\xdaA$name, reschedule_type, schedule_time\x82\xd3\xe4\x93\x02H"C/v1/{name=projects/*/locations/*/instances/*}:rescheduleMaintenance:\x01*'
    _globals['_NODEINFO']._serialized_start = 404
    _globals['_NODEINFO']._serialized_end = 450
    _globals['_INSTANCE']._serialized_start = 453
    _globals['_INSTANCE']._serialized_end = 2890
    _globals['_INSTANCE_LABELSENTRY']._serialized_start = 2087
    _globals['_INSTANCE_LABELSENTRY']._serialized_end = 2132
    _globals['_INSTANCE_REDISCONFIGSENTRY']._serialized_start = 2134
    _globals['_INSTANCE_REDISCONFIGSENTRY']._serialized_end = 2185
    _globals['_INSTANCE_STATE']._serialized_start = 2188
    _globals['_INSTANCE_STATE']._serialized_end = 2336
    _globals['_INSTANCE_TIER']._serialized_start = 2338
    _globals['_INSTANCE_TIER']._serialized_end = 2394
    _globals['_INSTANCE_CONNECTMODE']._serialized_start = 2396
    _globals['_INSTANCE_CONNECTMODE']._serialized_end = 2487
    _globals['_INSTANCE_TRANSITENCRYPTIONMODE']._serialized_start = 2489
    _globals['_INSTANCE_TRANSITENCRYPTIONMODE']._serialized_end = 2594
    _globals['_INSTANCE_READREPLICASMODE']._serialized_start = 2596
    _globals['_INSTANCE_READREPLICASMODE']._serialized_end = 2705
    _globals['_INSTANCE_SUSPENSIONREASON']._serialized_start = 2707
    _globals['_INSTANCE_SUSPENSIONREASON']._serialized_end = 2792
    _globals['_PERSISTENCECONFIG']._serialized_start = 2893
    _globals['_PERSISTENCECONFIG']._serialized_end = 3420
    _globals['_PERSISTENCECONFIG_PERSISTENCEMODE']._serialized_start = 3225
    _globals['_PERSISTENCECONFIG_PERSISTENCEMODE']._serialized_end = 3299
    _globals['_PERSISTENCECONFIG_SNAPSHOTPERIOD']._serialized_start = 3301
    _globals['_PERSISTENCECONFIG_SNAPSHOTPERIOD']._serialized_end = 3420
    _globals['_RESCHEDULEMAINTENANCEREQUEST']._serialized_start = 3423
    _globals['_RESCHEDULEMAINTENANCEREQUEST']._serialized_end = 3772
    _globals['_RESCHEDULEMAINTENANCEREQUEST_RESCHEDULETYPE']._serialized_start = 3662
    _globals['_RESCHEDULEMAINTENANCEREQUEST_RESCHEDULETYPE']._serialized_end = 3772
    _globals['_MAINTENANCEPOLICY']._serialized_start = 3775
    _globals['_MAINTENANCEPOLICY']._serialized_end = 4016
    _globals['_WEEKLYMAINTENANCEWINDOW']._serialized_start = 4019
    _globals['_WEEKLYMAINTENANCEWINDOW']._serialized_end = 4185
    _globals['_MAINTENANCESCHEDULE']._serialized_start = 4188
    _globals['_MAINTENANCESCHEDULE']._serialized_end = 4406
    _globals['_LISTINSTANCESREQUEST']._serialized_start = 4408
    _globals['_LISTINSTANCESREQUEST']._serialized_end = 4528
    _globals['_LISTINSTANCESRESPONSE']._serialized_start = 4530
    _globals['_LISTINSTANCESRESPONSE']._serialized_end = 4651
    _globals['_GETINSTANCEREQUEST']._serialized_start = 4653
    _globals['_GETINSTANCEREQUEST']._serialized_end = 4726
    _globals['_GETINSTANCEAUTHSTRINGREQUEST']._serialized_start = 4728
    _globals['_GETINSTANCEAUTHSTRINGREQUEST']._serialized_end = 4811
    _globals['_INSTANCEAUTHSTRING']._serialized_start = 4813
    _globals['_INSTANCEAUTHSTRING']._serialized_end = 4854
    _globals['_CREATEINSTANCEREQUEST']._serialized_start = 4857
    _globals['_CREATEINSTANCEREQUEST']._serialized_end = 5021
    _globals['_UPDATEINSTANCEREQUEST']._serialized_start = 5024
    _globals['_UPDATEINSTANCEREQUEST']._serialized_end = 5157
    _globals['_UPGRADEINSTANCEREQUEST']._serialized_start = 5159
    _globals['_UPGRADEINSTANCEREQUEST']._serialized_end = 5264
    _globals['_DELETEINSTANCEREQUEST']._serialized_start = 5266
    _globals['_DELETEINSTANCEREQUEST']._serialized_end = 5342
    _globals['_GCSSOURCE']._serialized_start = 5344
    _globals['_GCSSOURCE']._serialized_end = 5373
    _globals['_INPUTCONFIG']._serialized_start = 5375
    _globals['_INPUTCONFIG']._serialized_end = 5454
    _globals['_IMPORTINSTANCEREQUEST']._serialized_start = 5456
    _globals['_IMPORTINSTANCEREQUEST']._serialized_end = 5561
    _globals['_GCSDESTINATION']._serialized_start = 5563
    _globals['_GCSDESTINATION']._serialized_end = 5597
    _globals['_OUTPUTCONFIG']._serialized_start = 5599
    _globals['_OUTPUTCONFIG']._serialized_end = 5694
    _globals['_EXPORTINSTANCEREQUEST']._serialized_start = 5696
    _globals['_EXPORTINSTANCEREQUEST']._serialized_end = 5803
    _globals['_FAILOVERINSTANCEREQUEST']._serialized_start = 5806
    _globals['_FAILOVERINSTANCEREQUEST']._serialized_end = 6090
    _globals['_FAILOVERINSTANCEREQUEST_DATAPROTECTIONMODE']._serialized_start = 5988
    _globals['_FAILOVERINSTANCEREQUEST_DATAPROTECTIONMODE']._serialized_end = 6090
    _globals['_OPERATIONMETADATA']._serialized_start = 6093
    _globals['_OPERATIONMETADATA']._serialized_end = 6307
    _globals['_LOCATIONMETADATA']._serialized_start = 6310
    _globals['_LOCATIONMETADATA']._serialized_end = 6511
    _globals['_LOCATIONMETADATA_AVAILABLEZONESENTRY']._serialized_start = 6421
    _globals['_LOCATIONMETADATA_AVAILABLEZONESENTRY']._serialized_end = 6511
    _globals['_ZONEMETADATA']._serialized_start = 6513
    _globals['_ZONEMETADATA']._serialized_end = 6527
    _globals['_TLSCERTIFICATE']._serialized_start = 6530
    _globals['_TLSCERTIFICATE']._serialized_end = 6717
    _globals['_CLOUDREDIS']._serialized_start = 6720
    _globals['_CLOUDREDIS']._serialized_end = 9448