"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/dataplex/v1/service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.dataplex.v1 import analyze_pb2 as google_dot_cloud_dot_dataplex_dot_v1_dot_analyze__pb2
from .....google.cloud.dataplex.v1 import resources_pb2 as google_dot_cloud_dot_dataplex_dot_v1_dot_resources__pb2
from .....google.cloud.dataplex.v1 import tasks_pb2 as google_dot_cloud_dot_dataplex_dot_v1_dot_tasks__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&google/cloud/dataplex/v1/service.proto\x12\x18google.cloud.dataplex.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a&google/cloud/dataplex/v1/analyze.proto\x1a(google/cloud/dataplex/v1/resources.proto\x1a$google/cloud/dataplex/v1/tasks.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xb3\x01\n\x11CreateLakeRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x14\n\x07lake_id\x18\x02 \x01(\tB\x03\xe0A\x02\x121\n\x04lake\x18\x03 \x01(\x0b2\x1e.google.cloud.dataplex.v1.LakeB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x98\x01\n\x11UpdateLakeRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x121\n\x04lake\x18\x02 \x01(\x0b2\x1e.google.cloud.dataplex.v1.LakeB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x03 \x01(\x08B\x03\xe0A\x01"G\n\x11DeleteLakeRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake"\xaa\x01\n\x10ListLakesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"z\n\x11ListLakesResponse\x12-\n\x05lakes\x18\x01 \x03(\x0b2\x1e.google.cloud.dataplex.v1.Lake\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x1d\n\x15unreachable_locations\x18\x03 \x03(\t"\x7f\n\x16ListLakeActionsRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"a\n\x13ListActionsResponse\x121\n\x07actions\x18\x01 \x03(\x0b2 .google.cloud.dataplex.v1.Action\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"D\n\x0eGetLakeRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake"\xae\x01\n\x11CreateZoneRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake\x12\x14\n\x07zone_id\x18\x02 \x01(\tB\x03\xe0A\x02\x121\n\x04zone\x18\x03 \x01(\x0b2\x1e.google.cloud.dataplex.v1.ZoneB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x98\x01\n\x11UpdateZoneRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x121\n\x04zone\x18\x02 \x01(\x0b2\x1e.google.cloud.dataplex.v1.ZoneB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x03 \x01(\x08B\x03\xe0A\x01"G\n\x11DeleteZoneRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone"\xa5\x01\n\x10ListZonesRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"[\n\x11ListZonesResponse\x12-\n\x05zones\x18\x01 \x03(\x0b2\x1e.google.cloud.dataplex.v1.Zone\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x7f\n\x16ListZoneActionsRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"D\n\x0eGetZoneRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone"\xb2\x01\n\x12CreateAssetRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone\x12\x15\n\x08asset_id\x18\x02 \x01(\tB\x03\xe0A\x02\x123\n\x05asset\x18\x03 \x01(\x0b2\x1f.google.cloud.dataplex.v1.AssetB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x9b\x01\n\x12UpdateAssetRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x123\n\x05asset\x18\x02 \x01(\x0b2\x1f.google.cloud.dataplex.v1.AssetB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x03 \x01(\x08B\x03\xe0A\x01"I\n\x12DeleteAssetRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1ddataplex.googleapis.com/Asset"\xa6\x01\n\x11ListAssetsRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"^\n\x12ListAssetsResponse\x12/\n\x06assets\x18\x01 \x03(\x0b2\x1f.google.cloud.dataplex.v1.Asset\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x81\x01\n\x17ListAssetActionsRequest\x125\n\x06parent\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1ddataplex.googleapis.com/Asset\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"F\n\x0fGetAssetRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1ddataplex.googleapis.com/Asset"\x80\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x03"\xae\x01\n\x11CreateTaskRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake\x12\x14\n\x07task_id\x18\x02 \x01(\tB\x03\xe0A\x02\x121\n\x04task\x18\x03 \x01(\x0b2\x1e.google.cloud.dataplex.v1.TaskB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x98\x01\n\x11UpdateTaskRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x121\n\x04task\x18\x02 \x01(\x0b2\x1e.google.cloud.dataplex.v1.TaskB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x03 \x01(\x08B\x03\xe0A\x01"G\n\x11DeleteTaskRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task"\xa5\x01\n\x10ListTasksRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"z\n\x11ListTasksResponse\x12-\n\x05tasks\x18\x01 \x03(\x0b2\x1e.google.cloud.dataplex.v1.Task\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x1d\n\x15unreachable_locations\x18\x03 \x03(\t"D\n\x0eGetTaskRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task"B\n\rGetJobRequest\x121\n\x04name\x18\x01 \x01(\tB#\xe0A\x02\xfaA\x1d\n\x1bdataplex.googleapis.com/Job"\xb2\x02\n\x0eRunTaskRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task\x12I\n\x06labels\x18\x03 \x03(\x0b24.google.cloud.dataplex.v1.RunTaskRequest.LabelsEntryB\x03\xe0A\x01\x12E\n\x04args\x18\x04 \x03(\x0b22.google.cloud.dataplex.v1.RunTaskRequest.ArgsEntryB\x03\xe0A\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"=\n\x0fRunTaskResponse\x12*\n\x03job\x18\x01 \x01(\x0b2\x1d.google.cloud.dataplex.v1.Job"x\n\x0fListJobsRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"X\n\x10ListJobsResponse\x12+\n\x04jobs\x18\x01 \x03(\x0b2\x1d.google.cloud.dataplex.v1.Job\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"E\n\x10CancelJobRequest\x121\n\x04name\x18\x01 \x01(\tB#\xe0A\x02\xfaA\x1d\n\x1bdataplex.googleapis.com/Job"\xca\x01\n\x18CreateEnvironmentRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake\x12\x1b\n\x0eenvironment_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12?\n\x0benvironment\x18\x03 \x01(\x0b2%.google.cloud.dataplex.v1.EnvironmentB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\xad\x01\n\x18UpdateEnvironmentRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12?\n\x0benvironment\x18\x02 \x01(\x0b2%.google.cloud.dataplex.v1.EnvironmentB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x03 \x01(\x08B\x03\xe0A\x01"U\n\x18DeleteEnvironmentRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#dataplex.googleapis.com/Environment"\xac\x01\n\x17ListEnvironmentsRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"p\n\x18ListEnvironmentsResponse\x12;\n\x0cenvironments\x18\x01 \x03(\x0b2%.google.cloud.dataplex.v1.Environment\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"R\n\x15GetEnvironmentRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#dataplex.googleapis.com/Environment"\x98\x01\n\x13ListSessionsRequest\x12;\n\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#dataplex.googleapis.com/Environment\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"d\n\x14ListSessionsResponse\x123\n\x08sessions\x18\x01 \x03(\x0b2!.google.cloud.dataplex.v1.Session\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xac2\n\x0fDataplexService\x12\xc3\x01\n\nCreateLake\x12+.google.cloud.dataplex.v1.CreateLakeRequest\x1a\x1d.google.longrunning.Operation"i\xcaA\x19\n\x04Lake\x12\x11OperationMetadata\xdaA\x13parent,lake,lake_id\x82\xd3\xe4\x93\x021")/v1/{parent=projects/*/locations/*}/lakes:\x04lake\x12\xc5\x01\n\nUpdateLake\x12+.google.cloud.dataplex.v1.UpdateLakeRequest\x1a\x1d.google.longrunning.Operation"k\xcaA\x19\n\x04Lake\x12\x11OperationMetadata\xdaA\x10lake,update_mask\x82\xd3\xe4\x93\x0262./v1/{lake.name=projects/*/locations/*/lakes/*}:\x04lake\x12\xbf\x01\n\nDeleteLake\x12+.google.cloud.dataplex.v1.DeleteLakeRequest\x1a\x1d.google.longrunning.Operation"e\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02+*)/v1/{name=projects/*/locations/*/lakes/*}\x12\xa0\x01\n\tListLakes\x12*.google.cloud.dataplex.v1.ListLakesRequest\x1a+.google.cloud.dataplex.v1.ListLakesResponse":\xdaA\x06parent\x82\xd3\xe4\x93\x02+\x12)/v1/{parent=projects/*/locations/*}/lakes\x12\x8d\x01\n\x07GetLake\x12(.google.cloud.dataplex.v1.GetLakeRequest\x1a\x1e.google.cloud.dataplex.v1.Lake"8\xdaA\x04name\x82\xd3\xe4\x93\x02+\x12)/v1/{name=projects/*/locations/*/lakes/*}\x12\xb8\x01\n\x0fListLakeActions\x120.google.cloud.dataplex.v1.ListLakeActionsRequest\x1a-.google.cloud.dataplex.v1.ListActionsResponse"D\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*/lakes/*}/actions\x12\xcb\x01\n\nCreateZone\x12+.google.cloud.dataplex.v1.CreateZoneRequest\x1a\x1d.google.longrunning.Operation"q\xcaA\x19\n\x04Zone\x12\x11OperationMetadata\xdaA\x13parent,zone,zone_id\x82\xd3\xe4\x93\x029"1/v1/{parent=projects/*/locations/*/lakes/*}/zones:\x04zone\x12\xcd\x01\n\nUpdateZone\x12+.google.cloud.dataplex.v1.UpdateZoneRequest\x1a\x1d.google.longrunning.Operation"s\xcaA\x19\n\x04Zone\x12\x11OperationMetadata\xdaA\x10zone,update_mask\x82\xd3\xe4\x93\x02>26/v1/{zone.name=projects/*/locations/*/lakes/*/zones/*}:\x04zone\x12\xc7\x01\n\nDeleteZone\x12+.google.cloud.dataplex.v1.DeleteZoneRequest\x1a\x1d.google.longrunning.Operation"m\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1/{name=projects/*/locations/*/lakes/*/zones/*}\x12\xa8\x01\n\tListZones\x12*.google.cloud.dataplex.v1.ListZonesRequest\x1a+.google.cloud.dataplex.v1.ListZonesResponse"B\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1/{parent=projects/*/locations/*/lakes/*}/zones\x12\x95\x01\n\x07GetZone\x12(.google.cloud.dataplex.v1.GetZoneRequest\x1a\x1e.google.cloud.dataplex.v1.Zone"@\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1/{name=projects/*/locations/*/lakes/*/zones/*}\x12\xc0\x01\n\x0fListZoneActions\x120.google.cloud.dataplex.v1.ListZoneActionsRequest\x1a-.google.cloud.dataplex.v1.ListActionsResponse"L\xdaA\x06parent\x82\xd3\xe4\x93\x02=\x12;/v1/{parent=projects/*/locations/*/lakes/*/zones/*}/actions\x12\xda\x01\n\x0bCreateAsset\x12,.google.cloud.dataplex.v1.CreateAssetRequest\x1a\x1d.google.longrunning.Operation"~\xcaA\x1a\n\x05Asset\x12\x11OperationMetadata\xdaA\x15parent,asset,asset_id\x82\xd3\xe4\x93\x02C":/v1/{parent=projects/*/locations/*/lakes/*/zones/*}/assets:\x05asset\x12\xdd\x01\n\x0bUpdateAsset\x12,.google.cloud.dataplex.v1.UpdateAssetRequest\x1a\x1d.google.longrunning.Operation"\x80\x01\xcaA\x1a\n\x05Asset\x12\x11OperationMetadata\xdaA\x11asset,update_mask\x82\xd3\xe4\x93\x02I2@/v1/{asset.name=projects/*/locations/*/lakes/*/zones/*/assets/*}:\x05asset\x12\xd2\x01\n\x0bDeleteAsset\x12,.google.cloud.dataplex.v1.DeleteAssetRequest\x1a\x1d.google.longrunning.Operation"v\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02<*:/v1/{name=projects/*/locations/*/lakes/*/zones/*/assets/*}\x12\xb4\x01\n\nListAssets\x12+.google.cloud.dataplex.v1.ListAssetsRequest\x1a,.google.cloud.dataplex.v1.ListAssetsResponse"K\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v1/{parent=projects/*/locations/*/lakes/*/zones/*}/assets\x12\xa1\x01\n\x08GetAsset\x12).google.cloud.dataplex.v1.GetAssetRequest\x1a\x1f.google.cloud.dataplex.v1.Asset"I\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v1/{name=projects/*/locations/*/lakes/*/zones/*/assets/*}\x12\xcb\x01\n\x10ListAssetActions\x121.google.cloud.dataplex.v1.ListAssetActionsRequest\x1a-.google.cloud.dataplex.v1.ListActionsResponse"U\xdaA\x06parent\x82\xd3\xe4\x93\x02F\x12D/v1/{parent=projects/*/locations/*/lakes/*/zones/*/assets/*}/actions\x12\xcb\x01\n\nCreateTask\x12+.google.cloud.dataplex.v1.CreateTaskRequest\x1a\x1d.google.longrunning.Operation"q\xcaA\x19\n\x04Task\x12\x11OperationMetadata\xdaA\x13parent,task,task_id\x82\xd3\xe4\x93\x029"1/v1/{parent=projects/*/locations/*/lakes/*}/tasks:\x04task\x12\xcd\x01\n\nUpdateTask\x12+.google.cloud.dataplex.v1.UpdateTaskRequest\x1a\x1d.google.longrunning.Operation"s\xcaA\x19\n\x04Task\x12\x11OperationMetadata\xdaA\x10task,update_mask\x82\xd3\xe4\x93\x02>26/v1/{task.name=projects/*/locations/*/lakes/*/tasks/*}:\x04task\x12\xc7\x01\n\nDeleteTask\x12+.google.cloud.dataplex.v1.DeleteTaskRequest\x1a\x1d.google.longrunning.Operation"m\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1/{name=projects/*/locations/*/lakes/*/tasks/*}\x12\xa8\x01\n\tListTasks\x12*.google.cloud.dataplex.v1.ListTasksRequest\x1a+.google.cloud.dataplex.v1.ListTasksResponse"B\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1/{parent=projects/*/locations/*/lakes/*}/tasks\x12\x95\x01\n\x07GetTask\x12(.google.cloud.dataplex.v1.GetTaskRequest\x1a\x1e.google.cloud.dataplex.v1.Task"@\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1/{name=projects/*/locations/*/lakes/*/tasks/*}\x12\xac\x01\n\x08ListJobs\x12).google.cloud.dataplex.v1.ListJobsRequest\x1a*.google.cloud.dataplex.v1.ListJobsResponse"I\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*/lakes/*/tasks/*}/jobs\x12\xa7\x01\n\x07RunTask\x12(.google.cloud.dataplex.v1.RunTaskRequest\x1a).google.cloud.dataplex.v1.RunTaskResponse"G\xdaA\x04name\x82\xd3\xe4\x93\x02:"5/v1/{name=projects/*/locations/*/lakes/*/tasks/*}:run:\x01*\x12\x99\x01\n\x06GetJob\x12\'.google.cloud.dataplex.v1.GetJobRequest\x1a\x1d.google.cloud.dataplex.v1.Job"G\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/lakes/*/tasks/*/jobs/*}\x12\xa2\x01\n\tCancelJob\x12*.google.cloud.dataplex.v1.CancelJobRequest\x1a\x16.google.protobuf.Empty"Q\xdaA\x04name\x82\xd3\xe4\x93\x02D"?/v1/{name=projects/*/locations/*/lakes/*/tasks/*/jobs/*}:cancel:\x01*\x12\xfd\x01\n\x11CreateEnvironment\x122.google.cloud.dataplex.v1.CreateEnvironmentRequest\x1a\x1d.google.longrunning.Operation"\x94\x01\xcaA \n\x0bEnvironment\x12\x11OperationMetadata\xdaA!parent,environment,environment_id\x82\xd3\xe4\x93\x02G"8/v1/{parent=projects/*/locations/*/lakes/*}/environments:\x0benvironment\x12\xff\x01\n\x11UpdateEnvironment\x122.google.cloud.dataplex.v1.UpdateEnvironmentRequest\x1a\x1d.google.longrunning.Operation"\x96\x01\xcaA \n\x0bEnvironment\x12\x11OperationMetadata\xdaA\x17environment,update_mask\x82\xd3\xe4\x93\x02S2D/v1/{environment.name=projects/*/locations/*/lakes/*/environments/*}:\x0benvironment\x12\xdc\x01\n\x11DeleteEnvironment\x122.google.cloud.dataplex.v1.DeleteEnvironmentRequest\x1a\x1d.google.longrunning.Operation"t\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02:*8/v1/{name=projects/*/locations/*/lakes/*/environments/*}\x12\xc4\x01\n\x10ListEnvironments\x121.google.cloud.dataplex.v1.ListEnvironmentsRequest\x1a2.google.cloud.dataplex.v1.ListEnvironmentsResponse"I\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*/lakes/*}/environments\x12\xb1\x01\n\x0eGetEnvironment\x12/.google.cloud.dataplex.v1.GetEnvironmentRequest\x1a%.google.cloud.dataplex.v1.Environment"G\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/lakes/*/environments/*}\x12\xc3\x01\n\x0cListSessions\x12-.google.cloud.dataplex.v1.ListSessionsRequest\x1a..google.cloud.dataplex.v1.ListSessionsResponse"T\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1/{parent=projects/*/locations/*/lakes/*/environments/*}/sessions\x1aK\xcaA\x17dataplex.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformBh\n\x1ccom.google.cloud.dataplex.v1B\x0cServiceProtoP\x01Z8cloud.google.com/go/dataplex/apiv1/dataplexpb;dataplexpbb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.dataplex.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1ccom.google.cloud.dataplex.v1B\x0cServiceProtoP\x01Z8cloud.google.com/go/dataplex/apiv1/dataplexpb;dataplexpb'
    _globals['_CREATELAKEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATELAKEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATELAKEREQUEST'].fields_by_name['lake_id']._loaded_options = None
    _globals['_CREATELAKEREQUEST'].fields_by_name['lake_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATELAKEREQUEST'].fields_by_name['lake']._loaded_options = None
    _globals['_CREATELAKEREQUEST'].fields_by_name['lake']._serialized_options = b'\xe0A\x02'
    _globals['_CREATELAKEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATELAKEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATELAKEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATELAKEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATELAKEREQUEST'].fields_by_name['lake']._loaded_options = None
    _globals['_UPDATELAKEREQUEST'].fields_by_name['lake']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATELAKEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATELAKEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETELAKEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETELAKEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_LISTLAKESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTLAKESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTLAKESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTLAKESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTLAKESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTLAKESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTLAKESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTLAKESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTLAKESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTLAKESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTLAKEACTIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTLAKEACTIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_LISTLAKEACTIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTLAKEACTIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTLAKEACTIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTLAKEACTIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_GETLAKEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETLAKEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_CREATEZONEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEZONEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_CREATEZONEREQUEST'].fields_by_name['zone_id']._loaded_options = None
    _globals['_CREATEZONEREQUEST'].fields_by_name['zone_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEZONEREQUEST'].fields_by_name['zone']._loaded_options = None
    _globals['_CREATEZONEREQUEST'].fields_by_name['zone']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEZONEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEZONEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEZONEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEZONEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEZONEREQUEST'].fields_by_name['zone']._loaded_options = None
    _globals['_UPDATEZONEREQUEST'].fields_by_name['zone']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEZONEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEZONEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEZONEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEZONEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone'
    _globals['_LISTZONESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTZONESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_LISTZONESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTZONESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTZONESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTZONESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTZONESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTZONESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTZONESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTZONESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTZONEACTIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTZONEACTIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone'
    _globals['_LISTZONEACTIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTZONEACTIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTZONEACTIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTZONEACTIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_GETZONEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETZONEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone'
    _globals['_CREATEASSETREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEASSETREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone'
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset_id']._loaded_options = None
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset']._loaded_options = None
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEASSETREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEASSETREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEASSETREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEASSETREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEASSETREQUEST'].fields_by_name['asset']._loaded_options = None
    _globals['_UPDATEASSETREQUEST'].fields_by_name['asset']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEASSETREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEASSETREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEASSETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEASSETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1ddataplex.googleapis.com/Asset'
    _globals['_LISTASSETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTASSETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Zone'
    _globals['_LISTASSETSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTASSETSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTASSETSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTASSETSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTASSETSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTASSETSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTASSETSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTASSETSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTASSETACTIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTASSETACTIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1ddataplex.googleapis.com/Asset'
    _globals['_LISTASSETACTIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTASSETACTIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTASSETACTIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTASSETACTIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_GETASSETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETASSETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1ddataplex.googleapis.com/Asset'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_CREATETASKREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATETASKREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_CREATETASKREQUEST'].fields_by_name['task_id']._loaded_options = None
    _globals['_CREATETASKREQUEST'].fields_by_name['task_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETASKREQUEST'].fields_by_name['task']._loaded_options = None
    _globals['_CREATETASKREQUEST'].fields_by_name['task']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETASKREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATETASKREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATETASKREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATETASKREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATETASKREQUEST'].fields_by_name['task']._loaded_options = None
    _globals['_UPDATETASKREQUEST'].fields_by_name['task']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATETASKREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATETASKREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETETASKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETETASKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task'
    _globals['_LISTTASKSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTTASKSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_LISTTASKSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTTASKSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTTASKSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTTASKSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTTASKSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTTASKSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTTASKSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTTASKSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETTASKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETTASKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task'
    _globals['_GETJOBREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETJOBREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1d\n\x1bdataplex.googleapis.com/Job'
    _globals['_RUNTASKREQUEST_LABELSENTRY']._loaded_options = None
    _globals['_RUNTASKREQUEST_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_RUNTASKREQUEST_ARGSENTRY']._loaded_options = None
    _globals['_RUNTASKREQUEST_ARGSENTRY']._serialized_options = b'8\x01'
    _globals['_RUNTASKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RUNTASKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task'
    _globals['_RUNTASKREQUEST'].fields_by_name['labels']._loaded_options = None
    _globals['_RUNTASKREQUEST'].fields_by_name['labels']._serialized_options = b'\xe0A\x01'
    _globals['_RUNTASKREQUEST'].fields_by_name['args']._loaded_options = None
    _globals['_RUNTASKREQUEST'].fields_by_name['args']._serialized_options = b'\xe0A\x01'
    _globals['_LISTJOBSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTJOBSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Task'
    _globals['_LISTJOBSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTJOBSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTJOBSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTJOBSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_CANCELJOBREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CANCELJOBREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1d\n\x1bdataplex.googleapis.com/Job'
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['environment_id']._loaded_options = None
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['environment_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['environment']._loaded_options = None
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['environment']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEENVIRONMENTREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEENVIRONMENTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEENVIRONMENTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEENVIRONMENTREQUEST'].fields_by_name['environment']._loaded_options = None
    _globals['_UPDATEENVIRONMENTREQUEST'].fields_by_name['environment']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEENVIRONMENTREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEENVIRONMENTREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEENVIRONMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEENVIRONMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#dataplex.googleapis.com/Environment'
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cdataplex.googleapis.com/Lake'
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTENVIRONMENTSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETENVIRONMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETENVIRONMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#dataplex.googleapis.com/Environment'
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\n#dataplex.googleapis.com/Environment'
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTSESSIONSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_DATAPLEXSERVICE']._loaded_options = None
    _globals['_DATAPLEXSERVICE']._serialized_options = b'\xcaA\x17dataplex.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateLake']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateLake']._serialized_options = b'\xcaA\x19\n\x04Lake\x12\x11OperationMetadata\xdaA\x13parent,lake,lake_id\x82\xd3\xe4\x93\x021")/v1/{parent=projects/*/locations/*}/lakes:\x04lake'
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateLake']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateLake']._serialized_options = b'\xcaA\x19\n\x04Lake\x12\x11OperationMetadata\xdaA\x10lake,update_mask\x82\xd3\xe4\x93\x0262./v1/{lake.name=projects/*/locations/*/lakes/*}:\x04lake'
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteLake']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteLake']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02+*)/v1/{name=projects/*/locations/*/lakes/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListLakes']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListLakes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02+\x12)/v1/{parent=projects/*/locations/*}/lakes'
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetLake']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetLake']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02+\x12)/v1/{name=projects/*/locations/*/lakes/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListLakeActions']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListLakeActions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*/lakes/*}/actions'
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateZone']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateZone']._serialized_options = b'\xcaA\x19\n\x04Zone\x12\x11OperationMetadata\xdaA\x13parent,zone,zone_id\x82\xd3\xe4\x93\x029"1/v1/{parent=projects/*/locations/*/lakes/*}/zones:\x04zone'
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateZone']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateZone']._serialized_options = b'\xcaA\x19\n\x04Zone\x12\x11OperationMetadata\xdaA\x10zone,update_mask\x82\xd3\xe4\x93\x02>26/v1/{zone.name=projects/*/locations/*/lakes/*/zones/*}:\x04zone'
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteZone']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteZone']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1/{name=projects/*/locations/*/lakes/*/zones/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListZones']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListZones']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1/{parent=projects/*/locations/*/lakes/*}/zones'
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetZone']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetZone']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1/{name=projects/*/locations/*/lakes/*/zones/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListZoneActions']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListZoneActions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02=\x12;/v1/{parent=projects/*/locations/*/lakes/*/zones/*}/actions'
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateAsset']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateAsset']._serialized_options = b'\xcaA\x1a\n\x05Asset\x12\x11OperationMetadata\xdaA\x15parent,asset,asset_id\x82\xd3\xe4\x93\x02C":/v1/{parent=projects/*/locations/*/lakes/*/zones/*}/assets:\x05asset'
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateAsset']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateAsset']._serialized_options = b'\xcaA\x1a\n\x05Asset\x12\x11OperationMetadata\xdaA\x11asset,update_mask\x82\xd3\xe4\x93\x02I2@/v1/{asset.name=projects/*/locations/*/lakes/*/zones/*/assets/*}:\x05asset'
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteAsset']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteAsset']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02<*:/v1/{name=projects/*/locations/*/lakes/*/zones/*/assets/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListAssets']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListAssets']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v1/{parent=projects/*/locations/*/lakes/*/zones/*}/assets'
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetAsset']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetAsset']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v1/{name=projects/*/locations/*/lakes/*/zones/*/assets/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListAssetActions']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListAssetActions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02F\x12D/v1/{parent=projects/*/locations/*/lakes/*/zones/*/assets/*}/actions'
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateTask']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateTask']._serialized_options = b'\xcaA\x19\n\x04Task\x12\x11OperationMetadata\xdaA\x13parent,task,task_id\x82\xd3\xe4\x93\x029"1/v1/{parent=projects/*/locations/*/lakes/*}/tasks:\x04task'
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateTask']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateTask']._serialized_options = b'\xcaA\x19\n\x04Task\x12\x11OperationMetadata\xdaA\x10task,update_mask\x82\xd3\xe4\x93\x02>26/v1/{task.name=projects/*/locations/*/lakes/*/tasks/*}:\x04task'
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteTask']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteTask']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1/{name=projects/*/locations/*/lakes/*/tasks/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListTasks']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListTasks']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1/{parent=projects/*/locations/*/lakes/*}/tasks'
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetTask']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetTask']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1/{name=projects/*/locations/*/lakes/*/tasks/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListJobs']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListJobs']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*/lakes/*/tasks/*}/jobs'
    _globals['_DATAPLEXSERVICE'].methods_by_name['RunTask']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['RunTask']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02:"5/v1/{name=projects/*/locations/*/lakes/*/tasks/*}:run:\x01*'
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetJob']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetJob']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/lakes/*/tasks/*/jobs/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['CancelJob']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['CancelJob']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02D"?/v1/{name=projects/*/locations/*/lakes/*/tasks/*/jobs/*}:cancel:\x01*'
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateEnvironment']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['CreateEnvironment']._serialized_options = b'\xcaA \n\x0bEnvironment\x12\x11OperationMetadata\xdaA!parent,environment,environment_id\x82\xd3\xe4\x93\x02G"8/v1/{parent=projects/*/locations/*/lakes/*}/environments:\x0benvironment'
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateEnvironment']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['UpdateEnvironment']._serialized_options = b'\xcaA \n\x0bEnvironment\x12\x11OperationMetadata\xdaA\x17environment,update_mask\x82\xd3\xe4\x93\x02S2D/v1/{environment.name=projects/*/locations/*/lakes/*/environments/*}:\x0benvironment'
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteEnvironment']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['DeleteEnvironment']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02:*8/v1/{name=projects/*/locations/*/lakes/*/environments/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListEnvironments']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListEnvironments']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*/lakes/*}/environments'
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetEnvironment']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['GetEnvironment']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/lakes/*/environments/*}'
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListSessions']._loaded_options = None
    _globals['_DATAPLEXSERVICE'].methods_by_name['ListSessions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1/{parent=projects/*/locations/*/lakes/*/environments/*}/sessions'
    _globals['_CREATELAKEREQUEST']._serialized_start = 437
    _globals['_CREATELAKEREQUEST']._serialized_end = 616
    _globals['_UPDATELAKEREQUEST']._serialized_start = 619
    _globals['_UPDATELAKEREQUEST']._serialized_end = 771
    _globals['_DELETELAKEREQUEST']._serialized_start = 773
    _globals['_DELETELAKEREQUEST']._serialized_end = 844
    _globals['_LISTLAKESREQUEST']._serialized_start = 847
    _globals['_LISTLAKESREQUEST']._serialized_end = 1017
    _globals['_LISTLAKESRESPONSE']._serialized_start = 1019
    _globals['_LISTLAKESRESPONSE']._serialized_end = 1141
    _globals['_LISTLAKEACTIONSREQUEST']._serialized_start = 1143
    _globals['_LISTLAKEACTIONSREQUEST']._serialized_end = 1270
    _globals['_LISTACTIONSRESPONSE']._serialized_start = 1272
    _globals['_LISTACTIONSRESPONSE']._serialized_end = 1369
    _globals['_GETLAKEREQUEST']._serialized_start = 1371
    _globals['_GETLAKEREQUEST']._serialized_end = 1439
    _globals['_CREATEZONEREQUEST']._serialized_start = 1442
    _globals['_CREATEZONEREQUEST']._serialized_end = 1616
    _globals['_UPDATEZONEREQUEST']._serialized_start = 1619
    _globals['_UPDATEZONEREQUEST']._serialized_end = 1771
    _globals['_DELETEZONEREQUEST']._serialized_start = 1773
    _globals['_DELETEZONEREQUEST']._serialized_end = 1844
    _globals['_LISTZONESREQUEST']._serialized_start = 1847
    _globals['_LISTZONESREQUEST']._serialized_end = 2012
    _globals['_LISTZONESRESPONSE']._serialized_start = 2014
    _globals['_LISTZONESRESPONSE']._serialized_end = 2105
    _globals['_LISTZONEACTIONSREQUEST']._serialized_start = 2107
    _globals['_LISTZONEACTIONSREQUEST']._serialized_end = 2234
    _globals['_GETZONEREQUEST']._serialized_start = 2236
    _globals['_GETZONEREQUEST']._serialized_end = 2304
    _globals['_CREATEASSETREQUEST']._serialized_start = 2307
    _globals['_CREATEASSETREQUEST']._serialized_end = 2485
    _globals['_UPDATEASSETREQUEST']._serialized_start = 2488
    _globals['_UPDATEASSETREQUEST']._serialized_end = 2643
    _globals['_DELETEASSETREQUEST']._serialized_start = 2645
    _globals['_DELETEASSETREQUEST']._serialized_end = 2718
    _globals['_LISTASSETSREQUEST']._serialized_start = 2721
    _globals['_LISTASSETSREQUEST']._serialized_end = 2887
    _globals['_LISTASSETSRESPONSE']._serialized_start = 2889
    _globals['_LISTASSETSRESPONSE']._serialized_end = 2983
    _globals['_LISTASSETACTIONSREQUEST']._serialized_start = 2986
    _globals['_LISTASSETACTIONSREQUEST']._serialized_end = 3115
    _globals['_GETASSETREQUEST']._serialized_start = 3117
    _globals['_GETASSETREQUEST']._serialized_end = 3187
    _globals['_OPERATIONMETADATA']._serialized_start = 3190
    _globals['_OPERATIONMETADATA']._serialized_end = 3446
    _globals['_CREATETASKREQUEST']._serialized_start = 3449
    _globals['_CREATETASKREQUEST']._serialized_end = 3623
    _globals['_UPDATETASKREQUEST']._serialized_start = 3626
    _globals['_UPDATETASKREQUEST']._serialized_end = 3778
    _globals['_DELETETASKREQUEST']._serialized_start = 3780
    _globals['_DELETETASKREQUEST']._serialized_end = 3851
    _globals['_LISTTASKSREQUEST']._serialized_start = 3854
    _globals['_LISTTASKSREQUEST']._serialized_end = 4019
    _globals['_LISTTASKSRESPONSE']._serialized_start = 4021
    _globals['_LISTTASKSRESPONSE']._serialized_end = 4143
    _globals['_GETTASKREQUEST']._serialized_start = 4145
    _globals['_GETTASKREQUEST']._serialized_end = 4213
    _globals['_GETJOBREQUEST']._serialized_start = 4215
    _globals['_GETJOBREQUEST']._serialized_end = 4281
    _globals['_RUNTASKREQUEST']._serialized_start = 4284
    _globals['_RUNTASKREQUEST']._serialized_end = 4590
    _globals['_RUNTASKREQUEST_LABELSENTRY']._serialized_start = 4500
    _globals['_RUNTASKREQUEST_LABELSENTRY']._serialized_end = 4545
    _globals['_RUNTASKREQUEST_ARGSENTRY']._serialized_start = 4547
    _globals['_RUNTASKREQUEST_ARGSENTRY']._serialized_end = 4590
    _globals['_RUNTASKRESPONSE']._serialized_start = 4592
    _globals['_RUNTASKRESPONSE']._serialized_end = 4653
    _globals['_LISTJOBSREQUEST']._serialized_start = 4655
    _globals['_LISTJOBSREQUEST']._serialized_end = 4775
    _globals['_LISTJOBSRESPONSE']._serialized_start = 4777
    _globals['_LISTJOBSRESPONSE']._serialized_end = 4865
    _globals['_CANCELJOBREQUEST']._serialized_start = 4867
    _globals['_CANCELJOBREQUEST']._serialized_end = 4936
    _globals['_CREATEENVIRONMENTREQUEST']._serialized_start = 4939
    _globals['_CREATEENVIRONMENTREQUEST']._serialized_end = 5141
    _globals['_UPDATEENVIRONMENTREQUEST']._serialized_start = 5144
    _globals['_UPDATEENVIRONMENTREQUEST']._serialized_end = 5317
    _globals['_DELETEENVIRONMENTREQUEST']._serialized_start = 5319
    _globals['_DELETEENVIRONMENTREQUEST']._serialized_end = 5404
    _globals['_LISTENVIRONMENTSREQUEST']._serialized_start = 5407
    _globals['_LISTENVIRONMENTSREQUEST']._serialized_end = 5579
    _globals['_LISTENVIRONMENTSRESPONSE']._serialized_start = 5581
    _globals['_LISTENVIRONMENTSRESPONSE']._serialized_end = 5693
    _globals['_GETENVIRONMENTREQUEST']._serialized_start = 5695
    _globals['_GETENVIRONMENTREQUEST']._serialized_end = 5777
    _globals['_LISTSESSIONSREQUEST']._serialized_start = 5780
    _globals['_LISTSESSIONSREQUEST']._serialized_end = 5932
    _globals['_LISTSESSIONSRESPONSE']._serialized_start = 5934
    _globals['_LISTSESSIONSRESPONSE']._serialized_end = 6034
    _globals['_DATAPLEXSERVICE']._serialized_start = 6037
    _globals['_DATAPLEXSERVICE']._serialized_end = 12481