from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar
DESCRIPTOR: _descriptor.FileDescriptor

class ResourceLimitTypeEnum(_message.Message):
    __slots__ = ()

    class ResourceLimitType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        UNSPECIFIED: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        UNKNOWN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CAMPAIGNS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASE_CAMPAIGNS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_CAMPAIGNS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        HOTEL_CAMPAIGNS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SMART_SHOPPING_CAMPAIGNS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUPS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUPS_PER_SHOPPING_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUPS_PER_HOTEL_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        REPORTING_AD_GROUPS_PER_LOCAL_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        REPORTING_AD_GROUPS_PER_APP_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        MANAGED_AD_GROUPS_PER_SMART_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUP_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASE_AD_GROUP_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_AD_GROUP_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUP_CRITERIA_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CAMPAIGN_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASE_CAMPAIGN_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_CAMPAIGN_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        WEBPAGE_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASE_WEBPAGE_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_WEBPAGE_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        COMBINED_AUDIENCE_CRITERIA_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CUSTOMER_NEGATIVE_PLACEMENT_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CUSTOMER_NEGATIVE_YOUTUBE_CHANNEL_CRITERIA_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CRITERIA_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LISTING_GROUPS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPLICITLY_SHARED_BUDGETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        IMPLICITLY_SHARED_BUDGETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        COMBINED_AUDIENCE_CRITERIA_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        NEGATIVE_KEYWORDS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        NEGATIVE_PLACEMENTS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        GEO_TARGETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        NEGATIVE_IP_BLOCKS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PROXIMITIES_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LISTING_SCOPES_PER_SHOPPING_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LISTING_SCOPES_PER_NON_SHOPPING_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        NEGATIVE_KEYWORDS_PER_SHARED_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        NEGATIVE_PLACEMENTS_PER_SHARED_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SHARED_SETS_PER_CUSTOMER_FOR_TYPE_DEFAULT: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SHARED_SETS_PER_CUSTOMER_FOR_NEGATIVE_PLACEMENT_LIST_LOWER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        HOTEL_ADVANCE_BOOKING_WINDOW_BID_MODIFIERS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BIDDING_STRATEGIES_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASIC_USER_LISTS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LOGICAL_USER_LISTS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        RULE_BASED_USER_LISTS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASE_AD_GROUP_ADS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_AD_GROUP_ADS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUP_ADS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        TEXT_AND_OTHER_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        IMAGE_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SHOPPING_SMART_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        RESPONSIVE_SEARCH_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        APP_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        APP_ENGAGEMENT_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LOCAL_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        VIDEO_ADS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LEAD_FORM_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PROMOTION_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PROMOTION_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PROMOTION_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CALLOUT_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CALLOUT_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CALLOUT_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SITELINK_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SITELINK_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SITELINK_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        STRUCTURED_SNIPPET_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        STRUCTURED_SNIPPET_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        STRUCTURED_SNIPPET_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        MOBILE_APP_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        MOBILE_APP_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        MOBILE_APP_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        HOTEL_CALLOUT_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        HOTEL_CALLOUT_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        HOTEL_CALLOUT_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CALL_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CALL_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CALL_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PRICE_CUSTOMER_ASSETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PRICE_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PRICE_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_IMAGE_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_IMAGE_AD_GROUP_ASSETS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        PAGE_FEED_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_EDUCATION_FEED_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_PAGE_FEED_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_EDUCATION_FEED_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_REAL_ESTATE_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_REAL_ESTATE_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_CUSTOM_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_CUSTOM_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_HOTELS_AND_RENTALS_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_HOTELS_AND_RENTALS_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_LOCAL_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_LOCAL_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_FLIGHTS_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_FLIGHTS_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_TRAVEL_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_TRAVEL_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        DYNAMIC_JOBS_ASSET_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ASSETS_PER_DYNAMIC_JOBS_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BUSINESS_NAME_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BUSINESS_LOGO_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        VERSIONS_PER_AD: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        USER_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SYSTEM_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        FEED_ATTRIBUTES_PER_FEED: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        FEED_ITEMS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CAMPAIGN_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASE_CAMPAIGN_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_CAMPAIGN_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUP_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BASE_AD_GROUP_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_AD_GROUP_FEEDS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        AD_GROUP_FEEDS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        FEED_ITEM_SETS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        FEED_ITEMS_PER_FEED_ITEM_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CAMPAIGN_EXPERIMENTS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        EXPERIMENT_ARMS_PER_VIDEO_EXPERIMENT: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        OWNED_LABELS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LABELS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LABELS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LABELS_PER_AD_GROUP_AD: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LABELS_PER_AD_GROUP_CRITERION: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        TARGET_CUSTOMERS_PER_LABEL: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        KEYWORD_PLANS_PER_USER_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        KEYWORD_PLAN_AD_GROUP_KEYWORDS_PER_KEYWORD_PLAN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        KEYWORD_PLAN_AD_GROUPS_PER_KEYWORD_PLAN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        KEYWORD_PLAN_NEGATIVE_KEYWORDS_PER_KEYWORD_PLAN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        KEYWORD_PLAN_CAMPAIGNS_PER_KEYWORD_PLAN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        CONVERSION_ACTIONS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BATCH_JOB_OPERATIONS_PER_JOB: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BATCH_JOBS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        HOTEL_CHECK_IN_DATE_RANGE_BID_MODIFIERS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SHARED_SETS_PER_ACCOUNT_FOR_ACCOUNT_LEVEL_NEGATIVE_KEYWORDS: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ACCOUNT_LEVEL_NEGATIVE_KEYWORDS_PER_SHARED_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ENABLED_ASSET_PER_HOTEL_PROPERTY_ASSET_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ENABLED_HOTEL_PROPERTY_ASSET_LINKS_PER_ASSET_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BRANDS_PER_SHARED_SET: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        ENABLED_BRAND_LIST_CRITERIA_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        SHARED_SETS_PER_ACCOUNT_FOR_BRAND: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LOOKALIKE_USER_LISTS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        LOGO_CAMPAIGN_ASSETS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        BUSINESS_MESSAGE_ASSET_LINKS_PER_CUSTOMER: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        WHATSAPP_BUSINESS_MESSAGE_ASSET_LINKS_PER_CAMPAIGN: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
        WHATSAPP_BUSINESS_MESSAGE_ASSET_LINKS_PER_AD_GROUP: _ClassVar[ResourceLimitTypeEnum.ResourceLimitType]
    UNSPECIFIED: ResourceLimitTypeEnum.ResourceLimitType
    UNKNOWN: ResourceLimitTypeEnum.ResourceLimitType
    CAMPAIGNS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASE_CAMPAIGNS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_CAMPAIGNS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    HOTEL_CAMPAIGNS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    SMART_SHOPPING_CAMPAIGNS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUPS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUPS_PER_SHOPPING_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUPS_PER_HOTEL_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    REPORTING_AD_GROUPS_PER_LOCAL_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    REPORTING_AD_GROUPS_PER_APP_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    MANAGED_AD_GROUPS_PER_SMART_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUP_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASE_AD_GROUP_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_AD_GROUP_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUP_CRITERIA_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    CAMPAIGN_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASE_CAMPAIGN_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_CAMPAIGN_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    WEBPAGE_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASE_WEBPAGE_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_WEBPAGE_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    COMBINED_AUDIENCE_CRITERIA_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    CUSTOMER_NEGATIVE_PLACEMENT_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    CUSTOMER_NEGATIVE_YOUTUBE_CHANNEL_CRITERIA_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    CRITERIA_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    LISTING_GROUPS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    EXPLICITLY_SHARED_BUDGETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    IMPLICITLY_SHARED_BUDGETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    COMBINED_AUDIENCE_CRITERIA_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    NEGATIVE_KEYWORDS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    NEGATIVE_PLACEMENTS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    GEO_TARGETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    NEGATIVE_IP_BLOCKS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    PROXIMITIES_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    LISTING_SCOPES_PER_SHOPPING_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    LISTING_SCOPES_PER_NON_SHOPPING_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    NEGATIVE_KEYWORDS_PER_SHARED_SET: ResourceLimitTypeEnum.ResourceLimitType
    NEGATIVE_PLACEMENTS_PER_SHARED_SET: ResourceLimitTypeEnum.ResourceLimitType
    SHARED_SETS_PER_CUSTOMER_FOR_TYPE_DEFAULT: ResourceLimitTypeEnum.ResourceLimitType
    SHARED_SETS_PER_CUSTOMER_FOR_NEGATIVE_PLACEMENT_LIST_LOWER: ResourceLimitTypeEnum.ResourceLimitType
    HOTEL_ADVANCE_BOOKING_WINDOW_BID_MODIFIERS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    BIDDING_STRATEGIES_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASIC_USER_LISTS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    LOGICAL_USER_LISTS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    RULE_BASED_USER_LISTS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASE_AD_GROUP_ADS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_AD_GROUP_ADS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUP_ADS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    TEXT_AND_OTHER_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    IMAGE_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    SHOPPING_SMART_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    RESPONSIVE_SEARCH_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    APP_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    APP_ENGAGEMENT_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    LOCAL_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    VIDEO_ADS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    LEAD_FORM_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    PROMOTION_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    PROMOTION_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    PROMOTION_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    CALLOUT_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    CALLOUT_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    CALLOUT_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    SITELINK_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    SITELINK_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    SITELINK_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    STRUCTURED_SNIPPET_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    STRUCTURED_SNIPPET_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    STRUCTURED_SNIPPET_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    MOBILE_APP_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    MOBILE_APP_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    MOBILE_APP_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    HOTEL_CALLOUT_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    HOTEL_CALLOUT_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    HOTEL_CALLOUT_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    CALL_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    CALL_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    CALL_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    PRICE_CUSTOMER_ASSETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    PRICE_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    PRICE_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    AD_IMAGE_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    AD_IMAGE_AD_GROUP_ASSETS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    PAGE_FEED_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_EDUCATION_FEED_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_PAGE_FEED_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_EDUCATION_FEED_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_REAL_ESTATE_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_REAL_ESTATE_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_CUSTOM_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_CUSTOM_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_HOTELS_AND_RENTALS_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_HOTELS_AND_RENTALS_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_LOCAL_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_LOCAL_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_FLIGHTS_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_FLIGHTS_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_TRAVEL_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_TRAVEL_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    DYNAMIC_JOBS_ASSET_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    ASSETS_PER_DYNAMIC_JOBS_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    BUSINESS_NAME_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    BUSINESS_LOGO_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    VERSIONS_PER_AD: ResourceLimitTypeEnum.ResourceLimitType
    USER_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    SYSTEM_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    FEED_ATTRIBUTES_PER_FEED: ResourceLimitTypeEnum.ResourceLimitType
    FEED_ITEMS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    CAMPAIGN_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASE_CAMPAIGN_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_CAMPAIGN_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUP_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BASE_AD_GROUP_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_AD_GROUP_FEEDS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    AD_GROUP_FEEDS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    FEED_ITEM_SETS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    FEED_ITEMS_PER_FEED_ITEM_SET: ResourceLimitTypeEnum.ResourceLimitType
    CAMPAIGN_EXPERIMENTS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    EXPERIMENT_ARMS_PER_VIDEO_EXPERIMENT: ResourceLimitTypeEnum.ResourceLimitType
    OWNED_LABELS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    LABELS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    LABELS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    LABELS_PER_AD_GROUP_AD: ResourceLimitTypeEnum.ResourceLimitType
    LABELS_PER_AD_GROUP_CRITERION: ResourceLimitTypeEnum.ResourceLimitType
    TARGET_CUSTOMERS_PER_LABEL: ResourceLimitTypeEnum.ResourceLimitType
    KEYWORD_PLANS_PER_USER_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    KEYWORD_PLAN_AD_GROUP_KEYWORDS_PER_KEYWORD_PLAN: ResourceLimitTypeEnum.ResourceLimitType
    KEYWORD_PLAN_AD_GROUPS_PER_KEYWORD_PLAN: ResourceLimitTypeEnum.ResourceLimitType
    KEYWORD_PLAN_NEGATIVE_KEYWORDS_PER_KEYWORD_PLAN: ResourceLimitTypeEnum.ResourceLimitType
    KEYWORD_PLAN_CAMPAIGNS_PER_KEYWORD_PLAN: ResourceLimitTypeEnum.ResourceLimitType
    CONVERSION_ACTIONS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    BATCH_JOB_OPERATIONS_PER_JOB: ResourceLimitTypeEnum.ResourceLimitType
    BATCH_JOBS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    HOTEL_CHECK_IN_DATE_RANGE_BID_MODIFIERS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    SHARED_SETS_PER_ACCOUNT_FOR_ACCOUNT_LEVEL_NEGATIVE_KEYWORDS: ResourceLimitTypeEnum.ResourceLimitType
    ACCOUNT_LEVEL_NEGATIVE_KEYWORDS_PER_SHARED_SET: ResourceLimitTypeEnum.ResourceLimitType
    ENABLED_ASSET_PER_HOTEL_PROPERTY_ASSET_SET: ResourceLimitTypeEnum.ResourceLimitType
    ENABLED_HOTEL_PROPERTY_ASSET_LINKS_PER_ASSET_GROUP: ResourceLimitTypeEnum.ResourceLimitType
    BRANDS_PER_SHARED_SET: ResourceLimitTypeEnum.ResourceLimitType
    ENABLED_BRAND_LIST_CRITERIA_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    SHARED_SETS_PER_ACCOUNT_FOR_BRAND: ResourceLimitTypeEnum.ResourceLimitType
    LOOKALIKE_USER_LISTS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    LOGO_CAMPAIGN_ASSETS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    BUSINESS_MESSAGE_ASSET_LINKS_PER_CUSTOMER: ResourceLimitTypeEnum.ResourceLimitType
    WHATSAPP_BUSINESS_MESSAGE_ASSET_LINKS_PER_CAMPAIGN: ResourceLimitTypeEnum.ResourceLimitType
    WHATSAPP_BUSINESS_MESSAGE_ASSET_LINKS_PER_AD_GROUP: ResourceLimitTypeEnum.ResourceLimitType

    def __init__(self) -> None:
        ...