# coding: utf-8

"""
    Prediction Market OpenAPI

    Prediction Market REST API for trading and market operations

    The version of the OpenAPI document: 1.0
    Contact: support@polymarket.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from olab_open_api.models.openapi_quote_token_balance import OpenapiQuoteTokenBalance

class TestOpenapiQuoteTokenBalance(unittest.TestCase):
    """OpenapiQuoteTokenBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenapiQuoteTokenBalance:
        """Test OpenapiQuoteTokenBalance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenapiQuoteTokenBalance`
        """
        model = OpenapiQuoteTokenBalance()
        if include_optional:
            return OpenapiQuoteTokenBalance(
                available_balance = '',
                frozen_balance = '',
                quote_token = '',
                token_decimals = 56,
                total_balance = ''
            )
        else:
            return OpenapiQuoteTokenBalance(
        )
        """

    def testOpenapiQuoteTokenBalance(self):
        """Test OpenapiQuoteTokenBalance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
