# coding: utf-8

"""
    Prediction Market OpenAPI

    Prediction Market REST API for trading and market operations

    The version of the OpenAPI document: 1.0
    Contact: support@polymarket.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from olab_open_api.models.openapi_quote_token_get200_response import OpenapiQuoteTokenGet200Response

class TestOpenapiQuoteTokenGet200Response(unittest.TestCase):
    """OpenapiQuoteTokenGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenapiQuoteTokenGet200Response:
        """Test OpenapiQuoteTokenGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenapiQuoteTokenGet200Response`
        """
        model = OpenapiQuoteTokenGet200Response()
        if include_optional:
            return OpenapiQuoteTokenGet200Response(
                errmsg = '',
                errno = 56,
                result = olab_open_api.models.openapi/quote_token_list_resp_open_api.openapi.QuoteTokenListRespOpenAPI(
                    list = [
                        olab_open_api.models.openapi/quote_token_data_open_api.openapi.QuoteTokenDataOpenAPI(
                            chain_id = '', 
                            created_at = 56, 
                            ctf_exchange_address = '', 
                            decimal = 56, 
                            id = 56, 
                            quote_token_address = '', 
                            quote_token_name = '', 
                            symbol = '', )
                        ], 
                    total = 56, )
            )
        else:
            return OpenapiQuoteTokenGet200Response(
        )
        """

    def testOpenapiQuoteTokenGet200Response(self):
        """Test OpenapiQuoteTokenGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
