# coding: utf-8

"""
    Prediction Market OpenAPI

    Prediction Market REST API for trading and market operations

    The version of the OpenAPI document: 1.0
    Contact: support@polymarket.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from olab_open_api.models.openapi_position_data_open_api import OpenapiPositionDataOpenAPI

class TestOpenapiPositionDataOpenAPI(unittest.TestCase):
    """OpenapiPositionDataOpenAPI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenapiPositionDataOpenAPI:
        """Test OpenapiPositionDataOpenAPI
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenapiPositionDataOpenAPI`
        """
        model = OpenapiPositionDataOpenAPI()
        if include_optional:
            return OpenapiPositionDataOpenAPI(
                avg_entry_price = '',
                claim_status = 56,
                claim_status_enum = '',
                condition_id = '',
                current_value_in_quote_token = '',
                daily_pnl_change = '',
                daily_pnl_change_percent = '',
                market_cutoff_at = 56,
                market_id = 56,
                market_status = 56,
                market_status_enum = '',
                market_title = '',
                outcome = '',
                outcome_side = 56,
                outcome_side_enum = '',
                quote_token = '',
                root_market_id = 56,
                root_market_title = '',
                shares_frozen = '',
                shares_owned = '',
                token_id = '',
                unrealized_pnl = '',
                unrealized_pnl_percent = ''
            )
        else:
            return OpenapiPositionDataOpenAPI(
        )
        """

    def testOpenapiPositionDataOpenAPI(self):
        """Test OpenapiPositionDataOpenAPI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
