# coding: utf-8

"""
    Prediction Market OpenAPI

    Prediction Market REST API for trading and market operations

    The version of the OpenAPI document: 1.0
    Contact: support@polymarket.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from olab_open_api.models.openapi_trade_list_resp_open_api import OpenapiTradeListRespOpenAPI

class TestOpenapiTradeListRespOpenAPI(unittest.TestCase):
    """OpenapiTradeListRespOpenAPI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenapiTradeListRespOpenAPI:
        """Test OpenapiTradeListRespOpenAPI
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenapiTradeListRespOpenAPI`
        """
        model = OpenapiTradeListRespOpenAPI()
        if include_optional:
            return OpenapiTradeListRespOpenAPI(
                list = [
                    olab_open_api.models.openapi/trade_data_open_api.openapi.TradeDataOpenAPI(
                        amount = '', 
                        chain_id = '', 
                        created_at = 56, 
                        fee = 56, 
                        market_id = 56, 
                        market_title = '', 
                        order_no = '', 
                        outcome = '', 
                        outcome_side = 56, 
                        outcome_side_enum = '', 
                        price = '', 
                        profit = '', 
                        quote_token = '', 
                        quote_token_usd_price = '', 
                        root_market_id = 56, 
                        root_market_title = '', 
                        shares = '', 
                        side = '', 
                        status = 56, 
                        status_enum = '', 
                        trade_no = '', 
                        tx_hash = '', 
                        usd_amount = '', )
                    ],
                total = 56
            )
        else:
            return OpenapiTradeListRespOpenAPI(
        )
        """

    def testOpenapiTradeListRespOpenAPI(self):
        """Test OpenapiTradeListRespOpenAPI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
