"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/bigtable/admin/v2/bigtable_table_admin.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.bigtable.admin.v2 import common_pb2 as google_dot_bigtable_dot_admin_dot_v2_dot_common__pb2
from .....google.bigtable.admin.v2 import table_pb2 as google_dot_bigtable_dot_admin_dot_v2_dot_table__pb2
from .....google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from .....google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3google/bigtable/admin/v2/bigtable_table_admin.proto\x12\x18google.bigtable.admin.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a%google/bigtable/admin/v2/common.proto\x1a$google/bigtable/admin/v2/table.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a#google/longrunning/operations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xb1\x01\n\x13RestoreTableRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x15\n\x08table_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12:\n\x06backup\x18\x03 \x01(\tB(\xfaA%\n#bigtableadmin.googleapis.com/BackupH\x00B\x08\n\x06source"\x98\x02\n\x14RestoreTableMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12@\n\x0bsource_type\x18\x02 \x01(\x0e2+.google.bigtable.admin.v2.RestoreSourceType\x12;\n\x0bbackup_info\x18\x03 \x01(\x0b2$.google.bigtable.admin.v2.BackupInfoH\x00\x12%\n\x1doptimize_table_operation_name\x18\x04 \x01(\t\x12=\n\x08progress\x18\x05 \x01(\x0b2+.google.bigtable.admin.v2.OperationProgressB\r\n\x0bsource_info"l\n\x1dOptimizeRestoredTableMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12=\n\x08progress\x18\x02 \x01(\x0b2+.google.bigtable.admin.v2.OperationProgress"\x81\x02\n\x12CreateTableRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x15\n\x08table_id\x18\x02 \x01(\tB\x03\xe0A\x02\x123\n\x05table\x18\x03 \x01(\x0b2\x1f.google.bigtable.admin.v2.TableB\x03\xe0A\x02\x12J\n\x0einitial_splits\x18\x04 \x03(\x0b22.google.bigtable.admin.v2.CreateTableRequest.Split\x1a\x14\n\x05Split\x12\x0b\n\x03key\x18\x01 \x01(\x0c"\xbe\x01\n\x1eCreateTableFromSnapshotRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x15\n\x08table_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12F\n\x0fsource_snapshot\x18\x03 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Snapshot"\x99\x01\n\x13DropRowRangeRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table\x12\x18\n\x0erow_key_prefix\x18\x02 \x01(\x0cH\x00\x12$\n\x1adelete_all_data_from_table\x18\x03 \x01(\x08H\x00B\x08\n\x06target"\xad\x01\n\x11ListTablesRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x122\n\x04view\x18\x02 \x01(\x0e2$.google.bigtable.admin.v2.Table.View\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"^\n\x12ListTablesResponse\x12/\n\x06tables\x18\x01 \x03(\x0b2\x1f.google.bigtable.admin.v2.Table\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x7f\n\x0fGetTableRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table\x122\n\x04view\x18\x02 \x01(\x0e2$.google.bigtable.admin.v2.Table.View"\x9d\x01\n\x12UpdateTableRequest\x123\n\x05table\x18\x01 \x01(\x0b2\x1f.google.bigtable.admin.v2.TableB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x1c\n\x0fignore_warnings\x18\x03 \x01(\x08B\x03\xe0A\x01"\x81\x01\n\x13UpdateTableMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"N\n\x12DeleteTableRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table"P\n\x14UndeleteTableRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table"\x83\x01\n\x15UndeleteTableMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xb3\x03\n\x1bModifyColumnFamiliesRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table\x12^\n\rmodifications\x18\x02 \x03(\x0b2B.google.bigtable.admin.v2.ModifyColumnFamiliesRequest.ModificationB\x03\xe0A\x02\x12\x1c\n\x0fignore_warnings\x18\x03 \x01(\x08B\x03\xe0A\x01\x1a\xdb\x01\n\x0cModification\x12\n\n\x02id\x18\x01 \x01(\t\x128\n\x06create\x18\x02 \x01(\x0b2&.google.bigtable.admin.v2.ColumnFamilyH\x00\x128\n\x06update\x18\x03 \x01(\x0b2&.google.bigtable.admin.v2.ColumnFamilyH\x00\x12\x0e\n\x04drop\x18\x04 \x01(\x08H\x00\x124\n\x0bupdate_mask\x18\x06 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01B\x05\n\x03mod"[\n\x1fGenerateConsistencyTokenRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table"=\n GenerateConsistencyTokenResponse\x12\x19\n\x11consistency_token\x18\x01 \x01(\t"\xb2\x02\n\x17CheckConsistencyRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table\x12\x1e\n\x11consistency_token\x18\x02 \x01(\tB\x03\xe0A\x02\x12Y\n\x1bstandard_read_remote_writes\x18\x03 \x01(\x0b22.google.bigtable.admin.v2.StandardReadRemoteWritesH\x00\x12Z\n\x1cdata_boost_read_local_writes\x18\x04 \x01(\x0b22.google.bigtable.admin.v2.DataBoostReadLocalWritesH\x00B\x06\n\x04mode"\x1a\n\x18StandardReadRemoteWrites"\x1a\n\x18DataBoostReadLocalWrites".\n\x18CheckConsistencyResponse\x12\x12\n\nconsistent\x18\x01 \x01(\x08"\xe6\x01\n\x14SnapshotTableRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table\x12=\n\x07cluster\x18\x02 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster\x12\x18\n\x0bsnapshot_id\x18\x03 \x01(\tB\x03\xe0A\x02\x12&\n\x03ttl\x18\x04 \x01(\x0b2\x19.google.protobuf.Duration\x12\x13\n\x0bdescription\x18\x05 \x01(\t"Q\n\x12GetSnapshotRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Snapshot"{\n\x14ListSnapshotsRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"g\n\x15ListSnapshotsResponse\x125\n\tsnapshots\x18\x01 \x03(\x0b2".google.bigtable.admin.v2.Snapshot\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"T\n\x15DeleteSnapshotRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Snapshot"\xc4\x01\n\x15SnapshotTableMetadata\x12H\n\x10original_request\x18\x01 \x01(\x0b2..google.bigtable.admin.v2.SnapshotTableRequest\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xd8\x01\n\x1fCreateTableFromSnapshotMetadata\x12R\n\x10original_request\x18\x01 \x01(\x0b28.google.bigtable.admin.v2.CreateTableFromSnapshotRequest\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xa2\x01\n\x13CreateBackupRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster\x12\x16\n\tbackup_id\x18\x02 \x01(\tB\x03\xe0A\x02\x125\n\x06backup\x18\x03 \x01(\x0b2 .google.bigtable.admin.v2.BackupB\x03\xe0A\x02"\x98\x01\n\x14CreateBackupMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0csource_table\x18\x02 \x01(\t\x12.\n\nstart_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp"\x82\x01\n\x13UpdateBackupRequest\x125\n\x06backup\x18\x01 \x01(\x0b2 .google.bigtable.admin.v2.BackupB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"M\n\x10GetBackupRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#bigtableadmin.googleapis.com/Backup"P\n\x13DeleteBackupRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#bigtableadmin.googleapis.com/Backup"\x9b\x01\n\x12ListBackupsRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster\x12\x0e\n\x06filter\x18\x02 \x01(\t\x12\x10\n\x08order_by\x18\x03 \x01(\t\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x12\n\npage_token\x18\x05 \x01(\t"a\n\x13ListBackupsResponse\x121\n\x07backups\x18\x01 \x03(\x0b2 .google.bigtable.admin.v2.Backup\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xe3\x01\n\x11CopyBackupRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster\x12\x16\n\tbackup_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12B\n\rsource_backup\x18\x03 \x01(\tB+\xe0A\x02\xfaA%\n#bigtableadmin.googleapis.com/Backup\x124\n\x0bexpire_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x02"\xcd\x01\n\x12CopyBackupMetadata\x126\n\x04name\x18\x01 \x01(\tB(\xfaA%\n#bigtableadmin.googleapis.com/Backup\x12@\n\x12source_backup_info\x18\x02 \x01(\x0b2$.google.bigtable.admin.v2.BackupInfo\x12=\n\x08progress\x18\x03 \x01(\x0b2+.google.bigtable.admin.v2.OperationProgress"\xcb\x01\n\x1bCreateAuthorizedViewRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+bigtableadmin.googleapis.com/AuthorizedView\x12\x1f\n\x12authorized_view_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12F\n\x0fauthorized_view\x18\x03 \x01(\x0b2(.google.bigtable.admin.v2.AuthorizedViewB\x03\xe0A\x02"\xd2\x01\n\x1cCreateAuthorizedViewMetadata\x12O\n\x10original_request\x18\x01 \x01(\x0b25.google.bigtable.admin.v2.CreateAuthorizedViewRequest\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xdc\x01\n\x1aListAuthorizedViewsRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+bigtableadmin.googleapis.com/AuthorizedView\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12H\n\x04view\x18\x04 \x01(\x0e25.google.bigtable.admin.v2.AuthorizedView.ResponseViewB\x03\xe0A\x01"z\n\x1bListAuthorizedViewsResponse\x12B\n\x10authorized_views\x18\x01 \x03(\x0b2(.google.bigtable.admin.v2.AuthorizedView\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xa7\x01\n\x18GetAuthorizedViewRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+bigtableadmin.googleapis.com/AuthorizedView\x12H\n\x04view\x18\x02 \x01(\x0e25.google.bigtable.admin.v2.AuthorizedView.ResponseViewB\x03\xe0A\x01"\xb9\x01\n\x1bUpdateAuthorizedViewRequest\x12F\n\x0fauthorized_view\x18\x01 \x01(\x0b2(.google.bigtable.admin.v2.AuthorizedViewB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12\x1c\n\x0fignore_warnings\x18\x03 \x01(\x08B\x03\xe0A\x01"\xd2\x01\n\x1cUpdateAuthorizedViewMetadata\x12O\n\x10original_request\x18\x01 \x01(\x0b25.google.bigtable.admin.v2.UpdateAuthorizedViewRequest\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"s\n\x1bDeleteAuthorizedViewRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+bigtableadmin.googleapis.com/AuthorizedView\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01"\xba\x01\n\x19CreateSchemaBundleRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table\x12\x1d\n\x10schema_bundle_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12B\n\rschema_bundle\x18\x03 \x01(\x0b2&.google.bigtable.admin.v2.SchemaBundleB\x03\xe0A\x02"\x88\x01\n\x1aCreateSchemaBundleMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xb3\x01\n\x19UpdateSchemaBundleRequest\x12B\n\rschema_bundle\x18\x01 \x01(\x0b2&.google.bigtable.admin.v2.SchemaBundleB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12\x1c\n\x0fignore_warnings\x18\x03 \x01(\x08B\x03\xe0A\x01"\x88\x01\n\x1aUpdateSchemaBundleMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"Y\n\x16GetSchemaBundleRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)bigtableadmin.googleapis.com/SchemaBundle"\x84\x01\n\x18ListSchemaBundlesRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\x12)bigtableadmin.googleapis.com/SchemaBundle\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"t\n\x19ListSchemaBundlesResponse\x12>\n\x0eschema_bundles\x18\x01 \x03(\x0b2&.google.bigtable.admin.v2.SchemaBundle\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"o\n\x19DeleteSchemaBundleRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)bigtableadmin.googleapis.com/SchemaBundle\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x012\x92@\n\x12BigtableTableAdmin\x12\xab\x01\n\x0bCreateTable\x12,.google.bigtable.admin.v2.CreateTableRequest\x1a\x1f.google.bigtable.admin.v2.Table"M\xdaA\x15parent,table_id,table\x82\xd3\xe4\x93\x02/"*/v2/{parent=projects/*/instances/*}/tables:\x01*\x12\x8a\x02\n\x17CreateTableFromSnapshot\x128.google.bigtable.admin.v2.CreateTableFromSnapshotRequest\x1a\x1d.google.longrunning.Operation"\x95\x01\xcaA(\n\x05Table\x12\x1fCreateTableFromSnapshotMetadata\xdaA\x1fparent,table_id,source_snapshot\x82\xd3\xe4\x93\x02B"=/v2/{parent=projects/*/instances/*}/tables:createFromSnapshot:\x01*\x12\xa4\x01\n\nListTables\x12+.google.bigtable.admin.v2.ListTablesRequest\x1a,.google.bigtable.admin.v2.ListTablesResponse";\xdaA\x06parent\x82\xd3\xe4\x93\x02,\x12*/v2/{parent=projects/*/instances/*}/tables\x12\x91\x01\n\x08GetTable\x12).google.bigtable.admin.v2.GetTableRequest\x1a\x1f.google.bigtable.admin.v2.Table"9\xdaA\x04name\x82\xd3\xe4\x93\x02,\x12*/v2/{name=projects/*/instances/*/tables/*}\x12\xce\x01\n\x0bUpdateTable\x12,.google.bigtable.admin.v2.UpdateTableRequest\x1a\x1d.google.longrunning.Operation"r\xcaA\x1c\n\x05Table\x12\x13UpdateTableMetadata\xdaA\x11table,update_mask\x82\xd3\xe4\x93\x02920/v2/{table.name=projects/*/instances/*/tables/*}:\x05table\x12\x8e\x01\n\x0bDeleteTable\x12,.google.bigtable.admin.v2.DeleteTableRequest\x1a\x16.google.protobuf.Empty"9\xdaA\x04name\x82\xd3\xe4\x93\x02,**/v2/{name=projects/*/instances/*/tables/*}\x12\xc6\x01\n\rUndeleteTable\x12..google.bigtable.admin.v2.UndeleteTableRequest\x1a\x1d.google.longrunning.Operation"f\xcaA\x1e\n\x05Table\x12\x15UndeleteTableMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028"3/v2/{name=projects/*/instances/*/tables/*}:undelete:\x01*\x12\xa1\x02\n\x14CreateAuthorizedView\x125.google.bigtable.admin.v2.CreateAuthorizedViewRequest\x1a\x1d.google.longrunning.Operation"\xb2\x01\xcaA.\n\x0eAuthorizedView\x12\x1cCreateAuthorizedViewMetadata\xdaA)parent,authorized_view,authorized_view_id\x82\xd3\xe4\x93\x02O"</v2/{parent=projects/*/instances/*/tables/*}/authorizedViews:\x0fauthorized_view\x12\xd1\x01\n\x13ListAuthorizedViews\x124.google.bigtable.admin.v2.ListAuthorizedViewsRequest\x1a5.google.bigtable.admin.v2.ListAuthorizedViewsResponse"M\xdaA\x06parent\x82\xd3\xe4\x93\x02>\x12</v2/{parent=projects/*/instances/*/tables/*}/authorizedViews\x12\xbe\x01\n\x11GetAuthorizedView\x122.google.bigtable.admin.v2.GetAuthorizedViewRequest\x1a(.google.bigtable.admin.v2.AuthorizedView"K\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v2/{name=projects/*/instances/*/tables/*/authorizedViews/*}\x12\xa3\x02\n\x14UpdateAuthorizedView\x125.google.bigtable.admin.v2.UpdateAuthorizedViewRequest\x1a\x1d.google.longrunning.Operation"\xb4\x01\xcaA.\n\x0eAuthorizedView\x12\x1cUpdateAuthorizedViewMetadata\xdaA\x1bauthorized_view,update_mask\x82\xd3\xe4\x93\x02_2L/v2/{authorized_view.name=projects/*/instances/*/tables/*/authorizedViews/*}:\x0fauthorized_view\x12\xb2\x01\n\x14DeleteAuthorizedView\x125.google.bigtable.admin.v2.DeleteAuthorizedViewRequest\x1a\x16.google.protobuf.Empty"K\xdaA\x04name\x82\xd3\xe4\x93\x02>*</v2/{name=projects/*/instances/*/tables/*/authorizedViews/*}\x12\xcf\x01\n\x14ModifyColumnFamilies\x125.google.bigtable.admin.v2.ModifyColumnFamiliesRequest\x1a\x1f.google.bigtable.admin.v2.Table"_\xdaA\x12name,modifications\x82\xd3\xe4\x93\x02D"?/v2/{name=projects/*/instances/*/tables/*}:modifyColumnFamilies:\x01*\x12\x99\x01\n\x0cDropRowRange\x12-.google.bigtable.admin.v2.DropRowRangeRequest\x1a\x16.google.protobuf.Empty"B\x82\xd3\xe4\x93\x02<"7/v2/{name=projects/*/instances/*/tables/*}:dropRowRange:\x01*\x12\xe8\x01\n\x18GenerateConsistencyToken\x129.google.bigtable.admin.v2.GenerateConsistencyTokenRequest\x1a:.google.bigtable.admin.v2.GenerateConsistencyTokenResponse"U\xdaA\x04name\x82\xd3\xe4\x93\x02H"C/v2/{name=projects/*/instances/*/tables/*}:generateConsistencyToken:\x01*\x12\xda\x01\n\x10CheckConsistency\x121.google.bigtable.admin.v2.CheckConsistencyRequest\x1a2.google.bigtable.admin.v2.CheckConsistencyResponse"_\xdaA\x16name,consistency_token\x82\xd3\xe4\x93\x02@";/v2/{name=projects/*/instances/*/tables/*}:checkConsistency:\x01*\x12\xea\x01\n\rSnapshotTable\x12..google.bigtable.admin.v2.SnapshotTableRequest\x1a\x1d.google.longrunning.Operation"\x89\x01\xcaA!\n\x08Snapshot\x12\x15SnapshotTableMetadata\xdaA$name,cluster,snapshot_id,description\x82\xd3\xe4\x93\x028"3/v2/{name=projects/*/instances/*/tables/*}:snapshot:\x01*\x12\xa8\x01\n\x0bGetSnapshot\x12,.google.bigtable.admin.v2.GetSnapshotRequest\x1a".google.bigtable.admin.v2.Snapshot"G\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v2/{name=projects/*/instances/*/clusters/*/snapshots/*}\x12\xbb\x01\n\rListSnapshots\x12..google.bigtable.admin.v2.ListSnapshotsRequest\x1a/.google.bigtable.admin.v2.ListSnapshotsResponse"I\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v2/{parent=projects/*/instances/*/clusters/*}/snapshots\x12\xa2\x01\n\x0eDeleteSnapshot\x12/.google.bigtable.admin.v2.DeleteSnapshotRequest\x1a\x16.google.protobuf.Empty"G\xdaA\x04name\x82\xd3\xe4\x93\x02:*8/v2/{name=projects/*/instances/*/clusters/*/snapshots/*}\x12\xe0\x01\n\x0cCreateBackup\x12-.google.bigtable.admin.v2.CreateBackupRequest\x1a\x1d.google.longrunning.Operation"\x81\x01\xcaA\x1e\n\x06Backup\x12\x14CreateBackupMetadata\xdaA\x17parent,backup_id,backup\x82\xd3\xe4\x93\x02@"6/v2/{parent=projects/*/instances/*/clusters/*}/backups:\x06backup\x12\xa0\x01\n\tGetBackup\x12*.google.bigtable.admin.v2.GetBackupRequest\x1a .google.bigtable.admin.v2.Backup"E\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v2/{name=projects/*/instances/*/clusters/*/backups/*}\x12\xc3\x01\n\x0cUpdateBackup\x12-.google.bigtable.admin.v2.UpdateBackupRequest\x1a .google.bigtable.admin.v2.Backup"b\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02G2=/v2/{backup.name=projects/*/instances/*/clusters/*/backups/*}:\x06backup\x12\x9c\x01\n\x0cDeleteBackup\x12-.google.bigtable.admin.v2.DeleteBackupRequest\x1a\x16.google.protobuf.Empty"E\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v2/{name=projects/*/instances/*/clusters/*/backups/*}\x12\xb3\x01\n\x0bListBackups\x12,.google.bigtable.admin.v2.ListBackupsRequest\x1a-.google.bigtable.admin.v2.ListBackupsResponse"G\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v2/{parent=projects/*/instances/*/clusters/*}/backups\x12\xbb\x01\n\x0cRestoreTable\x12-.google.bigtable.admin.v2.RestoreTableRequest\x1a\x1d.google.longrunning.Operation"]\xcaA\x1d\n\x05Table\x12\x14RestoreTableMetadata\x82\xd3\xe4\x93\x027"2/v2/{parent=projects/*/instances/*}/tables:restore:\x01*\x12\xed\x01\n\nCopyBackup\x12+.google.bigtable.admin.v2.CopyBackupRequest\x1a\x1d.google.longrunning.Operation"\x92\x01\xcaA\x1c\n\x06Backup\x12\x12CopyBackupMetadata\xdaA*parent,backup_id,source_backup,expire_time\x82\xd3\xe4\x93\x02@";/v2/{parent=projects/*/instances/*/clusters/*}/backups:copy:\x01*\x12\x92\x03\n\x0cGetIamPolicy\x12".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"\xc6\x02\xdaA\x08resource\x82\xd3\xe4\x93\x02\xb4\x02";/v2/{resource=projects/*/instances/*/tables/*}:getIamPolicy:\x01*ZL"G/v2/{resource=projects/*/instances/*/clusters/*/backups/*}:getIamPolicy:\x01*ZR"M/v2/{resource=projects/*/instances/*/tables/*/authorizedViews/*}:getIamPolicy:\x01*ZP"K/v2/{resource=projects/*/instances/*/tables/*/schemaBundles/*}:getIamPolicy:\x01*\x12\x99\x03\n\x0cSetIamPolicy\x12".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"\xcd\x02\xdaA\x0fresource,policy\x82\xd3\xe4\x93\x02\xb4\x02";/v2/{resource=projects/*/instances/*/tables/*}:setIamPolicy:\x01*ZL"G/v2/{resource=projects/*/instances/*/clusters/*/backups/*}:setIamPolicy:\x01*ZR"M/v2/{resource=projects/*/instances/*/tables/*/authorizedViews/*}:setIamPolicy:\x01*ZP"K/v2/{resource=projects/*/instances/*/tables/*/schemaBundles/*}:setIamPolicy:\x01*\x12\xd6\x03\n\x12TestIamPermissions\x12(.google.iam.v1.TestIamPermissionsRequest\x1a).google.iam.v1.TestIamPermissionsResponse"\xea\x02\xdaA\x14resource,permissions\x82\xd3\xe4\x93\x02\xcc\x02"A/v2/{resource=projects/*/instances/*/tables/*}:testIamPermissions:\x01*ZR"M/v2/{resource=projects/*/instances/*/clusters/*/backups/*}:testIamPermissions:\x01*ZX"S/v2/{resource=projects/*/instances/*/tables/*/authorizedViews/*}:testIamPermissions:\x01*ZV"Q/v2/{resource=projects/*/instances/*/tables/*/schemaBundles/*}:testIamPermissions:\x01*\x12\x91\x02\n\x12CreateSchemaBundle\x123.google.bigtable.admin.v2.CreateSchemaBundleRequest\x1a\x1d.google.longrunning.Operation"\xa6\x01\xcaA*\n\x0cSchemaBundle\x12\x1aCreateSchemaBundleMetadata\xdaA%parent,schema_bundle_id,schema_bundle\x82\xd3\xe4\x93\x02K":/v2/{parent=projects/*/instances/*/tables/*}/schemaBundles:\rschema_bundle\x12\x93\x02\n\x12UpdateSchemaBundle\x123.google.bigtable.admin.v2.UpdateSchemaBundleRequest\x1a\x1d.google.longrunning.Operation"\xa8\x01\xcaA*\n\x0cSchemaBundle\x12\x1aUpdateSchemaBundleMetadata\xdaA\x19schema_bundle,update_mask\x82\xd3\xe4\x93\x02Y2H/v2/{schema_bundle.name=projects/*/instances/*/tables/*/schemaBundles/*}:\rschema_bundle\x12\xb6\x01\n\x0fGetSchemaBundle\x120.google.bigtable.admin.v2.GetSchemaBundleRequest\x1a&.google.bigtable.admin.v2.SchemaBundle"I\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v2/{name=projects/*/instances/*/tables/*/schemaBundles/*}\x12\xc9\x01\n\x11ListSchemaBundles\x122.google.bigtable.admin.v2.ListSchemaBundlesRequest\x1a3.google.bigtable.admin.v2.ListSchemaBundlesResponse"K\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v2/{parent=projects/*/instances/*/tables/*}/schemaBundles\x12\xac\x01\n\x12DeleteSchemaBundle\x123.google.bigtable.admin.v2.DeleteSchemaBundleRequest\x1a\x16.google.protobuf.Empty"I\xdaA\x04name\x82\xd3\xe4\x93\x02<*:/v2/{name=projects/*/instances/*/tables/*/schemaBundles/*}\x1a\xde\x02\xcaA\x1cbigtableadmin.googleapis.com\xd2A\xbb\x02https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.admin.table,https://www.googleapis.com/auth/cloud-bigtable.admin,https://www.googleapis.com/auth/cloud-bigtable.admin.table,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/cloud-platform.read-onlyB\xda\x01\n\x1ccom.google.bigtable.admin.v2B\x17BigtableTableAdminProtoP\x01Z8cloud.google.com/go/bigtable/admin/apiv2/adminpb;adminpb\xaa\x02\x1eGoogle.Cloud.Bigtable.Admin.V2\xca\x02\x1eGoogle\\Cloud\\Bigtable\\Admin\\V2\xea\x02"Google::Cloud::Bigtable::Admin::V2b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.bigtable.admin.v2.bigtable_table_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1ccom.google.bigtable.admin.v2B\x17BigtableTableAdminProtoP\x01Z8cloud.google.com/go/bigtable/admin/apiv2/adminpb;adminpb\xaa\x02\x1eGoogle.Cloud.Bigtable.Admin.V2\xca\x02\x1eGoogle\\Cloud\\Bigtable\\Admin\\V2\xea\x02"Google::Cloud::Bigtable::Admin::V2'
    _globals['_RESTORETABLEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_RESTORETABLEREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_RESTORETABLEREQUEST'].fields_by_name['table_id']._loaded_options = None
    _globals['_RESTORETABLEREQUEST'].fields_by_name['table_id']._serialized_options = b'\xe0A\x02'
    _globals['_RESTORETABLEREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_RESTORETABLEREQUEST'].fields_by_name['backup']._serialized_options = b'\xfaA%\n#bigtableadmin.googleapis.com/Backup'
    _globals['_CREATETABLEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATETABLEREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_CREATETABLEREQUEST'].fields_by_name['table_id']._loaded_options = None
    _globals['_CREATETABLEREQUEST'].fields_by_name['table_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETABLEREQUEST'].fields_by_name['table']._loaded_options = None
    _globals['_CREATETABLEREQUEST'].fields_by_name['table']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST'].fields_by_name['table_id']._loaded_options = None
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST'].fields_by_name['table_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST'].fields_by_name['source_snapshot']._loaded_options = None
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST'].fields_by_name['source_snapshot']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Snapshot"
    _globals['_DROPROWRANGEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DROPROWRANGEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_LISTTABLESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTTABLESREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_GETTABLEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETTABLEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_UPDATETABLEREQUEST'].fields_by_name['table']._loaded_options = None
    _globals['_UPDATETABLEREQUEST'].fields_by_name['table']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATETABLEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATETABLEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATETABLEREQUEST'].fields_by_name['ignore_warnings']._loaded_options = None
    _globals['_UPDATETABLEREQUEST'].fields_by_name['ignore_warnings']._serialized_options = b'\xe0A\x01'
    _globals['_DELETETABLEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETETABLEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_UNDELETETABLEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UNDELETETABLEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_MODIFYCOLUMNFAMILIESREQUEST_MODIFICATION'].fields_by_name['update_mask']._loaded_options = None
    _globals['_MODIFYCOLUMNFAMILIESREQUEST_MODIFICATION'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_MODIFYCOLUMNFAMILIESREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_MODIFYCOLUMNFAMILIESREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_MODIFYCOLUMNFAMILIESREQUEST'].fields_by_name['modifications']._loaded_options = None
    _globals['_MODIFYCOLUMNFAMILIESREQUEST'].fields_by_name['modifications']._serialized_options = b'\xe0A\x02'
    _globals['_MODIFYCOLUMNFAMILIESREQUEST'].fields_by_name['ignore_warnings']._loaded_options = None
    _globals['_MODIFYCOLUMNFAMILIESREQUEST'].fields_by_name['ignore_warnings']._serialized_options = b'\xe0A\x01'
    _globals['_GENERATECONSISTENCYTOKENREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GENERATECONSISTENCYTOKENREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_CHECKCONSISTENCYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CHECKCONSISTENCYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_CHECKCONSISTENCYREQUEST'].fields_by_name['consistency_token']._loaded_options = None
    _globals['_CHECKCONSISTENCYREQUEST'].fields_by_name['consistency_token']._serialized_options = b'\xe0A\x02'
    _globals['_SNAPSHOTTABLEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_SNAPSHOTTABLEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_SNAPSHOTTABLEREQUEST'].fields_by_name['cluster']._loaded_options = None
    _globals['_SNAPSHOTTABLEREQUEST'].fields_by_name['cluster']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_SNAPSHOTTABLEREQUEST'].fields_by_name['snapshot_id']._loaded_options = None
    _globals['_SNAPSHOTTABLEREQUEST'].fields_by_name['snapshot_id']._serialized_options = b'\xe0A\x02'
    _globals['_GETSNAPSHOTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSNAPSHOTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Snapshot"
    _globals['_LISTSNAPSHOTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSNAPSHOTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_DELETESNAPSHOTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESNAPSHOTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Snapshot"
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#bigtableadmin.googleapis.com/Backup'
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#bigtableadmin.googleapis.com/Backup'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_COPYBACKUPREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_COPYBACKUPREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_COPYBACKUPREQUEST'].fields_by_name['backup_id']._loaded_options = None
    _globals['_COPYBACKUPREQUEST'].fields_by_name['backup_id']._serialized_options = b'\xe0A\x02'
    _globals['_COPYBACKUPREQUEST'].fields_by_name['source_backup']._loaded_options = None
    _globals['_COPYBACKUPREQUEST'].fields_by_name['source_backup']._serialized_options = b'\xe0A\x02\xfaA%\n#bigtableadmin.googleapis.com/Backup'
    _globals['_COPYBACKUPREQUEST'].fields_by_name['expire_time']._loaded_options = None
    _globals['_COPYBACKUPREQUEST'].fields_by_name['expire_time']._serialized_options = b'\xe0A\x02'
    _globals['_COPYBACKUPMETADATA'].fields_by_name['name']._loaded_options = None
    _globals['_COPYBACKUPMETADATA'].fields_by_name['name']._serialized_options = b'\xfaA%\n#bigtableadmin.googleapis.com/Backup'
    _globals['_CREATEAUTHORIZEDVIEWREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEAUTHORIZEDVIEWREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+bigtableadmin.googleapis.com/AuthorizedView'
    _globals['_CREATEAUTHORIZEDVIEWREQUEST'].fields_by_name['authorized_view_id']._loaded_options = None
    _globals['_CREATEAUTHORIZEDVIEWREQUEST'].fields_by_name['authorized_view_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEAUTHORIZEDVIEWREQUEST'].fields_by_name['authorized_view']._loaded_options = None
    _globals['_CREATEAUTHORIZEDVIEWREQUEST'].fields_by_name['authorized_view']._serialized_options = b'\xe0A\x02'
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+bigtableadmin.googleapis.com/AuthorizedView'
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['view']._loaded_options = None
    _globals['_LISTAUTHORIZEDVIEWSREQUEST'].fields_by_name['view']._serialized_options = b'\xe0A\x01'
    _globals['_GETAUTHORIZEDVIEWREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETAUTHORIZEDVIEWREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+bigtableadmin.googleapis.com/AuthorizedView'
    _globals['_GETAUTHORIZEDVIEWREQUEST'].fields_by_name['view']._loaded_options = None
    _globals['_GETAUTHORIZEDVIEWREQUEST'].fields_by_name['view']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST'].fields_by_name['authorized_view']._loaded_options = None
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST'].fields_by_name['authorized_view']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST'].fields_by_name['ignore_warnings']._loaded_options = None
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST'].fields_by_name['ignore_warnings']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEAUTHORIZEDVIEWREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEAUTHORIZEDVIEWREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+bigtableadmin.googleapis.com/AuthorizedView'
    _globals['_DELETEAUTHORIZEDVIEWREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEAUTHORIZEDVIEWREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_CREATESCHEMABUNDLEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESCHEMABUNDLEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"bigtableadmin.googleapis.com/Table'
    _globals['_CREATESCHEMABUNDLEREQUEST'].fields_by_name['schema_bundle_id']._loaded_options = None
    _globals['_CREATESCHEMABUNDLEREQUEST'].fields_by_name['schema_bundle_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESCHEMABUNDLEREQUEST'].fields_by_name['schema_bundle']._loaded_options = None
    _globals['_CREATESCHEMABUNDLEREQUEST'].fields_by_name['schema_bundle']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESCHEMABUNDLEREQUEST'].fields_by_name['schema_bundle']._loaded_options = None
    _globals['_UPDATESCHEMABUNDLEREQUEST'].fields_by_name['schema_bundle']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESCHEMABUNDLEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATESCHEMABUNDLEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESCHEMABUNDLEREQUEST'].fields_by_name['ignore_warnings']._loaded_options = None
    _globals['_UPDATESCHEMABUNDLEREQUEST'].fields_by_name['ignore_warnings']._serialized_options = b'\xe0A\x01'
    _globals['_GETSCHEMABUNDLEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSCHEMABUNDLEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)bigtableadmin.googleapis.com/SchemaBundle'
    _globals['_LISTSCHEMABUNDLESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSCHEMABUNDLESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\x12)bigtableadmin.googleapis.com/SchemaBundle'
    _globals['_DELETESCHEMABUNDLEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESCHEMABUNDLEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)bigtableadmin.googleapis.com/SchemaBundle'
    _globals['_DELETESCHEMABUNDLEREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETESCHEMABUNDLEREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_BIGTABLETABLEADMIN']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN']._serialized_options = b'\xcaA\x1cbigtableadmin.googleapis.com\xd2A\xbb\x02https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.admin.table,https://www.googleapis.com/auth/cloud-bigtable.admin,https://www.googleapis.com/auth/cloud-bigtable.admin.table,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/cloud-platform.read-only'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateTable']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateTable']._serialized_options = b'\xdaA\x15parent,table_id,table\x82\xd3\xe4\x93\x02/"*/v2/{parent=projects/*/instances/*}/tables:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateTableFromSnapshot']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateTableFromSnapshot']._serialized_options = b'\xcaA(\n\x05Table\x12\x1fCreateTableFromSnapshotMetadata\xdaA\x1fparent,table_id,source_snapshot\x82\xd3\xe4\x93\x02B"=/v2/{parent=projects/*/instances/*}/tables:createFromSnapshot:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListTables']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListTables']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02,\x12*/v2/{parent=projects/*/instances/*}/tables'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetTable']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetTable']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02,\x12*/v2/{name=projects/*/instances/*/tables/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateTable']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateTable']._serialized_options = b'\xcaA\x1c\n\x05Table\x12\x13UpdateTableMetadata\xdaA\x11table,update_mask\x82\xd3\xe4\x93\x02920/v2/{table.name=projects/*/instances/*/tables/*}:\x05table'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteTable']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteTable']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02,**/v2/{name=projects/*/instances/*/tables/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UndeleteTable']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UndeleteTable']._serialized_options = b'\xcaA\x1e\n\x05Table\x12\x15UndeleteTableMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028"3/v2/{name=projects/*/instances/*/tables/*}:undelete:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateAuthorizedView']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateAuthorizedView']._serialized_options = b'\xcaA.\n\x0eAuthorizedView\x12\x1cCreateAuthorizedViewMetadata\xdaA)parent,authorized_view,authorized_view_id\x82\xd3\xe4\x93\x02O"</v2/{parent=projects/*/instances/*/tables/*}/authorizedViews:\x0fauthorized_view'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListAuthorizedViews']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListAuthorizedViews']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02>\x12</v2/{parent=projects/*/instances/*/tables/*}/authorizedViews'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetAuthorizedView']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetAuthorizedView']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v2/{name=projects/*/instances/*/tables/*/authorizedViews/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateAuthorizedView']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateAuthorizedView']._serialized_options = b'\xcaA.\n\x0eAuthorizedView\x12\x1cUpdateAuthorizedViewMetadata\xdaA\x1bauthorized_view,update_mask\x82\xd3\xe4\x93\x02_2L/v2/{authorized_view.name=projects/*/instances/*/tables/*/authorizedViews/*}:\x0fauthorized_view'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteAuthorizedView']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteAuthorizedView']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02>*</v2/{name=projects/*/instances/*/tables/*/authorizedViews/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ModifyColumnFamilies']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ModifyColumnFamilies']._serialized_options = b'\xdaA\x12name,modifications\x82\xd3\xe4\x93\x02D"?/v2/{name=projects/*/instances/*/tables/*}:modifyColumnFamilies:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DropRowRange']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DropRowRange']._serialized_options = b'\x82\xd3\xe4\x93\x02<"7/v2/{name=projects/*/instances/*/tables/*}:dropRowRange:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GenerateConsistencyToken']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GenerateConsistencyToken']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02H"C/v2/{name=projects/*/instances/*/tables/*}:generateConsistencyToken:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CheckConsistency']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CheckConsistency']._serialized_options = b'\xdaA\x16name,consistency_token\x82\xd3\xe4\x93\x02@";/v2/{name=projects/*/instances/*/tables/*}:checkConsistency:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['SnapshotTable']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['SnapshotTable']._serialized_options = b'\xcaA!\n\x08Snapshot\x12\x15SnapshotTableMetadata\xdaA$name,cluster,snapshot_id,description\x82\xd3\xe4\x93\x028"3/v2/{name=projects/*/instances/*/tables/*}:snapshot:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetSnapshot']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetSnapshot']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v2/{name=projects/*/instances/*/clusters/*/snapshots/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListSnapshots']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListSnapshots']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v2/{parent=projects/*/instances/*/clusters/*}/snapshots'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteSnapshot']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteSnapshot']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02:*8/v2/{name=projects/*/instances/*/clusters/*/snapshots/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateBackup']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateBackup']._serialized_options = b'\xcaA\x1e\n\x06Backup\x12\x14CreateBackupMetadata\xdaA\x17parent,backup_id,backup\x82\xd3\xe4\x93\x02@"6/v2/{parent=projects/*/instances/*/clusters/*}/backups:\x06backup'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetBackup']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetBackup']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v2/{name=projects/*/instances/*/clusters/*/backups/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateBackup']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateBackup']._serialized_options = b'\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02G2=/v2/{backup.name=projects/*/instances/*/clusters/*/backups/*}:\x06backup'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteBackup']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteBackup']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v2/{name=projects/*/instances/*/clusters/*/backups/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListBackups']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListBackups']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v2/{parent=projects/*/instances/*/clusters/*}/backups'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['RestoreTable']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['RestoreTable']._serialized_options = b'\xcaA\x1d\n\x05Table\x12\x14RestoreTableMetadata\x82\xd3\xe4\x93\x027"2/v2/{parent=projects/*/instances/*}/tables:restore:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CopyBackup']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CopyBackup']._serialized_options = b'\xcaA\x1c\n\x06Backup\x12\x12CopyBackupMetadata\xdaA*parent,backup_id,source_backup,expire_time\x82\xd3\xe4\x93\x02@";/v2/{parent=projects/*/instances/*/clusters/*}/backups:copy:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetIamPolicy']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetIamPolicy']._serialized_options = b'\xdaA\x08resource\x82\xd3\xe4\x93\x02\xb4\x02";/v2/{resource=projects/*/instances/*/tables/*}:getIamPolicy:\x01*ZL"G/v2/{resource=projects/*/instances/*/clusters/*/backups/*}:getIamPolicy:\x01*ZR"M/v2/{resource=projects/*/instances/*/tables/*/authorizedViews/*}:getIamPolicy:\x01*ZP"K/v2/{resource=projects/*/instances/*/tables/*/schemaBundles/*}:getIamPolicy:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['SetIamPolicy']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['SetIamPolicy']._serialized_options = b'\xdaA\x0fresource,policy\x82\xd3\xe4\x93\x02\xb4\x02";/v2/{resource=projects/*/instances/*/tables/*}:setIamPolicy:\x01*ZL"G/v2/{resource=projects/*/instances/*/clusters/*/backups/*}:setIamPolicy:\x01*ZR"M/v2/{resource=projects/*/instances/*/tables/*/authorizedViews/*}:setIamPolicy:\x01*ZP"K/v2/{resource=projects/*/instances/*/tables/*/schemaBundles/*}:setIamPolicy:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['TestIamPermissions']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['TestIamPermissions']._serialized_options = b'\xdaA\x14resource,permissions\x82\xd3\xe4\x93\x02\xcc\x02"A/v2/{resource=projects/*/instances/*/tables/*}:testIamPermissions:\x01*ZR"M/v2/{resource=projects/*/instances/*/clusters/*/backups/*}:testIamPermissions:\x01*ZX"S/v2/{resource=projects/*/instances/*/tables/*/authorizedViews/*}:testIamPermissions:\x01*ZV"Q/v2/{resource=projects/*/instances/*/tables/*/schemaBundles/*}:testIamPermissions:\x01*'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateSchemaBundle']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['CreateSchemaBundle']._serialized_options = b'\xcaA*\n\x0cSchemaBundle\x12\x1aCreateSchemaBundleMetadata\xdaA%parent,schema_bundle_id,schema_bundle\x82\xd3\xe4\x93\x02K":/v2/{parent=projects/*/instances/*/tables/*}/schemaBundles:\rschema_bundle'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateSchemaBundle']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['UpdateSchemaBundle']._serialized_options = b'\xcaA*\n\x0cSchemaBundle\x12\x1aUpdateSchemaBundleMetadata\xdaA\x19schema_bundle,update_mask\x82\xd3\xe4\x93\x02Y2H/v2/{schema_bundle.name=projects/*/instances/*/tables/*/schemaBundles/*}:\rschema_bundle'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetSchemaBundle']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['GetSchemaBundle']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v2/{name=projects/*/instances/*/tables/*/schemaBundles/*}'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListSchemaBundles']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['ListSchemaBundles']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v2/{parent=projects/*/instances/*/tables/*}/schemaBundles'
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteSchemaBundle']._loaded_options = None
    _globals['_BIGTABLETABLEADMIN'].methods_by_name['DeleteSchemaBundle']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02<*:/v2/{name=projects/*/instances/*/tables/*/schemaBundles/*}'
    _globals['_RESTORETABLEREQUEST']._serialized_start = 499
    _globals['_RESTORETABLEREQUEST']._serialized_end = 676
    _globals['_RESTORETABLEMETADATA']._serialized_start = 679
    _globals['_RESTORETABLEMETADATA']._serialized_end = 959
    _globals['_OPTIMIZERESTOREDTABLEMETADATA']._serialized_start = 961
    _globals['_OPTIMIZERESTOREDTABLEMETADATA']._serialized_end = 1069
    _globals['_CREATETABLEREQUEST']._serialized_start = 1072
    _globals['_CREATETABLEREQUEST']._serialized_end = 1329
    _globals['_CREATETABLEREQUEST_SPLIT']._serialized_start = 1309
    _globals['_CREATETABLEREQUEST_SPLIT']._serialized_end = 1329
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST']._serialized_start = 1332
    _globals['_CREATETABLEFROMSNAPSHOTREQUEST']._serialized_end = 1522
    _globals['_DROPROWRANGEREQUEST']._serialized_start = 1525
    _globals['_DROPROWRANGEREQUEST']._serialized_end = 1678
    _globals['_LISTTABLESREQUEST']._serialized_start = 1681
    _globals['_LISTTABLESREQUEST']._serialized_end = 1854
    _globals['_LISTTABLESRESPONSE']._serialized_start = 1856
    _globals['_LISTTABLESRESPONSE']._serialized_end = 1950
    _globals['_GETTABLEREQUEST']._serialized_start = 1952
    _globals['_GETTABLEREQUEST']._serialized_end = 2079
    _globals['_UPDATETABLEREQUEST']._serialized_start = 2082
    _globals['_UPDATETABLEREQUEST']._serialized_end = 2239
    _globals['_UPDATETABLEMETADATA']._serialized_start = 2242
    _globals['_UPDATETABLEMETADATA']._serialized_end = 2371
    _globals['_DELETETABLEREQUEST']._serialized_start = 2373
    _globals['_DELETETABLEREQUEST']._serialized_end = 2451
    _globals['_UNDELETETABLEREQUEST']._serialized_start = 2453
    _globals['_UNDELETETABLEREQUEST']._serialized_end = 2533
    _globals['_UNDELETETABLEMETADATA']._serialized_start = 2536
    _globals['_UNDELETETABLEMETADATA']._serialized_end = 2667
    _globals['_MODIFYCOLUMNFAMILIESREQUEST']._serialized_start = 2670
    _globals['_MODIFYCOLUMNFAMILIESREQUEST']._serialized_end = 3105
    _globals['_MODIFYCOLUMNFAMILIESREQUEST_MODIFICATION']._serialized_start = 2886
    _globals['_MODIFYCOLUMNFAMILIESREQUEST_MODIFICATION']._serialized_end = 3105
    _globals['_GENERATECONSISTENCYTOKENREQUEST']._serialized_start = 3107
    _globals['_GENERATECONSISTENCYTOKENREQUEST']._serialized_end = 3198
    _globals['_GENERATECONSISTENCYTOKENRESPONSE']._serialized_start = 3200
    _globals['_GENERATECONSISTENCYTOKENRESPONSE']._serialized_end = 3261
    _globals['_CHECKCONSISTENCYREQUEST']._serialized_start = 3264
    _globals['_CHECKCONSISTENCYREQUEST']._serialized_end = 3570
    _globals['_STANDARDREADREMOTEWRITES']._serialized_start = 3572
    _globals['_STANDARDREADREMOTEWRITES']._serialized_end = 3598
    _globals['_DATABOOSTREADLOCALWRITES']._serialized_start = 3600
    _globals['_DATABOOSTREADLOCALWRITES']._serialized_end = 3626
    _globals['_CHECKCONSISTENCYRESPONSE']._serialized_start = 3628
    _globals['_CHECKCONSISTENCYRESPONSE']._serialized_end = 3674
    _globals['_SNAPSHOTTABLEREQUEST']._serialized_start = 3677
    _globals['_SNAPSHOTTABLEREQUEST']._serialized_end = 3907
    _globals['_GETSNAPSHOTREQUEST']._serialized_start = 3909
    _globals['_GETSNAPSHOTREQUEST']._serialized_end = 3990
    _globals['_LISTSNAPSHOTSREQUEST']._serialized_start = 3992
    _globals['_LISTSNAPSHOTSREQUEST']._serialized_end = 4115
    _globals['_LISTSNAPSHOTSRESPONSE']._serialized_start = 4117
    _globals['_LISTSNAPSHOTSRESPONSE']._serialized_end = 4220
    _globals['_DELETESNAPSHOTREQUEST']._serialized_start = 4222
    _globals['_DELETESNAPSHOTREQUEST']._serialized_end = 4306
    _globals['_SNAPSHOTTABLEMETADATA']._serialized_start = 4309
    _globals['_SNAPSHOTTABLEMETADATA']._serialized_end = 4505
    _globals['_CREATETABLEFROMSNAPSHOTMETADATA']._serialized_start = 4508
    _globals['_CREATETABLEFROMSNAPSHOTMETADATA']._serialized_end = 4724
    _globals['_CREATEBACKUPREQUEST']._serialized_start = 4727
    _globals['_CREATEBACKUPREQUEST']._serialized_end = 4889
    _globals['_CREATEBACKUPMETADATA']._serialized_start = 4892
    _globals['_CREATEBACKUPMETADATA']._serialized_end = 5044
    _globals['_UPDATEBACKUPREQUEST']._serialized_start = 5047
    _globals['_UPDATEBACKUPREQUEST']._serialized_end = 5177
    _globals['_GETBACKUPREQUEST']._serialized_start = 5179
    _globals['_GETBACKUPREQUEST']._serialized_end = 5256
    _globals['_DELETEBACKUPREQUEST']._serialized_start = 5258
    _globals['_DELETEBACKUPREQUEST']._serialized_end = 5338
    _globals['_LISTBACKUPSREQUEST']._serialized_start = 5341
    _globals['_LISTBACKUPSREQUEST']._serialized_end = 5496
    _globals['_LISTBACKUPSRESPONSE']._serialized_start = 5498
    _globals['_LISTBACKUPSRESPONSE']._serialized_end = 5595
    _globals['_COPYBACKUPREQUEST']._serialized_start = 5598
    _globals['_COPYBACKUPREQUEST']._serialized_end = 5825
    _globals['_COPYBACKUPMETADATA']._serialized_start = 5828
    _globals['_COPYBACKUPMETADATA']._serialized_end = 6033
    _globals['_CREATEAUTHORIZEDVIEWREQUEST']._serialized_start = 6036
    _globals['_CREATEAUTHORIZEDVIEWREQUEST']._serialized_end = 6239
    _globals['_CREATEAUTHORIZEDVIEWMETADATA']._serialized_start = 6242
    _globals['_CREATEAUTHORIZEDVIEWMETADATA']._serialized_end = 6452
    _globals['_LISTAUTHORIZEDVIEWSREQUEST']._serialized_start = 6455
    _globals['_LISTAUTHORIZEDVIEWSREQUEST']._serialized_end = 6675
    _globals['_LISTAUTHORIZEDVIEWSRESPONSE']._serialized_start = 6677
    _globals['_LISTAUTHORIZEDVIEWSRESPONSE']._serialized_end = 6799
    _globals['_GETAUTHORIZEDVIEWREQUEST']._serialized_start = 6802
    _globals['_GETAUTHORIZEDVIEWREQUEST']._serialized_end = 6969
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST']._serialized_start = 6972
    _globals['_UPDATEAUTHORIZEDVIEWREQUEST']._serialized_end = 7157
    _globals['_UPDATEAUTHORIZEDVIEWMETADATA']._serialized_start = 7160
    _globals['_UPDATEAUTHORIZEDVIEWMETADATA']._serialized_end = 7370
    _globals['_DELETEAUTHORIZEDVIEWREQUEST']._serialized_start = 7372
    _globals['_DELETEAUTHORIZEDVIEWREQUEST']._serialized_end = 7487
    _globals['_CREATESCHEMABUNDLEREQUEST']._serialized_start = 7490
    _globals['_CREATESCHEMABUNDLEREQUEST']._serialized_end = 7676
    _globals['_CREATESCHEMABUNDLEMETADATA']._serialized_start = 7679
    _globals['_CREATESCHEMABUNDLEMETADATA']._serialized_end = 7815
    _globals['_UPDATESCHEMABUNDLEREQUEST']._serialized_start = 7818
    _globals['_UPDATESCHEMABUNDLEREQUEST']._serialized_end = 7997
    _globals['_UPDATESCHEMABUNDLEMETADATA']._serialized_start = 8000
    _globals['_UPDATESCHEMABUNDLEMETADATA']._serialized_end = 8136
    _globals['_GETSCHEMABUNDLEREQUEST']._serialized_start = 8138
    _globals['_GETSCHEMABUNDLEREQUEST']._serialized_end = 8227
    _globals['_LISTSCHEMABUNDLESREQUEST']._serialized_start = 8230
    _globals['_LISTSCHEMABUNDLESREQUEST']._serialized_end = 8362
    _globals['_LISTSCHEMABUNDLESRESPONSE']._serialized_start = 8364
    _globals['_LISTSCHEMABUNDLESRESPONSE']._serialized_end = 8480
    _globals['_DELETESCHEMABUNDLEREQUEST']._serialized_start = 8482
    _globals['_DELETESCHEMABUNDLEREQUEST']._serialized_end = 8593
    _globals['_BIGTABLETABLEADMIN']._serialized_start = 8596
    _globals['_BIGTABLETABLEADMIN']._serialized_end = 16806