"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/recommendationengine/v1beta1/recommendationengine_resources.proto')
_sym_db = _symbol_database.Default()
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNgoogle/cloud/recommendationengine/v1beta1/recommendationengine_resources.proto\x12)google.cloud.recommendationengine.v1beta1\x1a\x19google/api/resource.protoB\xac\x08\n-com.google.cloud.recommendationengine.v1beta1P\x01Zacloud.google.com/go/recommendationengine/apiv1beta1/recommendationenginepb;recommendationenginepb\xa2\x02\x05RECAI\xaa\x02)Google.Cloud.RecommendationEngine.V1Beta1\xca\x02)Google\\Cloud\\RecommendationEngine\\V1beta1\xea\x02,Google::Cloud::RecommendationEngine::V1beta1\xeaAi\n+recommendationengine.googleapis.com/Catalog\x12:projects/{project}/locations/{location}/catalogs/{catalog}\xeaA\x92\x01\n3recommendationengine.googleapis.com/CatalogItemPath\x12[projects/{project}/locations/{location}/catalogs/{catalog}/catalogItems/{catalog_item_path}\xeaA\x86\x01\n.recommendationengine.googleapis.com/EventStore\x12Tprojects/{project}/locations/{location}/catalogs/{catalog}/eventStores/{event_store}\xeaA\xd9\x01\n@recommendationengine.googleapis.com/PredictionApiKeyRegistration\x12\x94\x01projects/{project}/locations/{location}/catalogs/{catalog}/eventStores/{event_store}/predictionApiKeyRegistrations/{prediction_api_key_registration}\xeaA\x9c\x01\n-recommendationengine.googleapis.com/Placement\x12kprojects/{project}/locations/{location}/catalogs/{catalog}/eventStores/{event_store}/placements/{placement}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.recommendationengine.v1beta1.recommendationengine_resources_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n-com.google.cloud.recommendationengine.v1beta1P\x01Zacloud.google.com/go/recommendationengine/apiv1beta1/recommendationenginepb;recommendationenginepb\xa2\x02\x05RECAI\xaa\x02)Google.Cloud.RecommendationEngine.V1Beta1\xca\x02)Google\\Cloud\\RecommendationEngine\\V1beta1\xea\x02,Google::Cloud::RecommendationEngine::V1beta1\xeaAi\n+recommendationengine.googleapis.com/Catalog\x12:projects/{project}/locations/{location}/catalogs/{catalog}\xeaA\x92\x01\n3recommendationengine.googleapis.com/CatalogItemPath\x12[projects/{project}/locations/{location}/catalogs/{catalog}/catalogItems/{catalog_item_path}\xeaA\x86\x01\n.recommendationengine.googleapis.com/EventStore\x12Tprojects/{project}/locations/{location}/catalogs/{catalog}/eventStores/{event_store}\xeaA\xd9\x01\n@recommendationengine.googleapis.com/PredictionApiKeyRegistration\x12\x94\x01projects/{project}/locations/{location}/catalogs/{catalog}/eventStores/{event_store}/predictionApiKeyRegistrations/{prediction_api_key_registration}\xeaA\x9c\x01\n-recommendationengine.googleapis.com/Placement\x12kprojects/{project}/locations/{location}/catalogs/{catalog}/eventStores/{event_store}/placements/{placement}'