# coding: utf-8

# flake8: noqa

"""
    Rust Payroll System API  v1.0

    A high-performance, next-generation payroll management system API. This documentation provides detailed information on all available endpoints for managing employees, configuring payroll rules, and automating payroll runs. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "EmployeesApi",
    "PayrollAutomationApi",
    "RolesConfigurationApi",
    "PlaceholdersFutureFeaturesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateEmployee",
    "CreateRoleRequest",
    "Employee",
    "LeavePolicy",
    "LeavePolicyDeduction",
    "OvertimePolicy",
    "PayrollCalculationResult",
    "RoleConfiguration",
    "SalaryInfo",
]

# import apis into sdk package
from openapi_client.api.employees_api import EmployeesApi as EmployeesApi
from openapi_client.api.payroll_automation_api import PayrollAutomationApi as PayrollAutomationApi
from openapi_client.api.roles_configuration_api import RolesConfigurationApi as RolesConfigurationApi
from openapi_client.api.placeholders_future_features_api import PlaceholdersFutureFeaturesApi as PlaceholdersFutureFeaturesApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.create_employee import CreateEmployee as CreateEmployee
from openapi_client.models.create_role_request import CreateRoleRequest as CreateRoleRequest
from openapi_client.models.employee import Employee as Employee
from openapi_client.models.leave_policy import LeavePolicy as LeavePolicy
from openapi_client.models.leave_policy_deduction import LeavePolicyDeduction as LeavePolicyDeduction
from openapi_client.models.overtime_policy import OvertimePolicy as OvertimePolicy
from openapi_client.models.payroll_calculation_result import PayrollCalculationResult as PayrollCalculationResult
from openapi_client.models.role_configuration import RoleConfiguration as RoleConfiguration
from openapi_client.models.salary_info import SalaryInfo as SalaryInfo
