"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/kms/v1/service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.kms.v1 import resources_pb2 as google_dot_cloud_dot_kms_dot_v1_dot_resources__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!google/cloud/kms/v1/service.proto\x12\x13google.cloud.kms.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a#google/cloud/kms/v1/resources.proto\x1a google/protobuf/field_mask.proto\x1a\x1egoogle/protobuf/wrappers.proto"\xad\x01\n\x13ListKeyRingsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\xff\x01\n\x15ListCryptoKeysRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12P\n\x0cversion_view\x18\x04 \x01(\x0e2:.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionView\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x06 \x01(\tB\x03\xe0A\x01"\x80\x02\n\x1cListCryptoKeyVersionsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12H\n\x04view\x18\x04 \x01(\x0e2:.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionView\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x06 \x01(\tB\x03\xe0A\x01"\xad\x01\n\x15ListImportJobsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"t\n\x14ListKeyRingsResponse\x12/\n\tkey_rings\x18\x01 \x03(\x0b2\x1c.google.cloud.kms.v1.KeyRing\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x12\n\ntotal_size\x18\x03 \x01(\x05"z\n\x16ListCryptoKeysResponse\x123\n\x0bcrypto_keys\x18\x01 \x03(\x0b2\x1e.google.cloud.kms.v1.CryptoKey\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x12\n\ntotal_size\x18\x03 \x01(\x05"\x90\x01\n\x1dListCryptoKeyVersionsResponse\x12B\n\x13crypto_key_versions\x18\x01 \x03(\x0b2%.google.cloud.kms.v1.CryptoKeyVersion\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x12\n\ntotal_size\x18\x03 \x01(\x05"z\n\x16ListImportJobsResponse\x123\n\x0bimport_jobs\x18\x01 \x03(\x0b2\x1e.google.cloud.kms.v1.ImportJob\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x12\n\ntotal_size\x18\x03 \x01(\x05"J\n\x11GetKeyRingRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing"N\n\x13GetCryptoKeyRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey"\\\n\x1aGetCryptoKeyVersionRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion"\xa5\x01\n\x13GetPublicKeyRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion\x12N\n\x11public_key_format\x18\x02 \x01(\x0e2..google.cloud.kms.v1.PublicKey.PublicKeyFormatB\x03\xe0A\x01"N\n\x13GetImportJobRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/ImportJob"\xa0\x01\n\x14CreateKeyRingRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x18\n\x0bkey_ring_id\x18\x02 \x01(\tB\x03\xe0A\x02\x123\n\x08key_ring\x18\x03 \x01(\x0b2\x1c.google.cloud.kms.v1.KeyRingB\x03\xe0A\x02"\xcd\x01\n\x16CreateCryptoKeyRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing\x12\x1a\n\rcrypto_key_id\x18\x02 \x01(\tB\x03\xe0A\x02\x127\n\ncrypto_key\x18\x03 \x01(\x0b2\x1e.google.cloud.kms.v1.CryptoKeyB\x03\xe0A\x02\x12%\n\x1dskip_initial_version_creation\x18\x05 \x01(\x08"\xa2\x01\n\x1dCreateCryptoKeyVersionRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12F\n\x12crypto_key_version\x18\x02 \x01(\x0b2%.google.cloud.kms.v1.CryptoKeyVersionB\x03\xe0A\x02"\xf0\x02\n\x1dImportCryptoKeyVersionRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12L\n\x12crypto_key_version\x18\x06 \x01(\tB0\xe0A\x01\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion\x12W\n\talgorithm\x18\x02 \x01(\x0e2?.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionAlgorithmB\x03\xe0A\x02\x12\x17\n\nimport_job\x18\x04 \x01(\tB\x03\xe0A\x02\x12\x18\n\x0bwrapped_key\x18\x08 \x01(\x0cB\x03\xe0A\x01\x12"\n\x13rsa_aes_wrapped_key\x18\x05 \x01(\x0cB\x03\xe0A\x01H\x00B\x16\n\x14wrapped_key_material"\xa6\x01\n\x16CreateImportJobRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing\x12\x1a\n\rimport_job_id\x18\x02 \x01(\tB\x03\xe0A\x02\x127\n\nimport_job\x18\x03 \x01(\x0b2\x1e.google.cloud.kms.v1.ImportJobB\x03\xe0A\x02"\x87\x01\n\x16UpdateCryptoKeyRequest\x127\n\ncrypto_key\x18\x01 \x01(\x0b2\x1e.google.cloud.kms.v1.CryptoKeyB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\x9d\x01\n\x1dUpdateCryptoKeyVersionRequest\x12F\n\x12crypto_key_version\x18\x01 \x01(\x0b2%.google.cloud.kms.v1.CryptoKeyVersionB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\x83\x01\n$UpdateCryptoKeyPrimaryVersionRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12"\n\x15crypto_key_version_id\x18\x02 \x01(\tB\x03\xe0A\x02"`\n\x1eDestroyCryptoKeyVersionRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion"`\n\x1eRestoreCryptoKeyVersionRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion"\xf9\x01\n\x0eEncryptRequest\x12\x17\n\x04name\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12\x16\n\tplaintext\x18\x02 \x01(\x0cB\x03\xe0A\x02\x12*\n\x1dadditional_authenticated_data\x18\x03 \x01(\x0cB\x03\xe0A\x01\x12:\n\x10plaintext_crc32c\x18\x07 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12N\n$additional_authenticated_data_crc32c\x18\x08 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\x9b\x02\n\x0eDecryptRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12\x17\n\nciphertext\x18\x02 \x01(\x0cB\x03\xe0A\x02\x12*\n\x1dadditional_authenticated_data\x18\x03 \x01(\x0cB\x03\xe0A\x01\x12;\n\x11ciphertext_crc32c\x18\x05 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12N\n$additional_authenticated_data_crc32c\x18\x06 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\xe2\x02\n\x11RawEncryptRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\tplaintext\x18\x02 \x01(\x0cB\x03\xe0A\x02\x12*\n\x1dadditional_authenticated_data\x18\x03 \x01(\x0cB\x03\xe0A\x01\x12:\n\x10plaintext_crc32c\x18\x04 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12N\n$additional_authenticated_data_crc32c\x18\x05 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12"\n\x15initialization_vector\x18\x06 \x01(\x0cB\x03\xe0A\x01\x12F\n\x1cinitialization_vector_crc32c\x18\x07 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\xf8\x02\n\x11RawDecryptRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nciphertext\x18\x02 \x01(\x0cB\x03\xe0A\x02\x12*\n\x1dadditional_authenticated_data\x18\x03 \x01(\x0cB\x03\xe0A\x01\x12"\n\x15initialization_vector\x18\x04 \x01(\x0cB\x03\xe0A\x02\x12\x12\n\ntag_length\x18\x05 \x01(\x05\x12;\n\x11ciphertext_crc32c\x18\x06 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12N\n$additional_authenticated_data_crc32c\x18\x07 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12F\n\x1cinitialization_vector_crc32c\x18\x08 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\x8c\x02\n\x15AsymmetricSignRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion\x120\n\x06digest\x18\x03 \x01(\x0b2\x1b.google.cloud.kms.v1.DigestB\x03\xe0A\x01\x127\n\rdigest_crc32c\x18\x04 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12\x11\n\x04data\x18\x06 \x01(\x0cB\x03\xe0A\x01\x125\n\x0bdata_crc32c\x18\x07 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\xb0\x01\n\x18AsymmetricDecryptRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion\x12\x17\n\nciphertext\x18\x03 \x01(\x0cB\x03\xe0A\x02\x12;\n\x11ciphertext_crc32c\x18\x04 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\x9a\x01\n\x0eMacSignRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion\x12\x11\n\x04data\x18\x02 \x01(\x0cB\x03\xe0A\x02\x125\n\x0bdata_crc32c\x18\x03 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\xe4\x01\n\x10MacVerifyRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion\x12\x11\n\x04data\x18\x02 \x01(\x0cB\x03\xe0A\x02\x125\n\x0bdata_crc32c\x18\x03 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01\x12\x10\n\x03mac\x18\x04 \x01(\x0cB\x03\xe0A\x02\x124\n\nmac_crc32c\x18\x05 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\xaa\x01\n\x12DecapsulateRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion\x12\x17\n\nciphertext\x18\x02 \x01(\x0cB\x03\xe0A\x02\x12;\n\x11ciphertext_crc32c\x18\x03 \x01(\x0b2\x1b.google.protobuf.Int64ValueB\x03\xe0A\x01"\x84\x01\n\x1aGenerateRandomBytesRequest\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x14\n\x0clength_bytes\x18\x02 \x01(\x05\x12>\n\x10protection_level\x18\x03 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\x85\x02\n\x0fEncryptResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nciphertext\x18\x02 \x01(\x0c\x126\n\x11ciphertext_crc32c\x18\x04 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12!\n\x19verified_plaintext_crc32c\x18\x05 \x01(\x08\x125\n-verified_additional_authenticated_data_crc32c\x18\x06 \x01(\x08\x12>\n\x10protection_level\x18\x07 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\xb1\x01\n\x0fDecryptResponse\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\x125\n\x10plaintext_crc32c\x18\x02 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12\x14\n\x0cused_primary\x18\x03 \x01(\x08\x12>\n\x10protection_level\x18\x04 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\xad\x03\n\x12RawEncryptResponse\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\x12\x1d\n\x15initialization_vector\x18\x02 \x01(\x0c\x12\x12\n\ntag_length\x18\x03 \x01(\x05\x126\n\x11ciphertext_crc32c\x18\x04 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12A\n\x1cinitialization_vector_crc32c\x18\x05 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12!\n\x19verified_plaintext_crc32c\x18\x06 \x01(\x08\x125\n-verified_additional_authenticated_data_crc32c\x18\x07 \x01(\x08\x12-\n%verified_initialization_vector_crc32c\x18\n \x01(\x08\x12\x0c\n\x04name\x18\x08 \x01(\t\x12>\n\x10protection_level\x18\t \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\xa8\x02\n\x12RawDecryptResponse\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\x125\n\x10plaintext_crc32c\x18\x02 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12>\n\x10protection_level\x18\x03 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel\x12"\n\x1averified_ciphertext_crc32c\x18\x04 \x01(\x08\x125\n-verified_additional_authenticated_data_crc32c\x18\x05 \x01(\x08\x12-\n%verified_initialization_vector_crc32c\x18\x06 \x01(\x08"\xee\x01\n\x16AsymmetricSignResponse\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x125\n\x10signature_crc32c\x18\x02 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12\x1e\n\x16verified_digest_crc32c\x18\x03 \x01(\x08\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x1c\n\x14verified_data_crc32c\x18\x05 \x01(\x08\x12>\n\x10protection_level\x18\x06 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\xc9\x01\n\x19AsymmetricDecryptResponse\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\x125\n\x10plaintext_crc32c\x18\x02 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12"\n\x1averified_ciphertext_crc32c\x18\x03 \x01(\x08\x12>\n\x10protection_level\x18\x04 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\xbb\x01\n\x0fMacSignResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\x0c\x12/\n\nmac_crc32c\x18\x03 \x01(\x0b2\x1b.google.protobuf.Int64Value\x12\x1c\n\x14verified_data_crc32c\x18\x04 \x01(\x08\x12>\n\x10protection_level\x18\x05 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\xd1\x01\n\x11MacVerifyResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1c\n\x14verified_data_crc32c\x18\x03 \x01(\x08\x12\x1b\n\x13verified_mac_crc32c\x18\x04 \x01(\x08\x12"\n\x1averified_success_integrity\x18\x05 \x01(\x08\x12>\n\x10protection_level\x18\x06 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevel"\xda\x01\n\x13DecapsulateResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rshared_secret\x18\x02 \x01(\x0c\x12!\n\x14shared_secret_crc32c\x18\x03 \x01(\x03H\x00\x88\x01\x01\x12"\n\x1averified_ciphertext_crc32c\x18\x04 \x01(\x08\x12>\n\x10protection_level\x18\x05 \x01(\x0e2$.google.cloud.kms.v1.ProtectionLevelB\x17\n\x15_shared_secret_crc32c"]\n\x1bGenerateRandomBytesResponse\x12\x0c\n\x04data\x18\x01 \x01(\x0c\x120\n\x0bdata_crc32c\x18\x03 \x01(\x0b2\x1b.google.protobuf.Int64Value"H\n\x06Digest\x12\x10\n\x06sha256\x18\x01 \x01(\x0cH\x00\x12\x10\n\x06sha384\x18\x02 \x01(\x0cH\x00\x12\x10\n\x06sha512\x18\x03 \x01(\x0cH\x00B\x08\n\x06digest"@\n\x10LocationMetadata\x12\x15\n\rhsm_available\x18\x01 \x01(\x08\x12\x15\n\rekm_available\x18\x02 \x01(\x082\xd9/\n\x14KeyManagementService\x12\xa2\x01\n\x0cListKeyRings\x12(.google.cloud.kms.v1.ListKeyRingsRequest\x1a).google.cloud.kms.v1.ListKeyRingsResponse"=\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1/{parent=projects/*/locations/*}/keyRings\x12\xb5\x01\n\x0eListCryptoKeys\x12*.google.cloud.kms.v1.ListCryptoKeysRequest\x1a+.google.cloud.kms.v1.ListCryptoKeysResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/keyRings/*}/cryptoKeys\x12\xde\x01\n\x15ListCryptoKeyVersions\x121.google.cloud.kms.v1.ListCryptoKeyVersionsRequest\x1a2.google.cloud.kms.v1.ListCryptoKeyVersionsResponse"^\xdaA\x06parent\x82\xd3\xe4\x93\x02O\x12M/v1/{parent=projects/*/locations/*/keyRings/*/cryptoKeys/*}/cryptoKeyVersions\x12\xb5\x01\n\x0eListImportJobs\x12*.google.cloud.kms.v1.ListImportJobsRequest\x1a+.google.cloud.kms.v1.ListImportJobsResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/keyRings/*}/importJobs\x12\x8f\x01\n\nGetKeyRing\x12&.google.cloud.kms.v1.GetKeyRingRequest\x1a\x1c.google.cloud.kms.v1.KeyRing";\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v1/{name=projects/*/locations/*/keyRings/*}\x12\xa2\x01\n\x0cGetCryptoKey\x12(.google.cloud.kms.v1.GetCryptoKeyRequest\x1a\x1e.google.cloud.kms.v1.CryptoKey"H\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*}\x12\xcb\x01\n\x13GetCryptoKeyVersion\x12/.google.cloud.kms.v1.GetCryptoKeyVersionRequest\x1a%.google.cloud.kms.v1.CryptoKeyVersion"\\\xdaA\x04name\x82\xd3\xe4\x93\x02O\x12M/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}\x12\xc0\x01\n\x0cGetPublicKey\x12(.google.cloud.kms.v1.GetPublicKeyRequest\x1a\x1e.google.cloud.kms.v1.PublicKey"f\xdaA\x04name\x82\xd3\xe4\x93\x02Y\x12W/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}/publicKey\x12\xa2\x01\n\x0cGetImportJob\x12(.google.cloud.kms.v1.GetImportJobRequest\x1a\x1e.google.cloud.kms.v1.ImportJob"H\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/keyRings/*/importJobs/*}\x12\xb6\x01\n\rCreateKeyRing\x12).google.cloud.kms.v1.CreateKeyRingRequest\x1a\x1c.google.cloud.kms.v1.KeyRing"\\\xdaA\x1bparent,key_ring_id,key_ring\x82\xd3\xe4\x93\x028",/v1/{parent=projects/*/locations/*}/keyRings:\x08key_ring\x12\xcf\x01\n\x0fCreateCryptoKey\x12+.google.cloud.kms.v1.CreateCryptoKeyRequest\x1a\x1e.google.cloud.kms.v1.CryptoKey"o\xdaA\x1fparent,crypto_key_id,crypto_key\x82\xd3\xe4\x93\x02G"9/v1/{parent=projects/*/locations/*/keyRings/*}/cryptoKeys:\ncrypto_key\x12\xfb\x01\n\x16CreateCryptoKeyVersion\x122.google.cloud.kms.v1.CreateCryptoKeyVersionRequest\x1a%.google.cloud.kms.v1.CryptoKeyVersion"\x85\x01\xdaA\x19parent,crypto_key_version\x82\xd3\xe4\x93\x02c"M/v1/{parent=projects/*/locations/*/keyRings/*/cryptoKeys/*}/cryptoKeyVersions:\x12crypto_key_version\x12\xd4\x01\n\x16ImportCryptoKeyVersion\x122.google.cloud.kms.v1.ImportCryptoKeyVersionRequest\x1a%.google.cloud.kms.v1.CryptoKeyVersion"_\x82\xd3\xe4\x93\x02Y"T/v1/{parent=projects/*/locations/*/keyRings/*/cryptoKeys/*}/cryptoKeyVersions:import:\x01*\x12\xcf\x01\n\x0fCreateImportJob\x12+.google.cloud.kms.v1.CreateImportJobRequest\x1a\x1e.google.cloud.kms.v1.ImportJob"o\xdaA\x1fparent,import_job_id,import_job\x82\xd3\xe4\x93\x02G"9/v1/{parent=projects/*/locations/*/keyRings/*}/importJobs:\nimport_job\x12\xd1\x01\n\x0fUpdateCryptoKey\x12+.google.cloud.kms.v1.UpdateCryptoKeyRequest\x1a\x1e.google.cloud.kms.v1.CryptoKey"q\xdaA\x16crypto_key,update_mask\x82\xd3\xe4\x93\x02R2D/v1/{crypto_key.name=projects/*/locations/*/keyRings/*/cryptoKeys/*}:\ncrypto_key\x12\x93\x02\n\x16UpdateCryptoKeyVersion\x122.google.cloud.kms.v1.UpdateCryptoKeyVersionRequest\x1a%.google.cloud.kms.v1.CryptoKeyVersion"\x9d\x01\xdaA\x1ecrypto_key_version,update_mask\x82\xd3\xe4\x93\x02v2`/v1/{crypto_key_version.name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:\x12crypto_key_version\x12\xf2\x01\n\x1dUpdateCryptoKeyPrimaryVersion\x129.google.cloud.kms.v1.UpdateCryptoKeyPrimaryVersionRequest\x1a\x1e.google.cloud.kms.v1.CryptoKey"v\xdaA\x1aname,crypto_key_version_id\x82\xd3\xe4\x93\x02S"N/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*}:updatePrimaryVersion:\x01*\x12\xde\x01\n\x17DestroyCryptoKeyVersion\x123.google.cloud.kms.v1.DestroyCryptoKeyVersionRequest\x1a%.google.cloud.kms.v1.CryptoKeyVersion"g\xdaA\x04name\x82\xd3\xe4\x93\x02Z"U/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:destroy:\x01*\x12\xde\x01\n\x17RestoreCryptoKeyVersion\x123.google.cloud.kms.v1.RestoreCryptoKeyVersionRequest\x1a%.google.cloud.kms.v1.CryptoKeyVersion"g\xdaA\x04name\x82\xd3\xe4\x93\x02Z"U/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:restore:\x01*\x12\xb4\x01\n\x07Encrypt\x12#.google.cloud.kms.v1.EncryptRequest\x1a$.google.cloud.kms.v1.EncryptResponse"^\xdaA\x0ename,plaintext\x82\xd3\xe4\x93\x02G"B/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/**}:encrypt:\x01*\x12\xb4\x01\n\x07Decrypt\x12#.google.cloud.kms.v1.DecryptRequest\x1a$.google.cloud.kms.v1.DecryptResponse"^\xdaA\x0fname,ciphertext\x82\xd3\xe4\x93\x02F"A/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*}:decrypt:\x01*\x12\xc2\x01\n\nRawEncrypt\x12&.google.cloud.kms.v1.RawEncryptRequest\x1a\'.google.cloud.kms.v1.RawEncryptResponse"c\x82\xd3\xe4\x93\x02]"X/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:rawEncrypt:\x01*\x12\xc2\x01\n\nRawDecrypt\x12&.google.cloud.kms.v1.RawDecryptRequest\x1a\'.google.cloud.kms.v1.RawDecryptResponse"c\x82\xd3\xe4\x93\x02]"X/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:rawDecrypt:\x01*\x12\xe0\x01\n\x0eAsymmetricSign\x12*.google.cloud.kms.v1.AsymmetricSignRequest\x1a+.google.cloud.kms.v1.AsymmetricSignResponse"u\xdaA\x0bname,digest\x82\xd3\xe4\x93\x02a"\\/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:asymmetricSign:\x01*\x12\xf0\x01\n\x11AsymmetricDecrypt\x12-.google.cloud.kms.v1.AsymmetricDecryptRequest\x1a..google.cloud.kms.v1.AsymmetricDecryptResponse"|\xdaA\x0fname,ciphertext\x82\xd3\xe4\x93\x02d"_/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:asymmetricDecrypt:\x01*\x12\xc2\x01\n\x07MacSign\x12#.google.cloud.kms.v1.MacSignRequest\x1a$.google.cloud.kms.v1.MacSignResponse"l\xdaA\tname,data\x82\xd3\xe4\x93\x02Z"U/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:macSign:\x01*\x12\xce\x01\n\tMacVerify\x12%.google.cloud.kms.v1.MacVerifyRequest\x1a&.google.cloud.kms.v1.MacVerifyResponse"r\xdaA\rname,data,mac\x82\xd3\xe4\x93\x02\\"W/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:macVerify:\x01*\x12\xc6\x01\n\x0bDecapsulate\x12\'.google.cloud.kms.v1.DecapsulateRequest\x1a(.google.cloud.kms.v1.DecapsulateResponse"d\x82\xd3\xe4\x93\x02^"Y/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:decapsulate:\x01*\x12\xe7\x01\n\x13GenerateRandomBytes\x12/.google.cloud.kms.v1.GenerateRandomBytesRequest\x1a0.google.cloud.kms.v1.GenerateRandomBytesResponse"m\xdaA&location,length_bytes,protection_level\x82\xd3\xe4\x93\x02>"9/v1/{location=projects/*/locations/*}:generateRandomBytes:\x01*\x1at\xcaA\x17cloudkms.googleapis.com\xd2AWhttps://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/cloudkmsB|\n\x17com.google.cloud.kms.v1B\x08KmsProtoP\x01Z)cloud.google.com/go/kms/apiv1/kmspb;kmspb\xaa\x02\x13Google.Cloud.Kms.V1\xca\x02\x13Google\\Cloud\\Kms\\V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.kms.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x17com.google.cloud.kms.v1B\x08KmsProtoP\x01Z)cloud.google.com/go/kms/apiv1/kmspb;kmspb\xaa\x02\x13Google.Cloud.Kms.V1\xca\x02\x13Google\\Cloud\\Kms\\V1'
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTKEYRINGSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing'
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTCRYPTOKEYSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing'
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTIMPORTJOBSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETKEYRINGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETKEYRINGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing'
    _globals['_GETCRYPTOKEYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCRYPTOKEYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_GETCRYPTOKEYVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCRYPTOKEYVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_GETPUBLICKEYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPUBLICKEYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_GETPUBLICKEYREQUEST'].fields_by_name['public_key_format']._loaded_options = None
    _globals['_GETPUBLICKEYREQUEST'].fields_by_name['public_key_format']._serialized_options = b'\xe0A\x01'
    _globals['_GETIMPORTJOBREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETIMPORTJOBREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/ImportJob'
    _globals['_CREATEKEYRINGREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEKEYRINGREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEKEYRINGREQUEST'].fields_by_name['key_ring_id']._loaded_options = None
    _globals['_CREATEKEYRINGREQUEST'].fields_by_name['key_ring_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEKEYRINGREQUEST'].fields_by_name['key_ring']._loaded_options = None
    _globals['_CREATEKEYRINGREQUEST'].fields_by_name['key_ring']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECRYPTOKEYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECRYPTOKEYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing'
    _globals['_CREATECRYPTOKEYREQUEST'].fields_by_name['crypto_key_id']._loaded_options = None
    _globals['_CREATECRYPTOKEYREQUEST'].fields_by_name['crypto_key_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECRYPTOKEYREQUEST'].fields_by_name['crypto_key']._loaded_options = None
    _globals['_CREATECRYPTOKEYREQUEST'].fields_by_name['crypto_key']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECRYPTOKEYVERSIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECRYPTOKEYVERSIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_CREATECRYPTOKEYVERSIONREQUEST'].fields_by_name['crypto_key_version']._loaded_options = None
    _globals['_CREATECRYPTOKEYVERSIONREQUEST'].fields_by_name['crypto_key_version']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['crypto_key_version']._loaded_options = None
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['crypto_key_version']._serialized_options = b'\xe0A\x01\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['algorithm']._loaded_options = None
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['algorithm']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['import_job']._loaded_options = None
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['import_job']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['wrapped_key']._loaded_options = None
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['wrapped_key']._serialized_options = b'\xe0A\x01'
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['rsa_aes_wrapped_key']._loaded_options = None
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST'].fields_by_name['rsa_aes_wrapped_key']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEIMPORTJOBREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEIMPORTJOBREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fcloudkms.googleapis.com/KeyRing'
    _globals['_CREATEIMPORTJOBREQUEST'].fields_by_name['import_job_id']._loaded_options = None
    _globals['_CREATEIMPORTJOBREQUEST'].fields_by_name['import_job_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEIMPORTJOBREQUEST'].fields_by_name['import_job']._loaded_options = None
    _globals['_CREATEIMPORTJOBREQUEST'].fields_by_name['import_job']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECRYPTOKEYREQUEST'].fields_by_name['crypto_key']._loaded_options = None
    _globals['_UPDATECRYPTOKEYREQUEST'].fields_by_name['crypto_key']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECRYPTOKEYREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECRYPTOKEYREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECRYPTOKEYVERSIONREQUEST'].fields_by_name['crypto_key_version']._loaded_options = None
    _globals['_UPDATECRYPTOKEYVERSIONREQUEST'].fields_by_name['crypto_key_version']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECRYPTOKEYVERSIONREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECRYPTOKEYVERSIONREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECRYPTOKEYPRIMARYVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UPDATECRYPTOKEYPRIMARYVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_UPDATECRYPTOKEYPRIMARYVERSIONREQUEST'].fields_by_name['crypto_key_version_id']._loaded_options = None
    _globals['_UPDATECRYPTOKEYPRIMARYVERSIONREQUEST'].fields_by_name['crypto_key_version_id']._serialized_options = b'\xe0A\x02'
    _globals['_DESTROYCRYPTOKEYVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DESTROYCRYPTOKEYVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_RESTORECRYPTOKEYVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESTORECRYPTOKEYVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_ENCRYPTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ENCRYPTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_ENCRYPTREQUEST'].fields_by_name['plaintext']._loaded_options = None
    _globals['_ENCRYPTREQUEST'].fields_by_name['plaintext']._serialized_options = b'\xe0A\x02'
    _globals['_ENCRYPTREQUEST'].fields_by_name['additional_authenticated_data']._loaded_options = None
    _globals['_ENCRYPTREQUEST'].fields_by_name['additional_authenticated_data']._serialized_options = b'\xe0A\x01'
    _globals['_ENCRYPTREQUEST'].fields_by_name['plaintext_crc32c']._loaded_options = None
    _globals['_ENCRYPTREQUEST'].fields_by_name['plaintext_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_ENCRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._loaded_options = None
    _globals['_ENCRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_DECRYPTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DECRYPTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_DECRYPTREQUEST'].fields_by_name['ciphertext']._loaded_options = None
    _globals['_DECRYPTREQUEST'].fields_by_name['ciphertext']._serialized_options = b'\xe0A\x02'
    _globals['_DECRYPTREQUEST'].fields_by_name['additional_authenticated_data']._loaded_options = None
    _globals['_DECRYPTREQUEST'].fields_by_name['additional_authenticated_data']._serialized_options = b'\xe0A\x01'
    _globals['_DECRYPTREQUEST'].fields_by_name['ciphertext_crc32c']._loaded_options = None
    _globals['_DECRYPTREQUEST'].fields_by_name['ciphertext_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_DECRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._loaded_options = None
    _globals['_DECRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['plaintext']._loaded_options = None
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['plaintext']._serialized_options = b'\xe0A\x02'
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['additional_authenticated_data']._loaded_options = None
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['additional_authenticated_data']._serialized_options = b'\xe0A\x01'
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['plaintext_crc32c']._loaded_options = None
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['plaintext_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._loaded_options = None
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['initialization_vector']._loaded_options = None
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['initialization_vector']._serialized_options = b'\xe0A\x01'
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['initialization_vector_crc32c']._loaded_options = None
    _globals['_RAWENCRYPTREQUEST'].fields_by_name['initialization_vector_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['ciphertext']._loaded_options = None
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['ciphertext']._serialized_options = b'\xe0A\x02'
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['additional_authenticated_data']._loaded_options = None
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['additional_authenticated_data']._serialized_options = b'\xe0A\x01'
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['initialization_vector']._loaded_options = None
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['initialization_vector']._serialized_options = b'\xe0A\x02'
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['ciphertext_crc32c']._loaded_options = None
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['ciphertext_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._loaded_options = None
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['additional_authenticated_data_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['initialization_vector_crc32c']._loaded_options = None
    _globals['_RAWDECRYPTREQUEST'].fields_by_name['initialization_vector_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['digest']._loaded_options = None
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['digest']._serialized_options = b'\xe0A\x01'
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['digest_crc32c']._loaded_options = None
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['digest_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['data']._loaded_options = None
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['data']._serialized_options = b'\xe0A\x01'
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['data_crc32c']._loaded_options = None
    _globals['_ASYMMETRICSIGNREQUEST'].fields_by_name['data_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_ASYMMETRICDECRYPTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ASYMMETRICDECRYPTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_ASYMMETRICDECRYPTREQUEST'].fields_by_name['ciphertext']._loaded_options = None
    _globals['_ASYMMETRICDECRYPTREQUEST'].fields_by_name['ciphertext']._serialized_options = b'\xe0A\x02'
    _globals['_ASYMMETRICDECRYPTREQUEST'].fields_by_name['ciphertext_crc32c']._loaded_options = None
    _globals['_ASYMMETRICDECRYPTREQUEST'].fields_by_name['ciphertext_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_MACSIGNREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_MACSIGNREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_MACSIGNREQUEST'].fields_by_name['data']._loaded_options = None
    _globals['_MACSIGNREQUEST'].fields_by_name['data']._serialized_options = b'\xe0A\x02'
    _globals['_MACSIGNREQUEST'].fields_by_name['data_crc32c']._loaded_options = None
    _globals['_MACSIGNREQUEST'].fields_by_name['data_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_MACVERIFYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_MACVERIFYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_MACVERIFYREQUEST'].fields_by_name['data']._loaded_options = None
    _globals['_MACVERIFYREQUEST'].fields_by_name['data']._serialized_options = b'\xe0A\x02'
    _globals['_MACVERIFYREQUEST'].fields_by_name['data_crc32c']._loaded_options = None
    _globals['_MACVERIFYREQUEST'].fields_by_name['data_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_MACVERIFYREQUEST'].fields_by_name['mac']._loaded_options = None
    _globals['_MACVERIFYREQUEST'].fields_by_name['mac']._serialized_options = b'\xe0A\x02'
    _globals['_MACVERIFYREQUEST'].fields_by_name['mac_crc32c']._loaded_options = None
    _globals['_MACVERIFYREQUEST'].fields_by_name['mac_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_DECAPSULATEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DECAPSULATEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(cloudkms.googleapis.com/CryptoKeyVersion'
    _globals['_DECAPSULATEREQUEST'].fields_by_name['ciphertext']._loaded_options = None
    _globals['_DECAPSULATEREQUEST'].fields_by_name['ciphertext']._serialized_options = b'\xe0A\x02'
    _globals['_DECAPSULATEREQUEST'].fields_by_name['ciphertext_crc32c']._loaded_options = None
    _globals['_DECAPSULATEREQUEST'].fields_by_name['ciphertext_crc32c']._serialized_options = b'\xe0A\x01'
    _globals['_KEYMANAGEMENTSERVICE']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE']._serialized_options = b'\xcaA\x17cloudkms.googleapis.com\xd2AWhttps://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/cloudkms'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListKeyRings']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListKeyRings']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1/{parent=projects/*/locations/*}/keyRings'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListCryptoKeys']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListCryptoKeys']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/keyRings/*}/cryptoKeys'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListCryptoKeyVersions']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListCryptoKeyVersions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02O\x12M/v1/{parent=projects/*/locations/*/keyRings/*/cryptoKeys/*}/cryptoKeyVersions'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListImportJobs']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ListImportJobs']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/keyRings/*}/importJobs'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetKeyRing']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetKeyRing']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v1/{name=projects/*/locations/*/keyRings/*}'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetCryptoKey']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetCryptoKey']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*}'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetCryptoKeyVersion']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetCryptoKeyVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02O\x12M/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetPublicKey']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetPublicKey']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02Y\x12W/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}/publicKey'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetImportJob']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GetImportJob']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/keyRings/*/importJobs/*}'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateKeyRing']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateKeyRing']._serialized_options = b'\xdaA\x1bparent,key_ring_id,key_ring\x82\xd3\xe4\x93\x028",/v1/{parent=projects/*/locations/*}/keyRings:\x08key_ring'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateCryptoKey']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateCryptoKey']._serialized_options = b'\xdaA\x1fparent,crypto_key_id,crypto_key\x82\xd3\xe4\x93\x02G"9/v1/{parent=projects/*/locations/*/keyRings/*}/cryptoKeys:\ncrypto_key'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateCryptoKeyVersion']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateCryptoKeyVersion']._serialized_options = b'\xdaA\x19parent,crypto_key_version\x82\xd3\xe4\x93\x02c"M/v1/{parent=projects/*/locations/*/keyRings/*/cryptoKeys/*}/cryptoKeyVersions:\x12crypto_key_version'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ImportCryptoKeyVersion']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['ImportCryptoKeyVersion']._serialized_options = b'\x82\xd3\xe4\x93\x02Y"T/v1/{parent=projects/*/locations/*/keyRings/*/cryptoKeys/*}/cryptoKeyVersions:import:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateImportJob']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['CreateImportJob']._serialized_options = b'\xdaA\x1fparent,import_job_id,import_job\x82\xd3\xe4\x93\x02G"9/v1/{parent=projects/*/locations/*/keyRings/*}/importJobs:\nimport_job'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['UpdateCryptoKey']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['UpdateCryptoKey']._serialized_options = b'\xdaA\x16crypto_key,update_mask\x82\xd3\xe4\x93\x02R2D/v1/{crypto_key.name=projects/*/locations/*/keyRings/*/cryptoKeys/*}:\ncrypto_key'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['UpdateCryptoKeyVersion']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['UpdateCryptoKeyVersion']._serialized_options = b'\xdaA\x1ecrypto_key_version,update_mask\x82\xd3\xe4\x93\x02v2`/v1/{crypto_key_version.name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:\x12crypto_key_version'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['UpdateCryptoKeyPrimaryVersion']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['UpdateCryptoKeyPrimaryVersion']._serialized_options = b'\xdaA\x1aname,crypto_key_version_id\x82\xd3\xe4\x93\x02S"N/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*}:updatePrimaryVersion:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['DestroyCryptoKeyVersion']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['DestroyCryptoKeyVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02Z"U/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:destroy:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['RestoreCryptoKeyVersion']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['RestoreCryptoKeyVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02Z"U/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:restore:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['Encrypt']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['Encrypt']._serialized_options = b'\xdaA\x0ename,plaintext\x82\xd3\xe4\x93\x02G"B/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/**}:encrypt:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['Decrypt']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['Decrypt']._serialized_options = b'\xdaA\x0fname,ciphertext\x82\xd3\xe4\x93\x02F"A/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*}:decrypt:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['RawEncrypt']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['RawEncrypt']._serialized_options = b'\x82\xd3\xe4\x93\x02]"X/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:rawEncrypt:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['RawDecrypt']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['RawDecrypt']._serialized_options = b'\x82\xd3\xe4\x93\x02]"X/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:rawDecrypt:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['AsymmetricSign']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['AsymmetricSign']._serialized_options = b'\xdaA\x0bname,digest\x82\xd3\xe4\x93\x02a"\\/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:asymmetricSign:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['AsymmetricDecrypt']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['AsymmetricDecrypt']._serialized_options = b'\xdaA\x0fname,ciphertext\x82\xd3\xe4\x93\x02d"_/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:asymmetricDecrypt:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['MacSign']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['MacSign']._serialized_options = b'\xdaA\tname,data\x82\xd3\xe4\x93\x02Z"U/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:macSign:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['MacVerify']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['MacVerify']._serialized_options = b'\xdaA\rname,data,mac\x82\xd3\xe4\x93\x02\\"W/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:macVerify:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['Decapsulate']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['Decapsulate']._serialized_options = b'\x82\xd3\xe4\x93\x02^"Y/v1/{name=projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*}:decapsulate:\x01*'
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GenerateRandomBytes']._loaded_options = None
    _globals['_KEYMANAGEMENTSERVICE'].methods_by_name['GenerateRandomBytes']._serialized_options = b'\xdaA&location,length_bytes,protection_level\x82\xd3\xe4\x93\x02>"9/v1/{location=projects/*/locations/*}:generateRandomBytes:\x01*'
    _globals['_LISTKEYRINGSREQUEST']._serialized_start = 277
    _globals['_LISTKEYRINGSREQUEST']._serialized_end = 450
    _globals['_LISTCRYPTOKEYSREQUEST']._serialized_start = 453
    _globals['_LISTCRYPTOKEYSREQUEST']._serialized_end = 708
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST']._serialized_start = 711
    _globals['_LISTCRYPTOKEYVERSIONSREQUEST']._serialized_end = 967
    _globals['_LISTIMPORTJOBSREQUEST']._serialized_start = 970
    _globals['_LISTIMPORTJOBSREQUEST']._serialized_end = 1143
    _globals['_LISTKEYRINGSRESPONSE']._serialized_start = 1145
    _globals['_LISTKEYRINGSRESPONSE']._serialized_end = 1261
    _globals['_LISTCRYPTOKEYSRESPONSE']._serialized_start = 1263
    _globals['_LISTCRYPTOKEYSRESPONSE']._serialized_end = 1385
    _globals['_LISTCRYPTOKEYVERSIONSRESPONSE']._serialized_start = 1388
    _globals['_LISTCRYPTOKEYVERSIONSRESPONSE']._serialized_end = 1532
    _globals['_LISTIMPORTJOBSRESPONSE']._serialized_start = 1534
    _globals['_LISTIMPORTJOBSRESPONSE']._serialized_end = 1656
    _globals['_GETKEYRINGREQUEST']._serialized_start = 1658
    _globals['_GETKEYRINGREQUEST']._serialized_end = 1732
    _globals['_GETCRYPTOKEYREQUEST']._serialized_start = 1734
    _globals['_GETCRYPTOKEYREQUEST']._serialized_end = 1812
    _globals['_GETCRYPTOKEYVERSIONREQUEST']._serialized_start = 1814
    _globals['_GETCRYPTOKEYVERSIONREQUEST']._serialized_end = 1906
    _globals['_GETPUBLICKEYREQUEST']._serialized_start = 1909
    _globals['_GETPUBLICKEYREQUEST']._serialized_end = 2074
    _globals['_GETIMPORTJOBREQUEST']._serialized_start = 2076
    _globals['_GETIMPORTJOBREQUEST']._serialized_end = 2154
    _globals['_CREATEKEYRINGREQUEST']._serialized_start = 2157
    _globals['_CREATEKEYRINGREQUEST']._serialized_end = 2317
    _globals['_CREATECRYPTOKEYREQUEST']._serialized_start = 2320
    _globals['_CREATECRYPTOKEYREQUEST']._serialized_end = 2525
    _globals['_CREATECRYPTOKEYVERSIONREQUEST']._serialized_start = 2528
    _globals['_CREATECRYPTOKEYVERSIONREQUEST']._serialized_end = 2690
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST']._serialized_start = 2693
    _globals['_IMPORTCRYPTOKEYVERSIONREQUEST']._serialized_end = 3061
    _globals['_CREATEIMPORTJOBREQUEST']._serialized_start = 3064
    _globals['_CREATEIMPORTJOBREQUEST']._serialized_end = 3230
    _globals['_UPDATECRYPTOKEYREQUEST']._serialized_start = 3233
    _globals['_UPDATECRYPTOKEYREQUEST']._serialized_end = 3368
    _globals['_UPDATECRYPTOKEYVERSIONREQUEST']._serialized_start = 3371
    _globals['_UPDATECRYPTOKEYVERSIONREQUEST']._serialized_end = 3528
    _globals['_UPDATECRYPTOKEYPRIMARYVERSIONREQUEST']._serialized_start = 3531
    _globals['_UPDATECRYPTOKEYPRIMARYVERSIONREQUEST']._serialized_end = 3662
    _globals['_DESTROYCRYPTOKEYVERSIONREQUEST']._serialized_start = 3664
    _globals['_DESTROYCRYPTOKEYVERSIONREQUEST']._serialized_end = 3760
    _globals['_RESTORECRYPTOKEYVERSIONREQUEST']._serialized_start = 3762
    _globals['_RESTORECRYPTOKEYVERSIONREQUEST']._serialized_end = 3858
    _globals['_ENCRYPTREQUEST']._serialized_start = 3861
    _globals['_ENCRYPTREQUEST']._serialized_end = 4110
    _globals['_DECRYPTREQUEST']._serialized_start = 4113
    _globals['_DECRYPTREQUEST']._serialized_end = 4396
    _globals['_RAWENCRYPTREQUEST']._serialized_start = 4399
    _globals['_RAWENCRYPTREQUEST']._serialized_end = 4753
    _globals['_RAWDECRYPTREQUEST']._serialized_start = 4756
    _globals['_RAWDECRYPTREQUEST']._serialized_end = 5132
    _globals['_ASYMMETRICSIGNREQUEST']._serialized_start = 5135
    _globals['_ASYMMETRICSIGNREQUEST']._serialized_end = 5403
    _globals['_ASYMMETRICDECRYPTREQUEST']._serialized_start = 5406
    _globals['_ASYMMETRICDECRYPTREQUEST']._serialized_end = 5582
    _globals['_MACSIGNREQUEST']._serialized_start = 5585
    _globals['_MACSIGNREQUEST']._serialized_end = 5739
    _globals['_MACVERIFYREQUEST']._serialized_start = 5742
    _globals['_MACVERIFYREQUEST']._serialized_end = 5970
    _globals['_DECAPSULATEREQUEST']._serialized_start = 5973
    _globals['_DECAPSULATEREQUEST']._serialized_end = 6143
    _globals['_GENERATERANDOMBYTESREQUEST']._serialized_start = 6146
    _globals['_GENERATERANDOMBYTESREQUEST']._serialized_end = 6278
    _globals['_ENCRYPTRESPONSE']._serialized_start = 6281
    _globals['_ENCRYPTRESPONSE']._serialized_end = 6542
    _globals['_DECRYPTRESPONSE']._serialized_start = 6545
    _globals['_DECRYPTRESPONSE']._serialized_end = 6722
    _globals['_RAWENCRYPTRESPONSE']._serialized_start = 6725
    _globals['_RAWENCRYPTRESPONSE']._serialized_end = 7154
    _globals['_RAWDECRYPTRESPONSE']._serialized_start = 7157
    _globals['_RAWDECRYPTRESPONSE']._serialized_end = 7453
    _globals['_ASYMMETRICSIGNRESPONSE']._serialized_start = 7456
    _globals['_ASYMMETRICSIGNRESPONSE']._serialized_end = 7694
    _globals['_ASYMMETRICDECRYPTRESPONSE']._serialized_start = 7697
    _globals['_ASYMMETRICDECRYPTRESPONSE']._serialized_end = 7898
    _globals['_MACSIGNRESPONSE']._serialized_start = 7901
    _globals['_MACSIGNRESPONSE']._serialized_end = 8088
    _globals['_MACVERIFYRESPONSE']._serialized_start = 8091
    _globals['_MACVERIFYRESPONSE']._serialized_end = 8300
    _globals['_DECAPSULATERESPONSE']._serialized_start = 8303
    _globals['_DECAPSULATERESPONSE']._serialized_end = 8521
    _globals['_GENERATERANDOMBYTESRESPONSE']._serialized_start = 8523
    _globals['_GENERATERANDOMBYTESRESPONSE']._serialized_end = 8616
    _globals['_DIGEST']._serialized_start = 8618
    _globals['_DIGEST']._serialized_end = 8690
    _globals['_LOCATIONMETADATA']._serialized_start = 8692
    _globals['_LOCATIONMETADATA']._serialized_end = 8756
    _globals['_KEYMANAGEMENTSERVICE']._serialized_start = 8759
    _globals['_KEYMANAGEMENTSERVICE']._serialized_end = 14864