"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/security/privateca/v1/service.proto')
_sym_db = _symbol_database.Default()
from ......google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from ......google.api import client_pb2 as google_dot_api_dot_client__pb2
from ......google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from ......google.api import field_info_pb2 as google_dot_api_dot_field__info__pb2
from ......google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from ......google.cloud.security.privateca.v1 import resources_pb2 as google_dot_cloud_dot_security_dot_privateca_dot_v1_dot_resources__pb2
from ......google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0google/cloud/security/privateca/v1/service.proto\x12"google.cloud.security.privateca.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a\x19google/api/resource.proto\x1a2google/cloud/security/privateca/v1/resources.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x9f\x02\n\x18CreateCertificateRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool\x12\x1b\n\x0ecertificate_id\x18\x02 \x01(\tB\x03\xe0A\x01\x12I\n\x0bcertificate\x18\x03 \x01(\x0b2/.google.cloud.security.privateca.v1.CertificateB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x05 \x01(\x08B\x03\xe0A\x01\x12-\n issuing_certificate_authority_id\x18\x06 \x01(\tB\x03\xe0A\x01"S\n\x15GetCertificateRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$privateca.googleapis.com/Certificate"\xaf\x01\n\x17ListCertificatesRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x8f\x01\n\x18ListCertificatesResponse\x12E\n\x0ccertificates\x18\x01 \x03(\x0b2/.google.cloud.security.privateca.v1.Certificate\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xba\x01\n\x18RevokeCertificateRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$privateca.googleapis.com/Certificate\x12I\n\x06reason\x18\x02 \x01(\x0e24.google.cloud.security.privateca.v1.RevocationReasonB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"\xb4\x01\n\x18UpdateCertificateRequest\x12I\n\x0bcertificate\x18\x01 \x01(\x0b2/.google.cloud.security.privateca.v1.CertificateB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"\x84\x02\n#ActivateCertificateAuthorityRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority\x12\x1f\n\x12pem_ca_certificate\x18\x02 \x01(\tB\x03\xe0A\x02\x12V\n\x12subordinate_config\x18\x03 \x01(\x0b25.google.cloud.security.privateca.v1.SubordinateConfigB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x04 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\xfa\x01\n!CreateCertificateAuthorityRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool\x12%\n\x18certificate_authority_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12\\\n\x15certificate_authority\x18\x03 \x01(\x0b28.google.cloud.security.privateca.v1.CertificateAuthorityB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01"\xb3\x01\n"DisableCertificateAuthorityRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\'\n\x1aignore_dependent_resources\x18\x03 \x01(\x08B\x03\xe0A\x01"\x89\x01\n!EnableCertificateAuthorityRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"j\n#FetchCertificateAuthorityCsrRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority"<\n$FetchCertificateAuthorityCsrResponse\x12\x14\n\x07pem_csr\x18\x01 \x01(\tB\x03\xe0A\x03"e\n\x1eGetCertificateAuthorityRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority"\xb9\x01\n!ListCertificateAuthoritiesRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\xad\x01\n"ListCertificateAuthoritiesResponse\x12Y\n\x17certificate_authorities\x18\x01 \x03(\x0b28.google.cloud.security.privateca.v1.CertificateAuthority\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\x8b\x01\n#UndeleteCertificateAuthorityRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\xfb\x01\n!DeleteCertificateAuthorityRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\'\n\x1aignore_active_certificates\x18\x04 \x01(\x08B\x03\xe0A\x01\x12\x1e\n\x11skip_grace_period\x18\x05 \x01(\x08B\x03\xe0A\x01\x12\'\n\x1aignore_dependent_resources\x18\x06 \x01(\x08B\x03\xe0A\x01"\xd8\x01\n!UpdateCertificateAuthorityRequest\x12\\\n\x15certificate_authority\x18\x01 \x01(\x0b28.google.cloud.security.privateca.v1.CertificateAuthorityB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x03 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\xcc\x01\n\x13CreateCaPoolRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x17\n\nca_pool_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12@\n\x07ca_pool\x18\x03 \x01(\x0b2*.google.cloud.security.privateca.v1.CaPoolB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x04 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\xae\x01\n\x13UpdateCaPoolRequest\x12@\n\x07ca_pool\x18\x01 \x01(\x0b2*.google.cloud.security.privateca.v1.CaPoolB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x03 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\x96\x01\n\x13DeleteCaPoolRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\'\n\x1aignore_dependent_resources\x18\x04 \x01(\x08B\x03\xe0A\x01"h\n\x13FetchCaCertsRequest\x128\n\x07ca_pool\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\x8f\x01\n\x14FetchCaCertsResponse\x12T\n\x08ca_certs\x18\x01 \x03(\x0b2B.google.cloud.security.privateca.v1.FetchCaCertsResponse.CertChain\x1a!\n\tCertChain\x12\x14\n\x0ccertificates\x18\x01 \x03(\t"I\n\x10GetCaPoolRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool"\xac\x01\n\x12ListCaPoolsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x81\x01\n\x13ListCaPoolsResponse\x12<\n\x08ca_pools\x18\x01 \x03(\x0b2*.google.cloud.security.privateca.v1.CaPool\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"o\n#GetCertificateRevocationListRequest\x12H\n\x04name\x18\x01 \x01(\tB:\xe0A\x02\xfaA4\n2privateca.googleapis.com/CertificateRevocationList"\xcb\x01\n%ListCertificateRevocationListsRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\xbb\x01\n&ListCertificateRevocationListsResponse\x12c\n\x1ccertificate_revocation_lists\x18\x01 \x03(\x0b2=.google.cloud.security.privateca.v1.CertificateRevocationList\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xe0\x01\n&UpdateCertificateRevocationListRequest\x12g\n\x1bcertificate_revocation_list\x18\x01 \x01(\x0b2=.google.cloud.security.privateca.v1.CertificateRevocationListB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"\x80\x02\n CreateCertificateTemplateRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12$\n\x17certificate_template_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12Z\n\x14certificate_template\x18\x03 \x01(\x0b27.google.cloud.security.privateca.v1.CertificateTemplateB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x04 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\x87\x01\n DeleteCertificateTemplateRequest\x12B\n\x04name\x18\x01 \x01(\tB4\xe0A\x02\xfaA.\n,privateca.googleapis.com/CertificateTemplate\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"c\n\x1dGetCertificateTemplateRequest\x12B\n\x04name\x18\x01 \x01(\tB4\xe0A\x02\xfaA.\n,privateca.googleapis.com/CertificateTemplate"\xb9\x01\n\x1fListCertificateTemplatesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\xa8\x01\n ListCertificateTemplatesResponse\x12V\n\x15certificate_templates\x18\x01 \x03(\x0b27.google.cloud.security.privateca.v1.CertificateTemplate\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xd5\x01\n UpdateCertificateTemplateRequest\x12Z\n\x14certificate_template\x18\x01 \x01(\x0b27.google.cloud.security.privateca.v1.CertificateTemplateB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x03 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\x80\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x032\xfa;\n\x1bCertificateAuthorityService\x12\xf7\x01\n\x11CreateCertificate\x12<.google.cloud.security.privateca.v1.CreateCertificateRequest\x1a/.google.cloud.security.privateca.v1.Certificate"s\xdaA!parent,certificate,certificate_id\x82\xd3\xe4\x93\x02I":/v1/{parent=projects/*/locations/*/caPools/*}/certificates:\x0bcertificate\x12\xc7\x01\n\x0eGetCertificate\x129.google.cloud.security.privateca.v1.GetCertificateRequest\x1a/.google.cloud.security.privateca.v1.Certificate"I\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v1/{name=projects/*/locations/*/caPools/*/certificates/*}\x12\xda\x01\n\x10ListCertificates\x12;.google.cloud.security.privateca.v1.ListCertificatesRequest\x1a<.google.cloud.security.privateca.v1.ListCertificatesResponse"K\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v1/{parent=projects/*/locations/*/caPools/*}/certificates\x12\xd7\x01\n\x11RevokeCertificate\x12<.google.cloud.security.privateca.v1.RevokeCertificateRequest\x1a/.google.cloud.security.privateca.v1.Certificate"S\xdaA\x04name\x82\xd3\xe4\x93\x02F"A/v1/{name=projects/*/locations/*/caPools/*/certificates/*}:revoke:\x01*\x12\xf9\x01\n\x11UpdateCertificate\x12<.google.cloud.security.privateca.v1.UpdateCertificateRequest\x1a/.google.cloud.security.privateca.v1.Certificate"u\xdaA\x17certificate,update_mask\x82\xd3\xe4\x93\x02U2F/v1/{certificate.name=projects/*/locations/*/caPools/*/certificates/*}:\x0bcertificate\x12\x94\x02\n\x1cActivateCertificateAuthority\x12G.google.cloud.security.privateca.v1.ActivateCertificateAuthorityRequest\x1a\x1d.google.longrunning.Operation"\x8b\x01\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02R"M/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:activate:\x01*\x12\xcc\x02\n\x1aCreateCertificateAuthority\x12E.google.cloud.security.privateca.v1.CreateCertificateAuthorityRequest\x1a\x1d.google.longrunning.Operation"\xc7\x01\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA5parent,certificate_authority,certificate_authority_id\x82\xd3\xe4\x93\x02]"D/v1/{parent=projects/*/locations/*/caPools/*}/certificateAuthorities:\x15certificate_authority\x12\x91\x02\n\x1bDisableCertificateAuthority\x12F.google.cloud.security.privateca.v1.DisableCertificateAuthorityRequest\x1a\x1d.google.longrunning.Operation"\x8a\x01\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02Q"L/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:disable:\x01*\x12\x8e\x02\n\x1aEnableCertificateAuthority\x12E.google.cloud.security.privateca.v1.EnableCertificateAuthorityRequest\x1a\x1d.google.longrunning.Operation"\x89\x01\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02P"K/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:enable:\x01*\x12\x8c\x02\n\x1cFetchCertificateAuthorityCsr\x12G.google.cloud.security.privateca.v1.FetchCertificateAuthorityCsrRequest\x1aH.google.cloud.security.privateca.v1.FetchCertificateAuthorityCsrResponse"Y\xdaA\x04name\x82\xd3\xe4\x93\x02L\x12J/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:fetch\x12\xec\x01\n\x17GetCertificateAuthority\x12B.google.cloud.security.privateca.v1.GetCertificateAuthorityRequest\x1a8.google.cloud.security.privateca.v1.CertificateAuthority"S\xdaA\x04name\x82\xd3\xe4\x93\x02F\x12D/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}\x12\x82\x02\n\x1aListCertificateAuthorities\x12E.google.cloud.security.privateca.v1.ListCertificateAuthoritiesRequest\x1aF.google.cloud.security.privateca.v1.ListCertificateAuthoritiesResponse"U\xdaA\x06parent\x82\xd3\xe4\x93\x02F\x12D/v1/{parent=projects/*/locations/*/caPools/*}/certificateAuthorities\x12\x94\x02\n\x1cUndeleteCertificateAuthority\x12G.google.cloud.security.privateca.v1.UndeleteCertificateAuthorityRequest\x1a\x1d.google.longrunning.Operation"\x8b\x01\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02R"M/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:undelete:\x01*\x12\x83\x02\n\x1aDeleteCertificateAuthority\x12E.google.cloud.security.privateca.v1.DeleteCertificateAuthorityRequest\x1a\x1d.google.longrunning.Operation"\x7f\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02F*D/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}\x12\xce\x02\n\x1aUpdateCertificateAuthority\x12E.google.cloud.security.privateca.v1.UpdateCertificateAuthorityRequest\x1a\x1d.google.longrunning.Operation"\xc9\x01\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA!certificate_authority,update_mask\x82\xd3\xe4\x93\x02s2Z/v1/{certificate_authority.name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:\x15certificate_authority\x12\xde\x01\n\x0cCreateCaPool\x127.google.cloud.security.privateca.v1.CreateCaPoolRequest\x1a\x1d.google.longrunning.Operation"v\xcaA\x1b\n\x06CaPool\x12\x11OperationMetadata\xdaA\x19parent,ca_pool,ca_pool_id\x82\xd3\xe4\x93\x026"+/v1/{parent=projects/*/locations/*}/caPools:\x07ca_pool\x12\xe0\x01\n\x0cUpdateCaPool\x127.google.cloud.security.privateca.v1.UpdateCaPoolRequest\x1a\x1d.google.longrunning.Operation"x\xcaA\x1b\n\x06CaPool\x12\x11OperationMetadata\xdaA\x13ca_pool,update_mask\x82\xd3\xe4\x93\x02>23/v1/{ca_pool.name=projects/*/locations/*/caPools/*}:\x07ca_pool\x12\xa9\x01\n\tGetCaPool\x124.google.cloud.security.privateca.v1.GetCaPoolRequest\x1a*.google.cloud.security.privateca.v1.CaPool":\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1/{name=projects/*/locations/*/caPools/*}\x12\xbc\x01\n\x0bListCaPools\x126.google.cloud.security.privateca.v1.ListCaPoolsRequest\x1a7.google.cloud.security.privateca.v1.ListCaPoolsResponse"<\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=projects/*/locations/*}/caPools\x12\xcf\x01\n\x0cDeleteCaPool\x127.google.cloud.security.privateca.v1.DeleteCaPoolRequest\x1a\x1d.google.longrunning.Operation"g\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1/{name=projects/*/locations/*/caPools/*}\x12\xd3\x01\n\x0cFetchCaCerts\x127.google.cloud.security.privateca.v1.FetchCaCertsRequest\x1a8.google.cloud.security.privateca.v1.FetchCaCertsResponse"P\xdaA\x07ca_pool\x82\xd3\xe4\x93\x02@";/v1/{ca_pool=projects/*/locations/*/caPools/*}:fetchCaCerts:\x01*\x12\x98\x02\n\x1cGetCertificateRevocationList\x12G.google.cloud.security.privateca.v1.GetCertificateRevocationListRequest\x1a=.google.cloud.security.privateca.v1.CertificateRevocationList"p\xdaA\x04name\x82\xd3\xe4\x93\x02c\x12a/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*/certificateRevocationLists/*}\x12\xab\x02\n\x1eListCertificateRevocationLists\x12I.google.cloud.security.privateca.v1.ListCertificateRevocationListsRequest\x1aJ.google.cloud.security.privateca.v1.ListCertificateRevocationListsResponse"r\xdaA\x06parent\x82\xd3\xe4\x93\x02c\x12a/v1/{parent=projects/*/locations/*/caPools/*/certificateAuthorities/*}/certificateRevocationLists\x12\x8d\x03\n\x1fUpdateCertificateRevocationList\x12J.google.cloud.security.privateca.v1.UpdateCertificateRevocationListRequest\x1a\x1d.google.longrunning.Operation"\xfe\x01\xcaA.\n\x19CertificateRevocationList\x12\x11OperationMetadata\xdaA\'certificate_revocation_list,update_mask\x82\xd3\xe4\x93\x02\x9c\x012}/v1/{certificate_revocation_list.name=projects/*/locations/*/caPools/*/certificateAuthorities/*/certificateRevocationLists/*}:\x1bcertificate_revocation_list\x12\xba\x02\n\x19CreateCertificateTemplate\x12D.google.cloud.security.privateca.v1.CreateCertificateTemplateRequest\x1a\x1d.google.longrunning.Operation"\xb7\x01\xcaA(\n\x13CertificateTemplate\x12\x11OperationMetadata\xdaA3parent,certificate_template,certificate_template_id\x82\xd3\xe4\x93\x02P"8/v1/{parent=projects/*/locations/*}/certificateTemplates:\x14certificate_template\x12\x9a\x02\n\x19DeleteCertificateTemplate\x12D.google.cloud.security.privateca.v1.DeleteCertificateTemplateRequest\x1a\x1d.google.longrunning.Operation"\x97\x01\xcaAM\n\x15google.protobuf.Empty\x124google.cloud.security.privateca.v1.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02:*8/v1/{name=projects/*/locations/*/certificateTemplates/*}\x12\xdd\x01\n\x16GetCertificateTemplate\x12A.google.cloud.security.privateca.v1.GetCertificateTemplateRequest\x1a7.google.cloud.security.privateca.v1.CertificateTemplate"G\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/certificateTemplates/*}\x12\xf0\x01\n\x18ListCertificateTemplates\x12C.google.cloud.security.privateca.v1.ListCertificateTemplatesRequest\x1aD.google.cloud.security.privateca.v1.ListCertificateTemplatesResponse"I\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*}/certificateTemplates\x12\xbc\x02\n\x19UpdateCertificateTemplate\x12D.google.cloud.security.privateca.v1.UpdateCertificateTemplateRequest\x1a\x1d.google.longrunning.Operation"\xb9\x01\xcaA(\n\x13CertificateTemplate\x12\x11OperationMetadata\xdaA certificate_template,update_mask\x82\xd3\xe4\x93\x02e2M/v1/{certificate_template.name=projects/*/locations/*/certificateTemplates/*}:\x14certificate_template\x1aL\xcaA\x18privateca.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xf3\x01\n&com.google.cloud.security.privateca.v1B\x0ePrivateCaProtoP\x01ZDcloud.google.com/go/security/privateca/apiv1/privatecapb;privatecapb\xaa\x02"Google.Cloud.Security.PrivateCA.V1\xca\x02"Google\\Cloud\\Security\\PrivateCA\\V1\xea\x02&Google::Cloud::Security::PrivateCA::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.security.privateca.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n&com.google.cloud.security.privateca.v1B\x0ePrivateCaProtoP\x01ZDcloud.google.com/go/security/privateca/apiv1/privatecapb;privatecapb\xaa\x02"Google.Cloud.Security.PrivateCA.V1\xca\x02"Google\\Cloud\\Security\\PrivateCA\\V1\xea\x02&Google::Cloud::Security::PrivateCA::V1'
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['certificate_id']._loaded_options = None
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['certificate_id']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['certificate']._loaded_options = None
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['certificate']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['issuing_certificate_authority_id']._loaded_options = None
    _globals['_CREATECERTIFICATEREQUEST'].fields_by_name['issuing_certificate_authority_id']._serialized_options = b'\xe0A\x01'
    _globals['_GETCERTIFICATEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCERTIFICATEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$privateca.googleapis.com/Certificate'
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTCERTIFICATESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_REVOKECERTIFICATEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_REVOKECERTIFICATEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$privateca.googleapis.com/Certificate'
    _globals['_REVOKECERTIFICATEREQUEST'].fields_by_name['reason']._loaded_options = None
    _globals['_REVOKECERTIFICATEREQUEST'].fields_by_name['reason']._serialized_options = b'\xe0A\x02'
    _globals['_REVOKECERTIFICATEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_REVOKECERTIFICATEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECERTIFICATEREQUEST'].fields_by_name['certificate']._loaded_options = None
    _globals['_UPDATECERTIFICATEREQUEST'].fields_by_name['certificate']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECERTIFICATEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATECERTIFICATEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['pem_ca_certificate']._loaded_options = None
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['pem_ca_certificate']._serialized_options = b'\xe0A\x02'
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['subordinate_config']._loaded_options = None
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['subordinate_config']._serialized_options = b'\xe0A\x02'
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['certificate_authority_id']._loaded_options = None
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['certificate_authority_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['certificate_authority']._loaded_options = None
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['certificate_authority']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['ignore_dependent_resources']._loaded_options = None
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['ignore_dependent_resources']._serialized_options = b'\xe0A\x01'
    _globals['_ENABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ENABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_ENABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_ENABLECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_FETCHCERTIFICATEAUTHORITYCSRREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_FETCHCERTIFICATEAUTHORITYCSRREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_FETCHCERTIFICATEAUTHORITYCSRRESPONSE'].fields_by_name['pem_csr']._loaded_options = None
    _globals['_FETCHCERTIFICATEAUTHORITYCSRRESPONSE'].fields_by_name['pem_csr']._serialized_options = b'\xe0A\x03'
    _globals['_GETCERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_UNDELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UNDELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_UNDELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UNDELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['ignore_active_certificates']._loaded_options = None
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['ignore_active_certificates']._serialized_options = b'\xe0A\x01'
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['skip_grace_period']._loaded_options = None
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['skip_grace_period']._serialized_options = b'\xe0A\x01'
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['ignore_dependent_resources']._loaded_options = None
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST'].fields_by_name['ignore_dependent_resources']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['certificate_authority']._loaded_options = None
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['certificate_authority']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['ca_pool_id']._loaded_options = None
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['ca_pool_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['ca_pool']._loaded_options = None
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['ca_pool']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATECAPOOLREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_UPDATECAPOOLREQUEST'].fields_by_name['ca_pool']._loaded_options = None
    _globals['_UPDATECAPOOLREQUEST'].fields_by_name['ca_pool']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECAPOOLREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECAPOOLREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECAPOOLREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATECAPOOLREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECAPOOLREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECAPOOLREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_DELETECAPOOLREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETECAPOOLREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECAPOOLREQUEST'].fields_by_name['ignore_dependent_resources']._loaded_options = None
    _globals['_DELETECAPOOLREQUEST'].fields_by_name['ignore_dependent_resources']._serialized_options = b'\xe0A\x01'
    _globals['_FETCHCACERTSREQUEST'].fields_by_name['ca_pool']._loaded_options = None
    _globals['_FETCHCACERTSREQUEST'].fields_by_name['ca_pool']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_FETCHCACERTSREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_FETCHCACERTSREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_GETCAPOOLREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCAPOOLREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTCAPOOLSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETCERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA4\n2privateca.googleapis.com/CertificateRevocationList'
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\n-privateca.googleapis.com/CertificateAuthority'
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['certificate_revocation_list']._loaded_options = None
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['certificate_revocation_list']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['certificate_template_id']._loaded_options = None
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['certificate_template_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['certificate_template']._loaded_options = None
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['certificate_template']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATECERTIFICATETEMPLATEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECERTIFICATETEMPLATEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECERTIFICATETEMPLATEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA.\n,privateca.googleapis.com/CertificateTemplate'
    _globals['_DELETECERTIFICATETEMPLATEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETECERTIFICATETEMPLATEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_GETCERTIFICATETEMPLATEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCERTIFICATETEMPLATEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA.\n,privateca.googleapis.com/CertificateTemplate'
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTCERTIFICATETEMPLATESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST'].fields_by_name['certificate_template']._loaded_options = None
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST'].fields_by_name['certificate_template']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_CERTIFICATEAUTHORITYSERVICE']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE']._serialized_options = b'\xcaA\x18privateca.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCertificate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCertificate']._serialized_options = b'\xdaA!parent,certificate,certificate_id\x82\xd3\xe4\x93\x02I":/v1/{parent=projects/*/locations/*/caPools/*}/certificates:\x0bcertificate'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificate']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v1/{name=projects/*/locations/*/caPools/*/certificates/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificates']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificates']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v1/{parent=projects/*/locations/*/caPools/*}/certificates'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['RevokeCertificate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['RevokeCertificate']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02F"A/v1/{name=projects/*/locations/*/caPools/*/certificates/*}:revoke:\x01*'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificate']._serialized_options = b'\xdaA\x17certificate,update_mask\x82\xd3\xe4\x93\x02U2F/v1/{certificate.name=projects/*/locations/*/caPools/*/certificates/*}:\x0bcertificate'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ActivateCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ActivateCertificateAuthority']._serialized_options = b'\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02R"M/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:activate:\x01*'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCertificateAuthority']._serialized_options = b'\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA5parent,certificate_authority,certificate_authority_id\x82\xd3\xe4\x93\x02]"D/v1/{parent=projects/*/locations/*/caPools/*}/certificateAuthorities:\x15certificate_authority'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DisableCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DisableCertificateAuthority']._serialized_options = b'\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02Q"L/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:disable:\x01*'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['EnableCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['EnableCertificateAuthority']._serialized_options = b'\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02P"K/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:enable:\x01*'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['FetchCertificateAuthorityCsr']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['FetchCertificateAuthorityCsr']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02L\x12J/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:fetch'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificateAuthority']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02F\x12D/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificateAuthorities']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificateAuthorities']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02F\x12D/v1/{parent=projects/*/locations/*/caPools/*}/certificateAuthorities'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UndeleteCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UndeleteCertificateAuthority']._serialized_options = b'\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02R"M/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:undelete:\x01*'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DeleteCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DeleteCertificateAuthority']._serialized_options = b'\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02F*D/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificateAuthority']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificateAuthority']._serialized_options = b'\xcaA)\n\x14CertificateAuthority\x12\x11OperationMetadata\xdaA!certificate_authority,update_mask\x82\xd3\xe4\x93\x02s2Z/v1/{certificate_authority.name=projects/*/locations/*/caPools/*/certificateAuthorities/*}:\x15certificate_authority'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCaPool']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCaPool']._serialized_options = b'\xcaA\x1b\n\x06CaPool\x12\x11OperationMetadata\xdaA\x19parent,ca_pool,ca_pool_id\x82\xd3\xe4\x93\x026"+/v1/{parent=projects/*/locations/*}/caPools:\x07ca_pool'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCaPool']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCaPool']._serialized_options = b'\xcaA\x1b\n\x06CaPool\x12\x11OperationMetadata\xdaA\x13ca_pool,update_mask\x82\xd3\xe4\x93\x02>23/v1/{ca_pool.name=projects/*/locations/*/caPools/*}:\x07ca_pool'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCaPool']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCaPool']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1/{name=projects/*/locations/*/caPools/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCaPools']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCaPools']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=projects/*/locations/*}/caPools'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DeleteCaPool']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DeleteCaPool']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1/{name=projects/*/locations/*/caPools/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['FetchCaCerts']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['FetchCaCerts']._serialized_options = b'\xdaA\x07ca_pool\x82\xd3\xe4\x93\x02@";/v1/{ca_pool=projects/*/locations/*/caPools/*}:fetchCaCerts:\x01*'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificateRevocationList']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificateRevocationList']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02c\x12a/v1/{name=projects/*/locations/*/caPools/*/certificateAuthorities/*/certificateRevocationLists/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificateRevocationLists']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificateRevocationLists']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02c\x12a/v1/{parent=projects/*/locations/*/caPools/*/certificateAuthorities/*}/certificateRevocationLists'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificateRevocationList']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificateRevocationList']._serialized_options = b"\xcaA.\n\x19CertificateRevocationList\x12\x11OperationMetadata\xdaA'certificate_revocation_list,update_mask\x82\xd3\xe4\x93\x02\x9c\x012}/v1/{certificate_revocation_list.name=projects/*/locations/*/caPools/*/certificateAuthorities/*/certificateRevocationLists/*}:\x1bcertificate_revocation_list"
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCertificateTemplate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['CreateCertificateTemplate']._serialized_options = b'\xcaA(\n\x13CertificateTemplate\x12\x11OperationMetadata\xdaA3parent,certificate_template,certificate_template_id\x82\xd3\xe4\x93\x02P"8/v1/{parent=projects/*/locations/*}/certificateTemplates:\x14certificate_template'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DeleteCertificateTemplate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['DeleteCertificateTemplate']._serialized_options = b'\xcaAM\n\x15google.protobuf.Empty\x124google.cloud.security.privateca.v1.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02:*8/v1/{name=projects/*/locations/*/certificateTemplates/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificateTemplate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['GetCertificateTemplate']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02:\x128/v1/{name=projects/*/locations/*/certificateTemplates/*}'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificateTemplates']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['ListCertificateTemplates']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*}/certificateTemplates'
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificateTemplate']._loaded_options = None
    _globals['_CERTIFICATEAUTHORITYSERVICE'].methods_by_name['UpdateCertificateTemplate']._serialized_options = b'\xcaA(\n\x13CertificateTemplate\x12\x11OperationMetadata\xdaA certificate_template,update_mask\x82\xd3\xe4\x93\x02e2M/v1/{certificate_template.name=projects/*/locations/*/certificateTemplates/*}:\x14certificate_template'
    _globals['_CREATECERTIFICATEREQUEST']._serialized_start = 418
    _globals['_CREATECERTIFICATEREQUEST']._serialized_end = 705
    _globals['_GETCERTIFICATEREQUEST']._serialized_start = 707
    _globals['_GETCERTIFICATEREQUEST']._serialized_end = 790
    _globals['_LISTCERTIFICATESREQUEST']._serialized_start = 793
    _globals['_LISTCERTIFICATESREQUEST']._serialized_end = 968
    _globals['_LISTCERTIFICATESRESPONSE']._serialized_start = 971
    _globals['_LISTCERTIFICATESRESPONSE']._serialized_end = 1114
    _globals['_REVOKECERTIFICATEREQUEST']._serialized_start = 1117
    _globals['_REVOKECERTIFICATEREQUEST']._serialized_end = 1303
    _globals['_UPDATECERTIFICATEREQUEST']._serialized_start = 1306
    _globals['_UPDATECERTIFICATEREQUEST']._serialized_end = 1486
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST']._serialized_start = 1489
    _globals['_ACTIVATECERTIFICATEAUTHORITYREQUEST']._serialized_end = 1749
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST']._serialized_start = 1752
    _globals['_CREATECERTIFICATEAUTHORITYREQUEST']._serialized_end = 2002
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST']._serialized_start = 2005
    _globals['_DISABLECERTIFICATEAUTHORITYREQUEST']._serialized_end = 2184
    _globals['_ENABLECERTIFICATEAUTHORITYREQUEST']._serialized_start = 2187
    _globals['_ENABLECERTIFICATEAUTHORITYREQUEST']._serialized_end = 2324
    _globals['_FETCHCERTIFICATEAUTHORITYCSRREQUEST']._serialized_start = 2326
    _globals['_FETCHCERTIFICATEAUTHORITYCSRREQUEST']._serialized_end = 2432
    _globals['_FETCHCERTIFICATEAUTHORITYCSRRESPONSE']._serialized_start = 2434
    _globals['_FETCHCERTIFICATEAUTHORITYCSRRESPONSE']._serialized_end = 2494
    _globals['_GETCERTIFICATEAUTHORITYREQUEST']._serialized_start = 2496
    _globals['_GETCERTIFICATEAUTHORITYREQUEST']._serialized_end = 2597
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST']._serialized_start = 2600
    _globals['_LISTCERTIFICATEAUTHORITIESREQUEST']._serialized_end = 2785
    _globals['_LISTCERTIFICATEAUTHORITIESRESPONSE']._serialized_start = 2788
    _globals['_LISTCERTIFICATEAUTHORITIESRESPONSE']._serialized_end = 2961
    _globals['_UNDELETECERTIFICATEAUTHORITYREQUEST']._serialized_start = 2964
    _globals['_UNDELETECERTIFICATEAUTHORITYREQUEST']._serialized_end = 3103
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST']._serialized_start = 3106
    _globals['_DELETECERTIFICATEAUTHORITYREQUEST']._serialized_end = 3357
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST']._serialized_start = 3360
    _globals['_UPDATECERTIFICATEAUTHORITYREQUEST']._serialized_end = 3576
    _globals['_CREATECAPOOLREQUEST']._serialized_start = 3579
    _globals['_CREATECAPOOLREQUEST']._serialized_end = 3783
    _globals['_UPDATECAPOOLREQUEST']._serialized_start = 3786
    _globals['_UPDATECAPOOLREQUEST']._serialized_end = 3960
    _globals['_DELETECAPOOLREQUEST']._serialized_start = 3963
    _globals['_DELETECAPOOLREQUEST']._serialized_end = 4113
    _globals['_FETCHCACERTSREQUEST']._serialized_start = 4115
    _globals['_FETCHCACERTSREQUEST']._serialized_end = 4219
    _globals['_FETCHCACERTSRESPONSE']._serialized_start = 4222
    _globals['_FETCHCACERTSRESPONSE']._serialized_end = 4365
    _globals['_FETCHCACERTSRESPONSE_CERTCHAIN']._serialized_start = 4332
    _globals['_FETCHCACERTSRESPONSE_CERTCHAIN']._serialized_end = 4365
    _globals['_GETCAPOOLREQUEST']._serialized_start = 4367
    _globals['_GETCAPOOLREQUEST']._serialized_end = 4440
    _globals['_LISTCAPOOLSREQUEST']._serialized_start = 4443
    _globals['_LISTCAPOOLSREQUEST']._serialized_end = 4615
    _globals['_LISTCAPOOLSRESPONSE']._serialized_start = 4618
    _globals['_LISTCAPOOLSRESPONSE']._serialized_end = 4747
    _globals['_GETCERTIFICATEREVOCATIONLISTREQUEST']._serialized_start = 4749
    _globals['_GETCERTIFICATEREVOCATIONLISTREQUEST']._serialized_end = 4860
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST']._serialized_start = 4863
    _globals['_LISTCERTIFICATEREVOCATIONLISTSREQUEST']._serialized_end = 5066
    _globals['_LISTCERTIFICATEREVOCATIONLISTSRESPONSE']._serialized_start = 5069
    _globals['_LISTCERTIFICATEREVOCATIONLISTSRESPONSE']._serialized_end = 5256
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST']._serialized_start = 5259
    _globals['_UPDATECERTIFICATEREVOCATIONLISTREQUEST']._serialized_end = 5483
    _globals['_CREATECERTIFICATETEMPLATEREQUEST']._serialized_start = 5486
    _globals['_CREATECERTIFICATETEMPLATEREQUEST']._serialized_end = 5742
    _globals['_DELETECERTIFICATETEMPLATEREQUEST']._serialized_start = 5745
    _globals['_DELETECERTIFICATETEMPLATEREQUEST']._serialized_end = 5880
    _globals['_GETCERTIFICATETEMPLATEREQUEST']._serialized_start = 5882
    _globals['_GETCERTIFICATETEMPLATEREQUEST']._serialized_end = 5981
    _globals['_LISTCERTIFICATETEMPLATESREQUEST']._serialized_start = 5984
    _globals['_LISTCERTIFICATETEMPLATESREQUEST']._serialized_end = 6169
    _globals['_LISTCERTIFICATETEMPLATESRESPONSE']._serialized_start = 6172
    _globals['_LISTCERTIFICATETEMPLATESRESPONSE']._serialized_end = 6340
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST']._serialized_start = 6343
    _globals['_UPDATECERTIFICATETEMPLATEREQUEST']._serialized_end = 6556
    _globals['_OPERATIONMETADATA']._serialized_start = 6559
    _globals['_OPERATIONMETADATA']._serialized_end = 6815
    _globals['_CERTIFICATEAUTHORITYSERVICE']._serialized_start = 6818
    _globals['_CERTIFICATEAUTHORITYSERVICE']._serialized_end = 14492