"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/saasplatform/saasservicemgmt/v1beta1/deployments_service.proto')
_sym_db = _symbol_database.Default()
from ......google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from ......google.api import client_pb2 as google_dot_api_dot_client__pb2
from ......google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from ......google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from ......google.cloud.saasplatform.saasservicemgmt.v1beta1 import deployments_resources_pb2 as google_dot_cloud_dot_saasplatform_dot_saasservicemgmt_dot_v1beta1_dot_deployments__resources__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKgoogle/cloud/saasplatform/saasservicemgmt/v1beta1/deployments_service.proto\x121google.cloud.saasplatform.saasservicemgmt.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1aMgoogle/cloud/saasplatform/saasservicemgmt/v1beta1/deployments_resources.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto"\x9c\x01\n\x0fListSaasRequest\x12<\n\x06parent\x18\x96N \x01(\tB+\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Saas\x12\x12\n\tpage_size\x18\x89R \x01(\x05\x12\x13\n\npage_token\x18\x8aR \x01(\t\x12\x0f\n\x06filter\x18\x8bR \x01(\t\x12\x11\n\x08order_by\x18\x8cR \x01(\t"\x8a\x01\n\x10ListSaasResponse\x12F\n\x04saas\x18\x8dR \x03(\x0b27.google.cloud.saasplatform.saasservicemgmt.v1beta1.Saas\x12\x18\n\x0fnext_page_token\x18\x8eR \x01(\t\x12\x14\n\x0bunreachable\x18\x8fR \x03(\t"L\n\x0eGetSaasRequest\x12:\n\x04name\x18\x91N \x01(\tB+\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Saas"\xe2\x01\n\x11CreateSaasRequest\x12<\n\x06parent\x18\x96N \x01(\tB+\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Saas\x12\x15\n\x07saas_id\x18\x87R \x01(\tB\x03\xe0A\x02\x12K\n\x04saas\x18\x88R \x01(\x0b27.google.cloud.saasplatform.saasservicemgmt.v1beta1.SaasB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xbf\x01\n\x11UpdateSaasRequest\x12K\n\x04saas\x18\x88R \x01(\x0b27.google.cloud.saasplatform.saasservicemgmt.v1beta1.SaasB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t\x120\n\x0bupdate_mask\x18\x90R \x01(\x0b2\x1a.google.protobuf.FieldMask"\x8b\x01\n\x11DeleteSaasRequest\x12:\n\x04name\x18\x91N \x01(\tB+\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Saas\x12\r\n\x04etag\x18\xdaO \x01(\t\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xa1\x01\n\x12ListTenantsRequest\x12>\n\x06parent\x18\x96N \x01(\tB-\xe0A\x02\xfaA\'\x12%saasservicemgmt.googleapis.com/Tenant\x12\x12\n\tpage_size\x18\x89R \x01(\x05\x12\x13\n\npage_token\x18\x8aR \x01(\t\x12\x0f\n\x06filter\x18\x8bR \x01(\t\x12\x11\n\x08order_by\x18\x8cR \x01(\t"\x92\x01\n\x13ListTenantsResponse\x12K\n\x07tenants\x18\x8dR \x03(\x0b29.google.cloud.saasplatform.saasservicemgmt.v1beta1.Tenant\x12\x18\n\x0fnext_page_token\x18\x8eR \x01(\t\x12\x14\n\x0bunreachable\x18\x8fR \x03(\t"P\n\x10GetTenantRequest\x12<\n\x04name\x18\x91N \x01(\tB-\xe0A\x02\xfaA\'\n%saasservicemgmt.googleapis.com/Tenant"\xec\x01\n\x13CreateTenantRequest\x12>\n\x06parent\x18\x96N \x01(\tB-\xe0A\x02\xfaA\'\x12%saasservicemgmt.googleapis.com/Tenant\x12\x17\n\ttenant_id\x18\x87R \x01(\tB\x03\xe0A\x02\x12O\n\x06tenant\x18\x88R \x01(\x0b29.google.cloud.saasplatform.saasservicemgmt.v1beta1.TenantB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xc5\x01\n\x13UpdateTenantRequest\x12O\n\x06tenant\x18\x88R \x01(\x0b29.google.cloud.saasplatform.saasservicemgmt.v1beta1.TenantB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t\x120\n\x0bupdate_mask\x18\x90R \x01(\x0b2\x1a.google.protobuf.FieldMask"\x8f\x01\n\x13DeleteTenantRequest\x12<\n\x04name\x18\x91N \x01(\tB-\xe0A\x02\xfaA\'\n%saasservicemgmt.googleapis.com/Tenant\x12\r\n\x04etag\x18\xdaO \x01(\t\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xa5\x01\n\x14ListUnitKindsRequest\x12@\n\x06parent\x18\x96N \x01(\tB/\xe0A\x02\xfaA)\x12\'saasservicemgmt.googleapis.com/UnitKind\x12\x12\n\tpage_size\x18\x89R \x01(\x05\x12\x13\n\npage_token\x18\x8aR \x01(\t\x12\x0f\n\x06filter\x18\x8bR \x01(\t\x12\x11\n\x08order_by\x18\x8cR \x01(\t"\x99\x01\n\x15ListUnitKindsResponse\x12P\n\nunit_kinds\x18\x8dR \x03(\x0b2;.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitKind\x12\x18\n\x0fnext_page_token\x18\x8eR \x01(\t\x12\x14\n\x0bunreachable\x18\x8fR \x03(\t"T\n\x12GetUnitKindRequest\x12>\n\x04name\x18\x91N \x01(\tB/\xe0A\x02\xfaA)\n\'saasservicemgmt.googleapis.com/UnitKind"\xf8\x01\n\x15CreateUnitKindRequest\x12@\n\x06parent\x18\x96N \x01(\tB/\xe0A\x02\xfaA)\x12\'saasservicemgmt.googleapis.com/UnitKind\x12\x1a\n\x0cunit_kind_id\x18\x87R \x01(\tB\x03\xe0A\x02\x12T\n\tunit_kind\x18\x88R \x01(\x0b2;.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitKindB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xcc\x01\n\x15UpdateUnitKindRequest\x12T\n\tunit_kind\x18\x88R \x01(\x0b2;.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitKindB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t\x120\n\x0bupdate_mask\x18\x90R \x01(\x0b2\x1a.google.protobuf.FieldMask"\x93\x01\n\x15DeleteUnitKindRequest\x12>\n\x04name\x18\x91N \x01(\tB/\xe0A\x02\xfaA)\n\'saasservicemgmt.googleapis.com/UnitKind\x12\r\n\x04etag\x18\xdaO \x01(\t\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\x9d\x01\n\x10ListUnitsRequest\x12<\n\x06parent\x18\x96N \x01(\tB+\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Unit\x12\x12\n\tpage_size\x18\x89R \x01(\x05\x12\x13\n\npage_token\x18\x8aR \x01(\t\x12\x0f\n\x06filter\x18\x8bR \x01(\t\x12\x11\n\x08order_by\x18\x8cR \x01(\t"\x8c\x01\n\x11ListUnitsResponse\x12G\n\x05units\x18\x8dR \x03(\x0b27.google.cloud.saasplatform.saasservicemgmt.v1beta1.Unit\x12\x18\n\x0fnext_page_token\x18\x8eR \x01(\t\x12\x14\n\x0bunreachable\x18\x8fR \x03(\t"L\n\x0eGetUnitRequest\x12:\n\x04name\x18\x91N \x01(\tB+\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Unit"\xe2\x01\n\x11CreateUnitRequest\x12<\n\x06parent\x18\x96N \x01(\tB+\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Unit\x12\x15\n\x07unit_id\x18\x87R \x01(\tB\x03\xe0A\x02\x12K\n\x04unit\x18\x88R \x01(\x0b27.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xbf\x01\n\x11UpdateUnitRequest\x12K\n\x04unit\x18\x88R \x01(\x0b27.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t\x120\n\x0bupdate_mask\x18\x90R \x01(\x0b2\x1a.google.protobuf.FieldMask"\x8b\x01\n\x11DeleteUnitRequest\x12:\n\x04name\x18\x91N \x01(\tB+\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Unit\x12\r\n\x04etag\x18\xdaO \x01(\t\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xaf\x01\n\x19ListUnitOperationsRequest\x12E\n\x06parent\x18\x96N \x01(\tB4\xe0A\x02\xfaA.\x12,saasservicemgmt.googleapis.com/UnitOperation\x12\x12\n\tpage_size\x18\x89R \x01(\x05\x12\x13\n\npage_token\x18\x8aR \x01(\t\x12\x0f\n\x06filter\x18\x8bR \x01(\t\x12\x11\n\x08order_by\x18\x8cR \x01(\t"\xa8\x01\n\x1aListUnitOperationsResponse\x12Z\n\x0funit_operations\x18\x8dR \x03(\x0b2@.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitOperation\x12\x18\n\x0fnext_page_token\x18\x8eR \x01(\t\x12\x14\n\x0bunreachable\x18\x8fR \x03(\t"^\n\x17GetUnitOperationRequest\x12C\n\x04name\x18\x91N \x01(\tB4\xe0A\x02\xfaA.\n,saasservicemgmt.googleapis.com/UnitOperation"\x91\x02\n\x1aCreateUnitOperationRequest\x12E\n\x06parent\x18\x96N \x01(\tB4\xe0A\x02\xfaA.\x12,saasservicemgmt.googleapis.com/UnitOperation\x12\x1f\n\x11unit_operation_id\x18\x87R \x01(\tB\x03\xe0A\x02\x12^\n\x0eunit_operation\x18\x88R \x01(\x0b2@.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitOperationB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xdb\x01\n\x1aUpdateUnitOperationRequest\x12^\n\x0eunit_operation\x18\x88R \x01(\x0b2@.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitOperationB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t\x120\n\x0bupdate_mask\x18\x90R \x01(\x0b2\x1a.google.protobuf.FieldMask"\x9d\x01\n\x1aDeleteUnitOperationRequest\x12C\n\x04name\x18\x91N \x01(\tB4\xe0A\x02\xfaA.\n,saasservicemgmt.googleapis.com/UnitOperation\x12\r\n\x04etag\x18\xdaO \x01(\t\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xa3\x01\n\x13ListReleasesRequest\x12?\n\x06parent\x18\x96N \x01(\tB.\xe0A\x02\xfaA(\x12&saasservicemgmt.googleapis.com/Release\x12\x12\n\tpage_size\x18\x89R \x01(\x05\x12\x13\n\npage_token\x18\x8aR \x01(\t\x12\x0f\n\x06filter\x18\x8bR \x01(\t\x12\x11\n\x08order_by\x18\x8cR \x01(\t"\x95\x01\n\x14ListReleasesResponse\x12M\n\x08releases\x18\x8dR \x03(\x0b2:.google.cloud.saasplatform.saasservicemgmt.v1beta1.Release\x12\x18\n\x0fnext_page_token\x18\x8eR \x01(\t\x12\x14\n\x0bunreachable\x18\x8fR \x03(\t"R\n\x11GetReleaseRequest\x12=\n\x04name\x18\x91N \x01(\tB.\xe0A\x02\xfaA(\n&saasservicemgmt.googleapis.com/Release"\xf1\x01\n\x14CreateReleaseRequest\x12?\n\x06parent\x18\x96N \x01(\tB.\xe0A\x02\xfaA(\x12&saasservicemgmt.googleapis.com/Release\x12\x18\n\nrelease_id\x18\x87R \x01(\tB\x03\xe0A\x02\x12Q\n\x07release\x18\x88R \x01(\x0b2:.google.cloud.saasplatform.saasservicemgmt.v1beta1.ReleaseB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t"\xc8\x01\n\x14UpdateReleaseRequest\x12Q\n\x07release\x18\x88R \x01(\x0b2:.google.cloud.saasplatform.saasservicemgmt.v1beta1.ReleaseB\x03\xe0A\x02\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t\x120\n\x0bupdate_mask\x18\x90R \x01(\x0b2\x1a.google.protobuf.FieldMask"\x91\x01\n\x14DeleteReleaseRequest\x12=\n\x04name\x18\x91N \x01(\tB.\xe0A\x02\xfaA(\n&saasservicemgmt.googleapis.com/Release\x12\r\n\x04etag\x18\xdaO \x01(\t\x12\x16\n\rvalidate_only\x18\x85R \x01(\x08\x12\x13\n\nrequest_id\x18\x86R \x01(\t2\x9d5\n\x0fSaasDeployments\x12\xd3\x01\n\x08ListSaas\x12B.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListSaasRequest\x1aC.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListSaasResponse">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1beta1/{parent=projects/*/locations/*}/saas\x12\xc3\x01\n\x07GetSaas\x12A.google.cloud.saasplatform.saasservicemgmt.v1beta1.GetSaasRequest\x1a7.google.cloud.saasplatform.saasservicemgmt.v1beta1.Saas"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1beta1/{name=projects/*/locations/*/saas/*}\x12\xde\x01\n\nCreateSaas\x12D.google.cloud.saasplatform.saasservicemgmt.v1beta1.CreateSaasRequest\x1a7.google.cloud.saasplatform.saasservicemgmt.v1beta1.Saas"Q\xdaA\x13parent,saas,saas_id\x82\xd3\xe4\x93\x025"-/v1beta1/{parent=projects/*/locations/*}/saas:\x04saas\x12\xe0\x01\n\nUpdateSaas\x12D.google.cloud.saasplatform.saasservicemgmt.v1beta1.UpdateSaasRequest\x1a7.google.cloud.saasplatform.saasservicemgmt.v1beta1.Saas"S\xdaA\x10saas,update_mask\x82\xd3\xe4\x93\x02:22/v1beta1/{saas.name=projects/*/locations/*/saas/*}:\x04saas\x12\xa8\x01\n\nDeleteSaas\x12D.google.cloud.saasplatform.saasservicemgmt.v1beta1.DeleteSaasRequest\x1a\x16.google.protobuf.Empty"<\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1beta1/{name=projects/*/locations/*/saas/*}\x12\xdf\x01\n\x0bListTenants\x12E.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListTenantsRequest\x1aF.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListTenantsResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1beta1/{parent=projects/*/locations/*}/tenants\x12\xcc\x01\n\tGetTenant\x12C.google.cloud.saasplatform.saasservicemgmt.v1beta1.GetTenantRequest\x1a9.google.cloud.saasplatform.saasservicemgmt.v1beta1.Tenant"?\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1beta1/{name=projects/*/locations/*/tenants/*}\x12\xed\x01\n\x0cCreateTenant\x12F.google.cloud.saasplatform.saasservicemgmt.v1beta1.CreateTenantRequest\x1a9.google.cloud.saasplatform.saasservicemgmt.v1beta1.Tenant"Z\xdaA\x17parent,tenant,tenant_id\x82\xd3\xe4\x93\x02:"0/v1beta1/{parent=projects/*/locations/*}/tenants:\x06tenant\x12\xef\x01\n\x0cUpdateTenant\x12F.google.cloud.saasplatform.saasservicemgmt.v1beta1.UpdateTenantRequest\x1a9.google.cloud.saasplatform.saasservicemgmt.v1beta1.Tenant"\\\xdaA\x12tenant,update_mask\x82\xd3\xe4\x93\x02A27/v1beta1/{tenant.name=projects/*/locations/*/tenants/*}:\x06tenant\x12\xaf\x01\n\x0cDeleteTenant\x12F.google.cloud.saasplatform.saasservicemgmt.v1beta1.DeleteTenantRequest\x1a\x16.google.protobuf.Empty"?\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1beta1/{name=projects/*/locations/*/tenants/*}\x12\xe7\x01\n\rListUnitKinds\x12G.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListUnitKindsRequest\x1aH.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListUnitKindsResponse"C\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1beta1/{parent=projects/*/locations/*}/unitKinds\x12\xd4\x01\n\x0bGetUnitKind\x12E.google.cloud.saasplatform.saasservicemgmt.v1beta1.GetUnitKindRequest\x1a;.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitKind"A\xdaA\x04name\x82\xd3\xe4\x93\x024\x122/v1beta1/{name=projects/*/locations/*/unitKinds/*}\x12\xfe\x01\n\x0eCreateUnitKind\x12H.google.cloud.saasplatform.saasservicemgmt.v1beta1.CreateUnitKindRequest\x1a;.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitKind"e\xdaA\x1dparent,unit_kind,unit_kind_id\x82\xd3\xe4\x93\x02?"2/v1beta1/{parent=projects/*/locations/*}/unitKinds:\tunit_kind\x12\x80\x02\n\x0eUpdateUnitKind\x12H.google.cloud.saasplatform.saasservicemgmt.v1beta1.UpdateUnitKindRequest\x1a;.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitKind"g\xdaA\x15unit_kind,update_mask\x82\xd3\xe4\x93\x02I2</v1beta1/{unit_kind.name=projects/*/locations/*/unitKinds/*}:\tunit_kind\x12\xb5\x01\n\x0eDeleteUnitKind\x12H.google.cloud.saasplatform.saasservicemgmt.v1beta1.DeleteUnitKindRequest\x1a\x16.google.protobuf.Empty"A\xdaA\x04name\x82\xd3\xe4\x93\x024*2/v1beta1/{name=projects/*/locations/*/unitKinds/*}\x12\xd7\x01\n\tListUnits\x12C.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListUnitsRequest\x1aD.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListUnitsResponse"?\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1beta1/{parent=projects/*/locations/*}/units\x12\xc4\x01\n\x07GetUnit\x12A.google.cloud.saasplatform.saasservicemgmt.v1beta1.GetUnitRequest\x1a7.google.cloud.saasplatform.saasservicemgmt.v1beta1.Unit"=\xdaA\x04name\x82\xd3\xe4\x93\x020\x12./v1beta1/{name=projects/*/locations/*/units/*}\x12\xdf\x01\n\nCreateUnit\x12D.google.cloud.saasplatform.saasservicemgmt.v1beta1.CreateUnitRequest\x1a7.google.cloud.saasplatform.saasservicemgmt.v1beta1.Unit"R\xdaA\x13parent,unit,unit_id\x82\xd3\xe4\x93\x026"./v1beta1/{parent=projects/*/locations/*}/units:\x04unit\x12\xe1\x01\n\nUpdateUnit\x12D.google.cloud.saasplatform.saasservicemgmt.v1beta1.UpdateUnitRequest\x1a7.google.cloud.saasplatform.saasservicemgmt.v1beta1.Unit"T\xdaA\x10unit,update_mask\x82\xd3\xe4\x93\x02;23/v1beta1/{unit.name=projects/*/locations/*/units/*}:\x04unit\x12\xa9\x01\n\nDeleteUnit\x12D.google.cloud.saasplatform.saasservicemgmt.v1beta1.DeleteUnitRequest\x1a\x16.google.protobuf.Empty"=\xdaA\x04name\x82\xd3\xe4\x93\x020*./v1beta1/{name=projects/*/locations/*/units/*}\x12\xfb\x01\n\x12ListUnitOperations\x12L.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListUnitOperationsRequest\x1aM.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListUnitOperationsResponse"H\xdaA\x06parent\x82\xd3\xe4\x93\x029\x127/v1beta1/{parent=projects/*/locations/*}/unitOperations\x12\xe8\x01\n\x10GetUnitOperation\x12J.google.cloud.saasplatform.saasservicemgmt.v1beta1.GetUnitOperationRequest\x1a@.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitOperation"F\xdaA\x04name\x82\xd3\xe4\x93\x029\x127/v1beta1/{name=projects/*/locations/*/unitOperations/*}\x12\xa1\x02\n\x13CreateUnitOperation\x12M.google.cloud.saasplatform.saasservicemgmt.v1beta1.CreateUnitOperationRequest\x1a@.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitOperation"y\xdaA\'parent,unit_operation,unit_operation_id\x82\xd3\xe4\x93\x02I"7/v1beta1/{parent=projects/*/locations/*}/unitOperations:\x0eunit_operation\x12\xa3\x02\n\x13UpdateUnitOperation\x12M.google.cloud.saasplatform.saasservicemgmt.v1beta1.UpdateUnitOperationRequest\x1a@.google.cloud.saasplatform.saasservicemgmt.v1beta1.UnitOperation"{\xdaA\x1aunit_operation,update_mask\x82\xd3\xe4\x93\x02X2F/v1beta1/{unit_operation.name=projects/*/locations/*/unitOperations/*}:\x0eunit_operation\x12\xc4\x01\n\x13DeleteUnitOperation\x12M.google.cloud.saasplatform.saasservicemgmt.v1beta1.DeleteUnitOperationRequest\x1a\x16.google.protobuf.Empty"F\xdaA\x04name\x82\xd3\xe4\x93\x029*7/v1beta1/{name=projects/*/locations/*/unitOperations/*}\x12\xe3\x01\n\x0cListReleases\x12F.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListReleasesRequest\x1aG.google.cloud.saasplatform.saasservicemgmt.v1beta1.ListReleasesResponse"B\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1beta1/{parent=projects/*/locations/*}/releases\x12\xd0\x01\n\nGetRelease\x12D.google.cloud.saasplatform.saasservicemgmt.v1beta1.GetReleaseRequest\x1a:.google.cloud.saasplatform.saasservicemgmt.v1beta1.Release"@\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1beta1/{name=projects/*/locations/*/releases/*}\x12\xf4\x01\n\rCreateRelease\x12G.google.cloud.saasplatform.saasservicemgmt.v1beta1.CreateReleaseRequest\x1a:.google.cloud.saasplatform.saasservicemgmt.v1beta1.Release"^\xdaA\x19parent,release,release_id\x82\xd3\xe4\x93\x02<"1/v1beta1/{parent=projects/*/locations/*}/releases:\x07release\x12\xf6\x01\n\rUpdateRelease\x12G.google.cloud.saasplatform.saasservicemgmt.v1beta1.UpdateReleaseRequest\x1a:.google.cloud.saasplatform.saasservicemgmt.v1beta1.Release"`\xdaA\x13release,update_mask\x82\xd3\xe4\x93\x02D29/v1beta1/{release.name=projects/*/locations/*/releases/*}:\x07release\x12\xb2\x01\n\rDeleteRelease\x12G.google.cloud.saasplatform.saasservicemgmt.v1beta1.DeleteReleaseRequest\x1a\x16.google.protobuf.Empty"@\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1beta1/{name=projects/*/locations/*/releases/*}\x1aR\xcaA\x1esaasservicemgmt.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xd7\x02\n5com.google.cloud.saasplatform.saasservicemgmt.v1beta1B\x1bSaasDeploymentsServiceProtoP\x01Z_cloud.google.com/go/saasplatform/saasservicemgmt/apiv1beta1/saasservicemgmtpb;saasservicemgmtpb\xaa\x021Google.Cloud.SaasPlatform.SaasServiceMgmt.V1Beta1\xca\x021Google\\Cloud\\SaasPlatform\\SaasServiceMgmt\\V1beta1\xea\x025Google::Cloud::SaasPlatform::SaasServiceMgmt::V1beta1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.saasplatform.saasservicemgmt.v1beta1.deployments_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n5com.google.cloud.saasplatform.saasservicemgmt.v1beta1B\x1bSaasDeploymentsServiceProtoP\x01Z_cloud.google.com/go/saasplatform/saasservicemgmt/apiv1beta1/saasservicemgmtpb;saasservicemgmtpb\xaa\x021Google.Cloud.SaasPlatform.SaasServiceMgmt.V1Beta1\xca\x021Google\\Cloud\\SaasPlatform\\SaasServiceMgmt\\V1beta1\xea\x025Google::Cloud::SaasPlatform::SaasServiceMgmt::V1beta1'
    _globals['_LISTSAASREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSAASREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Saas'
    _globals['_GETSAASREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSAASREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Saas'
    _globals['_CREATESAASREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESAASREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Saas'
    _globals['_CREATESAASREQUEST'].fields_by_name['saas_id']._loaded_options = None
    _globals['_CREATESAASREQUEST'].fields_by_name['saas_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESAASREQUEST'].fields_by_name['saas']._loaded_options = None
    _globals['_CREATESAASREQUEST'].fields_by_name['saas']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESAASREQUEST'].fields_by_name['saas']._loaded_options = None
    _globals['_UPDATESAASREQUEST'].fields_by_name['saas']._serialized_options = b'\xe0A\x02'
    _globals['_DELETESAASREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESAASREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Saas'
    _globals['_LISTTENANTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTTENANTSREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\x12%saasservicemgmt.googleapis.com/Tenant"
    _globals['_GETTENANTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETTENANTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%saasservicemgmt.googleapis.com/Tenant"
    _globals['_CREATETENANTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATETENANTREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\x12%saasservicemgmt.googleapis.com/Tenant"
    _globals['_CREATETENANTREQUEST'].fields_by_name['tenant_id']._loaded_options = None
    _globals['_CREATETENANTREQUEST'].fields_by_name['tenant_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETENANTREQUEST'].fields_by_name['tenant']._loaded_options = None
    _globals['_CREATETENANTREQUEST'].fields_by_name['tenant']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATETENANTREQUEST'].fields_by_name['tenant']._loaded_options = None
    _globals['_UPDATETENANTREQUEST'].fields_by_name['tenant']._serialized_options = b'\xe0A\x02'
    _globals['_DELETETENANTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETETENANTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%saasservicemgmt.googleapis.com/Tenant"
    _globals['_LISTUNITKINDSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTUNITKINDSREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'saasservicemgmt.googleapis.com/UnitKind"
    _globals['_GETUNITKINDREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETUNITKINDREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'saasservicemgmt.googleapis.com/UnitKind"
    _globals['_CREATEUNITKINDREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEUNITKINDREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'saasservicemgmt.googleapis.com/UnitKind"
    _globals['_CREATEUNITKINDREQUEST'].fields_by_name['unit_kind_id']._loaded_options = None
    _globals['_CREATEUNITKINDREQUEST'].fields_by_name['unit_kind_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEUNITKINDREQUEST'].fields_by_name['unit_kind']._loaded_options = None
    _globals['_CREATEUNITKINDREQUEST'].fields_by_name['unit_kind']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEUNITKINDREQUEST'].fields_by_name['unit_kind']._loaded_options = None
    _globals['_UPDATEUNITKINDREQUEST'].fields_by_name['unit_kind']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEUNITKINDREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEUNITKINDREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'saasservicemgmt.googleapis.com/UnitKind"
    _globals['_LISTUNITSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTUNITSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Unit'
    _globals['_GETUNITREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETUNITREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Unit'
    _globals['_CREATEUNITREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEUNITREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\x12#saasservicemgmt.googleapis.com/Unit'
    _globals['_CREATEUNITREQUEST'].fields_by_name['unit_id']._loaded_options = None
    _globals['_CREATEUNITREQUEST'].fields_by_name['unit_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEUNITREQUEST'].fields_by_name['unit']._loaded_options = None
    _globals['_CREATEUNITREQUEST'].fields_by_name['unit']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEUNITREQUEST'].fields_by_name['unit']._loaded_options = None
    _globals['_UPDATEUNITREQUEST'].fields_by_name['unit']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEUNITREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEUNITREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#saasservicemgmt.googleapis.com/Unit'
    _globals['_LISTUNITOPERATIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTUNITOPERATIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA.\x12,saasservicemgmt.googleapis.com/UnitOperation'
    _globals['_GETUNITOPERATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETUNITOPERATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA.\n,saasservicemgmt.googleapis.com/UnitOperation'
    _globals['_CREATEUNITOPERATIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEUNITOPERATIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA.\x12,saasservicemgmt.googleapis.com/UnitOperation'
    _globals['_CREATEUNITOPERATIONREQUEST'].fields_by_name['unit_operation_id']._loaded_options = None
    _globals['_CREATEUNITOPERATIONREQUEST'].fields_by_name['unit_operation_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEUNITOPERATIONREQUEST'].fields_by_name['unit_operation']._loaded_options = None
    _globals['_CREATEUNITOPERATIONREQUEST'].fields_by_name['unit_operation']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEUNITOPERATIONREQUEST'].fields_by_name['unit_operation']._loaded_options = None
    _globals['_UPDATEUNITOPERATIONREQUEST'].fields_by_name['unit_operation']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEUNITOPERATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEUNITOPERATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA.\n,saasservicemgmt.googleapis.com/UnitOperation'
    _globals['_LISTRELEASESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTRELEASESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\x12&saasservicemgmt.googleapis.com/Release'
    _globals['_GETRELEASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETRELEASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&saasservicemgmt.googleapis.com/Release'
    _globals['_CREATERELEASEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATERELEASEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\x12&saasservicemgmt.googleapis.com/Release'
    _globals['_CREATERELEASEREQUEST'].fields_by_name['release_id']._loaded_options = None
    _globals['_CREATERELEASEREQUEST'].fields_by_name['release_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATERELEASEREQUEST'].fields_by_name['release']._loaded_options = None
    _globals['_CREATERELEASEREQUEST'].fields_by_name['release']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATERELEASEREQUEST'].fields_by_name['release']._loaded_options = None
    _globals['_UPDATERELEASEREQUEST'].fields_by_name['release']._serialized_options = b'\xe0A\x02'
    _globals['_DELETERELEASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETERELEASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&saasservicemgmt.googleapis.com/Release'
    _globals['_SAASDEPLOYMENTS']._loaded_options = None
    _globals['_SAASDEPLOYMENTS']._serialized_options = b'\xcaA\x1esaasservicemgmt.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListSaas']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListSaas']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1beta1/{parent=projects/*/locations/*}/saas'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetSaas']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetSaas']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1beta1/{name=projects/*/locations/*/saas/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateSaas']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateSaas']._serialized_options = b'\xdaA\x13parent,saas,saas_id\x82\xd3\xe4\x93\x025"-/v1beta1/{parent=projects/*/locations/*}/saas:\x04saas'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateSaas']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateSaas']._serialized_options = b'\xdaA\x10saas,update_mask\x82\xd3\xe4\x93\x02:22/v1beta1/{saas.name=projects/*/locations/*/saas/*}:\x04saas'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteSaas']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteSaas']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1beta1/{name=projects/*/locations/*/saas/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListTenants']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListTenants']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1beta1/{parent=projects/*/locations/*}/tenants'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetTenant']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetTenant']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1beta1/{name=projects/*/locations/*/tenants/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateTenant']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateTenant']._serialized_options = b'\xdaA\x17parent,tenant,tenant_id\x82\xd3\xe4\x93\x02:"0/v1beta1/{parent=projects/*/locations/*}/tenants:\x06tenant'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateTenant']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateTenant']._serialized_options = b'\xdaA\x12tenant,update_mask\x82\xd3\xe4\x93\x02A27/v1beta1/{tenant.name=projects/*/locations/*/tenants/*}:\x06tenant'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteTenant']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteTenant']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1beta1/{name=projects/*/locations/*/tenants/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListUnitKinds']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListUnitKinds']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1beta1/{parent=projects/*/locations/*}/unitKinds'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetUnitKind']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetUnitKind']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x024\x122/v1beta1/{name=projects/*/locations/*/unitKinds/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateUnitKind']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateUnitKind']._serialized_options = b'\xdaA\x1dparent,unit_kind,unit_kind_id\x82\xd3\xe4\x93\x02?"2/v1beta1/{parent=projects/*/locations/*}/unitKinds:\tunit_kind'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateUnitKind']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateUnitKind']._serialized_options = b'\xdaA\x15unit_kind,update_mask\x82\xd3\xe4\x93\x02I2</v1beta1/{unit_kind.name=projects/*/locations/*/unitKinds/*}:\tunit_kind'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteUnitKind']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteUnitKind']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x024*2/v1beta1/{name=projects/*/locations/*/unitKinds/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListUnits']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListUnits']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1beta1/{parent=projects/*/locations/*}/units'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetUnit']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetUnit']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x020\x12./v1beta1/{name=projects/*/locations/*/units/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateUnit']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateUnit']._serialized_options = b'\xdaA\x13parent,unit,unit_id\x82\xd3\xe4\x93\x026"./v1beta1/{parent=projects/*/locations/*}/units:\x04unit'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateUnit']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateUnit']._serialized_options = b'\xdaA\x10unit,update_mask\x82\xd3\xe4\x93\x02;23/v1beta1/{unit.name=projects/*/locations/*/units/*}:\x04unit'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteUnit']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteUnit']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x020*./v1beta1/{name=projects/*/locations/*/units/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListUnitOperations']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListUnitOperations']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x029\x127/v1beta1/{parent=projects/*/locations/*}/unitOperations'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetUnitOperation']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetUnitOperation']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x029\x127/v1beta1/{name=projects/*/locations/*/unitOperations/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateUnitOperation']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateUnitOperation']._serialized_options = b'\xdaA\'parent,unit_operation,unit_operation_id\x82\xd3\xe4\x93\x02I"7/v1beta1/{parent=projects/*/locations/*}/unitOperations:\x0eunit_operation'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateUnitOperation']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateUnitOperation']._serialized_options = b'\xdaA\x1aunit_operation,update_mask\x82\xd3\xe4\x93\x02X2F/v1beta1/{unit_operation.name=projects/*/locations/*/unitOperations/*}:\x0eunit_operation'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteUnitOperation']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteUnitOperation']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x029*7/v1beta1/{name=projects/*/locations/*/unitOperations/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListReleases']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['ListReleases']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1beta1/{parent=projects/*/locations/*}/releases'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetRelease']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['GetRelease']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1beta1/{name=projects/*/locations/*/releases/*}'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateRelease']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['CreateRelease']._serialized_options = b'\xdaA\x19parent,release,release_id\x82\xd3\xe4\x93\x02<"1/v1beta1/{parent=projects/*/locations/*}/releases:\x07release'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateRelease']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['UpdateRelease']._serialized_options = b'\xdaA\x13release,update_mask\x82\xd3\xe4\x93\x02D29/v1beta1/{release.name=projects/*/locations/*/releases/*}:\x07release'
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteRelease']._loaded_options = None
    _globals['_SAASDEPLOYMENTS'].methods_by_name['DeleteRelease']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1beta1/{name=projects/*/locations/*/releases/*}'
    _globals['_LISTSAASREQUEST']._serialized_start = 388
    _globals['_LISTSAASREQUEST']._serialized_end = 544
    _globals['_LISTSAASRESPONSE']._serialized_start = 547
    _globals['_LISTSAASRESPONSE']._serialized_end = 685
    _globals['_GETSAASREQUEST']._serialized_start = 687
    _globals['_GETSAASREQUEST']._serialized_end = 763
    _globals['_CREATESAASREQUEST']._serialized_start = 766
    _globals['_CREATESAASREQUEST']._serialized_end = 992
    _globals['_UPDATESAASREQUEST']._serialized_start = 995
    _globals['_UPDATESAASREQUEST']._serialized_end = 1186
    _globals['_DELETESAASREQUEST']._serialized_start = 1189
    _globals['_DELETESAASREQUEST']._serialized_end = 1328
    _globals['_LISTTENANTSREQUEST']._serialized_start = 1331
    _globals['_LISTTENANTSREQUEST']._serialized_end = 1492
    _globals['_LISTTENANTSRESPONSE']._serialized_start = 1495
    _globals['_LISTTENANTSRESPONSE']._serialized_end = 1641
    _globals['_GETTENANTREQUEST']._serialized_start = 1643
    _globals['_GETTENANTREQUEST']._serialized_end = 1723
    _globals['_CREATETENANTREQUEST']._serialized_start = 1726
    _globals['_CREATETENANTREQUEST']._serialized_end = 1962
    _globals['_UPDATETENANTREQUEST']._serialized_start = 1965
    _globals['_UPDATETENANTREQUEST']._serialized_end = 2162
    _globals['_DELETETENANTREQUEST']._serialized_start = 2165
    _globals['_DELETETENANTREQUEST']._serialized_end = 2308
    _globals['_LISTUNITKINDSREQUEST']._serialized_start = 2311
    _globals['_LISTUNITKINDSREQUEST']._serialized_end = 2476
    _globals['_LISTUNITKINDSRESPONSE']._serialized_start = 2479
    _globals['_LISTUNITKINDSRESPONSE']._serialized_end = 2632
    _globals['_GETUNITKINDREQUEST']._serialized_start = 2634
    _globals['_GETUNITKINDREQUEST']._serialized_end = 2718
    _globals['_CREATEUNITKINDREQUEST']._serialized_start = 2721
    _globals['_CREATEUNITKINDREQUEST']._serialized_end = 2969
    _globals['_UPDATEUNITKINDREQUEST']._serialized_start = 2972
    _globals['_UPDATEUNITKINDREQUEST']._serialized_end = 3176
    _globals['_DELETEUNITKINDREQUEST']._serialized_start = 3179
    _globals['_DELETEUNITKINDREQUEST']._serialized_end = 3326
    _globals['_LISTUNITSREQUEST']._serialized_start = 3329
    _globals['_LISTUNITSREQUEST']._serialized_end = 3486
    _globals['_LISTUNITSRESPONSE']._serialized_start = 3489
    _globals['_LISTUNITSRESPONSE']._serialized_end = 3629
    _globals['_GETUNITREQUEST']._serialized_start = 3631
    _globals['_GETUNITREQUEST']._serialized_end = 3707
    _globals['_CREATEUNITREQUEST']._serialized_start = 3710
    _globals['_CREATEUNITREQUEST']._serialized_end = 3936
    _globals['_UPDATEUNITREQUEST']._serialized_start = 3939
    _globals['_UPDATEUNITREQUEST']._serialized_end = 4130
    _globals['_DELETEUNITREQUEST']._serialized_start = 4133
    _globals['_DELETEUNITREQUEST']._serialized_end = 4272
    _globals['_LISTUNITOPERATIONSREQUEST']._serialized_start = 4275
    _globals['_LISTUNITOPERATIONSREQUEST']._serialized_end = 4450
    _globals['_LISTUNITOPERATIONSRESPONSE']._serialized_start = 4453
    _globals['_LISTUNITOPERATIONSRESPONSE']._serialized_end = 4621
    _globals['_GETUNITOPERATIONREQUEST']._serialized_start = 4623
    _globals['_GETUNITOPERATIONREQUEST']._serialized_end = 4717
    _globals['_CREATEUNITOPERATIONREQUEST']._serialized_start = 4720
    _globals['_CREATEUNITOPERATIONREQUEST']._serialized_end = 4993
    _globals['_UPDATEUNITOPERATIONREQUEST']._serialized_start = 4996
    _globals['_UPDATEUNITOPERATIONREQUEST']._serialized_end = 5215
    _globals['_DELETEUNITOPERATIONREQUEST']._serialized_start = 5218
    _globals['_DELETEUNITOPERATIONREQUEST']._serialized_end = 5375
    _globals['_LISTRELEASESREQUEST']._serialized_start = 5378
    _globals['_LISTRELEASESREQUEST']._serialized_end = 5541
    _globals['_LISTRELEASESRESPONSE']._serialized_start = 5544
    _globals['_LISTRELEASESRESPONSE']._serialized_end = 5693
    _globals['_GETRELEASEREQUEST']._serialized_start = 5695
    _globals['_GETRELEASEREQUEST']._serialized_end = 5777
    _globals['_CREATERELEASEREQUEST']._serialized_start = 5780
    _globals['_CREATERELEASEREQUEST']._serialized_end = 6021
    _globals['_UPDATERELEASEREQUEST']._serialized_start = 6024
    _globals['_UPDATERELEASEREQUEST']._serialized_end = 6224
    _globals['_DELETERELEASEREQUEST']._serialized_start = 6227
    _globals['_DELETERELEASEREQUEST']._serialized_end = 6372
    _globals['_SAASDEPLOYMENTS']._serialized_start = 6375
    _globals['_SAASDEPLOYMENTS']._serialized_end = 13188