# coding: utf-8

"""
    Phoenix API

    Base API for Glumanda and other services.

    The version of the OpenAPI document: Alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from phoenix_sdk.models.page_device_config_schema_out import PageDeviceConfigSchemaOUT

class TestPageDeviceConfigSchemaOUT(unittest.TestCase):
    """PageDeviceConfigSchemaOUT unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageDeviceConfigSchemaOUT:
        """Test PageDeviceConfigSchemaOUT
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageDeviceConfigSchemaOUT`
        """
        model = PageDeviceConfigSchemaOUT()
        if include_optional:
            return PageDeviceConfigSchemaOUT(
                results = [
                    phoenix_sdk.models.device_config_schema_out.DeviceConfigSchemaOUT(
                        created_by_id = null, 
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        conf = { }, 
                        formatter = '', 
                        is_ems = True, 
                        display_name = '', 
                        manufacturer = '', 
                        device_type = '', 
                        protocol = '', )
                    ],
                page = 1.0,
                size = 1.0,
                pages = 0.0,
                total = 0.0,
                has_next = True,
                has_prev = True
            )
        else:
            return PageDeviceConfigSchemaOUT(
                results = [
                    phoenix_sdk.models.device_config_schema_out.DeviceConfigSchemaOUT(
                        created_by_id = null, 
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        conf = { }, 
                        formatter = '', 
                        is_ems = True, 
                        display_name = '', 
                        manufacturer = '', 
                        device_type = '', 
                        protocol = '', )
                    ],
                total = 0.0,
        )
        """

    def testPageDeviceConfigSchemaOUT(self):
        """Test PageDeviceConfigSchemaOUT"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
