"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/functions/v2/functions.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .....google.type import date_pb2 as google_dot_type_dot_date__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)google/cloud/functions/v2/functions.proto\x12\x19google.cloud.functions.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a#google/longrunning/operations.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto"\xd9\x07\n\x08Function\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12<\n\x0cbuild_config\x18\x03 \x01(\x0b2&.google.cloud.functions.v2.BuildConfig\x12@\n\x0eservice_config\x18\x04 \x01(\x0b2(.google.cloud.functions.v2.ServiceConfig\x12>\n\revent_trigger\x18\x05 \x01(\x0b2\'.google.cloud.functions.v2.EventTrigger\x12=\n\x05state\x18\x06 \x01(\x0e2).google.cloud.functions.v2.Function.StateB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x07 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12?\n\x06labels\x18\x08 \x03(\x0b2/.google.cloud.functions.v2.Function.LabelsEntry\x12D\n\x0estate_messages\x18\t \x03(\x0b2\'.google.cloud.functions.v2.StateMessageB\x03\xe0A\x03\x12;\n\x0benvironment\x18\n \x01(\x0e2&.google.cloud.functions.v2.Environment\x12\x10\n\x03url\x18\x0e \x01(\tB\x03\xe0A\x03\x12<\n\x0ckms_key_name\x18\x19 \x01(\tB&\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12\x1a\n\rsatisfies_pzs\x18\x1b \x01(\x08B\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x1c \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"`\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\n\n\x06ACTIVE\x10\x01\x12\n\n\x06FAILED\x10\x02\x12\r\n\tDEPLOYING\x10\x03\x12\x0c\n\x08DELETING\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x05:~\xeaA{\n&cloudfunctions.googleapis.com/Function\x12<projects/{project}/locations/{location}/functions/{function}*\tfunctions2\x08function"\xb9\x01\n\x0cStateMessage\x12B\n\x08severity\x18\x01 \x01(\x0e20.google.cloud.functions.v2.StateMessage.Severity\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t"F\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\t\n\x05ERROR\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\x08\n\x04INFO\x10\x03"^\n\rStorageSource\x12\x0e\n\x06bucket\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x12\n\ngeneration\x18\x03 \x01(\x03\x12\x19\n\x11source_upload_url\x18\x04 \x01(\t"\xa3\x01\n\nRepoSource\x12\x15\n\x0bbranch_name\x18\x03 \x01(\tH\x00\x12\x12\n\x08tag_name\x18\x04 \x01(\tH\x00\x12\x14\n\ncommit_sha\x18\x05 \x01(\tH\x00\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x11\n\trepo_name\x18\x02 \x01(\t\x12\x0b\n\x03dir\x18\x06 \x01(\t\x12\x14\n\x0cinvert_regex\x18\x07 \x01(\x08B\n\n\x08revision"\xa7\x01\n\x06Source\x12B\n\x0estorage_source\x18\x01 \x01(\x0b2(.google.cloud.functions.v2.StorageSourceH\x00\x12<\n\x0brepo_source\x18\x02 \x01(\x0b2%.google.cloud.functions.v2.RepoSourceH\x00\x12\x11\n\x07git_uri\x18\x03 \x01(\tH\x00B\x08\n\x06source"\xb3\x01\n\x10SourceProvenance\x12I\n\x17resolved_storage_source\x18\x01 \x01(\x0b2(.google.cloud.functions.v2.StorageSource\x12C\n\x14resolved_repo_source\x18\x02 \x01(\x0b2%.google.cloud.functions.v2.RepoSource\x12\x0f\n\x07git_uri\x18\x03 \x01(\t"\xa6\x07\n\x0bBuildConfig\x12S\n\x17automatic_update_policy\x18( \x01(\x0b20.google.cloud.functions.v2.AutomaticUpdatePolicyH\x00\x12R\n\x17on_deploy_update_policy\x18) \x01(\x0b2/.google.cloud.functions.v2.OnDeployUpdatePolicyH\x00\x126\n\x05build\x18\x01 \x01(\tB\'\xe0A\x03\xfaA!\n\x1fcloudbuild.googleapis.com/Build\x12\x0f\n\x07runtime\x18\x02 \x01(\t\x12\x13\n\x0bentry_point\x18\x03 \x01(\t\x121\n\x06source\x18\x04 \x01(\x0b2!.google.cloud.functions.v2.Source\x12K\n\x11source_provenance\x18\x08 \x01(\x0b2+.google.cloud.functions.v2.SourceProvenanceB\x03\xe0A\x03\x12>\n\x0bworker_pool\x18\x05 \x01(\tB)\xfaA&\n$cloudbuild.googleapis.com/WorkerPool\x12_\n\x15environment_variables\x18\x06 \x03(\x0b2@.google.cloud.functions.v2.BuildConfig.EnvironmentVariablesEntry\x12R\n\x0fdocker_registry\x18\n \x01(\x0e25.google.cloud.functions.v2.BuildConfig.DockerRegistryB\x02\x18\x01\x12J\n\x11docker_repository\x18\x07 \x01(\tB/\xfaA,\n*artifactregistry.googleapis.com/Repository\x12\x17\n\x0fservice_account\x18\x1b \x01(\t\x1a;\n\x19EnvironmentVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"`\n\x0eDockerRegistry\x12\x1f\n\x1bDOCKER_REGISTRY_UNSPECIFIED\x10\x00\x12\x16\n\x12CONTAINER_REGISTRY\x10\x01\x12\x15\n\x11ARTIFACT_REGISTRY\x10\x02B\x17\n\x15runtime_update_policy"\xd4\n\n\rServiceConfig\x123\n\x07service\x18\x01 \x01(\tB"\xe0A\x03\xfaA\x1c\n\x1arun.googleapis.com/Service\x12\x17\n\x0ftimeout_seconds\x18\x02 \x01(\x05\x12\x18\n\x10available_memory\x18\r \x01(\t\x12\x15\n\ravailable_cpu\x18\x16 \x01(\t\x12a\n\x15environment_variables\x18\x04 \x03(\x0b2B.google.cloud.functions.v2.ServiceConfig.EnvironmentVariablesEntry\x12\x1a\n\x12max_instance_count\x18\x05 \x01(\x05\x12\x1a\n\x12min_instance_count\x18\x0c \x01(\x05\x12>\n\rvpc_connector\x18\x06 \x01(\tB\'\xfaA$\n"vpcaccess.googleapis.com/Connector\x12j\n\x1dvpc_connector_egress_settings\x18\x07 \x01(\x0e2C.google.cloud.functions.v2.ServiceConfig.VpcConnectorEgressSettings\x12R\n\x10ingress_settings\x18\x08 \x01(\x0e28.google.cloud.functions.v2.ServiceConfig.IngressSettings\x12\x10\n\x03uri\x18\t \x01(\tB\x03\xe0A\x03\x12\x1d\n\x15service_account_email\x18\n \x01(\t\x12&\n\x1eall_traffic_on_latest_revision\x18\x10 \x01(\x08\x12M\n\x1csecret_environment_variables\x18\x11 \x03(\x0b2\'.google.cloud.functions.v2.SecretEnvVar\x12?\n\x0esecret_volumes\x18\x13 \x03(\x0b2\'.google.cloud.functions.v2.SecretVolume\x12\x15\n\x08revision\x18\x12 \x01(\tB\x03\xe0A\x03\x12(\n max_instance_request_concurrency\x18\x14 \x01(\x05\x12N\n\x0esecurity_level\x18\x15 \x01(\x0e26.google.cloud.functions.v2.ServiceConfig.SecurityLevel\x12(\n\x1bbinary_authorization_policy\x18\x17 \x01(\tB\x03\xe0A\x01\x1a;\n\x19EnvironmentVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"u\n\x1aVpcConnectorEgressSettings\x12-\n)VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED\x10\x00\x12\x17\n\x13PRIVATE_RANGES_ONLY\x10\x01\x12\x0f\n\x0bALL_TRAFFIC\x10\x02"x\n\x0fIngressSettings\x12 \n\x1cINGRESS_SETTINGS_UNSPECIFIED\x10\x00\x12\r\n\tALLOW_ALL\x10\x01\x12\x17\n\x13ALLOW_INTERNAL_ONLY\x10\x02\x12\x1b\n\x17ALLOW_INTERNAL_AND_GCLB\x10\x03"W\n\rSecurityLevel\x12\x1e\n\x1aSECURITY_LEVEL_UNSPECIFIED\x10\x00\x12\x11\n\rSECURE_ALWAYS\x10\x01\x12\x13\n\x0fSECURE_OPTIONAL\x10\x02"P\n\x0cSecretEnvVar\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0e\n\x06secret\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t"\xbf\x01\n\x0cSecretVolume\x12\x12\n\nmount_path\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0e\n\x06secret\x18\x03 \x01(\t\x12G\n\x08versions\x18\x04 \x03(\x0b25.google.cloud.functions.v2.SecretVolume.SecretVersion\x1a.\n\rSecretVersion\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t"\x9b\x04\n\x0cEventTrigger\x128\n\x07trigger\x18\x01 \x01(\tB\'\xe0A\x03\xfaA!\n\x1feventarc.googleapis.com/Trigger\x12\x16\n\x0etrigger_region\x18\x02 \x01(\t\x12\x17\n\nevent_type\x18\x03 \x01(\tB\x03\xe0A\x02\x12=\n\revent_filters\x18\x04 \x03(\x0b2&.google.cloud.functions.v2.EventFilter\x129\n\x0cpubsub_topic\x18\x05 \x01(\tB#\xe0A\x01\xfaA\x1d\n\x1bpubsub.googleapis.com/Topic\x12"\n\x15service_account_email\x18\x06 \x01(\tB\x03\xe0A\x01\x12N\n\x0cretry_policy\x18\x07 \x01(\x0e23.google.cloud.functions.v2.EventTrigger.RetryPolicyB\x03\xe0A\x01\x128\n\x07channel\x18\x08 \x01(\tB\'\xe0A\x01\xfaA!\n\x1feventarc.googleapis.com/Channel\x12\x14\n\x07service\x18\t \x01(\tB\x03\xe0A\x01"b\n\x0bRetryPolicy\x12\x1c\n\x18RETRY_POLICY_UNSPECIFIED\x10\x00\x12\x1d\n\x19RETRY_POLICY_DO_NOT_RETRY\x10\x01\x12\x16\n\x12RETRY_POLICY_RETRY\x10\x02"P\n\x0bEventFilter\x12\x16\n\tattribute\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x12\n\x05value\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x15\n\x08operator\x18\x03 \x01(\tB\x03\xe0A\x01"i\n\x12GetFunctionRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&cloudfunctions.googleapis.com/Function\x12\x15\n\x08revision\x18\x02 \x01(\tB\x03\xe0A\x01"\x9f\x01\n\x14ListFunctionsRequest\x12>\n\x06parent\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\x12&cloudfunctions.googleapis.com/Function\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"}\n\x15ListFunctionsResponse\x126\n\tfunctions\x18\x01 \x03(\x0b2#.google.cloud.functions.v2.Function\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xa3\x01\n\x15CreateFunctionRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12:\n\x08function\x18\x02 \x01(\x0b2#.google.cloud.functions.v2.FunctionB\x03\xe0A\x02\x12\x13\n\x0bfunction_id\x18\x03 \x01(\t"\x84\x01\n\x15UpdateFunctionRequest\x12:\n\x08function\x18\x01 \x01(\x0b2#.google.cloud.functions.v2.FunctionB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"U\n\x15DeleteFunctionRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&cloudfunctions.googleapis.com/Function"\xd0\x01\n\x18GenerateUploadUrlRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12<\n\x0ckms_key_name\x18\x02 \x01(\tB&\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12;\n\x0benvironment\x18\x03 \x01(\x0e2&.google.cloud.functions.v2.Environment"q\n\x19GenerateUploadUrlResponse\x12\x12\n\nupload_url\x18\x01 \x01(\t\x12@\n\x0estorage_source\x18\x02 \x01(\x0b2(.google.cloud.functions.v2.StorageSource"Z\n\x1aGenerateDownloadUrlRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&cloudfunctions.googleapis.com/Function"3\n\x1bGenerateDownloadUrlResponse\x12\x14\n\x0cdownload_url\x18\x01 \x01(\t"`\n\x13ListRuntimesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x0e\n\x06filter\x18\x02 \x01(\t"\x89\x04\n\x14ListRuntimesResponse\x12I\n\x08runtimes\x18\x01 \x03(\x0b27.google.cloud.functions.v2.ListRuntimesResponse.Runtime\x1a\xa4\x02\n\x07Runtime\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cdisplay_name\x18\x05 \x01(\t\x12K\n\x05stage\x18\x02 \x01(\x0e2<.google.cloud.functions.v2.ListRuntimesResponse.RuntimeStage\x12\x10\n\x08warnings\x18\x03 \x03(\t\x12;\n\x0benvironment\x18\x04 \x01(\x0e2&.google.cloud.functions.v2.Environment\x12+\n\x10deprecation_date\x18\x06 \x01(\x0b2\x11.google.type.Date\x12,\n\x11decommission_date\x18\x07 \x01(\x0b2\x11.google.type.Date"\x7f\n\x0cRuntimeStage\x12\x1d\n\x19RUNTIME_STAGE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bDEVELOPMENT\x10\x01\x12\t\n\x05ALPHA\x10\x02\x12\x08\n\x04BETA\x10\x03\x12\x06\n\x02GA\x10\x04\x12\x0e\n\nDEPRECATED\x10\x05\x12\x12\n\x0eDECOMMISSIONED\x10\x06"\x17\n\x15AutomaticUpdatePolicy"4\n\x14OnDeployUpdatePolicy\x12\x1c\n\x0fruntime_version\x18\x01 \x01(\tB\x03\xe0A\x03"\xa4\x03\n\x11OperationMetadata\x12/\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0c\n\x04verb\x18\x04 \x01(\t\x12\x15\n\rstatus_detail\x18\x05 \x01(\t\x12\x18\n\x10cancel_requested\x18\x06 \x01(\x08\x12\x13\n\x0bapi_version\x18\x07 \x01(\t\x12.\n\x10request_resource\x18\x08 \x01(\x0b2\x14.google.protobuf.Any\x120\n\x06stages\x18\t \x03(\x0b2 .google.cloud.functions.v2.Stage\x12\x14\n\x0csource_token\x18\n \x01(\t\x12\x12\n\nbuild_name\x18\r \x01(\t\x12@\n\x0eoperation_type\x18\x0b \x01(\x0e2(.google.cloud.functions.v2.OperationType"P\n\x10LocationMetadata\x12<\n\x0cenvironments\x18\x01 \x03(\x0e2&.google.cloud.functions.v2.Environment"\xc4\x03\n\x05Stage\x123\n\x04name\x18\x01 \x01(\x0e2%.google.cloud.functions.v2.Stage.Name\x12\x0f\n\x07message\x18\x02 \x01(\t\x125\n\x05state\x18\x03 \x01(\x0e2&.google.cloud.functions.v2.Stage.State\x12\x10\n\x08resource\x18\x04 \x01(\t\x12\x14\n\x0cresource_uri\x18\x05 \x01(\t\x12?\n\x0estate_messages\x18\x06 \x03(\x0b2\'.google.cloud.functions.v2.StateMessage"\x84\x01\n\x04Name\x12\x14\n\x10NAME_UNSPECIFIED\x10\x00\x12\x15\n\x11ARTIFACT_REGISTRY\x10\x01\x12\t\n\x05BUILD\x10\x02\x12\x0b\n\x07SERVICE\x10\x03\x12\x0b\n\x07TRIGGER\x10\x04\x12\x14\n\x10SERVICE_ROLLBACK\x10\x05\x12\x14\n\x10TRIGGER_ROLLBACK\x10\x06"N\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bNOT_STARTED\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x12\x0c\n\x08COMPLETE\x10\x03*m\n\rOperationType\x12\x1d\n\x19OPERATIONTYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fCREATE_FUNCTION\x10\x01\x12\x13\n\x0fUPDATE_FUNCTION\x10\x02\x12\x13\n\x0fDELETE_FUNCTION\x10\x03*@\n\x0bEnvironment\x12\x1b\n\x17ENVIRONMENT_UNSPECIFIED\x10\x00\x12\t\n\x05GEN_1\x10\x01\x12\t\n\x05GEN_2\x10\x022\xaa\x0e\n\x0fFunctionService\x12\x9f\x01\n\x0bGetFunction\x12-.google.cloud.functions.v2.GetFunctionRequest\x1a#.google.cloud.functions.v2.Function"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v2/{name=projects/*/locations/*/functions/*}\x12\xb2\x01\n\rListFunctions\x12/.google.cloud.functions.v2.ListFunctionsRequest\x1a0.google.cloud.functions.v2.ListFunctionsResponse">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v2/{parent=projects/*/locations/*}/functions\x12\x95\x02\n\x0eCreateFunction\x120.google.cloud.functions.v2.CreateFunctionRequest\x1a\x1d.google.longrunning.Operation"\xb1\x01\xcaAQ\n"google.cloud.functions.v2.Function\x12+google.cloud.functions.v2.OperationMetadata\xdaA\x1bparent,function,function_id\x82\xd3\xe4\x93\x029"-/v2/{parent=projects/*/locations/*}/functions:\x08function\x12\x97\x02\n\x0eUpdateFunction\x120.google.cloud.functions.v2.UpdateFunctionRequest\x1a\x1d.google.longrunning.Operation"\xb3\x01\xcaAQ\n"google.cloud.functions.v2.Function\x12+google.cloud.functions.v2.OperationMetadata\xdaA\x14function,update_mask\x82\xd3\xe4\x93\x02B26/v2/{function.name=projects/*/locations/*/functions/*}:\x08function\x12\xe7\x01\n\x0eDeleteFunction\x120.google.cloud.functions.v2.DeleteFunctionRequest\x1a\x1d.google.longrunning.Operation"\x83\x01\xcaAD\n\x15google.protobuf.Empty\x12+google.cloud.functions.v2.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v2/{name=projects/*/locations/*/functions/*}\x12\xca\x01\n\x11GenerateUploadUrl\x123.google.cloud.functions.v2.GenerateUploadUrlRequest\x1a4.google.cloud.functions.v2.GenerateUploadUrlResponse"J\x82\xd3\xe4\x93\x02D"?/v2/{parent=projects/*/locations/*}/functions:generateUploadUrl:\x01*\x12\xd2\x01\n\x13GenerateDownloadUrl\x125.google.cloud.functions.v2.GenerateDownloadUrlRequest\x1a6.google.cloud.functions.v2.GenerateDownloadUrlResponse"L\x82\xd3\xe4\x93\x02F"A/v2/{name=projects/*/locations/*/functions/*}:generateDownloadUrl:\x01*\x12\xae\x01\n\x0cListRuntimes\x12..google.cloud.functions.v2.ListRuntimesRequest\x1a/.google.cloud.functions.v2.ListRuntimesResponse"=\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v2/{parent=projects/*/locations/*}/runtimes\x1aQ\xcaA\x1dcloudfunctions.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xee\x07\n\x1dcom.google.cloud.functions.v2B\x0eFunctionsProtoP\x01Z;cloud.google.com/go/functions/apiv2/functionspb;functionspb\xa2\x02\x03GCF\xeaAo\n*artifactregistry.googleapis.com/Repository\x12Aprojects/{project}/locations/{location}/repositories/{repository}\xeaAY\n\x1fcloudbuild.googleapis.com/Build\x126projects/{project}/locations/{location}/builds/{build}\xeaAi\n$cloudbuild.googleapis.com/WorkerPool\x12Aprojects/{project}/locations/{location}/workerPools/{worker_pool}\xeaAX\n\x1arun.googleapis.com/Service\x12:projects/{project}/locations/{location}/services/{service}\xeaAd\n"vpcaccess.googleapis.com/Connector\x12>projects/{project}/locations/{location}/connectors/{connector}\xeaA]\n\x1feventarc.googleapis.com/Trigger\x12:projects/{project}/locations/{location}/triggers/{trigger}\xeaA]\n\x1feventarc.googleapis.com/Channel\x12:projects/{project}/locations/{location}/channels/{channel}\xeaA@\n\x1bpubsub.googleapis.com/Topic\x12!projects/{project}/topics/{topic}\xeaAx\n!cloudkms.googleapis.com/CryptoKey\x12Sprojects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.functions.v2.functions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1dcom.google.cloud.functions.v2B\x0eFunctionsProtoP\x01Z;cloud.google.com/go/functions/apiv2/functionspb;functionspb\xa2\x02\x03GCF\xeaAo\n*artifactregistry.googleapis.com/Repository\x12Aprojects/{project}/locations/{location}/repositories/{repository}\xeaAY\n\x1fcloudbuild.googleapis.com/Build\x126projects/{project}/locations/{location}/builds/{build}\xeaAi\n$cloudbuild.googleapis.com/WorkerPool\x12Aprojects/{project}/locations/{location}/workerPools/{worker_pool}\xeaAX\n\x1arun.googleapis.com/Service\x12:projects/{project}/locations/{location}/services/{service}\xeaAd\n"vpcaccess.googleapis.com/Connector\x12>projects/{project}/locations/{location}/connectors/{connector}\xeaA]\n\x1feventarc.googleapis.com/Trigger\x12:projects/{project}/locations/{location}/triggers/{trigger}\xeaA]\n\x1feventarc.googleapis.com/Channel\x12:projects/{project}/locations/{location}/channels/{channel}\xeaA@\n\x1bpubsub.googleapis.com/Topic\x12!projects/{project}/topics/{topic}\xeaAx\n!cloudkms.googleapis.com/CryptoKey\x12Sprojects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}'
    _globals['_FUNCTION_LABELSENTRY']._loaded_options = None
    _globals['_FUNCTION_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_FUNCTION'].fields_by_name['state']._loaded_options = None
    _globals['_FUNCTION'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_FUNCTION'].fields_by_name['update_time']._loaded_options = None
    _globals['_FUNCTION'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_FUNCTION'].fields_by_name['state_messages']._loaded_options = None
    _globals['_FUNCTION'].fields_by_name['state_messages']._serialized_options = b'\xe0A\x03'
    _globals['_FUNCTION'].fields_by_name['url']._loaded_options = None
    _globals['_FUNCTION'].fields_by_name['url']._serialized_options = b'\xe0A\x03'
    _globals['_FUNCTION'].fields_by_name['kms_key_name']._loaded_options = None
    _globals['_FUNCTION'].fields_by_name['kms_key_name']._serialized_options = b'\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_FUNCTION'].fields_by_name['satisfies_pzs']._loaded_options = None
    _globals['_FUNCTION'].fields_by_name['satisfies_pzs']._serialized_options = b'\xe0A\x03'
    _globals['_FUNCTION'].fields_by_name['create_time']._loaded_options = None
    _globals['_FUNCTION'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_FUNCTION']._loaded_options = None
    _globals['_FUNCTION']._serialized_options = b'\xeaA{\n&cloudfunctions.googleapis.com/Function\x12<projects/{project}/locations/{location}/functions/{function}*\tfunctions2\x08function'
    _globals['_BUILDCONFIG_ENVIRONMENTVARIABLESENTRY']._loaded_options = None
    _globals['_BUILDCONFIG_ENVIRONMENTVARIABLESENTRY']._serialized_options = b'8\x01'
    _globals['_BUILDCONFIG'].fields_by_name['build']._loaded_options = None
    _globals['_BUILDCONFIG'].fields_by_name['build']._serialized_options = b'\xe0A\x03\xfaA!\n\x1fcloudbuild.googleapis.com/Build'
    _globals['_BUILDCONFIG'].fields_by_name['source_provenance']._loaded_options = None
    _globals['_BUILDCONFIG'].fields_by_name['source_provenance']._serialized_options = b'\xe0A\x03'
    _globals['_BUILDCONFIG'].fields_by_name['worker_pool']._loaded_options = None
    _globals['_BUILDCONFIG'].fields_by_name['worker_pool']._serialized_options = b'\xfaA&\n$cloudbuild.googleapis.com/WorkerPool'
    _globals['_BUILDCONFIG'].fields_by_name['docker_registry']._loaded_options = None
    _globals['_BUILDCONFIG'].fields_by_name['docker_registry']._serialized_options = b'\x18\x01'
    _globals['_BUILDCONFIG'].fields_by_name['docker_repository']._loaded_options = None
    _globals['_BUILDCONFIG'].fields_by_name['docker_repository']._serialized_options = b'\xfaA,\n*artifactregistry.googleapis.com/Repository'
    _globals['_SERVICECONFIG_ENVIRONMENTVARIABLESENTRY']._loaded_options = None
    _globals['_SERVICECONFIG_ENVIRONMENTVARIABLESENTRY']._serialized_options = b'8\x01'
    _globals['_SERVICECONFIG'].fields_by_name['service']._loaded_options = None
    _globals['_SERVICECONFIG'].fields_by_name['service']._serialized_options = b'\xe0A\x03\xfaA\x1c\n\x1arun.googleapis.com/Service'
    _globals['_SERVICECONFIG'].fields_by_name['vpc_connector']._loaded_options = None
    _globals['_SERVICECONFIG'].fields_by_name['vpc_connector']._serialized_options = b'\xfaA$\n"vpcaccess.googleapis.com/Connector'
    _globals['_SERVICECONFIG'].fields_by_name['uri']._loaded_options = None
    _globals['_SERVICECONFIG'].fields_by_name['uri']._serialized_options = b'\xe0A\x03'
    _globals['_SERVICECONFIG'].fields_by_name['revision']._loaded_options = None
    _globals['_SERVICECONFIG'].fields_by_name['revision']._serialized_options = b'\xe0A\x03'
    _globals['_SERVICECONFIG'].fields_by_name['binary_authorization_policy']._loaded_options = None
    _globals['_SERVICECONFIG'].fields_by_name['binary_authorization_policy']._serialized_options = b'\xe0A\x01'
    _globals['_EVENTTRIGGER'].fields_by_name['trigger']._loaded_options = None
    _globals['_EVENTTRIGGER'].fields_by_name['trigger']._serialized_options = b'\xe0A\x03\xfaA!\n\x1feventarc.googleapis.com/Trigger'
    _globals['_EVENTTRIGGER'].fields_by_name['event_type']._loaded_options = None
    _globals['_EVENTTRIGGER'].fields_by_name['event_type']._serialized_options = b'\xe0A\x02'
    _globals['_EVENTTRIGGER'].fields_by_name['pubsub_topic']._loaded_options = None
    _globals['_EVENTTRIGGER'].fields_by_name['pubsub_topic']._serialized_options = b'\xe0A\x01\xfaA\x1d\n\x1bpubsub.googleapis.com/Topic'
    _globals['_EVENTTRIGGER'].fields_by_name['service_account_email']._loaded_options = None
    _globals['_EVENTTRIGGER'].fields_by_name['service_account_email']._serialized_options = b'\xe0A\x01'
    _globals['_EVENTTRIGGER'].fields_by_name['retry_policy']._loaded_options = None
    _globals['_EVENTTRIGGER'].fields_by_name['retry_policy']._serialized_options = b'\xe0A\x01'
    _globals['_EVENTTRIGGER'].fields_by_name['channel']._loaded_options = None
    _globals['_EVENTTRIGGER'].fields_by_name['channel']._serialized_options = b'\xe0A\x01\xfaA!\n\x1feventarc.googleapis.com/Channel'
    _globals['_EVENTTRIGGER'].fields_by_name['service']._loaded_options = None
    _globals['_EVENTTRIGGER'].fields_by_name['service']._serialized_options = b'\xe0A\x01'
    _globals['_EVENTFILTER'].fields_by_name['attribute']._loaded_options = None
    _globals['_EVENTFILTER'].fields_by_name['attribute']._serialized_options = b'\xe0A\x02'
    _globals['_EVENTFILTER'].fields_by_name['value']._loaded_options = None
    _globals['_EVENTFILTER'].fields_by_name['value']._serialized_options = b'\xe0A\x02'
    _globals['_EVENTFILTER'].fields_by_name['operator']._loaded_options = None
    _globals['_EVENTFILTER'].fields_by_name['operator']._serialized_options = b'\xe0A\x01'
    _globals['_GETFUNCTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETFUNCTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&cloudfunctions.googleapis.com/Function'
    _globals['_GETFUNCTIONREQUEST'].fields_by_name['revision']._loaded_options = None
    _globals['_GETFUNCTIONREQUEST'].fields_by_name['revision']._serialized_options = b'\xe0A\x01'
    _globals['_LISTFUNCTIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTFUNCTIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\x12&cloudfunctions.googleapis.com/Function'
    _globals['_CREATEFUNCTIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEFUNCTIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEFUNCTIONREQUEST'].fields_by_name['function']._loaded_options = None
    _globals['_CREATEFUNCTIONREQUEST'].fields_by_name['function']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEFUNCTIONREQUEST'].fields_by_name['function']._loaded_options = None
    _globals['_UPDATEFUNCTIONREQUEST'].fields_by_name['function']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEFUNCTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEFUNCTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&cloudfunctions.googleapis.com/Function'
    _globals['_GENERATEUPLOADURLREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_GENERATEUPLOADURLREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_GENERATEUPLOADURLREQUEST'].fields_by_name['kms_key_name']._loaded_options = None
    _globals['_GENERATEUPLOADURLREQUEST'].fields_by_name['kms_key_name']._serialized_options = b'\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_GENERATEDOWNLOADURLREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GENERATEDOWNLOADURLREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&cloudfunctions.googleapis.com/Function'
    _globals['_LISTRUNTIMESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTRUNTIMESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_ONDEPLOYUPDATEPOLICY'].fields_by_name['runtime_version']._loaded_options = None
    _globals['_ONDEPLOYUPDATEPOLICY'].fields_by_name['runtime_version']._serialized_options = b'\xe0A\x03'
    _globals['_FUNCTIONSERVICE']._loaded_options = None
    _globals['_FUNCTIONSERVICE']._serialized_options = b'\xcaA\x1dcloudfunctions.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_FUNCTIONSERVICE'].methods_by_name['GetFunction']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['GetFunction']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v2/{name=projects/*/locations/*/functions/*}'
    _globals['_FUNCTIONSERVICE'].methods_by_name['ListFunctions']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['ListFunctions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v2/{parent=projects/*/locations/*}/functions'
    _globals['_FUNCTIONSERVICE'].methods_by_name['CreateFunction']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['CreateFunction']._serialized_options = b'\xcaAQ\n"google.cloud.functions.v2.Function\x12+google.cloud.functions.v2.OperationMetadata\xdaA\x1bparent,function,function_id\x82\xd3\xe4\x93\x029"-/v2/{parent=projects/*/locations/*}/functions:\x08function'
    _globals['_FUNCTIONSERVICE'].methods_by_name['UpdateFunction']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['UpdateFunction']._serialized_options = b'\xcaAQ\n"google.cloud.functions.v2.Function\x12+google.cloud.functions.v2.OperationMetadata\xdaA\x14function,update_mask\x82\xd3\xe4\x93\x02B26/v2/{function.name=projects/*/locations/*/functions/*}:\x08function'
    _globals['_FUNCTIONSERVICE'].methods_by_name['DeleteFunction']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['DeleteFunction']._serialized_options = b'\xcaAD\n\x15google.protobuf.Empty\x12+google.cloud.functions.v2.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v2/{name=projects/*/locations/*/functions/*}'
    _globals['_FUNCTIONSERVICE'].methods_by_name['GenerateUploadUrl']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['GenerateUploadUrl']._serialized_options = b'\x82\xd3\xe4\x93\x02D"?/v2/{parent=projects/*/locations/*}/functions:generateUploadUrl:\x01*'
    _globals['_FUNCTIONSERVICE'].methods_by_name['GenerateDownloadUrl']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['GenerateDownloadUrl']._serialized_options = b'\x82\xd3\xe4\x93\x02F"A/v2/{name=projects/*/locations/*/functions/*}:generateDownloadUrl:\x01*'
    _globals['_FUNCTIONSERVICE'].methods_by_name['ListRuntimes']._loaded_options = None
    _globals['_FUNCTIONSERVICE'].methods_by_name['ListRuntimes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v2/{parent=projects/*/locations/*}/runtimes'
    _globals['_OPERATIONTYPE']._serialized_start = 8281
    _globals['_OPERATIONTYPE']._serialized_end = 8390
    _globals['_ENVIRONMENT']._serialized_start = 8392
    _globals['_ENVIRONMENT']._serialized_end = 8456
    _globals['_FUNCTION']._serialized_start = 372
    _globals['_FUNCTION']._serialized_end = 1357
    _globals['_FUNCTION_LABELSENTRY']._serialized_start = 1086
    _globals['_FUNCTION_LABELSENTRY']._serialized_end = 1131
    _globals['_FUNCTION_STATE']._serialized_start = 1133
    _globals['_FUNCTION_STATE']._serialized_end = 1229
    _globals['_STATEMESSAGE']._serialized_start = 1360
    _globals['_STATEMESSAGE']._serialized_end = 1545
    _globals['_STATEMESSAGE_SEVERITY']._serialized_start = 1475
    _globals['_STATEMESSAGE_SEVERITY']._serialized_end = 1545
    _globals['_STORAGESOURCE']._serialized_start = 1547
    _globals['_STORAGESOURCE']._serialized_end = 1641
    _globals['_REPOSOURCE']._serialized_start = 1644
    _globals['_REPOSOURCE']._serialized_end = 1807
    _globals['_SOURCE']._serialized_start = 1810
    _globals['_SOURCE']._serialized_end = 1977
    _globals['_SOURCEPROVENANCE']._serialized_start = 1980
    _globals['_SOURCEPROVENANCE']._serialized_end = 2159
    _globals['_BUILDCONFIG']._serialized_start = 2162
    _globals['_BUILDCONFIG']._serialized_end = 3096
    _globals['_BUILDCONFIG_ENVIRONMENTVARIABLESENTRY']._serialized_start = 2914
    _globals['_BUILDCONFIG_ENVIRONMENTVARIABLESENTRY']._serialized_end = 2973
    _globals['_BUILDCONFIG_DOCKERREGISTRY']._serialized_start = 2975
    _globals['_BUILDCONFIG_DOCKERREGISTRY']._serialized_end = 3071
    _globals['_SERVICECONFIG']._serialized_start = 3099
    _globals['_SERVICECONFIG']._serialized_end = 4463
    _globals['_SERVICECONFIG_ENVIRONMENTVARIABLESENTRY']._serialized_start = 2914
    _globals['_SERVICECONFIG_ENVIRONMENTVARIABLESENTRY']._serialized_end = 2973
    _globals['_SERVICECONFIG_VPCCONNECTOREGRESSSETTINGS']._serialized_start = 4135
    _globals['_SERVICECONFIG_VPCCONNECTOREGRESSSETTINGS']._serialized_end = 4252
    _globals['_SERVICECONFIG_INGRESSSETTINGS']._serialized_start = 4254
    _globals['_SERVICECONFIG_INGRESSSETTINGS']._serialized_end = 4374
    _globals['_SERVICECONFIG_SECURITYLEVEL']._serialized_start = 4376
    _globals['_SERVICECONFIG_SECURITYLEVEL']._serialized_end = 4463
    _globals['_SECRETENVVAR']._serialized_start = 4465
    _globals['_SECRETENVVAR']._serialized_end = 4545
    _globals['_SECRETVOLUME']._serialized_start = 4548
    _globals['_SECRETVOLUME']._serialized_end = 4739
    _globals['_SECRETVOLUME_SECRETVERSION']._serialized_start = 4693
    _globals['_SECRETVOLUME_SECRETVERSION']._serialized_end = 4739
    _globals['_EVENTTRIGGER']._serialized_start = 4742
    _globals['_EVENTTRIGGER']._serialized_end = 5281
    _globals['_EVENTTRIGGER_RETRYPOLICY']._serialized_start = 5183
    _globals['_EVENTTRIGGER_RETRYPOLICY']._serialized_end = 5281
    _globals['_EVENTFILTER']._serialized_start = 5283
    _globals['_EVENTFILTER']._serialized_end = 5363
    _globals['_GETFUNCTIONREQUEST']._serialized_start = 5365
    _globals['_GETFUNCTIONREQUEST']._serialized_end = 5470
    _globals['_LISTFUNCTIONSREQUEST']._serialized_start = 5473
    _globals['_LISTFUNCTIONSREQUEST']._serialized_end = 5632
    _globals['_LISTFUNCTIONSRESPONSE']._serialized_start = 5634
    _globals['_LISTFUNCTIONSRESPONSE']._serialized_end = 5759
    _globals['_CREATEFUNCTIONREQUEST']._serialized_start = 5762
    _globals['_CREATEFUNCTIONREQUEST']._serialized_end = 5925
    _globals['_UPDATEFUNCTIONREQUEST']._serialized_start = 5928
    _globals['_UPDATEFUNCTIONREQUEST']._serialized_end = 6060
    _globals['_DELETEFUNCTIONREQUEST']._serialized_start = 6062
    _globals['_DELETEFUNCTIONREQUEST']._serialized_end = 6147
    _globals['_GENERATEUPLOADURLREQUEST']._serialized_start = 6150
    _globals['_GENERATEUPLOADURLREQUEST']._serialized_end = 6358
    _globals['_GENERATEUPLOADURLRESPONSE']._serialized_start = 6360
    _globals['_GENERATEUPLOADURLRESPONSE']._serialized_end = 6473
    _globals['_GENERATEDOWNLOADURLREQUEST']._serialized_start = 6475
    _globals['_GENERATEDOWNLOADURLREQUEST']._serialized_end = 6565
    _globals['_GENERATEDOWNLOADURLRESPONSE']._serialized_start = 6567
    _globals['_GENERATEDOWNLOADURLRESPONSE']._serialized_end = 6618
    _globals['_LISTRUNTIMESREQUEST']._serialized_start = 6620
    _globals['_LISTRUNTIMESREQUEST']._serialized_end = 6716
    _globals['_LISTRUNTIMESRESPONSE']._serialized_start = 6719
    _globals['_LISTRUNTIMESRESPONSE']._serialized_end = 7240
    _globals['_LISTRUNTIMESRESPONSE_RUNTIME']._serialized_start = 6819
    _globals['_LISTRUNTIMESRESPONSE_RUNTIME']._serialized_end = 7111
    _globals['_LISTRUNTIMESRESPONSE_RUNTIMESTAGE']._serialized_start = 7113
    _globals['_LISTRUNTIMESRESPONSE_RUNTIMESTAGE']._serialized_end = 7240
    _globals['_AUTOMATICUPDATEPOLICY']._serialized_start = 7242
    _globals['_AUTOMATICUPDATEPOLICY']._serialized_end = 7265
    _globals['_ONDEPLOYUPDATEPOLICY']._serialized_start = 7267
    _globals['_ONDEPLOYUPDATEPOLICY']._serialized_end = 7319
    _globals['_OPERATIONMETADATA']._serialized_start = 7322
    _globals['_OPERATIONMETADATA']._serialized_end = 7742
    _globals['_LOCATIONMETADATA']._serialized_start = 7744
    _globals['_LOCATIONMETADATA']._serialized_end = 7824
    _globals['_STAGE']._serialized_start = 7827
    _globals['_STAGE']._serialized_end = 8279
    _globals['_STAGE_NAME']._serialized_start = 8067
    _globals['_STAGE_NAME']._serialized_end = 8199
    _globals['_STAGE_STATE']._serialized_start = 8201
    _globals['_STAGE_STATE']._serialized_end = 8279
    _globals['_FUNCTIONSERVICE']._serialized_start = 8459
    _globals['_FUNCTIONSERVICE']._serialized_end = 10293