# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/cloud/run/v2/execution_template.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'google/cloud/run/v2/execution_template.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.cloud.run.v2 import task_template_pb2 as google_dot_cloud_dot_run_dot_v2_dot_task__template__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,google/cloud/run/v2/execution_template.proto\x12\x13google.cloud.run.v2\x1a\x1fgoogle/api/field_behavior.proto\x1a\'google/cloud/run/v2/task_template.proto\"\xf0\x02\n\x11\x45xecutionTemplate\x12\x42\n\x06labels\x18\x01 \x03(\x0b\x32\x32.google.cloud.run.v2.ExecutionTemplate.LabelsEntry\x12L\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32\x37.google.cloud.run.v2.ExecutionTemplate.AnnotationsEntry\x12\x18\n\x0bparallelism\x18\x03 \x01(\x05\x42\x03\xe0\x41\x01\x12\x12\n\ntask_count\x18\x04 \x01(\x05\x12\x38\n\x08template\x18\x05 \x01(\x0b\x32!.google.cloud.run.v2.TaskTemplateB\x03\xe0\x41\x02\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42^\n\x17\x63om.google.cloud.run.v2B\x16\x45xecutionTemplateProtoP\x01Z)cloud.google.com/go/run/apiv2/runpb;runpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.run.v2.execution_template_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.google.cloud.run.v2B\026ExecutionTemplateProtoP\001Z)cloud.google.com/go/run/apiv2/runpb;runpb'
  _globals['_EXECUTIONTEMPLATE_LABELSENTRY']._loaded_options = None
  _globals['_EXECUTIONTEMPLATE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTIONTEMPLATE_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_EXECUTIONTEMPLATE_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTIONTEMPLATE'].fields_by_name['parallelism']._loaded_options = None
  _globals['_EXECUTIONTEMPLATE'].fields_by_name['parallelism']._serialized_options = b'\340A\001'
  _globals['_EXECUTIONTEMPLATE'].fields_by_name['template']._loaded_options = None
  _globals['_EXECUTIONTEMPLATE'].fields_by_name['template']._serialized_options = b'\340A\002'
  _globals['_EXECUTIONTEMPLATE']._serialized_start=144
  _globals['_EXECUTIONTEMPLATE']._serialized_end=512
  _globals['_EXECUTIONTEMPLATE_LABELSENTRY']._serialized_start=415
  _globals['_EXECUTIONTEMPLATE_LABELSENTRY']._serialized_end=460
  _globals['_EXECUTIONTEMPLATE_ANNOTATIONSENTRY']._serialized_start=462
  _globals['_EXECUTIONTEMPLATE_ANNOTATIONSENTRY']._serialized_end=512
# @@protoc_insertion_point(module_scope)
