# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 0.1.16

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.domains_v1_domain_domain_extended_resource_domain_contacts import DomainsV1DomainDomainExtendedResourceDomainContacts

class TestDomainsV1DomainDomainExtendedResourceDomainContacts(unittest.TestCase):
    """DomainsV1DomainDomainExtendedResourceDomainContacts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainsV1DomainDomainExtendedResourceDomainContacts:
        """Test DomainsV1DomainDomainExtendedResourceDomainContacts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainsV1DomainDomainExtendedResourceDomainContacts`
        """
        model = DomainsV1DomainDomainExtendedResourceDomainContacts()
        if include_optional:
            return DomainsV1DomainDomainExtendedResourceDomainContacts(
                admin_id = 114698,
                owner_id = 614698,
                billing_id = 154698,
                tech_id = 524248
            )
        else:
            return DomainsV1DomainDomainExtendedResourceDomainContacts(
        )
        """

    def testDomainsV1DomainDomainExtendedResourceDomainContacts(self):
        """Test DomainsV1DomainDomainExtendedResourceDomainContacts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
