# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 0.1.16

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.reach_v1_contacts_contact_resource import ReachV1ContactsContactResource

class TestReachV1ContactsContactResource(unittest.TestCase):
    """ReachV1ContactsContactResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReachV1ContactsContactResource:
        """Test ReachV1ContactsContactResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReachV1ContactsContactResource`
        """
        model = ReachV1ContactsContactResource()
        if include_optional:
            return ReachV1ContactsContactResource(
                uuid = '550e8400-e29b-41d4-a716-446655440000',
                name = 'John',
                surname = 'Doe',
                email = 'john.doe@example.com',
                subscription_status = 'subscribed',
                subscribed_at = '2023-01-01T00:00Z',
                source = 'sync',
                note = 'VIP customer'
            )
        else:
            return ReachV1ContactsContactResource(
        )
        """

    def testReachV1ContactsContactResource(self):
        """Test ReachV1ContactsContactResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
