# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 0.1.16

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.domains_v1_portfolio_purchase_request import DomainsV1PortfolioPurchaseRequest

class TestDomainsV1PortfolioPurchaseRequest(unittest.TestCase):
    """DomainsV1PortfolioPurchaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainsV1PortfolioPurchaseRequest:
        """Test DomainsV1PortfolioPurchaseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainsV1PortfolioPurchaseRequest`
        """
        model = DomainsV1PortfolioPurchaseRequest()
        if include_optional:
            return DomainsV1PortfolioPurchaseRequest(
                domain = 'my-new-domain.tld',
                item_id = 'hostingercom-domain-com-usd-1y',
                payment_method_id = 1327362,
                domain_contacts = hostinger_api.models.domains_v1_portfolio_purchase_request_domain_contacts.Domains_V1_Portfolio_PurchaseRequest_domain_contacts(
                    owner_id = 741288, 
                    admin_id = 546123, 
                    billing_id = 741288, 
                    tech_id = 741288, ),
                additional_details = None,
                coupons = [
                    ["Coupon 3"]
                    ]
            )
        else:
            return DomainsV1PortfolioPurchaseRequest(
                domain = 'my-new-domain.tld',
                item_id = 'hostingercom-domain-com-usd-1y',
        )
        """

    def testDomainsV1PortfolioPurchaseRequest(self):
        """Test DomainsV1PortfolioPurchaseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
