"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/managedkafka/schemaregistry/v1/schema_registry.proto')
_sym_db = _symbol_database.Default()
from ......google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from ......google.api import client_pb2 as google_dot_api_dot_client__pb2
from ......google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from ......google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from ......google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from ......google.cloud.managedkafka.schemaregistry.v1 import schema_registry_resources_pb2 as google_dot_cloud_dot_managedkafka_dot_schemaregistry_dot_v1_dot_schema__registry__resources__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAgoogle/cloud/managedkafka/schemaregistry/v1/schema_registry.proto\x12+google.cloud.managedkafka.schemaregistry.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/httpbody.proto\x1a\x19google/api/resource.proto\x1aKgoogle/cloud/managedkafka/schemaregistry/v1/schema_registry_resources.proto\x1a\x1bgoogle/protobuf/empty.proto"\\\n\x18GetSchemaRegistryRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*managedkafka.googleapis.com/SchemaRegistry"8\n\x1bListSchemaRegistriesRequest\x12\x19\n\x06parent\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*"v\n\x1cListSchemaRegistriesResponse\x12V\n\x11schema_registries\x18\x01 \x03(\x0b2;.google.cloud.managedkafka.schemaregistry.v1.SchemaRegistry"\xb4\x01\n\x1bCreateSchemaRegistryRequest\x12\x19\n\x06parent\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12\x1f\n\x12schema_registry_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12Y\n\x0fschema_registry\x18\x03 \x01(\x0b2;.google.cloud.managedkafka.schemaregistry.v1.SchemaRegistryB\x03\xe0A\x02"_\n\x1bDeleteSchemaRegistryRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*managedkafka.googleapis.com/SchemaRegistry"T\n\x11GetContextRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaContext"Y\n\x13ListContextsRequest\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*managedkafka.googleapis.com/SchemaRegistry"s\n\x10GetSchemaRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"managedkafka.googleapis.com/Schema\x12\x19\n\x07subject\x18\x02 \x01(\tB\x03\xe0A\x01H\x00\x88\x01\x01B\n\n\x08_subject"3\n\x16ListSchemaTypesRequest\x12\x19\n\x06parent\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*"\xa5\x01\n\x19ListSchemaVersionsRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"managedkafka.googleapis.com/Schema\x12\x19\n\x07subject\x18\x02 \x01(\tB\x03\xe0A\x01H\x00\x88\x01\x01\x12\x19\n\x07deleted\x18\x03 \x01(\x08B\x03\xe0A\x01H\x01\x88\x01\x01B\n\n\x08_subjectB\n\n\x08_deleted"\x8c\x01\n\x13ListSubjectsRequest\x12\x19\n\x06parent\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12 \n\x0esubject_prefix\x18\x02 \x01(\tB\x03\xe0A\x01H\x00\x88\x01\x01\x12\x19\n\x07deleted\x18\x03 \x01(\x08B\x03\xe0A\x01H\x01\x88\x01\x01B\x11\n\x0f_subject_prefixB\n\n\x08_deleted"\x88\x01\n\x1dListSubjectsBySchemaIdRequest\x12\x19\n\x06parent\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12\x19\n\x07subject\x18\x02 \x01(\tB\x03\xe0A\x01H\x00\x88\x01\x01\x12\x19\n\x07deleted\x18\x03 \x01(\x08B\x03\xe0A\x01H\x01\x88\x01\x01B\n\n\x08_subjectB\n\n\x08_deleted"\x7f\n\x13ListVersionsRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject\x12\x19\n\x07deleted\x18\x02 \x01(\x08B\x03\xe0A\x01H\x00\x88\x01\x01B\n\n\x08_deleted"\x82\x01\n\x14DeleteSubjectRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject\x12\x1b\n\tpermanent\x18\x02 \x01(\x08B\x03\xe0A\x01H\x00\x88\x01\x01B\x0c\n\n_permanent"{\n\x11GetVersionRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaVersion\x12\x19\n\x07deleted\x18\x02 \x01(\x08B\x03\xe0A\x01H\x00\x88\x01\x01B\n\n\x08_deleted"\xaa\x03\n\x14CreateVersionRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject\x12\x19\n\x07version\x18\x02 \x01(\x05B\x03\xe0A\x01H\x00\x88\x01\x01\x12\x14\n\x02id\x18\x03 \x01(\x05B\x03\xe0A\x01H\x01\x88\x01\x01\x12]\n\x0bschema_type\x18\x04 \x01(\x0e2>.google.cloud.managedkafka.schemaregistry.v1.Schema.SchemaTypeB\x03\xe0A\x01H\x02\x88\x01\x01\x12\x13\n\x06schema\x18\x05 \x01(\tB\x03\xe0A\x02\x12\\\n\nreferences\x18\x06 \x03(\x0b2C.google.cloud.managedkafka.schemaregistry.v1.Schema.SchemaReferenceB\x03\xe0A\x01\x12\x1b\n\tnormalize\x18\x07 \x01(\x08B\x03\xe0A\x01H\x03\x88\x01\x01B\n\n\x08_versionB\x05\n\x03_idB\x0e\n\x0c_schema_typeB\x0c\n\n_normalize"#\n\x15CreateVersionResponse\x12\n\n\x02id\x18\x01 \x01(\x05"\x8d\x03\n\x14LookupVersionRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject\x12]\n\x0bschema_type\x18\x02 \x01(\x0e2>.google.cloud.managedkafka.schemaregistry.v1.Schema.SchemaTypeB\x03\xe0A\x01H\x00\x88\x01\x01\x12\x13\n\x06schema\x18\x03 \x01(\tB\x03\xe0A\x02\x12\\\n\nreferences\x18\x04 \x03(\x0b2C.google.cloud.managedkafka.schemaregistry.v1.Schema.SchemaReferenceB\x03\xe0A\x01\x12\x1b\n\tnormalize\x18\x05 \x01(\x08B\x03\xe0A\x01H\x01\x88\x01\x01\x12\x19\n\x07deleted\x18\x06 \x01(\x08B\x03\xe0A\x01H\x02\x88\x01\x01B\x0e\n\x0c_schema_typeB\x0c\n\n_normalizeB\n\n\x08_deleted"\x82\x01\n\x14DeleteVersionRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaVersion\x12\x1b\n\tpermanent\x18\x02 \x01(\x08B\x03\xe0A\x01H\x00\x88\x01\x01B\x0c\n\n_permanent"a\n\x1cListReferencedSchemasRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaVersion"\xbd\x02\n\x19CheckCompatibilityRequest\x12\x17\n\x04name\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12]\n\x0bschema_type\x18\x02 \x01(\x0e2>.google.cloud.managedkafka.schemaregistry.v1.Schema.SchemaTypeB\x03\xe0A\x01H\x00\x88\x01\x01\x12\x13\n\x06schema\x18\x03 \x01(\tB\x03\xe0A\x02\x12\\\n\nreferences\x18\x04 \x03(\x0b2C.google.cloud.managedkafka.schemaregistry.v1.Schema.SchemaReferenceB\x03\xe0A\x01\x12\x19\n\x07verbose\x18\x05 \x01(\x08B\x03\xe0A\x01H\x01\x88\x01\x01B\x0e\n\x0c_schema_typeB\n\n\x08_verbose"T\n\x1aCheckCompatibilityResponse\x12$\n\ris_compatible\x18\x01 \x01(\x08R\ris_compatible\x12\x10\n\x08messages\x18\x02 \x03(\t"\x93\x01\n\x16GetSchemaConfigRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(managedkafka.googleapis.com/SchemaConfig\x12#\n\x11default_to_global\x18\x02 \x01(\x08B\x03\xe0A\x01H\x00\x88\x01\x01B\x14\n\x12_default_to_global"\x86\x02\n\x19UpdateSchemaConfigRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(managedkafka.googleapis.com/SchemaConfig\x12l\n\rcompatibility\x18\x02 \x01(\x0e2K.google.cloud.managedkafka.schemaregistry.v1.SchemaConfig.CompatibilityTypeB\x03\xe0A\x02H\x00\x88\x01\x01\x12\x1b\n\tnormalize\x18\x03 \x01(\x08B\x03\xe0A\x01H\x01\x88\x01\x01B\x10\n\x0e_compatibilityB\x0c\n\n_normalize"[\n\x19DeleteSchemaConfigRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(managedkafka.googleapis.com/SchemaConfig"T\n\x14GetSchemaModeRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&managedkafka.googleapis.com/SchemaMode"\xac\x01\n\x17UpdateSchemaModeRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&managedkafka.googleapis.com/SchemaMode\x12S\n\x04mode\x18\x02 \x01(\x0e2@.google.cloud.managedkafka.schemaregistry.v1.SchemaMode.ModeTypeB\x03\xe0A\x02"W\n\x17DeleteSchemaModeRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&managedkafka.googleapis.com/SchemaMode2\xf0=\n\x15ManagedSchemaRegistry\x12\xdc\x01\n\x11GetSchemaRegistry\x12E.google.cloud.managedkafka.schemaregistry.v1.GetSchemaRegistryRequest\x1a;.google.cloud.managedkafka.schemaregistry.v1.SchemaRegistry"C\xdaA\x04name\x82\xd3\xe4\x93\x026\x124/v1/{name=projects/*/locations/*/schemaRegistries/*}\x12\xf2\x01\n\x14ListSchemaRegistries\x12H.google.cloud.managedkafka.schemaregistry.v1.ListSchemaRegistriesRequest\x1aI.google.cloud.managedkafka.schemaregistry.v1.ListSchemaRegistriesResponse"E\xdaA\x06parent\x82\xd3\xe4\x93\x026\x124/v1/{parent=projects/*/locations/*}/schemaRegistries\x12\xf7\x01\n\x14CreateSchemaRegistry\x12H.google.cloud.managedkafka.schemaregistry.v1.CreateSchemaRegistryRequest\x1a;.google.cloud.managedkafka.schemaregistry.v1.SchemaRegistry"X\xdaA\x16parent,schema_registry\x82\xd3\xe4\x93\x029"4/v1/{parent=projects/*/locations/*}/schemaRegistries:\x01*\x12\xbd\x01\n\x14DeleteSchemaRegistry\x12H.google.cloud.managedkafka.schemaregistry.v1.DeleteSchemaRegistryRequest\x1a\x16.google.protobuf.Empty"C\xdaA\x04name\x82\xd3\xe4\x93\x026*4/v1/{name=projects/*/locations/*/schemaRegistries/*}\x12\xd2\x01\n\nGetContext\x12>.google.cloud.managedkafka.schemaregistry.v1.GetContextRequest\x1a4.google.cloud.managedkafka.schemaregistry.v1.Context"N\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*}\x12\xb8\x01\n\x0cListContexts\x12@.google.cloud.managedkafka.schemaregistry.v1.ListContextsRequest\x1a\x14.google.api.HttpBody"P\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/locations/*/schemaRegistries/*}/contexts\x12\x9f\x02\n\tGetSchema\x12=.google.cloud.managedkafka.schemaregistry.v1.GetSchemaRequest\x1a3.google.cloud.managedkafka.schemaregistry.v1.Schema"\x9d\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x8f\x01\x12?/v1/{name=projects/*/locations/*/schemaRegistries/*/schemas/**}ZL\x12J/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}\x12\x91\x02\n\x0cGetRawSchema\x12=.google.cloud.managedkafka.schemaregistry.v1.GetSchemaRequest\x1a\x14.google.api.HttpBody"\xab\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x9d\x01\x12F/v1/{name=projects/*/locations/*/schemaRegistries/*/schemas/**}/schemaZS\x12Q/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}/schema\x12\xaa\x02\n\x12ListSchemaVersions\x12F.google.cloud.managedkafka.schemaregistry.v1.ListSchemaVersionsRequest\x1a\x14.google.api.HttpBody"\xb5\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/schemas/**}/versionsZW\x12U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}/versions\x12\x98\x02\n\x0fListSchemaTypes\x12C.google.cloud.managedkafka.schemaregistry.v1.ListSchemaTypesRequest\x1a\x14.google.api.HttpBody"\xa9\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02\x99\x01\x12D/v1/{parent=projects/*/locations/*/schemaRegistries/*}/schemas/typesZQ\x12O/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*}/schemas/types\x12\x9f\x02\n\x0cListSubjects\x12@.google.cloud.managedkafka.schemaregistry.v1.ListSubjectsRequest\x1a\x14.google.api.HttpBody"\xb6\x01\xdaA\x1dparent,subject_prefix,deleted\x82\xd3\xe4\x93\x02\x8f\x01\x12?/v1/{parent=projects/*/locations/*/schemaRegistries/*}/subjectsZL\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*}/subjects\x12\xc2\x02\n\x16ListSubjectsBySchemaId\x12J.google.cloud.managedkafka.schemaregistry.v1.ListSubjectsBySchemaIdRequest\x1a\x14.google.api.HttpBody"\xc5\x01\xdaA\x16parent,subject,deleted\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/schemas/**}/subjectsZW\x12U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}/subjects\x12\x88\x02\n\rDeleteSubject\x12A.google.cloud.managedkafka.schemaregistry.v1.DeleteSubjectRequest\x1a\x14.google.api.HttpBody"\x9d\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x8f\x01*?/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*}ZL*J/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}\x12\xc1\x02\n\rLookupVersion\x12A.google.cloud.managedkafka.schemaregistry.v1.LookupVersionRequest\x1a:.google.cloud.managedkafka.schemaregistry.v1.SchemaVersion"\xb0\x01\xdaA\rparent,schema\x82\xd3\xe4\x93\x02\x99\x01"A/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*}:\x01*ZQ"L/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}:\x01*\x12\xbe\x02\n\nGetVersion\x12>.google.cloud.managedkafka.schemaregistry.v1.GetVersionRequest\x1a:.google.cloud.managedkafka.schemaregistry.v1.SchemaVersion"\xb3\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}ZW\x12U/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}\x12\xaf\x02\n\x13GetRawSchemaVersion\x12>.google.cloud.managedkafka.schemaregistry.v1.GetVersionRequest\x1a\x14.google.api.HttpBody"\xc1\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\xb3\x01\x12Q/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}/schemaZ^\x12\\/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}/schema\x12\x9e\x02\n\x0cListVersions\x12@.google.cloud.managedkafka.schemaregistry.v1.ListVersionsRequest\x1a\x14.google.api.HttpBody"\xb5\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*}/versionsZW\x12U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}/versions\x12\x87\x03\n\rCreateVersion\x12A.google.cloud.managedkafka.schemaregistry.v1.CreateVersionRequest\x1aB.google.cloud.managedkafka.schemaregistry.v1.CreateVersionResponse"\xee\x01\xdaA9parent,version,id,schema_type,schema,references,normalize\x82\xd3\xe4\x93\x02\xab\x01"J/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*}/versions:\x01*ZZ"U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}/versions:\x01*\x12\x9e\x02\n\rDeleteVersion\x12A.google.cloud.managedkafka.schemaregistry.v1.DeleteVersionRequest\x1a\x14.google.api.HttpBody"\xb3\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\xa5\x01*J/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}ZW*U/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}\x12\xce\x02\n\x15ListReferencedSchemas\x12I.google.cloud.managedkafka.schemaregistry.v1.ListReferencedSchemasRequest\x1a\x14.google.api.HttpBody"\xd3\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02\xc3\x01\x12Y/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}/referencedbyZf\x12d/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}/referencedby\x12\xde\x02\n\x12CheckCompatibility\x12F.google.cloud.managedkafka.schemaregistry.v1.CheckCompatibilityRequest\x1aG.google.cloud.managedkafka.schemaregistry.v1.CheckCompatibilityResponse"\xb6\x01\xdaA\x0bname,schema\x82\xd3\xe4\x93\x02\xa1\x01"E/v1/{name=projects/*/locations/*/schemaRegistries/*/compatibility/**}:\x01*ZU"P/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/compatibility/**}:\x01*\x12\xaf\x02\n\x0fGetSchemaConfig\x12C.google.cloud.managedkafka.schemaregistry.v1.GetSchemaConfigRequest\x1a9.google.cloud.managedkafka.schemaregistry.v1.SchemaConfig"\x9b\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x8d\x01\x12>/v1/{name=projects/*/locations/*/schemaRegistries/*/config/**}ZK\x12I/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/config/**}\x12\xc9\x02\n\x12UpdateSchemaConfig\x12F.google.cloud.managedkafka.schemaregistry.v1.UpdateSchemaConfigRequest\x1a9.google.cloud.managedkafka.schemaregistry.v1.SchemaConfig"\xaf\x01\xdaA\x12name,compatibility\x82\xd3\xe4\x93\x02\x93\x01\x1a>/v1/{name=projects/*/locations/*/schemaRegistries/*/config/**}:\x01*ZN\x1aI/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/config/**}:\x01*\x12\xb5\x02\n\x12DeleteSchemaConfig\x12F.google.cloud.managedkafka.schemaregistry.v1.DeleteSchemaConfigRequest\x1a9.google.cloud.managedkafka.schemaregistry.v1.SchemaConfig"\x9b\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x8d\x01*>/v1/{name=projects/*/locations/*/schemaRegistries/*/config/**}ZK*I/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/config/**}\x12\xa5\x02\n\rGetSchemaMode\x12A.google.cloud.managedkafka.schemaregistry.v1.GetSchemaModeRequest\x1a7.google.cloud.managedkafka.schemaregistry.v1.SchemaMode"\x97\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x89\x01\x12</v1/{name=projects/*/locations/*/schemaRegistries/*/mode/**}ZI\x12G/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/mode/**}\x12\xb6\x02\n\x10UpdateSchemaMode\x12D.google.cloud.managedkafka.schemaregistry.v1.UpdateSchemaModeRequest\x1a7.google.cloud.managedkafka.schemaregistry.v1.SchemaMode"\xa2\x01\xdaA\tname,mode\x82\xd3\xe4\x93\x02\x8f\x01\x1a</v1/{name=projects/*/locations/*/schemaRegistries/*/mode/**}:\x01*ZL\x1aG/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/mode/**}:\x01*\x12\xab\x02\n\x10DeleteSchemaMode\x12D.google.cloud.managedkafka.schemaregistry.v1.DeleteSchemaModeRequest\x1a7.google.cloud.managedkafka.schemaregistry.v1.SchemaMode"\x97\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x89\x01*</v1/{name=projects/*/locations/*/schemaRegistries/*/mode/**}ZI*G/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/mode/**}\x1aO\xcaA\x1bmanagedkafka.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xaf\x02\n/com.google.cloud.managedkafka.schemaregistry.v1B\x13SchemaRegistryProtoP\x01ZWcloud.google.com/go/managedkafka/schemaregistry/apiv1/schemaregistrypb;schemaregistrypb\xaa\x02+Google.Cloud.ManagedKafka.SchemaRegistry.V1\xca\x02+Google\\Cloud\\ManagedKafka\\SchemaRegistry\\V1\xea\x02/Google::Cloud::ManagedKafka::SchemaRegistry::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.managedkafka.schemaregistry.v1.schema_registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n/com.google.cloud.managedkafka.schemaregistry.v1B\x13SchemaRegistryProtoP\x01ZWcloud.google.com/go/managedkafka/schemaregistry/apiv1/schemaregistrypb;schemaregistrypb\xaa\x02+Google.Cloud.ManagedKafka.SchemaRegistry.V1\xca\x02+Google\\Cloud\\ManagedKafka\\SchemaRegistry\\V1\xea\x02/Google::Cloud::ManagedKafka::SchemaRegistry::V1'
    _globals['_GETSCHEMAREGISTRYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSCHEMAREGISTRYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*managedkafka.googleapis.com/SchemaRegistry'
    _globals['_LISTSCHEMAREGISTRIESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSCHEMAREGISTRIESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_CREATESCHEMAREGISTRYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESCHEMAREGISTRYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_CREATESCHEMAREGISTRYREQUEST'].fields_by_name['schema_registry_id']._loaded_options = None
    _globals['_CREATESCHEMAREGISTRYREQUEST'].fields_by_name['schema_registry_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESCHEMAREGISTRYREQUEST'].fields_by_name['schema_registry']._loaded_options = None
    _globals['_CREATESCHEMAREGISTRYREQUEST'].fields_by_name['schema_registry']._serialized_options = b'\xe0A\x02'
    _globals['_DELETESCHEMAREGISTRYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESCHEMAREGISTRYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*managedkafka.googleapis.com/SchemaRegistry'
    _globals['_GETCONTEXTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCONTEXTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaContext'
    _globals['_LISTCONTEXTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCONTEXTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\n*managedkafka.googleapis.com/SchemaRegistry'
    _globals['_GETSCHEMAREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSCHEMAREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"managedkafka.googleapis.com/Schema'
    _globals['_GETSCHEMAREQUEST'].fields_by_name['subject']._loaded_options = None
    _globals['_GETSCHEMAREQUEST'].fields_by_name['subject']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSCHEMATYPESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSCHEMATYPESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_LISTSCHEMAVERSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSCHEMAVERSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"managedkafka.googleapis.com/Schema'
    _globals['_LISTSCHEMAVERSIONSREQUEST'].fields_by_name['subject']._loaded_options = None
    _globals['_LISTSCHEMAVERSIONSREQUEST'].fields_by_name['subject']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSCHEMAVERSIONSREQUEST'].fields_by_name['deleted']._loaded_options = None
    _globals['_LISTSCHEMAVERSIONSREQUEST'].fields_by_name['deleted']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSUBJECTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSUBJECTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_LISTSUBJECTSREQUEST'].fields_by_name['subject_prefix']._loaded_options = None
    _globals['_LISTSUBJECTSREQUEST'].fields_by_name['subject_prefix']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSUBJECTSREQUEST'].fields_by_name['deleted']._loaded_options = None
    _globals['_LISTSUBJECTSREQUEST'].fields_by_name['deleted']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST'].fields_by_name['subject']._loaded_options = None
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST'].fields_by_name['subject']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST'].fields_by_name['deleted']._loaded_options = None
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST'].fields_by_name['deleted']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVERSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTVERSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject'
    _globals['_LISTVERSIONSREQUEST'].fields_by_name['deleted']._loaded_options = None
    _globals['_LISTVERSIONSREQUEST'].fields_by_name['deleted']._serialized_options = b'\xe0A\x01'
    _globals['_DELETESUBJECTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESUBJECTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject'
    _globals['_DELETESUBJECTREQUEST'].fields_by_name['permanent']._loaded_options = None
    _globals['_DELETESUBJECTREQUEST'].fields_by_name['permanent']._serialized_options = b'\xe0A\x01'
    _globals['_GETVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaVersion'
    _globals['_GETVERSIONREQUEST'].fields_by_name['deleted']._loaded_options = None
    _globals['_GETVERSIONREQUEST'].fields_by_name['deleted']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject'
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['version']._loaded_options = None
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['version']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['id']._loaded_options = None
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['id']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['schema_type']._loaded_options = None
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['schema_type']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['schema']._loaded_options = None
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['schema']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['references']._loaded_options = None
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['references']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['normalize']._loaded_options = None
    _globals['_CREATEVERSIONREQUEST'].fields_by_name['normalize']._serialized_options = b'\xe0A\x01'
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaSubject'
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['schema_type']._loaded_options = None
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['schema_type']._serialized_options = b'\xe0A\x01'
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['schema']._loaded_options = None
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['schema']._serialized_options = b'\xe0A\x02'
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['references']._loaded_options = None
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['references']._serialized_options = b'\xe0A\x01'
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['normalize']._loaded_options = None
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['normalize']._serialized_options = b'\xe0A\x01'
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['deleted']._loaded_options = None
    _globals['_LOOKUPVERSIONREQUEST'].fields_by_name['deleted']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaVersion'
    _globals['_DELETEVERSIONREQUEST'].fields_by_name['permanent']._loaded_options = None
    _globals['_DELETEVERSIONREQUEST'].fields_by_name['permanent']._serialized_options = b'\xe0A\x01'
    _globals['_LISTREFERENCEDSCHEMASREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTREFERENCEDSCHEMASREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\n)managedkafka.googleapis.com/SchemaVersion'
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['schema_type']._loaded_options = None
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['schema_type']._serialized_options = b'\xe0A\x01'
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['schema']._loaded_options = None
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['schema']._serialized_options = b'\xe0A\x02'
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['references']._loaded_options = None
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['references']._serialized_options = b'\xe0A\x01'
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['verbose']._loaded_options = None
    _globals['_CHECKCOMPATIBILITYREQUEST'].fields_by_name['verbose']._serialized_options = b'\xe0A\x01'
    _globals['_GETSCHEMACONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSCHEMACONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(managedkafka.googleapis.com/SchemaConfig'
    _globals['_GETSCHEMACONFIGREQUEST'].fields_by_name['default_to_global']._loaded_options = None
    _globals['_GETSCHEMACONFIGREQUEST'].fields_by_name['default_to_global']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESCHEMACONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UPDATESCHEMACONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(managedkafka.googleapis.com/SchemaConfig'
    _globals['_UPDATESCHEMACONFIGREQUEST'].fields_by_name['compatibility']._loaded_options = None
    _globals['_UPDATESCHEMACONFIGREQUEST'].fields_by_name['compatibility']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESCHEMACONFIGREQUEST'].fields_by_name['normalize']._loaded_options = None
    _globals['_UPDATESCHEMACONFIGREQUEST'].fields_by_name['normalize']._serialized_options = b'\xe0A\x01'
    _globals['_DELETESCHEMACONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESCHEMACONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(managedkafka.googleapis.com/SchemaConfig'
    _globals['_GETSCHEMAMODEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSCHEMAMODEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&managedkafka.googleapis.com/SchemaMode'
    _globals['_UPDATESCHEMAMODEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UPDATESCHEMAMODEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&managedkafka.googleapis.com/SchemaMode'
    _globals['_UPDATESCHEMAMODEREQUEST'].fields_by_name['mode']._loaded_options = None
    _globals['_UPDATESCHEMAMODEREQUEST'].fields_by_name['mode']._serialized_options = b'\xe0A\x02'
    _globals['_DELETESCHEMAMODEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESCHEMAMODEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&managedkafka.googleapis.com/SchemaMode'
    _globals['_MANAGEDSCHEMAREGISTRY']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY']._serialized_options = b'\xcaA\x1bmanagedkafka.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchemaRegistry']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchemaRegistry']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x026\x124/v1/{name=projects/*/locations/*/schemaRegistries/*}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSchemaRegistries']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSchemaRegistries']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x026\x124/v1/{parent=projects/*/locations/*}/schemaRegistries'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['CreateSchemaRegistry']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['CreateSchemaRegistry']._serialized_options = b'\xdaA\x16parent,schema_registry\x82\xd3\xe4\x93\x029"4/v1/{parent=projects/*/locations/*}/schemaRegistries:\x01*'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSchemaRegistry']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSchemaRegistry']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x026*4/v1/{name=projects/*/locations/*/schemaRegistries/*}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetContext']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetContext']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListContexts']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListContexts']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/locations/*/schemaRegistries/*}/contexts'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchema']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchema']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x8f\x01\x12?/v1/{name=projects/*/locations/*/schemaRegistries/*/schemas/**}ZL\x12J/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetRawSchema']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetRawSchema']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x9d\x01\x12F/v1/{name=projects/*/locations/*/schemaRegistries/*/schemas/**}/schemaZS\x12Q/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}/schema'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSchemaVersions']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSchemaVersions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/schemas/**}/versionsZW\x12U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}/versions'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSchemaTypes']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSchemaTypes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\x99\x01\x12D/v1/{parent=projects/*/locations/*/schemaRegistries/*}/schemas/typesZQ\x12O/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*}/schemas/types'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSubjects']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSubjects']._serialized_options = b'\xdaA\x1dparent,subject_prefix,deleted\x82\xd3\xe4\x93\x02\x8f\x01\x12?/v1/{parent=projects/*/locations/*/schemaRegistries/*}/subjectsZL\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*}/subjects'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSubjectsBySchemaId']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListSubjectsBySchemaId']._serialized_options = b'\xdaA\x16parent,subject,deleted\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/schemas/**}/subjectsZW\x12U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/schemas/**}/subjects'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSubject']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSubject']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x8f\x01*?/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*}ZL*J/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['LookupVersion']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['LookupVersion']._serialized_options = b'\xdaA\rparent,schema\x82\xd3\xe4\x93\x02\x99\x01"A/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*}:\x01*ZQ"L/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}:\x01*'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetVersion']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}ZW\x12U/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetRawSchemaVersion']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetRawSchemaVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\xb3\x01\x12Q/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}/schemaZ^\x12\\/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}/schema'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListVersions']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListVersions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\xa5\x01\x12J/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*}/versionsZW\x12U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}/versions'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['CreateVersion']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['CreateVersion']._serialized_options = b'\xdaA9parent,version,id,schema_type,schema,references,normalize\x82\xd3\xe4\x93\x02\xab\x01"J/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*}/versions:\x01*ZZ"U/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*}/versions:\x01*'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteVersion']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\xa5\x01*J/v1/{name=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}ZW*U/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListReferencedSchemas']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['ListReferencedSchemas']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\xc3\x01\x12Y/v1/{parent=projects/*/locations/*/schemaRegistries/*/subjects/*/versions/*}/referencedbyZf\x12d/v1/{parent=projects/*/locations/*/schemaRegistries/*/contexts/*/subjects/*/versions/*}/referencedby'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['CheckCompatibility']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['CheckCompatibility']._serialized_options = b'\xdaA\x0bname,schema\x82\xd3\xe4\x93\x02\xa1\x01"E/v1/{name=projects/*/locations/*/schemaRegistries/*/compatibility/**}:\x01*ZU"P/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/compatibility/**}:\x01*'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchemaConfig']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchemaConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x8d\x01\x12>/v1/{name=projects/*/locations/*/schemaRegistries/*/config/**}ZK\x12I/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/config/**}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['UpdateSchemaConfig']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['UpdateSchemaConfig']._serialized_options = b'\xdaA\x12name,compatibility\x82\xd3\xe4\x93\x02\x93\x01\x1a>/v1/{name=projects/*/locations/*/schemaRegistries/*/config/**}:\x01*ZN\x1aI/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/config/**}:\x01*'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSchemaConfig']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSchemaConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x8d\x01*>/v1/{name=projects/*/locations/*/schemaRegistries/*/config/**}ZK*I/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/config/**}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchemaMode']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['GetSchemaMode']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x89\x01\x12</v1/{name=projects/*/locations/*/schemaRegistries/*/mode/**}ZI\x12G/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/mode/**}'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['UpdateSchemaMode']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['UpdateSchemaMode']._serialized_options = b'\xdaA\tname,mode\x82\xd3\xe4\x93\x02\x8f\x01\x1a</v1/{name=projects/*/locations/*/schemaRegistries/*/mode/**}:\x01*ZL\x1aG/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/mode/**}:\x01*'
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSchemaMode']._loaded_options = None
    _globals['_MANAGEDSCHEMAREGISTRY'].methods_by_name['DeleteSchemaMode']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x89\x01*</v1/{name=projects/*/locations/*/schemaRegistries/*/mode/**}ZI*G/v1/{name=projects/*/locations/*/schemaRegistries/*/contexts/*/mode/**}'
    _globals['_GETSCHEMAREGISTRYREQUEST']._serialized_start = 362
    _globals['_GETSCHEMAREGISTRYREQUEST']._serialized_end = 454
    _globals['_LISTSCHEMAREGISTRIESREQUEST']._serialized_start = 456
    _globals['_LISTSCHEMAREGISTRIESREQUEST']._serialized_end = 512
    _globals['_LISTSCHEMAREGISTRIESRESPONSE']._serialized_start = 514
    _globals['_LISTSCHEMAREGISTRIESRESPONSE']._serialized_end = 632
    _globals['_CREATESCHEMAREGISTRYREQUEST']._serialized_start = 635
    _globals['_CREATESCHEMAREGISTRYREQUEST']._serialized_end = 815
    _globals['_DELETESCHEMAREGISTRYREQUEST']._serialized_start = 817
    _globals['_DELETESCHEMAREGISTRYREQUEST']._serialized_end = 912
    _globals['_GETCONTEXTREQUEST']._serialized_start = 914
    _globals['_GETCONTEXTREQUEST']._serialized_end = 998
    _globals['_LISTCONTEXTSREQUEST']._serialized_start = 1000
    _globals['_LISTCONTEXTSREQUEST']._serialized_end = 1089
    _globals['_GETSCHEMAREQUEST']._serialized_start = 1091
    _globals['_GETSCHEMAREQUEST']._serialized_end = 1206
    _globals['_LISTSCHEMATYPESREQUEST']._serialized_start = 1208
    _globals['_LISTSCHEMATYPESREQUEST']._serialized_end = 1259
    _globals['_LISTSCHEMAVERSIONSREQUEST']._serialized_start = 1262
    _globals['_LISTSCHEMAVERSIONSREQUEST']._serialized_end = 1427
    _globals['_LISTSUBJECTSREQUEST']._serialized_start = 1430
    _globals['_LISTSUBJECTSREQUEST']._serialized_end = 1570
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST']._serialized_start = 1573
    _globals['_LISTSUBJECTSBYSCHEMAIDREQUEST']._serialized_end = 1709
    _globals['_LISTVERSIONSREQUEST']._serialized_start = 1711
    _globals['_LISTVERSIONSREQUEST']._serialized_end = 1838
    _globals['_DELETESUBJECTREQUEST']._serialized_start = 1841
    _globals['_DELETESUBJECTREQUEST']._serialized_end = 1971
    _globals['_GETVERSIONREQUEST']._serialized_start = 1973
    _globals['_GETVERSIONREQUEST']._serialized_end = 2096
    _globals['_CREATEVERSIONREQUEST']._serialized_start = 2099
    _globals['_CREATEVERSIONREQUEST']._serialized_end = 2525
    _globals['_CREATEVERSIONRESPONSE']._serialized_start = 2527
    _globals['_CREATEVERSIONRESPONSE']._serialized_end = 2562
    _globals['_LOOKUPVERSIONREQUEST']._serialized_start = 2565
    _globals['_LOOKUPVERSIONREQUEST']._serialized_end = 2962
    _globals['_DELETEVERSIONREQUEST']._serialized_start = 2965
    _globals['_DELETEVERSIONREQUEST']._serialized_end = 3095
    _globals['_LISTREFERENCEDSCHEMASREQUEST']._serialized_start = 3097
    _globals['_LISTREFERENCEDSCHEMASREQUEST']._serialized_end = 3194
    _globals['_CHECKCOMPATIBILITYREQUEST']._serialized_start = 3197
    _globals['_CHECKCOMPATIBILITYREQUEST']._serialized_end = 3514
    _globals['_CHECKCOMPATIBILITYRESPONSE']._serialized_start = 3516
    _globals['_CHECKCOMPATIBILITYRESPONSE']._serialized_end = 3600
    _globals['_GETSCHEMACONFIGREQUEST']._serialized_start = 3603
    _globals['_GETSCHEMACONFIGREQUEST']._serialized_end = 3750
    _globals['_UPDATESCHEMACONFIGREQUEST']._serialized_start = 3753
    _globals['_UPDATESCHEMACONFIGREQUEST']._serialized_end = 4015
    _globals['_DELETESCHEMACONFIGREQUEST']._serialized_start = 4017
    _globals['_DELETESCHEMACONFIGREQUEST']._serialized_end = 4108
    _globals['_GETSCHEMAMODEREQUEST']._serialized_start = 4110
    _globals['_GETSCHEMAMODEREQUEST']._serialized_end = 4194
    _globals['_UPDATESCHEMAMODEREQUEST']._serialized_start = 4197
    _globals['_UPDATESCHEMAMODEREQUEST']._serialized_end = 4369
    _globals['_DELETESCHEMAMODEREQUEST']._serialized_start = 4371
    _globals['_DELETESCHEMAMODEREQUEST']._serialized_end = 4458
    _globals['_MANAGEDSCHEMAREGISTRY']._serialized_start = 4461
    _globals['_MANAGEDSCHEMAREGISTRY']._serialized_end = 12381