# coding: utf-8

"""
    wst-api

    Api which exposes data about the current status of the Westerschelde tunnel

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wst_api_client.models.inline_object_situation_map_active_incidents import InlineObjectSituationMapActiveIncidents

class TestInlineObjectSituationMapActiveIncidents(unittest.TestCase):
    """InlineObjectSituationMapActiveIncidents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineObjectSituationMapActiveIncidents:
        """Test InlineObjectSituationMapActiveIncidents
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineObjectSituationMapActiveIncidents`
        """
        model = InlineObjectSituationMapActiveIncidents()
        if include_optional:
            return InlineObjectSituationMapActiveIncidents(
                var_none = '',
                singular = '',
                plural = ''
            )
        else:
            return InlineObjectSituationMapActiveIncidents(
        )
        """

    def testInlineObjectSituationMapActiveIncidents(self):
        """Test InlineObjectSituationMapActiveIncidents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
