# coding: utf-8

"""
    wst-api

    Api which exposes data about the current status of the Westerschelde tunnel

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wst_api_client.api.incident_api import IncidentApi


class TestIncidentApi(unittest.TestCase):
    """IncidentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IncidentApi()

    def tearDown(self) -> None:
        pass

    def test_get_incident_active(self) -> None:
        """Test case for get_incident_active

        Your GET endpoint
        """
        pass

    def test_get_incident_scheduled(self) -> None:
        """Test case for get_incident_scheduled

        Your GET endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
