# coding: utf-8

"""
    wst-api

    Api which exposes data about the current status of the Westerschelde tunnel

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wst_api_client.models.road_situation import RoadSituation

class TestRoadSituation(unittest.TestCase):
    """RoadSituation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoadSituation:
        """Test RoadSituation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoadSituation`
        """
        model = RoadSituation()
        if include_optional:
            return RoadSituation(
                direction = '',
                name = '',
                severity = '',
                states = [
                    wst_api_client.models.state.state(
                        name = '', 
                        severity = '', 
                        priority = 56, 
                        icon = '', 
                        category = '', )
                    ],
                additional_information = [
                    wst_api_client.models.additional_information.additionalInformation(
                        direction = '', 
                        notify = True, 
                        description = '', )
                    ]
            )
        else:
            return RoadSituation(
        )
        """

    def testRoadSituation(self):
        """Test RoadSituation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
