# coding: utf-8

"""
    wst-api

    Api which exposes data about the current status of the Westerschelde tunnel

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wst_api_client.models.inline_object_incident_popup_error import InlineObjectIncidentPopupError
from wst_api_client.models.inline_object_incident_popup_title import InlineObjectIncidentPopupTitle
from typing import Optional, Set
from typing_extensions import Self

class InlineObjectIncidentPopup(BaseModel):
    """
    InlineObjectIncidentPopup
    """ # noqa: E501
    title: Optional[InlineObjectIncidentPopupTitle] = None
    error: Optional[InlineObjectIncidentPopupError] = None
    heading_when: Optional[StrictStr] = None
    heading_status: Optional[StrictStr] = None
    heading_what: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["title", "error", "heading_when", "heading_status", "heading_what"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InlineObjectIncidentPopup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of title
        if self.title:
            _dict['title'] = self.title.to_dict()
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InlineObjectIncidentPopup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": InlineObjectIncidentPopupTitle.from_dict(obj["title"]) if obj.get("title") is not None else None,
            "error": InlineObjectIncidentPopupError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "heading_when": obj.get("heading_when"),
            "heading_status": obj.get("heading_status"),
            "heading_what": obj.get("heading_what")
        })
        return _obj


