from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar
DESCRIPTOR: _descriptor.FileDescriptor

class CampaignErrorEnum(_message.Message):
    __slots__ = ()

    class CampaignError(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        UNSPECIFIED: _ClassVar[CampaignErrorEnum.CampaignError]
        UNKNOWN: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_CONTENT_NETWORK: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_SEARCH_NETWORK: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_SEARCH_NETWORK_WITHOUT_GOOGLE_SEARCH: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_GOOGLE_SEARCH_FOR_CPM_CAMPAIGN: _ClassVar[CampaignErrorEnum.CampaignError]
        CAMPAIGN_MUST_TARGET_AT_LEAST_ONE_NETWORK: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_PARTNER_SEARCH_NETWORK: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CRITERIA_LEVEL_BIDDING_STRATEGY: _ClassVar[CampaignErrorEnum.CampaignError]
        CAMPAIGN_DURATION_MUST_CONTAIN_ALL_RUNNABLE_TRIALS: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_MODIFY_FOR_TRIAL_CAMPAIGN: _ClassVar[CampaignErrorEnum.CampaignError]
        DUPLICATE_CAMPAIGN_NAME: _ClassVar[CampaignErrorEnum.CampaignError]
        INCOMPATIBLE_CAMPAIGN_FIELD: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_CAMPAIGN_NAME: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_AD_SERVING_OPTIMIZATION_STATUS: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_TRACKING_URL: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_SET_BOTH_TRACKING_URL_TEMPLATE_AND_TRACKING_SETTING: _ClassVar[CampaignErrorEnum.CampaignError]
        MAX_IMPRESSIONS_NOT_IN_RANGE: _ClassVar[CampaignErrorEnum.CampaignError]
        TIME_UNIT_NOT_SUPPORTED: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_OPERATION_IF_SERVING_STATUS_HAS_ENDED: _ClassVar[CampaignErrorEnum.CampaignError]
        BUDGET_CANNOT_BE_SHARED: _ClassVar[CampaignErrorEnum.CampaignError]
        CAMPAIGN_CANNOT_USE_SHARED_BUDGET: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_CHANGE_BUDGET_ON_CAMPAIGN_WITH_TRIALS: _ClassVar[CampaignErrorEnum.CampaignError]
        CAMPAIGN_LABEL_DOES_NOT_EXIST: _ClassVar[CampaignErrorEnum.CampaignError]
        CAMPAIGN_LABEL_ALREADY_EXISTS: _ClassVar[CampaignErrorEnum.CampaignError]
        MISSING_SHOPPING_SETTING: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_SHOPPING_SALES_COUNTRY: _ClassVar[CampaignErrorEnum.CampaignError]
        ADVERTISING_CHANNEL_TYPE_NOT_AVAILABLE_FOR_ACCOUNT_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_ADVERTISING_CHANNEL_SUB_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        AT_LEAST_ONE_CONVERSION_MUST_BE_SELECTED: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_SET_AD_ROTATION_MODE: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_MODIFY_START_DATE_IF_ALREADY_STARTED: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_SET_DATE_TO_PAST: _ClassVar[CampaignErrorEnum.CampaignError]
        MISSING_HOTEL_CUSTOMER_LINK: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_HOTEL_CUSTOMER_LINK: _ClassVar[CampaignErrorEnum.CampaignError]
        MISSING_HOTEL_SETTING: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_USE_SHARED_CAMPAIGN_BUDGET_WHILE_PART_OF_CAMPAIGN_GROUP: _ClassVar[CampaignErrorEnum.CampaignError]
        APP_NOT_FOUND: _ClassVar[CampaignErrorEnum.CampaignError]
        SHOPPING_ENABLE_LOCAL_NOT_SUPPORTED_FOR_CAMPAIGN_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        MERCHANT_NOT_ALLOWED_FOR_COMPARISON_LISTING_ADS: _ClassVar[CampaignErrorEnum.CampaignError]
        INSUFFICIENT_APP_INSTALLS_COUNT: _ClassVar[CampaignErrorEnum.CampaignError]
        SENSITIVE_CATEGORY_APP: _ClassVar[CampaignErrorEnum.CampaignError]
        HEC_AGREEMENT_REQUIRED: _ClassVar[CampaignErrorEnum.CampaignError]
        NOT_COMPATIBLE_WITH_VIEW_THROUGH_CONVERSION_OPTIMIZATION: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_EXCLUDED_PARENT_ASSET_FIELD_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_CREATE_APP_PRE_REGISTRATION_FOR_NON_ANDROID_APP: _ClassVar[CampaignErrorEnum.CampaignError]
        APP_NOT_AVAILABLE_TO_CREATE_APP_PRE_REGISTRATION_CAMPAIGN: _ClassVar[CampaignErrorEnum.CampaignError]
        INCOMPATIBLE_BUDGET_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        LOCAL_SERVICES_DUPLICATE_CATEGORY_BID: _ClassVar[CampaignErrorEnum.CampaignError]
        LOCAL_SERVICES_INVALID_CATEGORY_BID: _ClassVar[CampaignErrorEnum.CampaignError]
        LOCAL_SERVICES_MISSING_CATEGORY_BID: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_STATUS_CHANGE: _ClassVar[CampaignErrorEnum.CampaignError]
        MISSING_TRAVEL_CUSTOMER_LINK: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_TRAVEL_CUSTOMER_LINK: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_EXCLUDED_PARENT_ASSET_SET_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        ASSET_SET_NOT_A_HOTEL_PROPERTY_ASSET_SET: _ClassVar[CampaignErrorEnum.CampaignError]
        HOTEL_PROPERTY_ASSET_SET_ONLY_FOR_PERFORMANCE_MAX_FOR_TRAVEL_GOALS: _ClassVar[CampaignErrorEnum.CampaignError]
        AVERAGE_DAILY_SPEND_TOO_HIGH: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_ATTACH_TO_REMOVED_CAMPAIGN_GROUP: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_ATTACH_TO_BIDDING_STRATEGY: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_CHANGE_BUDGET_PERIOD: _ClassVar[CampaignErrorEnum.CampaignError]
        NOT_ENOUGH_CONVERSIONS: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_SET_MORE_THAN_ONE_CONVERSION_ACTION: _ClassVar[CampaignErrorEnum.CampaignError]
        NOT_COMPATIBLE_WITH_BUDGET_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        NOT_COMPATIBLE_WITH_UPLOAD_CLICKS_CONVERSION: _ClassVar[CampaignErrorEnum.CampaignError]
        APP_ID_MUST_MATCH_CONVERSION_ACTION_APP_ID: _ClassVar[CampaignErrorEnum.CampaignError]
        CONVERSION_ACTION_WITH_DOWNLOAD_CATEGORY_NOT_ALLOWED: _ClassVar[CampaignErrorEnum.CampaignError]
        CONVERSION_ACTION_WITH_DOWNLOAD_CATEGORY_REQUIRED: _ClassVar[CampaignErrorEnum.CampaignError]
        CONVERSION_TRACKING_NOT_ENABLED: _ClassVar[CampaignErrorEnum.CampaignError]
        NOT_COMPATIBLE_WITH_BIDDING_STRATEGY_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        NOT_COMPATIBLE_WITH_GOOGLE_ATTRIBUTION_CONVERSIONS: _ClassVar[CampaignErrorEnum.CampaignError]
        CONVERSION_LAG_TOO_HIGH: _ClassVar[CampaignErrorEnum.CampaignError]
        NOT_LINKED_ADVERTISING_PARTNER: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_NUMBER_OF_ADVERTISING_PARTNER_IDS: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_DISPLAY_NETWORK_WITHOUT_YOUTUBE: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_LINK_TO_COMPARISON_SHOPPING_SERVICE_ACCOUNT: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_TARGET_NETWORK_FOR_COMPARISON_SHOPPING_SERVICE_LINKED_ACCOUNTS: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_MODIFY_TEXT_ASSET_AUTOMATION_WITH_ENABLED_TRIAL: _ClassVar[CampaignErrorEnum.CampaignError]
        DYNAMIC_TEXT_ASSET_CANNOT_OPT_OUT_WITH_FINAL_URL_EXPANSION_OPT_IN: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_SET_CAMPAIGN_KEYWORD_MATCH_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_DISABLE_BROAD_MATCH_WHEN_KEYWORD_CONVERSION_IN_PROCESS: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_DISABLE_BROAD_MATCH_WHEN_TARGETING_BRANDS: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_ENABLE_BROAD_MATCH_FOR_BASE_CAMPAIGN_WITH_PROMOTING_TRIAL: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_ENABLE_BROAD_MATCH_FOR_PROMOTING_TRIAL_CAMPAIGN: _ClassVar[CampaignErrorEnum.CampaignError]
        REQUIRED_BUSINESS_NAME_ASSET_NOT_LINKED: _ClassVar[CampaignErrorEnum.CampaignError]
        REQUIRED_LOGO_ASSET_NOT_LINKED: _ClassVar[CampaignErrorEnum.CampaignError]
        BRAND_TARGETING_OVERRIDES_NOT_SUPPORTED: _ClassVar[CampaignErrorEnum.CampaignError]
        BRAND_GUIDELINES_NOT_ENABLED_FOR_CAMPAIGN: _ClassVar[CampaignErrorEnum.CampaignError]
        BRAND_GUIDELINES_MAIN_AND_ACCENT_COLORS_REQUIRED: _ClassVar[CampaignErrorEnum.CampaignError]
        BRAND_GUIDELINES_COLOR_INVALID_FORMAT: _ClassVar[CampaignErrorEnum.CampaignError]
        BRAND_GUIDELINES_UNSUPPORTED_FONT_FAMILY: _ClassVar[CampaignErrorEnum.CampaignError]
        BRAND_GUIDELINES_UNSUPPORTED_CHANNEL: _ClassVar[CampaignErrorEnum.CampaignError]
        CANNOT_ENABLE_BRAND_GUIDELINES_FOR_TRAVEL_GOALS: _ClassVar[CampaignErrorEnum.CampaignError]
        CUSTOMER_NOT_ALLOWLISTED_FOR_BRAND_GUIDELINES: _ClassVar[CampaignErrorEnum.CampaignError]
        THIRD_PARTY_INTEGRATION_PARTNER_NOT_ALLOWED: _ClassVar[CampaignErrorEnum.CampaignError]
        THIRD_PARTY_INTEGRATION_PARTNER_SHARE_COST_NOT_ALLOWED: _ClassVar[CampaignErrorEnum.CampaignError]
        DUPLICATE_INTERACTION_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        INVALID_INTERACTION_TYPE: _ClassVar[CampaignErrorEnum.CampaignError]
        VIDEO_SEQUENCE_ERROR_SEQUENCE_DEFINITION_REQUIRED: _ClassVar[CampaignErrorEnum.CampaignError]
        AI_MAX_MUST_BE_ENABLED: _ClassVar[CampaignErrorEnum.CampaignError]
    UNSPECIFIED: CampaignErrorEnum.CampaignError
    UNKNOWN: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_CONTENT_NETWORK: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_SEARCH_NETWORK: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_SEARCH_NETWORK_WITHOUT_GOOGLE_SEARCH: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_GOOGLE_SEARCH_FOR_CPM_CAMPAIGN: CampaignErrorEnum.CampaignError
    CAMPAIGN_MUST_TARGET_AT_LEAST_ONE_NETWORK: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_PARTNER_SEARCH_NETWORK: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CRITERIA_LEVEL_BIDDING_STRATEGY: CampaignErrorEnum.CampaignError
    CAMPAIGN_DURATION_MUST_CONTAIN_ALL_RUNNABLE_TRIALS: CampaignErrorEnum.CampaignError
    CANNOT_MODIFY_FOR_TRIAL_CAMPAIGN: CampaignErrorEnum.CampaignError
    DUPLICATE_CAMPAIGN_NAME: CampaignErrorEnum.CampaignError
    INCOMPATIBLE_CAMPAIGN_FIELD: CampaignErrorEnum.CampaignError
    INVALID_CAMPAIGN_NAME: CampaignErrorEnum.CampaignError
    INVALID_AD_SERVING_OPTIMIZATION_STATUS: CampaignErrorEnum.CampaignError
    INVALID_TRACKING_URL: CampaignErrorEnum.CampaignError
    CANNOT_SET_BOTH_TRACKING_URL_TEMPLATE_AND_TRACKING_SETTING: CampaignErrorEnum.CampaignError
    MAX_IMPRESSIONS_NOT_IN_RANGE: CampaignErrorEnum.CampaignError
    TIME_UNIT_NOT_SUPPORTED: CampaignErrorEnum.CampaignError
    INVALID_OPERATION_IF_SERVING_STATUS_HAS_ENDED: CampaignErrorEnum.CampaignError
    BUDGET_CANNOT_BE_SHARED: CampaignErrorEnum.CampaignError
    CAMPAIGN_CANNOT_USE_SHARED_BUDGET: CampaignErrorEnum.CampaignError
    CANNOT_CHANGE_BUDGET_ON_CAMPAIGN_WITH_TRIALS: CampaignErrorEnum.CampaignError
    CAMPAIGN_LABEL_DOES_NOT_EXIST: CampaignErrorEnum.CampaignError
    CAMPAIGN_LABEL_ALREADY_EXISTS: CampaignErrorEnum.CampaignError
    MISSING_SHOPPING_SETTING: CampaignErrorEnum.CampaignError
    INVALID_SHOPPING_SALES_COUNTRY: CampaignErrorEnum.CampaignError
    ADVERTISING_CHANNEL_TYPE_NOT_AVAILABLE_FOR_ACCOUNT_TYPE: CampaignErrorEnum.CampaignError
    INVALID_ADVERTISING_CHANNEL_SUB_TYPE: CampaignErrorEnum.CampaignError
    AT_LEAST_ONE_CONVERSION_MUST_BE_SELECTED: CampaignErrorEnum.CampaignError
    CANNOT_SET_AD_ROTATION_MODE: CampaignErrorEnum.CampaignError
    CANNOT_MODIFY_START_DATE_IF_ALREADY_STARTED: CampaignErrorEnum.CampaignError
    CANNOT_SET_DATE_TO_PAST: CampaignErrorEnum.CampaignError
    MISSING_HOTEL_CUSTOMER_LINK: CampaignErrorEnum.CampaignError
    INVALID_HOTEL_CUSTOMER_LINK: CampaignErrorEnum.CampaignError
    MISSING_HOTEL_SETTING: CampaignErrorEnum.CampaignError
    CANNOT_USE_SHARED_CAMPAIGN_BUDGET_WHILE_PART_OF_CAMPAIGN_GROUP: CampaignErrorEnum.CampaignError
    APP_NOT_FOUND: CampaignErrorEnum.CampaignError
    SHOPPING_ENABLE_LOCAL_NOT_SUPPORTED_FOR_CAMPAIGN_TYPE: CampaignErrorEnum.CampaignError
    MERCHANT_NOT_ALLOWED_FOR_COMPARISON_LISTING_ADS: CampaignErrorEnum.CampaignError
    INSUFFICIENT_APP_INSTALLS_COUNT: CampaignErrorEnum.CampaignError
    SENSITIVE_CATEGORY_APP: CampaignErrorEnum.CampaignError
    HEC_AGREEMENT_REQUIRED: CampaignErrorEnum.CampaignError
    NOT_COMPATIBLE_WITH_VIEW_THROUGH_CONVERSION_OPTIMIZATION: CampaignErrorEnum.CampaignError
    INVALID_EXCLUDED_PARENT_ASSET_FIELD_TYPE: CampaignErrorEnum.CampaignError
    CANNOT_CREATE_APP_PRE_REGISTRATION_FOR_NON_ANDROID_APP: CampaignErrorEnum.CampaignError
    APP_NOT_AVAILABLE_TO_CREATE_APP_PRE_REGISTRATION_CAMPAIGN: CampaignErrorEnum.CampaignError
    INCOMPATIBLE_BUDGET_TYPE: CampaignErrorEnum.CampaignError
    LOCAL_SERVICES_DUPLICATE_CATEGORY_BID: CampaignErrorEnum.CampaignError
    LOCAL_SERVICES_INVALID_CATEGORY_BID: CampaignErrorEnum.CampaignError
    LOCAL_SERVICES_MISSING_CATEGORY_BID: CampaignErrorEnum.CampaignError
    INVALID_STATUS_CHANGE: CampaignErrorEnum.CampaignError
    MISSING_TRAVEL_CUSTOMER_LINK: CampaignErrorEnum.CampaignError
    INVALID_TRAVEL_CUSTOMER_LINK: CampaignErrorEnum.CampaignError
    INVALID_EXCLUDED_PARENT_ASSET_SET_TYPE: CampaignErrorEnum.CampaignError
    ASSET_SET_NOT_A_HOTEL_PROPERTY_ASSET_SET: CampaignErrorEnum.CampaignError
    HOTEL_PROPERTY_ASSET_SET_ONLY_FOR_PERFORMANCE_MAX_FOR_TRAVEL_GOALS: CampaignErrorEnum.CampaignError
    AVERAGE_DAILY_SPEND_TOO_HIGH: CampaignErrorEnum.CampaignError
    CANNOT_ATTACH_TO_REMOVED_CAMPAIGN_GROUP: CampaignErrorEnum.CampaignError
    CANNOT_ATTACH_TO_BIDDING_STRATEGY: CampaignErrorEnum.CampaignError
    CANNOT_CHANGE_BUDGET_PERIOD: CampaignErrorEnum.CampaignError
    NOT_ENOUGH_CONVERSIONS: CampaignErrorEnum.CampaignError
    CANNOT_SET_MORE_THAN_ONE_CONVERSION_ACTION: CampaignErrorEnum.CampaignError
    NOT_COMPATIBLE_WITH_BUDGET_TYPE: CampaignErrorEnum.CampaignError
    NOT_COMPATIBLE_WITH_UPLOAD_CLICKS_CONVERSION: CampaignErrorEnum.CampaignError
    APP_ID_MUST_MATCH_CONVERSION_ACTION_APP_ID: CampaignErrorEnum.CampaignError
    CONVERSION_ACTION_WITH_DOWNLOAD_CATEGORY_NOT_ALLOWED: CampaignErrorEnum.CampaignError
    CONVERSION_ACTION_WITH_DOWNLOAD_CATEGORY_REQUIRED: CampaignErrorEnum.CampaignError
    CONVERSION_TRACKING_NOT_ENABLED: CampaignErrorEnum.CampaignError
    NOT_COMPATIBLE_WITH_BIDDING_STRATEGY_TYPE: CampaignErrorEnum.CampaignError
    NOT_COMPATIBLE_WITH_GOOGLE_ATTRIBUTION_CONVERSIONS: CampaignErrorEnum.CampaignError
    CONVERSION_LAG_TOO_HIGH: CampaignErrorEnum.CampaignError
    NOT_LINKED_ADVERTISING_PARTNER: CampaignErrorEnum.CampaignError
    INVALID_NUMBER_OF_ADVERTISING_PARTNER_IDS: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_DISPLAY_NETWORK_WITHOUT_YOUTUBE: CampaignErrorEnum.CampaignError
    CANNOT_LINK_TO_COMPARISON_SHOPPING_SERVICE_ACCOUNT: CampaignErrorEnum.CampaignError
    CANNOT_TARGET_NETWORK_FOR_COMPARISON_SHOPPING_SERVICE_LINKED_ACCOUNTS: CampaignErrorEnum.CampaignError
    CANNOT_MODIFY_TEXT_ASSET_AUTOMATION_WITH_ENABLED_TRIAL: CampaignErrorEnum.CampaignError
    DYNAMIC_TEXT_ASSET_CANNOT_OPT_OUT_WITH_FINAL_URL_EXPANSION_OPT_IN: CampaignErrorEnum.CampaignError
    CANNOT_SET_CAMPAIGN_KEYWORD_MATCH_TYPE: CampaignErrorEnum.CampaignError
    CANNOT_DISABLE_BROAD_MATCH_WHEN_KEYWORD_CONVERSION_IN_PROCESS: CampaignErrorEnum.CampaignError
    CANNOT_DISABLE_BROAD_MATCH_WHEN_TARGETING_BRANDS: CampaignErrorEnum.CampaignError
    CANNOT_ENABLE_BROAD_MATCH_FOR_BASE_CAMPAIGN_WITH_PROMOTING_TRIAL: CampaignErrorEnum.CampaignError
    CANNOT_ENABLE_BROAD_MATCH_FOR_PROMOTING_TRIAL_CAMPAIGN: CampaignErrorEnum.CampaignError
    REQUIRED_BUSINESS_NAME_ASSET_NOT_LINKED: CampaignErrorEnum.CampaignError
    REQUIRED_LOGO_ASSET_NOT_LINKED: CampaignErrorEnum.CampaignError
    BRAND_TARGETING_OVERRIDES_NOT_SUPPORTED: CampaignErrorEnum.CampaignError
    BRAND_GUIDELINES_NOT_ENABLED_FOR_CAMPAIGN: CampaignErrorEnum.CampaignError
    BRAND_GUIDELINES_MAIN_AND_ACCENT_COLORS_REQUIRED: CampaignErrorEnum.CampaignError
    BRAND_GUIDELINES_COLOR_INVALID_FORMAT: CampaignErrorEnum.CampaignError
    BRAND_GUIDELINES_UNSUPPORTED_FONT_FAMILY: CampaignErrorEnum.CampaignError
    BRAND_GUIDELINES_UNSUPPORTED_CHANNEL: CampaignErrorEnum.CampaignError
    CANNOT_ENABLE_BRAND_GUIDELINES_FOR_TRAVEL_GOALS: CampaignErrorEnum.CampaignError
    CUSTOMER_NOT_ALLOWLISTED_FOR_BRAND_GUIDELINES: CampaignErrorEnum.CampaignError
    THIRD_PARTY_INTEGRATION_PARTNER_NOT_ALLOWED: CampaignErrorEnum.CampaignError
    THIRD_PARTY_INTEGRATION_PARTNER_SHARE_COST_NOT_ALLOWED: CampaignErrorEnum.CampaignError
    DUPLICATE_INTERACTION_TYPE: CampaignErrorEnum.CampaignError
    INVALID_INTERACTION_TYPE: CampaignErrorEnum.CampaignError
    VIDEO_SEQUENCE_ERROR_SEQUENCE_DEFINITION_REQUIRED: CampaignErrorEnum.CampaignError
    AI_MAX_MUST_BE_ENABLED: CampaignErrorEnum.CampaignError

    def __init__(self) -> None:
        ...