"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/eventarc/v1/eventarc.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.eventarc.v1 import channel_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_channel__pb2
from .....google.cloud.eventarc.v1 import channel_connection_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_channel__connection__pb2
from .....google.cloud.eventarc.v1 import discovery_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_discovery__pb2
from .....google.cloud.eventarc.v1 import enrollment_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_enrollment__pb2
from .....google.cloud.eventarc.v1 import google_api_source_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_google__api__source__pb2
from .....google.cloud.eventarc.v1 import google_channel_config_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_google__channel__config__pb2
from .....google.cloud.eventarc.v1 import message_bus_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_message__bus__pb2
from .....google.cloud.eventarc.v1 import pipeline_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_pipeline__pb2
from .....google.cloud.eventarc.v1 import trigger_pb2 as google_dot_cloud_dot_eventarc_dot_v1_dot_trigger__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'google/cloud/eventarc/v1/eventarc.proto\x12\x18google.cloud.eventarc.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a&google/cloud/eventarc/v1/channel.proto\x1a1google/cloud/eventarc/v1/channel_connection.proto\x1a(google/cloud/eventarc/v1/discovery.proto\x1a)google/cloud/eventarc/v1/enrollment.proto\x1a0google/cloud/eventarc/v1/google_api_source.proto\x1a4google/cloud/eventarc/v1/google_channel_config.proto\x1a*google/cloud/eventarc/v1/message_bus.proto\x1a\'google/cloud/eventarc/v1/pipeline.proto\x1a&google/cloud/eventarc/v1/trigger.proto\x1a#google/longrunning/operations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"J\n\x11GetTriggerRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Trigger"\x97\x01\n\x13ListTriggersRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Trigger\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"y\n\x14ListTriggersResponse\x123\n\x08triggers\x18\x01 \x03(\x0b2!.google.cloud.eventarc.v1.Trigger\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xbd\x01\n\x14CreateTriggerRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Trigger\x127\n\x07trigger\x18\x02 \x01(\x0b2!.google.cloud.eventarc.v1.TriggerB\x03\xe0A\x02\x12\x17\n\ntrigger_id\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\xae\x01\n\x14UpdateTriggerRequest\x122\n\x07trigger\x18\x01 \x01(\x0b2!.google.cloud.eventarc.v1.Trigger\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask\x12\x15\n\rallow_missing\x18\x03 \x01(\x08\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x8e\x01\n\x14DeleteTriggerRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Trigger\x12\x0c\n\x04etag\x18\x02 \x01(\t\x12\x15\n\rallow_missing\x18\x03 \x01(\x08\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"J\n\x11GetChannelRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Channel"\x87\x01\n\x13ListChannelsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Channel\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t"y\n\x14ListChannelsResponse\x123\n\x08channels\x18\x01 \x03(\x0b2!.google.cloud.eventarc.v1.Channel\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xbd\x01\n\x14CreateChannelRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Channel\x127\n\x07channel\x18\x02 \x01(\x0b2!.google.cloud.eventarc.v1.ChannelB\x03\xe0A\x02\x12\x17\n\nchannel_id\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x97\x01\n\x14UpdateChannelRequest\x122\n\x07channel\x18\x01 \x01(\x0b2!.google.cloud.eventarc.v1.Channel\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask\x12\x1a\n\rvalidate_only\x18\x03 \x01(\x08B\x03\xe0A\x01"i\n\x14DeleteChannelRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Channel\x12\x1a\n\rvalidate_only\x18\x02 \x01(\x08B\x03\xe0A\x01"L\n\x12GetProviderRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n eventarc.googleapis.com/Provider"\x99\x01\n\x14ListProvidersRequest\x128\n\x06parent\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\x12 eventarc.googleapis.com/Provider\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"|\n\x15ListProvidersResponse\x125\n\tproviders\x18\x01 \x03(\x0b2".google.cloud.eventarc.v1.Provider\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"^\n\x1bGetChannelConnectionRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)eventarc.googleapis.com/ChannelConnection"\x89\x01\n\x1dListChannelConnectionsRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\x12)eventarc.googleapis.com/ChannelConnection\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"\x98\x01\n\x1eListChannelConnectionsResponse\x12H\n\x13channel_connections\x18\x01 \x03(\x0b2+.google.cloud.eventarc.v1.ChannelConnection\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xd5\x01\n\x1eCreateChannelConnectionRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\x12)eventarc.googleapis.com/ChannelConnection\x12L\n\x12channel_connection\x18\x02 \x01(\x0b2+.google.cloud.eventarc.v1.ChannelConnectionB\x03\xe0A\x02\x12"\n\x15channel_connection_id\x18\x03 \x01(\tB\x03\xe0A\x02"a\n\x1eDeleteChannelConnectionRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)eventarc.googleapis.com/ChannelConnection"\xa6\x01\n UpdateGoogleChannelConfigRequest\x12Q\n\x15google_channel_config\x18\x01 \x01(\x0b2-.google.cloud.eventarc.v1.GoogleChannelConfigB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"b\n\x1dGetGoogleChannelConfigRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+eventarc.googleapis.com/GoogleChannelConfig"P\n\x14GetMessageBusRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"eventarc.googleapis.com/MessageBus"\xb2\x01\n\x17ListMessageBusesRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/MessageBus\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01"\x85\x01\n\x18ListMessageBusesResponse\x12;\n\rmessage_buses\x18\x01 \x03(\x0b2$.google.cloud.eventarc.v1.MessageBus\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\x8f\x01\n ListMessageBusEnrollmentsRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"eventarc.googleapis.com/MessageBus\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"f\n!ListMessageBusEnrollmentsResponse\x12\x13\n\x0benrollments\x18\x01 \x03(\t\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xce\x01\n\x17CreateMessageBusRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/MessageBus\x12>\n\x0bmessage_bus\x18\x02 \x01(\x0b2$.google.cloud.eventarc.v1.MessageBusB\x03\xe0A\x02\x12\x1b\n\x0emessage_bus_id\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\xc7\x01\n\x17UpdateMessageBusRequest\x12>\n\x0bmessage_bus\x18\x01 \x01(\x0b2$.google.cloud.eventarc.v1.MessageBusB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x9e\x01\n\x17DeleteMessageBusRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"eventarc.googleapis.com/MessageBus\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"P\n\x14GetEnrollmentRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"eventarc.googleapis.com/Enrollment"\xb1\x01\n\x16ListEnrollmentsRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/Enrollment\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01"\x82\x01\n\x17ListEnrollmentsResponse\x129\n\x0benrollments\x18\x01 \x03(\x0b2$.google.cloud.eventarc.v1.Enrollment\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xcc\x01\n\x17CreateEnrollmentRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/Enrollment\x12=\n\nenrollment\x18\x02 \x01(\x0b2$.google.cloud.eventarc.v1.EnrollmentB\x03\xe0A\x02\x12\x1a\n\renrollment_id\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\xc6\x01\n\x17UpdateEnrollmentRequest\x12=\n\nenrollment\x18\x01 \x01(\x0b2$.google.cloud.eventarc.v1.EnrollmentB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x9e\x01\n\x17DeleteEnrollmentRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"eventarc.googleapis.com/Enrollment\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"L\n\x12GetPipelineRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n eventarc.googleapis.com/Pipeline"\xad\x01\n\x14ListPipelinesRequest\x128\n\x06parent\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\x12 eventarc.googleapis.com/Pipeline\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01"|\n\x15ListPipelinesResponse\x125\n\tpipelines\x18\x01 \x03(\x0b2".google.cloud.eventarc.v1.Pipeline\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xc2\x01\n\x15CreatePipelineRequest\x128\n\x06parent\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\x12 eventarc.googleapis.com/Pipeline\x129\n\x08pipeline\x18\x02 \x01(\x0b2".google.cloud.eventarc.v1.PipelineB\x03\xe0A\x02\x12\x18\n\x0bpipeline_id\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\xc0\x01\n\x15UpdatePipelineRequest\x129\n\x08pipeline\x18\x01 \x01(\x0b2".google.cloud.eventarc.v1.PipelineB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x9a\x01\n\x15DeletePipelineRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n eventarc.googleapis.com/Pipeline\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"Z\n\x19GetGoogleApiSourceRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'eventarc.googleapis.com/GoogleApiSource"\xbb\x01\n\x1bListGoogleApiSourcesRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\x12\'eventarc.googleapis.com/GoogleApiSource\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01"\x93\x01\n\x1cListGoogleApiSourcesResponse\x12E\n\x12google_api_sources\x18\x01 \x03(\x0b2).google.cloud.eventarc.v1.GoogleApiSource\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xe9\x01\n\x1cCreateGoogleApiSourceRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\x12\'eventarc.googleapis.com/GoogleApiSource\x12I\n\x11google_api_source\x18\x02 \x01(\x0b2).google.cloud.eventarc.v1.GoogleApiSourceB\x03\xe0A\x02\x12!\n\x14google_api_source_id\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\xd7\x01\n\x1cUpdateGoogleApiSourceRequest\x12I\n\x11google_api_source\x18\x01 \x01(\x0b2).google.cloud.eventarc.v1.GoogleApiSourceB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\xa8\x01\n\x1cDeleteGoogleApiSourceRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'eventarc.googleapis.com/GoogleApiSource\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rallow_missing\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01"\x80\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x032\xf5@\n\x08Eventarc\x12\x99\x01\n\nGetTrigger\x12+.google.cloud.eventarc.v1.GetTriggerRequest\x1a!.google.cloud.eventarc.v1.Trigger";\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v1/{name=projects/*/locations/*/triggers/*}\x12\xac\x01\n\x0cListTriggers\x12-.google.cloud.eventarc.v1.ListTriggersRequest\x1a..google.cloud.eventarc.v1.ListTriggersResponse"=\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1/{parent=projects/*/locations/*}/triggers\x12\xd8\x01\n\rCreateTrigger\x12..google.cloud.eventarc.v1.CreateTriggerRequest\x1a\x1d.google.longrunning.Operation"x\xcaA\x1c\n\x07Trigger\x12\x11OperationMetadata\xdaA\x19parent,trigger,trigger_id\x82\xd3\xe4\x93\x027",/v1/{parent=projects/*/locations/*}/triggers:\x07trigger\x12\xe9\x01\n\rUpdateTrigger\x12..google.cloud.eventarc.v1.UpdateTriggerRequest\x1a\x1d.google.longrunning.Operation"\x88\x01\xcaA\x1c\n\x07Trigger\x12\x11OperationMetadata\xdaA!trigger,update_mask,allow_missing\x82\xd3\xe4\x93\x02?24/v1/{trigger.name=projects/*/locations/*/triggers/*}:\x07trigger\x12\xc8\x01\n\rDeleteTrigger\x12..google.cloud.eventarc.v1.DeleteTriggerRequest\x1a\x1d.google.longrunning.Operation"h\xcaA\x1c\n\x07Trigger\x12\x11OperationMetadata\xdaA\x12name,allow_missing\x82\xd3\xe4\x93\x02.*,/v1/{name=projects/*/locations/*/triggers/*}\x12\x99\x01\n\nGetChannel\x12+.google.cloud.eventarc.v1.GetChannelRequest\x1a!.google.cloud.eventarc.v1.Channel";\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v1/{name=projects/*/locations/*/channels/*}\x12\xac\x01\n\x0cListChannels\x12-.google.cloud.eventarc.v1.ListChannelsRequest\x1a..google.cloud.eventarc.v1.ListChannelsResponse"=\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1/{parent=projects/*/locations/*}/channels\x12\xd8\x01\n\rCreateChannel\x12..google.cloud.eventarc.v1.CreateChannelRequest\x1a\x1d.google.longrunning.Operation"x\xcaA\x1c\n\x07Channel\x12\x11OperationMetadata\xdaA\x19parent,channel,channel_id\x82\xd3\xe4\x93\x027",/v1/{parent=projects/*/locations/*}/channels:\x07channel\x12\xda\x01\n\rUpdateChannel\x12..google.cloud.eventarc.v1.UpdateChannelRequest\x1a\x1d.google.longrunning.Operation"z\xcaA\x1c\n\x07Channel\x12\x11OperationMetadata\xdaA\x13channel,update_mask\x82\xd3\xe4\x93\x02?24/v1/{channel.name=projects/*/locations/*/channels/*}:\x07channel\x12\xba\x01\n\rDeleteChannel\x12..google.cloud.eventarc.v1.DeleteChannelRequest\x1a\x1d.google.longrunning.Operation"Z\xcaA\x1c\n\x07Channel\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02.*,/v1/{name=projects/*/locations/*/channels/*}\x12\x9d\x01\n\x0bGetProvider\x12,.google.cloud.eventarc.v1.GetProviderRequest\x1a".google.cloud.eventarc.v1.Provider"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/providers/*}\x12\xb0\x01\n\rListProviders\x12..google.cloud.eventarc.v1.ListProvidersRequest\x1a/.google.cloud.eventarc.v1.ListProvidersResponse">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/providers\x12\xc1\x01\n\x14GetChannelConnection\x125.google.cloud.eventarc.v1.GetChannelConnectionRequest\x1a+.google.cloud.eventarc.v1.ChannelConnection"E\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/locations/*/channelConnections/*}\x12\xd4\x01\n\x16ListChannelConnections\x127.google.cloud.eventarc.v1.ListChannelConnectionsRequest\x1a8.google.cloud.eventarc.v1.ListChannelConnectionsResponse"G\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/locations/*}/channelConnections\x12\xa2\x02\n\x17CreateChannelConnection\x128.google.cloud.eventarc.v1.CreateChannelConnectionRequest\x1a\x1d.google.longrunning.Operation"\xad\x01\xcaA&\n\x11ChannelConnection\x12\x11OperationMetadata\xdaA/parent,channel_connection,channel_connection_id\x82\xd3\xe4\x93\x02L"6/v1/{parent=projects/*/locations/*}/channelConnections:\x12channel_connection\x12\xe2\x01\n\x17DeleteChannelConnection\x128.google.cloud.eventarc.v1.DeleteChannelConnectionRequest\x1a\x1d.google.longrunning.Operation"n\xcaA&\n\x11ChannelConnection\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/locations/*/channelConnections/*}\x12\xc6\x01\n\x16GetGoogleChannelConfig\x127.google.cloud.eventarc.v1.GetGoogleChannelConfigRequest\x1a-.google.cloud.eventarc.v1.GoogleChannelConfig"D\xdaA\x04name\x82\xd3\xe4\x93\x027\x125/v1/{name=projects/*/locations/*/googleChannelConfig}\x12\x97\x02\n\x19UpdateGoogleChannelConfig\x12:.google.cloud.eventarc.v1.UpdateGoogleChannelConfigRequest\x1a-.google.cloud.eventarc.v1.GoogleChannelConfig"\x8e\x01\xdaA!google_channel_config,update_mask\x82\xd3\xe4\x93\x02d2K/v1/{google_channel_config.name=projects/*/locations/*/googleChannelConfig}:\x15google_channel_config\x12\xa6\x01\n\rGetMessageBus\x12..google.cloud.eventarc.v1.GetMessageBusRequest\x1a$.google.cloud.eventarc.v1.MessageBus"?\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*/messageBuses/*}\x12\xbc\x01\n\x10ListMessageBuses\x121.google.cloud.eventarc.v1.ListMessageBusesRequest\x1a2.google.cloud.eventarc.v1.ListMessageBusesResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/messageBuses\x12\xe9\x01\n\x19ListMessageBusEnrollments\x12:.google.cloud.eventarc.v1.ListMessageBusEnrollmentsRequest\x1a;.google.cloud.eventarc.v1.ListMessageBusEnrollmentsResponse"S\xdaA\x06parent\x82\xd3\xe4\x93\x02D\x12B/v1/{parent=projects/*/locations/*/messageBuses/*}:listEnrollments\x12\xf2\x01\n\x10CreateMessageBus\x121.google.cloud.eventarc.v1.CreateMessageBusRequest\x1a\x1d.google.longrunning.Operation"\x8b\x01\xcaA\x1f\n\nMessageBus\x12\x11OperationMetadata\xdaA!parent,message_bus,message_bus_id\x82\xd3\xe4\x93\x02?"0/v1/{parent=projects/*/locations/*}/messageBuses:\x0bmessage_bus\x12\xf4\x01\n\x10UpdateMessageBus\x121.google.cloud.eventarc.v1.UpdateMessageBusRequest\x1a\x1d.google.longrunning.Operation"\x8d\x01\xcaA\x1f\n\nMessageBus\x12\x11OperationMetadata\xdaA\x17message_bus,update_mask\x82\xd3\xe4\x93\x02K2</v1/{message_bus.name=projects/*/locations/*/messageBuses/*}:\x0bmessage_bus\x12\xcc\x01\n\x10DeleteMessageBus\x121.google.cloud.eventarc.v1.DeleteMessageBusRequest\x1a\x1d.google.longrunning.Operation"f\xcaA\x1f\n\nMessageBus\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x022*0/v1/{name=projects/*/locations/*/messageBuses/*}\x12\xa5\x01\n\rGetEnrollment\x12..google.cloud.eventarc.v1.GetEnrollmentRequest\x1a$.google.cloud.eventarc.v1.Enrollment">\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v1/{name=projects/*/locations/*/enrollments/*}\x12\xb8\x01\n\x0fListEnrollments\x120.google.cloud.eventarc.v1.ListEnrollmentsRequest\x1a1.google.cloud.eventarc.v1.ListEnrollmentsResponse"@\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v1/{parent=projects/*/locations/*}/enrollments\x12\xee\x01\n\x10CreateEnrollment\x121.google.cloud.eventarc.v1.CreateEnrollmentRequest\x1a\x1d.google.longrunning.Operation"\x87\x01\xcaA\x1f\n\nEnrollment\x12\x11OperationMetadata\xdaA\x1fparent,enrollment,enrollment_id\x82\xd3\xe4\x93\x02="//v1/{parent=projects/*/locations/*}/enrollments:\nenrollment\x12\xf0\x01\n\x10UpdateEnrollment\x121.google.cloud.eventarc.v1.UpdateEnrollmentRequest\x1a\x1d.google.longrunning.Operation"\x89\x01\xcaA\x1f\n\nEnrollment\x12\x11OperationMetadata\xdaA\x16enrollment,update_mask\x82\xd3\xe4\x93\x02H2:/v1/{enrollment.name=projects/*/locations/*/enrollments/*}:\nenrollment\x12\xcb\x01\n\x10DeleteEnrollment\x121.google.cloud.eventarc.v1.DeleteEnrollmentRequest\x1a\x1d.google.longrunning.Operation"e\xcaA\x1f\n\nEnrollment\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x021*//v1/{name=projects/*/locations/*/enrollments/*}\x12\x9d\x01\n\x0bGetPipeline\x12,.google.cloud.eventarc.v1.GetPipelineRequest\x1a".google.cloud.eventarc.v1.Pipeline"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/pipelines/*}\x12\xb0\x01\n\rListPipelines\x12..google.cloud.eventarc.v1.ListPipelinesRequest\x1a/.google.cloud.eventarc.v1.ListPipelinesResponse">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/pipelines\x12\xdf\x01\n\x0eCreatePipeline\x12/.google.cloud.eventarc.v1.CreatePipelineRequest\x1a\x1d.google.longrunning.Operation"}\xcaA\x1d\n\x08Pipeline\x12\x11OperationMetadata\xdaA\x1bparent,pipeline,pipeline_id\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/pipelines:\x08pipeline\x12\xe1\x01\n\x0eUpdatePipeline\x12/.google.cloud.eventarc.v1.UpdatePipelineRequest\x1a\x1d.google.longrunning.Operation"\x7f\xcaA\x1d\n\x08Pipeline\x12\x11OperationMetadata\xdaA\x14pipeline,update_mask\x82\xd3\xe4\x93\x02B26/v1/{pipeline.name=projects/*/locations/*/pipelines/*}:\x08pipeline\x12\xc3\x01\n\x0eDeletePipeline\x12/.google.cloud.eventarc.v1.DeletePipelineRequest\x1a\x1d.google.longrunning.Operation"a\xcaA\x1d\n\x08Pipeline\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/pipelines/*}\x12\xb9\x01\n\x12GetGoogleApiSource\x123.google.cloud.eventarc.v1.GetGoogleApiSourceRequest\x1a).google.cloud.eventarc.v1.GoogleApiSource"C\xdaA\x04name\x82\xd3\xe4\x93\x026\x124/v1/{name=projects/*/locations/*/googleApiSources/*}\x12\xcc\x01\n\x14ListGoogleApiSources\x125.google.cloud.eventarc.v1.ListGoogleApiSourcesRequest\x1a6.google.cloud.eventarc.v1.ListGoogleApiSourcesResponse"E\xdaA\x06parent\x82\xd3\xe4\x93\x026\x124/v1/{parent=projects/*/locations/*}/googleApiSources\x12\x97\x02\n\x15CreateGoogleApiSource\x126.google.cloud.eventarc.v1.CreateGoogleApiSourceRequest\x1a\x1d.google.longrunning.Operation"\xa6\x01\xcaA$\n\x0fGoogleApiSource\x12\x11OperationMetadata\xdaA-parent,google_api_source,google_api_source_id\x82\xd3\xe4\x93\x02I"4/v1/{parent=projects/*/locations/*}/googleApiSources:\x11google_api_source\x12\x99\x02\n\x15UpdateGoogleApiSource\x126.google.cloud.eventarc.v1.UpdateGoogleApiSourceRequest\x1a\x1d.google.longrunning.Operation"\xa8\x01\xcaA$\n\x0fGoogleApiSource\x12\x11OperationMetadata\xdaA\x1dgoogle_api_source,update_mask\x82\xd3\xe4\x93\x02[2F/v1/{google_api_source.name=projects/*/locations/*/googleApiSources/*}:\x11google_api_source\x12\xdf\x01\n\x15DeleteGoogleApiSource\x126.google.cloud.eventarc.v1.DeleteGoogleApiSourceRequest\x1a\x1d.google.longrunning.Operation"o\xcaA$\n\x0fGoogleApiSource\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x026*4/v1/{name=projects/*/locations/*/googleApiSources/*}\x1aK\xcaA\x17eventarc.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xbd\x01\n\x1ccom.google.cloud.eventarc.v1B\rEventarcProtoP\x01Z8cloud.google.com/go/eventarc/apiv1/eventarcpb;eventarcpb\xaa\x02\x18Google.Cloud.Eventarc.V1\xca\x02\x18Google\\Cloud\\Eventarc\\V1\xea\x02\x1bGoogle::Cloud::Eventarc::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.eventarc.v1.eventarc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1ccom.google.cloud.eventarc.v1B\rEventarcProtoP\x01Z8cloud.google.com/go/eventarc/apiv1/eventarcpb;eventarcpb\xaa\x02\x18Google.Cloud.Eventarc.V1\xca\x02\x18Google\\Cloud\\Eventarc\\V1\xea\x02\x1bGoogle::Cloud::Eventarc::V1'
    _globals['_GETTRIGGERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETTRIGGERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Trigger'
    _globals['_LISTTRIGGERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTTRIGGERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Trigger'
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Trigger'
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['trigger']._loaded_options = None
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['trigger']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['trigger_id']._loaded_options = None
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['trigger_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATETRIGGERREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATETRIGGERREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATETRIGGERREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETETRIGGERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETETRIGGERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Trigger'
    _globals['_DELETETRIGGERREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_DELETETRIGGERREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_GETCHANNELREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCHANNELREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Channel'
    _globals['_LISTCHANNELSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCHANNELSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Channel'
    _globals['_CREATECHANNELREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECHANNELREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1feventarc.googleapis.com/Channel'
    _globals['_CREATECHANNELREQUEST'].fields_by_name['channel']._loaded_options = None
    _globals['_CREATECHANNELREQUEST'].fields_by_name['channel']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECHANNELREQUEST'].fields_by_name['channel_id']._loaded_options = None
    _globals['_CREATECHANNELREQUEST'].fields_by_name['channel_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECHANNELREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATECHANNELREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECHANNELREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATECHANNELREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETECHANNELREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECHANNELREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1feventarc.googleapis.com/Channel'
    _globals['_DELETECHANNELREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_DELETECHANNELREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_GETPROVIDERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPROVIDERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n eventarc.googleapis.com/Provider'
    _globals['_LISTPROVIDERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTPROVIDERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA"\x12 eventarc.googleapis.com/Provider'
    _globals['_GETCHANNELCONNECTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCHANNELCONNECTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)eventarc.googleapis.com/ChannelConnection'
    _globals['_LISTCHANNELCONNECTIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCHANNELCONNECTIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\x12)eventarc.googleapis.com/ChannelConnection'
    _globals['_CREATECHANNELCONNECTIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECHANNELCONNECTIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\x12)eventarc.googleapis.com/ChannelConnection'
    _globals['_CREATECHANNELCONNECTIONREQUEST'].fields_by_name['channel_connection']._loaded_options = None
    _globals['_CREATECHANNELCONNECTIONREQUEST'].fields_by_name['channel_connection']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECHANNELCONNECTIONREQUEST'].fields_by_name['channel_connection_id']._loaded_options = None
    _globals['_CREATECHANNELCONNECTIONREQUEST'].fields_by_name['channel_connection_id']._serialized_options = b'\xe0A\x02'
    _globals['_DELETECHANNELCONNECTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECHANNELCONNECTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)eventarc.googleapis.com/ChannelConnection'
    _globals['_UPDATEGOOGLECHANNELCONFIGREQUEST'].fields_by_name['google_channel_config']._loaded_options = None
    _globals['_UPDATEGOOGLECHANNELCONFIGREQUEST'].fields_by_name['google_channel_config']._serialized_options = b'\xe0A\x02'
    _globals['_GETGOOGLECHANNELCONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETGOOGLECHANNELCONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+eventarc.googleapis.com/GoogleChannelConfig'
    _globals['_GETMESSAGEBUSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETMESSAGEBUSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"eventarc.googleapis.com/MessageBus'
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/MessageBus'
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTMESSAGEBUSESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"eventarc.googleapis.com/MessageBus'
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/MessageBus'
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['message_bus']._loaded_options = None
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['message_bus']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['message_bus_id']._loaded_options = None
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['message_bus_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEMESSAGEBUSREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['message_bus']._loaded_options = None
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['message_bus']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEMESSAGEBUSREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"eventarc.googleapis.com/MessageBus'
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_DELETEMESSAGEBUSREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_GETENROLLMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETENROLLMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"eventarc.googleapis.com/Enrollment'
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/Enrollment'
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTENROLLMENTSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"eventarc.googleapis.com/Enrollment'
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['enrollment']._loaded_options = None
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['enrollment']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['enrollment_id']._loaded_options = None
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['enrollment_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEENROLLMENTREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['enrollment']._loaded_options = None
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['enrollment']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEENROLLMENTREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"eventarc.googleapis.com/Enrollment'
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_DELETEENROLLMENTREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_GETPIPELINEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPIPELINEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n eventarc.googleapis.com/Pipeline'
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA"\x12 eventarc.googleapis.com/Pipeline'
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTPIPELINESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA"\x12 eventarc.googleapis.com/Pipeline'
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['pipeline']._loaded_options = None
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['pipeline']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['pipeline_id']._loaded_options = None
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['pipeline_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEPIPELINEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['pipeline']._loaded_options = None
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['pipeline']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEPIPELINEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n eventarc.googleapis.com/Pipeline'
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_DELETEPIPELINEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_GETGOOGLEAPISOURCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETGOOGLEAPISOURCEREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'eventarc.googleapis.com/GoogleApiSource"
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'eventarc.googleapis.com/GoogleApiSource"
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTGOOGLEAPISOURCESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'eventarc.googleapis.com/GoogleApiSource"
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['google_api_source']._loaded_options = None
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['google_api_source']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['google_api_source_id']._loaded_options = None
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['google_api_source_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEGOOGLEAPISOURCEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['google_api_source']._loaded_options = None
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['google_api_source']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'eventarc.googleapis.com/GoogleApiSource"
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_DELETEGOOGLEAPISOURCEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_EVENTARC']._loaded_options = None
    _globals['_EVENTARC']._serialized_options = b'\xcaA\x17eventarc.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_EVENTARC'].methods_by_name['GetTrigger']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetTrigger']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v1/{name=projects/*/locations/*/triggers/*}'
    _globals['_EVENTARC'].methods_by_name['ListTriggers']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListTriggers']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1/{parent=projects/*/locations/*}/triggers'
    _globals['_EVENTARC'].methods_by_name['CreateTrigger']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['CreateTrigger']._serialized_options = b'\xcaA\x1c\n\x07Trigger\x12\x11OperationMetadata\xdaA\x19parent,trigger,trigger_id\x82\xd3\xe4\x93\x027",/v1/{parent=projects/*/locations/*}/triggers:\x07trigger'
    _globals['_EVENTARC'].methods_by_name['UpdateTrigger']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['UpdateTrigger']._serialized_options = b'\xcaA\x1c\n\x07Trigger\x12\x11OperationMetadata\xdaA!trigger,update_mask,allow_missing\x82\xd3\xe4\x93\x02?24/v1/{trigger.name=projects/*/locations/*/triggers/*}:\x07trigger'
    _globals['_EVENTARC'].methods_by_name['DeleteTrigger']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['DeleteTrigger']._serialized_options = b'\xcaA\x1c\n\x07Trigger\x12\x11OperationMetadata\xdaA\x12name,allow_missing\x82\xd3\xe4\x93\x02.*,/v1/{name=projects/*/locations/*/triggers/*}'
    _globals['_EVENTARC'].methods_by_name['GetChannel']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetChannel']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v1/{name=projects/*/locations/*/channels/*}'
    _globals['_EVENTARC'].methods_by_name['ListChannels']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListChannels']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1/{parent=projects/*/locations/*}/channels'
    _globals['_EVENTARC'].methods_by_name['CreateChannel']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['CreateChannel']._serialized_options = b'\xcaA\x1c\n\x07Channel\x12\x11OperationMetadata\xdaA\x19parent,channel,channel_id\x82\xd3\xe4\x93\x027",/v1/{parent=projects/*/locations/*}/channels:\x07channel'
    _globals['_EVENTARC'].methods_by_name['UpdateChannel']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['UpdateChannel']._serialized_options = b'\xcaA\x1c\n\x07Channel\x12\x11OperationMetadata\xdaA\x13channel,update_mask\x82\xd3\xe4\x93\x02?24/v1/{channel.name=projects/*/locations/*/channels/*}:\x07channel'
    _globals['_EVENTARC'].methods_by_name['DeleteChannel']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['DeleteChannel']._serialized_options = b'\xcaA\x1c\n\x07Channel\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02.*,/v1/{name=projects/*/locations/*/channels/*}'
    _globals['_EVENTARC'].methods_by_name['GetProvider']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetProvider']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/providers/*}'
    _globals['_EVENTARC'].methods_by_name['ListProviders']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListProviders']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/providers'
    _globals['_EVENTARC'].methods_by_name['GetChannelConnection']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetChannelConnection']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/locations/*/channelConnections/*}'
    _globals['_EVENTARC'].methods_by_name['ListChannelConnections']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListChannelConnections']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/locations/*}/channelConnections'
    _globals['_EVENTARC'].methods_by_name['CreateChannelConnection']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['CreateChannelConnection']._serialized_options = b'\xcaA&\n\x11ChannelConnection\x12\x11OperationMetadata\xdaA/parent,channel_connection,channel_connection_id\x82\xd3\xe4\x93\x02L"6/v1/{parent=projects/*/locations/*}/channelConnections:\x12channel_connection'
    _globals['_EVENTARC'].methods_by_name['DeleteChannelConnection']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['DeleteChannelConnection']._serialized_options = b'\xcaA&\n\x11ChannelConnection\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/locations/*/channelConnections/*}'
    _globals['_EVENTARC'].methods_by_name['GetGoogleChannelConfig']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetGoogleChannelConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x027\x125/v1/{name=projects/*/locations/*/googleChannelConfig}'
    _globals['_EVENTARC'].methods_by_name['UpdateGoogleChannelConfig']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['UpdateGoogleChannelConfig']._serialized_options = b'\xdaA!google_channel_config,update_mask\x82\xd3\xe4\x93\x02d2K/v1/{google_channel_config.name=projects/*/locations/*/googleChannelConfig}:\x15google_channel_config'
    _globals['_EVENTARC'].methods_by_name['GetMessageBus']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetMessageBus']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*/messageBuses/*}'
    _globals['_EVENTARC'].methods_by_name['ListMessageBuses']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListMessageBuses']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/messageBuses'
    _globals['_EVENTARC'].methods_by_name['ListMessageBusEnrollments']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListMessageBusEnrollments']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02D\x12B/v1/{parent=projects/*/locations/*/messageBuses/*}:listEnrollments'
    _globals['_EVENTARC'].methods_by_name['CreateMessageBus']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['CreateMessageBus']._serialized_options = b'\xcaA\x1f\n\nMessageBus\x12\x11OperationMetadata\xdaA!parent,message_bus,message_bus_id\x82\xd3\xe4\x93\x02?"0/v1/{parent=projects/*/locations/*}/messageBuses:\x0bmessage_bus'
    _globals['_EVENTARC'].methods_by_name['UpdateMessageBus']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['UpdateMessageBus']._serialized_options = b'\xcaA\x1f\n\nMessageBus\x12\x11OperationMetadata\xdaA\x17message_bus,update_mask\x82\xd3\xe4\x93\x02K2</v1/{message_bus.name=projects/*/locations/*/messageBuses/*}:\x0bmessage_bus'
    _globals['_EVENTARC'].methods_by_name['DeleteMessageBus']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['DeleteMessageBus']._serialized_options = b'\xcaA\x1f\n\nMessageBus\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x022*0/v1/{name=projects/*/locations/*/messageBuses/*}'
    _globals['_EVENTARC'].methods_by_name['GetEnrollment']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetEnrollment']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v1/{name=projects/*/locations/*/enrollments/*}'
    _globals['_EVENTARC'].methods_by_name['ListEnrollments']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListEnrollments']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v1/{parent=projects/*/locations/*}/enrollments'
    _globals['_EVENTARC'].methods_by_name['CreateEnrollment']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['CreateEnrollment']._serialized_options = b'\xcaA\x1f\n\nEnrollment\x12\x11OperationMetadata\xdaA\x1fparent,enrollment,enrollment_id\x82\xd3\xe4\x93\x02="//v1/{parent=projects/*/locations/*}/enrollments:\nenrollment'
    _globals['_EVENTARC'].methods_by_name['UpdateEnrollment']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['UpdateEnrollment']._serialized_options = b'\xcaA\x1f\n\nEnrollment\x12\x11OperationMetadata\xdaA\x16enrollment,update_mask\x82\xd3\xe4\x93\x02H2:/v1/{enrollment.name=projects/*/locations/*/enrollments/*}:\nenrollment'
    _globals['_EVENTARC'].methods_by_name['DeleteEnrollment']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['DeleteEnrollment']._serialized_options = b'\xcaA\x1f\n\nEnrollment\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x021*//v1/{name=projects/*/locations/*/enrollments/*}'
    _globals['_EVENTARC'].methods_by_name['GetPipeline']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetPipeline']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/pipelines/*}'
    _globals['_EVENTARC'].methods_by_name['ListPipelines']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListPipelines']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/pipelines'
    _globals['_EVENTARC'].methods_by_name['CreatePipeline']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['CreatePipeline']._serialized_options = b'\xcaA\x1d\n\x08Pipeline\x12\x11OperationMetadata\xdaA\x1bparent,pipeline,pipeline_id\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/pipelines:\x08pipeline'
    _globals['_EVENTARC'].methods_by_name['UpdatePipeline']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['UpdatePipeline']._serialized_options = b'\xcaA\x1d\n\x08Pipeline\x12\x11OperationMetadata\xdaA\x14pipeline,update_mask\x82\xd3\xe4\x93\x02B26/v1/{pipeline.name=projects/*/locations/*/pipelines/*}:\x08pipeline'
    _globals['_EVENTARC'].methods_by_name['DeletePipeline']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['DeletePipeline']._serialized_options = b'\xcaA\x1d\n\x08Pipeline\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/pipelines/*}'
    _globals['_EVENTARC'].methods_by_name['GetGoogleApiSource']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['GetGoogleApiSource']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x026\x124/v1/{name=projects/*/locations/*/googleApiSources/*}'
    _globals['_EVENTARC'].methods_by_name['ListGoogleApiSources']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['ListGoogleApiSources']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x026\x124/v1/{parent=projects/*/locations/*}/googleApiSources'
    _globals['_EVENTARC'].methods_by_name['CreateGoogleApiSource']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['CreateGoogleApiSource']._serialized_options = b'\xcaA$\n\x0fGoogleApiSource\x12\x11OperationMetadata\xdaA-parent,google_api_source,google_api_source_id\x82\xd3\xe4\x93\x02I"4/v1/{parent=projects/*/locations/*}/googleApiSources:\x11google_api_source'
    _globals['_EVENTARC'].methods_by_name['UpdateGoogleApiSource']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['UpdateGoogleApiSource']._serialized_options = b'\xcaA$\n\x0fGoogleApiSource\x12\x11OperationMetadata\xdaA\x1dgoogle_api_source,update_mask\x82\xd3\xe4\x93\x02[2F/v1/{google_api_source.name=projects/*/locations/*/googleApiSources/*}:\x11google_api_source'
    _globals['_EVENTARC'].methods_by_name['DeleteGoogleApiSource']._loaded_options = None
    _globals['_EVENTARC'].methods_by_name['DeleteGoogleApiSource']._serialized_options = b'\xcaA$\n\x0fGoogleApiSource\x12\x11OperationMetadata\xdaA\tname,etag\x82\xd3\xe4\x93\x026*4/v1/{name=projects/*/locations/*/googleApiSources/*}'
    _globals['_GETTRIGGERREQUEST']._serialized_start = 693
    _globals['_GETTRIGGERREQUEST']._serialized_end = 767
    _globals['_LISTTRIGGERSREQUEST']._serialized_start = 770
    _globals['_LISTTRIGGERSREQUEST']._serialized_end = 921
    _globals['_LISTTRIGGERSRESPONSE']._serialized_start = 923
    _globals['_LISTTRIGGERSRESPONSE']._serialized_end = 1044
    _globals['_CREATETRIGGERREQUEST']._serialized_start = 1047
    _globals['_CREATETRIGGERREQUEST']._serialized_end = 1236
    _globals['_UPDATETRIGGERREQUEST']._serialized_start = 1239
    _globals['_UPDATETRIGGERREQUEST']._serialized_end = 1413
    _globals['_DELETETRIGGERREQUEST']._serialized_start = 1416
    _globals['_DELETETRIGGERREQUEST']._serialized_end = 1558
    _globals['_GETCHANNELREQUEST']._serialized_start = 1560
    _globals['_GETCHANNELREQUEST']._serialized_end = 1634
    _globals['_LISTCHANNELSREQUEST']._serialized_start = 1637
    _globals['_LISTCHANNELSREQUEST']._serialized_end = 1772
    _globals['_LISTCHANNELSRESPONSE']._serialized_start = 1774
    _globals['_LISTCHANNELSRESPONSE']._serialized_end = 1895
    _globals['_CREATECHANNELREQUEST']._serialized_start = 1898
    _globals['_CREATECHANNELREQUEST']._serialized_end = 2087
    _globals['_UPDATECHANNELREQUEST']._serialized_start = 2090
    _globals['_UPDATECHANNELREQUEST']._serialized_end = 2241
    _globals['_DELETECHANNELREQUEST']._serialized_start = 2243
    _globals['_DELETECHANNELREQUEST']._serialized_end = 2348
    _globals['_GETPROVIDERREQUEST']._serialized_start = 2350
    _globals['_GETPROVIDERREQUEST']._serialized_end = 2426
    _globals['_LISTPROVIDERSREQUEST']._serialized_start = 2429
    _globals['_LISTPROVIDERSREQUEST']._serialized_end = 2582
    _globals['_LISTPROVIDERSRESPONSE']._serialized_start = 2584
    _globals['_LISTPROVIDERSRESPONSE']._serialized_end = 2708
    _globals['_GETCHANNELCONNECTIONREQUEST']._serialized_start = 2710
    _globals['_GETCHANNELCONNECTIONREQUEST']._serialized_end = 2804
    _globals['_LISTCHANNELCONNECTIONSREQUEST']._serialized_start = 2807
    _globals['_LISTCHANNELCONNECTIONSREQUEST']._serialized_end = 2944
    _globals['_LISTCHANNELCONNECTIONSRESPONSE']._serialized_start = 2947
    _globals['_LISTCHANNELCONNECTIONSRESPONSE']._serialized_end = 3099
    _globals['_CREATECHANNELCONNECTIONREQUEST']._serialized_start = 3102
    _globals['_CREATECHANNELCONNECTIONREQUEST']._serialized_end = 3315
    _globals['_DELETECHANNELCONNECTIONREQUEST']._serialized_start = 3317
    _globals['_DELETECHANNELCONNECTIONREQUEST']._serialized_end = 3414
    _globals['_UPDATEGOOGLECHANNELCONFIGREQUEST']._serialized_start = 3417
    _globals['_UPDATEGOOGLECHANNELCONFIGREQUEST']._serialized_end = 3583
    _globals['_GETGOOGLECHANNELCONFIGREQUEST']._serialized_start = 3585
    _globals['_GETGOOGLECHANNELCONFIGREQUEST']._serialized_end = 3683
    _globals['_GETMESSAGEBUSREQUEST']._serialized_start = 3685
    _globals['_GETMESSAGEBUSREQUEST']._serialized_end = 3765
    _globals['_LISTMESSAGEBUSESREQUEST']._serialized_start = 3768
    _globals['_LISTMESSAGEBUSESREQUEST']._serialized_end = 3946
    _globals['_LISTMESSAGEBUSESRESPONSE']._serialized_start = 3949
    _globals['_LISTMESSAGEBUSESRESPONSE']._serialized_end = 4082
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST']._serialized_start = 4085
    _globals['_LISTMESSAGEBUSENROLLMENTSREQUEST']._serialized_end = 4228
    _globals['_LISTMESSAGEBUSENROLLMENTSRESPONSE']._serialized_start = 4230
    _globals['_LISTMESSAGEBUSENROLLMENTSRESPONSE']._serialized_end = 4332
    _globals['_CREATEMESSAGEBUSREQUEST']._serialized_start = 4335
    _globals['_CREATEMESSAGEBUSREQUEST']._serialized_end = 4541
    _globals['_UPDATEMESSAGEBUSREQUEST']._serialized_start = 4544
    _globals['_UPDATEMESSAGEBUSREQUEST']._serialized_end = 4743
    _globals['_DELETEMESSAGEBUSREQUEST']._serialized_start = 4746
    _globals['_DELETEMESSAGEBUSREQUEST']._serialized_end = 4904
    _globals['_GETENROLLMENTREQUEST']._serialized_start = 4906
    _globals['_GETENROLLMENTREQUEST']._serialized_end = 4986
    _globals['_LISTENROLLMENTSREQUEST']._serialized_start = 4989
    _globals['_LISTENROLLMENTSREQUEST']._serialized_end = 5166
    _globals['_LISTENROLLMENTSRESPONSE']._serialized_start = 5169
    _globals['_LISTENROLLMENTSRESPONSE']._serialized_end = 5299
    _globals['_CREATEENROLLMENTREQUEST']._serialized_start = 5302
    _globals['_CREATEENROLLMENTREQUEST']._serialized_end = 5506
    _globals['_UPDATEENROLLMENTREQUEST']._serialized_start = 5509
    _globals['_UPDATEENROLLMENTREQUEST']._serialized_end = 5707
    _globals['_DELETEENROLLMENTREQUEST']._serialized_start = 5710
    _globals['_DELETEENROLLMENTREQUEST']._serialized_end = 5868
    _globals['_GETPIPELINEREQUEST']._serialized_start = 5870
    _globals['_GETPIPELINEREQUEST']._serialized_end = 5946
    _globals['_LISTPIPELINESREQUEST']._serialized_start = 5949
    _globals['_LISTPIPELINESREQUEST']._serialized_end = 6122
    _globals['_LISTPIPELINESRESPONSE']._serialized_start = 6124
    _globals['_LISTPIPELINESRESPONSE']._serialized_end = 6248
    _globals['_CREATEPIPELINEREQUEST']._serialized_start = 6251
    _globals['_CREATEPIPELINEREQUEST']._serialized_end = 6445
    _globals['_UPDATEPIPELINEREQUEST']._serialized_start = 6448
    _globals['_UPDATEPIPELINEREQUEST']._serialized_end = 6640
    _globals['_DELETEPIPELINEREQUEST']._serialized_start = 6643
    _globals['_DELETEPIPELINEREQUEST']._serialized_end = 6797
    _globals['_GETGOOGLEAPISOURCEREQUEST']._serialized_start = 6799
    _globals['_GETGOOGLEAPISOURCEREQUEST']._serialized_end = 6889
    _globals['_LISTGOOGLEAPISOURCESREQUEST']._serialized_start = 6892
    _globals['_LISTGOOGLEAPISOURCESREQUEST']._serialized_end = 7079
    _globals['_LISTGOOGLEAPISOURCESRESPONSE']._serialized_start = 7082
    _globals['_LISTGOOGLEAPISOURCESRESPONSE']._serialized_end = 7229
    _globals['_CREATEGOOGLEAPISOURCEREQUEST']._serialized_start = 7232
    _globals['_CREATEGOOGLEAPISOURCEREQUEST']._serialized_end = 7465
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST']._serialized_start = 7468
    _globals['_UPDATEGOOGLEAPISOURCEREQUEST']._serialized_end = 7683
    _globals['_DELETEGOOGLEAPISOURCEREQUEST']._serialized_start = 7686
    _globals['_DELETEGOOGLEAPISOURCEREQUEST']._serialized_end = 7854
    _globals['_OPERATIONMETADATA']._serialized_start = 7857
    _globals['_OPERATIONMETADATA']._serialized_end = 8113
    _globals['_EVENTARC']._serialized_start = 8116
    _globals['_EVENTARC']._serialized_end = 16425