"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/spanner/admin/instance/v1/spanner_instance_admin.proto')
_sym_db = _symbol_database.Default()
from ......google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from ......google.api import client_pb2 as google_dot_api_dot_client__pb2
from ......google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from ......google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from ......google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from ......google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from ......google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ......google.spanner.admin.instance.v1 import common_pb2 as google_dot_spanner_dot_admin_dot_instance_dot_v1_dot_common__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=google/spanner/admin/instance/v1/spanner_instance_admin.proto\x12 google.spanner.admin.instance.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a-google/spanner/admin/instance/v1/common.proto"\xda\x01\n\x0bReplicaInfo\x12\x10\n\x08location\x18\x01 \x01(\t\x12G\n\x04type\x18\x02 \x01(\x0e29.google.spanner.admin.instance.v1.ReplicaInfo.ReplicaType\x12\x1f\n\x17default_leader_location\x18\x03 \x01(\x08"O\n\x0bReplicaType\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nREAD_WRITE\x10\x01\x12\r\n\tREAD_ONLY\x10\x02\x12\x0b\n\x07WITNESS\x10\x03"\xc0\n\n\x0eInstanceConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cdisplay_name\x18\x02 \x01(\t\x12O\n\x0bconfig_type\x18\x05 \x01(\x0e25.google.spanner.admin.instance.v1.InstanceConfig.TypeB\x03\xe0A\x03\x12?\n\x08replicas\x18\x03 \x03(\x0b2-.google.spanner.admin.instance.v1.ReplicaInfo\x12M\n\x11optional_replicas\x18\x06 \x03(\x0b2-.google.spanner.admin.instance.v1.ReplicaInfoB\x03\xe0A\x03\x12?\n\x0bbase_config\x18\x07 \x01(\tB*\xfaA\'\n%spanner.googleapis.com/InstanceConfig\x12L\n\x06labels\x18\x08 \x03(\x0b2<.google.spanner.admin.instance.v1.InstanceConfig.LabelsEntry\x12\x0c\n\x04etag\x18\t \x01(\t\x12\x16\n\x0eleader_options\x18\x04 \x03(\t\x12\x18\n\x0breconciling\x18\n \x01(\x08B\x03\xe0A\x03\x12J\n\x05state\x18\x0b \x01(\x0e26.google.spanner.admin.instance.v1.InstanceConfig.StateB\x03\xe0A\x03\x12r\n\x1afree_instance_availability\x18\x0c \x01(\x0e2I.google.spanner.admin.instance.v1.InstanceConfig.FreeInstanceAvailabilityB\x03\xe0A\x03\x12U\n\x0bquorum_type\x18\x12 \x01(\x0e2;.google.spanner.admin.instance.v1.InstanceConfig.QuorumTypeB\x03\xe0A\x03\x12.\n!storage_limit_per_processing_unit\x18\x13 \x01(\x03B\x03\xe0A\x03\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"B\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eGOOGLE_MANAGED\x10\x01\x12\x10\n\x0cUSER_MANAGED\x10\x02"7\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02"\x88\x01\n\x18FreeInstanceAvailability\x12*\n&FREE_INSTANCE_AVAILABILITY_UNSPECIFIED\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\x0f\n\x0bUNSUPPORTED\x10\x02\x12\x0c\n\x08DISABLED\x10\x03\x12\x12\n\x0eQUOTA_EXCEEDED\x10\x04"X\n\nQuorumType\x12\x1b\n\x17QUORUM_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06REGION\x10\x01\x12\x0f\n\x0bDUAL_REGION\x10\x02\x12\x10\n\x0cMULTI_REGION\x10\x03:\x81\x01\xeaA~\n%spanner.googleapis.com/InstanceConfig\x124projects/{project}/instanceConfigs/{instance_config}*\x0finstanceConfigs2\x0einstanceConfig"\xb2\x01\n\x16ReplicaComputeCapacity\x12R\n\x11replica_selection\x18\x01 \x01(\x0b22.google.spanner.admin.instance.v1.ReplicaSelectionB\x03\xe0A\x02\x12\x14\n\nnode_count\x18\x02 \x01(\x05H\x00\x12\x1a\n\x10processing_units\x18\x03 \x01(\x05H\x00B\x12\n\x10compute_capacity"\xb8\x08\n\x11AutoscalingConfig\x12f\n\x12autoscaling_limits\x18\x01 \x01(\x0b2E.google.spanner.admin.instance.v1.AutoscalingConfig.AutoscalingLimitsB\x03\xe0A\x02\x12h\n\x13autoscaling_targets\x18\x02 \x01(\x0b2F.google.spanner.admin.instance.v1.AutoscalingConfig.AutoscalingTargetsB\x03\xe0A\x02\x12|\n\x1easymmetric_autoscaling_options\x18\x03 \x03(\x0b2O.google.spanner.admin.instance.v1.AutoscalingConfig.AsymmetricAutoscalingOptionB\x03\xe0A\x01\x1a\x97\x01\n\x11AutoscalingLimits\x12\x13\n\tmin_nodes\x18\x01 \x01(\x05H\x00\x12\x1e\n\x14min_processing_units\x18\x02 \x01(\x05H\x00\x12\x13\n\tmax_nodes\x18\x03 \x01(\x05H\x01\x12\x1e\n\x14max_processing_units\x18\x04 \x01(\x05H\x01B\x0b\n\tmin_limitB\x0b\n\tmax_limit\x1ar\n\x12AutoscalingTargets\x122\n%high_priority_cpu_utilization_percent\x18\x01 \x01(\x05B\x03\xe0A\x02\x12(\n\x1bstorage_utilization_percent\x18\x02 \x01(\x05B\x03\xe0A\x02\x1a\xc4\x03\n\x1bAsymmetricAutoscalingOption\x12R\n\x11replica_selection\x18\x01 \x01(\x0b22.google.spanner.admin.instance.v1.ReplicaSelectionB\x03\xe0A\x02\x12\x82\x01\n\toverrides\x18\x02 \x01(\x0b2j.google.spanner.admin.instance.v1.AutoscalingConfig.AsymmetricAutoscalingOption.AutoscalingConfigOverridesB\x03\xe0A\x01\x1a\xcb\x01\n\x1aAutoscalingConfigOverrides\x12f\n\x12autoscaling_limits\x18\x01 \x01(\x0b2E.google.spanner.admin.instance.v1.AutoscalingConfig.AutoscalingLimitsB\x03\xe0A\x01\x12E\n8autoscaling_target_high_priority_cpu_utilization_percent\x18\x02 \x01(\x05B\x03\xe0A\x01"\xaa\x0b\n\x08Instance\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12=\n\x06config\x18\x02 \x01(\tB-\xe0A\x02\xfaA\'\n%spanner.googleapis.com/InstanceConfig\x12\x19\n\x0cdisplay_name\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x12\n\nnode_count\x18\x05 \x01(\x05\x12\x18\n\x10processing_units\x18\t \x01(\x05\x12_\n\x18replica_compute_capacity\x18\x13 \x03(\x0b28.google.spanner.admin.instance.v1.ReplicaComputeCapacityB\x03\xe0A\x03\x12T\n\x12autoscaling_config\x18\x11 \x01(\x0b23.google.spanner.admin.instance.v1.AutoscalingConfigB\x03\xe0A\x01\x12D\n\x05state\x18\x06 \x01(\x0e20.google.spanner.admin.instance.v1.Instance.StateB\x03\xe0A\x03\x12F\n\x06labels\x18\x07 \x03(\x0b26.google.spanner.admin.instance.v1.Instance.LabelsEntry\x12N\n\rinstance_type\x18\n \x01(\x0e27.google.spanner.admin.instance.v1.Instance.InstanceType\x12\x15\n\rendpoint_uris\x18\x08 \x03(\t\x124\n\x0bcreate_time\x18\x0b \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x0c \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12V\n\x16free_instance_metadata\x18\r \x01(\x0b26.google.spanner.admin.instance.v1.FreeInstanceMetadata\x12H\n\x07edition\x18\x14 \x01(\x0e22.google.spanner.admin.instance.v1.Instance.EditionB\x03\xe0A\x01\x12o\n\x1cdefault_backup_schedule_type\x18\x17 \x01(\x0e2D.google.spanner.admin.instance.v1.Instance.DefaultBackupScheduleTypeB\x03\xe0A\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"7\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02"Q\n\x0cInstanceType\x12\x1d\n\x19INSTANCE_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bPROVISIONED\x10\x01\x12\x11\n\rFREE_INSTANCE\x10\x02"U\n\x07Edition\x12\x17\n\x13EDITION_UNSPECIFIED\x10\x00\x12\x0c\n\x08STANDARD\x10\x01\x12\x0e\n\nENTERPRISE\x10\x02\x12\x13\n\x0fENTERPRISE_PLUS\x10\x03"b\n\x19DefaultBackupScheduleType\x12,\n(DEFAULT_BACKUP_SCHEDULE_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04NONE\x10\x01\x12\r\n\tAUTOMATIC\x10\x02:b\xeaA_\n\x1fspanner.googleapis.com/Instance\x12\'projects/{project}/instances/{instance}*\tinstances2\x08instance"\x88\x01\n\x1aListInstanceConfigsRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"\x82\x01\n\x1bListInstanceConfigsResponse\x12J\n\x10instance_configs\x18\x01 \x03(\x0b20.google.spanner.admin.instance.v1.InstanceConfig\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"W\n\x18GetInstanceConfigRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%spanner.googleapis.com/InstanceConfig"\xea\x01\n\x1bCreateInstanceConfigRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12\x1f\n\x12instance_config_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12N\n\x0finstance_config\x18\x03 \x01(\x0b20.google.spanner.admin.instance.v1.InstanceConfigB\x03\xe0A\x02\x12\x15\n\rvalidate_only\x18\x04 \x01(\x08"\xba\x01\n\x1bUpdateInstanceConfigRequest\x12N\n\x0finstance_config\x18\x01 \x01(\x0b20.google.spanner.admin.instance.v1.InstanceConfigB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x15\n\rvalidate_only\x18\x03 \x01(\x08"\x7f\n\x1bDeleteInstanceConfigRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%spanner.googleapis.com/InstanceConfig\x12\x0c\n\x04etag\x18\x02 \x01(\t\x12\x15\n\rvalidate_only\x18\x03 \x01(\x08"\xa1\x01\n#ListInstanceConfigOperationsRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12\x0e\n\x06filter\x18\x02 \x01(\t\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x12\n\npage_token\x18\x04 \x01(\t"r\n$ListInstanceConfigOperationsResponse\x121\n\noperations\x18\x01 \x03(\x0b2\x1d.google.longrunning.Operation\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"{\n\x12GetInstanceRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance\x12.\n\nfield_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"\xb9\x01\n\x15CreateInstanceRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12\x18\n\x0binstance_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12A\n\x08instance\x18\x03 \x01(\x0b2*.google.spanner.admin.instance.v1.InstanceB\x03\xe0A\x02"\xc9\x01\n\x14ListInstancesRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x125\n\x11instance_deadline\x18\x05 \x01(\x0b2\x1a.google.protobuf.Timestamp"\x84\x01\n\x15ListInstancesResponse\x12=\n\tinstances\x18\x01 \x03(\x0b2*.google.spanner.admin.instance.v1.Instance\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\x8f\x01\n\x15UpdateInstanceRequest\x12A\n\x08instance\x18\x01 \x01(\x0b2*.google.spanner.admin.instance.v1.InstanceB\x03\xe0A\x02\x123\n\nfield_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"N\n\x15DeleteInstanceRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance"\xbf\x02\n\x16CreateInstanceMetadata\x12<\n\x08instance\x18\x01 \x01(\x0b2*.google.spanner.admin.instance.v1.Instance\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bcancel_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12X\n\x1bexpected_fulfillment_period\x18\x05 \x01(\x0e23.google.spanner.admin.instance.v1.FulfillmentPeriod"\xbf\x02\n\x16UpdateInstanceMetadata\x12<\n\x08instance\x18\x01 \x01(\x0b2*.google.spanner.admin.instance.v1.Instance\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bcancel_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12X\n\x1bexpected_fulfillment_period\x18\x05 \x01(\x0e23.google.spanner.admin.instance.v1.FulfillmentPeriod"\xce\x02\n\x14FreeInstanceMetadata\x124\n\x0bexpire_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x125\n\x0cupgrade_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12^\n\x0fexpire_behavior\x18\x03 \x01(\x0e2E.google.spanner.admin.instance.v1.FreeInstanceMetadata.ExpireBehavior"i\n\x0eExpireBehavior\x12\x1f\n\x1bEXPIRE_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x17\n\x13FREE_TO_PROVISIONED\x10\x01\x12\x1d\n\x19REMOVE_AFTER_GRACE_PERIOD\x10\x02"\xe1\x01\n\x1cCreateInstanceConfigMetadata\x12I\n\x0finstance_config\x18\x01 \x01(\x0b20.google.spanner.admin.instance.v1.InstanceConfig\x12E\n\x08progress\x18\x02 \x01(\x0b23.google.spanner.admin.instance.v1.OperationProgress\x12/\n\x0bcancel_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xe1\x01\n\x1cUpdateInstanceConfigMetadata\x12I\n\x0finstance_config\x18\x01 \x01(\x0b20.google.spanner.admin.instance.v1.InstanceConfig\x12E\n\x08progress\x18\x02 \x01(\x0b23.google.spanner.admin.instance.v1.OperationProgress\x12/\n\x0bcancel_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xb9\x05\n\x11InstancePartition\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12=\n\x06config\x18\x02 \x01(\tB-\xe0A\x02\xfaA\'\n%spanner.googleapis.com/InstanceConfig\x12\x19\n\x0cdisplay_name\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x14\n\nnode_count\x18\x05 \x01(\x05H\x00\x12\x1a\n\x10processing_units\x18\x06 \x01(\x05H\x00\x12M\n\x05state\x18\x07 \x01(\x0e29.google.spanner.admin.instance.v1.InstancePartition.StateB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x08 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\t \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12"\n\x15referencing_databases\x18\n \x03(\tB\x03\xe0A\x03\x12"\n\x13referencing_backups\x18\x0b \x03(\tB\x05\x18\x01\xe0A\x03\x12\x0c\n\x04etag\x18\x0c \x01(\t"7\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02:\xa6\x01\xeaA\xa2\x01\n(spanner.googleapis.com/InstancePartition\x12Oprojects/{project}/instances/{instance}/instancePartitions/{instance_partition}*\x12instancePartitions2\x11instancePartitionB\x12\n\x10compute_capacity"\x81\x02\n\x1fCreateInstancePartitionMetadata\x12O\n\x12instance_partition\x18\x01 \x01(\x0b23.google.spanner.admin.instance.v1.InstancePartition\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bcancel_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xd3\x01\n\x1eCreateInstancePartitionRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance\x12"\n\x15instance_partition_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12T\n\x12instance_partition\x18\x03 \x01(\x0b23.google.spanner.admin.instance.v1.InstancePartitionB\x03\xe0A\x02"n\n\x1eDeleteInstancePartitionRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(spanner.googleapis.com/InstancePartition\x12\x0c\n\x04etag\x18\x02 \x01(\t"]\n\x1bGetInstancePartitionRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(spanner.googleapis.com/InstancePartition"\xab\x01\n\x1eUpdateInstancePartitionRequest\x12T\n\x12instance_partition\x18\x01 \x01(\x0b23.google.spanner.admin.instance.v1.InstancePartitionB\x03\xe0A\x02\x123\n\nfield_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\x81\x02\n\x1fUpdateInstancePartitionMetadata\x12O\n\x12instance_partition\x18\x01 \x01(\x0b23.google.spanner.admin.instance.v1.InstancePartition\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bcancel_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xc5\x01\n\x1dListInstancePartitionsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12D\n\x1binstance_partition_deadline\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x01"\xa0\x01\n\x1eListInstancePartitionsResponse\x12P\n\x13instance_partitions\x18\x01 \x03(\x0b23.google.spanner.admin.instance.v1.InstancePartition\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xed\x01\n&ListInstancePartitionOperationsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance\x12\x13\n\x06filter\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x16\n\tpage_size\x18\x03 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x04 \x01(\tB\x03\xe0A\x01\x12D\n\x1binstance_partition_deadline\x18\x05 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x01"\x9e\x01\n\'ListInstancePartitionOperationsResponse\x121\n\noperations\x18\x01 \x03(\x0b2\x1d.google.longrunning.Operation\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\'\n\x1funreachable_instance_partitions\x18\x03 \x03(\t"\x92\x01\n\x13MoveInstanceRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance\x12D\n\rtarget_config\x18\x02 \x01(\tB-\xe0A\x02\xfaA\'\n%spanner.googleapis.com/InstanceConfig"\x16\n\x14MoveInstanceResponse"\xa5\x01\n\x14MoveInstanceMetadata\x12\x15\n\rtarget_config\x18\x01 \x01(\t\x12E\n\x08progress\x18\x02 \x01(\x0b23.google.spanner.admin.instance.v1.OperationProgress\x12/\n\x0bcancel_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp2\xda\'\n\rInstanceAdmin\x12\xcc\x01\n\x13ListInstanceConfigs\x12<.google.spanner.admin.instance.v1.ListInstanceConfigsRequest\x1a=.google.spanner.admin.instance.v1.ListInstanceConfigsResponse"8\xdaA\x06parent\x82\xd3\xe4\x93\x02)\x12\'/v1/{parent=projects/*}/instanceConfigs\x12\xb9\x01\n\x11GetInstanceConfig\x12:.google.spanner.admin.instance.v1.GetInstanceConfigRequest\x1a0.google.spanner.admin.instance.v1.InstanceConfig"6\xdaA\x04name\x82\xd3\xe4\x93\x02)\x12\'/v1/{name=projects/*/instanceConfigs/*}\x12\xc8\x02\n\x14CreateInstanceConfig\x12=.google.spanner.admin.instance.v1.CreateInstanceConfigRequest\x1a\x1d.google.longrunning.Operation"\xd1\x01\xcaAp\n/google.spanner.admin.instance.v1.InstanceConfig\x12=google.spanner.admin.instance.v1.CreateInstanceConfigMetadata\xdaA)parent,instance_config,instance_config_id\x82\xd3\xe4\x93\x02,"\'/v1/{parent=projects/*}/instanceConfigs:\x01*\x12\xca\x02\n\x14UpdateInstanceConfig\x12=.google.spanner.admin.instance.v1.UpdateInstanceConfigRequest\x1a\x1d.google.longrunning.Operation"\xd3\x01\xcaAp\n/google.spanner.admin.instance.v1.InstanceConfig\x12=google.spanner.admin.instance.v1.UpdateInstanceConfigMetadata\xdaA\x1binstance_config,update_mask\x82\xd3\xe4\x93\x02<27/v1/{instance_config.name=projects/*/instanceConfigs/*}:\x01*\x12\xa5\x01\n\x14DeleteInstanceConfig\x12=.google.spanner.admin.instance.v1.DeleteInstanceConfigRequest\x1a\x16.google.protobuf.Empty"6\xdaA\x04name\x82\xd3\xe4\x93\x02)*\'/v1/{name=projects/*/instanceConfigs/*}\x12\xf0\x01\n\x1cListInstanceConfigOperations\x12E.google.spanner.admin.instance.v1.ListInstanceConfigOperationsRequest\x1aF.google.spanner.admin.instance.v1.ListInstanceConfigOperationsResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*}/instanceConfigOperations\x12\xb4\x01\n\rListInstances\x126.google.spanner.admin.instance.v1.ListInstancesRequest\x1a7.google.spanner.admin.instance.v1.ListInstancesResponse"2\xdaA\x06parent\x82\xd3\xe4\x93\x02#\x12!/v1/{parent=projects/*}/instances\x12\xe4\x01\n\x16ListInstancePartitions\x12?.google.spanner.admin.instance.v1.ListInstancePartitionsRequest\x1a@.google.spanner.admin.instance.v1.ListInstancePartitionsResponse"G\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/instances/*}/instancePartitions\x12\xa1\x01\n\x0bGetInstance\x124.google.spanner.admin.instance.v1.GetInstanceRequest\x1a*.google.spanner.admin.instance.v1.Instance"0\xdaA\x04name\x82\xd3\xe4\x93\x02#\x12!/v1/{name=projects/*/instances/*}\x12\x9c\x02\n\x0eCreateInstance\x127.google.spanner.admin.instance.v1.CreateInstanceRequest\x1a\x1d.google.longrunning.Operation"\xb1\x01\xcaAd\n)google.spanner.admin.instance.v1.Instance\x127google.spanner.admin.instance.v1.CreateInstanceMetadata\xdaA\x1bparent,instance_id,instance\x82\xd3\xe4\x93\x02&"!/v1/{parent=projects/*}/instances:\x01*\x12\x9d\x02\n\x0eUpdateInstance\x127.google.spanner.admin.instance.v1.UpdateInstanceRequest\x1a\x1d.google.longrunning.Operation"\xb2\x01\xcaAd\n)google.spanner.admin.instance.v1.Instance\x127google.spanner.admin.instance.v1.UpdateInstanceMetadata\xdaA\x13instance,field_mask\x82\xd3\xe4\x93\x02/2*/v1/{instance.name=projects/*/instances/*}:\x01*\x12\x93\x01\n\x0eDeleteInstance\x127.google.spanner.admin.instance.v1.DeleteInstanceRequest\x1a\x16.google.protobuf.Empty"0\xdaA\x04name\x82\xd3\xe4\x93\x02#*!/v1/{name=projects/*/instances/*}\x12\x9a\x01\n\x0cSetIamPolicy\x12".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"O\xdaA\x0fresource,policy\x82\xd3\xe4\x93\x027"2/v1/{resource=projects/*/instances/*}:setIamPolicy:\x01*\x12\x93\x01\n\x0cGetIamPolicy\x12".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"H\xdaA\x08resource\x82\xd3\xe4\x93\x027"2/v1/{resource=projects/*/instances/*}:getIamPolicy:\x01*\x12\xc5\x01\n\x12TestIamPermissions\x12(.google.iam.v1.TestIamPermissionsRequest\x1a).google.iam.v1.TestIamPermissionsResponse"Z\xdaA\x14resource,permissions\x82\xd3\xe4\x93\x02="8/v1/{resource=projects/*/instances/*}:testIamPermissions:\x01*\x12\xd1\x01\n\x14GetInstancePartition\x12=.google.spanner.admin.instance.v1.GetInstancePartitionRequest\x1a3.google.spanner.admin.instance.v1.InstancePartition"E\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/instances/*/instancePartitions/*}\x12\xe9\x02\n\x17CreateInstancePartition\x12@.google.spanner.admin.instance.v1.CreateInstancePartitionRequest\x1a\x1d.google.longrunning.Operation"\xec\x01\xcaAv\n2google.spanner.admin.instance.v1.InstancePartition\x12@google.spanner.admin.instance.v1.CreateInstancePartitionMetadata\xdaA/parent,instance_partition,instance_partition_id\x82\xd3\xe4\x93\x02;"6/v1/{parent=projects/*/instances/*}/instancePartitions:\x01*\x12\xba\x01\n\x17DeleteInstancePartition\x12@.google.spanner.admin.instance.v1.DeleteInstancePartitionRequest\x1a\x16.google.protobuf.Empty"E\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/instances/*/instancePartitions/*}\x12\xea\x02\n\x17UpdateInstancePartition\x12@.google.spanner.admin.instance.v1.UpdateInstancePartitionRequest\x1a\x1d.google.longrunning.Operation"\xed\x01\xcaAv\n2google.spanner.admin.instance.v1.InstancePartition\x12@google.spanner.admin.instance.v1.UpdateInstancePartitionMetadata\xdaA\x1dinstance_partition,field_mask\x82\xd3\xe4\x93\x02N2I/v1/{instance_partition.name=projects/*/instances/*/instancePartitions/*}:\x01*\x12\x88\x02\n\x1fListInstancePartitionOperations\x12H.google.spanner.admin.instance.v1.ListInstancePartitionOperationsRequest\x1aI.google.spanner.admin.instance.v1.ListInstancePartitionOperationsResponse"P\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/instances/*}/instancePartitionOperations\x12\x89\x02\n\x0cMoveInstance\x125.google.spanner.admin.instance.v1.MoveInstanceRequest\x1a\x1d.google.longrunning.Operation"\xa2\x01\xcaAn\n5google.spanner.admin.instance.v1.MoveInstanceResponse\x125google.spanner.admin.instance.v1.MoveInstanceMetadata\x82\xd3\xe4\x93\x02+"&/v1/{name=projects/*/instances/*}:move:\x01*\x1ax\xcaA\x16spanner.googleapis.com\xd2A\\https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/spanner.adminB\x8b\x02\n$com.google.spanner.admin.instance.v1B\x19SpannerInstanceAdminProtoP\x01ZFcloud.google.com/go/spanner/admin/instance/apiv1/instancepb;instancepb\xaa\x02&Google.Cloud.Spanner.Admin.Instance.V1\xca\x02&Google\\Cloud\\Spanner\\Admin\\Instance\\V1\xea\x02+Google::Cloud::Spanner::Admin::Instance::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.spanner.admin.instance.v1.spanner_instance_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n$com.google.spanner.admin.instance.v1B\x19SpannerInstanceAdminProtoP\x01ZFcloud.google.com/go/spanner/admin/instance/apiv1/instancepb;instancepb\xaa\x02&Google.Cloud.Spanner.Admin.Instance.V1\xca\x02&Google\\Cloud\\Spanner\\Admin\\Instance\\V1\xea\x02+Google::Cloud::Spanner::Admin::Instance::V1'
    _globals['_INSTANCECONFIG_LABELSENTRY']._loaded_options = None
    _globals['_INSTANCECONFIG_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_INSTANCECONFIG'].fields_by_name['config_type']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['config_type']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCECONFIG'].fields_by_name['optional_replicas']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['optional_replicas']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCECONFIG'].fields_by_name['base_config']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['base_config']._serialized_options = b"\xfaA'\n%spanner.googleapis.com/InstanceConfig"
    _globals['_INSTANCECONFIG'].fields_by_name['reconciling']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['reconciling']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCECONFIG'].fields_by_name['state']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCECONFIG'].fields_by_name['free_instance_availability']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['free_instance_availability']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCECONFIG'].fields_by_name['quorum_type']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['quorum_type']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCECONFIG'].fields_by_name['storage_limit_per_processing_unit']._loaded_options = None
    _globals['_INSTANCECONFIG'].fields_by_name['storage_limit_per_processing_unit']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCECONFIG']._loaded_options = None
    _globals['_INSTANCECONFIG']._serialized_options = b'\xeaA~\n%spanner.googleapis.com/InstanceConfig\x124projects/{project}/instanceConfigs/{instance_config}*\x0finstanceConfigs2\x0einstanceConfig'
    _globals['_REPLICACOMPUTECAPACITY'].fields_by_name['replica_selection']._loaded_options = None
    _globals['_REPLICACOMPUTECAPACITY'].fields_by_name['replica_selection']._serialized_options = b'\xe0A\x02'
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGTARGETS'].fields_by_name['high_priority_cpu_utilization_percent']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGTARGETS'].fields_by_name['high_priority_cpu_utilization_percent']._serialized_options = b'\xe0A\x02'
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGTARGETS'].fields_by_name['storage_utilization_percent']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGTARGETS'].fields_by_name['storage_utilization_percent']._serialized_options = b'\xe0A\x02'
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION_AUTOSCALINGCONFIGOVERRIDES'].fields_by_name['autoscaling_limits']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION_AUTOSCALINGCONFIGOVERRIDES'].fields_by_name['autoscaling_limits']._serialized_options = b'\xe0A\x01'
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION_AUTOSCALINGCONFIGOVERRIDES'].fields_by_name['autoscaling_target_high_priority_cpu_utilization_percent']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION_AUTOSCALINGCONFIGOVERRIDES'].fields_by_name['autoscaling_target_high_priority_cpu_utilization_percent']._serialized_options = b'\xe0A\x01'
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION'].fields_by_name['replica_selection']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION'].fields_by_name['replica_selection']._serialized_options = b'\xe0A\x02'
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION'].fields_by_name['overrides']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION'].fields_by_name['overrides']._serialized_options = b'\xe0A\x01'
    _globals['_AUTOSCALINGCONFIG'].fields_by_name['autoscaling_limits']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG'].fields_by_name['autoscaling_limits']._serialized_options = b'\xe0A\x02'
    _globals['_AUTOSCALINGCONFIG'].fields_by_name['autoscaling_targets']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG'].fields_by_name['autoscaling_targets']._serialized_options = b'\xe0A\x02'
    _globals['_AUTOSCALINGCONFIG'].fields_by_name['asymmetric_autoscaling_options']._loaded_options = None
    _globals['_AUTOSCALINGCONFIG'].fields_by_name['asymmetric_autoscaling_options']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE_LABELSENTRY']._loaded_options = None
    _globals['_INSTANCE_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_INSTANCE'].fields_by_name['name']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_INSTANCE'].fields_by_name['config']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['config']._serialized_options = b"\xe0A\x02\xfaA'\n%spanner.googleapis.com/InstanceConfig"
    _globals['_INSTANCE'].fields_by_name['display_name']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['display_name']._serialized_options = b'\xe0A\x02'
    _globals['_INSTANCE'].fields_by_name['replica_compute_capacity']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['replica_compute_capacity']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['autoscaling_config']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['autoscaling_config']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['state']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['create_time']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['update_time']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['edition']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['edition']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['default_backup_schedule_type']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['default_backup_schedule_type']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE']._loaded_options = None
    _globals['_INSTANCE']._serialized_options = b"\xeaA_\n\x1fspanner.googleapis.com/Instance\x12'projects/{project}/instances/{instance}*\tinstances2\x08instance"
    _globals['_LISTINSTANCECONFIGSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCECONFIGSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_GETINSTANCECONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCECONFIGREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%spanner.googleapis.com/InstanceConfig"
    _globals['_CREATEINSTANCECONFIGREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCECONFIGREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_CREATEINSTANCECONFIGREQUEST'].fields_by_name['instance_config_id']._loaded_options = None
    _globals['_CREATEINSTANCECONFIGREQUEST'].fields_by_name['instance_config_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCECONFIGREQUEST'].fields_by_name['instance_config']._loaded_options = None
    _globals['_CREATEINSTANCECONFIGREQUEST'].fields_by_name['instance_config']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEINSTANCECONFIGREQUEST'].fields_by_name['instance_config']._loaded_options = None
    _globals['_UPDATEINSTANCECONFIGREQUEST'].fields_by_name['instance_config']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEINSTANCECONFIGREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEINSTANCECONFIGREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEINSTANCECONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCECONFIGREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%spanner.googleapis.com/InstanceConfig"
    _globals['_LISTINSTANCECONFIGOPERATIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCECONFIGOPERATIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['field_mask']._loaded_options = None
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['field_mask']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance'
    _globals['_FREEINSTANCEMETADATA'].fields_by_name['expire_time']._loaded_options = None
    _globals['_FREEINSTANCEMETADATA'].fields_by_name['expire_time']._serialized_options = b'\xe0A\x03'
    _globals['_FREEINSTANCEMETADATA'].fields_by_name['upgrade_time']._loaded_options = None
    _globals['_FREEINSTANCEMETADATA'].fields_by_name['upgrade_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCEPARTITION'].fields_by_name['name']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_INSTANCEPARTITION'].fields_by_name['config']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['config']._serialized_options = b"\xe0A\x02\xfaA'\n%spanner.googleapis.com/InstanceConfig"
    _globals['_INSTANCEPARTITION'].fields_by_name['display_name']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['display_name']._serialized_options = b'\xe0A\x02'
    _globals['_INSTANCEPARTITION'].fields_by_name['state']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCEPARTITION'].fields_by_name['create_time']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCEPARTITION'].fields_by_name['update_time']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCEPARTITION'].fields_by_name['referencing_databases']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['referencing_databases']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCEPARTITION'].fields_by_name['referencing_backups']._loaded_options = None
    _globals['_INSTANCEPARTITION'].fields_by_name['referencing_backups']._serialized_options = b'\x18\x01\xe0A\x03'
    _globals['_INSTANCEPARTITION']._loaded_options = None
    _globals['_INSTANCEPARTITION']._serialized_options = b'\xeaA\xa2\x01\n(spanner.googleapis.com/InstancePartition\x12Oprojects/{project}/instances/{instance}/instancePartitions/{instance_partition}*\x12instancePartitions2\x11instancePartition'
    _globals['_CREATEINSTANCEPARTITIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCEPARTITIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance'
    _globals['_CREATEINSTANCEPARTITIONREQUEST'].fields_by_name['instance_partition_id']._loaded_options = None
    _globals['_CREATEINSTANCEPARTITIONREQUEST'].fields_by_name['instance_partition_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEPARTITIONREQUEST'].fields_by_name['instance_partition']._loaded_options = None
    _globals['_CREATEINSTANCEPARTITIONREQUEST'].fields_by_name['instance_partition']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEINSTANCEPARTITIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCEPARTITIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(spanner.googleapis.com/InstancePartition'
    _globals['_GETINSTANCEPARTITIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEPARTITIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(spanner.googleapis.com/InstancePartition'
    _globals['_UPDATEINSTANCEPARTITIONREQUEST'].fields_by_name['instance_partition']._loaded_options = None
    _globals['_UPDATEINSTANCEPARTITIONREQUEST'].fields_by_name['instance_partition']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEINSTANCEPARTITIONREQUEST'].fields_by_name['field_mask']._loaded_options = None
    _globals['_UPDATEINSTANCEPARTITIONREQUEST'].fields_by_name['field_mask']._serialized_options = b'\xe0A\x02'
    _globals['_LISTINSTANCEPARTITIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCEPARTITIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance'
    _globals['_LISTINSTANCEPARTITIONSREQUEST'].fields_by_name['instance_partition_deadline']._loaded_options = None
    _globals['_LISTINSTANCEPARTITIONSREQUEST'].fields_by_name['instance_partition_deadline']._serialized_options = b'\xe0A\x01'
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance'
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['instance_partition_deadline']._loaded_options = None
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST'].fields_by_name['instance_partition_deadline']._serialized_options = b'\xe0A\x01'
    _globals['_MOVEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_MOVEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fspanner.googleapis.com/Instance'
    _globals['_MOVEINSTANCEREQUEST'].fields_by_name['target_config']._loaded_options = None
    _globals['_MOVEINSTANCEREQUEST'].fields_by_name['target_config']._serialized_options = b"\xe0A\x02\xfaA'\n%spanner.googleapis.com/InstanceConfig"
    _globals['_INSTANCEADMIN']._loaded_options = None
    _globals['_INSTANCEADMIN']._serialized_options = b'\xcaA\x16spanner.googleapis.com\xd2A\\https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/spanner.admin'
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstanceConfigs']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstanceConfigs']._serialized_options = b"\xdaA\x06parent\x82\xd3\xe4\x93\x02)\x12'/v1/{parent=projects/*}/instanceConfigs"
    _globals['_INSTANCEADMIN'].methods_by_name['GetInstanceConfig']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['GetInstanceConfig']._serialized_options = b"\xdaA\x04name\x82\xd3\xe4\x93\x02)\x12'/v1/{name=projects/*/instanceConfigs/*}"
    _globals['_INSTANCEADMIN'].methods_by_name['CreateInstanceConfig']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['CreateInstanceConfig']._serialized_options = b'\xcaAp\n/google.spanner.admin.instance.v1.InstanceConfig\x12=google.spanner.admin.instance.v1.CreateInstanceConfigMetadata\xdaA)parent,instance_config,instance_config_id\x82\xd3\xe4\x93\x02,"\'/v1/{parent=projects/*}/instanceConfigs:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['UpdateInstanceConfig']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['UpdateInstanceConfig']._serialized_options = b'\xcaAp\n/google.spanner.admin.instance.v1.InstanceConfig\x12=google.spanner.admin.instance.v1.UpdateInstanceConfigMetadata\xdaA\x1binstance_config,update_mask\x82\xd3\xe4\x93\x02<27/v1/{instance_config.name=projects/*/instanceConfigs/*}:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['DeleteInstanceConfig']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['DeleteInstanceConfig']._serialized_options = b"\xdaA\x04name\x82\xd3\xe4\x93\x02)*'/v1/{name=projects/*/instanceConfigs/*}"
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstanceConfigOperations']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstanceConfigOperations']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*}/instanceConfigOperations'
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstances']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstances']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02#\x12!/v1/{parent=projects/*}/instances'
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstancePartitions']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstancePartitions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/instances/*}/instancePartitions'
    _globals['_INSTANCEADMIN'].methods_by_name['GetInstance']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['GetInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02#\x12!/v1/{name=projects/*/instances/*}'
    _globals['_INSTANCEADMIN'].methods_by_name['CreateInstance']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['CreateInstance']._serialized_options = b'\xcaAd\n)google.spanner.admin.instance.v1.Instance\x127google.spanner.admin.instance.v1.CreateInstanceMetadata\xdaA\x1bparent,instance_id,instance\x82\xd3\xe4\x93\x02&"!/v1/{parent=projects/*}/instances:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['UpdateInstance']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['UpdateInstance']._serialized_options = b'\xcaAd\n)google.spanner.admin.instance.v1.Instance\x127google.spanner.admin.instance.v1.UpdateInstanceMetadata\xdaA\x13instance,field_mask\x82\xd3\xe4\x93\x02/2*/v1/{instance.name=projects/*/instances/*}:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['DeleteInstance']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['DeleteInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02#*!/v1/{name=projects/*/instances/*}'
    _globals['_INSTANCEADMIN'].methods_by_name['SetIamPolicy']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['SetIamPolicy']._serialized_options = b'\xdaA\x0fresource,policy\x82\xd3\xe4\x93\x027"2/v1/{resource=projects/*/instances/*}:setIamPolicy:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['GetIamPolicy']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['GetIamPolicy']._serialized_options = b'\xdaA\x08resource\x82\xd3\xe4\x93\x027"2/v1/{resource=projects/*/instances/*}:getIamPolicy:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['TestIamPermissions']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['TestIamPermissions']._serialized_options = b'\xdaA\x14resource,permissions\x82\xd3\xe4\x93\x02="8/v1/{resource=projects/*/instances/*}:testIamPermissions:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['GetInstancePartition']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['GetInstancePartition']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/instances/*/instancePartitions/*}'
    _globals['_INSTANCEADMIN'].methods_by_name['CreateInstancePartition']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['CreateInstancePartition']._serialized_options = b'\xcaAv\n2google.spanner.admin.instance.v1.InstancePartition\x12@google.spanner.admin.instance.v1.CreateInstancePartitionMetadata\xdaA/parent,instance_partition,instance_partition_id\x82\xd3\xe4\x93\x02;"6/v1/{parent=projects/*/instances/*}/instancePartitions:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['DeleteInstancePartition']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['DeleteInstancePartition']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/instances/*/instancePartitions/*}'
    _globals['_INSTANCEADMIN'].methods_by_name['UpdateInstancePartition']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['UpdateInstancePartition']._serialized_options = b'\xcaAv\n2google.spanner.admin.instance.v1.InstancePartition\x12@google.spanner.admin.instance.v1.UpdateInstancePartitionMetadata\xdaA\x1dinstance_partition,field_mask\x82\xd3\xe4\x93\x02N2I/v1/{instance_partition.name=projects/*/instances/*/instancePartitions/*}:\x01*'
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstancePartitionOperations']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['ListInstancePartitionOperations']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/instances/*}/instancePartitionOperations'
    _globals['_INSTANCEADMIN'].methods_by_name['MoveInstance']._loaded_options = None
    _globals['_INSTANCEADMIN'].methods_by_name['MoveInstance']._serialized_options = b'\xcaAn\n5google.spanner.admin.instance.v1.MoveInstanceResponse\x125google.spanner.admin.instance.v1.MoveInstanceMetadata\x82\xd3\xe4\x93\x02+"&/v1/{name=projects/*/instances/*}:move:\x01*'
    _globals['_REPLICAINFO']._serialized_start = 455
    _globals['_REPLICAINFO']._serialized_end = 673
    _globals['_REPLICAINFO_REPLICATYPE']._serialized_start = 594
    _globals['_REPLICAINFO_REPLICATYPE']._serialized_end = 673
    _globals['_INSTANCECONFIG']._serialized_start = 676
    _globals['_INSTANCECONFIG']._serialized_end = 2020
    _globals['_INSTANCECONFIG_LABELSENTRY']._serialized_start = 1489
    _globals['_INSTANCECONFIG_LABELSENTRY']._serialized_end = 1534
    _globals['_INSTANCECONFIG_TYPE']._serialized_start = 1536
    _globals['_INSTANCECONFIG_TYPE']._serialized_end = 1602
    _globals['_INSTANCECONFIG_STATE']._serialized_start = 1604
    _globals['_INSTANCECONFIG_STATE']._serialized_end = 1659
    _globals['_INSTANCECONFIG_FREEINSTANCEAVAILABILITY']._serialized_start = 1662
    _globals['_INSTANCECONFIG_FREEINSTANCEAVAILABILITY']._serialized_end = 1798
    _globals['_INSTANCECONFIG_QUORUMTYPE']._serialized_start = 1800
    _globals['_INSTANCECONFIG_QUORUMTYPE']._serialized_end = 1888
    _globals['_REPLICACOMPUTECAPACITY']._serialized_start = 2023
    _globals['_REPLICACOMPUTECAPACITY']._serialized_end = 2201
    _globals['_AUTOSCALINGCONFIG']._serialized_start = 2204
    _globals['_AUTOSCALINGCONFIG']._serialized_end = 3284
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGLIMITS']._serialized_start = 2562
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGLIMITS']._serialized_end = 2713
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGTARGETS']._serialized_start = 2715
    _globals['_AUTOSCALINGCONFIG_AUTOSCALINGTARGETS']._serialized_end = 2829
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION']._serialized_start = 2832
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION']._serialized_end = 3284
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION_AUTOSCALINGCONFIGOVERRIDES']._serialized_start = 3081
    _globals['_AUTOSCALINGCONFIG_ASYMMETRICAUTOSCALINGOPTION_AUTOSCALINGCONFIGOVERRIDES']._serialized_end = 3284
    _globals['_INSTANCE']._serialized_start = 3287
    _globals['_INSTANCE']._serialized_end = 4737
    _globals['_INSTANCE_LABELSENTRY']._serialized_start = 1489
    _globals['_INSTANCE_LABELSENTRY']._serialized_end = 1534
    _globals['_INSTANCE_STATE']._serialized_start = 1604
    _globals['_INSTANCE_STATE']._serialized_end = 1659
    _globals['_INSTANCE_INSTANCETYPE']._serialized_start = 4369
    _globals['_INSTANCE_INSTANCETYPE']._serialized_end = 4450
    _globals['_INSTANCE_EDITION']._serialized_start = 4452
    _globals['_INSTANCE_EDITION']._serialized_end = 4537
    _globals['_INSTANCE_DEFAULTBACKUPSCHEDULETYPE']._serialized_start = 4539
    _globals['_INSTANCE_DEFAULTBACKUPSCHEDULETYPE']._serialized_end = 4637
    _globals['_LISTINSTANCECONFIGSREQUEST']._serialized_start = 4740
    _globals['_LISTINSTANCECONFIGSREQUEST']._serialized_end = 4876
    _globals['_LISTINSTANCECONFIGSRESPONSE']._serialized_start = 4879
    _globals['_LISTINSTANCECONFIGSRESPONSE']._serialized_end = 5009
    _globals['_GETINSTANCECONFIGREQUEST']._serialized_start = 5011
    _globals['_GETINSTANCECONFIGREQUEST']._serialized_end = 5098
    _globals['_CREATEINSTANCECONFIGREQUEST']._serialized_start = 5101
    _globals['_CREATEINSTANCECONFIGREQUEST']._serialized_end = 5335
    _globals['_UPDATEINSTANCECONFIGREQUEST']._serialized_start = 5338
    _globals['_UPDATEINSTANCECONFIGREQUEST']._serialized_end = 5524
    _globals['_DELETEINSTANCECONFIGREQUEST']._serialized_start = 5526
    _globals['_DELETEINSTANCECONFIGREQUEST']._serialized_end = 5653
    _globals['_LISTINSTANCECONFIGOPERATIONSREQUEST']._serialized_start = 5656
    _globals['_LISTINSTANCECONFIGOPERATIONSREQUEST']._serialized_end = 5817
    _globals['_LISTINSTANCECONFIGOPERATIONSRESPONSE']._serialized_start = 5819
    _globals['_LISTINSTANCECONFIGOPERATIONSRESPONSE']._serialized_end = 5933
    _globals['_GETINSTANCEREQUEST']._serialized_start = 5935
    _globals['_GETINSTANCEREQUEST']._serialized_end = 6058
    _globals['_CREATEINSTANCEREQUEST']._serialized_start = 6061
    _globals['_CREATEINSTANCEREQUEST']._serialized_end = 6246
    _globals['_LISTINSTANCESREQUEST']._serialized_start = 6249
    _globals['_LISTINSTANCESREQUEST']._serialized_end = 6450
    _globals['_LISTINSTANCESRESPONSE']._serialized_start = 6453
    _globals['_LISTINSTANCESRESPONSE']._serialized_end = 6585
    _globals['_UPDATEINSTANCEREQUEST']._serialized_start = 6588
    _globals['_UPDATEINSTANCEREQUEST']._serialized_end = 6731
    _globals['_DELETEINSTANCEREQUEST']._serialized_start = 6733
    _globals['_DELETEINSTANCEREQUEST']._serialized_end = 6811
    _globals['_CREATEINSTANCEMETADATA']._serialized_start = 6814
    _globals['_CREATEINSTANCEMETADATA']._serialized_end = 7133
    _globals['_UPDATEINSTANCEMETADATA']._serialized_start = 7136
    _globals['_UPDATEINSTANCEMETADATA']._serialized_end = 7455
    _globals['_FREEINSTANCEMETADATA']._serialized_start = 7458
    _globals['_FREEINSTANCEMETADATA']._serialized_end = 7792
    _globals['_FREEINSTANCEMETADATA_EXPIREBEHAVIOR']._serialized_start = 7687
    _globals['_FREEINSTANCEMETADATA_EXPIREBEHAVIOR']._serialized_end = 7792
    _globals['_CREATEINSTANCECONFIGMETADATA']._serialized_start = 7795
    _globals['_CREATEINSTANCECONFIGMETADATA']._serialized_end = 8020
    _globals['_UPDATEINSTANCECONFIGMETADATA']._serialized_start = 8023
    _globals['_UPDATEINSTANCECONFIGMETADATA']._serialized_end = 8248
    _globals['_INSTANCEPARTITION']._serialized_start = 8251
    _globals['_INSTANCEPARTITION']._serialized_end = 8948
    _globals['_INSTANCEPARTITION_STATE']._serialized_start = 1604
    _globals['_INSTANCEPARTITION_STATE']._serialized_end = 1659
    _globals['_CREATEINSTANCEPARTITIONMETADATA']._serialized_start = 8951
    _globals['_CREATEINSTANCEPARTITIONMETADATA']._serialized_end = 9208
    _globals['_CREATEINSTANCEPARTITIONREQUEST']._serialized_start = 9211
    _globals['_CREATEINSTANCEPARTITIONREQUEST']._serialized_end = 9422
    _globals['_DELETEINSTANCEPARTITIONREQUEST']._serialized_start = 9424
    _globals['_DELETEINSTANCEPARTITIONREQUEST']._serialized_end = 9534
    _globals['_GETINSTANCEPARTITIONREQUEST']._serialized_start = 9536
    _globals['_GETINSTANCEPARTITIONREQUEST']._serialized_end = 9629
    _globals['_UPDATEINSTANCEPARTITIONREQUEST']._serialized_start = 9632
    _globals['_UPDATEINSTANCEPARTITIONREQUEST']._serialized_end = 9803
    _globals['_UPDATEINSTANCEPARTITIONMETADATA']._serialized_start = 9806
    _globals['_UPDATEINSTANCEPARTITIONMETADATA']._serialized_end = 10063
    _globals['_LISTINSTANCEPARTITIONSREQUEST']._serialized_start = 10066
    _globals['_LISTINSTANCEPARTITIONSREQUEST']._serialized_end = 10263
    _globals['_LISTINSTANCEPARTITIONSRESPONSE']._serialized_start = 10266
    _globals['_LISTINSTANCEPARTITIONSRESPONSE']._serialized_end = 10426
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST']._serialized_start = 10429
    _globals['_LISTINSTANCEPARTITIONOPERATIONSREQUEST']._serialized_end = 10666
    _globals['_LISTINSTANCEPARTITIONOPERATIONSRESPONSE']._serialized_start = 10669
    _globals['_LISTINSTANCEPARTITIONOPERATIONSRESPONSE']._serialized_end = 10827
    _globals['_MOVEINSTANCEREQUEST']._serialized_start = 10830
    _globals['_MOVEINSTANCEREQUEST']._serialized_end = 10976
    _globals['_MOVEINSTANCERESPONSE']._serialized_start = 10978
    _globals['_MOVEINSTANCERESPONSE']._serialized_end = 11000
    _globals['_MOVEINSTANCEMETADATA']._serialized_start = 11003
    _globals['_MOVEINSTANCEMETADATA']._serialized_end = 11168
    _globals['_INSTANCEADMIN']._serialized_start = 11171
    _globals['_INSTANCEADMIN']._serialized_end = 16253