# coding: utf-8

"""
    Phoenix API

    Base API for Glumanda and other services.

    The version of the OpenAPI document: Alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from phoenix_sdk.models.unit_event_schema_in import UnitEventSchemaIN

class TestUnitEventSchemaIN(unittest.TestCase):
    """UnitEventSchemaIN unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnitEventSchemaIN:
        """Test UnitEventSchemaIN
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnitEventSchemaIN`
        """
        model = UnitEventSchemaIN()
        if include_optional:
            return UnitEventSchemaIN(
                created_by_id = '',
                details = { },
                type = 'scheduled',
                temp = 1.337
            )
        else:
            return UnitEventSchemaIN(
                created_by_id = '',
                type = 'scheduled',
        )
        """

    def testUnitEventSchemaIN(self):
        """Test UnitEventSchemaIN"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
