"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/asset/v1/asset_service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.asset.v1 import assets_pb2 as google_dot_cloud_dot_asset_dot_v1_dot_assets__pb2
from .....google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .....google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from .....google.type import expr_pb2 as google_dot_type_dot_expr__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)google/cloud/asset/v1/asset_service.proto\x12\x15google.cloud.asset.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a"google/cloud/asset/v1/assets.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a#google/longrunning/operations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\x1a\x16google/type/expr.proto"[\n#AnalyzeIamPolicyLongrunningMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03"\xa9\x02\n\x13ExportAssetsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset\x12-\n\tread_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x13\n\x0basset_types\x18\x03 \x03(\t\x128\n\x0ccontent_type\x18\x04 \x01(\x0e2".google.cloud.asset.v1.ContentType\x12?\n\routput_config\x18\x05 \x01(\x0b2#.google.cloud.asset.v1.OutputConfigB\x03\xe0A\x02\x12\x1a\n\x12relationship_types\x18\x06 \x03(\t"\xbd\x01\n\x14ExportAssetsResponse\x12-\n\tread_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12:\n\routput_config\x18\x02 \x01(\x0b2#.google.cloud.asset.v1.OutputConfig\x12:\n\routput_result\x18\x03 \x01(\x0b2#.google.cloud.asset.v1.OutputResult"\x8d\x02\n\x11ListAssetsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset\x12-\n\tread_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x13\n\x0basset_types\x18\x03 \x03(\t\x128\n\x0ccontent_type\x18\x04 \x01(\x0e2".google.cloud.asset.v1.ContentType\x12\x11\n\tpage_size\x18\x05 \x01(\x05\x12\x12\n\npage_token\x18\x06 \x01(\t\x12\x1a\n\x12relationship_types\x18\x07 \x03(\t"\x8a\x01\n\x12ListAssetsResponse\x12-\n\tread_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x06assets\x18\x02 \x03(\x0b2\x1c.google.cloud.asset.v1.Asset\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t"\x8e\x02\n\x1cBatchGetAssetsHistoryRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset\x12\x13\n\x0basset_names\x18\x02 \x03(\t\x12=\n\x0ccontent_type\x18\x03 \x01(\x0e2".google.cloud.asset.v1.ContentTypeB\x03\xe0A\x01\x12@\n\x10read_time_window\x18\x04 \x01(\x0b2!.google.cloud.asset.v1.TimeWindowB\x03\xe0A\x01\x12\x1f\n\x12relationship_types\x18\x05 \x03(\tB\x03\xe0A\x01"U\n\x1dBatchGetAssetsHistoryResponse\x124\n\x06assets\x18\x01 \x03(\x0b2$.google.cloud.asset.v1.TemporalAsset"n\n\x11CreateFeedRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x14\n\x07feed_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12.\n\x04feed\x18\x03 \x01(\x0b2\x1b.google.cloud.asset.v1.FeedB\x03\xe0A\x02"F\n\x0eGetFeedRequest\x124\n\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n\x1ecloudasset.googleapis.com/Feed"\'\n\x10ListFeedsRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02"?\n\x11ListFeedsResponse\x12*\n\x05feeds\x18\x01 \x03(\x0b2\x1b.google.cloud.asset.v1.Feed"y\n\x11UpdateFeedRequest\x12.\n\x04feed\x18\x01 \x01(\x0b2\x1b.google.cloud.asset.v1.FeedB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"I\n\x11DeleteFeedRequest\x124\n\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n\x1ecloudasset.googleapis.com/Feed"\xab\x01\n\x0cOutputConfig\x12@\n\x0fgcs_destination\x18\x01 \x01(\x0b2%.google.cloud.asset.v1.GcsDestinationH\x00\x12J\n\x14bigquery_destination\x18\x02 \x01(\x0b2*.google.cloud.asset.v1.BigQueryDestinationH\x00B\r\n\x0bdestination"V\n\x0cOutputResult\x12<\n\ngcs_result\x18\x01 \x01(\x0b2&.google.cloud.asset.v1.GcsOutputResultH\x00B\x08\n\x06result"\x1f\n\x0fGcsOutputResult\x12\x0c\n\x04uris\x18\x01 \x03(\t"C\n\x0eGcsDestination\x12\r\n\x03uri\x18\x01 \x01(\tH\x00\x12\x14\n\nuri_prefix\x18\x02 \x01(\tH\x00B\x0c\n\nobject_uri"\xb4\x01\n\x13BigQueryDestination\x12\x14\n\x07dataset\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x12\n\x05table\x18\x02 \x01(\tB\x03\xe0A\x02\x12\r\n\x05force\x18\x03 \x01(\x08\x12<\n\x0epartition_spec\x18\x04 \x01(\x0b2$.google.cloud.asset.v1.PartitionSpec\x12&\n\x1eseparate_tables_per_asset_type\x18\x05 \x01(\x08"\xa9\x01\n\rPartitionSpec\x12H\n\rpartition_key\x18\x01 \x01(\x0e21.google.cloud.asset.v1.PartitionSpec.PartitionKey"N\n\x0cPartitionKey\x12\x1d\n\x19PARTITION_KEY_UNSPECIFIED\x10\x00\x12\r\n\tREAD_TIME\x10\x01\x12\x10\n\x0cREQUEST_TIME\x10\x02""\n\x11PubsubDestination\x12\r\n\x05topic\x18\x01 \x01(\t"i\n\x10FeedOutputConfig\x12F\n\x12pubsub_destination\x18\x01 \x01(\x0b2(.google.cloud.asset.v1.PubsubDestinationH\x00B\r\n\x0bdestination"\x9d\x03\n\x04Feed\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x13\n\x0basset_names\x18\x02 \x03(\t\x12\x13\n\x0basset_types\x18\x03 \x03(\t\x128\n\x0ccontent_type\x18\x04 \x01(\x0e2".google.cloud.asset.v1.ContentType\x12H\n\x12feed_output_config\x18\x05 \x01(\x0b2\'.google.cloud.asset.v1.FeedOutputConfigB\x03\xe0A\x02\x12$\n\tcondition\x18\x06 \x01(\x0b2\x11.google.type.Expr\x12\x1a\n\x12relationship_types\x18\x07 \x03(\t:\x91\x01\xeaA\x8d\x01\n\x1ecloudasset.googleapis.com/Feed\x12\x1fprojects/{project}/feeds/{feed}\x12\x1dfolders/{folder}/feeds/{feed}\x12)organizations/{organization}/feeds/{feed} \x01"\xd9\x01\n\x19SearchAllResourcesRequest\x12\x12\n\x05scope\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x12\n\x05query\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x18\n\x0basset_types\x18\x03 \x03(\tB\x03\xe0A\x01\x12\x16\n\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x06 \x01(\tB\x03\xe0A\x01\x122\n\tread_mask\x18\x08 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"s\n\x1aSearchAllResourcesResponse\x12<\n\x07results\x18\x01 \x03(\x0b2+.google.cloud.asset.v1.ResourceSearchResult\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xa7\x01\n\x1bSearchAllIamPoliciesRequest\x12\x12\n\x05scope\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x12\n\x05query\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x16\n\tpage_size\x18\x03 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x18\n\x0basset_types\x18\x05 \x03(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x07 \x01(\tB\x03\xe0A\x01"v\n\x1cSearchAllIamPoliciesResponse\x12=\n\x07results\x18\x01 \x03(\x0b2,.google.cloud.asset.v1.IamPolicySearchResult\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xc6\x07\n\x16IamPolicyAnalysisQuery\x12\x12\n\x05scope\x18\x01 \x01(\tB\x03\xe0A\x02\x12^\n\x11resource_selector\x18\x02 \x01(\x0b2>.google.cloud.asset.v1.IamPolicyAnalysisQuery.ResourceSelectorB\x03\xe0A\x01\x12^\n\x11identity_selector\x18\x03 \x01(\x0b2>.google.cloud.asset.v1.IamPolicyAnalysisQuery.IdentitySelectorB\x03\xe0A\x01\x12Z\n\x0faccess_selector\x18\x04 \x01(\x0b2<.google.cloud.asset.v1.IamPolicyAnalysisQuery.AccessSelectorB\x03\xe0A\x01\x12K\n\x07options\x18\x05 \x01(\x0b25.google.cloud.asset.v1.IamPolicyAnalysisQuery.OptionsB\x03\xe0A\x01\x12^\n\x11condition_context\x18\x06 \x01(\x0b2>.google.cloud.asset.v1.IamPolicyAnalysisQuery.ConditionContextB\x03\xe0A\x01\x1a3\n\x10ResourceSelector\x12\x1f\n\x12full_resource_name\x18\x01 \x01(\tB\x03\xe0A\x02\x1a)\n\x10IdentitySelector\x12\x15\n\x08identity\x18\x01 \x01(\tB\x03\xe0A\x02\x1a>\n\x0eAccessSelector\x12\x12\n\x05roles\x18\x01 \x03(\tB\x03\xe0A\x01\x12\x18\n\x0bpermissions\x18\x02 \x03(\tB\x03\xe0A\x01\x1a\xd8\x01\n\x07Options\x12\x1a\n\rexpand_groups\x18\x01 \x01(\x08B\x03\xe0A\x01\x12\x19\n\x0cexpand_roles\x18\x02 \x01(\x08B\x03\xe0A\x01\x12\x1d\n\x10expand_resources\x18\x03 \x01(\x08B\x03\xe0A\x01\x12"\n\x15output_resource_edges\x18\x04 \x01(\x08B\x03\xe0A\x01\x12\x1f\n\x12output_group_edges\x18\x05 \x01(\x08B\x03\xe0A\x01\x122\n%analyze_service_account_impersonation\x18\x06 \x01(\x08B\x03\xe0A\x01\x1aT\n\x10ConditionContext\x121\n\x0baccess_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampH\x00B\r\n\x0bTimeContext"\xc3\x01\n\x17AnalyzeIamPolicyRequest\x12J\n\x0eanalysis_query\x18\x01 \x01(\x0b2-.google.cloud.asset.v1.IamPolicyAnalysisQueryB\x03\xe0A\x02\x12!\n\x14saved_analysis_query\x18\x03 \x01(\tB\x03\xe0A\x01\x129\n\x11execution_timeout\x18\x02 \x01(\x0b2\x19.google.protobuf.DurationB\x03\xe0A\x01"\x8a\x04\n\x18AnalyzeIamPolicyResponse\x12X\n\rmain_analysis\x18\x01 \x01(\x0b2A.google.cloud.asset.v1.AnalyzeIamPolicyResponse.IamPolicyAnalysis\x12q\n&service_account_impersonation_analysis\x18\x02 \x03(\x0b2A.google.cloud.asset.v1.AnalyzeIamPolicyResponse.IamPolicyAnalysis\x12\x16\n\x0efully_explored\x18\x03 \x01(\x08\x1a\x88\x02\n\x11IamPolicyAnalysis\x12E\n\x0eanalysis_query\x18\x01 \x01(\x0b2-.google.cloud.asset.v1.IamPolicyAnalysisQuery\x12H\n\x10analysis_results\x18\x02 \x03(\x0b2..google.cloud.asset.v1.IamPolicyAnalysisResult\x12\x16\n\x0efully_explored\x18\x03 \x01(\x08\x12J\n\x13non_critical_errors\x18\x05 \x03(\x0b2-.google.cloud.asset.v1.IamPolicyAnalysisState"\xb4\x04\n\x1dIamPolicyAnalysisOutputConfig\x12^\n\x0fgcs_destination\x18\x01 \x01(\x0b2C.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.GcsDestinationH\x00\x12h\n\x14bigquery_destination\x18\x02 \x01(\x0b2H.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.BigQueryDestinationH\x00\x1a"\n\x0eGcsDestination\x12\x10\n\x03uri\x18\x01 \x01(\tB\x03\xe0A\x02\x1a\x95\x02\n\x13BigQueryDestination\x12\x14\n\x07dataset\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x19\n\x0ctable_prefix\x18\x02 \x01(\tB\x03\xe0A\x02\x12l\n\rpartition_key\x18\x03 \x01(\x0e2U.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.BigQueryDestination.PartitionKey\x12\x1e\n\x11write_disposition\x18\x04 \x01(\tB\x03\xe0A\x01"?\n\x0cPartitionKey\x12\x1d\n\x19PARTITION_KEY_UNSPECIFIED\x10\x00\x12\x10\n\x0cREQUEST_TIME\x10\x01B\r\n\x0bdestination"\xe5\x01\n"AnalyzeIamPolicyLongrunningRequest\x12J\n\x0eanalysis_query\x18\x01 \x01(\x0b2-.google.cloud.asset.v1.IamPolicyAnalysisQueryB\x03\xe0A\x02\x12!\n\x14saved_analysis_query\x18\x03 \x01(\tB\x03\xe0A\x01\x12P\n\routput_config\x18\x02 \x01(\x0b24.google.cloud.asset.v1.IamPolicyAnalysisOutputConfigB\x03\xe0A\x02"%\n#AnalyzeIamPolicyLongrunningResponse"\xb7\x05\n\nSavedQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x124\n\x0bcreate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x14\n\x07creator\x18\x04 \x01(\tB\x03\xe0A\x03\x129\n\x10last_update_time\x18\x05 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x19\n\x0clast_updater\x18\x06 \x01(\tB\x03\xe0A\x03\x12=\n\x06labels\x18\x07 \x03(\x0b2-.google.cloud.asset.v1.SavedQuery.LabelsEntry\x12?\n\x07content\x18\x08 \x01(\x0b2..google.cloud.asset.v1.SavedQuery.QueryContent\x1as\n\x0cQueryContent\x12R\n\x19iam_policy_analysis_query\x18\x01 \x01(\x0b2-.google.cloud.asset.v1.IamPolicyAnalysisQueryH\x00B\x0f\n\rquery_content\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01:\xbf\x01\xeaA\xbb\x01\n$cloudasset.googleapis.com/SavedQuery\x12-projects/{project}/savedQueries/{saved_query}\x12+folders/{folder}/savedQueries/{saved_query}\x127organizations/{organization}/savedQueries/{saved_query}"\xb1\x01\n\x17CreateSavedQueryRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$cloudasset.googleapis.com/SavedQuery\x12;\n\x0bsaved_query\x18\x02 \x01(\x0b2!.google.cloud.asset.v1.SavedQueryB\x03\xe0A\x02\x12\x1b\n\x0esaved_query_id\x18\x03 \x01(\tB\x03\xe0A\x02"R\n\x14GetSavedQueryRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudasset.googleapis.com/SavedQuery"\x9d\x01\n\x17ListSavedQueriesRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$cloudasset.googleapis.com/SavedQuery\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"m\n\x18ListSavedQueriesResponse\x128\n\rsaved_queries\x18\x01 \x03(\x0b2!.google.cloud.asset.v1.SavedQuery\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x8c\x01\n\x17UpdateSavedQueryRequest\x12;\n\x0bsaved_query\x18\x01 \x01(\x0b2!.google.cloud.asset.v1.SavedQueryB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"U\n\x17DeleteSavedQueryRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudasset.googleapis.com/SavedQuery"\x8c\x02\n\x12AnalyzeMoveRequest\x12E\n\x08resource\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12%\n\x12destination_parent\x18\x02 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12D\n\x04view\x18\x03 \x01(\x0e26.google.cloud.asset.v1.AnalyzeMoveRequest.AnalysisView"B\n\x0cAnalysisView\x12\x1d\n\x19ANALYSIS_VIEW_UNSPECIFIED\x10\x00\x12\x08\n\x04FULL\x10\x01\x12\t\n\x05BASIC\x10\x02"Q\n\x13AnalyzeMoveResponse\x12:\n\rmove_analysis\x18\x01 \x03(\x0b2#.google.cloud.asset.v1.MoveAnalysis"\x92\x01\n\x0cMoveAnalysis\x12\x14\n\x0cdisplay_name\x18\x01 \x01(\t\x12=\n\x08analysis\x18\x02 \x01(\x0b2).google.cloud.asset.v1.MoveAnalysisResultH\x00\x12#\n\x05error\x18\x03 \x01(\x0b2\x12.google.rpc.StatusH\x00B\x08\n\x06result"~\n\x12MoveAnalysisResult\x123\n\x08blockers\x18\x01 \x03(\x0b2!.google.cloud.asset.v1.MoveImpact\x123\n\x08warnings\x18\x02 \x03(\x0b2!.google.cloud.asset.v1.MoveImpact"\x1c\n\nMoveImpact\x12\x0e\n\x06detail\x18\x01 \x01(\t"\xd7\x01\n\x17QueryAssetsOutputConfig\x12`\n\x14bigquery_destination\x18\x01 \x01(\x0b2B.google.cloud.asset.v1.QueryAssetsOutputConfig.BigQueryDestination\x1aZ\n\x13BigQueryDestination\x12\x14\n\x07dataset\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x12\n\x05table\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x19\n\x11write_disposition\x18\x03 \x01(\t"\xbe\x03\n\x12QueryAssetsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset\x12\x18\n\tstatement\x18\x02 \x01(\tB\x03\xe0A\x01H\x00\x12\x1c\n\rjob_reference\x18\x03 \x01(\tB\x03\xe0A\x01H\x00\x12\x16\n\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x05 \x01(\tB\x03\xe0A\x01\x12/\n\x07timeout\x18\x06 \x01(\x0b2\x19.google.protobuf.DurationB\x03\xe0A\x01\x12B\n\x10read_time_window\x18\x07 \x01(\x0b2!.google.cloud.asset.v1.TimeWindowB\x03\xe0A\x01H\x01\x124\n\tread_time\x18\x08 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x01H\x01\x12J\n\routput_config\x18\t \x01(\x0b2..google.cloud.asset.v1.QueryAssetsOutputConfigB\x03\xe0A\x01B\x07\n\x05queryB\x06\n\x04time"\xf0\x01\n\x13QueryAssetsResponse\x12\x15\n\rjob_reference\x18\x01 \x01(\t\x12\x0c\n\x04done\x18\x02 \x01(\x08\x12#\n\x05error\x18\x03 \x01(\x0b2\x12.google.rpc.StatusH\x00\x12:\n\x0cquery_result\x18\x04 \x01(\x0b2".google.cloud.asset.v1.QueryResultH\x00\x12G\n\routput_config\x18\x05 \x01(\x0b2..google.cloud.asset.v1.QueryAssetsOutputConfigH\x00B\n\n\x08response"\x95\x01\n\x0bQueryResult\x12%\n\x04rows\x18\x01 \x03(\x0b2\x17.google.protobuf.Struct\x122\n\x06schema\x18\x02 \x01(\x0b2".google.cloud.asset.v1.TableSchema\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t\x12\x12\n\ntotal_rows\x18\x04 \x01(\x03"F\n\x0bTableSchema\x127\n\x06fields\x18\x01 \x03(\x0b2\'.google.cloud.asset.v1.TableFieldSchema"v\n\x10TableFieldSchema\x12\r\n\x05field\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x127\n\x06fields\x18\x04 \x03(\x0b2\'.google.cloud.asset.v1.TableFieldSchema"Y\n#BatchGetEffectiveIamPoliciesRequest\x12\x18\n\x05scope\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\x12\x01*\x12\x18\n\x05names\x18\x03 \x03(\tB\t\xe0A\x02\xfaA\x03\n\x01*"\xfe\x02\n$BatchGetEffectiveIamPoliciesResponse\x12f\n\x0epolicy_results\x18\x02 \x03(\x0b2N.google.cloud.asset.v1.BatchGetEffectiveIamPoliciesResponse.EffectiveIamPolicy\x1a\xed\x01\n\x12EffectiveIamPolicy\x12\x1a\n\x12full_resource_name\x18\x01 \x01(\t\x12k\n\x08policies\x18\x02 \x03(\x0b2Y.google.cloud.asset.v1.BatchGetEffectiveIamPoliciesResponse.EffectiveIamPolicy.PolicyInfo\x1aN\n\nPolicyInfo\x12\x19\n\x11attached_resource\x18\x01 \x01(\t\x12%\n\x06policy\x18\x02 \x01(\x0b2\x15.google.iam.v1.Policy"\xfc\x03\n\x11AnalyzerOrgPolicy\x12\x19\n\x11attached_resource\x18\x01 \x01(\t\x12\x18\n\x10applied_resource\x18\x05 \x01(\t\x12<\n\x05rules\x18\x02 \x03(\x0b2-.google.cloud.asset.v1.AnalyzerOrgPolicy.Rule\x12\x1b\n\x13inherit_from_parent\x18\x03 \x01(\x08\x12\r\n\x05reset\x18\x04 \x01(\x08\x1a\xc7\x02\n\x04Rule\x12L\n\x06values\x18\x03 \x01(\x0b2:.google.cloud.asset.v1.AnalyzerOrgPolicy.Rule.StringValuesH\x00\x12\x13\n\tallow_all\x18\x04 \x01(\x08H\x00\x12\x12\n\x08deny_all\x18\x05 \x01(\x08H\x00\x12\x11\n\x07enforce\x18\x06 \x01(\x08H\x00\x12$\n\tcondition\x18\x07 \x01(\x0b2\x11.google.type.Expr\x12H\n\x14condition_evaluation\x18\x08 \x01(\x0b2*.google.cloud.asset.v1.ConditionEvaluation\x1a=\n\x0cStringValues\x12\x16\n\x0eallowed_values\x18\x01 \x03(\t\x12\x15\n\rdenied_values\x18\x02 \x03(\tB\x06\n\x04kind"\xb4\n\n\x1bAnalyzerOrgPolicyConstraint\x12b\n\x19google_defined_constraint\x18\x01 \x01(\x0b2=.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.ConstraintH\x00\x12`\n\x11custom_constraint\x18\x02 \x01(\x0b2C.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.CustomConstraintH\x00\x1a\xbf\x04\n\nConstraint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cdisplay_name\x18\x02 \x01(\t\x12\x13\n\x0bdescription\x18\x03 \x01(\t\x12k\n\x12constraint_default\x18\x04 \x01(\x0e2O.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.Constraint.ConstraintDefault\x12g\n\x0flist_constraint\x18\x05 \x01(\x0b2L.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.Constraint.ListConstraintH\x00\x12m\n\x12boolean_constraint\x18\x06 \x01(\x0b2O.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.Constraint.BooleanConstraintH\x00\x1a=\n\x0eListConstraint\x12\x13\n\x0bsupports_in\x18\x01 \x01(\x08\x12\x16\n\x0esupports_under\x18\x02 \x01(\x08\x1a\x13\n\x11BooleanConstraint"L\n\x11ConstraintDefault\x12"\n\x1eCONSTRAINT_DEFAULT_UNSPECIFIED\x10\x00\x12\t\n\x05ALLOW\x10\x01\x12\x08\n\x04DENY\x10\x02B\x11\n\x0fconstraint_type\x1a\xf3\x03\n\x10CustomConstraint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0eresource_types\x18\x02 \x03(\t\x12d\n\x0cmethod_types\x18\x03 \x03(\x0e2N.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.CustomConstraint.MethodType\x12\x11\n\tcondition\x18\x04 \x01(\t\x12c\n\x0baction_type\x18\x05 \x01(\x0e2N.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.CustomConstraint.ActionType\x12\x14\n\x0cdisplay_name\x18\x06 \x01(\t\x12\x13\n\x0bdescription\x18\x07 \x01(\t"p\n\nMethodType\x12\x1b\n\x17METHOD_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06CREATE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06DELETE\x10\x03\x12\x10\n\x0cREMOVE_GRANT\x10\x04\x12\x0f\n\x0bGOVERN_TAGS\x10\x05">\n\nActionType\x12\x1b\n\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05ALLOW\x10\x01\x12\x08\n\x04DENY\x10\x02B\x17\n\x15constraint_definition"\x92\x01\n\x19AnalyzeOrgPoliciesRequest\x12\x12\n\x05scope\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nconstraint\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x0e\n\x06filter\x18\x03 \x01(\t\x12\x16\n\tpage_size\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\npage_token\x18\x05 \x01(\tB\x0c\n\n_page_size"\xb0\x03\n\x1aAnalyzeOrgPoliciesResponse\x12]\n\x12org_policy_results\x18\x01 \x03(\x0b2A.google.cloud.asset.v1.AnalyzeOrgPoliciesResponse.OrgPolicyResult\x12F\n\nconstraint\x18\x02 \x01(\x0b22.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t\x1a\xd1\x01\n\x0fOrgPolicyResult\x12E\n\x13consolidated_policy\x18\x01 \x01(\x0b2(.google.cloud.asset.v1.AnalyzerOrgPolicy\x12?\n\rpolicy_bundle\x18\x02 \x03(\x0b2(.google.cloud.asset.v1.AnalyzerOrgPolicy\x12\x0f\n\x07project\x18\x03 \x01(\t\x12\x0f\n\x07folders\x18\x04 \x03(\t\x12\x14\n\x0corganization\x18\x05 \x01(\t"\xa2\x01\n)AnalyzeOrgPolicyGovernedContainersRequest\x12\x12\n\x05scope\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nconstraint\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x0e\n\x06filter\x18\x03 \x01(\t\x12\x16\n\tpage_size\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\npage_token\x18\x05 \x01(\tB\x0c\n\n_page_size"\xc5\x04\n*AnalyzeOrgPolicyGovernedContainersResponse\x12p\n\x13governed_containers\x18\x01 \x03(\x0b2S.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer\x12F\n\nconstraint\x18\x02 \x01(\x0b22.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t\x1a\xc3\x02\n\x11GovernedContainer\x12\x1a\n\x12full_resource_name\x18\x01 \x01(\t\x12\x0e\n\x06parent\x18\x02 \x01(\t\x12E\n\x13consolidated_policy\x18\x03 \x01(\x0b2(.google.cloud.asset.v1.AnalyzerOrgPolicy\x12?\n\rpolicy_bundle\x18\x04 \x03(\x0b2(.google.cloud.asset.v1.AnalyzerOrgPolicy\x12\x0f\n\x07project\x18\x05 \x01(\t\x12\x0f\n\x07folders\x18\x06 \x03(\t\x12\x14\n\x0corganization\x18\x07 \x01(\t\x12B\n\x0eeffective_tags\x18\x08 \x03(\x0b2*.google.cloud.asset.v1.EffectiveTagDetails"\x9e\x01\n%AnalyzeOrgPolicyGovernedAssetsRequest\x12\x12\n\x05scope\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nconstraint\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x0e\n\x06filter\x18\x03 \x01(\t\x12\x16\n\tpage_size\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\npage_token\x18\x05 \x01(\tB\x0c\n\n_page_size"\xed\x07\n&AnalyzeOrgPolicyGovernedAssetsResponse\x12d\n\x0fgoverned_assets\x18\x01 \x03(\x0b2K.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset\x12F\n\nconstraint\x18\x02 \x01(\x0b22.google.cloud.asset.v1.AnalyzerOrgPolicyConstraint\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t\x1a\xce\x01\n\x10GovernedResource\x12\x1a\n\x12full_resource_name\x18\x01 \x01(\t\x12\x0e\n\x06parent\x18\x02 \x01(\t\x12\x0f\n\x07project\x18\x05 \x01(\t\x12\x0f\n\x07folders\x18\x06 \x03(\t\x12\x14\n\x0corganization\x18\x07 \x01(\t\x12\x12\n\nasset_type\x18\x08 \x01(\t\x12B\n\x0eeffective_tags\x18\t \x03(\x0b2*.google.cloud.asset.v1.EffectiveTagDetails\x1a\xa1\x01\n\x11GovernedIamPolicy\x12\x19\n\x11attached_resource\x18\x01 \x01(\t\x12%\n\x06policy\x18\x02 \x01(\x0b2\x15.google.iam.v1.Policy\x12\x0f\n\x07project\x18\x05 \x01(\t\x12\x0f\n\x07folders\x18\x06 \x03(\t\x12\x14\n\x0corganization\x18\x07 \x01(\t\x12\x12\n\nasset_type\x18\x08 \x01(\t\x1a\x86\x03\n\rGovernedAsset\x12k\n\x11governed_resource\x18\x01 \x01(\x0b2N.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedResourceH\x00\x12n\n\x13governed_iam_policy\x18\x02 \x01(\x0b2O.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedIamPolicyH\x00\x12E\n\x13consolidated_policy\x18\x03 \x01(\x0b2(.google.cloud.asset.v1.AnalyzerOrgPolicy\x12?\n\rpolicy_bundle\x18\x04 \x03(\x0b2(.google.cloud.asset.v1.AnalyzerOrgPolicyB\x10\n\x0egoverned_asset*\x90\x01\n\x0bContentType\x12\x1c\n\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x0c\n\x08RESOURCE\x10\x01\x12\x0e\n\nIAM_POLICY\x10\x02\x12\x0e\n\nORG_POLICY\x10\x04\x12\x11\n\rACCESS_POLICY\x10\x05\x12\x10\n\x0cOS_INVENTORY\x10\x06\x12\x10\n\x0cRELATIONSHIP\x10\x072\xd1 \n\x0cAssetService\x12\xde\x01\n\x0cExportAssets\x12*.google.cloud.asset.v1.ExportAssetsRequest\x1a\x1d.google.longrunning.Operation"\x82\x01\xcaAW\n*google.cloud.asset.v1.ExportAssetsResponse\x12)google.cloud.asset.v1.ExportAssetsRequest\x82\xd3\xe4\x93\x02""\x1d/v1/{parent=*/*}:exportAssets:\x01*\x12\x8b\x01\n\nListAssets\x12(.google.cloud.asset.v1.ListAssetsRequest\x1a).google.cloud.asset.v1.ListAssetsResponse"(\xdaA\x06parent\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/{parent=*/*}/assets\x12\xb2\x01\n\x15BatchGetAssetsHistory\x123.google.cloud.asset.v1.BatchGetAssetsHistoryRequest\x1a4.google.cloud.asset.v1.BatchGetAssetsHistoryResponse".\x82\xd3\xe4\x93\x02(\x12&/v1/{parent=*/*}:batchGetAssetsHistory\x12\x7f\n\nCreateFeed\x12(.google.cloud.asset.v1.CreateFeedRequest\x1a\x1b.google.cloud.asset.v1.Feed"*\xdaA\x06parent\x82\xd3\xe4\x93\x02\x1b"\x16/v1/{parent=*/*}/feeds:\x01*\x12t\n\x07GetFeed\x12%.google.cloud.asset.v1.GetFeedRequest\x1a\x1b.google.cloud.asset.v1.Feed"%\xdaA\x04name\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{name=*/*/feeds/*}\x12\x87\x01\n\tListFeeds\x12\'.google.cloud.asset.v1.ListFeedsRequest\x1a(.google.cloud.asset.v1.ListFeedsResponse"\'\xdaA\x06parent\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{parent=*/*}/feeds\x12\x82\x01\n\nUpdateFeed\x12(.google.cloud.asset.v1.UpdateFeedRequest\x1a\x1b.google.cloud.asset.v1.Feed"-\xdaA\x04feed\x82\xd3\xe4\x93\x02 2\x1b/v1/{feed.name=*/*/feeds/*}:\x01*\x12u\n\nDeleteFeed\x12(.google.cloud.asset.v1.DeleteFeedRequest\x1a\x16.google.protobuf.Empty"%\xdaA\x04name\x82\xd3\xe4\x93\x02\x18*\x16/v1/{name=*/*/feeds/*}\x12\xbf\x01\n\x12SearchAllResources\x120.google.cloud.asset.v1.SearchAllResourcesRequest\x1a1.google.cloud.asset.v1.SearchAllResourcesResponse"D\xdaA\x17scope,query,asset_types\x82\xd3\xe4\x93\x02$\x12"/v1/{scope=*/*}:searchAllResources\x12\xbb\x01\n\x14SearchAllIamPolicies\x122.google.cloud.asset.v1.SearchAllIamPoliciesRequest\x1a3.google.cloud.asset.v1.SearchAllIamPoliciesResponse":\xdaA\x0bscope,query\x82\xd3\xe4\x93\x02&\x12$/v1/{scope=*/*}:searchAllIamPolicies\x12\xac\x01\n\x10AnalyzeIamPolicy\x12..google.cloud.asset.v1.AnalyzeIamPolicyRequest\x1a/.google.cloud.asset.v1.AnalyzeIamPolicyResponse"7\x82\xd3\xe4\x93\x021\x12//v1/{analysis_query.scope=*/*}:analyzeIamPolicy\x12\xb8\x02\n\x1bAnalyzeIamPolicyLongrunning\x129.google.cloud.asset.v1.AnalyzeIamPolicyLongrunningRequest\x1a\x1d.google.longrunning.Operation"\xbe\x01\xcaAv\n9google.cloud.asset.v1.AnalyzeIamPolicyLongrunningResponse\x129google.cloud.asset.v1.AnalyzeIamPolicyLongrunningMetadata\x82\xd3\xe4\x93\x02?":/v1/{analysis_query.scope=*/*}:analyzeIamPolicyLongrunning:\x01*\x12\x8c\x01\n\x0bAnalyzeMove\x12).google.cloud.asset.v1.AnalyzeMoveRequest\x1a*.google.cloud.asset.v1.AnalyzeMoveResponse"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/{resource=*/*}:analyzeMove\x12\x8d\x01\n\x0bQueryAssets\x12).google.cloud.asset.v1.QueryAssetsRequest\x1a*.google.cloud.asset.v1.QueryAssetsResponse"\'\x82\xd3\xe4\x93\x02!"\x1c/v1/{parent=*/*}:queryAssets:\x01*\x12\xbd\x01\n\x10CreateSavedQuery\x12..google.cloud.asset.v1.CreateSavedQueryRequest\x1a!.google.cloud.asset.v1.SavedQuery"V\xdaA!parent,saved_query,saved_query_id\x82\xd3\xe4\x93\x02,"\x1d/v1/{parent=*/*}/savedQueries:\x0bsaved_query\x12\x8d\x01\n\rGetSavedQuery\x12+.google.cloud.asset.v1.GetSavedQueryRequest\x1a!.google.cloud.asset.v1.SavedQuery",\xdaA\x04name\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/{name=*/*/savedQueries/*}\x12\xa3\x01\n\x10ListSavedQueries\x12..google.cloud.asset.v1.ListSavedQueriesRequest\x1a/.google.cloud.asset.v1.ListSavedQueriesResponse".\xdaA\x06parent\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/{parent=*/*}/savedQueries\x12\xbf\x01\n\x10UpdateSavedQuery\x12..google.cloud.asset.v1.UpdateSavedQueryRequest\x1a!.google.cloud.asset.v1.SavedQuery"X\xdaA\x17saved_query,update_mask\x82\xd3\xe4\x93\x0282)/v1/{saved_query.name=*/*/savedQueries/*}:\x0bsaved_query\x12\x88\x01\n\x10DeleteSavedQuery\x12..google.cloud.asset.v1.DeleteSavedQueryRequest\x1a\x16.google.protobuf.Empty",\xdaA\x04name\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/{name=*/*/savedQueries/*}\x12\xce\x01\n\x1cBatchGetEffectiveIamPolicies\x12:.google.cloud.asset.v1.BatchGetEffectiveIamPoliciesRequest\x1a;.google.cloud.asset.v1.BatchGetEffectiveIamPoliciesResponse"5\x82\xd3\xe4\x93\x02/\x12-/v1/{scope=*/*}/effectiveIamPolicies:batchGet\x12\xbf\x01\n\x12AnalyzeOrgPolicies\x120.google.cloud.asset.v1.AnalyzeOrgPoliciesRequest\x1a1.google.cloud.asset.v1.AnalyzeOrgPoliciesResponse"D\xdaA\x17scope,constraint,filter\x82\xd3\xe4\x93\x02$\x12"/v1/{scope=*/*}:analyzeOrgPolicies\x12\xff\x01\n"AnalyzeOrgPolicyGovernedContainers\x12@.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedContainersRequest\x1aA.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedContainersResponse"T\xdaA\x17scope,constraint,filter\x82\xd3\xe4\x93\x024\x122/v1/{scope=*/*}:analyzeOrgPolicyGovernedContainers\x12\xef\x01\n\x1eAnalyzeOrgPolicyGovernedAssets\x12<.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsRequest\x1a=.google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse"P\xdaA\x17scope,constraint,filter\x82\xd3\xe4\x93\x020\x12./v1/{scope=*/*}:analyzeOrgPolicyGovernedAssets\x1aM\xcaA\x19cloudasset.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\x91\x01\n\x19com.google.cloud.asset.v1B\x11AssetServiceProtoP\x01Z/cloud.google.com/go/asset/apiv1/assetpb;assetpb\xaa\x02\x15Google.Cloud.Asset.V1\xca\x02\x15Google\\Cloud\\Asset\\V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.asset.v1.asset_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x19com.google.cloud.asset.v1B\x11AssetServiceProtoP\x01Z/cloud.google.com/go/asset/apiv1/assetpb;assetpb\xaa\x02\x15Google.Cloud.Asset.V1\xca\x02\x15Google\\Cloud\\Asset\\V1'
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_EXPORTASSETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_EXPORTASSETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset'
    _globals['_EXPORTASSETSREQUEST'].fields_by_name['output_config']._loaded_options = None
    _globals['_EXPORTASSETSREQUEST'].fields_by_name['output_config']._serialized_options = b'\xe0A\x02'
    _globals['_LISTASSETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTASSETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset'
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset'
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['content_type']._loaded_options = None
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['content_type']._serialized_options = b'\xe0A\x01'
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['read_time_window']._loaded_options = None
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['read_time_window']._serialized_options = b'\xe0A\x01'
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['relationship_types']._loaded_options = None
    _globals['_BATCHGETASSETSHISTORYREQUEST'].fields_by_name['relationship_types']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEFEEDREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEFEEDREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEFEEDREQUEST'].fields_by_name['feed_id']._loaded_options = None
    _globals['_CREATEFEEDREQUEST'].fields_by_name['feed_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEFEEDREQUEST'].fields_by_name['feed']._loaded_options = None
    _globals['_CREATEFEEDREQUEST'].fields_by_name['feed']._serialized_options = b'\xe0A\x02'
    _globals['_GETFEEDREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETFEEDREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA \n\x1ecloudasset.googleapis.com/Feed'
    _globals['_LISTFEEDSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTFEEDSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEFEEDREQUEST'].fields_by_name['feed']._loaded_options = None
    _globals['_UPDATEFEEDREQUEST'].fields_by_name['feed']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEFEEDREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEFEEDREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEFEEDREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEFEEDREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA \n\x1ecloudasset.googleapis.com/Feed'
    _globals['_BIGQUERYDESTINATION'].fields_by_name['dataset']._loaded_options = None
    _globals['_BIGQUERYDESTINATION'].fields_by_name['dataset']._serialized_options = b'\xe0A\x02'
    _globals['_BIGQUERYDESTINATION'].fields_by_name['table']._loaded_options = None
    _globals['_BIGQUERYDESTINATION'].fields_by_name['table']._serialized_options = b'\xe0A\x02'
    _globals['_FEED'].fields_by_name['name']._loaded_options = None
    _globals['_FEED'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_FEED'].fields_by_name['feed_output_config']._loaded_options = None
    _globals['_FEED'].fields_by_name['feed_output_config']._serialized_options = b'\xe0A\x02'
    _globals['_FEED']._loaded_options = None
    _globals['_FEED']._serialized_options = b'\xeaA\x8d\x01\n\x1ecloudasset.googleapis.com/Feed\x12\x1fprojects/{project}/feeds/{feed}\x12\x1dfolders/{folder}/feeds/{feed}\x12)organizations/{organization}/feeds/{feed} \x01'
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['scope']._loaded_options = None
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['scope']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['query']._loaded_options = None
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['query']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['asset_types']._loaded_options = None
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['asset_types']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['read_mask']._loaded_options = None
    _globals['_SEARCHALLRESOURCESREQUEST'].fields_by_name['read_mask']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['scope']._loaded_options = None
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['scope']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['query']._loaded_options = None
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['query']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['asset_types']._loaded_options = None
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['asset_types']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_SEARCHALLIAMPOLICIESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_RESOURCESELECTOR'].fields_by_name['full_resource_name']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_RESOURCESELECTOR'].fields_by_name['full_resource_name']._serialized_options = b'\xe0A\x02'
    _globals['_IAMPOLICYANALYSISQUERY_IDENTITYSELECTOR'].fields_by_name['identity']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_IDENTITYSELECTOR'].fields_by_name['identity']._serialized_options = b'\xe0A\x02'
    _globals['_IAMPOLICYANALYSISQUERY_ACCESSSELECTOR'].fields_by_name['roles']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_ACCESSSELECTOR'].fields_by_name['roles']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_ACCESSSELECTOR'].fields_by_name['permissions']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_ACCESSSELECTOR'].fields_by_name['permissions']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['expand_groups']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['expand_groups']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['expand_roles']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['expand_roles']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['expand_resources']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['expand_resources']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['output_resource_edges']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['output_resource_edges']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['output_group_edges']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['output_group_edges']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['analyze_service_account_impersonation']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS'].fields_by_name['analyze_service_account_impersonation']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['scope']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['scope']._serialized_options = b'\xe0A\x02'
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['resource_selector']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['resource_selector']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['identity_selector']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['identity_selector']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['access_selector']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['access_selector']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['options']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['options']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['condition_context']._loaded_options = None
    _globals['_IAMPOLICYANALYSISQUERY'].fields_by_name['condition_context']._serialized_options = b'\xe0A\x01'
    _globals['_ANALYZEIAMPOLICYREQUEST'].fields_by_name['analysis_query']._loaded_options = None
    _globals['_ANALYZEIAMPOLICYREQUEST'].fields_by_name['analysis_query']._serialized_options = b'\xe0A\x02'
    _globals['_ANALYZEIAMPOLICYREQUEST'].fields_by_name['saved_analysis_query']._loaded_options = None
    _globals['_ANALYZEIAMPOLICYREQUEST'].fields_by_name['saved_analysis_query']._serialized_options = b'\xe0A\x01'
    _globals['_ANALYZEIAMPOLICYREQUEST'].fields_by_name['execution_timeout']._loaded_options = None
    _globals['_ANALYZEIAMPOLICYREQUEST'].fields_by_name['execution_timeout']._serialized_options = b'\xe0A\x01'
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_GCSDESTINATION'].fields_by_name['uri']._loaded_options = None
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_GCSDESTINATION'].fields_by_name['uri']._serialized_options = b'\xe0A\x02'
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['dataset']._loaded_options = None
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['dataset']._serialized_options = b'\xe0A\x02'
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['table_prefix']._loaded_options = None
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['table_prefix']._serialized_options = b'\xe0A\x02'
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['write_disposition']._loaded_options = None
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['write_disposition']._serialized_options = b'\xe0A\x01'
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST'].fields_by_name['analysis_query']._loaded_options = None
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST'].fields_by_name['analysis_query']._serialized_options = b'\xe0A\x02'
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST'].fields_by_name['saved_analysis_query']._loaded_options = None
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST'].fields_by_name['saved_analysis_query']._serialized_options = b'\xe0A\x01'
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST'].fields_by_name['output_config']._loaded_options = None
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST'].fields_by_name['output_config']._serialized_options = b'\xe0A\x02'
    _globals['_SAVEDQUERY_LABELSENTRY']._loaded_options = None
    _globals['_SAVEDQUERY_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_SAVEDQUERY'].fields_by_name['create_time']._loaded_options = None
    _globals['_SAVEDQUERY'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_SAVEDQUERY'].fields_by_name['creator']._loaded_options = None
    _globals['_SAVEDQUERY'].fields_by_name['creator']._serialized_options = b'\xe0A\x03'
    _globals['_SAVEDQUERY'].fields_by_name['last_update_time']._loaded_options = None
    _globals['_SAVEDQUERY'].fields_by_name['last_update_time']._serialized_options = b'\xe0A\x03'
    _globals['_SAVEDQUERY'].fields_by_name['last_updater']._loaded_options = None
    _globals['_SAVEDQUERY'].fields_by_name['last_updater']._serialized_options = b'\xe0A\x03'
    _globals['_SAVEDQUERY']._loaded_options = None
    _globals['_SAVEDQUERY']._serialized_options = b'\xeaA\xbb\x01\n$cloudasset.googleapis.com/SavedQuery\x12-projects/{project}/savedQueries/{saved_query}\x12+folders/{folder}/savedQueries/{saved_query}\x127organizations/{organization}/savedQueries/{saved_query}'
    _globals['_CREATESAVEDQUERYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESAVEDQUERYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$cloudasset.googleapis.com/SavedQuery'
    _globals['_CREATESAVEDQUERYREQUEST'].fields_by_name['saved_query']._loaded_options = None
    _globals['_CREATESAVEDQUERYREQUEST'].fields_by_name['saved_query']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESAVEDQUERYREQUEST'].fields_by_name['saved_query_id']._loaded_options = None
    _globals['_CREATESAVEDQUERYREQUEST'].fields_by_name['saved_query_id']._serialized_options = b'\xe0A\x02'
    _globals['_GETSAVEDQUERYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSAVEDQUERYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudasset.googleapis.com/SavedQuery'
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$cloudasset.googleapis.com/SavedQuery'
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTSAVEDQUERIESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESAVEDQUERYREQUEST'].fields_by_name['saved_query']._loaded_options = None
    _globals['_UPDATESAVEDQUERYREQUEST'].fields_by_name['saved_query']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESAVEDQUERYREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATESAVEDQUERYREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_DELETESAVEDQUERYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESAVEDQUERYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudasset.googleapis.com/SavedQuery'
    _globals['_ANALYZEMOVEREQUEST'].fields_by_name['resource']._loaded_options = None
    _globals['_ANALYZEMOVEREQUEST'].fields_by_name['resource']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_ANALYZEMOVEREQUEST'].fields_by_name['destination_parent']._loaded_options = None
    _globals['_ANALYZEMOVEREQUEST'].fields_by_name['destination_parent']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_QUERYASSETSOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['dataset']._loaded_options = None
    _globals['_QUERYASSETSOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['dataset']._serialized_options = b'\xe0A\x02'
    _globals['_QUERYASSETSOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['table']._loaded_options = None
    _globals['_QUERYASSETSOUTPUTCONFIG_BIGQUERYDESTINATION'].fields_by_name['table']._serialized_options = b'\xe0A\x02'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1fcloudasset.googleapis.com/Asset'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['statement']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['statement']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['job_reference']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['job_reference']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['timeout']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['timeout']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['read_time_window']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['read_time_window']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['read_time']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['read_time']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYASSETSREQUEST'].fields_by_name['output_config']._loaded_options = None
    _globals['_QUERYASSETSREQUEST'].fields_by_name['output_config']._serialized_options = b'\xe0A\x01'
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESREQUEST'].fields_by_name['scope']._loaded_options = None
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESREQUEST'].fields_by_name['scope']._serialized_options = b'\xe0A\x02\xfaA\x03\x12\x01*'
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESREQUEST'].fields_by_name['names']._loaded_options = None
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESREQUEST'].fields_by_name['names']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_ANALYZEORGPOLICIESREQUEST'].fields_by_name['scope']._loaded_options = None
    _globals['_ANALYZEORGPOLICIESREQUEST'].fields_by_name['scope']._serialized_options = b'\xe0A\x02'
    _globals['_ANALYZEORGPOLICIESREQUEST'].fields_by_name['constraint']._loaded_options = None
    _globals['_ANALYZEORGPOLICIESREQUEST'].fields_by_name['constraint']._serialized_options = b'\xe0A\x02'
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSREQUEST'].fields_by_name['scope']._loaded_options = None
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSREQUEST'].fields_by_name['scope']._serialized_options = b'\xe0A\x02'
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSREQUEST'].fields_by_name['constraint']._loaded_options = None
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSREQUEST'].fields_by_name['constraint']._serialized_options = b'\xe0A\x02'
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSREQUEST'].fields_by_name['scope']._loaded_options = None
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSREQUEST'].fields_by_name['scope']._serialized_options = b'\xe0A\x02'
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSREQUEST'].fields_by_name['constraint']._loaded_options = None
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSREQUEST'].fields_by_name['constraint']._serialized_options = b'\xe0A\x02'
    _globals['_ASSETSERVICE']._loaded_options = None
    _globals['_ASSETSERVICE']._serialized_options = b'\xcaA\x19cloudasset.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_ASSETSERVICE'].methods_by_name['ExportAssets']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['ExportAssets']._serialized_options = b'\xcaAW\n*google.cloud.asset.v1.ExportAssetsResponse\x12)google.cloud.asset.v1.ExportAssetsRequest\x82\xd3\xe4\x93\x02""\x1d/v1/{parent=*/*}:exportAssets:\x01*'
    _globals['_ASSETSERVICE'].methods_by_name['ListAssets']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['ListAssets']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/{parent=*/*}/assets'
    _globals['_ASSETSERVICE'].methods_by_name['BatchGetAssetsHistory']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['BatchGetAssetsHistory']._serialized_options = b'\x82\xd3\xe4\x93\x02(\x12&/v1/{parent=*/*}:batchGetAssetsHistory'
    _globals['_ASSETSERVICE'].methods_by_name['CreateFeed']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['CreateFeed']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\x1b"\x16/v1/{parent=*/*}/feeds:\x01*'
    _globals['_ASSETSERVICE'].methods_by_name['GetFeed']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['GetFeed']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{name=*/*/feeds/*}'
    _globals['_ASSETSERVICE'].methods_by_name['ListFeeds']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['ListFeeds']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{parent=*/*}/feeds'
    _globals['_ASSETSERVICE'].methods_by_name['UpdateFeed']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['UpdateFeed']._serialized_options = b'\xdaA\x04feed\x82\xd3\xe4\x93\x02 2\x1b/v1/{feed.name=*/*/feeds/*}:\x01*'
    _globals['_ASSETSERVICE'].methods_by_name['DeleteFeed']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['DeleteFeed']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x18*\x16/v1/{name=*/*/feeds/*}'
    _globals['_ASSETSERVICE'].methods_by_name['SearchAllResources']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['SearchAllResources']._serialized_options = b'\xdaA\x17scope,query,asset_types\x82\xd3\xe4\x93\x02$\x12"/v1/{scope=*/*}:searchAllResources'
    _globals['_ASSETSERVICE'].methods_by_name['SearchAllIamPolicies']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['SearchAllIamPolicies']._serialized_options = b'\xdaA\x0bscope,query\x82\xd3\xe4\x93\x02&\x12$/v1/{scope=*/*}:searchAllIamPolicies'
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeIamPolicy']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeIamPolicy']._serialized_options = b'\x82\xd3\xe4\x93\x021\x12//v1/{analysis_query.scope=*/*}:analyzeIamPolicy'
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeIamPolicyLongrunning']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeIamPolicyLongrunning']._serialized_options = b'\xcaAv\n9google.cloud.asset.v1.AnalyzeIamPolicyLongrunningResponse\x129google.cloud.asset.v1.AnalyzeIamPolicyLongrunningMetadata\x82\xd3\xe4\x93\x02?":/v1/{analysis_query.scope=*/*}:analyzeIamPolicyLongrunning:\x01*'
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeMove']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeMove']._serialized_options = b'\x82\xd3\xe4\x93\x02 \x12\x1e/v1/{resource=*/*}:analyzeMove'
    _globals['_ASSETSERVICE'].methods_by_name['QueryAssets']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['QueryAssets']._serialized_options = b'\x82\xd3\xe4\x93\x02!"\x1c/v1/{parent=*/*}:queryAssets:\x01*'
    _globals['_ASSETSERVICE'].methods_by_name['CreateSavedQuery']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['CreateSavedQuery']._serialized_options = b'\xdaA!parent,saved_query,saved_query_id\x82\xd3\xe4\x93\x02,"\x1d/v1/{parent=*/*}/savedQueries:\x0bsaved_query'
    _globals['_ASSETSERVICE'].methods_by_name['GetSavedQuery']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['GetSavedQuery']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/{name=*/*/savedQueries/*}'
    _globals['_ASSETSERVICE'].methods_by_name['ListSavedQueries']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['ListSavedQueries']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/{parent=*/*}/savedQueries'
    _globals['_ASSETSERVICE'].methods_by_name['UpdateSavedQuery']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['UpdateSavedQuery']._serialized_options = b'\xdaA\x17saved_query,update_mask\x82\xd3\xe4\x93\x0282)/v1/{saved_query.name=*/*/savedQueries/*}:\x0bsaved_query'
    _globals['_ASSETSERVICE'].methods_by_name['DeleteSavedQuery']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['DeleteSavedQuery']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/{name=*/*/savedQueries/*}'
    _globals['_ASSETSERVICE'].methods_by_name['BatchGetEffectiveIamPolicies']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['BatchGetEffectiveIamPolicies']._serialized_options = b'\x82\xd3\xe4\x93\x02/\x12-/v1/{scope=*/*}/effectiveIamPolicies:batchGet'
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeOrgPolicies']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeOrgPolicies']._serialized_options = b'\xdaA\x17scope,constraint,filter\x82\xd3\xe4\x93\x02$\x12"/v1/{scope=*/*}:analyzeOrgPolicies'
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeOrgPolicyGovernedContainers']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeOrgPolicyGovernedContainers']._serialized_options = b'\xdaA\x17scope,constraint,filter\x82\xd3\xe4\x93\x024\x122/v1/{scope=*/*}:analyzeOrgPolicyGovernedContainers'
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeOrgPolicyGovernedAssets']._loaded_options = None
    _globals['_ASSETSERVICE'].methods_by_name['AnalyzeOrgPolicyGovernedAssets']._serialized_options = b'\xdaA\x17scope,constraint,filter\x82\xd3\xe4\x93\x020\x12./v1/{scope=*/*}:analyzeOrgPolicyGovernedAssets'
    _globals['_CONTENTTYPE']._serialized_start = 14975
    _globals['_CONTENTTYPE']._serialized_end = 15119
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGMETADATA']._serialized_start = 491
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGMETADATA']._serialized_end = 582
    _globals['_EXPORTASSETSREQUEST']._serialized_start = 585
    _globals['_EXPORTASSETSREQUEST']._serialized_end = 882
    _globals['_EXPORTASSETSRESPONSE']._serialized_start = 885
    _globals['_EXPORTASSETSRESPONSE']._serialized_end = 1074
    _globals['_LISTASSETSREQUEST']._serialized_start = 1077
    _globals['_LISTASSETSREQUEST']._serialized_end = 1346
    _globals['_LISTASSETSRESPONSE']._serialized_start = 1349
    _globals['_LISTASSETSRESPONSE']._serialized_end = 1487
    _globals['_BATCHGETASSETSHISTORYREQUEST']._serialized_start = 1490
    _globals['_BATCHGETASSETSHISTORYREQUEST']._serialized_end = 1760
    _globals['_BATCHGETASSETSHISTORYRESPONSE']._serialized_start = 1762
    _globals['_BATCHGETASSETSHISTORYRESPONSE']._serialized_end = 1847
    _globals['_CREATEFEEDREQUEST']._serialized_start = 1849
    _globals['_CREATEFEEDREQUEST']._serialized_end = 1959
    _globals['_GETFEEDREQUEST']._serialized_start = 1961
    _globals['_GETFEEDREQUEST']._serialized_end = 2031
    _globals['_LISTFEEDSREQUEST']._serialized_start = 2033
    _globals['_LISTFEEDSREQUEST']._serialized_end = 2072
    _globals['_LISTFEEDSRESPONSE']._serialized_start = 2074
    _globals['_LISTFEEDSRESPONSE']._serialized_end = 2137
    _globals['_UPDATEFEEDREQUEST']._serialized_start = 2139
    _globals['_UPDATEFEEDREQUEST']._serialized_end = 2260
    _globals['_DELETEFEEDREQUEST']._serialized_start = 2262
    _globals['_DELETEFEEDREQUEST']._serialized_end = 2335
    _globals['_OUTPUTCONFIG']._serialized_start = 2338
    _globals['_OUTPUTCONFIG']._serialized_end = 2509
    _globals['_OUTPUTRESULT']._serialized_start = 2511
    _globals['_OUTPUTRESULT']._serialized_end = 2597
    _globals['_GCSOUTPUTRESULT']._serialized_start = 2599
    _globals['_GCSOUTPUTRESULT']._serialized_end = 2630
    _globals['_GCSDESTINATION']._serialized_start = 2632
    _globals['_GCSDESTINATION']._serialized_end = 2699
    _globals['_BIGQUERYDESTINATION']._serialized_start = 2702
    _globals['_BIGQUERYDESTINATION']._serialized_end = 2882
    _globals['_PARTITIONSPEC']._serialized_start = 2885
    _globals['_PARTITIONSPEC']._serialized_end = 3054
    _globals['_PARTITIONSPEC_PARTITIONKEY']._serialized_start = 2976
    _globals['_PARTITIONSPEC_PARTITIONKEY']._serialized_end = 3054
    _globals['_PUBSUBDESTINATION']._serialized_start = 3056
    _globals['_PUBSUBDESTINATION']._serialized_end = 3090
    _globals['_FEEDOUTPUTCONFIG']._serialized_start = 3092
    _globals['_FEEDOUTPUTCONFIG']._serialized_end = 3197
    _globals['_FEED']._serialized_start = 3200
    _globals['_FEED']._serialized_end = 3613
    _globals['_SEARCHALLRESOURCESREQUEST']._serialized_start = 3616
    _globals['_SEARCHALLRESOURCESREQUEST']._serialized_end = 3833
    _globals['_SEARCHALLRESOURCESRESPONSE']._serialized_start = 3835
    _globals['_SEARCHALLRESOURCESRESPONSE']._serialized_end = 3950
    _globals['_SEARCHALLIAMPOLICIESREQUEST']._serialized_start = 3953
    _globals['_SEARCHALLIAMPOLICIESREQUEST']._serialized_end = 4120
    _globals['_SEARCHALLIAMPOLICIESRESPONSE']._serialized_start = 4122
    _globals['_SEARCHALLIAMPOLICIESRESPONSE']._serialized_end = 4240
    _globals['_IAMPOLICYANALYSISQUERY']._serialized_start = 4243
    _globals['_IAMPOLICYANALYSISQUERY']._serialized_end = 5209
    _globals['_IAMPOLICYANALYSISQUERY_RESOURCESELECTOR']._serialized_start = 4746
    _globals['_IAMPOLICYANALYSISQUERY_RESOURCESELECTOR']._serialized_end = 4797
    _globals['_IAMPOLICYANALYSISQUERY_IDENTITYSELECTOR']._serialized_start = 4799
    _globals['_IAMPOLICYANALYSISQUERY_IDENTITYSELECTOR']._serialized_end = 4840
    _globals['_IAMPOLICYANALYSISQUERY_ACCESSSELECTOR']._serialized_start = 4842
    _globals['_IAMPOLICYANALYSISQUERY_ACCESSSELECTOR']._serialized_end = 4904
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS']._serialized_start = 4907
    _globals['_IAMPOLICYANALYSISQUERY_OPTIONS']._serialized_end = 5123
    _globals['_IAMPOLICYANALYSISQUERY_CONDITIONCONTEXT']._serialized_start = 5125
    _globals['_IAMPOLICYANALYSISQUERY_CONDITIONCONTEXT']._serialized_end = 5209
    _globals['_ANALYZEIAMPOLICYREQUEST']._serialized_start = 5212
    _globals['_ANALYZEIAMPOLICYREQUEST']._serialized_end = 5407
    _globals['_ANALYZEIAMPOLICYRESPONSE']._serialized_start = 5410
    _globals['_ANALYZEIAMPOLICYRESPONSE']._serialized_end = 5932
    _globals['_ANALYZEIAMPOLICYRESPONSE_IAMPOLICYANALYSIS']._serialized_start = 5668
    _globals['_ANALYZEIAMPOLICYRESPONSE_IAMPOLICYANALYSIS']._serialized_end = 5932
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG']._serialized_start = 5935
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG']._serialized_end = 6499
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_GCSDESTINATION']._serialized_start = 6170
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_GCSDESTINATION']._serialized_end = 6204
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION']._serialized_start = 6207
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION']._serialized_end = 6484
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION_PARTITIONKEY']._serialized_start = 6421
    _globals['_IAMPOLICYANALYSISOUTPUTCONFIG_BIGQUERYDESTINATION_PARTITIONKEY']._serialized_end = 6484
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST']._serialized_start = 6502
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGREQUEST']._serialized_end = 6731
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGRESPONSE']._serialized_start = 6733
    _globals['_ANALYZEIAMPOLICYLONGRUNNINGRESPONSE']._serialized_end = 6770
    _globals['_SAVEDQUERY']._serialized_start = 6773
    _globals['_SAVEDQUERY']._serialized_end = 7468
    _globals['_SAVEDQUERY_QUERYCONTENT']._serialized_start = 7112
    _globals['_SAVEDQUERY_QUERYCONTENT']._serialized_end = 7227
    _globals['_SAVEDQUERY_LABELSENTRY']._serialized_start = 7229
    _globals['_SAVEDQUERY_LABELSENTRY']._serialized_end = 7274
    _globals['_CREATESAVEDQUERYREQUEST']._serialized_start = 7471
    _globals['_CREATESAVEDQUERYREQUEST']._serialized_end = 7648
    _globals['_GETSAVEDQUERYREQUEST']._serialized_start = 7650
    _globals['_GETSAVEDQUERYREQUEST']._serialized_end = 7732
    _globals['_LISTSAVEDQUERIESREQUEST']._serialized_start = 7735
    _globals['_LISTSAVEDQUERIESREQUEST']._serialized_end = 7892
    _globals['_LISTSAVEDQUERIESRESPONSE']._serialized_start = 7894
    _globals['_LISTSAVEDQUERIESRESPONSE']._serialized_end = 8003
    _globals['_UPDATESAVEDQUERYREQUEST']._serialized_start = 8006
    _globals['_UPDATESAVEDQUERYREQUEST']._serialized_end = 8146
    _globals['_DELETESAVEDQUERYREQUEST']._serialized_start = 8148
    _globals['_DELETESAVEDQUERYREQUEST']._serialized_end = 8233
    _globals['_ANALYZEMOVEREQUEST']._serialized_start = 8236
    _globals['_ANALYZEMOVEREQUEST']._serialized_end = 8504
    _globals['_ANALYZEMOVEREQUEST_ANALYSISVIEW']._serialized_start = 8438
    _globals['_ANALYZEMOVEREQUEST_ANALYSISVIEW']._serialized_end = 8504
    _globals['_ANALYZEMOVERESPONSE']._serialized_start = 8506
    _globals['_ANALYZEMOVERESPONSE']._serialized_end = 8587
    _globals['_MOVEANALYSIS']._serialized_start = 8590
    _globals['_MOVEANALYSIS']._serialized_end = 8736
    _globals['_MOVEANALYSISRESULT']._serialized_start = 8738
    _globals['_MOVEANALYSISRESULT']._serialized_end = 8864
    _globals['_MOVEIMPACT']._serialized_start = 8866
    _globals['_MOVEIMPACT']._serialized_end = 8894
    _globals['_QUERYASSETSOUTPUTCONFIG']._serialized_start = 8897
    _globals['_QUERYASSETSOUTPUTCONFIG']._serialized_end = 9112
    _globals['_QUERYASSETSOUTPUTCONFIG_BIGQUERYDESTINATION']._serialized_start = 9022
    _globals['_QUERYASSETSOUTPUTCONFIG_BIGQUERYDESTINATION']._serialized_end = 9112
    _globals['_QUERYASSETSREQUEST']._serialized_start = 9115
    _globals['_QUERYASSETSREQUEST']._serialized_end = 9561
    _globals['_QUERYASSETSRESPONSE']._serialized_start = 9564
    _globals['_QUERYASSETSRESPONSE']._serialized_end = 9804
    _globals['_QUERYRESULT']._serialized_start = 9807
    _globals['_QUERYRESULT']._serialized_end = 9956
    _globals['_TABLESCHEMA']._serialized_start = 9958
    _globals['_TABLESCHEMA']._serialized_end = 10028
    _globals['_TABLEFIELDSCHEMA']._serialized_start = 10030
    _globals['_TABLEFIELDSCHEMA']._serialized_end = 10148
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESREQUEST']._serialized_start = 10150
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESREQUEST']._serialized_end = 10239
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESRESPONSE']._serialized_start = 10242
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESRESPONSE']._serialized_end = 10624
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESRESPONSE_EFFECTIVEIAMPOLICY']._serialized_start = 10387
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESRESPONSE_EFFECTIVEIAMPOLICY']._serialized_end = 10624
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESRESPONSE_EFFECTIVEIAMPOLICY_POLICYINFO']._serialized_start = 10546
    _globals['_BATCHGETEFFECTIVEIAMPOLICIESRESPONSE_EFFECTIVEIAMPOLICY_POLICYINFO']._serialized_end = 10624
    _globals['_ANALYZERORGPOLICY']._serialized_start = 10627
    _globals['_ANALYZERORGPOLICY']._serialized_end = 11135
    _globals['_ANALYZERORGPOLICY_RULE']._serialized_start = 10808
    _globals['_ANALYZERORGPOLICY_RULE']._serialized_end = 11135
    _globals['_ANALYZERORGPOLICY_RULE_STRINGVALUES']._serialized_start = 11066
    _globals['_ANALYZERORGPOLICY_RULE_STRINGVALUES']._serialized_end = 11127
    _globals['_ANALYZERORGPOLICYCONSTRAINT']._serialized_start = 11138
    _globals['_ANALYZERORGPOLICYCONSTRAINT']._serialized_end = 12470
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT']._serialized_start = 11368
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT']._serialized_end = 11943
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT_LISTCONSTRAINT']._serialized_start = 11764
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT_LISTCONSTRAINT']._serialized_end = 11825
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT_BOOLEANCONSTRAINT']._serialized_start = 11827
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT_BOOLEANCONSTRAINT']._serialized_end = 11846
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT_CONSTRAINTDEFAULT']._serialized_start = 11848
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CONSTRAINT_CONSTRAINTDEFAULT']._serialized_end = 11924
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CUSTOMCONSTRAINT']._serialized_start = 11946
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CUSTOMCONSTRAINT']._serialized_end = 12445
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CUSTOMCONSTRAINT_METHODTYPE']._serialized_start = 12269
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CUSTOMCONSTRAINT_METHODTYPE']._serialized_end = 12381
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CUSTOMCONSTRAINT_ACTIONTYPE']._serialized_start = 12383
    _globals['_ANALYZERORGPOLICYCONSTRAINT_CUSTOMCONSTRAINT_ACTIONTYPE']._serialized_end = 12445
    _globals['_ANALYZEORGPOLICIESREQUEST']._serialized_start = 12473
    _globals['_ANALYZEORGPOLICIESREQUEST']._serialized_end = 12619
    _globals['_ANALYZEORGPOLICIESRESPONSE']._serialized_start = 12622
    _globals['_ANALYZEORGPOLICIESRESPONSE']._serialized_end = 13054
    _globals['_ANALYZEORGPOLICIESRESPONSE_ORGPOLICYRESULT']._serialized_start = 12845
    _globals['_ANALYZEORGPOLICIESRESPONSE_ORGPOLICYRESULT']._serialized_end = 13054
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSREQUEST']._serialized_start = 13057
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSREQUEST']._serialized_end = 13219
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSRESPONSE']._serialized_start = 13222
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSRESPONSE']._serialized_end = 13803
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSRESPONSE_GOVERNEDCONTAINER']._serialized_start = 13480
    _globals['_ANALYZEORGPOLICYGOVERNEDCONTAINERSRESPONSE_GOVERNEDCONTAINER']._serialized_end = 13803
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSREQUEST']._serialized_start = 13806
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSREQUEST']._serialized_end = 13964
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE']._serialized_start = 13967
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE']._serialized_end = 14972
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE_GOVERNEDRESOURCE']._serialized_start = 14209
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE_GOVERNEDRESOURCE']._serialized_end = 14415
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE_GOVERNEDIAMPOLICY']._serialized_start = 14418
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE_GOVERNEDIAMPOLICY']._serialized_end = 14579
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE_GOVERNEDASSET']._serialized_start = 14582
    _globals['_ANALYZEORGPOLICYGOVERNEDASSETSRESPONSE_GOVERNEDASSET']._serialized_end = 14972
    _globals['_ASSETSERVICE']._serialized_start = 15122
    _globals['_ASSETSERVICE']._serialized_end = 19299