if(NOT ENABLE_GPERFTOOLS)
    message(STATUS "gperftools profiling support disabled by option")
    set(SAGE_GPERFTOOLS_LIBS "")
    return()
endif()

find_library(SAGE_GPERFTOOLS_PROFILER_LIB profiler)
find_library(SAGE_GPERFTOOLS_TCMALLOC_LIB tcmalloc)

if(SAGE_GPERFTOOLS_PROFILER_LIB AND SAGE_GPERFTOOLS_TCMALLOC_LIB)
    set(SAGE_GPERFTOOLS_LIBS ${SAGE_GPERFTOOLS_PROFILER_LIB} ${SAGE_GPERFTOOLS_TCMALLOC_LIB})
    message(STATUS "gperftools found for sage_flow: ${SAGE_GPERFTOOLS_LIBS}")
elseif(NOT SAGE_GPERFTOOLS_PROFILER_LIB)
    message(WARNING "Profiler library not found. Disabling gperftools support.")
    set(SAGE_GPERFTOOLS_LIBS "")
    set(ENABLE_GPERFTOOLS OFF CACHE BOOL "Enable gperftools profiling support" FORCE)
elseif(NOT SAGE_GPERFTOOLS_TCMALLOC_LIB)
    message(WARNING "TCMalloc library not found. Disabling gperftools support.")
    set(SAGE_GPERFTOOLS_LIBS "")
    set(ENABLE_GPERFTOOLS OFF CACHE BOOL "Enable gperftools profiling support" FORCE)
endif()