"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/gkebackup/v1/gkebackup.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.gkebackup.v1 import backup_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_backup__pb2
from .....google.cloud.gkebackup.v1 import backup_channel_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_backup__channel__pb2
from .....google.cloud.gkebackup.v1 import backup_plan_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_backup__plan__pb2
from .....google.cloud.gkebackup.v1 import backup_plan_binding_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_backup__plan__binding__pb2
from .....google.cloud.gkebackup.v1 import restore_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_restore__pb2
from .....google.cloud.gkebackup.v1 import restore_channel_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_restore__channel__pb2
from .....google.cloud.gkebackup.v1 import restore_plan_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_restore__plan__pb2
from .....google.cloud.gkebackup.v1 import restore_plan_binding_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_restore__plan__binding__pb2
from .....google.cloud.gkebackup.v1 import volume_pb2 as google_dot_cloud_dot_gkebackup_dot_v1_dot_volume__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)google/cloud/gkebackup/v1/gkebackup.proto\x12\x19google.cloud.gkebackup.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a&google/cloud/gkebackup/v1/backup.proto\x1a.google/cloud/gkebackup/v1/backup_channel.proto\x1a+google/cloud/gkebackup/v1/backup_plan.proto\x1a3google/cloud/gkebackup/v1/backup_plan_binding.proto\x1a\'google/cloud/gkebackup/v1/restore.proto\x1a/google/cloud/gkebackup/v1/restore_channel.proto\x1a,google/cloud/gkebackup/v1/restore_plan.proto\x1a4google/cloud/gkebackup/v1/restore_plan_binding.proto\x1a&google/cloud/gkebackup/v1/volume.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x80\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x03"\xb2\x01\n\x17CreateBackupPlanRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12?\n\x0bbackup_plan\x18\x02 \x01(\x0b2%.google.cloud.gkebackup.v1.BackupPlanB\x03\xe0A\x02\x12\x1b\n\x0ebackup_plan_id\x18\x03 \x01(\tB\x03\xe0A\x02"\xb0\x01\n\x16ListBackupPlansRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x84\x01\n\x17ListBackupPlansResponse\x12;\n\x0cbackup_plans\x18\x01 \x03(\x0b2%.google.cloud.gkebackup.v1.BackupPlan\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"Q\n\x14GetBackupPlanRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan"\x90\x01\n\x17UpdateBackupPlanRequest\x12?\n\x0bbackup_plan\x18\x01 \x01(\x0b2%.google.cloud.gkebackup.v1.BackupPlanB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"g\n\x17DeleteBackupPlanRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01"\xbe\x01\n\x1aCreateBackupChannelRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12E\n\x0ebackup_channel\x18\x02 \x01(\x0b2(.google.cloud.gkebackup.v1.BackupChannelB\x03\xe0A\x02\x12\x1e\n\x11backup_channel_id\x18\x03 \x01(\tB\x03\xe0A\x01"\xb3\x01\n\x19ListBackupChannelsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x8d\x01\n\x1aListBackupChannelsResponse\x12A\n\x0fbackup_channels\x18\x01 \x03(\x0b2(.google.cloud.gkebackup.v1.BackupChannel\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"W\n\x17GetBackupChannelRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/BackupChannel"\x99\x01\n\x1aUpdateBackupChannelRequest\x12E\n\x0ebackup_channel\x18\x01 \x01(\x0b2(.google.cloud.gkebackup.v1.BackupChannelB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"\x81\x01\n\x1aDeleteBackupChannelRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/BackupChannel\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"\xbc\x01\n\x1dListBackupPlanBindingsRequest\x12>\n\x06parent\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/BackupChannel\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x9a\x01\n\x1eListBackupPlanBindingsResponse\x12J\n\x14backup_plan_bindings\x18\x01 \x03(\x0b2,.google.cloud.gkebackup.v1.BackupPlanBinding\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"_\n\x1bGetBackupPlanBindingRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*gkebackup.googleapis.com/BackupPlanBinding"\xa2\x01\n\x13CreateBackupRequest\x12;\n\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan\x126\n\x06backup\x18\x02 \x01(\x0b2!.google.cloud.gkebackup.v1.BackupB\x03\xe0A\x01\x12\x16\n\tbackup_id\x18\x03 \x01(\tB\x03\xe0A\x01"\xd3\x01\n\x12ListBackupsRequest\x12;\n\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01\x12#\n\x16return_partial_success\x18\x06 \x01(\x08B\x03\xe0A\x01"w\n\x13ListBackupsResponse\x122\n\x07backups\x18\x01 \x03(\x0b2!.google.cloud.gkebackup.v1.Backup\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"I\n\x10GetBackupRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup"\x83\x01\n\x13UpdateBackupRequest\x126\n\x06backup\x18\x01 \x01(\x0b2!.google.cloud.gkebackup.v1.BackupB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"s\n\x13DeleteBackupRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"\xb0\x01\n\x18ListVolumeBackupsRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"u\n\x19ListVolumeBackupsResponse\x12?\n\x0evolume_backups\x18\x01 \x03(\x0b2\'.google.cloud.gkebackup.v1.VolumeBackup\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"U\n\x16GetVolumeBackupRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%gkebackup.googleapis.com/VolumeBackup"\xb6\x01\n\x18CreateRestorePlanRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12A\n\x0crestore_plan\x18\x02 \x01(\x0b2&.google.cloud.gkebackup.v1.RestorePlanB\x03\xe0A\x02\x12\x1c\n\x0frestore_plan_id\x18\x03 \x01(\tB\x03\xe0A\x02"\xb1\x01\n\x17ListRestorePlansRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x87\x01\n\x18ListRestorePlansResponse\x12=\n\rrestore_plans\x18\x01 \x03(\x0b2&.google.cloud.gkebackup.v1.RestorePlan\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"S\n\x15GetRestorePlanRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan"\x93\x01\n\x18UpdateRestorePlanRequest\x12A\n\x0crestore_plan\x18\x01 \x01(\x0b2&.google.cloud.gkebackup.v1.RestorePlanB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"}\n\x18DeleteRestorePlanRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"\xc2\x01\n\x1bCreateRestoreChannelRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12G\n\x0frestore_channel\x18\x02 \x01(\x0b2).google.cloud.gkebackup.v1.RestoreChannelB\x03\xe0A\x02\x12\x1f\n\x12restore_channel_id\x18\x03 \x01(\tB\x03\xe0A\x01"\xb4\x01\n\x1aListRestoreChannelsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x90\x01\n\x1bListRestoreChannelsResponse\x12C\n\x10restore_channels\x18\x01 \x03(\x0b2).google.cloud.gkebackup.v1.RestoreChannel\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"Y\n\x18GetRestoreChannelRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'gkebackup.googleapis.com/RestoreChannel"\x9c\x01\n\x1bUpdateRestoreChannelRequest\x12G\n\x0frestore_channel\x18\x01 \x01(\x0b2).google.cloud.gkebackup.v1.RestoreChannelB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"o\n\x1bDeleteRestoreChannelRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'gkebackup.googleapis.com/RestoreChannel\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01"\xbe\x01\n\x1eListRestorePlanBindingsRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'gkebackup.googleapis.com/RestoreChannel\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\xa2\x01\n\x1fListRestorePlanBindingsResponse\x12L\n\x15restore_plan_bindings\x18\x01 \x03(\x0b2-.google.cloud.gkebackup.v1.RestorePlanBinding\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x18\n\x0bunreachable\x18\x03 \x03(\tB\x03\xe0A\x06"a\n\x1cGetRestorePlanBindingRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+gkebackup.googleapis.com/RestorePlanBinding"\xa7\x01\n\x14CreateRestoreRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan\x128\n\x07restore\x18\x02 \x01(\x0b2".google.cloud.gkebackup.v1.RestoreB\x03\xe0A\x02\x12\x17\n\nrestore_id\x18\x03 \x01(\tB\x03\xe0A\x02"\xb0\x01\n\x13ListRestoresRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"z\n\x14ListRestoresResponse\x124\n\x08restores\x18\x01 \x03(\x0b2".google.cloud.gkebackup.v1.Restore\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"K\n\x11GetRestoreRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n gkebackup.googleapis.com/Restore"\x86\x01\n\x14UpdateRestoreRequest\x128\n\x07restore\x18\x01 \x01(\x0b2".google.cloud.gkebackup.v1.RestoreB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"u\n\x14DeleteRestoreRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n gkebackup.googleapis.com/Restore\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"\xb2\x01\n\x19ListVolumeRestoresRequest\x128\n\x06parent\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n gkebackup.googleapis.com/Restore\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"x\n\x1aListVolumeRestoresResponse\x12A\n\x0fvolume_restores\x18\x01 \x03(\x0b2(.google.cloud.gkebackup.v1.VolumeRestore\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"W\n\x17GetVolumeRestoreRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/VolumeRestore"[\n GetBackupIndexDownloadUrlRequest\x127\n\x06backup\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup"<\n!GetBackupIndexDownloadUrlResponse\x12\x17\n\nsigned_url\x18\x01 \x01(\tB\x03\xe0A\x022\xd1C\n\x0cBackupForGKE\x12\xf2\x01\n\x10CreateBackupPlan\x122.google.cloud.gkebackup.v1.CreateBackupPlanRequest\x1a\x1d.google.longrunning.Operation"\x8a\x01\xcaA\x1f\n\nBackupPlan\x12\x11OperationMetadata\xdaA!parent,backup_plan,backup_plan_id\x82\xd3\xe4\x93\x02>"//v1/{parent=projects/*/locations/*}/backupPlans:\x0bbackup_plan\x12\xba\x01\n\x0fListBackupPlans\x121.google.cloud.gkebackup.v1.ListBackupPlansRequest\x1a2.google.cloud.gkebackup.v1.ListBackupPlansResponse"@\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v1/{parent=projects/*/locations/*}/backupPlans\x12\xa7\x01\n\rGetBackupPlan\x12/.google.cloud.gkebackup.v1.GetBackupPlanRequest\x1a%.google.cloud.gkebackup.v1.BackupPlan">\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v1/{name=projects/*/locations/*/backupPlans/*}\x12\xf4\x01\n\x10UpdateBackupPlan\x122.google.cloud.gkebackup.v1.UpdateBackupPlanRequest\x1a\x1d.google.longrunning.Operation"\x8c\x01\xcaA\x1f\n\nBackupPlan\x12\x11OperationMetadata\xdaA\x17backup_plan,update_mask\x82\xd3\xe4\x93\x02J2;/v1/{backup_plan.name=projects/*/locations/*/backupPlans/*}:\x0bbackup_plan\x12\xd2\x01\n\x10DeleteBackupPlan\x122.google.cloud.gkebackup.v1.DeleteBackupPlanRequest\x1a\x1d.google.longrunning.Operation"k\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x021*//v1/{name=projects/*/locations/*/backupPlans/*}\x12\x87\x02\n\x13CreateBackupChannel\x125.google.cloud.gkebackup.v1.CreateBackupChannelRequest\x1a\x1d.google.longrunning.Operation"\x99\x01\xcaA"\n\rBackupChannel\x12\x11OperationMetadata\xdaA\'parent,backup_channel,backup_channel_id\x82\xd3\xe4\x93\x02D"2/v1/{parent=projects/*/locations/*}/backupChannels:\x0ebackup_channel\x12\xc6\x01\n\x12ListBackupChannels\x124.google.cloud.gkebackup.v1.ListBackupChannelsRequest\x1a5.google.cloud.gkebackup.v1.ListBackupChannelsResponse"C\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1/{parent=projects/*/locations/*}/backupChannels\x12\xb3\x01\n\x10GetBackupChannel\x122.google.cloud.gkebackup.v1.GetBackupChannelRequest\x1a(.google.cloud.gkebackup.v1.BackupChannel"A\xdaA\x04name\x82\xd3\xe4\x93\x024\x122/v1/{name=projects/*/locations/*/backupChannels/*}\x12\x89\x02\n\x13UpdateBackupChannel\x125.google.cloud.gkebackup.v1.UpdateBackupChannelRequest\x1a\x1d.google.longrunning.Operation"\x9b\x01\xcaA"\n\rBackupChannel\x12\x11OperationMetadata\xdaA\x1abackup_channel,update_mask\x82\xd3\xe4\x93\x02S2A/v1/{backup_channel.name=projects/*/locations/*/backupChannels/*}:\x0ebackup_channel\x12\xdb\x01\n\x13DeleteBackupChannel\x125.google.cloud.gkebackup.v1.DeleteBackupChannelRequest\x1a\x1d.google.longrunning.Operation"n\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x024*2/v1/{name=projects/*/locations/*/backupChannels/*}\x12\xe7\x01\n\x16ListBackupPlanBindings\x128.google.cloud.gkebackup.v1.ListBackupPlanBindingsRequest\x1a9.google.cloud.gkebackup.v1.ListBackupPlanBindingsResponse"X\xdaA\x06parent\x82\xd3\xe4\x93\x02I\x12G/v1/{parent=projects/*/locations/*/backupChannels/*}/backupPlanBindings\x12\xd4\x01\n\x14GetBackupPlanBinding\x126.google.cloud.gkebackup.v1.GetBackupPlanBindingRequest\x1a,.google.cloud.gkebackup.v1.BackupPlanBinding"V\xdaA\x04name\x82\xd3\xe4\x93\x02I\x12G/v1/{name=projects/*/locations/*/backupChannels/*/backupPlanBindings/*}\x12\xe1\x01\n\x0cCreateBackup\x12..google.cloud.gkebackup.v1.CreateBackupRequest\x1a\x1d.google.longrunning.Operation"\x81\x01\xcaA\x1b\n\x06Backup\x12\x11OperationMetadata\xdaA\x17parent,backup,backup_id\x82\xd3\xe4\x93\x02C"9/v1/{parent=projects/*/locations/*/backupPlans/*}/backups:\x06backup\x12\xb8\x01\n\x0bListBackups\x12-.google.cloud.gkebackup.v1.ListBackupsRequest\x1a..google.cloud.gkebackup.v1.ListBackupsResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/backupPlans/*}/backups\x12\xa5\x01\n\tGetBackup\x12+.google.cloud.gkebackup.v1.GetBackupRequest\x1a!.google.cloud.gkebackup.v1.Backup"H\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/backupPlans/*/backups/*}\x12\xe3\x01\n\x0cUpdateBackup\x12..google.cloud.gkebackup.v1.UpdateBackupRequest\x1a\x1d.google.longrunning.Operation"\x83\x01\xcaA\x1b\n\x06Backup\x12\x11OperationMetadata\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02J2@/v1/{backup.name=projects/*/locations/*/backupPlans/*/backups/*}:\x06backup\x12\xd4\x01\n\x0cDeleteBackup\x12..google.cloud.gkebackup.v1.DeleteBackupRequest\x1a\x1d.google.longrunning.Operation"u\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02;*9/v1/{name=projects/*/locations/*/backupPlans/*/backups/*}\x12\xda\x01\n\x11ListVolumeBackups\x123.google.cloud.gkebackup.v1.ListVolumeBackupsRequest\x1a4.google.cloud.gkebackup.v1.ListVolumeBackupsResponse"Z\xdaA\x06parent\x82\xd3\xe4\x93\x02K\x12I/v1/{parent=projects/*/locations/*/backupPlans/*/backups/*}/volumeBackups\x12\xc7\x01\n\x0fGetVolumeBackup\x121.google.cloud.gkebackup.v1.GetVolumeBackupRequest\x1a\'.google.cloud.gkebackup.v1.VolumeBackup"X\xdaA\x04name\x82\xd3\xe4\x93\x02K\x12I/v1/{name=projects/*/locations/*/backupPlans/*/backups/*/volumeBackups/*}\x12\xf9\x01\n\x11CreateRestorePlan\x123.google.cloud.gkebackup.v1.CreateRestorePlanRequest\x1a\x1d.google.longrunning.Operation"\x8f\x01\xcaA \n\x0bRestorePlan\x12\x11OperationMetadata\xdaA#parent,restore_plan,restore_plan_id\x82\xd3\xe4\x93\x02@"0/v1/{parent=projects/*/locations/*}/restorePlans:\x0crestore_plan\x12\xbe\x01\n\x10ListRestorePlans\x122.google.cloud.gkebackup.v1.ListRestorePlansRequest\x1a3.google.cloud.gkebackup.v1.ListRestorePlansResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/restorePlans\x12\xab\x01\n\x0eGetRestorePlan\x120.google.cloud.gkebackup.v1.GetRestorePlanRequest\x1a&.google.cloud.gkebackup.v1.RestorePlan"?\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*/restorePlans/*}\x12\xfb\x01\n\x11UpdateRestorePlan\x123.google.cloud.gkebackup.v1.UpdateRestorePlanRequest\x1a\x1d.google.longrunning.Operation"\x91\x01\xcaA \n\x0bRestorePlan\x12\x11OperationMetadata\xdaA\x18restore_plan,update_mask\x82\xd3\xe4\x93\x02M2=/v1/{restore_plan.name=projects/*/locations/*/restorePlans/*}:\x0crestore_plan\x12\xd5\x01\n\x11DeleteRestorePlan\x123.google.cloud.gkebackup.v1.DeleteRestorePlanRequest\x1a\x1d.google.longrunning.Operation"l\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1/{name=projects/*/locations/*/restorePlans/*}\x12\x8e\x02\n\x14CreateRestoreChannel\x126.google.cloud.gkebackup.v1.CreateRestoreChannelRequest\x1a\x1d.google.longrunning.Operation"\x9e\x01\xcaA#\n\x0eRestoreChannel\x12\x11OperationMetadata\xdaA)parent,restore_channel,restore_channel_id\x82\xd3\xe4\x93\x02F"3/v1/{parent=projects/*/locations/*}/restoreChannels:\x0frestore_channel\x12\xca\x01\n\x13ListRestoreChannels\x125.google.cloud.gkebackup.v1.ListRestoreChannelsRequest\x1a6.google.cloud.gkebackup.v1.ListRestoreChannelsResponse"D\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*}/restoreChannels\x12\xb7\x01\n\x11GetRestoreChannel\x123.google.cloud.gkebackup.v1.GetRestoreChannelRequest\x1a).google.cloud.gkebackup.v1.RestoreChannel"B\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/restoreChannels/*}\x12\x90\x02\n\x14UpdateRestoreChannel\x126.google.cloud.gkebackup.v1.UpdateRestoreChannelRequest\x1a\x1d.google.longrunning.Operation"\xa0\x01\xcaA#\n\x0eRestoreChannel\x12\x11OperationMetadata\xdaA\x1brestore_channel,update_mask\x82\xd3\xe4\x93\x02V2C/v1/{restore_channel.name=projects/*/locations/*/restoreChannels/*}:\x0frestore_channel\x12\xde\x01\n\x14DeleteRestoreChannel\x126.google.cloud.gkebackup.v1.DeleteRestoreChannelRequest\x1a\x1d.google.longrunning.Operation"o\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/restoreChannels/*}\x12\xec\x01\n\x17ListRestorePlanBindings\x129.google.cloud.gkebackup.v1.ListRestorePlanBindingsRequest\x1a:.google.cloud.gkebackup.v1.ListRestorePlanBindingsResponse"Z\xdaA\x06parent\x82\xd3\xe4\x93\x02K\x12I/v1/{parent=projects/*/locations/*/restoreChannels/*}/restorePlanBindings\x12\xd9\x01\n\x15GetRestorePlanBinding\x127.google.cloud.gkebackup.v1.GetRestorePlanBindingRequest\x1a-.google.cloud.gkebackup.v1.RestorePlanBinding"X\xdaA\x04name\x82\xd3\xe4\x93\x02K\x12I/v1/{name=projects/*/locations/*/restoreChannels/*/restorePlanBindings/*}\x12\xe9\x01\n\rCreateRestore\x12/.google.cloud.gkebackup.v1.CreateRestoreRequest\x1a\x1d.google.longrunning.Operation"\x87\x01\xcaA\x1c\n\x07Restore\x12\x11OperationMetadata\xdaA\x19parent,restore,restore_id\x82\xd3\xe4\x93\x02F";/v1/{parent=projects/*/locations/*/restorePlans/*}/restores:\x07restore\x12\xbd\x01\n\x0cListRestores\x12..google.cloud.gkebackup.v1.ListRestoresRequest\x1a/.google.cloud.gkebackup.v1.ListRestoresResponse"L\xdaA\x06parent\x82\xd3\xe4\x93\x02=\x12;/v1/{parent=projects/*/locations/*/restorePlans/*}/restores\x12\xaa\x01\n\nGetRestore\x12,.google.cloud.gkebackup.v1.GetRestoreRequest\x1a".google.cloud.gkebackup.v1.Restore"J\xdaA\x04name\x82\xd3\xe4\x93\x02=\x12;/v1/{name=projects/*/locations/*/restorePlans/*/restores/*}\x12\xeb\x01\n\rUpdateRestore\x12/.google.cloud.gkebackup.v1.UpdateRestoreRequest\x1a\x1d.google.longrunning.Operation"\x89\x01\xcaA\x1c\n\x07Restore\x12\x11OperationMetadata\xdaA\x13restore,update_mask\x82\xd3\xe4\x93\x02N2C/v1/{restore.name=projects/*/locations/*/restorePlans/*/restores/*}:\x07restore\x12\xd8\x01\n\rDeleteRestore\x12/.google.cloud.gkebackup.v1.DeleteRestoreRequest\x1a\x1d.google.longrunning.Operation"w\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02=*;/v1/{name=projects/*/locations/*/restorePlans/*/restores/*}\x12\xe0\x01\n\x12ListVolumeRestores\x124.google.cloud.gkebackup.v1.ListVolumeRestoresRequest\x1a5.google.cloud.gkebackup.v1.ListVolumeRestoresResponse"]\xdaA\x06parent\x82\xd3\xe4\x93\x02N\x12L/v1/{parent=projects/*/locations/*/restorePlans/*/restores/*}/volumeRestores\x12\xcd\x01\n\x10GetVolumeRestore\x122.google.cloud.gkebackup.v1.GetVolumeRestoreRequest\x1a(.google.cloud.gkebackup.v1.VolumeRestore"[\xdaA\x04name\x82\xd3\xe4\x93\x02N\x12L/v1/{name=projects/*/locations/*/restorePlans/*/restores/*/volumeRestores/*}\x12\xfe\x01\n\x19GetBackupIndexDownloadUrl\x12;.google.cloud.gkebackup.v1.GetBackupIndexDownloadUrlRequest\x1a<.google.cloud.gkebackup.v1.GetBackupIndexDownloadUrlResponse"f\xdaA\x06backup\x82\xd3\xe4\x93\x02W\x12U/v1/{backup=projects/*/locations/*/backupPlans/*/backups/*}:getBackupIndexDownloadUrl\x1aL\xcaA\x18gkebackup.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xa1\x03\n\x1dcom.google.cloud.gkebackup.v1B\x0eGKEBackupProtoP\x01Z;cloud.google.com/go/gkebackup/apiv1/gkebackuppb;gkebackuppb\xaa\x02\x19Google.Cloud.GkeBackup.V1\xca\x02\x19Google\\Cloud\\GkeBackup\\V1\xea\x02\x1cGoogle::Cloud::GkeBackup::V1\xeaA^\n container.googleapis.com/Cluster\x12:projects/{project}/locations/{location}/clusters/{cluster}\xeaAx\n!cloudkms.googleapis.com/CryptoKey\x12Sprojects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.gkebackup.v1.gkebackup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1dcom.google.cloud.gkebackup.v1B\x0eGKEBackupProtoP\x01Z;cloud.google.com/go/gkebackup/apiv1/gkebackuppb;gkebackuppb\xaa\x02\x19Google.Cloud.GkeBackup.V1\xca\x02\x19Google\\Cloud\\GkeBackup\\V1\xea\x02\x1cGoogle::Cloud::GkeBackup::V1\xeaA^\n container.googleapis.com/Cluster\x12:projects/{project}/locations/{location}/clusters/{cluster}\xeaAx\n!cloudkms.googleapis.com/CryptoKey\x12Sprojects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_CREATEBACKUPPLANREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEBACKUPPLANREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEBACKUPPLANREQUEST'].fields_by_name['backup_plan']._loaded_options = None
    _globals['_CREATEBACKUPPLANREQUEST'].fields_by_name['backup_plan']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEBACKUPPLANREQUEST'].fields_by_name['backup_plan_id']._loaded_options = None
    _globals['_CREATEBACKUPPLANREQUEST'].fields_by_name['backup_plan_id']._serialized_options = b'\xe0A\x02'
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTBACKUPPLANSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETBACKUPPLANREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBACKUPPLANREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan'
    _globals['_UPDATEBACKUPPLANREQUEST'].fields_by_name['backup_plan']._loaded_options = None
    _globals['_UPDATEBACKUPPLANREQUEST'].fields_by_name['backup_plan']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBACKUPPLANREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEBACKUPPLANREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEBACKUPPLANREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEBACKUPPLANREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan'
    _globals['_DELETEBACKUPPLANREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEBACKUPPLANREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEBACKUPCHANNELREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEBACKUPCHANNELREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEBACKUPCHANNELREQUEST'].fields_by_name['backup_channel']._loaded_options = None
    _globals['_CREATEBACKUPCHANNELREQUEST'].fields_by_name['backup_channel']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEBACKUPCHANNELREQUEST'].fields_by_name['backup_channel_id']._loaded_options = None
    _globals['_CREATEBACKUPCHANNELREQUEST'].fields_by_name['backup_channel_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTBACKUPCHANNELSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETBACKUPCHANNELREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBACKUPCHANNELREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/BackupChannel'
    _globals['_UPDATEBACKUPCHANNELREQUEST'].fields_by_name['backup_channel']._loaded_options = None
    _globals['_UPDATEBACKUPCHANNELREQUEST'].fields_by_name['backup_channel']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBACKUPCHANNELREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEBACKUPCHANNELREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEBACKUPCHANNELREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEBACKUPCHANNELREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/BackupChannel'
    _globals['_DELETEBACKUPCHANNELREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEBACKUPCHANNELREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEBACKUPCHANNELREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_DELETEBACKUPCHANNELREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/BackupChannel'
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTBACKUPPLANBINDINGSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETBACKUPPLANBINDINGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBACKUPPLANBINDINGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*gkebackup.googleapis.com/BackupPlanBinding'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\n#gkebackup.googleapis.com/BackupPlan'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['return_partial_success']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['return_partial_success']._serialized_options = b'\xe0A\x01'
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup'
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup'
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTVOLUMEBACKUPSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETVOLUMEBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETVOLUMEBACKUPREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%gkebackup.googleapis.com/VolumeBackup"
    _globals['_CREATERESTOREPLANREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATERESTOREPLANREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATERESTOREPLANREQUEST'].fields_by_name['restore_plan']._loaded_options = None
    _globals['_CREATERESTOREPLANREQUEST'].fields_by_name['restore_plan']._serialized_options = b'\xe0A\x02'
    _globals['_CREATERESTOREPLANREQUEST'].fields_by_name['restore_plan_id']._loaded_options = None
    _globals['_CREATERESTOREPLANREQUEST'].fields_by_name['restore_plan_id']._serialized_options = b'\xe0A\x02'
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTRESTOREPLANSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETRESTOREPLANREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETRESTOREPLANREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan'
    _globals['_UPDATERESTOREPLANREQUEST'].fields_by_name['restore_plan']._loaded_options = None
    _globals['_UPDATERESTOREPLANREQUEST'].fields_by_name['restore_plan']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATERESTOREPLANREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATERESTOREPLANREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETERESTOREPLANREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETERESTOREPLANREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan'
    _globals['_DELETERESTOREPLANREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETERESTOREPLANREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETERESTOREPLANREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_DELETERESTOREPLANREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_CREATERESTORECHANNELREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATERESTORECHANNELREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATERESTORECHANNELREQUEST'].fields_by_name['restore_channel']._loaded_options = None
    _globals['_CREATERESTORECHANNELREQUEST'].fields_by_name['restore_channel']._serialized_options = b'\xe0A\x02'
    _globals['_CREATERESTORECHANNELREQUEST'].fields_by_name['restore_channel_id']._loaded_options = None
    _globals['_CREATERESTORECHANNELREQUEST'].fields_by_name['restore_channel_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTRESTORECHANNELSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETRESTORECHANNELREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETRESTORECHANNELREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'gkebackup.googleapis.com/RestoreChannel"
    _globals['_UPDATERESTORECHANNELREQUEST'].fields_by_name['restore_channel']._loaded_options = None
    _globals['_UPDATERESTORECHANNELREQUEST'].fields_by_name['restore_channel']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATERESTORECHANNELREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATERESTORECHANNELREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETERESTORECHANNELREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETERESTORECHANNELREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'gkebackup.googleapis.com/RestoreChannel"
    _globals['_DELETERESTORECHANNELREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETERESTORECHANNELREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\n'gkebackup.googleapis.com/RestoreChannel"
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTRESTOREPLANBINDINGSREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTOREPLANBINDINGSRESPONSE'].fields_by_name['unreachable']._loaded_options = None
    _globals['_LISTRESTOREPLANBINDINGSRESPONSE'].fields_by_name['unreachable']._serialized_options = b'\xe0A\x06'
    _globals['_GETRESTOREPLANBINDINGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETRESTOREPLANBINDINGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+gkebackup.googleapis.com/RestorePlanBinding'
    _globals['_CREATERESTOREREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATERESTOREREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan'
    _globals['_CREATERESTOREREQUEST'].fields_by_name['restore']._loaded_options = None
    _globals['_CREATERESTOREREQUEST'].fields_by_name['restore']._serialized_options = b'\xe0A\x02'
    _globals['_CREATERESTOREREQUEST'].fields_by_name['restore_id']._loaded_options = None
    _globals['_CREATERESTOREREQUEST'].fields_by_name['restore_id']._serialized_options = b'\xe0A\x02'
    _globals['_LISTRESTORESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTRESTORESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$gkebackup.googleapis.com/RestorePlan'
    _globals['_LISTRESTORESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTRESTORESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTORESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTRESTORESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTORESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTRESTORESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTRESTORESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTRESTORESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETRESTOREREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETRESTOREREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n gkebackup.googleapis.com/Restore'
    _globals['_UPDATERESTOREREQUEST'].fields_by_name['restore']._loaded_options = None
    _globals['_UPDATERESTOREREQUEST'].fields_by_name['restore']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATERESTOREREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATERESTOREREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETERESTOREREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETERESTOREREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n gkebackup.googleapis.com/Restore'
    _globals['_DELETERESTOREREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETERESTOREREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_DELETERESTOREREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_DELETERESTOREREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA"\n gkebackup.googleapis.com/Restore'
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTVOLUMERESTORESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETVOLUMERESTOREREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETVOLUMERESTOREREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&gkebackup.googleapis.com/VolumeRestore'
    _globals['_GETBACKUPINDEXDOWNLOADURLREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_GETBACKUPINDEXDOWNLOADURLREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fgkebackup.googleapis.com/Backup'
    _globals['_GETBACKUPINDEXDOWNLOADURLRESPONSE'].fields_by_name['signed_url']._loaded_options = None
    _globals['_GETBACKUPINDEXDOWNLOADURLRESPONSE'].fields_by_name['signed_url']._serialized_options = b'\xe0A\x02'
    _globals['_BACKUPFORGKE']._loaded_options = None
    _globals['_BACKUPFORGKE']._serialized_options = b'\xcaA\x18gkebackup.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_BACKUPFORGKE'].methods_by_name['CreateBackupPlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['CreateBackupPlan']._serialized_options = b'\xcaA\x1f\n\nBackupPlan\x12\x11OperationMetadata\xdaA!parent,backup_plan,backup_plan_id\x82\xd3\xe4\x93\x02>"//v1/{parent=projects/*/locations/*}/backupPlans:\x0bbackup_plan'
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackupPlans']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackupPlans']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v1/{parent=projects/*/locations/*}/backupPlans'
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupPlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupPlan']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v1/{name=projects/*/locations/*/backupPlans/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateBackupPlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateBackupPlan']._serialized_options = b'\xcaA\x1f\n\nBackupPlan\x12\x11OperationMetadata\xdaA\x17backup_plan,update_mask\x82\xd3\xe4\x93\x02J2;/v1/{backup_plan.name=projects/*/locations/*/backupPlans/*}:\x0bbackup_plan'
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteBackupPlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteBackupPlan']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x021*//v1/{name=projects/*/locations/*/backupPlans/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['CreateBackupChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['CreateBackupChannel']._serialized_options = b'\xcaA"\n\rBackupChannel\x12\x11OperationMetadata\xdaA\'parent,backup_channel,backup_channel_id\x82\xd3\xe4\x93\x02D"2/v1/{parent=projects/*/locations/*}/backupChannels:\x0ebackup_channel'
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackupChannels']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackupChannels']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1/{parent=projects/*/locations/*}/backupChannels'
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupChannel']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x024\x122/v1/{name=projects/*/locations/*/backupChannels/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateBackupChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateBackupChannel']._serialized_options = b'\xcaA"\n\rBackupChannel\x12\x11OperationMetadata\xdaA\x1abackup_channel,update_mask\x82\xd3\xe4\x93\x02S2A/v1/{backup_channel.name=projects/*/locations/*/backupChannels/*}:\x0ebackup_channel'
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteBackupChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteBackupChannel']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x024*2/v1/{name=projects/*/locations/*/backupChannels/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackupPlanBindings']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackupPlanBindings']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02I\x12G/v1/{parent=projects/*/locations/*/backupChannels/*}/backupPlanBindings'
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupPlanBinding']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupPlanBinding']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02I\x12G/v1/{name=projects/*/locations/*/backupChannels/*/backupPlanBindings/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['CreateBackup']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['CreateBackup']._serialized_options = b'\xcaA\x1b\n\x06Backup\x12\x11OperationMetadata\xdaA\x17parent,backup,backup_id\x82\xd3\xe4\x93\x02C"9/v1/{parent=projects/*/locations/*/backupPlans/*}/backups:\x06backup'
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackups']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListBackups']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/backupPlans/*}/backups'
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackup']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackup']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/backupPlans/*/backups/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateBackup']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateBackup']._serialized_options = b'\xcaA\x1b\n\x06Backup\x12\x11OperationMetadata\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02J2@/v1/{backup.name=projects/*/locations/*/backupPlans/*/backups/*}:\x06backup'
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteBackup']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteBackup']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02;*9/v1/{name=projects/*/locations/*/backupPlans/*/backups/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['ListVolumeBackups']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListVolumeBackups']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02K\x12I/v1/{parent=projects/*/locations/*/backupPlans/*/backups/*}/volumeBackups'
    _globals['_BACKUPFORGKE'].methods_by_name['GetVolumeBackup']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetVolumeBackup']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02K\x12I/v1/{name=projects/*/locations/*/backupPlans/*/backups/*/volumeBackups/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['CreateRestorePlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['CreateRestorePlan']._serialized_options = b'\xcaA \n\x0bRestorePlan\x12\x11OperationMetadata\xdaA#parent,restore_plan,restore_plan_id\x82\xd3\xe4\x93\x02@"0/v1/{parent=projects/*/locations/*}/restorePlans:\x0crestore_plan'
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestorePlans']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestorePlans']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/restorePlans'
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestorePlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestorePlan']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*/restorePlans/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateRestorePlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateRestorePlan']._serialized_options = b'\xcaA \n\x0bRestorePlan\x12\x11OperationMetadata\xdaA\x18restore_plan,update_mask\x82\xd3\xe4\x93\x02M2=/v1/{restore_plan.name=projects/*/locations/*/restorePlans/*}:\x0crestore_plan'
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteRestorePlan']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteRestorePlan']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1/{name=projects/*/locations/*/restorePlans/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['CreateRestoreChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['CreateRestoreChannel']._serialized_options = b'\xcaA#\n\x0eRestoreChannel\x12\x11OperationMetadata\xdaA)parent,restore_channel,restore_channel_id\x82\xd3\xe4\x93\x02F"3/v1/{parent=projects/*/locations/*}/restoreChannels:\x0frestore_channel'
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestoreChannels']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestoreChannels']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*}/restoreChannels'
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestoreChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestoreChannel']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/restoreChannels/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateRestoreChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateRestoreChannel']._serialized_options = b'\xcaA#\n\x0eRestoreChannel\x12\x11OperationMetadata\xdaA\x1brestore_channel,update_mask\x82\xd3\xe4\x93\x02V2C/v1/{restore_channel.name=projects/*/locations/*/restoreChannels/*}:\x0frestore_channel'
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteRestoreChannel']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteRestoreChannel']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/restoreChannels/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestorePlanBindings']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestorePlanBindings']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02K\x12I/v1/{parent=projects/*/locations/*/restoreChannels/*}/restorePlanBindings'
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestorePlanBinding']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestorePlanBinding']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02K\x12I/v1/{name=projects/*/locations/*/restoreChannels/*/restorePlanBindings/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['CreateRestore']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['CreateRestore']._serialized_options = b'\xcaA\x1c\n\x07Restore\x12\x11OperationMetadata\xdaA\x19parent,restore,restore_id\x82\xd3\xe4\x93\x02F";/v1/{parent=projects/*/locations/*/restorePlans/*}/restores:\x07restore'
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestores']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListRestores']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02=\x12;/v1/{parent=projects/*/locations/*/restorePlans/*}/restores'
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestore']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetRestore']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02=\x12;/v1/{name=projects/*/locations/*/restorePlans/*/restores/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateRestore']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['UpdateRestore']._serialized_options = b'\xcaA\x1c\n\x07Restore\x12\x11OperationMetadata\xdaA\x13restore,update_mask\x82\xd3\xe4\x93\x02N2C/v1/{restore.name=projects/*/locations/*/restorePlans/*/restores/*}:\x07restore'
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteRestore']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['DeleteRestore']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02=*;/v1/{name=projects/*/locations/*/restorePlans/*/restores/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['ListVolumeRestores']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['ListVolumeRestores']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02N\x12L/v1/{parent=projects/*/locations/*/restorePlans/*/restores/*}/volumeRestores'
    _globals['_BACKUPFORGKE'].methods_by_name['GetVolumeRestore']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetVolumeRestore']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02N\x12L/v1/{name=projects/*/locations/*/restorePlans/*/restores/*/volumeRestores/*}'
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupIndexDownloadUrl']._loaded_options = None
    _globals['_BACKUPFORGKE'].methods_by_name['GetBackupIndexDownloadUrl']._serialized_options = b'\xdaA\x06backup\x82\xd3\xe4\x93\x02W\x12U/v1/{backup=projects/*/locations/*/backupPlans/*/backups/*}:getBackupIndexDownloadUrl'
    _globals['_OPERATIONMETADATA']._serialized_start = 737
    _globals['_OPERATIONMETADATA']._serialized_end = 993
    _globals['_CREATEBACKUPPLANREQUEST']._serialized_start = 996
    _globals['_CREATEBACKUPPLANREQUEST']._serialized_end = 1174
    _globals['_LISTBACKUPPLANSREQUEST']._serialized_start = 1177
    _globals['_LISTBACKUPPLANSREQUEST']._serialized_end = 1353
    _globals['_LISTBACKUPPLANSRESPONSE']._serialized_start = 1356
    _globals['_LISTBACKUPPLANSRESPONSE']._serialized_end = 1488
    _globals['_GETBACKUPPLANREQUEST']._serialized_start = 1490
    _globals['_GETBACKUPPLANREQUEST']._serialized_end = 1571
    _globals['_UPDATEBACKUPPLANREQUEST']._serialized_start = 1574
    _globals['_UPDATEBACKUPPLANREQUEST']._serialized_end = 1718
    _globals['_DELETEBACKUPPLANREQUEST']._serialized_start = 1720
    _globals['_DELETEBACKUPPLANREQUEST']._serialized_end = 1823
    _globals['_CREATEBACKUPCHANNELREQUEST']._serialized_start = 1826
    _globals['_CREATEBACKUPCHANNELREQUEST']._serialized_end = 2016
    _globals['_LISTBACKUPCHANNELSREQUEST']._serialized_start = 2019
    _globals['_LISTBACKUPCHANNELSREQUEST']._serialized_end = 2198
    _globals['_LISTBACKUPCHANNELSRESPONSE']._serialized_start = 2201
    _globals['_LISTBACKUPCHANNELSRESPONSE']._serialized_end = 2342
    _globals['_GETBACKUPCHANNELREQUEST']._serialized_start = 2344
    _globals['_GETBACKUPCHANNELREQUEST']._serialized_end = 2431
    _globals['_UPDATEBACKUPCHANNELREQUEST']._serialized_start = 2434
    _globals['_UPDATEBACKUPCHANNELREQUEST']._serialized_end = 2587
    _globals['_DELETEBACKUPCHANNELREQUEST']._serialized_start = 2590
    _globals['_DELETEBACKUPCHANNELREQUEST']._serialized_end = 2719
    _globals['_LISTBACKUPPLANBINDINGSREQUEST']._serialized_start = 2722
    _globals['_LISTBACKUPPLANBINDINGSREQUEST']._serialized_end = 2910
    _globals['_LISTBACKUPPLANBINDINGSRESPONSE']._serialized_start = 2913
    _globals['_LISTBACKUPPLANBINDINGSRESPONSE']._serialized_end = 3067
    _globals['_GETBACKUPPLANBINDINGREQUEST']._serialized_start = 3069
    _globals['_GETBACKUPPLANBINDINGREQUEST']._serialized_end = 3164
    _globals['_CREATEBACKUPREQUEST']._serialized_start = 3167
    _globals['_CREATEBACKUPREQUEST']._serialized_end = 3329
    _globals['_LISTBACKUPSREQUEST']._serialized_start = 3332
    _globals['_LISTBACKUPSREQUEST']._serialized_end = 3543
    _globals['_LISTBACKUPSRESPONSE']._serialized_start = 3545
    _globals['_LISTBACKUPSRESPONSE']._serialized_end = 3664
    _globals['_GETBACKUPREQUEST']._serialized_start = 3666
    _globals['_GETBACKUPREQUEST']._serialized_end = 3739
    _globals['_UPDATEBACKUPREQUEST']._serialized_start = 3742
    _globals['_UPDATEBACKUPREQUEST']._serialized_end = 3873
    _globals['_DELETEBACKUPREQUEST']._serialized_start = 3875
    _globals['_DELETEBACKUPREQUEST']._serialized_end = 3990
    _globals['_LISTVOLUMEBACKUPSREQUEST']._serialized_start = 3993
    _globals['_LISTVOLUMEBACKUPSREQUEST']._serialized_end = 4169
    _globals['_LISTVOLUMEBACKUPSRESPONSE']._serialized_start = 4171
    _globals['_LISTVOLUMEBACKUPSRESPONSE']._serialized_end = 4288
    _globals['_GETVOLUMEBACKUPREQUEST']._serialized_start = 4290
    _globals['_GETVOLUMEBACKUPREQUEST']._serialized_end = 4375
    _globals['_CREATERESTOREPLANREQUEST']._serialized_start = 4378
    _globals['_CREATERESTOREPLANREQUEST']._serialized_end = 4560
    _globals['_LISTRESTOREPLANSREQUEST']._serialized_start = 4563
    _globals['_LISTRESTOREPLANSREQUEST']._serialized_end = 4740
    _globals['_LISTRESTOREPLANSRESPONSE']._serialized_start = 4743
    _globals['_LISTRESTOREPLANSRESPONSE']._serialized_end = 4878
    _globals['_GETRESTOREPLANREQUEST']._serialized_start = 4880
    _globals['_GETRESTOREPLANREQUEST']._serialized_end = 4963
    _globals['_UPDATERESTOREPLANREQUEST']._serialized_start = 4966
    _globals['_UPDATERESTOREPLANREQUEST']._serialized_end = 5113
    _globals['_DELETERESTOREPLANREQUEST']._serialized_start = 5115
    _globals['_DELETERESTOREPLANREQUEST']._serialized_end = 5240
    _globals['_CREATERESTORECHANNELREQUEST']._serialized_start = 5243
    _globals['_CREATERESTORECHANNELREQUEST']._serialized_end = 5437
    _globals['_LISTRESTORECHANNELSREQUEST']._serialized_start = 5440
    _globals['_LISTRESTORECHANNELSREQUEST']._serialized_end = 5620
    _globals['_LISTRESTORECHANNELSRESPONSE']._serialized_start = 5623
    _globals['_LISTRESTORECHANNELSRESPONSE']._serialized_end = 5767
    _globals['_GETRESTORECHANNELREQUEST']._serialized_start = 5769
    _globals['_GETRESTORECHANNELREQUEST']._serialized_end = 5858
    _globals['_UPDATERESTORECHANNELREQUEST']._serialized_start = 5861
    _globals['_UPDATERESTORECHANNELREQUEST']._serialized_end = 6017
    _globals['_DELETERESTORECHANNELREQUEST']._serialized_start = 6019
    _globals['_DELETERESTORECHANNELREQUEST']._serialized_end = 6130
    _globals['_LISTRESTOREPLANBINDINGSREQUEST']._serialized_start = 6133
    _globals['_LISTRESTOREPLANBINDINGSREQUEST']._serialized_end = 6323
    _globals['_LISTRESTOREPLANBINDINGSRESPONSE']._serialized_start = 6326
    _globals['_LISTRESTOREPLANBINDINGSRESPONSE']._serialized_end = 6488
    _globals['_GETRESTOREPLANBINDINGREQUEST']._serialized_start = 6490
    _globals['_GETRESTOREPLANBINDINGREQUEST']._serialized_end = 6587
    _globals['_CREATERESTOREREQUEST']._serialized_start = 6590
    _globals['_CREATERESTOREREQUEST']._serialized_end = 6757
    _globals['_LISTRESTORESREQUEST']._serialized_start = 6760
    _globals['_LISTRESTORESREQUEST']._serialized_end = 6936
    _globals['_LISTRESTORESRESPONSE']._serialized_start = 6938
    _globals['_LISTRESTORESRESPONSE']._serialized_end = 7060
    _globals['_GETRESTOREREQUEST']._serialized_start = 7062
    _globals['_GETRESTOREREQUEST']._serialized_end = 7137
    _globals['_UPDATERESTOREREQUEST']._serialized_start = 7140
    _globals['_UPDATERESTOREREQUEST']._serialized_end = 7274
    _globals['_DELETERESTOREREQUEST']._serialized_start = 7276
    _globals['_DELETERESTOREREQUEST']._serialized_end = 7393
    _globals['_LISTVOLUMERESTORESREQUEST']._serialized_start = 7396
    _globals['_LISTVOLUMERESTORESREQUEST']._serialized_end = 7574
    _globals['_LISTVOLUMERESTORESRESPONSE']._serialized_start = 7576
    _globals['_LISTVOLUMERESTORESRESPONSE']._serialized_end = 7696
    _globals['_GETVOLUMERESTOREREQUEST']._serialized_start = 7698
    _globals['_GETVOLUMERESTOREREQUEST']._serialized_end = 7785
    _globals['_GETBACKUPINDEXDOWNLOADURLREQUEST']._serialized_start = 7787
    _globals['_GETBACKUPINDEXDOWNLOADURLREQUEST']._serialized_end = 7878
    _globals['_GETBACKUPINDEXDOWNLOADURLRESPONSE']._serialized_start = 7880
    _globals['_GETBACKUPINDEXDOWNLOADURLRESPONSE']._serialized_end = 7940
    _globals['_BACKUPFORGKE']._serialized_start = 7943
    _globals['_BACKUPFORGKE']._serialized_end = 16600