# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages/common/search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages/common/search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmessages/common/search.proto\x12\x15\x63ore_system.common.v1\"?\n\rSearchRequest\x12\x1b\n\x0esearch_keyword\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_search_keyword\"\x8b\x01\n\x0bSortRequest\x12\x17\n\nsort_field\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x41\n\x0esort_direction\x18\x02 \x01(\x0e\x32$.core_system.common.v1.SortDirectionH\x01\x88\x01\x01\x42\r\n\x0b_sort_fieldB\x11\n\x0f_sort_direction*`\n\rSortDirection\x12\x1e\n\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n\x13SORT_DIRECTION_DESC\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.common.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SORTDIRECTION']._serialized_start=262
  _globals['_SORTDIRECTION']._serialized_end=358
  _globals['_SEARCHREQUEST']._serialized_start=55
  _globals['_SEARCHREQUEST']._serialized_end=118
  _globals['_SORTREQUEST']._serialized_start=121
  _globals['_SORTREQUEST']._serialized_end=260
# @@protoc_insertion_point(module_scope)
