"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/domains/v1beta1/domains.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .....google.type import money_pb2 as google_dot_type_dot_money__pb2
from .....google.type import postal_address_pb2 as google_dot_type_dot_postal__address__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*google/cloud/domains/v1beta1/domains.proto\x12\x1cgoogle.cloud.domains.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a#google/longrunning/operations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/type/money.proto\x1a google/type/postal_address.proto"\x93\t\n\x0cRegistration\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0bdomain_name\x18\x02 \x01(\tB\x06\xe0A\x02\xe0A\x05\x124\n\x0bcreate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bexpire_time\x18\x06 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12D\n\x05state\x18\x07 \x01(\x0e20.google.cloud.domains.v1beta1.Registration.StateB\x03\xe0A\x03\x12E\n\x06issues\x18\x08 \x03(\x0e20.google.cloud.domains.v1beta1.Registration.IssueB\x03\xe0A\x03\x12F\n\x06labels\x18\t \x03(\x0b26.google.cloud.domains.v1beta1.Registration.LabelsEntry\x12M\n\x13management_settings\x18\n \x01(\x0b20.google.cloud.domains.v1beta1.ManagementSettings\x12?\n\x0cdns_settings\x18\x0b \x01(\x0b2).google.cloud.domains.v1beta1.DnsSettings\x12L\n\x10contact_settings\x18\x0c \x01(\x0b2-.google.cloud.domains.v1beta1.ContactSettingsB\x03\xe0A\x02\x12T\n\x18pending_contact_settings\x18\r \x01(\x0b2-.google.cloud.domains.v1beta1.ContactSettingsB\x03\xe0A\x03\x12L\n\x11supported_privacy\x18\x0e \x03(\x0e2,.google.cloud.domains.v1beta1.ContactPrivacyB\x03\xe0A\x03\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\xa5\x01\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x18\n\x14REGISTRATION_PENDING\x10\x01\x12\x17\n\x13REGISTRATION_FAILED\x10\x02\x12\x14\n\x10TRANSFER_PENDING\x10\x03\x12\x13\n\x0fTRANSFER_FAILED\x10\x04\x12\n\n\x06ACTIVE\x10\x06\x12\r\n\tSUSPENDED\x10\x07\x12\x0c\n\x08EXPORTED\x10\x08"I\n\x05Issue\x12\x15\n\x11ISSUE_UNSPECIFIED\x10\x00\x12\x13\n\x0fCONTACT_SUPPORT\x10\x01\x12\x14\n\x10UNVERIFIED_EMAIL\x10\x02:n\xeaAk\n#domains.googleapis.com/Registration\x12Dprojects/{project}/locations/{location}/registrations/{registration}"\x9b\x02\n\x12ManagementSettings\x12[\n\x0erenewal_method\x18\x03 \x01(\x0e2>.google.cloud.domains.v1beta1.ManagementSettings.RenewalMethodB\x03\xe0A\x03\x12L\n\x13transfer_lock_state\x18\x04 \x01(\x0e2/.google.cloud.domains.v1beta1.TransferLockState"Z\n\rRenewalMethod\x12\x1e\n\x1aRENEWAL_METHOD_UNSPECIFIED\x10\x00\x12\x15\n\x11AUTOMATIC_RENEWAL\x10\x01\x12\x12\n\x0eMANUAL_RENEWAL\x10\x02"\xc6\n\n\x0bDnsSettings\x12I\n\ncustom_dns\x18\x01 \x01(\x0b23.google.cloud.domains.v1beta1.DnsSettings.CustomDnsH\x00\x12X\n\x12google_domains_dns\x18\x02 \x01(\x0b2:.google.cloud.domains.v1beta1.DnsSettings.GoogleDomainsDnsH\x00\x12J\n\x0cglue_records\x18\x04 \x03(\x0b24.google.cloud.domains.v1beta1.DnsSettings.GlueRecord\x1an\n\tCustomDns\x12\x19\n\x0cname_servers\x18\x01 \x03(\tB\x03\xe0A\x02\x12F\n\nds_records\x18\x02 \x03(\x0b22.google.cloud.domains.v1beta1.DnsSettings.DsRecord\x1a\xc4\x01\n\x10GoogleDomainsDns\x12\x19\n\x0cname_servers\x18\x01 \x03(\tB\x03\xe0A\x03\x12H\n\x08ds_state\x18\x02 \x01(\x0e21.google.cloud.domains.v1beta1.DnsSettings.DsStateB\x03\xe0A\x02\x12K\n\nds_records\x18\x03 \x03(\x0b22.google.cloud.domains.v1beta1.DnsSettings.DsRecordB\x03\xe0A\x03\x1a\xcd\x04\n\x08DsRecord\x12\x0f\n\x07key_tag\x18\x01 \x01(\x05\x12O\n\talgorithm\x18\x02 \x01(\x0e2<.google.cloud.domains.v1beta1.DnsSettings.DsRecord.Algorithm\x12R\n\x0bdigest_type\x18\x03 \x01(\x0e2=.google.cloud.domains.v1beta1.DnsSettings.DsRecord.DigestType\x12\x0e\n\x06digest\x18\x04 \x01(\t"\x9f\x02\n\tAlgorithm\x12\x19\n\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\n\n\x06RSAMD5\x10\x01\x12\x06\n\x02DH\x10\x02\x12\x07\n\x03DSA\x10\x03\x12\x07\n\x03ECC\x10\x04\x12\x0b\n\x07RSASHA1\x10\x05\x12\x10\n\x0cDSANSEC3SHA1\x10\x06\x12\x14\n\x10RSASHA1NSEC3SHA1\x10\x07\x12\r\n\tRSASHA256\x10\x08\x12\r\n\tRSASHA512\x10\n\x12\x0b\n\x07ECCGOST\x10\x0c\x12\x13\n\x0fECDSAP256SHA256\x10\r\x12\x13\n\x0fECDSAP384SHA384\x10\x0e\x12\x0b\n\x07ED25519\x10\x0f\x12\t\n\x05ED448\x10\x10\x12\r\n\x08INDIRECT\x10\xfc\x01\x12\x0f\n\nPRIVATEDNS\x10\xfd\x01\x12\x0f\n\nPRIVATEOID\x10\xfe\x01"Y\n\nDigestType\x12\x1b\n\x17DIGEST_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04SHA1\x10\x01\x12\n\n\x06SHA256\x10\x02\x12\x0c\n\x08GOST3411\x10\x03\x12\n\n\x06SHA384\x10\x04\x1aT\n\nGlueRecord\x12\x16\n\thost_name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\x0eipv4_addresses\x18\x02 \x03(\t\x12\x16\n\x0eipv6_addresses\x18\x03 \x03(\t"Y\n\x07DsState\x12\x18\n\x14DS_STATE_UNSPECIFIED\x10\x00\x12\x1a\n\x16DS_RECORDS_UNPUBLISHED\x10\x01\x12\x18\n\x14DS_RECORDS_PUBLISHED\x10\x02B\x0e\n\x0cdns_provider"\xdf\x03\n\x0fContactSettings\x12B\n\x07privacy\x18\x01 \x01(\x0e2,.google.cloud.domains.v1beta1.ContactPrivacyB\x03\xe0A\x02\x12V\n\x12registrant_contact\x18\x02 \x01(\x0b25.google.cloud.domains.v1beta1.ContactSettings.ContactB\x03\xe0A\x02\x12Q\n\radmin_contact\x18\x03 \x01(\x0b25.google.cloud.domains.v1beta1.ContactSettings.ContactB\x03\xe0A\x02\x12U\n\x11technical_contact\x18\x04 \x01(\x0b25.google.cloud.domains.v1beta1.ContactSettings.ContactB\x03\xe0A\x02\x1a\x85\x01\n\x07Contact\x127\n\x0epostal_address\x18\x01 \x01(\x0b2\x1a.google.type.PostalAddressB\x03\xe0A\x02\x12\x12\n\x05email\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x19\n\x0cphone_number\x18\x03 \x01(\tB\x03\xe0A\x02\x12\x12\n\nfax_number\x18\x04 \x01(\t"g\n\x14SearchDomainsRequest\x12\x12\n\x05query\x18\x01 \x01(\tB\x03\xe0A\x02\x12;\n\x08location\x18\x02 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location"f\n\x15SearchDomainsResponse\x12M\n\x13register_parameters\x18\x01 \x03(\x0b20.google.cloud.domains.v1beta1.RegisterParameters"z\n!RetrieveRegisterParametersRequest\x12\x18\n\x0bdomain_name\x18\x01 \x01(\tB\x03\xe0A\x02\x12;\n\x08location\x18\x02 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location"s\n"RetrieveRegisterParametersResponse\x12M\n\x13register_parameters\x18\x01 \x01(\x0b20.google.cloud.domains.v1beta1.RegisterParameters"\xe9\x02\n\x15RegisterDomainRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12E\n\x0cregistration\x18\x02 \x01(\x0b2*.google.cloud.domains.v1beta1.RegistrationB\x03\xe0A\x02\x12B\n\x0edomain_notices\x18\x03 \x03(\x0e2*.google.cloud.domains.v1beta1.DomainNotice\x12D\n\x0fcontact_notices\x18\x04 \x03(\x0e2+.google.cloud.domains.v1beta1.ContactNotice\x12-\n\x0cyearly_price\x18\x05 \x01(\x0b2\x12.google.type.MoneyB\x03\xe0A\x02\x12\x15\n\rvalidate_only\x18\x06 \x01(\x08"z\n!RetrieveTransferParametersRequest\x12\x18\n\x0bdomain_name\x18\x01 \x01(\tB\x03\xe0A\x02\x12;\n\x08location\x18\x02 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location"s\n"RetrieveTransferParametersResponse\x12M\n\x13transfer_parameters\x18\x01 \x01(\x0b20.google.cloud.domains.v1beta1.TransferParameters"\xf2\x02\n\x15TransferDomainRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12E\n\x0cregistration\x18\x02 \x01(\x0b2*.google.cloud.domains.v1beta1.RegistrationB\x03\xe0A\x02\x12D\n\x0fcontact_notices\x18\x03 \x03(\x0e2+.google.cloud.domains.v1beta1.ContactNotice\x12-\n\x0cyearly_price\x18\x04 \x01(\x0b2\x12.google.type.MoneyB\x03\xe0A\x02\x12K\n\x12authorization_code\x18\x05 \x01(\x0b2/.google.cloud.domains.v1beta1.AuthorizationCode\x12\x15\n\rvalidate_only\x18\x06 \x01(\x08"\x8c\x01\n\x18ListRegistrationsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t"w\n\x19ListRegistrationsResponse\x12A\n\rregistrations\x18\x01 \x03(\x0b2*.google.cloud.domains.v1beta1.Registration\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"S\n\x16GetRegistrationRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration"\x93\x01\n\x19UpdateRegistrationRequest\x12@\n\x0cregistration\x18\x01 \x01(\x0b2*.google.cloud.domains.v1beta1.Registration\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\xec\x01\n"ConfigureManagementSettingsRequest\x12A\n\x0cregistration\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration\x12M\n\x13management_settings\x18\x02 \x01(\x0b20.google.cloud.domains.v1beta1.ManagementSettings\x124\n\x0bupdate_mask\x18\x03 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\xee\x01\n\x1bConfigureDnsSettingsRequest\x12A\n\x0cregistration\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration\x12?\n\x0cdns_settings\x18\x02 \x01(\x0b2).google.cloud.domains.v1beta1.DnsSettings\x124\n\x0bupdate_mask\x18\x03 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x15\n\rvalidate_only\x18\x04 \x01(\x08"\xc0\x02\n\x1fConfigureContactSettingsRequest\x12A\n\x0cregistration\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration\x12G\n\x10contact_settings\x18\x02 \x01(\x0b2-.google.cloud.domains.v1beta1.ContactSettings\x124\n\x0bupdate_mask\x18\x03 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12D\n\x0fcontact_notices\x18\x04 \x03(\x0e2+.google.cloud.domains.v1beta1.ContactNotice\x12\x15\n\rvalidate_only\x18\x05 \x01(\x08"V\n\x19ExportRegistrationRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration"V\n\x19DeleteRegistrationRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration"e\n RetrieveAuthorizationCodeRequest\x12A\n\x0cregistration\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration"b\n\x1dResetAuthorizationCodeRequest\x12A\n\x0cregistration\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration"\xa1\x03\n\x12RegisterParameters\x12\x13\n\x0bdomain_name\x18\x01 \x01(\t\x12S\n\x0cavailability\x18\x02 \x01(\x0e2=.google.cloud.domains.v1beta1.RegisterParameters.Availability\x12G\n\x11supported_privacy\x18\x03 \x03(\x0e2,.google.cloud.domains.v1beta1.ContactPrivacy\x12B\n\x0edomain_notices\x18\x04 \x03(\x0e2*.google.cloud.domains.v1beta1.DomainNotice\x12(\n\x0cyearly_price\x18\x05 \x01(\x0b2\x12.google.type.Money"j\n\x0cAvailability\x12\x1c\n\x18AVAILABILITY_UNSPECIFIED\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\x0f\n\x0bUNAVAILABLE\x10\x02\x12\x0f\n\x0bUNSUPPORTED\x10\x03\x12\x0b\n\x07UNKNOWN\x10\x04"\x9b\x02\n\x12TransferParameters\x12\x13\n\x0bdomain_name\x18\x01 \x01(\t\x12\x19\n\x11current_registrar\x18\x02 \x01(\t\x12\x14\n\x0cname_servers\x18\x03 \x03(\t\x12L\n\x13transfer_lock_state\x18\x04 \x01(\x0e2/.google.cloud.domains.v1beta1.TransferLockState\x12G\n\x11supported_privacy\x18\x05 \x03(\x0e2,.google.cloud.domains.v1beta1.ContactPrivacy\x12(\n\x0cyearly_price\x18\x06 \x01(\x0b2\x12.google.type.Money"!\n\x11AuthorizationCode\x12\x0c\n\x04code\x18\x01 \x01(\t"\xbc\x01\n\x11OperationMetadata\x12/\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0c\n\x04verb\x18\x04 \x01(\t\x12\x15\n\rstatus_detail\x18\x05 \x01(\t\x12\x13\n\x0bapi_version\x18\x06 \x01(\t*\x7f\n\x0eContactPrivacy\x12\x1f\n\x1bCONTACT_PRIVACY_UNSPECIFIED\x10\x00\x12\x17\n\x13PUBLIC_CONTACT_DATA\x10\x01\x12\x18\n\x14PRIVATE_CONTACT_DATA\x10\x02\x12\x19\n\x15REDACTED_CONTACT_DATA\x10\x03*A\n\x0cDomainNotice\x12\x1d\n\x19DOMAIN_NOTICE_UNSPECIFIED\x10\x00\x12\x12\n\x0eHSTS_PRELOADED\x10\x01*X\n\rContactNotice\x12\x1e\n\x1aCONTACT_NOTICE_UNSPECIFIED\x10\x00\x12\'\n#PUBLIC_CONTACT_DATA_ACKNOWLEDGEMENT\x10\x01*R\n\x11TransferLockState\x12#\n\x1fTRANSFER_LOCK_STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08UNLOCKED\x10\x01\x12\n\n\x06LOCKED\x10\x022\xca\x1e\n\x07Domains\x12\xd9\x01\n\rSearchDomains\x122.google.cloud.domains.v1beta1.SearchDomainsRequest\x1a3.google.cloud.domains.v1beta1.SearchDomainsResponse"_\xdaA\x0elocation,query\x82\xd3\xe4\x93\x02H\x12F/v1beta1/{location=projects/*/locations/*}/registrations:searchDomains\x12\x93\x02\n\x1aRetrieveRegisterParameters\x12?.google.cloud.domains.v1beta1.RetrieveRegisterParametersRequest\x1a@.google.cloud.domains.v1beta1.RetrieveRegisterParametersResponse"r\xdaA\x14location,domain_name\x82\xd3\xe4\x93\x02U\x12S/v1beta1/{location=projects/*/locations/*}/registrations:retrieveRegisterParameters\x12\xf8\x01\n\x0eRegisterDomain\x123.google.cloud.domains.v1beta1.RegisterDomainRequest\x1a\x1d.google.longrunning.Operation"\x91\x01\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA parent,registration,yearly_price\x82\xd3\xe4\x93\x02D"?/v1beta1/{parent=projects/*/locations/*}/registrations:register:\x01*\x12\x93\x02\n\x1aRetrieveTransferParameters\x12?.google.cloud.domains.v1beta1.RetrieveTransferParametersRequest\x1a@.google.cloud.domains.v1beta1.RetrieveTransferParametersResponse"r\xdaA\x14location,domain_name\x82\xd3\xe4\x93\x02U\x12S/v1beta1/{location=projects/*/locations/*}/registrations:retrieveTransferParameters\x12\x8b\x02\n\x0eTransferDomain\x123.google.cloud.domains.v1beta1.TransferDomainRequest\x1a\x1d.google.longrunning.Operation"\xa4\x01\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA3parent,registration,yearly_price,authorization_code\x82\xd3\xe4\x93\x02D"?/v1beta1/{parent=projects/*/locations/*}/registrations:transfer:\x01*\x12\xcd\x01\n\x11ListRegistrations\x126.google.cloud.domains.v1beta1.ListRegistrationsRequest\x1a7.google.cloud.domains.v1beta1.ListRegistrationsResponse"G\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1beta1/{parent=projects/*/locations/*}/registrations\x12\xba\x01\n\x0fGetRegistration\x124.google.cloud.domains.v1beta1.GetRegistrationRequest\x1a*.google.cloud.domains.v1beta1.Registration"E\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1beta1/{name=projects/*/locations/*/registrations/*}\x12\x87\x02\n\x12UpdateRegistration\x127.google.cloud.domains.v1beta1.UpdateRegistrationRequest\x1a\x1d.google.longrunning.Operation"\x98\x01\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA\x18registration,update_mask\x82\xd3\xe4\x93\x02S2C/v1beta1/{registration.name=projects/*/locations/*/registrations/*}:\x0cregistration\x12\xb9\x02\n\x1bConfigureManagementSettings\x12@.google.cloud.domains.v1beta1.ConfigureManagementSettingsRequest\x1a\x1d.google.longrunning.Operation"\xb8\x01\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA,registration,management_settings,update_mask\x82\xd3\xe4\x93\x02_"Z/v1beta1/{registration=projects/*/locations/*/registrations/*}:configureManagementSettings:\x01*\x12\x9d\x02\n\x14ConfigureDnsSettings\x129.google.cloud.domains.v1beta1.ConfigureDnsSettingsRequest\x1a\x1d.google.longrunning.Operation"\xaa\x01\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA%registration,dns_settings,update_mask\x82\xd3\xe4\x93\x02X"S/v1beta1/{registration=projects/*/locations/*/registrations/*}:configureDnsSettings:\x01*\x12\xad\x02\n\x18ConfigureContactSettings\x12=.google.cloud.domains.v1beta1.ConfigureContactSettingsRequest\x1a\x1d.google.longrunning.Operation"\xb2\x01\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA)registration,contact_settings,update_mask\x82\xd3\xe4\x93\x02\\"W/v1beta1/{registration=projects/*/locations/*/registrations/*}:configureContactSettings:\x01*\x12\xe1\x01\n\x12ExportRegistration\x127.google.cloud.domains.v1beta1.ExportRegistrationRequest\x1a\x1d.google.longrunning.Operation"s\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02B"=/v1beta1/{name=projects/*/locations/*/registrations/*}:export:\x01*\x12\xe0\x01\n\x12DeleteRegistration\x127.google.cloud.domains.v1beta1.DeleteRegistrationRequest\x1a\x1d.google.longrunning.Operation"r\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1beta1/{name=projects/*/locations/*/registrations/*}\x12\xfd\x01\n\x19RetrieveAuthorizationCode\x12>.google.cloud.domains.v1beta1.RetrieveAuthorizationCodeRequest\x1a/.google.cloud.domains.v1beta1.AuthorizationCode"o\xdaA\x0cregistration\x82\xd3\xe4\x93\x02Z\x12X/v1beta1/{registration=projects/*/locations/*/registrations/*}:retrieveAuthorizationCode\x12\xf7\x01\n\x16ResetAuthorizationCode\x12;.google.cloud.domains.v1beta1.ResetAuthorizationCodeRequest\x1a/.google.cloud.domains.v1beta1.AuthorizationCode"o\xdaA\x0cregistration\x82\xd3\xe4\x93\x02Z"U/v1beta1/{registration=projects/*/locations/*/registrations/*}:resetAuthorizationCode:\x01*\x1aJ\xcaA\x16domains.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformBn\n com.google.cloud.domains.v1beta1B\x0cDomainsProtoP\x01Z:cloud.google.com/go/domains/apiv1beta1/domainspb;domainspbb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.domains.v1beta1.domains_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n com.google.cloud.domains.v1beta1B\x0cDomainsProtoP\x01Z:cloud.google.com/go/domains/apiv1beta1/domainspb;domainspb'
    _globals['_REGISTRATION_LABELSENTRY']._loaded_options = None
    _globals['_REGISTRATION_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_REGISTRATION'].fields_by_name['name']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_REGISTRATION'].fields_by_name['domain_name']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['domain_name']._serialized_options = b'\xe0A\x02\xe0A\x05'
    _globals['_REGISTRATION'].fields_by_name['create_time']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_REGISTRATION'].fields_by_name['expire_time']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['expire_time']._serialized_options = b'\xe0A\x03'
    _globals['_REGISTRATION'].fields_by_name['state']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_REGISTRATION'].fields_by_name['issues']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['issues']._serialized_options = b'\xe0A\x03'
    _globals['_REGISTRATION'].fields_by_name['contact_settings']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['contact_settings']._serialized_options = b'\xe0A\x02'
    _globals['_REGISTRATION'].fields_by_name['pending_contact_settings']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['pending_contact_settings']._serialized_options = b'\xe0A\x03'
    _globals['_REGISTRATION'].fields_by_name['supported_privacy']._loaded_options = None
    _globals['_REGISTRATION'].fields_by_name['supported_privacy']._serialized_options = b'\xe0A\x03'
    _globals['_REGISTRATION']._loaded_options = None
    _globals['_REGISTRATION']._serialized_options = b'\xeaAk\n#domains.googleapis.com/Registration\x12Dprojects/{project}/locations/{location}/registrations/{registration}'
    _globals['_MANAGEMENTSETTINGS'].fields_by_name['renewal_method']._loaded_options = None
    _globals['_MANAGEMENTSETTINGS'].fields_by_name['renewal_method']._serialized_options = b'\xe0A\x03'
    _globals['_DNSSETTINGS_CUSTOMDNS'].fields_by_name['name_servers']._loaded_options = None
    _globals['_DNSSETTINGS_CUSTOMDNS'].fields_by_name['name_servers']._serialized_options = b'\xe0A\x02'
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS'].fields_by_name['name_servers']._loaded_options = None
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS'].fields_by_name['name_servers']._serialized_options = b'\xe0A\x03'
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS'].fields_by_name['ds_state']._loaded_options = None
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS'].fields_by_name['ds_state']._serialized_options = b'\xe0A\x02'
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS'].fields_by_name['ds_records']._loaded_options = None
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS'].fields_by_name['ds_records']._serialized_options = b'\xe0A\x03'
    _globals['_DNSSETTINGS_GLUERECORD'].fields_by_name['host_name']._loaded_options = None
    _globals['_DNSSETTINGS_GLUERECORD'].fields_by_name['host_name']._serialized_options = b'\xe0A\x02'
    _globals['_CONTACTSETTINGS_CONTACT'].fields_by_name['postal_address']._loaded_options = None
    _globals['_CONTACTSETTINGS_CONTACT'].fields_by_name['postal_address']._serialized_options = b'\xe0A\x02'
    _globals['_CONTACTSETTINGS_CONTACT'].fields_by_name['email']._loaded_options = None
    _globals['_CONTACTSETTINGS_CONTACT'].fields_by_name['email']._serialized_options = b'\xe0A\x02'
    _globals['_CONTACTSETTINGS_CONTACT'].fields_by_name['phone_number']._loaded_options = None
    _globals['_CONTACTSETTINGS_CONTACT'].fields_by_name['phone_number']._serialized_options = b'\xe0A\x02'
    _globals['_CONTACTSETTINGS'].fields_by_name['privacy']._loaded_options = None
    _globals['_CONTACTSETTINGS'].fields_by_name['privacy']._serialized_options = b'\xe0A\x02'
    _globals['_CONTACTSETTINGS'].fields_by_name['registrant_contact']._loaded_options = None
    _globals['_CONTACTSETTINGS'].fields_by_name['registrant_contact']._serialized_options = b'\xe0A\x02'
    _globals['_CONTACTSETTINGS'].fields_by_name['admin_contact']._loaded_options = None
    _globals['_CONTACTSETTINGS'].fields_by_name['admin_contact']._serialized_options = b'\xe0A\x02'
    _globals['_CONTACTSETTINGS'].fields_by_name['technical_contact']._loaded_options = None
    _globals['_CONTACTSETTINGS'].fields_by_name['technical_contact']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHDOMAINSREQUEST'].fields_by_name['query']._loaded_options = None
    _globals['_SEARCHDOMAINSREQUEST'].fields_by_name['query']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHDOMAINSREQUEST'].fields_by_name['location']._loaded_options = None
    _globals['_SEARCHDOMAINSREQUEST'].fields_by_name['location']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_RETRIEVEREGISTERPARAMETERSREQUEST'].fields_by_name['domain_name']._loaded_options = None
    _globals['_RETRIEVEREGISTERPARAMETERSREQUEST'].fields_by_name['domain_name']._serialized_options = b'\xe0A\x02'
    _globals['_RETRIEVEREGISTERPARAMETERSREQUEST'].fields_by_name['location']._loaded_options = None
    _globals['_RETRIEVEREGISTERPARAMETERSREQUEST'].fields_by_name['location']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_REGISTERDOMAINREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_REGISTERDOMAINREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_REGISTERDOMAINREQUEST'].fields_by_name['registration']._loaded_options = None
    _globals['_REGISTERDOMAINREQUEST'].fields_by_name['registration']._serialized_options = b'\xe0A\x02'
    _globals['_REGISTERDOMAINREQUEST'].fields_by_name['yearly_price']._loaded_options = None
    _globals['_REGISTERDOMAINREQUEST'].fields_by_name['yearly_price']._serialized_options = b'\xe0A\x02'
    _globals['_RETRIEVETRANSFERPARAMETERSREQUEST'].fields_by_name['domain_name']._loaded_options = None
    _globals['_RETRIEVETRANSFERPARAMETERSREQUEST'].fields_by_name['domain_name']._serialized_options = b'\xe0A\x02'
    _globals['_RETRIEVETRANSFERPARAMETERSREQUEST'].fields_by_name['location']._loaded_options = None
    _globals['_RETRIEVETRANSFERPARAMETERSREQUEST'].fields_by_name['location']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_TRANSFERDOMAINREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_TRANSFERDOMAINREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_TRANSFERDOMAINREQUEST'].fields_by_name['registration']._loaded_options = None
    _globals['_TRANSFERDOMAINREQUEST'].fields_by_name['registration']._serialized_options = b'\xe0A\x02'
    _globals['_TRANSFERDOMAINREQUEST'].fields_by_name['yearly_price']._loaded_options = None
    _globals['_TRANSFERDOMAINREQUEST'].fields_by_name['yearly_price']._serialized_options = b'\xe0A\x02'
    _globals['_LISTREGISTRATIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTREGISTRATIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_GETREGISTRATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETREGISTRATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_UPDATEREGISTRATIONREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEREGISTRATIONREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_CONFIGUREMANAGEMENTSETTINGSREQUEST'].fields_by_name['registration']._loaded_options = None
    _globals['_CONFIGUREMANAGEMENTSETTINGSREQUEST'].fields_by_name['registration']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_CONFIGUREMANAGEMENTSETTINGSREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_CONFIGUREMANAGEMENTSETTINGSREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_CONFIGUREDNSSETTINGSREQUEST'].fields_by_name['registration']._loaded_options = None
    _globals['_CONFIGUREDNSSETTINGSREQUEST'].fields_by_name['registration']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_CONFIGUREDNSSETTINGSREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_CONFIGUREDNSSETTINGSREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_CONFIGURECONTACTSETTINGSREQUEST'].fields_by_name['registration']._loaded_options = None
    _globals['_CONFIGURECONTACTSETTINGSREQUEST'].fields_by_name['registration']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_CONFIGURECONTACTSETTINGSREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_CONFIGURECONTACTSETTINGSREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_EXPORTREGISTRATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_EXPORTREGISTRATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_DELETEREGISTRATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEREGISTRATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_RETRIEVEAUTHORIZATIONCODEREQUEST'].fields_by_name['registration']._loaded_options = None
    _globals['_RETRIEVEAUTHORIZATIONCODEREQUEST'].fields_by_name['registration']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_RESETAUTHORIZATIONCODEREQUEST'].fields_by_name['registration']._loaded_options = None
    _globals['_RESETAUTHORIZATIONCODEREQUEST'].fields_by_name['registration']._serialized_options = b'\xe0A\x02\xfaA%\n#domains.googleapis.com/Registration'
    _globals['_DOMAINS']._loaded_options = None
    _globals['_DOMAINS']._serialized_options = b'\xcaA\x16domains.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_DOMAINS'].methods_by_name['SearchDomains']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['SearchDomains']._serialized_options = b'\xdaA\x0elocation,query\x82\xd3\xe4\x93\x02H\x12F/v1beta1/{location=projects/*/locations/*}/registrations:searchDomains'
    _globals['_DOMAINS'].methods_by_name['RetrieveRegisterParameters']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['RetrieveRegisterParameters']._serialized_options = b'\xdaA\x14location,domain_name\x82\xd3\xe4\x93\x02U\x12S/v1beta1/{location=projects/*/locations/*}/registrations:retrieveRegisterParameters'
    _globals['_DOMAINS'].methods_by_name['RegisterDomain']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['RegisterDomain']._serialized_options = b'\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA parent,registration,yearly_price\x82\xd3\xe4\x93\x02D"?/v1beta1/{parent=projects/*/locations/*}/registrations:register:\x01*'
    _globals['_DOMAINS'].methods_by_name['RetrieveTransferParameters']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['RetrieveTransferParameters']._serialized_options = b'\xdaA\x14location,domain_name\x82\xd3\xe4\x93\x02U\x12S/v1beta1/{location=projects/*/locations/*}/registrations:retrieveTransferParameters'
    _globals['_DOMAINS'].methods_by_name['TransferDomain']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['TransferDomain']._serialized_options = b'\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA3parent,registration,yearly_price,authorization_code\x82\xd3\xe4\x93\x02D"?/v1beta1/{parent=projects/*/locations/*}/registrations:transfer:\x01*'
    _globals['_DOMAINS'].methods_by_name['ListRegistrations']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['ListRegistrations']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1beta1/{parent=projects/*/locations/*}/registrations'
    _globals['_DOMAINS'].methods_by_name['GetRegistration']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['GetRegistration']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1beta1/{name=projects/*/locations/*/registrations/*}'
    _globals['_DOMAINS'].methods_by_name['UpdateRegistration']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['UpdateRegistration']._serialized_options = b'\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA\x18registration,update_mask\x82\xd3\xe4\x93\x02S2C/v1beta1/{registration.name=projects/*/locations/*/registrations/*}:\x0cregistration'
    _globals['_DOMAINS'].methods_by_name['ConfigureManagementSettings']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['ConfigureManagementSettings']._serialized_options = b'\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA,registration,management_settings,update_mask\x82\xd3\xe4\x93\x02_"Z/v1beta1/{registration=projects/*/locations/*/registrations/*}:configureManagementSettings:\x01*'
    _globals['_DOMAINS'].methods_by_name['ConfigureDnsSettings']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['ConfigureDnsSettings']._serialized_options = b'\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA%registration,dns_settings,update_mask\x82\xd3\xe4\x93\x02X"S/v1beta1/{registration=projects/*/locations/*/registrations/*}:configureDnsSettings:\x01*'
    _globals['_DOMAINS'].methods_by_name['ConfigureContactSettings']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['ConfigureContactSettings']._serialized_options = b'\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA)registration,contact_settings,update_mask\x82\xd3\xe4\x93\x02\\"W/v1beta1/{registration=projects/*/locations/*/registrations/*}:configureContactSettings:\x01*'
    _globals['_DOMAINS'].methods_by_name['ExportRegistration']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['ExportRegistration']._serialized_options = b'\xcaA!\n\x0cRegistration\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02B"=/v1beta1/{name=projects/*/locations/*/registrations/*}:export:\x01*'
    _globals['_DOMAINS'].methods_by_name['DeleteRegistration']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['DeleteRegistration']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1beta1/{name=projects/*/locations/*/registrations/*}'
    _globals['_DOMAINS'].methods_by_name['RetrieveAuthorizationCode']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['RetrieveAuthorizationCode']._serialized_options = b'\xdaA\x0cregistration\x82\xd3\xe4\x93\x02Z\x12X/v1beta1/{registration=projects/*/locations/*/registrations/*}:retrieveAuthorizationCode'
    _globals['_DOMAINS'].methods_by_name['ResetAuthorizationCode']._loaded_options = None
    _globals['_DOMAINS'].methods_by_name['ResetAuthorizationCode']._serialized_options = b'\xdaA\x0cregistration\x82\xd3\xe4\x93\x02Z"U/v1beta1/{registration=projects/*/locations/*/registrations/*}:resetAuthorizationCode:\x01*'
    _globals['_CONTACTPRIVACY']._serialized_start = 7690
    _globals['_CONTACTPRIVACY']._serialized_end = 7817
    _globals['_DOMAINNOTICE']._serialized_start = 7819
    _globals['_DOMAINNOTICE']._serialized_end = 7884
    _globals['_CONTACTNOTICE']._serialized_start = 7886
    _globals['_CONTACTNOTICE']._serialized_end = 7974
    _globals['_TRANSFERLOCKSTATE']._serialized_start = 7976
    _globals['_TRANSFERLOCKSTATE']._serialized_end = 8058
    _globals['_REGISTRATION']._serialized_start = 355
    _globals['_REGISTRATION']._serialized_end = 1526
    _globals['_REGISTRATION_LABELSENTRY']._serialized_start = 1126
    _globals['_REGISTRATION_LABELSENTRY']._serialized_end = 1171
    _globals['_REGISTRATION_STATE']._serialized_start = 1174
    _globals['_REGISTRATION_STATE']._serialized_end = 1339
    _globals['_REGISTRATION_ISSUE']._serialized_start = 1341
    _globals['_REGISTRATION_ISSUE']._serialized_end = 1414
    _globals['_MANAGEMENTSETTINGS']._serialized_start = 1529
    _globals['_MANAGEMENTSETTINGS']._serialized_end = 1812
    _globals['_MANAGEMENTSETTINGS_RENEWALMETHOD']._serialized_start = 1722
    _globals['_MANAGEMENTSETTINGS_RENEWALMETHOD']._serialized_end = 1812
    _globals['_DNSSETTINGS']._serialized_start = 1815
    _globals['_DNSSETTINGS']._serialized_end = 3165
    _globals['_DNSSETTINGS_CUSTOMDNS']._serialized_start = 2071
    _globals['_DNSSETTINGS_CUSTOMDNS']._serialized_end = 2181
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS']._serialized_start = 2184
    _globals['_DNSSETTINGS_GOOGLEDOMAINSDNS']._serialized_end = 2380
    _globals['_DNSSETTINGS_DSRECORD']._serialized_start = 2383
    _globals['_DNSSETTINGS_DSRECORD']._serialized_end = 2972
    _globals['_DNSSETTINGS_DSRECORD_ALGORITHM']._serialized_start = 2594
    _globals['_DNSSETTINGS_DSRECORD_ALGORITHM']._serialized_end = 2881
    _globals['_DNSSETTINGS_DSRECORD_DIGESTTYPE']._serialized_start = 2883
    _globals['_DNSSETTINGS_DSRECORD_DIGESTTYPE']._serialized_end = 2972
    _globals['_DNSSETTINGS_GLUERECORD']._serialized_start = 2974
    _globals['_DNSSETTINGS_GLUERECORD']._serialized_end = 3058
    _globals['_DNSSETTINGS_DSSTATE']._serialized_start = 3060
    _globals['_DNSSETTINGS_DSSTATE']._serialized_end = 3149
    _globals['_CONTACTSETTINGS']._serialized_start = 3168
    _globals['_CONTACTSETTINGS']._serialized_end = 3647
    _globals['_CONTACTSETTINGS_CONTACT']._serialized_start = 3514
    _globals['_CONTACTSETTINGS_CONTACT']._serialized_end = 3647
    _globals['_SEARCHDOMAINSREQUEST']._serialized_start = 3649
    _globals['_SEARCHDOMAINSREQUEST']._serialized_end = 3752
    _globals['_SEARCHDOMAINSRESPONSE']._serialized_start = 3754
    _globals['_SEARCHDOMAINSRESPONSE']._serialized_end = 3856
    _globals['_RETRIEVEREGISTERPARAMETERSREQUEST']._serialized_start = 3858
    _globals['_RETRIEVEREGISTERPARAMETERSREQUEST']._serialized_end = 3980
    _globals['_RETRIEVEREGISTERPARAMETERSRESPONSE']._serialized_start = 3982
    _globals['_RETRIEVEREGISTERPARAMETERSRESPONSE']._serialized_end = 4097
    _globals['_REGISTERDOMAINREQUEST']._serialized_start = 4100
    _globals['_REGISTERDOMAINREQUEST']._serialized_end = 4461
    _globals['_RETRIEVETRANSFERPARAMETERSREQUEST']._serialized_start = 4463
    _globals['_RETRIEVETRANSFERPARAMETERSREQUEST']._serialized_end = 4585
    _globals['_RETRIEVETRANSFERPARAMETERSRESPONSE']._serialized_start = 4587
    _globals['_RETRIEVETRANSFERPARAMETERSRESPONSE']._serialized_end = 4702
    _globals['_TRANSFERDOMAINREQUEST']._serialized_start = 4705
    _globals['_TRANSFERDOMAINREQUEST']._serialized_end = 5075
    _globals['_LISTREGISTRATIONSREQUEST']._serialized_start = 5078
    _globals['_LISTREGISTRATIONSREQUEST']._serialized_end = 5218
    _globals['_LISTREGISTRATIONSRESPONSE']._serialized_start = 5220
    _globals['_LISTREGISTRATIONSRESPONSE']._serialized_end = 5339
    _globals['_GETREGISTRATIONREQUEST']._serialized_start = 5341
    _globals['_GETREGISTRATIONREQUEST']._serialized_end = 5424
    _globals['_UPDATEREGISTRATIONREQUEST']._serialized_start = 5427
    _globals['_UPDATEREGISTRATIONREQUEST']._serialized_end = 5574
    _globals['_CONFIGUREMANAGEMENTSETTINGSREQUEST']._serialized_start = 5577
    _globals['_CONFIGUREMANAGEMENTSETTINGSREQUEST']._serialized_end = 5813
    _globals['_CONFIGUREDNSSETTINGSREQUEST']._serialized_start = 5816
    _globals['_CONFIGUREDNSSETTINGSREQUEST']._serialized_end = 6054
    _globals['_CONFIGURECONTACTSETTINGSREQUEST']._serialized_start = 6057
    _globals['_CONFIGURECONTACTSETTINGSREQUEST']._serialized_end = 6377
    _globals['_EXPORTREGISTRATIONREQUEST']._serialized_start = 6379
    _globals['_EXPORTREGISTRATIONREQUEST']._serialized_end = 6465
    _globals['_DELETEREGISTRATIONREQUEST']._serialized_start = 6467
    _globals['_DELETEREGISTRATIONREQUEST']._serialized_end = 6553
    _globals['_RETRIEVEAUTHORIZATIONCODEREQUEST']._serialized_start = 6555
    _globals['_RETRIEVEAUTHORIZATIONCODEREQUEST']._serialized_end = 6656
    _globals['_RESETAUTHORIZATIONCODEREQUEST']._serialized_start = 6658
    _globals['_RESETAUTHORIZATIONCODEREQUEST']._serialized_end = 6756
    _globals['_REGISTERPARAMETERS']._serialized_start = 6759
    _globals['_REGISTERPARAMETERS']._serialized_end = 7176
    _globals['_REGISTERPARAMETERS_AVAILABILITY']._serialized_start = 7070
    _globals['_REGISTERPARAMETERS_AVAILABILITY']._serialized_end = 7176
    _globals['_TRANSFERPARAMETERS']._serialized_start = 7179
    _globals['_TRANSFERPARAMETERS']._serialized_end = 7462
    _globals['_AUTHORIZATIONCODE']._serialized_start = 7464
    _globals['_AUTHORIZATIONCODE']._serialized_end = 7497
    _globals['_OPERATIONMETADATA']._serialized_start = 7500
    _globals['_OPERATIONMETADATA']._serialized_end = 7688
    _globals['_DOMAINS']._serialized_start = 8061
    _globals['_DOMAINS']._serialized_end = 11975