"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/ads/googleads/v20/resources/invoice.proto')
_sym_db = _symbol_database.Default()
from ......google.ads.googleads.v20.common import dates_pb2 as google_dot_ads_dot_googleads_dot_v20_dot_common_dot_dates__pb2
from ......google.ads.googleads.v20.enums import invoice_type_pb2 as google_dot_ads_dot_googleads_dot_v20_dot_enums_dot_invoice__type__pb2
from ......google.ads.googleads.v20.enums import month_of_year_pb2 as google_dot_ads_dot_googleads_dot_v20_dot_enums_dot_month__of__year__pb2
from ......google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from ......google.api import resource_pb2 as google_dot_api_dot_resource__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0google/ads/googleads/v20/resources/invoice.proto\x12"google.ads.googleads.v20.resources\x1a+google/ads/googleads/v20/common/dates.proto\x1a1google/ads/googleads/v20/enums/invoice_type.proto\x1a2google/ads/googleads/v20/enums/month_of_year.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto"\xa5\'\n\x07Invoice\x12?\n\rresource_name\x18\x01 \x01(\tB(\xe0A\x03\xfaA"\n googleads.googleapis.com/Invoice\x12\x14\n\x02id\x18\x19 \x01(\tB\x03\xe0A\x03H\x00\x88\x01\x01\x12N\n\x04type\x18\x03 \x01(\x0e2;.google.ads.googleads.v20.enums.InvoiceTypeEnum.InvoiceTypeB\x03\xe0A\x03\x12\x1f\n\rbilling_setup\x18\x1a \x01(\tB\x03\xe0A\x03H\x01\x88\x01\x01\x12%\n\x13payments_account_id\x18\x1b \x01(\tB\x03\xe0A\x03H\x02\x88\x01\x01\x12%\n\x13payments_profile_id\x18\x1c \x01(\tB\x03\xe0A\x03H\x03\x88\x01\x01\x12\x1c\n\nissue_date\x18\x1d \x01(\tB\x03\xe0A\x03H\x04\x88\x01\x01\x12\x1a\n\x08due_date\x18\x1e \x01(\tB\x03\xe0A\x03H\x05\x88\x01\x01\x12K\n\x12service_date_range\x18\t \x01(\x0b2*.google.ads.googleads.v20.common.DateRangeB\x03\xe0A\x03\x12\x1f\n\rcurrency_code\x18\x1f \x01(\tB\x03\xe0A\x03H\x06\x88\x01\x01\x12/\n"adjustments_subtotal_amount_micros\x18\x13 \x01(\x03B\x03\xe0A\x03\x12*\n\x1dadjustments_tax_amount_micros\x18\x14 \x01(\x03B\x03\xe0A\x03\x12,\n\x1fadjustments_total_amount_micros\x18\x15 \x01(\x03B\x03\xe0A\x03\x124\n\'regulatory_costs_subtotal_amount_micros\x18\x16 \x01(\x03B\x03\xe0A\x03\x12/\n"regulatory_costs_tax_amount_micros\x18\x17 \x01(\x03B\x03\xe0A\x03\x121\n$regulatory_costs_total_amount_micros\x18\x18 \x01(\x03B\x03\xe0A\x03\x126\n$export_charge_subtotal_amount_micros\x18( \x01(\x03B\x03\xe0A\x03H\x07\x88\x01\x01\x121\n\x1fexport_charge_tax_amount_micros\x18) \x01(\x03B\x03\xe0A\x03H\x08\x88\x01\x01\x123\n!export_charge_total_amount_micros\x18* \x01(\x03B\x03\xe0A\x03H\t\x88\x01\x01\x12(\n\x16subtotal_amount_micros\x18! \x01(\x03B\x03\xe0A\x03H\n\x88\x01\x01\x12#\n\x11tax_amount_micros\x18" \x01(\x03B\x03\xe0A\x03H\x0b\x88\x01\x01\x12%\n\x13total_amount_micros\x18# \x01(\x03B\x03\xe0A\x03H\x0c\x88\x01\x01\x12#\n\x11corrected_invoice\x18$ \x01(\tB\x03\xe0A\x03H\r\x88\x01\x01\x12\x1e\n\x11replaced_invoices\x18% \x03(\tB\x03\xe0A\x03\x12\x19\n\x07pdf_url\x18& \x01(\tB\x03\xe0A\x03H\x0e\x88\x01\x01\x12g\n\x18account_budget_summaries\x18\x12 \x03(\x0b2@.google.ads.googleads.v20.resources.Invoice.AccountBudgetSummaryB\x03\xe0A\x03\x12Z\n\x11account_summaries\x18\' \x03(\x0b2:.google.ads.googleads.v20.resources.Invoice.AccountSummaryB\x03\xe0A\x03\x1a\xe1\r\n\x0eAccountSummary\x12\x1a\n\x08customer\x18\x01 \x01(\tB\x03\xe0A\x03H\x00\x88\x01\x01\x12;\n)billing_correction_subtotal_amount_micros\x18\x02 \x01(\x03B\x03\xe0A\x03H\x01\x88\x01\x01\x126\n$billing_correction_tax_amount_micros\x18\x03 \x01(\x03B\x03\xe0A\x03H\x02\x88\x01\x01\x128\n&billing_correction_total_amount_micros\x18\x04 \x01(\x03B\x03\xe0A\x03H\x03\x88\x01\x01\x12:\n(coupon_adjustment_subtotal_amount_micros\x18\x05 \x01(\x03B\x03\xe0A\x03H\x04\x88\x01\x01\x125\n#coupon_adjustment_tax_amount_micros\x18\x06 \x01(\x03B\x03\xe0A\x03H\x05\x88\x01\x01\x127\n%coupon_adjustment_total_amount_micros\x18\x07 \x01(\x03B\x03\xe0A\x03H\x06\x88\x01\x01\x12A\n/excess_credit_adjustment_subtotal_amount_micros\x18\x08 \x01(\x03B\x03\xe0A\x03H\x07\x88\x01\x01\x12<\n*excess_credit_adjustment_tax_amount_micros\x18\t \x01(\x03B\x03\xe0A\x03H\x08\x88\x01\x01\x12>\n,excess_credit_adjustment_total_amount_micros\x18\n \x01(\x03B\x03\xe0A\x03H\t\x88\x01\x01\x129\n\'regulatory_costs_subtotal_amount_micros\x18\x0b \x01(\x03B\x03\xe0A\x03H\n\x88\x01\x01\x124\n"regulatory_costs_tax_amount_micros\x18\x0c \x01(\x03B\x03\xe0A\x03H\x0b\x88\x01\x01\x126\n$regulatory_costs_total_amount_micros\x18\r \x01(\x03B\x03\xe0A\x03H\x0c\x88\x01\x01\x126\n$export_charge_subtotal_amount_micros\x18\x11 \x01(\x03B\x03\xe0A\x03H\r\x88\x01\x01\x121\n\x1fexport_charge_tax_amount_micros\x18\x12 \x01(\x03B\x03\xe0A\x03H\x0e\x88\x01\x01\x123\n!export_charge_total_amount_micros\x18\x13 \x01(\x03B\x03\xe0A\x03H\x0f\x88\x01\x01\x12(\n\x16subtotal_amount_micros\x18\x0e \x01(\x03B\x03\xe0A\x03H\x10\x88\x01\x01\x12#\n\x11tax_amount_micros\x18\x0f \x01(\x03B\x03\xe0A\x03H\x11\x88\x01\x01\x12%\n\x13total_amount_micros\x18\x10 \x01(\x03B\x03\xe0A\x03H\x12\x88\x01\x01B\x0b\n\t_customerB,\n*_billing_correction_subtotal_amount_microsB\'\n%_billing_correction_tax_amount_microsB)\n\'_billing_correction_total_amount_microsB+\n)_coupon_adjustment_subtotal_amount_microsB&\n$_coupon_adjustment_tax_amount_microsB(\n&_coupon_adjustment_total_amount_microsB2\n0_excess_credit_adjustment_subtotal_amount_microsB-\n+_excess_credit_adjustment_tax_amount_microsB/\n-_excess_credit_adjustment_total_amount_microsB*\n(_regulatory_costs_subtotal_amount_microsB%\n#_regulatory_costs_tax_amount_microsB\'\n%_regulatory_costs_total_amount_microsB\'\n%_export_charge_subtotal_amount_microsB"\n _export_charge_tax_amount_microsB$\n"_export_charge_total_amount_microsB\x19\n\x17_subtotal_amount_microsB\x14\n\x12_tax_amount_microsB\x16\n\x14_total_amount_micros\x1a\xe8\x07\n\x14AccountBudgetSummary\x12\x1a\n\x08customer\x18\n \x01(\tB\x03\xe0A\x03H\x00\x88\x01\x01\x12+\n\x19customer_descriptive_name\x18\x0b \x01(\tB\x03\xe0A\x03H\x01\x88\x01\x01\x12 \n\x0eaccount_budget\x18\x0c \x01(\tB\x03\xe0A\x03H\x02\x88\x01\x01\x12%\n\x13account_budget_name\x18\r \x01(\tB\x03\xe0A\x03H\x03\x88\x01\x01\x12\'\n\x15purchase_order_number\x18\x0e \x01(\tB\x03\xe0A\x03H\x04\x88\x01\x01\x12(\n\x16subtotal_amount_micros\x18\x0f \x01(\x03B\x03\xe0A\x03H\x05\x88\x01\x01\x12#\n\x11tax_amount_micros\x18\x10 \x01(\x03B\x03\xe0A\x03H\x06\x88\x01\x01\x12%\n\x13total_amount_micros\x18\x11 \x01(\x03B\x03\xe0A\x03H\x07\x88\x01\x01\x12U\n\x1cbillable_activity_date_range\x18\t \x01(\x0b2*.google.ads.googleads.v20.common.DateRangeB\x03\xe0A\x03\x12&\n\x14served_amount_micros\x18\x12 \x01(\x03B\x03\xe0A\x03H\x08\x88\x01\x01\x12&\n\x14billed_amount_micros\x18\x13 \x01(\x03B\x03\xe0A\x03H\t\x88\x01\x01\x12,\n\x1aoverdelivery_amount_micros\x18\x14 \x01(\x03B\x03\xe0A\x03H\n\x88\x01\x01\x120\n\x1einvalid_activity_amount_micros\x18\x15 \x01(\x03B\x03\xe0A\x03H\x0b\x88\x01\x01\x12k\n\x1ainvalid_activity_summaries\x18\x16 \x03(\x0b2B.google.ads.googleads.v20.resources.Invoice.InvalidActivitySummaryB\x03\xe0A\x03B\x0b\n\t_customerB\x1c\n\x1a_customer_descriptive_nameB\x11\n\x0f_account_budgetB\x16\n\x14_account_budget_nameB\x18\n\x16_purchase_order_numberB\x19\n\x17_subtotal_amount_microsB\x14\n\x12_tax_amount_microsB\x16\n\x14_total_amount_microsB\x17\n\x15_served_amount_microsB\x17\n\x15_billed_amount_microsB\x1d\n\x1b_overdelivery_amount_microsB!\n\x1f_invalid_activity_amount_micros\x1a\x81\x04\n\x16InvalidActivitySummary\x12h\n\x19original_month_of_service\x18\x01 \x01(\x0e2;.google.ads.googleads.v20.enums.MonthOfYearEnum.MonthOfYearB\x03\xe0A\x03H\x00\x88\x01\x01\x12*\n\x18original_year_of_service\x18\x02 \x01(\tB\x03\xe0A\x03H\x01\x88\x01\x01\x12%\n\x13original_invoice_id\x18\x03 \x01(\tB\x03\xe0A\x03H\x02\x88\x01\x01\x12.\n\x1coriginal_account_budget_name\x18\x04 \x01(\tB\x03\xe0A\x03H\x03\x88\x01\x01\x120\n\x1eoriginal_purchase_order_number\x18\x05 \x01(\tB\x03\xe0A\x03H\x04\x88\x01\x01\x12\x1f\n\ramount_micros\x18\x06 \x01(\x03B\x03\xe0A\x03H\x05\x88\x01\x01B\x1c\n\x1a_original_month_of_serviceB\x1b\n\x19_original_year_of_serviceB\x16\n\x14_original_invoice_idB\x1f\n\x1d_original_account_budget_nameB!\n\x1f_original_purchase_order_numberB\x10\n\x0e_amount_micros:T\xeaAQ\n googleads.googleapis.com/Invoice\x12-customers/{customer_id}/invoices/{invoice_id}B\x05\n\x03_idB\x10\n\x0e_billing_setupB\x16\n\x14_payments_account_idB\x16\n\x14_payments_profile_idB\r\n\x0b_issue_dateB\x0b\n\t_due_dateB\x10\n\x0e_currency_codeB\'\n%_export_charge_subtotal_amount_microsB"\n _export_charge_tax_amount_microsB$\n"_export_charge_total_amount_microsB\x19\n\x17_subtotal_amount_microsB\x14\n\x12_tax_amount_microsB\x16\n\x14_total_amount_microsB\x14\n\x12_corrected_invoiceB\n\n\x08_pdf_urlB\xfe\x01\n&com.google.ads.googleads.v20.resourcesB\x0cInvoiceProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v20/resources;resources\xa2\x02\x03GAA\xaa\x02"Google.Ads.GoogleAds.V20.Resources\xca\x02"Google\\Ads\\GoogleAds\\V20\\Resources\xea\x02&Google::Ads::GoogleAds::V20::Resourcesb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.ads.googleads.v20.resources.invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n&com.google.ads.googleads.v20.resourcesB\x0cInvoiceProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v20/resources;resources\xa2\x02\x03GAA\xaa\x02"Google.Ads.GoogleAds.V20.Resources\xca\x02"Google\\Ads\\GoogleAds\\V20\\Resources\xea\x02&Google::Ads::GoogleAds::V20::Resources'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['customer']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['customer']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['billing_correction_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['billing_correction_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['billing_correction_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['billing_correction_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['billing_correction_total_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['billing_correction_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['coupon_adjustment_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['coupon_adjustment_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['coupon_adjustment_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['coupon_adjustment_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['coupon_adjustment_total_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['coupon_adjustment_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['excess_credit_adjustment_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['excess_credit_adjustment_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['excess_credit_adjustment_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['excess_credit_adjustment_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['excess_credit_adjustment_total_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['excess_credit_adjustment_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['regulatory_costs_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['regulatory_costs_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['regulatory_costs_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['regulatory_costs_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['regulatory_costs_total_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['regulatory_costs_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['export_charge_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['export_charge_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['export_charge_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['export_charge_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['export_charge_total_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['export_charge_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['tax_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['total_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTSUMMARY'].fields_by_name['total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['customer']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['customer']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['customer_descriptive_name']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['customer_descriptive_name']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['account_budget']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['account_budget']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['account_budget_name']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['account_budget_name']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['purchase_order_number']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['purchase_order_number']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['tax_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['total_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['billable_activity_date_range']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['billable_activity_date_range']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['served_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['served_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['billed_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['billed_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['overdelivery_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['overdelivery_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['invalid_activity_amount_micros']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['invalid_activity_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['invalid_activity_summaries']._loaded_options = None
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY'].fields_by_name['invalid_activity_summaries']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_month_of_service']._loaded_options = None
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_month_of_service']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_year_of_service']._loaded_options = None
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_year_of_service']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_invoice_id']._loaded_options = None
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_invoice_id']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_account_budget_name']._loaded_options = None
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_account_budget_name']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_purchase_order_number']._loaded_options = None
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['original_purchase_order_number']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['amount_micros']._loaded_options = None
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY'].fields_by_name['amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['resource_name']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['resource_name']._serialized_options = b'\xe0A\x03\xfaA"\n googleads.googleapis.com/Invoice'
    _globals['_INVOICE'].fields_by_name['id']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['id']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['type']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['type']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['billing_setup']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['billing_setup']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['payments_account_id']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['payments_account_id']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['payments_profile_id']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['payments_profile_id']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['issue_date']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['issue_date']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['due_date']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['due_date']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['service_date_range']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['service_date_range']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['currency_code']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['currency_code']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['adjustments_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['adjustments_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['adjustments_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['adjustments_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['adjustments_total_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['adjustments_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['regulatory_costs_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['regulatory_costs_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['regulatory_costs_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['regulatory_costs_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['regulatory_costs_total_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['regulatory_costs_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['export_charge_subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['export_charge_subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['export_charge_tax_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['export_charge_tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['export_charge_total_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['export_charge_total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['subtotal_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['subtotal_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['tax_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['tax_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['total_amount_micros']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['total_amount_micros']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['corrected_invoice']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['corrected_invoice']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['replaced_invoices']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['replaced_invoices']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['pdf_url']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['pdf_url']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['account_budget_summaries']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['account_budget_summaries']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE'].fields_by_name['account_summaries']._loaded_options = None
    _globals['_INVOICE'].fields_by_name['account_summaries']._serialized_options = b'\xe0A\x03'
    _globals['_INVOICE']._loaded_options = None
    _globals['_INVOICE']._serialized_options = b'\xeaAQ\n googleads.googleapis.com/Invoice\x12-customers/{customer_id}/invoices/{invoice_id}'
    _globals['_INVOICE']._serialized_start = 297
    _globals['_INVOICE']._serialized_end = 5326
    _globals['_INVOICE_ACCOUNTSUMMARY']._serialized_start = 1619
    _globals['_INVOICE_ACCOUNTSUMMARY']._serialized_end = 3380
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY']._serialized_start = 3383
    _globals['_INVOICE_ACCOUNTBUDGETSUMMARY']._serialized_end = 4383
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY']._serialized_start = 4386
    _globals['_INVOICE_INVALIDACTIVITYSUMMARY']._serialized_end = 4899