"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2020-2025 Exactpro (Exactpro Systems Limited)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import th2_grpc_common.common_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TemplateFixRuleCreate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> th2_grpc_common.common_pb2.Value: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: th2_grpc_common.common_pb2.Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class SessionAliasesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    FIELDS_FIELD_NUMBER: builtins.int
    SESSION_ALIASES_FIELD_NUMBER: builtins.int
    CONNECTION_ID_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, th2_grpc_common.common_pb2.Value]: ...
    @property
    def session_aliases(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def connection_id(self) -> th2_grpc_common.common_pb2.ConnectionID: ...
    def __init__(
        self,
        *,
        fields: collections.abc.Mapping[builtins.str, th2_grpc_common.common_pb2.Value] | None = ...,
        session_aliases: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        connection_id: th2_grpc_common.common_pb2.ConnectionID | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["connection_id", b"connection_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["connection_id", b"connection_id", "fields", b"fields", "session_aliases", b"session_aliases"]) -> None: ...

global___TemplateFixRuleCreate = TemplateFixRuleCreate
