"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/oracledatabase/v1/oracledatabase.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import field_info_pb2 as google_dot_api_dot_field__info__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.oracledatabase.v1 import autonomous_database_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_autonomous__database__pb2
from .....google.cloud.oracledatabase.v1 import autonomous_database_character_set_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_autonomous__database__character__set__pb2
from .....google.cloud.oracledatabase.v1 import autonomous_db_backup_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_autonomous__db__backup__pb2
from .....google.cloud.oracledatabase.v1 import autonomous_db_version_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_autonomous__db__version__pb2
from .....google.cloud.oracledatabase.v1 import db_node_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_db__node__pb2
from .....google.cloud.oracledatabase.v1 import db_server_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_db__server__pb2
from .....google.cloud.oracledatabase.v1 import db_system_shape_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_db__system__shape__pb2
from .....google.cloud.oracledatabase.v1 import entitlement_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_entitlement__pb2
from .....google.cloud.oracledatabase.v1 import exadata_infra_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_exadata__infra__pb2
from .....google.cloud.oracledatabase.v1 import gi_version_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_gi__version__pb2
from .....google.cloud.oracledatabase.v1 import vm_cluster_pb2 as google_dot_cloud_dot_oracledatabase_dot_v1_dot_vm__cluster__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3google/cloud/oracledatabase/v1/oracledatabase.proto\x12\x1egoogle.cloud.oracledatabase.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a\x19google/api/resource.proto\x1a8google/cloud/oracledatabase/v1/autonomous_database.proto\x1aFgoogle/cloud/oracledatabase/v1/autonomous_database_character_set.proto\x1a9google/cloud/oracledatabase/v1/autonomous_db_backup.proto\x1a:google/cloud/oracledatabase/v1/autonomous_db_version.proto\x1a,google/cloud/oracledatabase/v1/db_node.proto\x1a.google/cloud/oracledatabase/v1/db_server.proto\x1a4google/cloud/oracledatabase/v1/db_system_shape.proto\x1a0google/cloud/oracledatabase/v1/entitlement.proto\x1a2google/cloud/oracledatabase/v1/exadata_infra.proto\x1a/google/cloud/oracledatabase/v1/gi_version.proto\x1a/google/cloud/oracledatabase/v1/vm_cluster.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xab\x01\n&ListCloudExadataInfrastructuresRequest\x12P\n\x06parent\x18\x01 \x01(\tB@\xe0A\x02\xfaA:\x128oracledatabase.googleapis.com/CloudExadataInfrastructure\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"\xa5\x01\n\'ListCloudExadataInfrastructuresResponse\x12a\n\x1dcloud_exadata_infrastructures\x18\x01 \x03(\x0b2:.google.cloud.oracledatabase.v1.CloudExadataInfrastructure\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"v\n$GetCloudExadataInfrastructureRequest\x12N\n\x04name\x18\x01 \x01(\tB@\xe0A\x02\xfaA:\n8oracledatabase.googleapis.com/CloudExadataInfrastructure"\xb1\x02\n\'CreateCloudExadataInfrastructureRequest\x12P\n\x06parent\x18\x01 \x01(\tB@\xe0A\x02\xfaA:\x128oracledatabase.googleapis.com/CloudExadataInfrastructure\x12,\n\x1fcloud_exadata_infrastructure_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12e\n\x1ccloud_exadata_infrastructure\x18\x03 \x01(\x0b2:.google.cloud.oracledatabase.v1.CloudExadataInfrastructureB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x04 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\xae\x01\n\'DeleteCloudExadataInfrastructureRequest\x12N\n\x04name\x18\x01 \x01(\tB@\xe0A\x02\xfaA:\n8oracledatabase.googleapis.com/CloudExadataInfrastructure\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"\xa8\x01\n\x1aListCloudVmClustersRequest\x12D\n\x06parent\x18\x01 \x01(\tB4\xe0A\x02\xfaA.\x12,oracledatabase.googleapis.com/CloudVmCluster\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"\x81\x01\n\x1bListCloudVmClustersResponse\x12I\n\x11cloud_vm_clusters\x18\x01 \x03(\x0b2..google.cloud.oracledatabase.v1.CloudVmCluster\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"^\n\x18GetCloudVmClusterRequest\x12B\n\x04name\x18\x01 \x01(\tB4\xe0A\x02\xfaA.\n,oracledatabase.googleapis.com/CloudVmCluster"\xf5\x01\n\x1bCreateCloudVmClusterRequest\x12D\n\x06parent\x18\x01 \x01(\tB4\xe0A\x02\xfaA.\x12,oracledatabase.googleapis.com/CloudVmCluster\x12 \n\x13cloud_vm_cluster_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12M\n\x10cloud_vm_cluster\x18\x03 \x01(\x0b2..google.cloud.oracledatabase.v1.CloudVmClusterB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x04 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\x96\x01\n\x1bDeleteCloudVmClusterRequest\x12B\n\x04name\x18\x01 \x01(\tB4\xe0A\x02\xfaA.\n,oracledatabase.googleapis.com/CloudVmCluster\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"\x8d\x01\n\x17ListEntitlementsRequest\x12A\n\x06parent\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\x12)oracledatabase.googleapis.com/Entitlement\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"v\n\x18ListEntitlementsResponse\x12A\n\x0centitlements\x18\x01 \x03(\x0b2+.google.cloud.oracledatabase.v1.Entitlement\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x87\x01\n\x14ListDbServersRequest\x12>\n\x06parent\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\x12&oracledatabase.googleapis.com/DbServer\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"n\n\x15ListDbServersResponse\x12<\n\ndb_servers\x18\x01 \x03(\x0b2(.google.cloud.oracledatabase.v1.DbServer\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x83\x01\n\x12ListDbNodesRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$oracledatabase.googleapis.com/DbNode\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"h\n\x13ListDbNodesResponse\x128\n\x08db_nodes\x18\x01 \x03(\x0b2&.google.cloud.oracledatabase.v1.DbNode\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x89\x01\n\x15ListGiVersionsRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\x12\'oracledatabase.googleapis.com/GiVersion\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"q\n\x16ListGiVersionsResponse\x12>\n\x0bgi_versions\x18\x01 \x03(\x0b2).google.cloud.oracledatabase.v1.GiVersion\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x91\x01\n\x19ListDbSystemShapesRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+oracledatabase.googleapis.com/DbSystemShape\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"~\n\x1aListDbSystemShapesResponse\x12G\n\x10db_system_shapes\x18\x01 \x03(\x0b2-.google.cloud.oracledatabase.v1.DbSystemShape\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x9f\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x03\x12\x1d\n\x10percent_complete\x18\x08 \x01(\x01B\x03\xe0A\x03"\xc7\x01\n\x1eListAutonomousDatabasesRequest\x12H\n\x06parent\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\x120oracledatabase.googleapis.com/AutonomousDatabase\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x05 \x01(\tB\x03\xe0A\x01"\x8c\x01\n\x1fListAutonomousDatabasesResponse\x12P\n\x14autonomous_databases\x18\x01 \x03(\x0b22.google.cloud.oracledatabase.v1.AutonomousDatabase\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"f\n\x1cGetAutonomousDatabaseRequest\x12F\n\x04name\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase"\x87\x02\n\x1fCreateAutonomousDatabaseRequest\x12H\n\x06parent\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\x120oracledatabase.googleapis.com/AutonomousDatabase\x12#\n\x16autonomous_database_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12T\n\x13autonomous_database\x18\x03 \x01(\x0b22.google.cloud.oracledatabase.v1.AutonomousDatabaseB\x03\xe0A\x02\x12\x1f\n\nrequest_id\x18\x04 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\x8a\x01\n\x1fDeleteAutonomousDatabaseRequest\x12F\n\x04name\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase\x12\x1f\n\nrequest_id\x18\x02 \x01(\tB\x0b\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01"\xa1\x01\n RestoreAutonomousDatabaseRequest\x12F\n\x04name\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase\x125\n\x0crestore_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x02"g\n\x1dStopAutonomousDatabaseRequest\x12F\n\x04name\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase"h\n\x1eStartAutonomousDatabaseRequest\x12F\n\x04name\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase"j\n RestartAutonomousDatabaseRequest\x12F\n\x04name\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase"\xe3\x01\n\'GenerateAutonomousDatabaseWalletRequest\x12F\n\x04name\x18\x01 \x01(\tB8\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase\x12?\n\x04type\x18\x02 \x01(\x0e2,.google.cloud.oracledatabase.v1.GenerateTypeB\x03\xe0A\x01\x12\x18\n\x0bis_regional\x18\x03 \x01(\x08B\x03\xe0A\x01\x12\x15\n\x08password\x18\x04 \x01(\tB\x03\xe0A\x02"H\n(GenerateAutonomousDatabaseWalletResponse\x12\x1c\n\x0farchive_content\x18\x01 \x01(\x0cB\x03\xe0A\x03"\x9d\x01\n\x1fListAutonomousDbVersionsRequest\x12I\n\x06parent\x18\x01 \x01(\tB9\xe0A\x02\xfaA3\x121oracledatabase.googleapis.com/AutonomousDbVersion\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"\x90\x01\n ListAutonomousDbVersionsResponse\x12S\n\x16autonomous_db_versions\x18\x01 \x03(\x0b23.google.cloud.oracledatabase.v1.AutonomousDbVersion\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xc8\x01\n*ListAutonomousDatabaseCharacterSetsRequest\x12T\n\x06parent\x18\x01 \x01(\tBD\xe0A\x02\xfaA>\x12<oracledatabase.googleapis.com/AutonomousDatabaseCharacterSet\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"\xb2\x01\n+ListAutonomousDatabaseCharacterSetsResponse\x12j\n"autonomous_database_character_sets\x18\x01 \x03(\x0b2>.google.cloud.oracledatabase.v1.AutonomousDatabaseCharacterSet\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xbc\x01\n$ListAutonomousDatabaseBackupsRequest\x12N\n\x06parent\x18\x01 \x01(\tB>\xe0A\x02\xfaA8\x126oracledatabase.googleapis.com/AutonomousDatabaseBackup\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x16\n\tpage_size\x18\x03 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x04 \x01(\tB\x03\xe0A\x01"\x9f\x01\n%ListAutonomousDatabaseBackupsResponse\x12]\n\x1bautonomous_database_backups\x18\x01 \x03(\x0b28.google.cloud.oracledatabase.v1.AutonomousDatabaseBackup\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xf10\n\x0eOracleDatabase\x12\x84\x02\n\x1fListCloudExadataInfrastructures\x12F.google.cloud.oracledatabase.v1.ListCloudExadataInfrastructuresRequest\x1aG.google.cloud.oracledatabase.v1.ListCloudExadataInfrastructuresResponse"P\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/locations/*}/cloudExadataInfrastructures\x12\xf1\x01\n\x1dGetCloudExadataInfrastructure\x12D.google.cloud.oracledatabase.v1.GetCloudExadataInfrastructureRequest\x1a:.google.cloud.oracledatabase.v1.CloudExadataInfrastructure"N\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1/{name=projects/*/locations/*/cloudExadataInfrastructures/*}\x12\xea\x02\n CreateCloudExadataInfrastructure\x12G.google.cloud.oracledatabase.v1.CreateCloudExadataInfrastructureRequest\x1a\x1d.google.longrunning.Operation"\xdd\x01\xcaA/\n\x1aCloudExadataInfrastructure\x12\x11OperationMetadata\xdaACparent,cloud_exadata_infrastructure,cloud_exadata_infrastructure_id\x82\xd3\xe4\x93\x02_"?/v1/{parent=projects/*/locations/*}/cloudExadataInfrastructures:\x1ccloud_exadata_infrastructure\x12\x87\x02\n DeleteCloudExadataInfrastructure\x12G.google.cloud.oracledatabase.v1.DeleteCloudExadataInfrastructureRequest\x1a\x1d.google.longrunning.Operation"{\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02A*?/v1/{name=projects/*/locations/*/cloudExadataInfrastructures/*}\x12\xd4\x01\n\x13ListCloudVmClusters\x12:.google.cloud.oracledatabase.v1.ListCloudVmClustersRequest\x1a;.google.cloud.oracledatabase.v1.ListCloudVmClustersResponse"D\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*}/cloudVmClusters\x12\xc1\x01\n\x11GetCloudVmCluster\x128.google.cloud.oracledatabase.v1.GetCloudVmClusterRequest\x1a..google.cloud.oracledatabase.v1.CloudVmCluster"B\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/cloudVmClusters/*}\x12\x96\x02\n\x14CreateCloudVmCluster\x12;.google.cloud.oracledatabase.v1.CreateCloudVmClusterRequest\x1a\x1d.google.longrunning.Operation"\xa1\x01\xcaA#\n\x0eCloudVmCluster\x12\x11OperationMetadata\xdaA+parent,cloud_vm_cluster,cloud_vm_cluster_id\x82\xd3\xe4\x93\x02G"3/v1/{parent=projects/*/locations/*}/cloudVmClusters:\x10cloud_vm_cluster\x12\xe3\x01\n\x14DeleteCloudVmCluster\x12;.google.cloud.oracledatabase.v1.DeleteCloudVmClusterRequest\x1a\x1d.google.longrunning.Operation"o\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/cloudVmClusters/*}\x12\xc8\x01\n\x10ListEntitlements\x127.google.cloud.oracledatabase.v1.ListEntitlementsRequest\x1a8.google.cloud.oracledatabase.v1.ListEntitlementsResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/entitlements\x12\xda\x01\n\rListDbServers\x124.google.cloud.oracledatabase.v1.ListDbServersRequest\x1a5.google.cloud.oracledatabase.v1.ListDbServersResponse"\\\xdaA\x06parent\x82\xd3\xe4\x93\x02M\x12K/v1/{parent=projects/*/locations/*/cloudExadataInfrastructures/*}/dbServers\x12\xc6\x01\n\x0bListDbNodes\x122.google.cloud.oracledatabase.v1.ListDbNodesRequest\x1a3.google.cloud.oracledatabase.v1.ListDbNodesResponse"N\xdaA\x06parent\x82\xd3\xe4\x93\x02?\x12=/v1/{parent=projects/*/locations/*/cloudVmClusters/*}/dbNodes\x12\xc0\x01\n\x0eListGiVersions\x125.google.cloud.oracledatabase.v1.ListGiVersionsRequest\x1a6.google.cloud.oracledatabase.v1.ListGiVersionsResponse"?\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1/{parent=projects/*/locations/*}/giVersions\x12\xd0\x01\n\x12ListDbSystemShapes\x129.google.cloud.oracledatabase.v1.ListDbSystemShapesRequest\x1a:.google.cloud.oracledatabase.v1.ListDbSystemShapesResponse"C\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1/{parent=projects/*/locations/*}/dbSystemShapes\x12\xe4\x01\n\x17ListAutonomousDatabases\x12>.google.cloud.oracledatabase.v1.ListAutonomousDatabasesRequest\x1a?.google.cloud.oracledatabase.v1.ListAutonomousDatabasesResponse"H\xdaA\x06parent\x82\xd3\xe4\x93\x029\x127/v1/{parent=projects/*/locations/*}/autonomousDatabases\x12\xd1\x01\n\x15GetAutonomousDatabase\x12<.google.cloud.oracledatabase.v1.GetAutonomousDatabaseRequest\x1a2.google.cloud.oracledatabase.v1.AutonomousDatabase"F\xdaA\x04name\x82\xd3\xe4\x93\x029\x127/v1/{name=projects/*/locations/*/autonomousDatabases/*}\x12\xaf\x02\n\x18CreateAutonomousDatabase\x12?.google.cloud.oracledatabase.v1.CreateAutonomousDatabaseRequest\x1a\x1d.google.longrunning.Operation"\xb2\x01\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA1parent,autonomous_database,autonomous_database_id\x82\xd3\xe4\x93\x02N"7/v1/{parent=projects/*/locations/*}/autonomousDatabases:\x13autonomous_database\x12\xef\x01\n\x18DeleteAutonomousDatabase\x12?.google.cloud.oracledatabase.v1.DeleteAutonomousDatabaseRequest\x1a\x1d.google.longrunning.Operation"s\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x029*7/v1/{name=projects/*/locations/*/autonomousDatabases/*}\x12\x87\x02\n\x19RestoreAutonomousDatabase\x12@.google.cloud.oracledatabase.v1.RestoreAutonomousDatabaseRequest\x1a\x1d.google.longrunning.Operation"\x88\x01\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x11name,restore_time\x82\xd3\xe4\x93\x02D"?/v1/{name=projects/*/locations/*/autonomousDatabases/*}:restore:\x01*\x12\xa9\x02\n GenerateAutonomousDatabaseWallet\x12G.google.cloud.oracledatabase.v1.GenerateAutonomousDatabaseWalletRequest\x1aH.google.cloud.oracledatabase.v1.GenerateAutonomousDatabaseWalletResponse"r\xdaA\x1ename,type,is_regional,password\x82\xd3\xe4\x93\x02K"F/v1/{name=projects/*/locations/*/autonomousDatabases/*}:generateWallet:\x01*\x12\xe8\x01\n\x18ListAutonomousDbVersions\x12?.google.cloud.oracledatabase.v1.ListAutonomousDbVersionsRequest\x1a@.google.cloud.oracledatabase.v1.ListAutonomousDbVersionsResponse"I\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*}/autonomousDbVersions\x12\x94\x02\n#ListAutonomousDatabaseCharacterSets\x12J.google.cloud.oracledatabase.v1.ListAutonomousDatabaseCharacterSetsRequest\x1aK.google.cloud.oracledatabase.v1.ListAutonomousDatabaseCharacterSetsResponse"T\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1/{parent=projects/*/locations/*}/autonomousDatabaseCharacterSets\x12\xfc\x01\n\x1dListAutonomousDatabaseBackups\x12D.google.cloud.oracledatabase.v1.ListAutonomousDatabaseBackupsRequest\x1aE.google.cloud.oracledatabase.v1.ListAutonomousDatabaseBackupsResponse"N\xdaA\x06parent\x82\xd3\xe4\x93\x02?\x12=/v1/{parent=projects/*/locations/*}/autonomousDatabaseBackups\x12\xf0\x01\n\x16StopAutonomousDatabase\x12=.google.cloud.oracledatabase.v1.StopAutonomousDatabaseRequest\x1a\x1d.google.longrunning.Operation"x\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02A"</v1/{name=projects/*/locations/*/autonomousDatabases/*}:stop:\x01*\x12\xf3\x01\n\x17StartAutonomousDatabase\x12>.google.cloud.oracledatabase.v1.StartAutonomousDatabaseRequest\x1a\x1d.google.longrunning.Operation"y\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02B"=/v1/{name=projects/*/locations/*/autonomousDatabases/*}:start:\x01*\x12\xf9\x01\n\x19RestartAutonomousDatabase\x12@.google.cloud.oracledatabase.v1.RestartAutonomousDatabaseRequest\x1a\x1d.google.longrunning.Operation"{\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02D"?/v1/{name=projects/*/locations/*/autonomousDatabases/*}:restart:\x01*\x1aQ\xcaA\x1doracledatabase.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xb6\x02\n"com.google.cloud.oracledatabase.v1B\x0bV1mainProtoP\x01ZJcloud.google.com/go/oracledatabase/apiv1/oracledatabasepb;oracledatabasepb\xaa\x02\x1eGoogle.Cloud.OracleDatabase.V1\xca\x02\x1eGoogle\\Cloud\\OracleDatabase\\V1\xea\x02!Google::Cloud::OracleDatabase::V1\xeaAN\n\x1ecompute.googleapis.com/Network\x12,projects/{project}/global/networks/{network}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.oracledatabase.v1.oracledatabase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n"com.google.cloud.oracledatabase.v1B\x0bV1mainProtoP\x01ZJcloud.google.com/go/oracledatabase/apiv1/oracledatabasepb;oracledatabasepb\xaa\x02\x1eGoogle.Cloud.OracleDatabase.V1\xca\x02\x1eGoogle\\Cloud\\OracleDatabase\\V1\xea\x02!Google::Cloud::OracleDatabase::V1\xeaAN\n\x1ecompute.googleapis.com/Network\x12,projects/{project}/global/networks/{network}'
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA:\x128oracledatabase.googleapis.com/CloudExadataInfrastructure'
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_GETCLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA:\n8oracledatabase.googleapis.com/CloudExadataInfrastructure'
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA:\x128oracledatabase.googleapis.com/CloudExadataInfrastructure'
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['cloud_exadata_infrastructure_id']._loaded_options = None
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['cloud_exadata_infrastructure_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['cloud_exadata_infrastructure']._loaded_options = None
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['cloud_exadata_infrastructure']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA:\n8oracledatabase.googleapis.com/CloudExadataInfrastructure'
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA.\x12,oracledatabase.googleapis.com/CloudVmCluster'
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCLOUDVMCLUSTERSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_GETCLOUDVMCLUSTERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCLOUDVMCLUSTERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA.\n,oracledatabase.googleapis.com/CloudVmCluster'
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA.\x12,oracledatabase.googleapis.com/CloudVmCluster'
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['cloud_vm_cluster_id']._loaded_options = None
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['cloud_vm_cluster_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['cloud_vm_cluster']._loaded_options = None
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['cloud_vm_cluster']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATECLOUDVMCLUSTERREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECLOUDVMCLUSTERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECLOUDVMCLUSTERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA.\n,oracledatabase.googleapis.com/CloudVmCluster'
    _globals['_DELETECLOUDVMCLUSTERREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETECLOUDVMCLUSTERREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETECLOUDVMCLUSTERREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_DELETECLOUDVMCLUSTERREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA+\x12)oracledatabase.googleapis.com/Entitlement'
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTDBSERVERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTDBSERVERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\x12&oracledatabase.googleapis.com/DbServer'
    _globals['_LISTDBSERVERSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTDBSERVERSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTDBSERVERSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTDBSERVERSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTDBNODESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTDBNODESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$oracledatabase.googleapis.com/DbNode'
    _globals['_LISTDBNODESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTDBNODESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTDBNODESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTDBNODESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTGIVERSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTGIVERSIONSREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'oracledatabase.googleapis.com/GiVersion"
    _globals['_LISTGIVERSIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTGIVERSIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTGIVERSIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTGIVERSIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTDBSYSTEMSHAPESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTDBSYSTEMSHAPESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+oracledatabase.googleapis.com/DbSystemShape'
    _globals['_LISTDBSYSTEMSHAPESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTDBSYSTEMSHAPESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTDBSYSTEMSHAPESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTDBSYSTEMSHAPESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['percent_complete']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['percent_complete']._serialized_options = b'\xe0A\x03'
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA2\x120oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_GETAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA2\x120oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['autonomous_database_id']._loaded_options = None
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['autonomous_database_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['autonomous_database']._loaded_options = None
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['autonomous_database']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_DELETEAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_DELETEAUTONOMOUSDATABASEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETEAUTONOMOUSDATABASEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01\xe2\x8c\xcf\xd7\x08\x02\x08\x01'
    _globals['_RESTOREAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESTOREAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_RESTOREAUTONOMOUSDATABASEREQUEST'].fields_by_name['restore_time']._loaded_options = None
    _globals['_RESTOREAUTONOMOUSDATABASEREQUEST'].fields_by_name['restore_time']._serialized_options = b'\xe0A\x02'
    _globals['_STOPAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_STOPAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_STARTAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_STARTAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_RESTARTAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESTARTAUTONOMOUSDATABASEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA2\n0oracledatabase.googleapis.com/AutonomousDatabase'
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['type']._loaded_options = None
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['type']._serialized_options = b'\xe0A\x01'
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['is_regional']._loaded_options = None
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['is_regional']._serialized_options = b'\xe0A\x01'
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['password']._loaded_options = None
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST'].fields_by_name['password']._serialized_options = b'\xe0A\x02'
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETRESPONSE'].fields_by_name['archive_content']._loaded_options = None
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETRESPONSE'].fields_by_name['archive_content']._serialized_options = b'\xe0A\x03'
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA3\x121oracledatabase.googleapis.com/AutonomousDbVersion'
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA>\x12<oracledatabase.googleapis.com/AutonomousDatabaseCharacterSet'
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA8\x126oracledatabase.googleapis.com/AutonomousDatabaseBackup'
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_ORACLEDATABASE']._loaded_options = None
    _globals['_ORACLEDATABASE']._serialized_options = b'\xcaA\x1doracledatabase.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_ORACLEDATABASE'].methods_by_name['ListCloudExadataInfrastructures']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListCloudExadataInfrastructures']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/locations/*}/cloudExadataInfrastructures'
    _globals['_ORACLEDATABASE'].methods_by_name['GetCloudExadataInfrastructure']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['GetCloudExadataInfrastructure']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1/{name=projects/*/locations/*/cloudExadataInfrastructures/*}'
    _globals['_ORACLEDATABASE'].methods_by_name['CreateCloudExadataInfrastructure']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['CreateCloudExadataInfrastructure']._serialized_options = b'\xcaA/\n\x1aCloudExadataInfrastructure\x12\x11OperationMetadata\xdaACparent,cloud_exadata_infrastructure,cloud_exadata_infrastructure_id\x82\xd3\xe4\x93\x02_"?/v1/{parent=projects/*/locations/*}/cloudExadataInfrastructures:\x1ccloud_exadata_infrastructure'
    _globals['_ORACLEDATABASE'].methods_by_name['DeleteCloudExadataInfrastructure']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['DeleteCloudExadataInfrastructure']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02A*?/v1/{name=projects/*/locations/*/cloudExadataInfrastructures/*}'
    _globals['_ORACLEDATABASE'].methods_by_name['ListCloudVmClusters']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListCloudVmClusters']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*}/cloudVmClusters'
    _globals['_ORACLEDATABASE'].methods_by_name['GetCloudVmCluster']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['GetCloudVmCluster']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/cloudVmClusters/*}'
    _globals['_ORACLEDATABASE'].methods_by_name['CreateCloudVmCluster']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['CreateCloudVmCluster']._serialized_options = b'\xcaA#\n\x0eCloudVmCluster\x12\x11OperationMetadata\xdaA+parent,cloud_vm_cluster,cloud_vm_cluster_id\x82\xd3\xe4\x93\x02G"3/v1/{parent=projects/*/locations/*}/cloudVmClusters:\x10cloud_vm_cluster'
    _globals['_ORACLEDATABASE'].methods_by_name['DeleteCloudVmCluster']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['DeleteCloudVmCluster']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/cloudVmClusters/*}'
    _globals['_ORACLEDATABASE'].methods_by_name['ListEntitlements']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListEntitlements']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/entitlements'
    _globals['_ORACLEDATABASE'].methods_by_name['ListDbServers']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListDbServers']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02M\x12K/v1/{parent=projects/*/locations/*/cloudExadataInfrastructures/*}/dbServers'
    _globals['_ORACLEDATABASE'].methods_by_name['ListDbNodes']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListDbNodes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02?\x12=/v1/{parent=projects/*/locations/*/cloudVmClusters/*}/dbNodes'
    _globals['_ORACLEDATABASE'].methods_by_name['ListGiVersions']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListGiVersions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1/{parent=projects/*/locations/*}/giVersions'
    _globals['_ORACLEDATABASE'].methods_by_name['ListDbSystemShapes']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListDbSystemShapes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1/{parent=projects/*/locations/*}/dbSystemShapes'
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDatabases']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDatabases']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x029\x127/v1/{parent=projects/*/locations/*}/autonomousDatabases'
    _globals['_ORACLEDATABASE'].methods_by_name['GetAutonomousDatabase']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['GetAutonomousDatabase']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x029\x127/v1/{name=projects/*/locations/*/autonomousDatabases/*}'
    _globals['_ORACLEDATABASE'].methods_by_name['CreateAutonomousDatabase']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['CreateAutonomousDatabase']._serialized_options = b'\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA1parent,autonomous_database,autonomous_database_id\x82\xd3\xe4\x93\x02N"7/v1/{parent=projects/*/locations/*}/autonomousDatabases:\x13autonomous_database'
    _globals['_ORACLEDATABASE'].methods_by_name['DeleteAutonomousDatabase']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['DeleteAutonomousDatabase']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x029*7/v1/{name=projects/*/locations/*/autonomousDatabases/*}'
    _globals['_ORACLEDATABASE'].methods_by_name['RestoreAutonomousDatabase']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['RestoreAutonomousDatabase']._serialized_options = b'\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x11name,restore_time\x82\xd3\xe4\x93\x02D"?/v1/{name=projects/*/locations/*/autonomousDatabases/*}:restore:\x01*'
    _globals['_ORACLEDATABASE'].methods_by_name['GenerateAutonomousDatabaseWallet']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['GenerateAutonomousDatabaseWallet']._serialized_options = b'\xdaA\x1ename,type,is_regional,password\x82\xd3\xe4\x93\x02K"F/v1/{name=projects/*/locations/*/autonomousDatabases/*}:generateWallet:\x01*'
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDbVersions']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDbVersions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02:\x128/v1/{parent=projects/*/locations/*}/autonomousDbVersions'
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDatabaseCharacterSets']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDatabaseCharacterSets']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1/{parent=projects/*/locations/*}/autonomousDatabaseCharacterSets'
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDatabaseBackups']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['ListAutonomousDatabaseBackups']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02?\x12=/v1/{parent=projects/*/locations/*}/autonomousDatabaseBackups'
    _globals['_ORACLEDATABASE'].methods_by_name['StopAutonomousDatabase']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['StopAutonomousDatabase']._serialized_options = b'\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02A"</v1/{name=projects/*/locations/*/autonomousDatabases/*}:stop:\x01*'
    _globals['_ORACLEDATABASE'].methods_by_name['StartAutonomousDatabase']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['StartAutonomousDatabase']._serialized_options = b'\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02B"=/v1/{name=projects/*/locations/*/autonomousDatabases/*}:start:\x01*'
    _globals['_ORACLEDATABASE'].methods_by_name['RestartAutonomousDatabase']._loaded_options = None
    _globals['_ORACLEDATABASE'].methods_by_name['RestartAutonomousDatabase']._serialized_options = b'\xcaA\'\n\x12AutonomousDatabase\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02D"?/v1/{name=projects/*/locations/*/autonomousDatabases/*}:restart:\x01*'
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST']._serialized_start = 928
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESREQUEST']._serialized_end = 1099
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESRESPONSE']._serialized_start = 1102
    _globals['_LISTCLOUDEXADATAINFRASTRUCTURESRESPONSE']._serialized_end = 1267
    _globals['_GETCLOUDEXADATAINFRASTRUCTUREREQUEST']._serialized_start = 1269
    _globals['_GETCLOUDEXADATAINFRASTRUCTUREREQUEST']._serialized_end = 1387
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST']._serialized_start = 1390
    _globals['_CREATECLOUDEXADATAINFRASTRUCTUREREQUEST']._serialized_end = 1695
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST']._serialized_start = 1698
    _globals['_DELETECLOUDEXADATAINFRASTRUCTUREREQUEST']._serialized_end = 1872
    _globals['_LISTCLOUDVMCLUSTERSREQUEST']._serialized_start = 1875
    _globals['_LISTCLOUDVMCLUSTERSREQUEST']._serialized_end = 2043
    _globals['_LISTCLOUDVMCLUSTERSRESPONSE']._serialized_start = 2046
    _globals['_LISTCLOUDVMCLUSTERSRESPONSE']._serialized_end = 2175
    _globals['_GETCLOUDVMCLUSTERREQUEST']._serialized_start = 2177
    _globals['_GETCLOUDVMCLUSTERREQUEST']._serialized_end = 2271
    _globals['_CREATECLOUDVMCLUSTERREQUEST']._serialized_start = 2274
    _globals['_CREATECLOUDVMCLUSTERREQUEST']._serialized_end = 2519
    _globals['_DELETECLOUDVMCLUSTERREQUEST']._serialized_start = 2522
    _globals['_DELETECLOUDVMCLUSTERREQUEST']._serialized_end = 2672
    _globals['_LISTENTITLEMENTSREQUEST']._serialized_start = 2675
    _globals['_LISTENTITLEMENTSREQUEST']._serialized_end = 2816
    _globals['_LISTENTITLEMENTSRESPONSE']._serialized_start = 2818
    _globals['_LISTENTITLEMENTSRESPONSE']._serialized_end = 2936
    _globals['_LISTDBSERVERSREQUEST']._serialized_start = 2939
    _globals['_LISTDBSERVERSREQUEST']._serialized_end = 3074
    _globals['_LISTDBSERVERSRESPONSE']._serialized_start = 3076
    _globals['_LISTDBSERVERSRESPONSE']._serialized_end = 3186
    _globals['_LISTDBNODESREQUEST']._serialized_start = 3189
    _globals['_LISTDBNODESREQUEST']._serialized_end = 3320
    _globals['_LISTDBNODESRESPONSE']._serialized_start = 3322
    _globals['_LISTDBNODESRESPONSE']._serialized_end = 3426
    _globals['_LISTGIVERSIONSREQUEST']._serialized_start = 3429
    _globals['_LISTGIVERSIONSREQUEST']._serialized_end = 3566
    _globals['_LISTGIVERSIONSRESPONSE']._serialized_start = 3568
    _globals['_LISTGIVERSIONSRESPONSE']._serialized_end = 3681
    _globals['_LISTDBSYSTEMSHAPESREQUEST']._serialized_start = 3684
    _globals['_LISTDBSYSTEMSHAPESREQUEST']._serialized_end = 3829
    _globals['_LISTDBSYSTEMSHAPESRESPONSE']._serialized_start = 3831
    _globals['_LISTDBSYSTEMSHAPESRESPONSE']._serialized_end = 3957
    _globals['_OPERATIONMETADATA']._serialized_start = 3960
    _globals['_OPERATIONMETADATA']._serialized_end = 4247
    _globals['_LISTAUTONOMOUSDATABASESREQUEST']._serialized_start = 4250
    _globals['_LISTAUTONOMOUSDATABASESREQUEST']._serialized_end = 4449
    _globals['_LISTAUTONOMOUSDATABASESRESPONSE']._serialized_start = 4452
    _globals['_LISTAUTONOMOUSDATABASESRESPONSE']._serialized_end = 4592
    _globals['_GETAUTONOMOUSDATABASEREQUEST']._serialized_start = 4594
    _globals['_GETAUTONOMOUSDATABASEREQUEST']._serialized_end = 4696
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST']._serialized_start = 4699
    _globals['_CREATEAUTONOMOUSDATABASEREQUEST']._serialized_end = 4962
    _globals['_DELETEAUTONOMOUSDATABASEREQUEST']._serialized_start = 4965
    _globals['_DELETEAUTONOMOUSDATABASEREQUEST']._serialized_end = 5103
    _globals['_RESTOREAUTONOMOUSDATABASEREQUEST']._serialized_start = 5106
    _globals['_RESTOREAUTONOMOUSDATABASEREQUEST']._serialized_end = 5267
    _globals['_STOPAUTONOMOUSDATABASEREQUEST']._serialized_start = 5269
    _globals['_STOPAUTONOMOUSDATABASEREQUEST']._serialized_end = 5372
    _globals['_STARTAUTONOMOUSDATABASEREQUEST']._serialized_start = 5374
    _globals['_STARTAUTONOMOUSDATABASEREQUEST']._serialized_end = 5478
    _globals['_RESTARTAUTONOMOUSDATABASEREQUEST']._serialized_start = 5480
    _globals['_RESTARTAUTONOMOUSDATABASEREQUEST']._serialized_end = 5586
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST']._serialized_start = 5589
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETREQUEST']._serialized_end = 5816
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETRESPONSE']._serialized_start = 5818
    _globals['_GENERATEAUTONOMOUSDATABASEWALLETRESPONSE']._serialized_end = 5890
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST']._serialized_start = 5893
    _globals['_LISTAUTONOMOUSDBVERSIONSREQUEST']._serialized_end = 6050
    _globals['_LISTAUTONOMOUSDBVERSIONSRESPONSE']._serialized_start = 6053
    _globals['_LISTAUTONOMOUSDBVERSIONSRESPONSE']._serialized_end = 6197
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST']._serialized_start = 6200
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSREQUEST']._serialized_end = 6400
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSRESPONSE']._serialized_start = 6403
    _globals['_LISTAUTONOMOUSDATABASECHARACTERSETSRESPONSE']._serialized_end = 6581
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST']._serialized_start = 6584
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSREQUEST']._serialized_end = 6772
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSRESPONSE']._serialized_start = 6775
    _globals['_LISTAUTONOMOUSDATABASEBACKUPSRESPONSE']._serialized_end = 6934
    _globals['_ORACLEDATABASE']._serialized_start = 6937
    _globals['_ORACLEDATABASE']._serialized_end = 13194