from MF.V3.Descriptors.Settings.Advanced import * 
from MF.V3.Descriptors.Settings.Camera import * 
from MF.V3.Descriptors.Settings.Capture import * 
from MF.V3.Descriptors.Settings.I18n import * 
from MF.V3.Descriptors.Settings.Projector import * 
from MF.V3.Descriptors.Settings.Scanner import * 
from MF.V3.Descriptors.Settings.Software import * 
from MF.V3.Descriptors.Settings.Style import * 
from MF.V3.Descriptors.Settings.Turntable import * 
from MF.V3.Descriptors.Settings.Tutorials import * 
from MF.V3.Descriptors.Settings.Viewer import * 
