"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/analytics/admin/v1beta/analytics_admin.proto')
_sym_db = _symbol_database.Default()
from .....google.analytics.admin.v1beta import access_report_pb2 as google_dot_analytics_dot_admin_dot_v1beta_dot_access__report__pb2
from .....google.analytics.admin.v1beta import resources_pb2 as google_dot_analytics_dot_admin_dot_v1beta_dot_resources__pb2
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3google/analytics/admin/v1beta/analytics_admin.proto\x12\x1dgoogle.analytics.admin.v1beta\x1a1google/analytics/admin/v1beta/access_report.proto\x1a-google/analytics/admin/v1beta/resources.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xda\x04\n\x16RunAccessReportRequest\x12\x0e\n\x06entity\x18\x01 \x01(\t\x12B\n\ndimensions\x18\x02 \x03(\x0b2..google.analytics.admin.v1beta.AccessDimension\x12<\n\x07metrics\x18\x03 \x03(\x0b2+.google.analytics.admin.v1beta.AccessMetric\x12C\n\x0bdate_ranges\x18\x04 \x03(\x0b2..google.analytics.admin.v1beta.AccessDateRange\x12O\n\x10dimension_filter\x18\x05 \x01(\x0b25.google.analytics.admin.v1beta.AccessFilterExpression\x12L\n\rmetric_filter\x18\x06 \x01(\x0b25.google.analytics.admin.v1beta.AccessFilterExpression\x12\x0e\n\x06offset\x18\x07 \x01(\x03\x12\r\n\x05limit\x18\x08 \x01(\x03\x12\x11\n\ttime_zone\x18\t \x01(\t\x12?\n\torder_bys\x18\n \x03(\x0b2,.google.analytics.admin.v1beta.AccessOrderBy\x12\x1b\n\x13return_entity_quota\x18\x0b \x01(\x08\x12\x1e\n\x11include_all_users\x18\x0c \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rexpand_groups\x18\r \x01(\x08B\x03\xe0A\x01"\xbb\x02\n\x17RunAccessReportResponse\x12O\n\x11dimension_headers\x18\x01 \x03(\x0b24.google.analytics.admin.v1beta.AccessDimensionHeader\x12I\n\x0emetric_headers\x18\x02 \x03(\x0b21.google.analytics.admin.v1beta.AccessMetricHeader\x126\n\x04rows\x18\x03 \x03(\x0b2(.google.analytics.admin.v1beta.AccessRow\x12\x11\n\trow_count\x18\x04 \x01(\x05\x129\n\x05quota\x18\x05 \x01(\x0b2*.google.analytics.admin.v1beta.AccessQuota"P\n\x11GetAccountRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%analyticsadmin.googleapis.com/Account"R\n\x13ListAccountsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x14\n\x0cshow_deleted\x18\x03 \x01(\x08"i\n\x14ListAccountsResponse\x128\n\x08accounts\x18\x01 \x03(\x0b2&.google.analytics.admin.v1beta.Account\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"S\n\x14DeleteAccountRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%analyticsadmin.googleapis.com/Account"\x8a\x01\n\x14UpdateAccountRequest\x12<\n\x07account\x18\x01 \x01(\x0b2&.google.analytics.admin.v1beta.AccountB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"n\n\x1dProvisionAccountTicketRequest\x127\n\x07account\x18\x01 \x01(\x0b2&.google.analytics.admin.v1beta.Account\x12\x14\n\x0credirect_uri\x18\x02 \x01(\t";\n\x1eProvisionAccountTicketResponse\x12\x19\n\x11account_ticket_id\x18\x01 \x01(\t"R\n\x12GetPropertyRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/Property"i\n\x15ListPropertiesRequest\x12\x13\n\x06filter\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x14\n\x0cshow_deleted\x18\x04 \x01(\x08"n\n\x16ListPropertiesResponse\x12;\n\nproperties\x18\x01 \x03(\x0b2\'.google.analytics.admin.v1beta.Property\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x8d\x01\n\x15UpdatePropertyRequest\x12>\n\x08property\x18\x01 \x01(\x0b2\'.google.analytics.admin.v1beta.PropertyB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"W\n\x15CreatePropertyRequest\x12>\n\x08property\x18\x01 \x01(\x0b2\'.google.analytics.admin.v1beta.PropertyB\x03\xe0A\x02"U\n\x15DeletePropertyRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/Property"\xa8\x01\n\x19CreateFirebaseLinkRequest\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/FirebaseLink\x12G\n\rfirebase_link\x18\x02 \x01(\x0b2+.google.analytics.admin.v1beta.FirebaseLinkB\x03\xe0A\x02"]\n\x19DeleteFirebaseLinkRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*analyticsadmin.googleapis.com/FirebaseLink"\x85\x01\n\x18ListFirebaseLinksRequest\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/FirebaseLink\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"y\n\x19ListFirebaseLinksResponse\x12C\n\x0efirebase_links\x18\x01 \x03(\x0b2+.google.analytics.admin.v1beta.FirebaseLink\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xad\x01\n\x1aCreateGoogleAdsLinkRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+analyticsadmin.googleapis.com/GoogleAdsLink\x12J\n\x0fgoogle_ads_link\x18\x02 \x01(\x0b2,.google.analytics.admin.v1beta.GoogleAdsLinkB\x03\xe0A\x02"\x99\x01\n\x1aUpdateGoogleAdsLinkRequest\x12E\n\x0fgoogle_ads_link\x18\x01 \x01(\x0b2,.google.analytics.admin.v1beta.GoogleAdsLink\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"_\n\x1aDeleteGoogleAdsLinkRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+analyticsadmin.googleapis.com/GoogleAdsLink"\x87\x01\n\x19ListGoogleAdsLinksRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+analyticsadmin.googleapis.com/GoogleAdsLink\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"}\n\x1aListGoogleAdsLinksResponse\x12F\n\x10google_ads_links\x18\x01 \x03(\x0b2,.google.analytics.admin.v1beta.GoogleAdsLink\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"h\n\x1dGetDataSharingSettingsRequest\x12G\n\x04name\x18\x01 \x01(\tB9\xe0A\x02\xfaA3\n1analyticsadmin.googleapis.com/DataSharingSettings"D\n\x1bListAccountSummariesRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t"\x81\x01\n\x1cListAccountSummariesResponse\x12H\n\x11account_summaries\x18\x01 \x03(\x0b2-.google.analytics.admin.v1beta.AccountSummary\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x86\x01\n$AcknowledgeUserDataCollectionRequest\x12@\n\x08property\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/Property\x12\x1c\n\x0facknowledgement\x18\x02 \x01(\tB\x03\xe0A\x02"\'\n%AcknowledgeUserDataCollectionResponse"\x81\x04\n SearchChangeHistoryEventsRequest\x12>\n\x07account\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%analyticsadmin.googleapis.com/Account\x12@\n\x08property\x18\x02 \x01(\tB.\xe0A\x01\xfaA(\n&analyticsadmin.googleapis.com/Property\x12T\n\rresource_type\x18\x03 \x03(\x0e28.google.analytics.admin.v1beta.ChangeHistoryResourceTypeB\x03\xe0A\x01\x12>\n\x06action\x18\x04 \x03(\x0e2).google.analytics.admin.v1beta.ActionTypeB\x03\xe0A\x01\x12\x18\n\x0bactor_email\x18\x05 \x03(\tB\x03\xe0A\x01\x12=\n\x14earliest_change_time\x18\x06 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x01\x12;\n\x12latest_change_time\x18\x07 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x01\x12\x16\n\tpage_size\x18\x08 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\t \x01(\tB\x03\xe0A\x01"\x8e\x01\n!SearchChangeHistoryEventsResponse\x12P\n\x15change_history_events\x18\x01 \x03(\x0b21.google.analytics.admin.v1beta.ChangeHistoryEvent\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"t\n#GetMeasurementProtocolSecretRequest\x12M\n\x04name\x18\x01 \x01(\tB?\xe0A\x02\xfaA9\n7analyticsadmin.googleapis.com/MeasurementProtocolSecret"\xdd\x01\n&CreateMeasurementProtocolSecretRequest\x12O\n\x06parent\x18\x01 \x01(\tB?\xe0A\x02\xfaA9\x127analyticsadmin.googleapis.com/MeasurementProtocolSecret\x12b\n\x1bmeasurement_protocol_secret\x18\x02 \x01(\x0b28.google.analytics.admin.v1beta.MeasurementProtocolSecretB\x03\xe0A\x02"w\n&DeleteMeasurementProtocolSecretRequest\x12M\n\x04name\x18\x01 \x01(\tB?\xe0A\x02\xfaA9\n7analyticsadmin.googleapis.com/MeasurementProtocolSecret"\xc2\x01\n&UpdateMeasurementProtocolSecretRequest\x12b\n\x1bmeasurement_protocol_secret\x18\x01 \x01(\x0b28.google.analytics.admin.v1beta.MeasurementProtocolSecretB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\x9f\x01\n%ListMeasurementProtocolSecretsRequest\x12O\n\x06parent\x18\x01 \x01(\tB?\xe0A\x02\xfaA9\x127analyticsadmin.googleapis.com/MeasurementProtocolSecret\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"\xa1\x01\n&ListMeasurementProtocolSecretsResponse\x12^\n\x1cmeasurement_protocol_secrets\x18\x01 \x03(\x0b28.google.analytics.admin.v1beta.MeasurementProtocolSecret\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb4\x01\n\x1cCreateConversionEventRequest\x12M\n\x10conversion_event\x18\x01 \x01(\x0b2..google.analytics.admin.v1beta.ConversionEventB\x03\xe0A\x02\x12E\n\x06parent\x18\x02 \x01(\tB5\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/ConversionEvent"\xa3\x01\n\x1cUpdateConversionEventRequest\x12M\n\x10conversion_event\x18\x01 \x01(\x0b2..google.analytics.admin.v1beta.ConversionEventB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"`\n\x19GetConversionEventRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/ConversionEvent"c\n\x1cDeleteConversionEventRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/ConversionEvent"\x8b\x01\n\x1bListConversionEventsRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/ConversionEvent\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"\x82\x01\n\x1cListConversionEventsResponse\x12I\n\x11conversion_events\x18\x01 \x03(\x0b2..google.analytics.admin.v1beta.ConversionEvent\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x98\x01\n\x15CreateKeyEventRequest\x12?\n\tkey_event\x18\x01 \x01(\x0b2\'.google.analytics.admin.v1beta.KeyEventB\x03\xe0A\x02\x12>\n\x06parent\x18\x02 \x01(\tB.\xe0A\x02\xfaA(\x12&analyticsadmin.googleapis.com/KeyEvent"\x8e\x01\n\x15UpdateKeyEventRequest\x12?\n\tkey_event\x18\x01 \x01(\x0b2\'.google.analytics.admin.v1beta.KeyEventB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"R\n\x12GetKeyEventRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/KeyEvent"U\n\x15DeleteKeyEventRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/KeyEvent"}\n\x14ListKeyEventsRequest\x12>\n\x06parent\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\x12&analyticsadmin.googleapis.com/KeyEvent\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"m\n\x15ListKeyEventsResponse\x12;\n\nkey_events\x18\x01 \x03(\x0b2\'.google.analytics.admin.v1beta.KeyEvent\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb4\x01\n\x1cCreateCustomDimensionRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/CustomDimension\x12M\n\x10custom_dimension\x18\x02 \x01(\x0b2..google.analytics.admin.v1beta.CustomDimensionB\x03\xe0A\x02"\x9e\x01\n\x1cUpdateCustomDimensionRequest\x12H\n\x10custom_dimension\x18\x01 \x01(\x0b2..google.analytics.admin.v1beta.CustomDimension\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\x8b\x01\n\x1bListCustomDimensionsRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/CustomDimension\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"\x82\x01\n\x1cListCustomDimensionsResponse\x12I\n\x11custom_dimensions\x18\x01 \x03(\x0b2..google.analytics.admin.v1beta.CustomDimension\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"d\n\x1dArchiveCustomDimensionRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/CustomDimension"`\n\x19GetCustomDimensionRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/CustomDimension"\xa8\x01\n\x19CreateCustomMetricRequest\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/CustomMetric\x12G\n\rcustom_metric\x18\x02 \x01(\x0b2+.google.analytics.admin.v1beta.CustomMetricB\x03\xe0A\x02"\x95\x01\n\x19UpdateCustomMetricRequest\x12B\n\rcustom_metric\x18\x01 \x01(\x0b2+.google.analytics.admin.v1beta.CustomMetric\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\x85\x01\n\x18ListCustomMetricsRequest\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/CustomMetric\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"y\n\x19ListCustomMetricsResponse\x12C\n\x0ecustom_metrics\x18\x01 \x03(\x0b2+.google.analytics.admin.v1beta.CustomMetric\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"^\n\x1aArchiveCustomMetricRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*analyticsadmin.googleapis.com/CustomMetric"Z\n\x16GetCustomMetricRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*analyticsadmin.googleapis.com/CustomMetric"l\n\x1fGetDataRetentionSettingsRequest\x12I\n\x04name\x18\x01 \x01(\tB;\xe0A\x02\xfaA5\n3analyticsadmin.googleapis.com/DataRetentionSettings"\xb6\x01\n"UpdateDataRetentionSettingsRequest\x12Z\n\x17data_retention_settings\x18\x01 \x01(\x0b24.google.analytics.admin.v1beta.DataRetentionSettingsB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\xa0\x01\n\x17CreateDataStreamRequest\x12@\n\x06parent\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\x12(analyticsadmin.googleapis.com/DataStream\x12C\n\x0bdata_stream\x18\x02 \x01(\x0b2).google.analytics.admin.v1beta.DataStreamB\x03\xe0A\x02"Y\n\x17DeleteDataStreamRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(analyticsadmin.googleapis.com/DataStream"\x8f\x01\n\x17UpdateDataStreamRequest\x12>\n\x0bdata_stream\x18\x01 \x01(\x0b2).google.analytics.admin.v1beta.DataStream\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\x81\x01\n\x16ListDataStreamsRequest\x12@\n\x06parent\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\x12(analyticsadmin.googleapis.com/DataStream\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"s\n\x17ListDataStreamsResponse\x12?\n\x0cdata_streams\x18\x01 \x03(\x0b2).google.analytics.admin.v1beta.DataStream\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"V\n\x14GetDataStreamRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(analyticsadmin.googleapis.com/DataStream2\xefW\n\x15AnalyticsAdminService\x12\x90\x01\n\nGetAccount\x120.google.analytics.admin.v1beta.GetAccountRequest\x1a&.google.analytics.admin.v1beta.Account"(\xdaA\x04name\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1beta/{name=accounts/*}\x12\x91\x01\n\x0cListAccounts\x122.google.analytics.admin.v1beta.ListAccountsRequest\x1a3.google.analytics.admin.v1beta.ListAccountsResponse"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1beta/accounts\x12\x86\x01\n\rDeleteAccount\x123.google.analytics.admin.v1beta.DeleteAccountRequest\x1a\x16.google.protobuf.Empty"(\xdaA\x04name\x82\xd3\xe4\x93\x02\x1b*\x19/v1beta/{name=accounts/*}\x12\xb6\x01\n\rUpdateAccount\x123.google.analytics.admin.v1beta.UpdateAccountRequest\x1a&.google.analytics.admin.v1beta.Account"H\xdaA\x13account,update_mask\x82\xd3\xe4\x93\x02,2!/v1beta/{account.name=accounts/*}:\x07account\x12\xc9\x01\n\x16ProvisionAccountTicket\x12<.google.analytics.admin.v1beta.ProvisionAccountTicketRequest\x1a=.google.analytics.admin.v1beta.ProvisionAccountTicketResponse"2\x82\xd3\xe4\x93\x02,"\'/v1beta/accounts:provisionAccountTicket:\x01*\x12\xb1\x01\n\x14ListAccountSummaries\x12:.google.analytics.admin.v1beta.ListAccountSummariesRequest\x1a;.google.analytics.admin.v1beta.ListAccountSummariesResponse" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1beta/accountSummaries\x12\x95\x01\n\x0bGetProperty\x121.google.analytics.admin.v1beta.GetPropertyRequest\x1a\'.google.analytics.admin.v1beta.Property"*\xdaA\x04name\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1beta/{name=properties/*}\x12\x99\x01\n\x0eListProperties\x124.google.analytics.admin.v1beta.ListPropertiesRequest\x1a5.google.analytics.admin.v1beta.ListPropertiesResponse"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1beta/properties\x12\xa0\x01\n\x0eCreateProperty\x124.google.analytics.admin.v1beta.CreatePropertyRequest\x1a\'.google.analytics.admin.v1beta.Property"/\xdaA\x08property\x82\xd3\xe4\x93\x02\x1e"\x12/v1beta/properties:\x08property\x12\x9b\x01\n\x0eDeleteProperty\x124.google.analytics.admin.v1beta.DeletePropertyRequest\x1a\'.google.analytics.admin.v1beta.Property"*\xdaA\x04name\x82\xd3\xe4\x93\x02\x1d*\x1b/v1beta/{name=properties/*}\x12\xbe\x01\n\x0eUpdateProperty\x124.google.analytics.admin.v1beta.UpdatePropertyRequest\x1a\'.google.analytics.admin.v1beta.Property"M\xdaA\x14property,update_mask\x82\xd3\xe4\x93\x0202$/v1beta/{property.name=properties/*}:\x08property\x12\xd6\x01\n\x12CreateFirebaseLink\x128.google.analytics.admin.v1beta.CreateFirebaseLinkRequest\x1a+.google.analytics.admin.v1beta.FirebaseLink"Y\xdaA\x14parent,firebase_link\x82\xd3\xe4\x93\x02<"+/v1beta/{parent=properties/*}/firebaseLinks:\rfirebase_link\x12\xa2\x01\n\x12DeleteFirebaseLink\x128.google.analytics.admin.v1beta.DeleteFirebaseLinkRequest\x1a\x16.google.protobuf.Empty":\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1beta/{name=properties/*/firebaseLinks/*}\x12\xc4\x01\n\x11ListFirebaseLinks\x127.google.analytics.admin.v1beta.ListFirebaseLinksRequest\x1a8.google.analytics.admin.v1beta.ListFirebaseLinksResponse"<\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1beta/{parent=properties/*}/firebaseLinks\x12\xde\x01\n\x13CreateGoogleAdsLink\x129.google.analytics.admin.v1beta.CreateGoogleAdsLinkRequest\x1a,.google.analytics.admin.v1beta.GoogleAdsLink"^\xdaA\x16parent,google_ads_link\x82\xd3\xe4\x93\x02?",/v1beta/{parent=properties/*}/googleAdsLinks:\x0fgoogle_ads_link\x12\xf3\x01\n\x13UpdateGoogleAdsLink\x129.google.analytics.admin.v1beta.UpdateGoogleAdsLinkRequest\x1a,.google.analytics.admin.v1beta.GoogleAdsLink"s\xdaA\x1bgoogle_ads_link,update_mask\x82\xd3\xe4\x93\x02O2</v1beta/{google_ads_link.name=properties/*/googleAdsLinks/*}:\x0fgoogle_ads_link\x12\xa5\x01\n\x13DeleteGoogleAdsLink\x129.google.analytics.admin.v1beta.DeleteGoogleAdsLinkRequest\x1a\x16.google.protobuf.Empty";\xdaA\x04name\x82\xd3\xe4\x93\x02.*,/v1beta/{name=properties/*/googleAdsLinks/*}\x12\xc8\x01\n\x12ListGoogleAdsLinks\x128.google.analytics.admin.v1beta.ListGoogleAdsLinksRequest\x1a9.google.analytics.admin.v1beta.ListGoogleAdsLinksResponse"=\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1beta/{parent=properties/*}/googleAdsLinks\x12\xc8\x01\n\x16GetDataSharingSettings\x12<.google.analytics.admin.v1beta.GetDataSharingSettingsRequest\x1a2.google.analytics.admin.v1beta.DataSharingSettings"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1beta/{name=accounts/*/dataSharingSettings}\x12\xf3\x01\n\x1cGetMeasurementProtocolSecret\x12B.google.analytics.admin.v1beta.GetMeasurementProtocolSecretRequest\x1a8.google.analytics.admin.v1beta.MeasurementProtocolSecret"U\xdaA\x04name\x82\xd3\xe4\x93\x02H\x12F/v1beta/{name=properties/*/dataStreams/*/measurementProtocolSecrets/*}\x12\x86\x02\n\x1eListMeasurementProtocolSecrets\x12D.google.analytics.admin.v1beta.ListMeasurementProtocolSecretsRequest\x1aE.google.analytics.admin.v1beta.ListMeasurementProtocolSecretsResponse"W\xdaA\x06parent\x82\xd3\xe4\x93\x02H\x12F/v1beta/{parent=properties/*/dataStreams/*}/measurementProtocolSecrets\x12\xb5\x02\n\x1fCreateMeasurementProtocolSecret\x12E.google.analytics.admin.v1beta.CreateMeasurementProtocolSecretRequest\x1a8.google.analytics.admin.v1beta.MeasurementProtocolSecret"\x90\x01\xdaA"parent,measurement_protocol_secret\x82\xd3\xe4\x93\x02e"F/v1beta/{parent=properties/*/dataStreams/*}/measurementProtocolSecrets:\x1bmeasurement_protocol_secret\x12\xd7\x01\n\x1fDeleteMeasurementProtocolSecret\x12E.google.analytics.admin.v1beta.DeleteMeasurementProtocolSecretRequest\x1a\x16.google.protobuf.Empty"U\xdaA\x04name\x82\xd3\xe4\x93\x02H*F/v1beta/{name=properties/*/dataStreams/*/measurementProtocolSecrets/*}\x12\xd7\x02\n\x1fUpdateMeasurementProtocolSecret\x12E.google.analytics.admin.v1beta.UpdateMeasurementProtocolSecretRequest\x1a8.google.analytics.admin.v1beta.MeasurementProtocolSecret"\xb2\x01\xdaA\'measurement_protocol_secret,update_mask\x82\xd3\xe4\x93\x02\x81\x012b/v1beta/{measurement_protocol_secret.name=properties/*/dataStreams/*/measurementProtocolSecrets/*}:\x1bmeasurement_protocol_secret\x12\xf4\x01\n\x1dAcknowledgeUserDataCollection\x12C.google.analytics.admin.v1beta.AcknowledgeUserDataCollectionRequest\x1aD.google.analytics.admin.v1beta.AcknowledgeUserDataCollectionResponse"H\x82\xd3\xe4\x93\x02B"=/v1beta/{property=properties/*}:acknowledgeUserDataCollection:\x01*\x12\xe1\x01\n\x19SearchChangeHistoryEvents\x12?.google.analytics.admin.v1beta.SearchChangeHistoryEventsRequest\x1a@.google.analytics.admin.v1beta.SearchChangeHistoryEventsResponse"A\x82\xd3\xe4\x93\x02;"6/v1beta/{account=accounts/*}:searchChangeHistoryEvents:\x01*\x12\xeb\x01\n\x15CreateConversionEvent\x12;.google.analytics.admin.v1beta.CreateConversionEventRequest\x1a..google.analytics.admin.v1beta.ConversionEvent"e\x88\x02\x01\xdaA\x17parent,conversion_event\x82\xd3\xe4\x93\x02B"./v1beta/{parent=properties/*}/conversionEvents:\x10conversion_event\x12\x81\x02\n\x15UpdateConversionEvent\x12;.google.analytics.admin.v1beta.UpdateConversionEventRequest\x1a..google.analytics.admin.v1beta.ConversionEvent"{\x88\x02\x01\xdaA\x1cconversion_event,update_mask\x82\xd3\xe4\x93\x02S2?/v1beta/{conversion_event.name=properties/*/conversionEvents/*}:\x10conversion_event\x12\xc0\x01\n\x12GetConversionEvent\x128.google.analytics.admin.v1beta.GetConversionEventRequest\x1a..google.analytics.admin.v1beta.ConversionEvent"@\x88\x02\x01\xdaA\x04name\x82\xd3\xe4\x93\x020\x12./v1beta/{name=properties/*/conversionEvents/*}\x12\xae\x01\n\x15DeleteConversionEvent\x12;.google.analytics.admin.v1beta.DeleteConversionEventRequest\x1a\x16.google.protobuf.Empty"@\x88\x02\x01\xdaA\x04name\x82\xd3\xe4\x93\x020*./v1beta/{name=properties/*/conversionEvents/*}\x12\xd3\x01\n\x14ListConversionEvents\x12:.google.analytics.admin.v1beta.ListConversionEventsRequest\x1a;.google.analytics.admin.v1beta.ListConversionEventsResponse"B\x88\x02\x01\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1beta/{parent=properties/*}/conversionEvents\x12\xbe\x01\n\x0eCreateKeyEvent\x124.google.analytics.admin.v1beta.CreateKeyEventRequest\x1a\'.google.analytics.admin.v1beta.KeyEvent"M\xdaA\x10parent,key_event\x82\xd3\xe4\x93\x024"\'/v1beta/{parent=properties/*}/keyEvents:\tkey_event\x12\xcd\x01\n\x0eUpdateKeyEvent\x124.google.analytics.admin.v1beta.UpdateKeyEventRequest\x1a\'.google.analytics.admin.v1beta.KeyEvent"\\\xdaA\x15key_event,update_mask\x82\xd3\xe4\x93\x02>21/v1beta/{key_event.name=properties/*/keyEvents/*}:\tkey_event\x12\xa1\x01\n\x0bGetKeyEvent\x121.google.analytics.admin.v1beta.GetKeyEventRequest\x1a\'.google.analytics.admin.v1beta.KeyEvent"6\xdaA\x04name\x82\xd3\xe4\x93\x02)\x12\'/v1beta/{name=properties/*/keyEvents/*}\x12\x96\x01\n\x0eDeleteKeyEvent\x124.google.analytics.admin.v1beta.DeleteKeyEventRequest\x1a\x16.google.protobuf.Empty"6\xdaA\x04name\x82\xd3\xe4\x93\x02)*\'/v1beta/{name=properties/*/keyEvents/*}\x12\xb4\x01\n\rListKeyEvents\x123.google.analytics.admin.v1beta.ListKeyEventsRequest\x1a4.google.analytics.admin.v1beta.ListKeyEventsResponse"8\xdaA\x06parent\x82\xd3\xe4\x93\x02)\x12\'/v1beta/{parent=properties/*}/keyEvents\x12\xe8\x01\n\x15CreateCustomDimension\x12;.google.analytics.admin.v1beta.CreateCustomDimensionRequest\x1a..google.analytics.admin.v1beta.CustomDimension"b\xdaA\x17parent,custom_dimension\x82\xd3\xe4\x93\x02B"./v1beta/{parent=properties/*}/customDimensions:\x10custom_dimension\x12\xfe\x01\n\x15UpdateCustomDimension\x12;.google.analytics.admin.v1beta.UpdateCustomDimensionRequest\x1a..google.analytics.admin.v1beta.CustomDimension"x\xdaA\x1ccustom_dimension,update_mask\x82\xd3\xe4\x93\x02S2?/v1beta/{custom_dimension.name=properties/*/customDimensions/*}:\x10custom_dimension\x12\xd0\x01\n\x14ListCustomDimensions\x12:.google.analytics.admin.v1beta.ListCustomDimensionsRequest\x1a;.google.analytics.admin.v1beta.ListCustomDimensionsResponse"?\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1beta/{parent=properties/*}/customDimensions\x12\xb8\x01\n\x16ArchiveCustomDimension\x12<.google.analytics.admin.v1beta.ArchiveCustomDimensionRequest\x1a\x16.google.protobuf.Empty"H\xdaA\x04name\x82\xd3\xe4\x93\x02;"6/v1beta/{name=properties/*/customDimensions/*}:archive:\x01*\x12\xbd\x01\n\x12GetCustomDimension\x128.google.analytics.admin.v1beta.GetCustomDimensionRequest\x1a..google.analytics.admin.v1beta.CustomDimension"=\xdaA\x04name\x82\xd3\xe4\x93\x020\x12./v1beta/{name=properties/*/customDimensions/*}\x12\xd6\x01\n\x12CreateCustomMetric\x128.google.analytics.admin.v1beta.CreateCustomMetricRequest\x1a+.google.analytics.admin.v1beta.CustomMetric"Y\xdaA\x14parent,custom_metric\x82\xd3\xe4\x93\x02<"+/v1beta/{parent=properties/*}/customMetrics:\rcustom_metric\x12\xe9\x01\n\x12UpdateCustomMetric\x128.google.analytics.admin.v1beta.UpdateCustomMetricRequest\x1a+.google.analytics.admin.v1beta.CustomMetric"l\xdaA\x19custom_metric,update_mask\x82\xd3\xe4\x93\x02J29/v1beta/{custom_metric.name=properties/*/customMetrics/*}:\rcustom_metric\x12\xc4\x01\n\x11ListCustomMetrics\x127.google.analytics.admin.v1beta.ListCustomMetricsRequest\x1a8.google.analytics.admin.v1beta.ListCustomMetricsResponse"<\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1beta/{parent=properties/*}/customMetrics\x12\xaf\x01\n\x13ArchiveCustomMetric\x129.google.analytics.admin.v1beta.ArchiveCustomMetricRequest\x1a\x16.google.protobuf.Empty"E\xdaA\x04name\x82\xd3\xe4\x93\x028"3/v1beta/{name=properties/*/customMetrics/*}:archive:\x01*\x12\xb1\x01\n\x0fGetCustomMetric\x125.google.analytics.admin.v1beta.GetCustomMetricRequest\x1a+.google.analytics.admin.v1beta.CustomMetric":\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1beta/{name=properties/*/customMetrics/*}\x12\xd2\x01\n\x18GetDataRetentionSettings\x12>.google.analytics.admin.v1beta.GetDataRetentionSettingsRequest\x1a4.google.analytics.admin.v1beta.DataRetentionSettings"@\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1beta/{name=properties/*/dataRetentionSettings}\x12\xa9\x02\n\x1bUpdateDataRetentionSettings\x12A.google.analytics.admin.v1beta.UpdateDataRetentionSettingsRequest\x1a4.google.analytics.admin.v1beta.DataRetentionSettings"\x90\x01\xdaA#data_retention_settings,update_mask\x82\xd3\xe4\x93\x02d2I/v1beta/{data_retention_settings.name=properties/*/dataRetentionSettings}:\x17data_retention_settings\x12\xca\x01\n\x10CreateDataStream\x126.google.analytics.admin.v1beta.CreateDataStreamRequest\x1a).google.analytics.admin.v1beta.DataStream"S\xdaA\x12parent,data_stream\x82\xd3\xe4\x93\x028")/v1beta/{parent=properties/*}/dataStreams:\x0bdata_stream\x12\x9c\x01\n\x10DeleteDataStream\x126.google.analytics.admin.v1beta.DeleteDataStreamRequest\x1a\x16.google.protobuf.Empty"8\xdaA\x04name\x82\xd3\xe4\x93\x02+*)/v1beta/{name=properties/*/dataStreams/*}\x12\xdb\x01\n\x10UpdateDataStream\x126.google.analytics.admin.v1beta.UpdateDataStreamRequest\x1a).google.analytics.admin.v1beta.DataStream"d\xdaA\x17data_stream,update_mask\x82\xd3\xe4\x93\x02D25/v1beta/{data_stream.name=properties/*/dataStreams/*}:\x0bdata_stream\x12\xbc\x01\n\x0fListDataStreams\x125.google.analytics.admin.v1beta.ListDataStreamsRequest\x1a6.google.analytics.admin.v1beta.ListDataStreamsResponse":\xdaA\x06parent\x82\xd3\xe4\x93\x02+\x12)/v1beta/{parent=properties/*}/dataStreams\x12\xa9\x01\n\rGetDataStream\x123.google.analytics.admin.v1beta.GetDataStreamRequest\x1a).google.analytics.admin.v1beta.DataStream"8\xdaA\x04name\x82\xd3\xe4\x93\x02+\x12)/v1beta/{name=properties/*/dataStreams/*}\x12\xec\x01\n\x0fRunAccessReport\x125.google.analytics.admin.v1beta.RunAccessReportRequest\x1a6.google.analytics.admin.v1beta.RunAccessReportResponse"j\x82\xd3\xe4\x93\x02d"-/v1beta/{entity=properties/*}:runAccessReport:\x01*Z0"+/v1beta/{entity=accounts/*}:runAccessReport:\x01*\x1a\x84\x01\xcaA\x1danalyticsadmin.googleapis.com\xd2Aahttps://www.googleapis.com/auth/analytics.edit,https://www.googleapis.com/auth/analytics.readonlyBy\n!com.google.analytics.admin.v1betaB\x13AnalyticsAdminProtoP\x01Z=cloud.google.com/go/analytics/admin/apiv1beta/adminpb;adminpbb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.analytics.admin.v1beta.analytics_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n!com.google.analytics.admin.v1betaB\x13AnalyticsAdminProtoP\x01Z=cloud.google.com/go/analytics/admin/apiv1beta/adminpb;adminpb'
    _globals['_RUNACCESSREPORTREQUEST'].fields_by_name['include_all_users']._loaded_options = None
    _globals['_RUNACCESSREPORTREQUEST'].fields_by_name['include_all_users']._serialized_options = b'\xe0A\x01'
    _globals['_RUNACCESSREPORTREQUEST'].fields_by_name['expand_groups']._loaded_options = None
    _globals['_RUNACCESSREPORTREQUEST'].fields_by_name['expand_groups']._serialized_options = b'\xe0A\x01'
    _globals['_GETACCOUNTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETACCOUNTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%analyticsadmin.googleapis.com/Account"
    _globals['_DELETEACCOUNTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEACCOUNTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%analyticsadmin.googleapis.com/Account"
    _globals['_UPDATEACCOUNTREQUEST'].fields_by_name['account']._loaded_options = None
    _globals['_UPDATEACCOUNTREQUEST'].fields_by_name['account']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEACCOUNTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEACCOUNTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_GETPROPERTYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPROPERTYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/Property'
    _globals['_LISTPROPERTIESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTPROPERTIESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEPROPERTYREQUEST'].fields_by_name['property']._loaded_options = None
    _globals['_UPDATEPROPERTYREQUEST'].fields_by_name['property']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEPROPERTYREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEPROPERTYREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEPROPERTYREQUEST'].fields_by_name['property']._loaded_options = None
    _globals['_CREATEPROPERTYREQUEST'].fields_by_name['property']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEPROPERTYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEPROPERTYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/Property'
    _globals['_CREATEFIREBASELINKREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEFIREBASELINKREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/FirebaseLink'
    _globals['_CREATEFIREBASELINKREQUEST'].fields_by_name['firebase_link']._loaded_options = None
    _globals['_CREATEFIREBASELINKREQUEST'].fields_by_name['firebase_link']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEFIREBASELINKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEFIREBASELINKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*analyticsadmin.googleapis.com/FirebaseLink'
    _globals['_LISTFIREBASELINKSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTFIREBASELINKSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/FirebaseLink'
    _globals['_CREATEGOOGLEADSLINKREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEGOOGLEADSLINKREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+analyticsadmin.googleapis.com/GoogleAdsLink'
    _globals['_CREATEGOOGLEADSLINKREQUEST'].fields_by_name['google_ads_link']._loaded_options = None
    _globals['_CREATEGOOGLEADSLINKREQUEST'].fields_by_name['google_ads_link']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEGOOGLEADSLINKREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEGOOGLEADSLINKREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEGOOGLEADSLINKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEGOOGLEADSLINKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+analyticsadmin.googleapis.com/GoogleAdsLink'
    _globals['_LISTGOOGLEADSLINKSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTGOOGLEADSLINKSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+analyticsadmin.googleapis.com/GoogleAdsLink'
    _globals['_GETDATASHARINGSETTINGSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETDATASHARINGSETTINGSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA3\n1analyticsadmin.googleapis.com/DataSharingSettings'
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONREQUEST'].fields_by_name['property']._loaded_options = None
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONREQUEST'].fields_by_name['property']._serialized_options = b'\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/Property'
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONREQUEST'].fields_by_name['acknowledgement']._loaded_options = None
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONREQUEST'].fields_by_name['acknowledgement']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['account']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['account']._serialized_options = b"\xe0A\x02\xfaA'\n%analyticsadmin.googleapis.com/Account"
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['property']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['property']._serialized_options = b'\xe0A\x01\xfaA(\n&analyticsadmin.googleapis.com/Property'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['resource_type']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['resource_type']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['action']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['action']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['actor_email']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['actor_email']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['earliest_change_time']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['earliest_change_time']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['latest_change_time']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['latest_change_time']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_GETMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA9\n7analyticsadmin.googleapis.com/MeasurementProtocolSecret'
    _globals['_CREATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA9\x127analyticsadmin.googleapis.com/MeasurementProtocolSecret'
    _globals['_CREATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['measurement_protocol_secret']._loaded_options = None
    _globals['_CREATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['measurement_protocol_secret']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA9\n7analyticsadmin.googleapis.com/MeasurementProtocolSecret'
    _globals['_UPDATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['measurement_protocol_secret']._loaded_options = None
    _globals['_UPDATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['measurement_protocol_secret']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEMEASUREMENTPROTOCOLSECRETREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_LISTMEASUREMENTPROTOCOLSECRETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTMEASUREMENTPROTOCOLSECRETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA9\x127analyticsadmin.googleapis.com/MeasurementProtocolSecret'
    _globals['_CREATECONVERSIONEVENTREQUEST'].fields_by_name['conversion_event']._loaded_options = None
    _globals['_CREATECONVERSIONEVENTREQUEST'].fields_by_name['conversion_event']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECONVERSIONEVENTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECONVERSIONEVENTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/ConversionEvent'
    _globals['_UPDATECONVERSIONEVENTREQUEST'].fields_by_name['conversion_event']._loaded_options = None
    _globals['_UPDATECONVERSIONEVENTREQUEST'].fields_by_name['conversion_event']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECONVERSIONEVENTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECONVERSIONEVENTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_GETCONVERSIONEVENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCONVERSIONEVENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/ConversionEvent'
    _globals['_DELETECONVERSIONEVENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECONVERSIONEVENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/ConversionEvent'
    _globals['_LISTCONVERSIONEVENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCONVERSIONEVENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/ConversionEvent'
    _globals['_CREATEKEYEVENTREQUEST'].fields_by_name['key_event']._loaded_options = None
    _globals['_CREATEKEYEVENTREQUEST'].fields_by_name['key_event']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEKEYEVENTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEKEYEVENTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\x12&analyticsadmin.googleapis.com/KeyEvent'
    _globals['_UPDATEKEYEVENTREQUEST'].fields_by_name['key_event']._loaded_options = None
    _globals['_UPDATEKEYEVENTREQUEST'].fields_by_name['key_event']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEKEYEVENTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEKEYEVENTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_GETKEYEVENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETKEYEVENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/KeyEvent'
    _globals['_DELETEKEYEVENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEKEYEVENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&analyticsadmin.googleapis.com/KeyEvent'
    _globals['_LISTKEYEVENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTKEYEVENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\x12&analyticsadmin.googleapis.com/KeyEvent'
    _globals['_CREATECUSTOMDIMENSIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECUSTOMDIMENSIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/CustomDimension'
    _globals['_CREATECUSTOMDIMENSIONREQUEST'].fields_by_name['custom_dimension']._loaded_options = None
    _globals['_CREATECUSTOMDIMENSIONREQUEST'].fields_by_name['custom_dimension']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECUSTOMDIMENSIONREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECUSTOMDIMENSIONREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_LISTCUSTOMDIMENSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCUSTOMDIMENSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-analyticsadmin.googleapis.com/CustomDimension'
    _globals['_ARCHIVECUSTOMDIMENSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ARCHIVECUSTOMDIMENSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/CustomDimension'
    _globals['_GETCUSTOMDIMENSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCUSTOMDIMENSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-analyticsadmin.googleapis.com/CustomDimension'
    _globals['_CREATECUSTOMMETRICREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECUSTOMMETRICREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/CustomMetric'
    _globals['_CREATECUSTOMMETRICREQUEST'].fields_by_name['custom_metric']._loaded_options = None
    _globals['_CREATECUSTOMMETRICREQUEST'].fields_by_name['custom_metric']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECUSTOMMETRICREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECUSTOMMETRICREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_LISTCUSTOMMETRICSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCUSTOMMETRICSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\x12*analyticsadmin.googleapis.com/CustomMetric'
    _globals['_ARCHIVECUSTOMMETRICREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ARCHIVECUSTOMMETRICREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*analyticsadmin.googleapis.com/CustomMetric'
    _globals['_GETCUSTOMMETRICREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCUSTOMMETRICREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*analyticsadmin.googleapis.com/CustomMetric'
    _globals['_GETDATARETENTIONSETTINGSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETDATARETENTIONSETTINGSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA5\n3analyticsadmin.googleapis.com/DataRetentionSettings'
    _globals['_UPDATEDATARETENTIONSETTINGSREQUEST'].fields_by_name['data_retention_settings']._loaded_options = None
    _globals['_UPDATEDATARETENTIONSETTINGSREQUEST'].fields_by_name['data_retention_settings']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEDATARETENTIONSETTINGSREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEDATARETENTIONSETTINGSREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEDATASTREAMREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEDATASTREAMREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA*\x12(analyticsadmin.googleapis.com/DataStream'
    _globals['_CREATEDATASTREAMREQUEST'].fields_by_name['data_stream']._loaded_options = None
    _globals['_CREATEDATASTREAMREQUEST'].fields_by_name['data_stream']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEDATASTREAMREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEDATASTREAMREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(analyticsadmin.googleapis.com/DataStream'
    _globals['_UPDATEDATASTREAMREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEDATASTREAMREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_LISTDATASTREAMSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTDATASTREAMSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA*\x12(analyticsadmin.googleapis.com/DataStream'
    _globals['_GETDATASTREAMREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETDATASTREAMREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(analyticsadmin.googleapis.com/DataStream'
    _globals['_ANALYTICSADMINSERVICE']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE']._serialized_options = b'\xcaA\x1danalyticsadmin.googleapis.com\xd2Aahttps://www.googleapis.com/auth/analytics.edit,https://www.googleapis.com/auth/analytics.readonly'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetAccount']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetAccount']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1beta/{name=accounts/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListAccounts']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListAccounts']._serialized_options = b'\x82\xd3\xe4\x93\x02\x12\x12\x10/v1beta/accounts'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteAccount']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteAccount']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1b*\x19/v1beta/{name=accounts/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateAccount']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateAccount']._serialized_options = b'\xdaA\x13account,update_mask\x82\xd3\xe4\x93\x02,2!/v1beta/{account.name=accounts/*}:\x07account'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ProvisionAccountTicket']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ProvisionAccountTicket']._serialized_options = b'\x82\xd3\xe4\x93\x02,"\'/v1beta/accounts:provisionAccountTicket:\x01*'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListAccountSummaries']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListAccountSummaries']._serialized_options = b'\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1beta/accountSummaries'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetProperty']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetProperty']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1beta/{name=properties/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListProperties']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListProperties']._serialized_options = b'\x82\xd3\xe4\x93\x02\x14\x12\x12/v1beta/properties'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateProperty']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateProperty']._serialized_options = b'\xdaA\x08property\x82\xd3\xe4\x93\x02\x1e"\x12/v1beta/properties:\x08property'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteProperty']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteProperty']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1d*\x1b/v1beta/{name=properties/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateProperty']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateProperty']._serialized_options = b'\xdaA\x14property,update_mask\x82\xd3\xe4\x93\x0202$/v1beta/{property.name=properties/*}:\x08property'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateFirebaseLink']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateFirebaseLink']._serialized_options = b'\xdaA\x14parent,firebase_link\x82\xd3\xe4\x93\x02<"+/v1beta/{parent=properties/*}/firebaseLinks:\rfirebase_link'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteFirebaseLink']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteFirebaseLink']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1beta/{name=properties/*/firebaseLinks/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListFirebaseLinks']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListFirebaseLinks']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1beta/{parent=properties/*}/firebaseLinks'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateGoogleAdsLink']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateGoogleAdsLink']._serialized_options = b'\xdaA\x16parent,google_ads_link\x82\xd3\xe4\x93\x02?",/v1beta/{parent=properties/*}/googleAdsLinks:\x0fgoogle_ads_link'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateGoogleAdsLink']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateGoogleAdsLink']._serialized_options = b'\xdaA\x1bgoogle_ads_link,update_mask\x82\xd3\xe4\x93\x02O2</v1beta/{google_ads_link.name=properties/*/googleAdsLinks/*}:\x0fgoogle_ads_link'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteGoogleAdsLink']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteGoogleAdsLink']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02.*,/v1beta/{name=properties/*/googleAdsLinks/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListGoogleAdsLinks']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListGoogleAdsLinks']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v1beta/{parent=properties/*}/googleAdsLinks'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetDataSharingSettings']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetDataSharingSettings']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1beta/{name=accounts/*/dataSharingSettings}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetMeasurementProtocolSecret']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetMeasurementProtocolSecret']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02H\x12F/v1beta/{name=properties/*/dataStreams/*/measurementProtocolSecrets/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListMeasurementProtocolSecrets']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListMeasurementProtocolSecrets']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02H\x12F/v1beta/{parent=properties/*/dataStreams/*}/measurementProtocolSecrets'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateMeasurementProtocolSecret']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateMeasurementProtocolSecret']._serialized_options = b'\xdaA"parent,measurement_protocol_secret\x82\xd3\xe4\x93\x02e"F/v1beta/{parent=properties/*/dataStreams/*}/measurementProtocolSecrets:\x1bmeasurement_protocol_secret'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteMeasurementProtocolSecret']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteMeasurementProtocolSecret']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02H*F/v1beta/{name=properties/*/dataStreams/*/measurementProtocolSecrets/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateMeasurementProtocolSecret']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateMeasurementProtocolSecret']._serialized_options = b"\xdaA'measurement_protocol_secret,update_mask\x82\xd3\xe4\x93\x02\x81\x012b/v1beta/{measurement_protocol_secret.name=properties/*/dataStreams/*/measurementProtocolSecrets/*}:\x1bmeasurement_protocol_secret"
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['AcknowledgeUserDataCollection']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['AcknowledgeUserDataCollection']._serialized_options = b'\x82\xd3\xe4\x93\x02B"=/v1beta/{property=properties/*}:acknowledgeUserDataCollection:\x01*'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['SearchChangeHistoryEvents']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['SearchChangeHistoryEvents']._serialized_options = b'\x82\xd3\xe4\x93\x02;"6/v1beta/{account=accounts/*}:searchChangeHistoryEvents:\x01*'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateConversionEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateConversionEvent']._serialized_options = b'\x88\x02\x01\xdaA\x17parent,conversion_event\x82\xd3\xe4\x93\x02B"./v1beta/{parent=properties/*}/conversionEvents:\x10conversion_event'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateConversionEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateConversionEvent']._serialized_options = b'\x88\x02\x01\xdaA\x1cconversion_event,update_mask\x82\xd3\xe4\x93\x02S2?/v1beta/{conversion_event.name=properties/*/conversionEvents/*}:\x10conversion_event'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetConversionEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetConversionEvent']._serialized_options = b'\x88\x02\x01\xdaA\x04name\x82\xd3\xe4\x93\x020\x12./v1beta/{name=properties/*/conversionEvents/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteConversionEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteConversionEvent']._serialized_options = b'\x88\x02\x01\xdaA\x04name\x82\xd3\xe4\x93\x020*./v1beta/{name=properties/*/conversionEvents/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListConversionEvents']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListConversionEvents']._serialized_options = b'\x88\x02\x01\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1beta/{parent=properties/*}/conversionEvents'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateKeyEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateKeyEvent']._serialized_options = b'\xdaA\x10parent,key_event\x82\xd3\xe4\x93\x024"\'/v1beta/{parent=properties/*}/keyEvents:\tkey_event'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateKeyEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateKeyEvent']._serialized_options = b'\xdaA\x15key_event,update_mask\x82\xd3\xe4\x93\x02>21/v1beta/{key_event.name=properties/*/keyEvents/*}:\tkey_event'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetKeyEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetKeyEvent']._serialized_options = b"\xdaA\x04name\x82\xd3\xe4\x93\x02)\x12'/v1beta/{name=properties/*/keyEvents/*}"
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteKeyEvent']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteKeyEvent']._serialized_options = b"\xdaA\x04name\x82\xd3\xe4\x93\x02)*'/v1beta/{name=properties/*/keyEvents/*}"
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListKeyEvents']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListKeyEvents']._serialized_options = b"\xdaA\x06parent\x82\xd3\xe4\x93\x02)\x12'/v1beta/{parent=properties/*}/keyEvents"
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateCustomDimension']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateCustomDimension']._serialized_options = b'\xdaA\x17parent,custom_dimension\x82\xd3\xe4\x93\x02B"./v1beta/{parent=properties/*}/customDimensions:\x10custom_dimension'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateCustomDimension']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateCustomDimension']._serialized_options = b'\xdaA\x1ccustom_dimension,update_mask\x82\xd3\xe4\x93\x02S2?/v1beta/{custom_dimension.name=properties/*/customDimensions/*}:\x10custom_dimension'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListCustomDimensions']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListCustomDimensions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x020\x12./v1beta/{parent=properties/*}/customDimensions'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ArchiveCustomDimension']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ArchiveCustomDimension']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;"6/v1beta/{name=properties/*/customDimensions/*}:archive:\x01*'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetCustomDimension']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetCustomDimension']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x020\x12./v1beta/{name=properties/*/customDimensions/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateCustomMetric']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateCustomMetric']._serialized_options = b'\xdaA\x14parent,custom_metric\x82\xd3\xe4\x93\x02<"+/v1beta/{parent=properties/*}/customMetrics:\rcustom_metric'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateCustomMetric']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateCustomMetric']._serialized_options = b'\xdaA\x19custom_metric,update_mask\x82\xd3\xe4\x93\x02J29/v1beta/{custom_metric.name=properties/*/customMetrics/*}:\rcustom_metric'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListCustomMetrics']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListCustomMetrics']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1beta/{parent=properties/*}/customMetrics'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ArchiveCustomMetric']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ArchiveCustomMetric']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028"3/v1beta/{name=properties/*/customMetrics/*}:archive:\x01*'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetCustomMetric']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetCustomMetric']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1beta/{name=properties/*/customMetrics/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetDataRetentionSettings']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetDataRetentionSettings']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1beta/{name=properties/*/dataRetentionSettings}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateDataRetentionSettings']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateDataRetentionSettings']._serialized_options = b'\xdaA#data_retention_settings,update_mask\x82\xd3\xe4\x93\x02d2I/v1beta/{data_retention_settings.name=properties/*/dataRetentionSettings}:\x17data_retention_settings'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateDataStream']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['CreateDataStream']._serialized_options = b'\xdaA\x12parent,data_stream\x82\xd3\xe4\x93\x028")/v1beta/{parent=properties/*}/dataStreams:\x0bdata_stream'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteDataStream']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['DeleteDataStream']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02+*)/v1beta/{name=properties/*/dataStreams/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateDataStream']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['UpdateDataStream']._serialized_options = b'\xdaA\x17data_stream,update_mask\x82\xd3\xe4\x93\x02D25/v1beta/{data_stream.name=properties/*/dataStreams/*}:\x0bdata_stream'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListDataStreams']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['ListDataStreams']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02+\x12)/v1beta/{parent=properties/*}/dataStreams'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetDataStream']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['GetDataStream']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02+\x12)/v1beta/{name=properties/*/dataStreams/*}'
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['RunAccessReport']._loaded_options = None
    _globals['_ANALYTICSADMINSERVICE'].methods_by_name['RunAccessReport']._serialized_options = b'\x82\xd3\xe4\x93\x02d"-/v1beta/{entity=properties/*}:runAccessReport:\x01*Z0"+/v1beta/{entity=accounts/*}:runAccessReport:\x01*'
    _globals['_RUNACCESSREPORTREQUEST']._serialized_start = 396
    _globals['_RUNACCESSREPORTREQUEST']._serialized_end = 998
    _globals['_RUNACCESSREPORTRESPONSE']._serialized_start = 1001
    _globals['_RUNACCESSREPORTRESPONSE']._serialized_end = 1316
    _globals['_GETACCOUNTREQUEST']._serialized_start = 1318
    _globals['_GETACCOUNTREQUEST']._serialized_end = 1398
    _globals['_LISTACCOUNTSREQUEST']._serialized_start = 1400
    _globals['_LISTACCOUNTSREQUEST']._serialized_end = 1482
    _globals['_LISTACCOUNTSRESPONSE']._serialized_start = 1484
    _globals['_LISTACCOUNTSRESPONSE']._serialized_end = 1589
    _globals['_DELETEACCOUNTREQUEST']._serialized_start = 1591
    _globals['_DELETEACCOUNTREQUEST']._serialized_end = 1674
    _globals['_UPDATEACCOUNTREQUEST']._serialized_start = 1677
    _globals['_UPDATEACCOUNTREQUEST']._serialized_end = 1815
    _globals['_PROVISIONACCOUNTTICKETREQUEST']._serialized_start = 1817
    _globals['_PROVISIONACCOUNTTICKETREQUEST']._serialized_end = 1927
    _globals['_PROVISIONACCOUNTTICKETRESPONSE']._serialized_start = 1929
    _globals['_PROVISIONACCOUNTTICKETRESPONSE']._serialized_end = 1988
    _globals['_GETPROPERTYREQUEST']._serialized_start = 1990
    _globals['_GETPROPERTYREQUEST']._serialized_end = 2072
    _globals['_LISTPROPERTIESREQUEST']._serialized_start = 2074
    _globals['_LISTPROPERTIESREQUEST']._serialized_end = 2179
    _globals['_LISTPROPERTIESRESPONSE']._serialized_start = 2181
    _globals['_LISTPROPERTIESRESPONSE']._serialized_end = 2291
    _globals['_UPDATEPROPERTYREQUEST']._serialized_start = 2294
    _globals['_UPDATEPROPERTYREQUEST']._serialized_end = 2435
    _globals['_CREATEPROPERTYREQUEST']._serialized_start = 2437
    _globals['_CREATEPROPERTYREQUEST']._serialized_end = 2524
    _globals['_DELETEPROPERTYREQUEST']._serialized_start = 2526
    _globals['_DELETEPROPERTYREQUEST']._serialized_end = 2611
    _globals['_CREATEFIREBASELINKREQUEST']._serialized_start = 2614
    _globals['_CREATEFIREBASELINKREQUEST']._serialized_end = 2782
    _globals['_DELETEFIREBASELINKREQUEST']._serialized_start = 2784
    _globals['_DELETEFIREBASELINKREQUEST']._serialized_end = 2877
    _globals['_LISTFIREBASELINKSREQUEST']._serialized_start = 2880
    _globals['_LISTFIREBASELINKSREQUEST']._serialized_end = 3013
    _globals['_LISTFIREBASELINKSRESPONSE']._serialized_start = 3015
    _globals['_LISTFIREBASELINKSRESPONSE']._serialized_end = 3136
    _globals['_CREATEGOOGLEADSLINKREQUEST']._serialized_start = 3139
    _globals['_CREATEGOOGLEADSLINKREQUEST']._serialized_end = 3312
    _globals['_UPDATEGOOGLEADSLINKREQUEST']._serialized_start = 3315
    _globals['_UPDATEGOOGLEADSLINKREQUEST']._serialized_end = 3468
    _globals['_DELETEGOOGLEADSLINKREQUEST']._serialized_start = 3470
    _globals['_DELETEGOOGLEADSLINKREQUEST']._serialized_end = 3565
    _globals['_LISTGOOGLEADSLINKSREQUEST']._serialized_start = 3568
    _globals['_LISTGOOGLEADSLINKSREQUEST']._serialized_end = 3703
    _globals['_LISTGOOGLEADSLINKSRESPONSE']._serialized_start = 3705
    _globals['_LISTGOOGLEADSLINKSRESPONSE']._serialized_end = 3830
    _globals['_GETDATASHARINGSETTINGSREQUEST']._serialized_start = 3832
    _globals['_GETDATASHARINGSETTINGSREQUEST']._serialized_end = 3936
    _globals['_LISTACCOUNTSUMMARIESREQUEST']._serialized_start = 3938
    _globals['_LISTACCOUNTSUMMARIESREQUEST']._serialized_end = 4006
    _globals['_LISTACCOUNTSUMMARIESRESPONSE']._serialized_start = 4009
    _globals['_LISTACCOUNTSUMMARIESRESPONSE']._serialized_end = 4138
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONREQUEST']._serialized_start = 4141
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONREQUEST']._serialized_end = 4275
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONRESPONSE']._serialized_start = 4277
    _globals['_ACKNOWLEDGEUSERDATACOLLECTIONRESPONSE']._serialized_end = 4316
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST']._serialized_start = 4319
    _globals['_SEARCHCHANGEHISTORYEVENTSREQUEST']._serialized_end = 4832
    _globals['_SEARCHCHANGEHISTORYEVENTSRESPONSE']._serialized_start = 4835
    _globals['_SEARCHCHANGEHISTORYEVENTSRESPONSE']._serialized_end = 4977
    _globals['_GETMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_start = 4979
    _globals['_GETMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_end = 5095
    _globals['_CREATEMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_start = 5098
    _globals['_CREATEMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_end = 5319
    _globals['_DELETEMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_start = 5321
    _globals['_DELETEMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_end = 5440
    _globals['_UPDATEMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_start = 5443
    _globals['_UPDATEMEASUREMENTPROTOCOLSECRETREQUEST']._serialized_end = 5637
    _globals['_LISTMEASUREMENTPROTOCOLSECRETSREQUEST']._serialized_start = 5640
    _globals['_LISTMEASUREMENTPROTOCOLSECRETSREQUEST']._serialized_end = 5799
    _globals['_LISTMEASUREMENTPROTOCOLSECRETSRESPONSE']._serialized_start = 5802
    _globals['_LISTMEASUREMENTPROTOCOLSECRETSRESPONSE']._serialized_end = 5963
    _globals['_CREATECONVERSIONEVENTREQUEST']._serialized_start = 5966
    _globals['_CREATECONVERSIONEVENTREQUEST']._serialized_end = 6146
    _globals['_UPDATECONVERSIONEVENTREQUEST']._serialized_start = 6149
    _globals['_UPDATECONVERSIONEVENTREQUEST']._serialized_end = 6312
    _globals['_GETCONVERSIONEVENTREQUEST']._serialized_start = 6314
    _globals['_GETCONVERSIONEVENTREQUEST']._serialized_end = 6410
    _globals['_DELETECONVERSIONEVENTREQUEST']._serialized_start = 6412
    _globals['_DELETECONVERSIONEVENTREQUEST']._serialized_end = 6511
    _globals['_LISTCONVERSIONEVENTSREQUEST']._serialized_start = 6514
    _globals['_LISTCONVERSIONEVENTSREQUEST']._serialized_end = 6653
    _globals['_LISTCONVERSIONEVENTSRESPONSE']._serialized_start = 6656
    _globals['_LISTCONVERSIONEVENTSRESPONSE']._serialized_end = 6786
    _globals['_CREATEKEYEVENTREQUEST']._serialized_start = 6789
    _globals['_CREATEKEYEVENTREQUEST']._serialized_end = 6941
    _globals['_UPDATEKEYEVENTREQUEST']._serialized_start = 6944
    _globals['_UPDATEKEYEVENTREQUEST']._serialized_end = 7086
    _globals['_GETKEYEVENTREQUEST']._serialized_start = 7088
    _globals['_GETKEYEVENTREQUEST']._serialized_end = 7170
    _globals['_DELETEKEYEVENTREQUEST']._serialized_start = 7172
    _globals['_DELETEKEYEVENTREQUEST']._serialized_end = 7257
    _globals['_LISTKEYEVENTSREQUEST']._serialized_start = 7259
    _globals['_LISTKEYEVENTSREQUEST']._serialized_end = 7384
    _globals['_LISTKEYEVENTSRESPONSE']._serialized_start = 7386
    _globals['_LISTKEYEVENTSRESPONSE']._serialized_end = 7495
    _globals['_CREATECUSTOMDIMENSIONREQUEST']._serialized_start = 7498
    _globals['_CREATECUSTOMDIMENSIONREQUEST']._serialized_end = 7678
    _globals['_UPDATECUSTOMDIMENSIONREQUEST']._serialized_start = 7681
    _globals['_UPDATECUSTOMDIMENSIONREQUEST']._serialized_end = 7839
    _globals['_LISTCUSTOMDIMENSIONSREQUEST']._serialized_start = 7842
    _globals['_LISTCUSTOMDIMENSIONSREQUEST']._serialized_end = 7981
    _globals['_LISTCUSTOMDIMENSIONSRESPONSE']._serialized_start = 7984
    _globals['_LISTCUSTOMDIMENSIONSRESPONSE']._serialized_end = 8114
    _globals['_ARCHIVECUSTOMDIMENSIONREQUEST']._serialized_start = 8116
    _globals['_ARCHIVECUSTOMDIMENSIONREQUEST']._serialized_end = 8216
    _globals['_GETCUSTOMDIMENSIONREQUEST']._serialized_start = 8218
    _globals['_GETCUSTOMDIMENSIONREQUEST']._serialized_end = 8314
    _globals['_CREATECUSTOMMETRICREQUEST']._serialized_start = 8317
    _globals['_CREATECUSTOMMETRICREQUEST']._serialized_end = 8485
    _globals['_UPDATECUSTOMMETRICREQUEST']._serialized_start = 8488
    _globals['_UPDATECUSTOMMETRICREQUEST']._serialized_end = 8637
    _globals['_LISTCUSTOMMETRICSREQUEST']._serialized_start = 8640
    _globals['_LISTCUSTOMMETRICSREQUEST']._serialized_end = 8773
    _globals['_LISTCUSTOMMETRICSRESPONSE']._serialized_start = 8775
    _globals['_LISTCUSTOMMETRICSRESPONSE']._serialized_end = 8896
    _globals['_ARCHIVECUSTOMMETRICREQUEST']._serialized_start = 8898
    _globals['_ARCHIVECUSTOMMETRICREQUEST']._serialized_end = 8992
    _globals['_GETCUSTOMMETRICREQUEST']._serialized_start = 8994
    _globals['_GETCUSTOMMETRICREQUEST']._serialized_end = 9084
    _globals['_GETDATARETENTIONSETTINGSREQUEST']._serialized_start = 9086
    _globals['_GETDATARETENTIONSETTINGSREQUEST']._serialized_end = 9194
    _globals['_UPDATEDATARETENTIONSETTINGSREQUEST']._serialized_start = 9197
    _globals['_UPDATEDATARETENTIONSETTINGSREQUEST']._serialized_end = 9379
    _globals['_CREATEDATASTREAMREQUEST']._serialized_start = 9382
    _globals['_CREATEDATASTREAMREQUEST']._serialized_end = 9542
    _globals['_DELETEDATASTREAMREQUEST']._serialized_start = 9544
    _globals['_DELETEDATASTREAMREQUEST']._serialized_end = 9633
    _globals['_UPDATEDATASTREAMREQUEST']._serialized_start = 9636
    _globals['_UPDATEDATASTREAMREQUEST']._serialized_end = 9779
    _globals['_LISTDATASTREAMSREQUEST']._serialized_start = 9782
    _globals['_LISTDATASTREAMSREQUEST']._serialized_end = 9911
    _globals['_LISTDATASTREAMSRESPONSE']._serialized_start = 9913
    _globals['_LISTDATASTREAMSRESPONSE']._serialized_end = 10028
    _globals['_GETDATASTREAMREQUEST']._serialized_start = 10030
    _globals['_GETDATASTREAMREQUEST']._serialized_end = 10116
    _globals['_ANALYTICSADMINSERVICE']._serialized_start = 10119
    _globals['_ANALYTICSADMINSERVICE']._serialized_end = 21366