"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/bigtable/admin/v2/bigtable_instance_admin.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.bigtable.admin.v2 import instance_pb2 as google_dot_bigtable_dot_admin_dot_v2_dot_instance__pb2
from .....google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from .....google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6google/bigtable/admin/v2/bigtable_instance_admin.proto\x12\x18google.bigtable.admin.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\'google/bigtable/admin/v2/instance.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xdb\x02\n\x15CreateInstanceRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12\x18\n\x0binstance_id\x18\x02 \x01(\tB\x03\xe0A\x02\x129\n\x08instance\x18\x03 \x01(\x0b2".google.bigtable.admin.v2.InstanceB\x03\xe0A\x02\x12T\n\x08clusters\x18\x04 \x03(\x0b2=.google.bigtable.admin.v2.CreateInstanceRequest.ClustersEntryB\x03\xe0A\x02\x1aR\n\rClustersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x120\n\x05value\x18\x02 \x01(\x0b2!.google.bigtable.admin.v2.Cluster:\x028\x01"Q\n\x12GetInstanceRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance"o\n\x14ListInstancesRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project\x12\x12\n\npage_token\x18\x02 \x01(\t"\x81\x01\n\x15ListInstancesResponse\x125\n\tinstances\x18\x01 \x03(\x0b2".google.bigtable.admin.v2.Instance\x12\x18\n\x10failed_locations\x18\x02 \x03(\t\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t"\x8f\x01\n\x1cPartialUpdateInstanceRequest\x129\n\x08instance\x18\x01 \x01(\x0b2".google.bigtable.admin.v2.InstanceB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"T\n\x15DeleteInstanceRequest\x12;\n\x04name\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance"\xa7\x01\n\x14CreateClusterRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x17\n\ncluster_id\x18\x02 \x01(\tB\x03\xe0A\x02\x127\n\x07cluster\x18\x03 \x01(\x0b2!.google.bigtable.admin.v2.ClusterB\x03\xe0A\x02"O\n\x11GetClusterRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster"h\n\x13ListClustersRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x12\n\npage_token\x18\x02 \x01(\t"~\n\x14ListClustersResponse\x123\n\x08clusters\x18\x01 \x03(\x0b2!.google.bigtable.admin.v2.Cluster\x12\x18\n\x10failed_locations\x18\x02 \x03(\t\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t"R\n\x14DeleteClusterRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster"\xc6\x01\n\x16CreateInstanceMetadata\x12I\n\x10original_request\x18\x01 \x01(\x0b2/.google.bigtable.admin.v2.CreateInstanceRequest\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xcd\x01\n\x16UpdateInstanceMetadata\x12P\n\x10original_request\x18\x01 \x01(\x0b26.google.bigtable.admin.v2.PartialUpdateInstanceRequest\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xfb\x04\n\x15CreateClusterMetadata\x12H\n\x10original_request\x18\x01 \x01(\x0b2..google.bigtable.admin.v2.CreateClusterRequest\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12K\n\x06tables\x18\x04 \x03(\x0b2;.google.bigtable.admin.v2.CreateClusterMetadata.TablesEntry\x1a\xf9\x01\n\rTableProgress\x12\x1c\n\x14estimated_size_bytes\x18\x02 \x01(\x03\x12\x1e\n\x16estimated_copied_bytes\x18\x03 \x01(\x03\x12R\n\x05state\x18\x04 \x01(\x0e2C.google.bigtable.admin.v2.CreateClusterMetadata.TableProgress.State"V\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07COPYING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\r\n\tCANCELLED\x10\x04\x1al\n\x0bTablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12L\n\x05value\x18\x02 \x01(\x0b2=.google.bigtable.admin.v2.CreateClusterMetadata.TableProgress:\x028\x01"\xb7\x01\n\x15UpdateClusterMetadata\x12;\n\x10original_request\x18\x01 \x01(\x0b2!.google.bigtable.admin.v2.Cluster\x120\n\x0crequest_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"\xd2\x01\n\x1cPartialUpdateClusterMetadata\x120\n\x0crequest_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bfinish_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12O\n\x10original_request\x18\x03 \x01(\x0b25.google.bigtable.admin.v2.PartialUpdateClusterRequest"\x8c\x01\n\x1bPartialUpdateClusterRequest\x127\n\x07cluster\x18\x01 \x01(\x0b2!.google.bigtable.admin.v2.ClusterB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"\xce\x01\n\x17CreateAppProfileRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x1b\n\x0eapp_profile_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12>\n\x0bapp_profile\x18\x03 \x01(\x0b2$.google.bigtable.admin.v2.AppProfileB\x03\xe0A\x02\x12\x17\n\x0fignore_warnings\x18\x04 \x01(\x08"U\n\x14GetAppProfileRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'bigtableadmin.googleapis.com/AppProfile"~\n\x16ListAppProfilesRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t"\x88\x01\n\x17ListAppProfilesResponse\x12:\n\x0capp_profiles\x18\x01 \x03(\x0b2$.google.bigtable.admin.v2.AppProfile\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x18\n\x10failed_locations\x18\x03 \x03(\t"\xa8\x01\n\x17UpdateAppProfileRequest\x12>\n\x0bapp_profile\x18\x01 \x01(\x0b2$.google.bigtable.admin.v2.AppProfileB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12\x17\n\x0fignore_warnings\x18\x03 \x01(\x08"v\n\x17DeleteAppProfileRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'bigtableadmin.googleapis.com/AppProfile\x12\x1c\n\x0fignore_warnings\x18\x02 \x01(\x08B\x03\xe0A\x02"\x1a\n\x18UpdateAppProfileMetadata"\xda\x01\n\x15ListHotTabletsRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x12\n\npage_token\x18\x05 \x01(\t"k\n\x16ListHotTabletsResponse\x128\n\x0bhot_tablets\x18\x01 \x03(\x0b2#.google.bigtable.admin.v2.HotTablet\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb9\x01\n\x18CreateLogicalViewRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12\x1c\n\x0flogical_view_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12@\n\x0clogical_view\x18\x03 \x01(\x0b2%.google.bigtable.admin.v2.LogicalViewB\x03\xe0A\x02"\xc7\x01\n\x19CreateLogicalViewMetadata\x12L\n\x10original_request\x18\x01 \x01(\x0b22.google.bigtable.admin.v2.CreateLogicalViewRequest\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"W\n\x15GetLogicalViewRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(bigtableadmin.googleapis.com/LogicalView"\x8c\x01\n\x17ListLogicalViewsRequest\x12@\n\x06parent\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\x12(bigtableadmin.googleapis.com/LogicalView\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"q\n\x18ListLogicalViewsResponse\x12<\n\rlogical_views\x18\x01 \x03(\x0b2%.google.bigtable.admin.v2.LogicalView\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x92\x01\n\x18UpdateLogicalViewRequest\x12@\n\x0clogical_view\x18\x01 \x01(\x0b2%.google.bigtable.admin.v2.LogicalViewB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"\xc7\x01\n\x19UpdateLogicalViewMetadata\x12L\n\x10original_request\x18\x01 \x01(\x0b22.google.bigtable.admin.v2.UpdateLogicalViewRequest\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"m\n\x18DeleteLogicalViewRequest\x12>\n\x04name\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(bigtableadmin.googleapis.com/LogicalView\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01"\xcd\x01\n\x1dCreateMaterializedViewRequest\x12=\n\x06parent\x18\x01 \x01(\tB-\xe0A\x02\xfaA\'\n%bigtableadmin.googleapis.com/Instance\x12!\n\x14materialized_view_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12J\n\x11materialized_view\x18\x03 \x01(\x0b2*.google.bigtable.admin.v2.MaterializedViewB\x03\xe0A\x02"\xd1\x01\n\x1eCreateMaterializedViewMetadata\x12Q\n\x10original_request\x18\x01 \x01(\x0b27.google.bigtable.admin.v2.CreateMaterializedViewRequest\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"a\n\x1aGetMaterializedViewRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-bigtableadmin.googleapis.com/MaterializedView"\x96\x01\n\x1cListMaterializedViewsRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-bigtableadmin.googleapis.com/MaterializedView\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"\x80\x01\n\x1dListMaterializedViewsResponse\x12F\n\x12materialized_views\x18\x01 \x03(\x0b2*.google.bigtable.admin.v2.MaterializedView\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xa1\x01\n\x1dUpdateMaterializedViewRequest\x12J\n\x11materialized_view\x18\x01 \x01(\x0b2*.google.bigtable.admin.v2.MaterializedViewB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01"\xd1\x01\n\x1eUpdateMaterializedViewMetadata\x12Q\n\x10original_request\x18\x01 \x01(\x0b27.google.bigtable.admin.v2.UpdateMaterializedViewRequest\x12.\n\nstart_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"w\n\x1dDeleteMaterializedViewRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-bigtableadmin.googleapis.com/MaterializedView\x12\x11\n\x04etag\x18\x02 \x01(\tB\x03\xe0A\x012\xe66\n\x15BigtableInstanceAdmin\x12\xda\x01\n\x0eCreateInstance\x12/.google.bigtable.admin.v2.CreateInstanceRequest\x1a\x1d.google.longrunning.Operation"x\xcaA"\n\x08Instance\x12\x16CreateInstanceMetadata\xdaA$parent,instance_id,instance,clusters\x82\xd3\xe4\x93\x02&"!/v2/{parent=projects/*}/instances:\x01*\x12\x91\x01\n\x0bGetInstance\x12,.google.bigtable.admin.v2.GetInstanceRequest\x1a".google.bigtable.admin.v2.Instance"0\xdaA\x04name\x82\xd3\xe4\x93\x02#\x12!/v2/{name=projects/*/instances/*}\x12\xa4\x01\n\rListInstances\x12..google.bigtable.admin.v2.ListInstancesRequest\x1a/.google.bigtable.admin.v2.ListInstancesResponse"2\xdaA\x06parent\x82\xd3\xe4\x93\x02#\x12!/v2/{parent=projects/*}/instances\x12\x86\x01\n\x0eUpdateInstance\x12".google.bigtable.admin.v2.Instance\x1a".google.bigtable.admin.v2.Instance",\x82\xd3\xe4\x93\x02&\x1a!/v2/{name=projects/*/instances/*}:\x01*\x12\xe8\x01\n\x15PartialUpdateInstance\x126.google.bigtable.admin.v2.PartialUpdateInstanceRequest\x1a\x1d.google.longrunning.Operation"x\xcaA"\n\x08Instance\x12\x16UpdateInstanceMetadata\xdaA\x14instance,update_mask\x82\xd3\xe4\x93\x0262*/v2/{instance.name=projects/*/instances/*}:\x08instance\x12\x8b\x01\n\x0eDeleteInstance\x12/.google.bigtable.admin.v2.DeleteInstanceRequest\x1a\x16.google.protobuf.Empty"0\xdaA\x04name\x82\xd3\xe4\x93\x02#*!/v2/{name=projects/*/instances/*}\x12\xdc\x01\n\rCreateCluster\x12..google.bigtable.admin.v2.CreateClusterRequest\x1a\x1d.google.longrunning.Operation"|\xcaA \n\x07Cluster\x12\x15CreateClusterMetadata\xdaA\x19parent,cluster_id,cluster\x82\xd3\xe4\x93\x027",/v2/{parent=projects/*/instances/*}/clusters:\x07cluster\x12\x99\x01\n\nGetCluster\x12+.google.bigtable.admin.v2.GetClusterRequest\x1a!.google.bigtable.admin.v2.Cluster";\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v2/{name=projects/*/instances/*/clusters/*}\x12\xac\x01\n\x0cListClusters\x12-.google.bigtable.admin.v2.ListClustersRequest\x1a..google.bigtable.admin.v2.ListClustersResponse"=\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v2/{parent=projects/*/instances/*}/clusters\x12\xad\x01\n\rUpdateCluster\x12!.google.bigtable.admin.v2.Cluster\x1a\x1d.google.longrunning.Operation"Z\xcaA \n\x07Cluster\x12\x15UpdateClusterMetadata\x82\xd3\xe4\x93\x021\x1a,/v2/{name=projects/*/instances/*/clusters/*}:\x01*\x12\xf4\x01\n\x14PartialUpdateCluster\x125.google.bigtable.admin.v2.PartialUpdateClusterRequest\x1a\x1d.google.longrunning.Operation"\x85\x01\xcaA\'\n\x07Cluster\x12\x1cPartialUpdateClusterMetadata\xdaA\x13cluster,update_mask\x82\xd3\xe4\x93\x02?24/v2/{cluster.name=projects/*/instances/*/clusters/*}:\x07cluster\x12\x94\x01\n\rDeleteCluster\x12..google.bigtable.admin.v2.DeleteClusterRequest\x1a\x16.google.protobuf.Empty";\xdaA\x04name\x82\xd3\xe4\x93\x02.*,/v2/{name=projects/*/instances/*/clusters/*}\x12\xd5\x01\n\x10CreateAppProfile\x121.google.bigtable.admin.v2.CreateAppProfileRequest\x1a$.google.bigtable.admin.v2.AppProfile"h\xdaA!parent,app_profile_id,app_profile\x82\xd3\xe4\x93\x02>"//v2/{parent=projects/*/instances/*}/appProfiles:\x0bapp_profile\x12\xa5\x01\n\rGetAppProfile\x12..google.bigtable.admin.v2.GetAppProfileRequest\x1a$.google.bigtable.admin.v2.AppProfile">\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v2/{name=projects/*/instances/*/appProfiles/*}\x12\xb8\x01\n\x0fListAppProfiles\x120.google.bigtable.admin.v2.ListAppProfilesRequest\x1a1.google.bigtable.admin.v2.ListAppProfilesResponse"@\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v2/{parent=projects/*/instances/*}/appProfiles\x12\xfa\x01\n\x10UpdateAppProfile\x121.google.bigtable.admin.v2.UpdateAppProfileRequest\x1a\x1d.google.longrunning.Operation"\x93\x01\xcaA&\n\nAppProfile\x12\x18UpdateAppProfileMetadata\xdaA\x17app_profile,update_mask\x82\xd3\xe4\x93\x02J2;/v2/{app_profile.name=projects/*/instances/*/appProfiles/*}:\x0bapp_profile\x12\xb4\x01\n\x10DeleteAppProfile\x121.google.bigtable.admin.v2.DeleteAppProfileRequest\x1a\x16.google.protobuf.Empty"U\xdaA\x04name\xdaA\x14name,ignore_warnings\x82\xd3\xe4\x93\x021*//v2/{name=projects/*/instances/*/appProfiles/*}\x12\xaa\x02\n\x0cGetIamPolicy\x12".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"\xde\x01\xdaA\x08resource\x82\xd3\xe4\x93\x02\xcc\x01"2/v2/{resource=projects/*/instances/*}:getIamPolicy:\x01*ZK"F/v2/{resource=projects/*/instances/*/materializedViews/*}:getIamPolicy:\x01*ZF"A/v2/{resource=projects/*/instances/*/logicalViews/*}:getIamPolicy:\x01*\x12\xb1\x02\n\x0cSetIamPolicy\x12".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"\xe5\x01\xdaA\x0fresource,policy\x82\xd3\xe4\x93\x02\xcc\x01"2/v2/{resource=projects/*/instances/*}:setIamPolicy:\x01*ZK"F/v2/{resource=projects/*/instances/*/materializedViews/*}:setIamPolicy:\x01*ZF"A/v2/{resource=projects/*/instances/*/logicalViews/*}:setIamPolicy:\x01*\x12\xe8\x02\n\x12TestIamPermissions\x12(.google.iam.v1.TestIamPermissionsRequest\x1a).google.iam.v1.TestIamPermissionsResponse"\xfc\x01\xdaA\x14resource,permissions\x82\xd3\xe4\x93\x02\xde\x01"8/v2/{resource=projects/*/instances/*}:testIamPermissions:\x01*ZQ"L/v2/{resource=projects/*/instances/*/materializedViews/*}:testIamPermissions:\x01*ZL"G/v2/{resource=projects/*/instances/*/logicalViews/*}:testIamPermissions:\x01*\x12\xbf\x01\n\x0eListHotTablets\x12/.google.bigtable.admin.v2.ListHotTabletsRequest\x1a0.google.bigtable.admin.v2.ListHotTabletsResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v2/{parent=projects/*/instances/*/clusters/*}/hotTablets\x12\x80\x02\n\x11CreateLogicalView\x122.google.bigtable.admin.v2.CreateLogicalViewRequest\x1a\x1d.google.longrunning.Operation"\x97\x01\xcaA(\n\x0bLogicalView\x12\x19CreateLogicalViewMetadata\xdaA#parent,logical_view,logical_view_id\x82\xd3\xe4\x93\x02@"0/v2/{parent=projects/*/instances/*}/logicalViews:\x0clogical_view\x12\xa9\x01\n\x0eGetLogicalView\x12/.google.bigtable.admin.v2.GetLogicalViewRequest\x1a%.google.bigtable.admin.v2.LogicalView"?\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v2/{name=projects/*/instances/*/logicalViews/*}\x12\xbc\x01\n\x10ListLogicalViews\x121.google.bigtable.admin.v2.ListLogicalViewsRequest\x1a2.google.bigtable.admin.v2.ListLogicalViewsResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v2/{parent=projects/*/instances/*}/logicalViews\x12\x82\x02\n\x11UpdateLogicalView\x122.google.bigtable.admin.v2.UpdateLogicalViewRequest\x1a\x1d.google.longrunning.Operation"\x99\x01\xcaA(\n\x0bLogicalView\x12\x19UpdateLogicalViewMetadata\xdaA\x18logical_view,update_mask\x82\xd3\xe4\x93\x02M2=/v2/{logical_view.name=projects/*/instances/*/logicalViews/*}:\x0clogical_view\x12\xa0\x01\n\x11DeleteLogicalView\x122.google.bigtable.admin.v2.DeleteLogicalViewRequest\x1a\x16.google.protobuf.Empty"?\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v2/{name=projects/*/instances/*/logicalViews/*}\x12\xa8\x02\n\x16CreateMaterializedView\x127.google.bigtable.admin.v2.CreateMaterializedViewRequest\x1a\x1d.google.longrunning.Operation"\xb5\x01\xcaA2\n\x10MaterializedView\x12\x1eCreateMaterializedViewMetadata\xdaA-parent,materialized_view,materialized_view_id\x82\xd3\xe4\x93\x02J"5/v2/{parent=projects/*/instances/*}/materializedViews:\x11materialized_view\x12\xbd\x01\n\x13GetMaterializedView\x124.google.bigtable.admin.v2.GetMaterializedViewRequest\x1a*.google.bigtable.admin.v2.MaterializedView"D\xdaA\x04name\x82\xd3\xe4\x93\x027\x125/v2/{name=projects/*/instances/*/materializedViews/*}\x12\xd0\x01\n\x15ListMaterializedViews\x126.google.bigtable.admin.v2.ListMaterializedViewsRequest\x1a7.google.bigtable.admin.v2.ListMaterializedViewsResponse"F\xdaA\x06parent\x82\xd3\xe4\x93\x027\x125/v2/{parent=projects/*/instances/*}/materializedViews\x12\xaa\x02\n\x16UpdateMaterializedView\x127.google.bigtable.admin.v2.UpdateMaterializedViewRequest\x1a\x1d.google.longrunning.Operation"\xb7\x01\xcaA2\n\x10MaterializedView\x12\x1eUpdateMaterializedViewMetadata\xdaA\x1dmaterialized_view,update_mask\x82\xd3\xe4\x93\x02\\2G/v2/{materialized_view.name=projects/*/instances/*/materializedViews/*}:\x11materialized_view\x12\xaf\x01\n\x16DeleteMaterializedView\x127.google.bigtable.admin.v2.DeleteMaterializedViewRequest\x1a\x16.google.protobuf.Empty"D\xdaA\x04name\x82\xd3\xe4\x93\x027*5/v2/{name=projects/*/instances/*/materializedViews/*}\x1a\x9a\x03\xcaA\x1cbigtableadmin.googleapis.com\xd2A\xf7\x02https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.admin.cluster,https://www.googleapis.com/auth/bigtable.admin.instance,https://www.googleapis.com/auth/cloud-bigtable.admin,https://www.googleapis.com/auth/cloud-bigtable.admin.cluster,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/cloud-platform.read-onlyB\xdd\x01\n\x1ccom.google.bigtable.admin.v2B\x1aBigtableInstanceAdminProtoP\x01Z8cloud.google.com/go/bigtable/admin/apiv2/adminpb;adminpb\xaa\x02\x1eGoogle.Cloud.Bigtable.Admin.V2\xca\x02\x1eGoogle\\Cloud\\Bigtable\\Admin\\V2\xea\x02"Google::Cloud::Bigtable::Admin::V2b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.bigtable.admin.v2.bigtable_instance_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1ccom.google.bigtable.admin.v2B\x1aBigtableInstanceAdminProtoP\x01Z8cloud.google.com/go/bigtable/admin/apiv2/adminpb;adminpb\xaa\x02\x1eGoogle.Cloud.Bigtable.Admin.V2\xca\x02\x1eGoogle\\Cloud\\Bigtable\\Admin\\V2\xea\x02"Google::Cloud::Bigtable::Admin::V2'
    _globals['_CREATEINSTANCEREQUEST_CLUSTERSENTRY']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST_CLUSTERSENTRY']._serialized_options = b'8\x01'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['clusters']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['clusters']._serialized_options = b'\xe0A\x02'
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\n+cloudresourcemanager.googleapis.com/Project'
    _globals['_PARTIALUPDATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_PARTIALUPDATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_PARTIALUPDATEINSTANCEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_PARTIALUPDATEINSTANCEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_CREATECLUSTERREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECLUSTERREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_CREATECLUSTERREQUEST'].fields_by_name['cluster_id']._loaded_options = None
    _globals['_CREATECLUSTERREQUEST'].fields_by_name['cluster_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECLUSTERREQUEST'].fields_by_name['cluster']._loaded_options = None
    _globals['_CREATECLUSTERREQUEST'].fields_by_name['cluster']._serialized_options = b'\xe0A\x02'
    _globals['_GETCLUSTERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCLUSTERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_LISTCLUSTERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCLUSTERSREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_DELETECLUSTERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECLUSTERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_CREATECLUSTERMETADATA_TABLESENTRY']._loaded_options = None
    _globals['_CREATECLUSTERMETADATA_TABLESENTRY']._serialized_options = b'8\x01'
    _globals['_PARTIALUPDATECLUSTERREQUEST'].fields_by_name['cluster']._loaded_options = None
    _globals['_PARTIALUPDATECLUSTERREQUEST'].fields_by_name['cluster']._serialized_options = b'\xe0A\x02'
    _globals['_PARTIALUPDATECLUSTERREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_PARTIALUPDATECLUSTERREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEAPPPROFILEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEAPPPROFILEREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_CREATEAPPPROFILEREQUEST'].fields_by_name['app_profile_id']._loaded_options = None
    _globals['_CREATEAPPPROFILEREQUEST'].fields_by_name['app_profile_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEAPPPROFILEREQUEST'].fields_by_name['app_profile']._loaded_options = None
    _globals['_CREATEAPPPROFILEREQUEST'].fields_by_name['app_profile']._serialized_options = b'\xe0A\x02'
    _globals['_GETAPPPROFILEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETAPPPROFILEREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'bigtableadmin.googleapis.com/AppProfile"
    _globals['_LISTAPPPROFILESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTAPPPROFILESREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_UPDATEAPPPROFILEREQUEST'].fields_by_name['app_profile']._loaded_options = None
    _globals['_UPDATEAPPPROFILEREQUEST'].fields_by_name['app_profile']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEAPPPROFILEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEAPPPROFILEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEAPPPROFILEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEAPPPROFILEREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'bigtableadmin.googleapis.com/AppProfile"
    _globals['_DELETEAPPPROFILEREQUEST'].fields_by_name['ignore_warnings']._loaded_options = None
    _globals['_DELETEAPPPROFILEREQUEST'].fields_by_name['ignore_warnings']._serialized_options = b'\xe0A\x02'
    _globals['_LISTHOTTABLETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTHOTTABLETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$bigtableadmin.googleapis.com/Cluster'
    _globals['_CREATELOGICALVIEWREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATELOGICALVIEWREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_CREATELOGICALVIEWREQUEST'].fields_by_name['logical_view_id']._loaded_options = None
    _globals['_CREATELOGICALVIEWREQUEST'].fields_by_name['logical_view_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATELOGICALVIEWREQUEST'].fields_by_name['logical_view']._loaded_options = None
    _globals['_CREATELOGICALVIEWREQUEST'].fields_by_name['logical_view']._serialized_options = b'\xe0A\x02'
    _globals['_GETLOGICALVIEWREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETLOGICALVIEWREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(bigtableadmin.googleapis.com/LogicalView'
    _globals['_LISTLOGICALVIEWSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTLOGICALVIEWSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA*\x12(bigtableadmin.googleapis.com/LogicalView'
    _globals['_LISTLOGICALVIEWSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTLOGICALVIEWSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTLOGICALVIEWSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTLOGICALVIEWSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATELOGICALVIEWREQUEST'].fields_by_name['logical_view']._loaded_options = None
    _globals['_UPDATELOGICALVIEWREQUEST'].fields_by_name['logical_view']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATELOGICALVIEWREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATELOGICALVIEWREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETELOGICALVIEWREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETELOGICALVIEWREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA*\n(bigtableadmin.googleapis.com/LogicalView'
    _globals['_DELETELOGICALVIEWREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETELOGICALVIEWREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEMATERIALIZEDVIEWREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEMATERIALIZEDVIEWREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA'\n%bigtableadmin.googleapis.com/Instance"
    _globals['_CREATEMATERIALIZEDVIEWREQUEST'].fields_by_name['materialized_view_id']._loaded_options = None
    _globals['_CREATEMATERIALIZEDVIEWREQUEST'].fields_by_name['materialized_view_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEMATERIALIZEDVIEWREQUEST'].fields_by_name['materialized_view']._loaded_options = None
    _globals['_CREATEMATERIALIZEDVIEWREQUEST'].fields_by_name['materialized_view']._serialized_options = b'\xe0A\x02'
    _globals['_GETMATERIALIZEDVIEWREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETMATERIALIZEDVIEWREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-bigtableadmin.googleapis.com/MaterializedView'
    _globals['_LISTMATERIALIZEDVIEWSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTMATERIALIZEDVIEWSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-bigtableadmin.googleapis.com/MaterializedView'
    _globals['_LISTMATERIALIZEDVIEWSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTMATERIALIZEDVIEWSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTMATERIALIZEDVIEWSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTMATERIALIZEDVIEWSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEMATERIALIZEDVIEWREQUEST'].fields_by_name['materialized_view']._loaded_options = None
    _globals['_UPDATEMATERIALIZEDVIEWREQUEST'].fields_by_name['materialized_view']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEMATERIALIZEDVIEWREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEMATERIALIZEDVIEWREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEMATERIALIZEDVIEWREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEMATERIALIZEDVIEWREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-bigtableadmin.googleapis.com/MaterializedView'
    _globals['_DELETEMATERIALIZEDVIEWREQUEST'].fields_by_name['etag']._loaded_options = None
    _globals['_DELETEMATERIALIZEDVIEWREQUEST'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_BIGTABLEINSTANCEADMIN']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN']._serialized_options = b'\xcaA\x1cbigtableadmin.googleapis.com\xd2A\xf7\x02https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.admin.cluster,https://www.googleapis.com/auth/bigtable.admin.instance,https://www.googleapis.com/auth/cloud-bigtable.admin,https://www.googleapis.com/auth/cloud-bigtable.admin.cluster,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/cloud-platform.read-only'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateInstance']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateInstance']._serialized_options = b'\xcaA"\n\x08Instance\x12\x16CreateInstanceMetadata\xdaA$parent,instance_id,instance,clusters\x82\xd3\xe4\x93\x02&"!/v2/{parent=projects/*}/instances:\x01*'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetInstance']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02#\x12!/v2/{name=projects/*/instances/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListInstances']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListInstances']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02#\x12!/v2/{parent=projects/*}/instances'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateInstance']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateInstance']._serialized_options = b'\x82\xd3\xe4\x93\x02&\x1a!/v2/{name=projects/*/instances/*}:\x01*'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['PartialUpdateInstance']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['PartialUpdateInstance']._serialized_options = b'\xcaA"\n\x08Instance\x12\x16UpdateInstanceMetadata\xdaA\x14instance,update_mask\x82\xd3\xe4\x93\x0262*/v2/{instance.name=projects/*/instances/*}:\x08instance'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteInstance']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02#*!/v2/{name=projects/*/instances/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateCluster']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateCluster']._serialized_options = b'\xcaA \n\x07Cluster\x12\x15CreateClusterMetadata\xdaA\x19parent,cluster_id,cluster\x82\xd3\xe4\x93\x027",/v2/{parent=projects/*/instances/*}/clusters:\x07cluster'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetCluster']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetCluster']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02.\x12,/v2/{name=projects/*/instances/*/clusters/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListClusters']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListClusters']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02.\x12,/v2/{parent=projects/*/instances/*}/clusters'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateCluster']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateCluster']._serialized_options = b'\xcaA \n\x07Cluster\x12\x15UpdateClusterMetadata\x82\xd3\xe4\x93\x021\x1a,/v2/{name=projects/*/instances/*/clusters/*}:\x01*'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['PartialUpdateCluster']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['PartialUpdateCluster']._serialized_options = b"\xcaA'\n\x07Cluster\x12\x1cPartialUpdateClusterMetadata\xdaA\x13cluster,update_mask\x82\xd3\xe4\x93\x02?24/v2/{cluster.name=projects/*/instances/*/clusters/*}:\x07cluster"
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteCluster']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteCluster']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02.*,/v2/{name=projects/*/instances/*/clusters/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateAppProfile']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateAppProfile']._serialized_options = b'\xdaA!parent,app_profile_id,app_profile\x82\xd3\xe4\x93\x02>"//v2/{parent=projects/*/instances/*}/appProfiles:\x0bapp_profile'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetAppProfile']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetAppProfile']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v2/{name=projects/*/instances/*/appProfiles/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListAppProfiles']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListAppProfiles']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v2/{parent=projects/*/instances/*}/appProfiles'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateAppProfile']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateAppProfile']._serialized_options = b'\xcaA&\n\nAppProfile\x12\x18UpdateAppProfileMetadata\xdaA\x17app_profile,update_mask\x82\xd3\xe4\x93\x02J2;/v2/{app_profile.name=projects/*/instances/*/appProfiles/*}:\x0bapp_profile'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteAppProfile']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteAppProfile']._serialized_options = b'\xdaA\x04name\xdaA\x14name,ignore_warnings\x82\xd3\xe4\x93\x021*//v2/{name=projects/*/instances/*/appProfiles/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetIamPolicy']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetIamPolicy']._serialized_options = b'\xdaA\x08resource\x82\xd3\xe4\x93\x02\xcc\x01"2/v2/{resource=projects/*/instances/*}:getIamPolicy:\x01*ZK"F/v2/{resource=projects/*/instances/*/materializedViews/*}:getIamPolicy:\x01*ZF"A/v2/{resource=projects/*/instances/*/logicalViews/*}:getIamPolicy:\x01*'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['SetIamPolicy']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['SetIamPolicy']._serialized_options = b'\xdaA\x0fresource,policy\x82\xd3\xe4\x93\x02\xcc\x01"2/v2/{resource=projects/*/instances/*}:setIamPolicy:\x01*ZK"F/v2/{resource=projects/*/instances/*/materializedViews/*}:setIamPolicy:\x01*ZF"A/v2/{resource=projects/*/instances/*/logicalViews/*}:setIamPolicy:\x01*'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['TestIamPermissions']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['TestIamPermissions']._serialized_options = b'\xdaA\x14resource,permissions\x82\xd3\xe4\x93\x02\xde\x01"8/v2/{resource=projects/*/instances/*}:testIamPermissions:\x01*ZQ"L/v2/{resource=projects/*/instances/*/materializedViews/*}:testIamPermissions:\x01*ZL"G/v2/{resource=projects/*/instances/*/logicalViews/*}:testIamPermissions:\x01*'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListHotTablets']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListHotTablets']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v2/{parent=projects/*/instances/*/clusters/*}/hotTablets'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateLogicalView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateLogicalView']._serialized_options = b'\xcaA(\n\x0bLogicalView\x12\x19CreateLogicalViewMetadata\xdaA#parent,logical_view,logical_view_id\x82\xd3\xe4\x93\x02@"0/v2/{parent=projects/*/instances/*}/logicalViews:\x0clogical_view'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetLogicalView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetLogicalView']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v2/{name=projects/*/instances/*/logicalViews/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListLogicalViews']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListLogicalViews']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v2/{parent=projects/*/instances/*}/logicalViews'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateLogicalView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateLogicalView']._serialized_options = b'\xcaA(\n\x0bLogicalView\x12\x19UpdateLogicalViewMetadata\xdaA\x18logical_view,update_mask\x82\xd3\xe4\x93\x02M2=/v2/{logical_view.name=projects/*/instances/*/logicalViews/*}:\x0clogical_view'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteLogicalView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteLogicalView']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v2/{name=projects/*/instances/*/logicalViews/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateMaterializedView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['CreateMaterializedView']._serialized_options = b'\xcaA2\n\x10MaterializedView\x12\x1eCreateMaterializedViewMetadata\xdaA-parent,materialized_view,materialized_view_id\x82\xd3\xe4\x93\x02J"5/v2/{parent=projects/*/instances/*}/materializedViews:\x11materialized_view'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetMaterializedView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['GetMaterializedView']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x027\x125/v2/{name=projects/*/instances/*/materializedViews/*}'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListMaterializedViews']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['ListMaterializedViews']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x027\x125/v2/{parent=projects/*/instances/*}/materializedViews'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateMaterializedView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['UpdateMaterializedView']._serialized_options = b'\xcaA2\n\x10MaterializedView\x12\x1eUpdateMaterializedViewMetadata\xdaA\x1dmaterialized_view,update_mask\x82\xd3\xe4\x93\x02\\2G/v2/{materialized_view.name=projects/*/instances/*/materializedViews/*}:\x11materialized_view'
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteMaterializedView']._loaded_options = None
    _globals['_BIGTABLEINSTANCEADMIN'].methods_by_name['DeleteMaterializedView']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x027*5/v2/{name=projects/*/instances/*/materializedViews/*}'
    _globals['_CREATEINSTANCEREQUEST']._serialized_start = 434
    _globals['_CREATEINSTANCEREQUEST']._serialized_end = 781
    _globals['_CREATEINSTANCEREQUEST_CLUSTERSENTRY']._serialized_start = 699
    _globals['_CREATEINSTANCEREQUEST_CLUSTERSENTRY']._serialized_end = 781
    _globals['_GETINSTANCEREQUEST']._serialized_start = 783
    _globals['_GETINSTANCEREQUEST']._serialized_end = 864
    _globals['_LISTINSTANCESREQUEST']._serialized_start = 866
    _globals['_LISTINSTANCESREQUEST']._serialized_end = 977
    _globals['_LISTINSTANCESRESPONSE']._serialized_start = 980
    _globals['_LISTINSTANCESRESPONSE']._serialized_end = 1109
    _globals['_PARTIALUPDATEINSTANCEREQUEST']._serialized_start = 1112
    _globals['_PARTIALUPDATEINSTANCEREQUEST']._serialized_end = 1255
    _globals['_DELETEINSTANCEREQUEST']._serialized_start = 1257
    _globals['_DELETEINSTANCEREQUEST']._serialized_end = 1341
    _globals['_CREATECLUSTERREQUEST']._serialized_start = 1344
    _globals['_CREATECLUSTERREQUEST']._serialized_end = 1511
    _globals['_GETCLUSTERREQUEST']._serialized_start = 1513
    _globals['_GETCLUSTERREQUEST']._serialized_end = 1592
    _globals['_LISTCLUSTERSREQUEST']._serialized_start = 1594
    _globals['_LISTCLUSTERSREQUEST']._serialized_end = 1698
    _globals['_LISTCLUSTERSRESPONSE']._serialized_start = 1700
    _globals['_LISTCLUSTERSRESPONSE']._serialized_end = 1826
    _globals['_DELETECLUSTERREQUEST']._serialized_start = 1828
    _globals['_DELETECLUSTERREQUEST']._serialized_end = 1910
    _globals['_CREATEINSTANCEMETADATA']._serialized_start = 1913
    _globals['_CREATEINSTANCEMETADATA']._serialized_end = 2111
    _globals['_UPDATEINSTANCEMETADATA']._serialized_start = 2114
    _globals['_UPDATEINSTANCEMETADATA']._serialized_end = 2319
    _globals['_CREATECLUSTERMETADATA']._serialized_start = 2322
    _globals['_CREATECLUSTERMETADATA']._serialized_end = 2957
    _globals['_CREATECLUSTERMETADATA_TABLEPROGRESS']._serialized_start = 2598
    _globals['_CREATECLUSTERMETADATA_TABLEPROGRESS']._serialized_end = 2847
    _globals['_CREATECLUSTERMETADATA_TABLEPROGRESS_STATE']._serialized_start = 2761
    _globals['_CREATECLUSTERMETADATA_TABLEPROGRESS_STATE']._serialized_end = 2847
    _globals['_CREATECLUSTERMETADATA_TABLESENTRY']._serialized_start = 2849
    _globals['_CREATECLUSTERMETADATA_TABLESENTRY']._serialized_end = 2957
    _globals['_UPDATECLUSTERMETADATA']._serialized_start = 2960
    _globals['_UPDATECLUSTERMETADATA']._serialized_end = 3143
    _globals['_PARTIALUPDATECLUSTERMETADATA']._serialized_start = 3146
    _globals['_PARTIALUPDATECLUSTERMETADATA']._serialized_end = 3356
    _globals['_PARTIALUPDATECLUSTERREQUEST']._serialized_start = 3359
    _globals['_PARTIALUPDATECLUSTERREQUEST']._serialized_end = 3499
    _globals['_CREATEAPPPROFILEREQUEST']._serialized_start = 3502
    _globals['_CREATEAPPPROFILEREQUEST']._serialized_end = 3708
    _globals['_GETAPPPROFILEREQUEST']._serialized_start = 3710
    _globals['_GETAPPPROFILEREQUEST']._serialized_end = 3795
    _globals['_LISTAPPPROFILESREQUEST']._serialized_start = 3797
    _globals['_LISTAPPPROFILESREQUEST']._serialized_end = 3923
    _globals['_LISTAPPPROFILESRESPONSE']._serialized_start = 3926
    _globals['_LISTAPPPROFILESRESPONSE']._serialized_end = 4062
    _globals['_UPDATEAPPPROFILEREQUEST']._serialized_start = 4065
    _globals['_UPDATEAPPPROFILEREQUEST']._serialized_end = 4233
    _globals['_DELETEAPPPROFILEREQUEST']._serialized_start = 4235
    _globals['_DELETEAPPPROFILEREQUEST']._serialized_end = 4353
    _globals['_UPDATEAPPPROFILEMETADATA']._serialized_start = 4355
    _globals['_UPDATEAPPPROFILEMETADATA']._serialized_end = 4381
    _globals['_LISTHOTTABLETSREQUEST']._serialized_start = 4384
    _globals['_LISTHOTTABLETSREQUEST']._serialized_end = 4602
    _globals['_LISTHOTTABLETSRESPONSE']._serialized_start = 4604
    _globals['_LISTHOTTABLETSRESPONSE']._serialized_end = 4711
    _globals['_CREATELOGICALVIEWREQUEST']._serialized_start = 4714
    _globals['_CREATELOGICALVIEWREQUEST']._serialized_end = 4899
    _globals['_CREATELOGICALVIEWMETADATA']._serialized_start = 4902
    _globals['_CREATELOGICALVIEWMETADATA']._serialized_end = 5101
    _globals['_GETLOGICALVIEWREQUEST']._serialized_start = 5103
    _globals['_GETLOGICALVIEWREQUEST']._serialized_end = 5190
    _globals['_LISTLOGICALVIEWSREQUEST']._serialized_start = 5193
    _globals['_LISTLOGICALVIEWSREQUEST']._serialized_end = 5333
    _globals['_LISTLOGICALVIEWSRESPONSE']._serialized_start = 5335
    _globals['_LISTLOGICALVIEWSRESPONSE']._serialized_end = 5448
    _globals['_UPDATELOGICALVIEWREQUEST']._serialized_start = 5451
    _globals['_UPDATELOGICALVIEWREQUEST']._serialized_end = 5597
    _globals['_UPDATELOGICALVIEWMETADATA']._serialized_start = 5600
    _globals['_UPDATELOGICALVIEWMETADATA']._serialized_end = 5799
    _globals['_DELETELOGICALVIEWREQUEST']._serialized_start = 5801
    _globals['_DELETELOGICALVIEWREQUEST']._serialized_end = 5910
    _globals['_CREATEMATERIALIZEDVIEWREQUEST']._serialized_start = 5913
    _globals['_CREATEMATERIALIZEDVIEWREQUEST']._serialized_end = 6118
    _globals['_CREATEMATERIALIZEDVIEWMETADATA']._serialized_start = 6121
    _globals['_CREATEMATERIALIZEDVIEWMETADATA']._serialized_end = 6330
    _globals['_GETMATERIALIZEDVIEWREQUEST']._serialized_start = 6332
    _globals['_GETMATERIALIZEDVIEWREQUEST']._serialized_end = 6429
    _globals['_LISTMATERIALIZEDVIEWSREQUEST']._serialized_start = 6432
    _globals['_LISTMATERIALIZEDVIEWSREQUEST']._serialized_end = 6582
    _globals['_LISTMATERIALIZEDVIEWSRESPONSE']._serialized_start = 6585
    _globals['_LISTMATERIALIZEDVIEWSRESPONSE']._serialized_end = 6713
    _globals['_UPDATEMATERIALIZEDVIEWREQUEST']._serialized_start = 6716
    _globals['_UPDATEMATERIALIZEDVIEWREQUEST']._serialized_end = 6877
    _globals['_UPDATEMATERIALIZEDVIEWMETADATA']._serialized_start = 6880
    _globals['_UPDATEMATERIALIZEDVIEWMETADATA']._serialized_end = 7089
    _globals['_DELETEMATERIALIZEDVIEWREQUEST']._serialized_start = 7091
    _globals['_DELETEMATERIALIZEDVIEWREQUEST']._serialized_end = 7210
    _globals['_BIGTABLEINSTANCEADMIN']._serialized_start = 7213
    _globals['_BIGTABLEINSTANCEADMIN']._serialized_end = 14227