# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core_system_grpc.messages.common import request_pb2 as messages_dot_common_dot_request__pb2
from core_system_grpc.messages.customer import response_pb2 as messages_dot_customer_dot_response__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/customer_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerServiceStub(object):
    """CustomerService 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomersByShop = channel.unary_unary(
                '/core_system.customer.v1.CustomerService/GetCustomersByShop',
                request_serializer=messages_dot_common_dot_request__pb2.GetByShopRequest.SerializeToString,
                response_deserializer=messages_dot_customer_dot_response__pb2.GetCustomersByShopResponse.FromString,
                _registered_method=True)


class CustomerServiceServicer(object):
    """CustomerService 정의
    """

    def GetCustomersByShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomersByShop': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomersByShop,
                    request_deserializer=messages_dot_common_dot_request__pb2.GetByShopRequest.FromString,
                    response_serializer=messages_dot_customer_dot_response__pb2.GetCustomersByShopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core_system.customer.v1.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core_system.customer.v1.CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """CustomerService 정의
    """

    @staticmethod
    def GetCustomersByShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_system.customer.v1.CustomerService/GetCustomersByShop',
            messages_dot_common_dot_request__pb2.GetByShopRequest.SerializeToString,
            messages_dot_customer_dot_response__pb2.GetCustomersByShopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
