from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar
DESCRIPTOR: _descriptor.FileDescriptor

class FeedItemValidationErrorEnum(_message.Message):
    __slots__ = ()

    class FeedItemValidationError(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        UNSPECIFIED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        UNKNOWN: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        STRING_TOO_SHORT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        STRING_TOO_LONG: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        VALUE_NOT_SPECIFIED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_DOMESTIC_PHONE_NUMBER_FORMAT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_PHONE_NUMBER: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        PREMIUM_RATE_NUMBER_NOT_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        DISALLOWED_NUMBER_TYPE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        VALUE_OUT_OF_RANGE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        CUSTOMER_NOT_IN_ALLOWLIST_FOR_CALLTRACKING: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_COUNTRY_CODE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_APP_ID: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_ATTRIBUTES_FOR_FIELDS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_TYPE_ID: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_EMAIL_ADDRESS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_HTTPS_URL: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_DELIVERY_ADDRESS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        START_DATE_AFTER_END_DATE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_FEED_ITEM_START_TIME: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_FEED_ITEM_END_TIME: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_FEED_ITEM_ID: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        VANITY_PHONE_NUMBER_NOT_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_REVIEW_EXTENSION_SNIPPET: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_NUMBER_FORMAT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_DATE_FORMAT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_PRICE_FORMAT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        UNKNOWN_PLACEHOLDER_FIELD: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_ENHANCED_SITELINK_DESCRIPTION_LINE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        REVIEW_EXTENSION_SOURCE_INELIGIBLE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        HYPHENS_IN_REVIEW_EXTENSION_SNIPPET: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        DOUBLE_QUOTES_IN_REVIEW_EXTENSION_SNIPPET: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        QUOTES_IN_REVIEW_EXTENSION_SNIPPET: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_FORM_ENCODED_PARAMS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_URL_PARAMETER_NAME: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        NO_GEOCODING_RESULT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        SOURCE_NAME_IN_REVIEW_EXTENSION_TEXT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_PLACEHOLDER_FIELD_ID: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_URL_TAG: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        LIST_TOO_LONG: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_ATTRIBUTES_COMBINATION: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        DUPLICATE_VALUES: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_CALL_CONVERSION_ACTION_ID: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        CANNOT_SET_WITHOUT_FINAL_URLS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        APP_ID_DOESNT_EXIST_IN_APP_STORE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_FINAL_URL: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_TRACKING_URL: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_FINAL_URL_FOR_APP_DOWNLOAD_URL: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        LIST_TOO_SHORT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_USER_ACTION: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_TYPE_NAME: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_EVENT_CHANGE_STATUS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_SNIPPETS_HEADER: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_ANDROID_APP_LINK: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        NUMBER_TYPE_WITH_CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        RESERVED_KEYWORD_OTHER: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        DUPLICATE_OPTION_LABELS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        DUPLICATE_OPTION_PREFILLS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        UNEQUAL_LIST_LENGTHS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INCONSISTENT_CURRENCY_CODES: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        PRICE_EXTENSION_HAS_DUPLICATED_HEADERS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        ITEM_HAS_DUPLICATED_HEADER_AND_DESCRIPTION: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        PRICE_EXTENSION_HAS_TOO_FEW_ITEMS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        UNSUPPORTED_VALUE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_FINAL_MOBILE_URL: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_KEYWORDLESS_AD_RULE_LABEL: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        VALUE_TRACK_PARAMETER_NOT_SUPPORTED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        UNSUPPORTED_VALUE_IN_SELECTED_LANGUAGE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_IOS_APP_LINK: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_IOS_APP_LINK_OR_IOS_APP_STORE_ID: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        PROMOTION_INVALID_TIME: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        PROMOTION_CANNOT_SET_PERCENT_OFF_AND_MONEY_AMOUNT_OFF: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        PROMOTION_CANNOT_SET_PROMOTION_CODE_AND_ORDERS_OVER_AMOUNT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        TOO_MANY_DECIMAL_PLACES_SPECIFIED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        AD_CUSTOMIZERS_NOT_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_LANGUAGE_CODE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        UNSUPPORTED_LANGUAGE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IF_FUNCTION_NOT_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_FINAL_URL_SUFFIX: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_TAG_IN_FINAL_URL_SUFFIX: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_FINAL_URL_SUFFIX_FORMAT: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        ONLY_ONE_DELIVERY_OPTION_IS_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        NO_DELIVERY_OPTION_IS_SET: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_CONVERSION_REPORTING_STATE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IMAGE_SIZE_WRONG: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        EMAIL_DELIVERY_NOT_AVAILABLE_IN_COUNTRY: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        AUTO_REPLY_NOT_AVAILABLE_IN_COUNTRY: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_LATITUDE_VALUE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_LONGITUDE_VALUE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        TOO_MANY_LABELS: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_IMAGE_URL: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_LATITUDE_VALUE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        MISSING_LONGITUDE_VALUE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        ADDRESS_NOT_FOUND: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        ADDRESS_NOT_TARGETABLE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INVALID_ASSET_ID: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        INCOMPATIBLE_ASSET_TYPE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IMAGE_ERROR_UNEXPECTED_SIZE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IMAGE_ERROR_ASPECT_RATIO_NOT_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IMAGE_ERROR_FILE_TOO_LARGE: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IMAGE_ERROR_FORMAT_NOT_ALLOWED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IMAGE_ERROR_CONSTRAINTS_VIOLATED: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
        IMAGE_ERROR_SERVER_ERROR: _ClassVar[FeedItemValidationErrorEnum.FeedItemValidationError]
    UNSPECIFIED: FeedItemValidationErrorEnum.FeedItemValidationError
    UNKNOWN: FeedItemValidationErrorEnum.FeedItemValidationError
    STRING_TOO_SHORT: FeedItemValidationErrorEnum.FeedItemValidationError
    STRING_TOO_LONG: FeedItemValidationErrorEnum.FeedItemValidationError
    VALUE_NOT_SPECIFIED: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_DOMESTIC_PHONE_NUMBER_FORMAT: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_PHONE_NUMBER: FeedItemValidationErrorEnum.FeedItemValidationError
    PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY: FeedItemValidationErrorEnum.FeedItemValidationError
    PREMIUM_RATE_NUMBER_NOT_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    DISALLOWED_NUMBER_TYPE: FeedItemValidationErrorEnum.FeedItemValidationError
    VALUE_OUT_OF_RANGE: FeedItemValidationErrorEnum.FeedItemValidationError
    CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY: FeedItemValidationErrorEnum.FeedItemValidationError
    CUSTOMER_NOT_IN_ALLOWLIST_FOR_CALLTRACKING: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_COUNTRY_CODE: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_APP_ID: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_ATTRIBUTES_FOR_FIELDS: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_TYPE_ID: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_EMAIL_ADDRESS: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_HTTPS_URL: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_DELIVERY_ADDRESS: FeedItemValidationErrorEnum.FeedItemValidationError
    START_DATE_AFTER_END_DATE: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_FEED_ITEM_START_TIME: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_FEED_ITEM_END_TIME: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_FEED_ITEM_ID: FeedItemValidationErrorEnum.FeedItemValidationError
    VANITY_PHONE_NUMBER_NOT_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_REVIEW_EXTENSION_SNIPPET: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_NUMBER_FORMAT: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_DATE_FORMAT: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_PRICE_FORMAT: FeedItemValidationErrorEnum.FeedItemValidationError
    UNKNOWN_PLACEHOLDER_FIELD: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_ENHANCED_SITELINK_DESCRIPTION_LINE: FeedItemValidationErrorEnum.FeedItemValidationError
    REVIEW_EXTENSION_SOURCE_INELIGIBLE: FeedItemValidationErrorEnum.FeedItemValidationError
    HYPHENS_IN_REVIEW_EXTENSION_SNIPPET: FeedItemValidationErrorEnum.FeedItemValidationError
    DOUBLE_QUOTES_IN_REVIEW_EXTENSION_SNIPPET: FeedItemValidationErrorEnum.FeedItemValidationError
    QUOTES_IN_REVIEW_EXTENSION_SNIPPET: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_FORM_ENCODED_PARAMS: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_URL_PARAMETER_NAME: FeedItemValidationErrorEnum.FeedItemValidationError
    NO_GEOCODING_RESULT: FeedItemValidationErrorEnum.FeedItemValidationError
    SOURCE_NAME_IN_REVIEW_EXTENSION_TEXT: FeedItemValidationErrorEnum.FeedItemValidationError
    CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_PLACEHOLDER_FIELD_ID: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_URL_TAG: FeedItemValidationErrorEnum.FeedItemValidationError
    LIST_TOO_LONG: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_ATTRIBUTES_COMBINATION: FeedItemValidationErrorEnum.FeedItemValidationError
    DUPLICATE_VALUES: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_CALL_CONVERSION_ACTION_ID: FeedItemValidationErrorEnum.FeedItemValidationError
    CANNOT_SET_WITHOUT_FINAL_URLS: FeedItemValidationErrorEnum.FeedItemValidationError
    APP_ID_DOESNT_EXIST_IN_APP_STORE: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_FINAL_URL: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_TRACKING_URL: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_FINAL_URL_FOR_APP_DOWNLOAD_URL: FeedItemValidationErrorEnum.FeedItemValidationError
    LIST_TOO_SHORT: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_USER_ACTION: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_TYPE_NAME: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_EVENT_CHANGE_STATUS: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_SNIPPETS_HEADER: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_ANDROID_APP_LINK: FeedItemValidationErrorEnum.FeedItemValidationError
    NUMBER_TYPE_WITH_CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY: FeedItemValidationErrorEnum.FeedItemValidationError
    RESERVED_KEYWORD_OTHER: FeedItemValidationErrorEnum.FeedItemValidationError
    DUPLICATE_OPTION_LABELS: FeedItemValidationErrorEnum.FeedItemValidationError
    DUPLICATE_OPTION_PREFILLS: FeedItemValidationErrorEnum.FeedItemValidationError
    UNEQUAL_LIST_LENGTHS: FeedItemValidationErrorEnum.FeedItemValidationError
    INCONSISTENT_CURRENCY_CODES: FeedItemValidationErrorEnum.FeedItemValidationError
    PRICE_EXTENSION_HAS_DUPLICATED_HEADERS: FeedItemValidationErrorEnum.FeedItemValidationError
    ITEM_HAS_DUPLICATED_HEADER_AND_DESCRIPTION: FeedItemValidationErrorEnum.FeedItemValidationError
    PRICE_EXTENSION_HAS_TOO_FEW_ITEMS: FeedItemValidationErrorEnum.FeedItemValidationError
    UNSUPPORTED_VALUE: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_FINAL_MOBILE_URL: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_KEYWORDLESS_AD_RULE_LABEL: FeedItemValidationErrorEnum.FeedItemValidationError
    VALUE_TRACK_PARAMETER_NOT_SUPPORTED: FeedItemValidationErrorEnum.FeedItemValidationError
    UNSUPPORTED_VALUE_IN_SELECTED_LANGUAGE: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_IOS_APP_LINK: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_IOS_APP_LINK_OR_IOS_APP_STORE_ID: FeedItemValidationErrorEnum.FeedItemValidationError
    PROMOTION_INVALID_TIME: FeedItemValidationErrorEnum.FeedItemValidationError
    PROMOTION_CANNOT_SET_PERCENT_OFF_AND_MONEY_AMOUNT_OFF: FeedItemValidationErrorEnum.FeedItemValidationError
    PROMOTION_CANNOT_SET_PROMOTION_CODE_AND_ORDERS_OVER_AMOUNT: FeedItemValidationErrorEnum.FeedItemValidationError
    TOO_MANY_DECIMAL_PLACES_SPECIFIED: FeedItemValidationErrorEnum.FeedItemValidationError
    AD_CUSTOMIZERS_NOT_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_LANGUAGE_CODE: FeedItemValidationErrorEnum.FeedItemValidationError
    UNSUPPORTED_LANGUAGE: FeedItemValidationErrorEnum.FeedItemValidationError
    IF_FUNCTION_NOT_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_FINAL_URL_SUFFIX: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_TAG_IN_FINAL_URL_SUFFIX: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_FINAL_URL_SUFFIX_FORMAT: FeedItemValidationErrorEnum.FeedItemValidationError
    CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED: FeedItemValidationErrorEnum.FeedItemValidationError
    ONLY_ONE_DELIVERY_OPTION_IS_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    NO_DELIVERY_OPTION_IS_SET: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_CONVERSION_REPORTING_STATE: FeedItemValidationErrorEnum.FeedItemValidationError
    IMAGE_SIZE_WRONG: FeedItemValidationErrorEnum.FeedItemValidationError
    EMAIL_DELIVERY_NOT_AVAILABLE_IN_COUNTRY: FeedItemValidationErrorEnum.FeedItemValidationError
    AUTO_REPLY_NOT_AVAILABLE_IN_COUNTRY: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_LATITUDE_VALUE: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_LONGITUDE_VALUE: FeedItemValidationErrorEnum.FeedItemValidationError
    TOO_MANY_LABELS: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_IMAGE_URL: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_LATITUDE_VALUE: FeedItemValidationErrorEnum.FeedItemValidationError
    MISSING_LONGITUDE_VALUE: FeedItemValidationErrorEnum.FeedItemValidationError
    ADDRESS_NOT_FOUND: FeedItemValidationErrorEnum.FeedItemValidationError
    ADDRESS_NOT_TARGETABLE: FeedItemValidationErrorEnum.FeedItemValidationError
    INVALID_ASSET_ID: FeedItemValidationErrorEnum.FeedItemValidationError
    INCOMPATIBLE_ASSET_TYPE: FeedItemValidationErrorEnum.FeedItemValidationError
    IMAGE_ERROR_UNEXPECTED_SIZE: FeedItemValidationErrorEnum.FeedItemValidationError
    IMAGE_ERROR_ASPECT_RATIO_NOT_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    IMAGE_ERROR_FILE_TOO_LARGE: FeedItemValidationErrorEnum.FeedItemValidationError
    IMAGE_ERROR_FORMAT_NOT_ALLOWED: FeedItemValidationErrorEnum.FeedItemValidationError
    IMAGE_ERROR_CONSTRAINTS_VIOLATED: FeedItemValidationErrorEnum.FeedItemValidationError
    IMAGE_ERROR_SERVER_ERROR: FeedItemValidationErrorEnum.FeedItemValidationError

    def __init__(self) -> None:
        ...