"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/discoveryengine/v1/search_service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.discoveryengine.v1 import chunk_pb2 as google_dot_cloud_dot_discoveryengine_dot_v1_dot_chunk__pb2
from .....google.cloud.discoveryengine.v1 import common_pb2 as google_dot_cloud_dot_discoveryengine_dot_v1_dot_common__pb2
from .....google.cloud.discoveryengine.v1 import document_pb2 as google_dot_cloud_dot_discoveryengine_dot_v1_dot_document__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4google/cloud/discoveryengine/v1/search_service.proto\x12\x1fgoogle.cloud.discoveryengine.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a+google/cloud/discoveryengine/v1/chunk.proto\x1a,google/cloud/discoveryengine/v1/common.proto\x1a.google/cloud/discoveryengine/v1/document.proto\x1a\x1cgoogle/protobuf/struct.proto"\xca2\n\rSearchRequest\x12L\n\x0eserving_config\x18\x01 \x01(\tB4\xe0A\x02\xfaA.\n,discoveryengine.googleapis.com/ServingConfig\x12:\n\x06branch\x18\x02 \x01(\tB*\xfaA\'\n%discoveryengine.googleapis.com/Branch\x12\r\n\x05query\x18\x03 \x01(\t\x12N\n\x0bimage_query\x18\x13 \x01(\x0b29.google.cloud.discoveryengine.v1.SearchRequest.ImageQuery\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x12\n\npage_token\x18\x05 \x01(\t\x12\x0e\n\x06offset\x18\x06 \x01(\x05\x12\x19\n\x11one_box_page_size\x18/ \x01(\x05\x12V\n\x10data_store_specs\x18  \x03(\x0b2<.google.cloud.discoveryengine.v1.SearchRequest.DataStoreSpec\x12\x0e\n\x06filter\x18\x07 \x01(\t\x12\x18\n\x10canonical_filter\x18\x1d \x01(\t\x12\x10\n\x08order_by\x18\x08 \x01(\t\x12<\n\tuser_info\x18\x15 \x01(\x0b2).google.cloud.discoveryengine.v1.UserInfo\x12\x15\n\rlanguage_code\x18# \x01(\t\x12M\n\x0bfacet_specs\x18\t \x03(\x0b28.google.cloud.discoveryengine.v1.SearchRequest.FacetSpec\x12L\n\nboost_spec\x18\n \x01(\x0b28.google.cloud.discoveryengine.v1.SearchRequest.BoostSpec\x12J\n\x06params\x18\x0b \x03(\x0b2:.google.cloud.discoveryengine.v1.SearchRequest.ParamsEntry\x12_\n\x14query_expansion_spec\x18\r \x01(\x0b2A.google.cloud.discoveryengine.v1.SearchRequest.QueryExpansionSpec\x12a\n\x15spell_correction_spec\x18\x0e \x01(\x0b2B.google.cloud.discoveryengine.v1.SearchRequest.SpellCorrectionSpec\x12\x16\n\x0euser_pseudo_id\x18\x0f \x01(\t\x12]\n\x13content_search_spec\x18\x18 \x01(\x0b2@.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec\x12\x13\n\x0bsafe_search\x18\x14 \x01(\x08\x12S\n\x0buser_labels\x18\x16 \x03(\x0b2>.google.cloud.discoveryengine.v1.SearchRequest.UserLabelsEntry\x12c\n\x17search_as_you_type_spec\x18\x1f \x01(\x0b2B.google.cloud.discoveryengine.v1.SearchRequest.SearchAsYouTypeSpec\x12U\n\x0cdisplay_spec\x18& \x01(\x0b2:.google.cloud.discoveryengine.v1.SearchRequest.DisplaySpecB\x03\xe0A\x01\x12<\n\x07session\x18) \x01(\tB+\xfaA(\n&discoveryengine.googleapis.com/Session\x12P\n\x0csession_spec\x18* \x01(\x0b2:.google.cloud.discoveryengine.v1.SearchRequest.SessionSpec\x12^\n\x13relevance_threshold\x18, \x01(\x0e2A.google.cloud.discoveryengine.v1.SearchRequest.RelevanceThreshold\x12d\n\x14relevance_score_spec\x184 \x01(\x0b2A.google.cloud.discoveryengine.v1.SearchRequest.RelevanceScoreSpecB\x03\xe0A\x01\x12\x1a\n\x12ranking_expression\x18\x1a \x01(\t\x12p\n\x1aranking_expression_backend\x185 \x01(\x0e2G.google.cloud.discoveryengine.v1.SearchRequest.RankingExpressionBackendB\x03\xe0A\x01\x1a,\n\nImageQuery\x12\x15\n\x0bimage_bytes\x18\x01 \x01(\tH\x00B\x07\n\x05image\x1a\xe3\x01\n\rDataStoreSpec\x12D\n\ndata_store\x18\x01 \x01(\tB0\xe0A\x02\xfaA*\n(discoveryengine.googleapis.com/DataStore\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01\x12Q\n\nboost_spec\x18\x06 \x01(\x0b28.google.cloud.discoveryengine.v1.SearchRequest.BoostSpecB\x03\xe0A\x01\x12$\n\x17custom_search_operators\x18\x07 \x01(\tB\x03\xe0A\x01\x1a\xfc\x02\n\tFacetSpec\x12Y\n\tfacet_key\x18\x01 \x01(\x0b2A.google.cloud.discoveryengine.v1.SearchRequest.FacetSpec.FacetKeyB\x03\xe0A\x02\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x1c\n\x14excluded_filter_keys\x18\x03 \x03(\t\x12\x1f\n\x17enable_dynamic_position\x18\x04 \x01(\x08\x1a\xc5\x01\n\x08FacetKey\x12\x10\n\x03key\x18\x01 \x01(\tB\x03\xe0A\x02\x12<\n\tintervals\x18\x02 \x03(\x0b2).google.cloud.discoveryengine.v1.Interval\x12\x19\n\x11restricted_values\x18\x03 \x03(\t\x12\x10\n\x08prefixes\x18\x04 \x03(\t\x12\x10\n\x08contains\x18\x05 \x03(\t\x12\x18\n\x10case_insensitive\x18\x06 \x01(\x08\x12\x10\n\x08order_by\x18\x07 \x01(\t\x1a\xbc\x07\n\tBoostSpec\x12j\n\x15condition_boost_specs\x18\x01 \x03(\x0b2K.google.cloud.discoveryengine.v1.SearchRequest.BoostSpec.ConditionBoostSpec\x1a\xc2\x06\n\x12ConditionBoostSpec\x12\x11\n\tcondition\x18\x01 \x01(\t\x12\r\n\x05boost\x18\x02 \x01(\x02\x12x\n\x12boost_control_spec\x18\x03 \x01(\x0b2\\.google.cloud.discoveryengine.v1.SearchRequest.BoostSpec.ConditionBoostSpec.BoostControlSpec\x1a\x8f\x05\n\x10BoostControlSpec\x12\x12\n\nfield_name\x18\x01 \x01(\t\x12\x82\x01\n\x0eattribute_type\x18\x02 \x01(\x0e2j.google.cloud.discoveryengine.v1.SearchRequest.BoostSpec.ConditionBoostSpec.BoostControlSpec.AttributeType\x12\x8a\x01\n\x12interpolation_type\x18\x03 \x01(\x0e2n.google.cloud.discoveryengine.v1.SearchRequest.BoostSpec.ConditionBoostSpec.BoostControlSpec.InterpolationType\x12\x81\x01\n\x0econtrol_points\x18\x04 \x03(\x0b2i.google.cloud.discoveryengine.v1.SearchRequest.BoostSpec.ConditionBoostSpec.BoostControlSpec.ControlPoint\x1a=\n\x0cControlPoint\x12\x17\n\x0fattribute_value\x18\x01 \x01(\t\x12\x14\n\x0cboost_amount\x18\x02 \x01(\x02"M\n\rAttributeType\x12\x1e\n\x1aATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\r\n\tNUMERICAL\x10\x01\x12\r\n\tFRESHNESS\x10\x02"C\n\x11InterpolationType\x12"\n\x1eINTERPOLATION_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06LINEAR\x10\x01\x1a\xd4\x01\n\x12QueryExpansionSpec\x12^\n\tcondition\x18\x01 \x01(\x0e2K.google.cloud.discoveryengine.v1.SearchRequest.QueryExpansionSpec.Condition\x12\x1e\n\x16pin_unexpanded_results\x18\x02 \x01(\x08">\n\tCondition\x12\x19\n\x15CONDITION_UNSPECIFIED\x10\x00\x12\x0c\n\x08DISABLED\x10\x01\x12\x08\n\x04AUTO\x10\x02\x1a\xa9\x01\n\x13SpellCorrectionSpec\x12U\n\x04mode\x18\x01 \x01(\x0e2G.google.cloud.discoveryengine.v1.SearchRequest.SpellCorrectionSpec.Mode";\n\x04Mode\x12\x14\n\x10MODE_UNSPECIFIED\x10\x00\x12\x13\n\x0fSUGGESTION_ONLY\x10\x01\x12\x08\n\x04AUTO\x10\x02\x1a\xa2\x0c\n\x11ContentSearchSpec\x12b\n\x0csnippet_spec\x18\x01 \x01(\x0b2L.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.SnippetSpec\x12b\n\x0csummary_spec\x18\x02 \x01(\x0b2L.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.SummarySpec\x12w\n\x17extractive_content_spec\x18\x03 \x01(\x0b2V.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.ExtractiveContentSpec\x12m\n\x12search_result_mode\x18\x04 \x01(\x0e2Q.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.SearchResultMode\x12^\n\nchunk_spec\x18\x05 \x01(\x0b2J.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.ChunkSpec\x1a`\n\x0bSnippetSpec\x12\x1d\n\x11max_snippet_count\x18\x01 \x01(\x05B\x02\x18\x01\x12\x1a\n\x0ereference_only\x18\x02 \x01(\x08B\x02\x18\x01\x12\x16\n\x0ereturn_snippet\x18\x03 \x01(\x08\x1a\xbc\x04\n\x0bSummarySpec\x12\x1c\n\x14summary_result_count\x18\x01 \x01(\x05\x12\x19\n\x11include_citations\x18\x02 \x01(\x08\x12 \n\x18ignore_adversarial_query\x18\x03 \x01(\x08\x12(\n ignore_non_summary_seeking_query\x18\x04 \x01(\x08\x12#\n\x1bignore_low_relevant_content\x18\t \x01(\x08\x12\'\n\x1aignore_jail_breaking_query\x18\n \x01(\x08B\x03\xe0A\x01\x12w\n\x11model_prompt_spec\x18\x05 \x01(\x0b2\\.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.SummarySpec.ModelPromptSpec\x12\x15\n\rlanguage_code\x18\x06 \x01(\t\x12j\n\nmodel_spec\x18\x07 \x01(\x0b2V.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.SummarySpec.ModelSpec\x12\x1b\n\x13use_semantic_chunks\x18\x08 \x01(\x08\x1a#\n\x0fModelPromptSpec\x12\x10\n\x08preamble\x18\x01 \x01(\t\x1a\x1c\n\tModelSpec\x12\x0f\n\x07version\x18\x01 \x01(\t\x1a\xc5\x01\n\x15ExtractiveContentSpec\x12#\n\x1bmax_extractive_answer_count\x18\x01 \x01(\x05\x12$\n\x1cmax_extractive_segment_count\x18\x02 \x01(\x05\x12\'\n\x1freturn_extractive_segment_score\x18\x03 \x01(\x08\x12\x1d\n\x15num_previous_segments\x18\x04 \x01(\x05\x12\x19\n\x11num_next_segments\x18\x05 \x01(\x05\x1aA\n\tChunkSpec\x12\x1b\n\x13num_previous_chunks\x18\x01 \x01(\x05\x12\x17\n\x0fnum_next_chunks\x18\x02 \x01(\x05"Q\n\x10SearchResultMode\x12"\n\x1eSEARCH_RESULT_MODE_UNSPECIFIED\x10\x00\x12\r\n\tDOCUMENTS\x10\x01\x12\n\n\x06CHUNKS\x10\x02\x1a\xc3\x01\n\x13SearchAsYouTypeSpec\x12_\n\tcondition\x18\x01 \x01(\x0e2L.google.cloud.discoveryengine.v1.SearchRequest.SearchAsYouTypeSpec.Condition"K\n\tCondition\x12\x19\n\x15CONDITION_UNSPECIFIED\x10\x00\x12\x0c\n\x08DISABLED\x10\x01\x12\x0b\n\x07ENABLED\x10\x02\x12\x08\n\x04AUTO\x10\x03\x1a\x98\x02\n\x0bDisplaySpec\x12{\n\x1cmatch_highlighting_condition\x18\x01 \x01(\x0e2U.google.cloud.discoveryengine.v1.SearchRequest.DisplaySpec.MatchHighlightingCondition"\x8b\x01\n\x1aMatchHighlightingCondition\x12,\n(MATCH_HIGHLIGHTING_CONDITION_UNSPECIFIED\x10\x00\x12\x1f\n\x1bMATCH_HIGHLIGHTING_DISABLED\x10\x01\x12\x1e\n\x1aMATCH_HIGHLIGHTING_ENABLED\x10\x02\x1aq\n\x0bSessionSpec\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12,\n\x1fsearch_result_persistence_count\x18\x02 \x01(\x05H\x00\x88\x01\x01B"\n _search_result_persistence_count\x1a9\n\x12RelevanceScoreSpec\x12#\n\x16return_relevance_score\x18\x01 \x01(\x08B\x03\xe0A\x01\x1aE\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b2\x16.google.protobuf.Value:\x028\x01\x1a1\n\x0fUserLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"d\n\x12RelevanceThreshold\x12#\n\x1fRELEVANCE_THRESHOLD_UNSPECIFIED\x10\x00\x12\n\n\x06LOWEST\x10\x01\x12\x07\n\x03LOW\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\x08\n\x04HIGH\x10\x04"~\n\x18RankingExpressionBackend\x12*\n&RANKING_EXPRESSION_BACKEND_UNSPECIFIED\x10\x00\x12\x15\n\x11RANK_BY_EMBEDDING\x10\x03\x12\x13\n\x0fRANK_BY_FORMULA\x10\x04"\x04\x08\x01\x10\x01"\x04\x08\x02\x10\x02"\xbe\x1c\n\x0eSearchResponse\x12M\n\x07results\x18\x01 \x03(\x0b2<.google.cloud.discoveryengine.v1.SearchResponse.SearchResult\x12E\n\x06facets\x18\x02 \x03(\x0b25.google.cloud.discoveryengine.v1.SearchResponse.Facet\x12\x12\n\ntotal_size\x18\x03 \x01(\x05\x12\x19\n\x11attribution_token\x18\x04 \x01(\t\x12\x14\n\x0credirect_uri\x18\x0c \x01(\t\x12\x17\n\x0fnext_page_token\x18\x05 \x01(\t\x12\x17\n\x0fcorrected_query\x18\x07 \x01(\t\x12H\n\x07summary\x18\t \x01(\x0b27.google.cloud.discoveryengine.v1.SearchResponse.Summary\x12`\n\x14query_expansion_info\x18\x0e \x01(\x0b2B.google.cloud.discoveryengine.v1.SearchResponse.QueryExpansionInfo\x12Q\n\x0csession_info\x18\x13 \x01(\x0b2;.google.cloud.discoveryengine.v1.SearchResponse.SessionInfo\x12T\n\x16search_link_promotions\x18\x17 \x03(\x0b24.google.cloud.discoveryengine.v1.SearchLinkPromotion\x1a\xaf\x08\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12;\n\x08document\x18\x02 \x01(\x0b2).google.cloud.discoveryengine.v1.Document\x125\n\x05chunk\x18\x12 \x01(\x0b2&.google.cloud.discoveryengine.v1.Chunk\x12h\n\x0cmodel_scores\x18\x04 \x03(\x0b2M.google.cloud.discoveryengine.v1.SearchResponse.SearchResult.ModelScoresEntryB\x03\xe0A\x03\x12c\n\x0crank_signals\x18\x07 \x01(\x0b2H.google.cloud.discoveryengine.v1.SearchResponse.SearchResult.RankSignalsB\x03\xe0A\x01\x1a_\n\x10ModelScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12:\n\x05value\x18\x02 \x01(\x0b2+.google.cloud.discoveryengine.v1.DoubleList:\x028\x01\x1a\xee\x04\n\x0bRankSignals\x12*\n\x18keyword_similarity_score\x18\x01 \x01(\x02B\x03\xe0A\x01H\x00\x88\x01\x01\x12!\n\x0frelevance_score\x18\x02 \x01(\x02B\x03\xe0A\x01H\x01\x88\x01\x01\x12+\n\x19semantic_similarity_score\x18\x03 \x01(\x02B\x03\xe0A\x01H\x02\x88\x01\x01\x12\x1b\n\tpctr_rank\x18\x04 \x01(\x02B\x03\xe0A\x01H\x03\x88\x01\x01\x12!\n\x0ftopicality_rank\x18\x06 \x01(\x02B\x03\xe0A\x01H\x04\x88\x01\x01\x12\x1e\n\x0cdocument_age\x18\x07 \x01(\x02B\x03\xe0A\x01H\x05\x88\x01\x01\x12!\n\x0fboosting_factor\x18\x08 \x01(\x02B\x03\xe0A\x01H\x06\x88\x01\x01\x12\x19\n\x0cdefault_rank\x18  \x01(\x02B\x03\xe0A\x01\x12r\n\x0ecustom_signals\x18! \x03(\x0b2U.google.cloud.discoveryengine.v1.SearchResponse.SearchResult.RankSignals.CustomSignalB\x03\xe0A\x01\x1a5\n\x0cCustomSignal\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05value\x18\x02 \x01(\x02B\x03\xe0A\x01B\x1b\n\x19_keyword_similarity_scoreB\x12\n\x10_relevance_scoreB\x1c\n\x1a_semantic_similarity_scoreB\x0c\n\n_pctr_rankB\x12\n\x10_topicality_rankB\x0f\n\r_document_ageB\x12\n\x10_boosting_factorJ\x04\x08\x05\x10\x06\x1a\xf9\x01\n\x05Facet\x12\x0b\n\x03key\x18\x01 \x01(\t\x12P\n\x06values\x18\x02 \x03(\x0b2@.google.cloud.discoveryengine.v1.SearchResponse.Facet.FacetValue\x12\x15\n\rdynamic_facet\x18\x03 \x01(\x08\x1az\n\nFacetValue\x12\x0f\n\x05value\x18\x01 \x01(\tH\x00\x12=\n\x08interval\x18\x02 \x01(\x0b2).google.cloud.discoveryengine.v1.IntervalH\x00\x12\r\n\x05count\x18\x03 \x01(\x03B\r\n\x0bfacet_value\x1a\xa1\x0c\n\x07Summary\x12\x14\n\x0csummary_text\x18\x01 \x01(\t\x12m\n\x17summary_skipped_reasons\x18\x02 \x03(\x0e2L.google.cloud.discoveryengine.v1.SearchResponse.Summary.SummarySkippedReason\x12c\n\x11safety_attributes\x18\x03 \x01(\x0b2H.google.cloud.discoveryengine.v1.SearchResponse.Summary.SafetyAttributes\x12j\n\x15summary_with_metadata\x18\x04 \x01(\x0b2K.google.cloud.discoveryengine.v1.SearchResponse.Summary.SummaryWithMetadata\x1a6\n\x10SafetyAttributes\x12\x12\n\ncategories\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x1ag\n\x10CitationMetadata\x12S\n\tcitations\x18\x01 \x03(\x0b2@.google.cloud.discoveryengine.v1.SearchResponse.Summary.Citation\x1a\x8b\x01\n\x08Citation\x12\x13\n\x0bstart_index\x18\x01 \x01(\x03\x12\x11\n\tend_index\x18\x02 \x01(\x03\x12W\n\x07sources\x18\x03 \x03(\x0b2F.google.cloud.discoveryengine.v1.SearchResponse.Summary.CitationSource\x1a)\n\x0eCitationSource\x12\x17\n\x0freference_index\x18\x04 \x01(\x03\x1a\x8c\x02\n\tReference\x12\r\n\x05title\x18\x01 \x01(\t\x12A\n\x08document\x18\x02 \x01(\tB/\xe0A\x02\xfaA)\n\'discoveryengine.googleapis.com/Document\x12\x0b\n\x03uri\x18\x03 \x01(\t\x12f\n\x0echunk_contents\x18\x04 \x03(\x0b2N.google.cloud.discoveryengine.v1.SearchResponse.Summary.Reference.ChunkContent\x1a8\n\x0cChunkContent\x12\x0f\n\x07content\x18\x01 \x01(\t\x12\x17\n\x0fpage_identifier\x18\x02 \x01(\t\x1a\xe2\x01\n\x13SummaryWithMetadata\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12c\n\x11citation_metadata\x18\x02 \x01(\x0b2H.google.cloud.discoveryengine.v1.SearchResponse.Summary.CitationMetadata\x12U\n\nreferences\x18\x03 \x03(\x0b2A.google.cloud.discoveryengine.v1.SearchResponse.Summary.Reference"\xf1\x02\n\x14SummarySkippedReason\x12&\n"SUMMARY_SKIPPED_REASON_UNSPECIFIED\x10\x00\x12\x1d\n\x19ADVERSARIAL_QUERY_IGNORED\x10\x01\x12%\n!NON_SUMMARY_SEEKING_QUERY_IGNORED\x10\x02\x12\x1f\n\x1bOUT_OF_DOMAIN_QUERY_IGNORED\x10\x03\x12\x1e\n\x1aPOTENTIAL_POLICY_VIOLATION\x10\x04\x12\x19\n\x15LLM_ADDON_NOT_ENABLED\x10\x05\x12\x17\n\x13NO_RELEVANT_CONTENT\x10\x06\x12\x1f\n\x1bJAIL_BREAKING_QUERY_IGNORED\x10\x07\x12\x1d\n\x19CUSTOMER_POLICY_VIOLATION\x10\x08\x12(\n$NON_SUMMARY_SEEKING_QUERY_IGNORED_V2\x10\t\x12\x0c\n\x08TIME_OUT\x10\n\x1aI\n\x12QueryExpansionInfo\x12\x16\n\x0eexpanded_query\x18\x01 \x01(\x08\x12\x1b\n\x13pinned_result_count\x18\x02 \x01(\x03\x1a-\n\x0bSessionInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08query_id\x18\x02 \x01(\t2\x97\x07\n\rSearchService\x12\x8f\x03\n\x06Search\x12..google.cloud.discoveryengine.v1.SearchRequest\x1a/.google.cloud.discoveryengine.v1.SearchResponse"\xa3\x02\x82\xd3\xe4\x93\x02\x9c\x02"P/v1/{serving_config=projects/*/locations/*/dataStores/*/servingConfigs/*}:search:\x01*Zc"^/v1/{serving_config=projects/*/locations/*/collections/*/dataStores/*/servingConfigs/*}:search:\x01*Z`"[/v1/{serving_config=projects/*/locations/*/collections/*/engines/*/servingConfigs/*}:search:\x01*\x12\x9f\x03\n\nSearchLite\x12..google.cloud.discoveryengine.v1.SearchRequest\x1a/.google.cloud.discoveryengine.v1.SearchResponse"\xaf\x02\x82\xd3\xe4\x93\x02\xa8\x02"T/v1/{serving_config=projects/*/locations/*/dataStores/*/servingConfigs/*}:searchLite:\x01*Zg"b/v1/{serving_config=projects/*/locations/*/collections/*/dataStores/*/servingConfigs/*}:searchLite:\x01*Zd"_/v1/{serving_config=projects/*/locations/*/collections/*/engines/*/servingConfigs/*}:searchLite:\x01*\x1aR\xcaA\x1ediscoveryengine.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\x85\x02\n#com.google.cloud.discoveryengine.v1B\x12SearchServiceProtoP\x01ZMcloud.google.com/go/discoveryengine/apiv1/discoveryenginepb;discoveryenginepb\xa2\x02\x0fDISCOVERYENGINE\xaa\x02\x1fGoogle.Cloud.DiscoveryEngine.V1\xca\x02\x1fGoogle\\Cloud\\DiscoveryEngine\\V1\xea\x02"Google::Cloud::DiscoveryEngine::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.discoveryengine.v1.search_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n#com.google.cloud.discoveryengine.v1B\x12SearchServiceProtoP\x01ZMcloud.google.com/go/discoveryengine/apiv1/discoveryenginepb;discoveryenginepb\xa2\x02\x0fDISCOVERYENGINE\xaa\x02\x1fGoogle.Cloud.DiscoveryEngine.V1\xca\x02\x1fGoogle\\Cloud\\DiscoveryEngine\\V1\xea\x02"Google::Cloud::DiscoveryEngine::V1'
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['data_store']._loaded_options = None
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['data_store']._serialized_options = b'\xe0A\x02\xfaA*\n(discoveryengine.googleapis.com/DataStore'
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['filter']._loaded_options = None
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['boost_spec']._loaded_options = None
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['boost_spec']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['custom_search_operators']._loaded_options = None
    _globals['_SEARCHREQUEST_DATASTORESPEC'].fields_by_name['custom_search_operators']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHREQUEST_FACETSPEC_FACETKEY'].fields_by_name['key']._loaded_options = None
    _globals['_SEARCHREQUEST_FACETSPEC_FACETKEY'].fields_by_name['key']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHREQUEST_FACETSPEC'].fields_by_name['facet_key']._loaded_options = None
    _globals['_SEARCHREQUEST_FACETSPEC'].fields_by_name['facet_key']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SNIPPETSPEC'].fields_by_name['max_snippet_count']._loaded_options = None
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SNIPPETSPEC'].fields_by_name['max_snippet_count']._serialized_options = b'\x18\x01'
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SNIPPETSPEC'].fields_by_name['reference_only']._loaded_options = None
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SNIPPETSPEC'].fields_by_name['reference_only']._serialized_options = b'\x18\x01'
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC'].fields_by_name['ignore_jail_breaking_query']._loaded_options = None
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC'].fields_by_name['ignore_jail_breaking_query']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHREQUEST_RELEVANCESCORESPEC'].fields_by_name['return_relevance_score']._loaded_options = None
    _globals['_SEARCHREQUEST_RELEVANCESCORESPEC'].fields_by_name['return_relevance_score']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHREQUEST_PARAMSENTRY']._loaded_options = None
    _globals['_SEARCHREQUEST_PARAMSENTRY']._serialized_options = b'8\x01'
    _globals['_SEARCHREQUEST_USERLABELSENTRY']._loaded_options = None
    _globals['_SEARCHREQUEST_USERLABELSENTRY']._serialized_options = b'8\x01'
    _globals['_SEARCHREQUEST'].fields_by_name['serving_config']._loaded_options = None
    _globals['_SEARCHREQUEST'].fields_by_name['serving_config']._serialized_options = b'\xe0A\x02\xfaA.\n,discoveryengine.googleapis.com/ServingConfig'
    _globals['_SEARCHREQUEST'].fields_by_name['branch']._loaded_options = None
    _globals['_SEARCHREQUEST'].fields_by_name['branch']._serialized_options = b"\xfaA'\n%discoveryengine.googleapis.com/Branch"
    _globals['_SEARCHREQUEST'].fields_by_name['display_spec']._loaded_options = None
    _globals['_SEARCHREQUEST'].fields_by_name['display_spec']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHREQUEST'].fields_by_name['session']._loaded_options = None
    _globals['_SEARCHREQUEST'].fields_by_name['session']._serialized_options = b'\xfaA(\n&discoveryengine.googleapis.com/Session'
    _globals['_SEARCHREQUEST'].fields_by_name['relevance_score_spec']._loaded_options = None
    _globals['_SEARCHREQUEST'].fields_by_name['relevance_score_spec']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHREQUEST'].fields_by_name['ranking_expression_backend']._loaded_options = None
    _globals['_SEARCHREQUEST'].fields_by_name['ranking_expression_backend']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_MODELSCORESENTRY']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_MODELSCORESENTRY']._serialized_options = b'8\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS_CUSTOMSIGNAL'].fields_by_name['name']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS_CUSTOMSIGNAL'].fields_by_name['name']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS_CUSTOMSIGNAL'].fields_by_name['value']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS_CUSTOMSIGNAL'].fields_by_name['value']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['keyword_similarity_score']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['keyword_similarity_score']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['relevance_score']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['relevance_score']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['semantic_similarity_score']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['semantic_similarity_score']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['pctr_rank']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['pctr_rank']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['topicality_rank']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['topicality_rank']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['document_age']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['document_age']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['boosting_factor']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['boosting_factor']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['default_rank']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['default_rank']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['custom_signals']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS'].fields_by_name['custom_signals']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SEARCHRESULT'].fields_by_name['model_scores']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT'].fields_by_name['model_scores']._serialized_options = b'\xe0A\x03'
    _globals['_SEARCHRESPONSE_SEARCHRESULT'].fields_by_name['rank_signals']._loaded_options = None
    _globals['_SEARCHRESPONSE_SEARCHRESULT'].fields_by_name['rank_signals']._serialized_options = b'\xe0A\x01'
    _globals['_SEARCHRESPONSE_SUMMARY_REFERENCE'].fields_by_name['document']._loaded_options = None
    _globals['_SEARCHRESPONSE_SUMMARY_REFERENCE'].fields_by_name['document']._serialized_options = b"\xe0A\x02\xfaA)\n'discoveryengine.googleapis.com/Document"
    _globals['_SEARCHSERVICE']._loaded_options = None
    _globals['_SEARCHSERVICE']._serialized_options = b'\xcaA\x1ediscoveryengine.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_SEARCHSERVICE'].methods_by_name['Search']._loaded_options = None
    _globals['_SEARCHSERVICE'].methods_by_name['Search']._serialized_options = b'\x82\xd3\xe4\x93\x02\x9c\x02"P/v1/{serving_config=projects/*/locations/*/dataStores/*/servingConfigs/*}:search:\x01*Zc"^/v1/{serving_config=projects/*/locations/*/collections/*/dataStores/*/servingConfigs/*}:search:\x01*Z`"[/v1/{serving_config=projects/*/locations/*/collections/*/engines/*/servingConfigs/*}:search:\x01*'
    _globals['_SEARCHSERVICE'].methods_by_name['SearchLite']._loaded_options = None
    _globals['_SEARCHSERVICE'].methods_by_name['SearchLite']._serialized_options = b'\x82\xd3\xe4\x93\x02\xa8\x02"T/v1/{serving_config=projects/*/locations/*/dataStores/*/servingConfigs/*}:searchLite:\x01*Zg"b/v1/{serving_config=projects/*/locations/*/collections/*/dataStores/*/servingConfigs/*}:searchLite:\x01*Zd"_/v1/{serving_config=projects/*/locations/*/collections/*/engines/*/servingConfigs/*}:searchLite:\x01*'
    _globals['_SEARCHREQUEST']._serialized_start = 374
    _globals['_SEARCHREQUEST']._serialized_end = 6848
    _globals['_SEARCHREQUEST_IMAGEQUERY']._serialized_start = 2265
    _globals['_SEARCHREQUEST_IMAGEQUERY']._serialized_end = 2309
    _globals['_SEARCHREQUEST_DATASTORESPEC']._serialized_start = 2312
    _globals['_SEARCHREQUEST_DATASTORESPEC']._serialized_end = 2539
    _globals['_SEARCHREQUEST_FACETSPEC']._serialized_start = 2542
    _globals['_SEARCHREQUEST_FACETSPEC']._serialized_end = 2922
    _globals['_SEARCHREQUEST_FACETSPEC_FACETKEY']._serialized_start = 2725
    _globals['_SEARCHREQUEST_FACETSPEC_FACETKEY']._serialized_end = 2922
    _globals['_SEARCHREQUEST_BOOSTSPEC']._serialized_start = 2925
    _globals['_SEARCHREQUEST_BOOSTSPEC']._serialized_end = 3881
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC']._serialized_start = 3047
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC']._serialized_end = 3881
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC']._serialized_start = 3226
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC']._serialized_end = 3881
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC_CONTROLPOINT']._serialized_start = 3672
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC_CONTROLPOINT']._serialized_end = 3733
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC_ATTRIBUTETYPE']._serialized_start = 3735
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC_ATTRIBUTETYPE']._serialized_end = 3812
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC_INTERPOLATIONTYPE']._serialized_start = 3814
    _globals['_SEARCHREQUEST_BOOSTSPEC_CONDITIONBOOSTSPEC_BOOSTCONTROLSPEC_INTERPOLATIONTYPE']._serialized_end = 3881
    _globals['_SEARCHREQUEST_QUERYEXPANSIONSPEC']._serialized_start = 3884
    _globals['_SEARCHREQUEST_QUERYEXPANSIONSPEC']._serialized_end = 4096
    _globals['_SEARCHREQUEST_QUERYEXPANSIONSPEC_CONDITION']._serialized_start = 4034
    _globals['_SEARCHREQUEST_QUERYEXPANSIONSPEC_CONDITION']._serialized_end = 4096
    _globals['_SEARCHREQUEST_SPELLCORRECTIONSPEC']._serialized_start = 4099
    _globals['_SEARCHREQUEST_SPELLCORRECTIONSPEC']._serialized_end = 4268
    _globals['_SEARCHREQUEST_SPELLCORRECTIONSPEC_MODE']._serialized_start = 4209
    _globals['_SEARCHREQUEST_SPELLCORRECTIONSPEC_MODE']._serialized_end = 4268
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC']._serialized_start = 4271
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC']._serialized_end = 5841
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SNIPPETSPEC']._serialized_start = 4820
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SNIPPETSPEC']._serialized_end = 4916
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC']._serialized_start = 4919
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC']._serialized_end = 5491
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC_MODELPROMPTSPEC']._serialized_start = 5426
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC_MODELPROMPTSPEC']._serialized_end = 5461
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC_MODELSPEC']._serialized_start = 5463
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SUMMARYSPEC_MODELSPEC']._serialized_end = 5491
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_EXTRACTIVECONTENTSPEC']._serialized_start = 5494
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_EXTRACTIVECONTENTSPEC']._serialized_end = 5691
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_CHUNKSPEC']._serialized_start = 5693
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_CHUNKSPEC']._serialized_end = 5758
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SEARCHRESULTMODE']._serialized_start = 5760
    _globals['_SEARCHREQUEST_CONTENTSEARCHSPEC_SEARCHRESULTMODE']._serialized_end = 5841
    _globals['_SEARCHREQUEST_SEARCHASYOUTYPESPEC']._serialized_start = 5844
    _globals['_SEARCHREQUEST_SEARCHASYOUTYPESPEC']._serialized_end = 6039
    _globals['_SEARCHREQUEST_SEARCHASYOUTYPESPEC_CONDITION']._serialized_start = 5964
    _globals['_SEARCHREQUEST_SEARCHASYOUTYPESPEC_CONDITION']._serialized_end = 6039
    _globals['_SEARCHREQUEST_DISPLAYSPEC']._serialized_start = 6042
    _globals['_SEARCHREQUEST_DISPLAYSPEC']._serialized_end = 6322
    _globals['_SEARCHREQUEST_DISPLAYSPEC_MATCHHIGHLIGHTINGCONDITION']._serialized_start = 6183
    _globals['_SEARCHREQUEST_DISPLAYSPEC_MATCHHIGHLIGHTINGCONDITION']._serialized_end = 6322
    _globals['_SEARCHREQUEST_SESSIONSPEC']._serialized_start = 6324
    _globals['_SEARCHREQUEST_SESSIONSPEC']._serialized_end = 6437
    _globals['_SEARCHREQUEST_RELEVANCESCORESPEC']._serialized_start = 6439
    _globals['_SEARCHREQUEST_RELEVANCESCORESPEC']._serialized_end = 6496
    _globals['_SEARCHREQUEST_PARAMSENTRY']._serialized_start = 6498
    _globals['_SEARCHREQUEST_PARAMSENTRY']._serialized_end = 6567
    _globals['_SEARCHREQUEST_USERLABELSENTRY']._serialized_start = 6569
    _globals['_SEARCHREQUEST_USERLABELSENTRY']._serialized_end = 6618
    _globals['_SEARCHREQUEST_RELEVANCETHRESHOLD']._serialized_start = 6620
    _globals['_SEARCHREQUEST_RELEVANCETHRESHOLD']._serialized_end = 6720
    _globals['_SEARCHREQUEST_RANKINGEXPRESSIONBACKEND']._serialized_start = 6722
    _globals['_SEARCHREQUEST_RANKINGEXPRESSIONBACKEND']._serialized_end = 6848
    _globals['_SEARCHRESPONSE']._serialized_start = 6851
    _globals['_SEARCHRESPONSE']._serialized_end = 10497
    _globals['_SEARCHRESPONSE_SEARCHRESULT']._serialized_start = 7480
    _globals['_SEARCHRESPONSE_SEARCHRESULT']._serialized_end = 8551
    _globals['_SEARCHRESPONSE_SEARCHRESULT_MODELSCORESENTRY']._serialized_start = 7831
    _globals['_SEARCHRESPONSE_SEARCHRESULT_MODELSCORESENTRY']._serialized_end = 7926
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS']._serialized_start = 7929
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS']._serialized_end = 8551
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS_CUSTOMSIGNAL']._serialized_start = 8342
    _globals['_SEARCHRESPONSE_SEARCHRESULT_RANKSIGNALS_CUSTOMSIGNAL']._serialized_end = 8395
    _globals['_SEARCHRESPONSE_FACET']._serialized_start = 8554
    _globals['_SEARCHRESPONSE_FACET']._serialized_end = 8803
    _globals['_SEARCHRESPONSE_FACET_FACETVALUE']._serialized_start = 8681
    _globals['_SEARCHRESPONSE_FACET_FACETVALUE']._serialized_end = 8803
    _globals['_SEARCHRESPONSE_SUMMARY']._serialized_start = 8806
    _globals['_SEARCHRESPONSE_SUMMARY']._serialized_end = 10375
    _globals['_SEARCHRESPONSE_SUMMARY_SAFETYATTRIBUTES']._serialized_start = 9159
    _globals['_SEARCHRESPONSE_SUMMARY_SAFETYATTRIBUTES']._serialized_end = 9213
    _globals['_SEARCHRESPONSE_SUMMARY_CITATIONMETADATA']._serialized_start = 9215
    _globals['_SEARCHRESPONSE_SUMMARY_CITATIONMETADATA']._serialized_end = 9318
    _globals['_SEARCHRESPONSE_SUMMARY_CITATION']._serialized_start = 9321
    _globals['_SEARCHRESPONSE_SUMMARY_CITATION']._serialized_end = 9460
    _globals['_SEARCHRESPONSE_SUMMARY_CITATIONSOURCE']._serialized_start = 9462
    _globals['_SEARCHRESPONSE_SUMMARY_CITATIONSOURCE']._serialized_end = 9503
    _globals['_SEARCHRESPONSE_SUMMARY_REFERENCE']._serialized_start = 9506
    _globals['_SEARCHRESPONSE_SUMMARY_REFERENCE']._serialized_end = 9774
    _globals['_SEARCHRESPONSE_SUMMARY_REFERENCE_CHUNKCONTENT']._serialized_start = 9718
    _globals['_SEARCHRESPONSE_SUMMARY_REFERENCE_CHUNKCONTENT']._serialized_end = 9774
    _globals['_SEARCHRESPONSE_SUMMARY_SUMMARYWITHMETADATA']._serialized_start = 9777
    _globals['_SEARCHRESPONSE_SUMMARY_SUMMARYWITHMETADATA']._serialized_end = 10003
    _globals['_SEARCHRESPONSE_SUMMARY_SUMMARYSKIPPEDREASON']._serialized_start = 10006
    _globals['_SEARCHRESPONSE_SUMMARY_SUMMARYSKIPPEDREASON']._serialized_end = 10375
    _globals['_SEARCHRESPONSE_QUERYEXPANSIONINFO']._serialized_start = 10377
    _globals['_SEARCHRESPONSE_QUERYEXPANSIONINFO']._serialized_end = 10450
    _globals['_SEARCHRESPONSE_SESSIONINFO']._serialized_start = 10452
    _globals['_SEARCHRESPONSE_SESSIONINFO']._serialized_end = 10497
    _globals['_SEARCHSERVICE']._serialized_start = 10500
    _globals['_SEARCHSERVICE']._serialized_end = 11419