"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/discoveryengine/v1/session_service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.discoveryengine.v1 import conversational_search_service_pb2 as google_dot_cloud_dot_discoveryengine_dot_v1_dot_conversational__search__service__pb2
from .....google.cloud.discoveryengine.v1 import session_pb2 as google_dot_cloud_dot_discoveryengine_dot_v1_dot_session__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5google/cloud/discoveryengine/v1/session_service.proto\x12\x1fgoogle.cloud.discoveryengine.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1aCgoogle/cloud/discoveryengine/v1/conversational_search_service.proto\x1a-google/cloud/discoveryengine/v1/session.proto\x1a\x1bgoogle/protobuf/empty.proto2\xda\x0e\n\x0eSessionService\x12\xf4\x02\n\rCreateSession\x125.google.cloud.discoveryengine.v1.CreateSessionRequest\x1a(.google.cloud.discoveryengine.v1.Session"\x81\x02\xdaA\x0eparent,session\x82\xd3\xe4\x93\x02\xe9\x01"9/v1/{parent=projects/*/locations/*/dataStores/*}/sessions:\x07sessionZR"G/v1/{parent=projects/*/locations/*/collections/*/dataStores/*}/sessions:\x07sessionZO"D/v1/{parent=projects/*/locations/*/collections/*/engines/*}/sessions:\x07session\x12\xbd\x02\n\rDeleteSession\x125.google.cloud.discoveryengine.v1.DeleteSessionRequest\x1a\x16.google.protobuf.Empty"\xdc\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\xce\x01*9/v1/{name=projects/*/locations/*/dataStores/*/sessions/*}ZI*G/v1/{name=projects/*/locations/*/collections/*/dataStores/*/sessions/*}ZF*D/v1/{name=projects/*/locations/*/collections/*/engines/*/sessions/*}\x12\x91\x03\n\rUpdateSession\x125.google.cloud.discoveryengine.v1.UpdateSessionRequest\x1a(.google.cloud.discoveryengine.v1.Session"\x9e\x02\xdaA\x13session,update_mask\x82\xd3\xe4\x93\x02\x81\x022A/v1/{session.name=projects/*/locations/*/dataStores/*/sessions/*}:\x07sessionZZ2O/v1/{session.name=projects/*/locations/*/collections/*/dataStores/*/sessions/*}:\x07sessionZW2L/v1/{session.name=projects/*/locations/*/collections/*/engines/*/sessions/*}:\x07session\x12\xc9\x02\n\nGetSession\x122.google.cloud.discoveryengine.v1.GetSessionRequest\x1a(.google.cloud.discoveryengine.v1.Session"\xdc\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\xce\x01\x129/v1/{name=projects/*/locations/*/dataStores/*/sessions/*}ZI\x12G/v1/{name=projects/*/locations/*/collections/*/dataStores/*/sessions/*}ZF\x12D/v1/{name=projects/*/locations/*/collections/*/engines/*/sessions/*}\x12\xdc\x02\n\x0cListSessions\x124.google.cloud.discoveryengine.v1.ListSessionsRequest\x1a5.google.cloud.discoveryengine.v1.ListSessionsResponse"\xde\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02\xce\x01\x129/v1/{parent=projects/*/locations/*/dataStores/*}/sessionsZI\x12G/v1/{parent=projects/*/locations/*/collections/*/dataStores/*}/sessionsZF\x12D/v1/{parent=projects/*/locations/*/collections/*/engines/*}/sessions\x1aR\xcaA\x1ediscoveryengine.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\x86\x02\n#com.google.cloud.discoveryengine.v1B\x13SessionServiceProtoP\x01ZMcloud.google.com/go/discoveryengine/apiv1/discoveryenginepb;discoveryenginepb\xa2\x02\x0fDISCOVERYENGINE\xaa\x02\x1fGoogle.Cloud.DiscoveryEngine.V1\xca\x02\x1fGoogle\\Cloud\\DiscoveryEngine\\V1\xea\x02"Google::Cloud::DiscoveryEngine::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.discoveryengine.v1.session_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n#com.google.cloud.discoveryengine.v1B\x13SessionServiceProtoP\x01ZMcloud.google.com/go/discoveryengine/apiv1/discoveryenginepb;discoveryenginepb\xa2\x02\x0fDISCOVERYENGINE\xaa\x02\x1fGoogle.Cloud.DiscoveryEngine.V1\xca\x02\x1fGoogle\\Cloud\\DiscoveryEngine\\V1\xea\x02"Google::Cloud::DiscoveryEngine::V1'
    _globals['_SESSIONSERVICE']._loaded_options = None
    _globals['_SESSIONSERVICE']._serialized_options = b'\xcaA\x1ediscoveryengine.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_SESSIONSERVICE'].methods_by_name['CreateSession']._loaded_options = None
    _globals['_SESSIONSERVICE'].methods_by_name['CreateSession']._serialized_options = b'\xdaA\x0eparent,session\x82\xd3\xe4\x93\x02\xe9\x01"9/v1/{parent=projects/*/locations/*/dataStores/*}/sessions:\x07sessionZR"G/v1/{parent=projects/*/locations/*/collections/*/dataStores/*}/sessions:\x07sessionZO"D/v1/{parent=projects/*/locations/*/collections/*/engines/*}/sessions:\x07session'
    _globals['_SESSIONSERVICE'].methods_by_name['DeleteSession']._loaded_options = None
    _globals['_SESSIONSERVICE'].methods_by_name['DeleteSession']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\xce\x01*9/v1/{name=projects/*/locations/*/dataStores/*/sessions/*}ZI*G/v1/{name=projects/*/locations/*/collections/*/dataStores/*/sessions/*}ZF*D/v1/{name=projects/*/locations/*/collections/*/engines/*/sessions/*}'
    _globals['_SESSIONSERVICE'].methods_by_name['UpdateSession']._loaded_options = None
    _globals['_SESSIONSERVICE'].methods_by_name['UpdateSession']._serialized_options = b'\xdaA\x13session,update_mask\x82\xd3\xe4\x93\x02\x81\x022A/v1/{session.name=projects/*/locations/*/dataStores/*/sessions/*}:\x07sessionZZ2O/v1/{session.name=projects/*/locations/*/collections/*/dataStores/*/sessions/*}:\x07sessionZW2L/v1/{session.name=projects/*/locations/*/collections/*/engines/*/sessions/*}:\x07session'
    _globals['_SESSIONSERVICE'].methods_by_name['GetSession']._loaded_options = None
    _globals['_SESSIONSERVICE'].methods_by_name['GetSession']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\xce\x01\x129/v1/{name=projects/*/locations/*/dataStores/*/sessions/*}ZI\x12G/v1/{name=projects/*/locations/*/collections/*/dataStores/*/sessions/*}ZF\x12D/v1/{name=projects/*/locations/*/collections/*/engines/*/sessions/*}'
    _globals['_SESSIONSERVICE'].methods_by_name['ListSessions']._loaded_options = None
    _globals['_SESSIONSERVICE'].methods_by_name['ListSessions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02\xce\x01\x129/v1/{parent=projects/*/locations/*/dataStores/*}/sessionsZI\x12G/v1/{parent=projects/*/locations/*/collections/*/dataStores/*}/sessionsZF\x12D/v1/{parent=projects/*/locations/*/collections/*/engines/*}/sessions'
    _globals['_SESSIONSERVICE']._serialized_start = 351
    _globals['_SESSIONSERVICE']._serialized_end = 2233