"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/edgenetwork/v1/service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.edgenetwork.v1 import resources_pb2 as google_dot_cloud_dot_edgenetwork_dot_v1_dot_resources__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)google/cloud/edgenetwork/v1/service.proto\x12\x1bgoogle.cloud.edgenetwork.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a+google/cloud/edgenetwork/v1/resources.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x98\x01\n\x10ListZonesRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1fedgenetwork.googleapis.com/Zone\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t:\x02\x18\x01"w\n\x11ListZonesResponse\x120\n\x05zones\x18\x01 \x03(\x0b2!.google.cloud.edgenetwork.v1.Zone\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t:\x02\x18\x01"K\n\x0eGetZoneRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fedgenetwork.googleapis.com/Zone:\x02\x18\x01"\x9a\x01\n\x13ListNetworksRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"edgenetwork.googleapis.com/Network\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"|\n\x14ListNetworksResponse\x126\n\x08networks\x18\x01 \x03(\x0b2$.google.cloud.edgenetwork.v1.Network\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"M\n\x11GetNetworkRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"edgenetwork.googleapis.com/Network"\xc0\x01\n\x14CreateNetworkRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"edgenetwork.googleapis.com/Network\x12\x17\n\nnetwork_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12:\n\x07network\x18\x03 \x01(\x0b2$.google.cloud.edgenetwork.v1.NetworkB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01"i\n\x14DeleteNetworkRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"edgenetwork.googleapis.com/Network\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\x98\x01\n\x12ListSubnetsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Subnet\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"y\n\x13ListSubnetsResponse\x124\n\x07subnets\x18\x01 \x03(\x0b2#.google.cloud.edgenetwork.v1.Subnet\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"K\n\x10GetSubnetRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Subnet"\xbb\x01\n\x13CreateSubnetRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Subnet\x12\x16\n\tsubnet_id\x18\x02 \x01(\tB\x03\xe0A\x02\x128\n\x06subnet\x18\x03 \x01(\x0b2#.google.cloud.edgenetwork.v1.SubnetB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01"\x9e\x01\n\x13UpdateSubnetRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x128\n\x06subnet\x18\x02 \x01(\x0b2#.google.cloud.edgenetwork.v1.SubnetB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"g\n\x13DeleteSubnetRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Subnet\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\xa4\x01\n\x18ListInterconnectsRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\x12\'edgenetwork.googleapis.com/Interconnect\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"\x8b\x01\n\x19ListInterconnectsResponse\x12@\n\rinterconnects\x18\x01 \x03(\x0b2).google.cloud.edgenetwork.v1.Interconnect\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"W\n\x16GetInterconnectRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'edgenetwork.googleapis.com/Interconnect"\xb8\x01\n"ListInterconnectAttachmentsRequest\x12I\n\x06parent\x18\x01 \x01(\tB9\xe0A\x02\xfaA3\x121edgenetwork.googleapis.com/InterconnectAttachment\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"\xaa\x01\n#ListInterconnectAttachmentsResponse\x12U\n\x18interconnect_attachments\x18\x01 \x03(\x0b23.google.cloud.edgenetwork.v1.InterconnectAttachment\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"k\n GetInterconnectAttachmentRequest\x12G\n\x04name\x18\x01 \x01(\tB9\xe0A\x02\xfaA3\n1edgenetwork.googleapis.com/InterconnectAttachment"\x8d\x02\n#CreateInterconnectAttachmentRequest\x12I\n\x06parent\x18\x01 \x01(\tB9\xe0A\x02\xfaA3\x121edgenetwork.googleapis.com/InterconnectAttachment\x12\'\n\x1ainterconnect_attachment_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12Y\n\x17interconnect_attachment\x18\x03 \x01(\x0b23.google.cloud.edgenetwork.v1.InterconnectAttachmentB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01"\x87\x01\n#DeleteInterconnectAttachmentRequest\x12G\n\x04name\x18\x01 \x01(\tB9\xe0A\x02\xfaA3\n1edgenetwork.googleapis.com/InterconnectAttachment\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\x98\x01\n\x12ListRoutersRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Router\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"y\n\x13ListRoutersResponse\x124\n\x07routers\x18\x01 \x03(\x0b2#.google.cloud.edgenetwork.v1.Router\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"K\n\x10GetRouterRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Router"\xbb\x01\n\x13CreateRouterRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Router\x12\x16\n\trouter_id\x18\x02 \x01(\tB\x03\xe0A\x02\x128\n\x06router\x18\x03 \x01(\x0b2#.google.cloud.edgenetwork.v1.RouterB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01"\x9e\x01\n\x13UpdateRouterRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x128\n\x06router\x18\x02 \x01(\x0b2#.google.cloud.edgenetwork.v1.RouterB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"g\n\x13DeleteRouterRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Router\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\x80\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x03"R\n\x16DiagnoseNetworkRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"edgenetwork.googleapis.com/Network"\xb2\x03\n\x17DiagnoseNetworkResponse\x12/\n\x0bupdate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12R\n\x06result\x18\x02 \x01(\x0b2B.google.cloud.edgenetwork.v1.DiagnoseNetworkResponse.NetworkStatus\x1a\x91\x02\n\rNetworkStatus\x12@\n\rsubnet_status\x18\x01 \x03(\x0b2).google.cloud.edgenetwork.v1.SubnetStatus\x12u\n\x1cmacsec_status_internal_links\x18\x02 \x01(\x0e2O.google.cloud.edgenetwork.v1.DiagnoseNetworkResponse.NetworkStatus.MacsecStatus"G\n\x0cMacsecStatus\x12\x1d\n\x19MACSEC_STATUS_UNSPECIFIED\x10\x00\x12\n\n\x06SECURE\x10\x01\x12\x0c\n\x08UNSECURE\x10\x02"\\\n\x1bDiagnoseInterconnectRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'edgenetwork.googleapis.com/Interconnect"\x95\x01\n\x1cDiagnoseInterconnectResponse\x12/\n\x0bupdate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12D\n\x06result\x18\x02 \x01(\x0b24.google.cloud.edgenetwork.v1.InterconnectDiagnostics"P\n\x15DiagnoseRouterRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Router"\x84\x01\n\x16DiagnoseRouterResponse\x12/\n\x0bupdate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x129\n\x06result\x18\x02 \x01(\x0b2).google.cloud.edgenetwork.v1.RouterStatus"N\n\x15InitializeZoneRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fedgenetwork.googleapis.com/Zone"\x18\n\x16InitializeZoneResponse2\xa9+\n\x0bEdgeNetwork\x12\xc1\x01\n\x0eInitializeZone\x122.google.cloud.edgenetwork.v1.InitializeZoneRequest\x1a3.google.cloud.edgenetwork.v1.InitializeZoneResponse"F\xdaA\x04name\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/zones/*}:initialize:\x01*\x12\xa9\x01\n\tListZones\x12-.google.cloud.edgenetwork.v1.ListZonesRequest\x1a..google.cloud.edgenetwork.v1.ListZonesResponse"=\x88\x02\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02+\x12)/v1/{parent=projects/*/locations/*}/zones\x12\x96\x01\n\x07GetZone\x12+.google.cloud.edgenetwork.v1.GetZoneRequest\x1a!.google.cloud.edgenetwork.v1.Zone";\x88\x02\x01\xdaA\x04name\x82\xd3\xe4\x93\x02+\x12)/v1/{name=projects/*/locations/*/zones/*}\x12\xba\x01\n\x0cListNetworks\x120.google.cloud.edgenetwork.v1.ListNetworksRequest\x1a1.google.cloud.edgenetwork.v1.ListNetworksResponse"E\xdaA\x06parent\x82\xd3\xe4\x93\x026\x124/v1/{parent=projects/*/locations/*/zones/*}/networks\x12\xa7\x01\n\nGetNetwork\x12..google.cloud.edgenetwork.v1.GetNetworkRequest\x1a$.google.cloud.edgenetwork.v1.Network"C\xdaA\x04name\x82\xd3\xe4\x93\x026\x124/v1/{name=projects/*/locations/*/zones/*/networks/*}\x12\xca\x01\n\x0fDiagnoseNetwork\x123.google.cloud.edgenetwork.v1.DiagnoseNetworkRequest\x1a4.google.cloud.edgenetwork.v1.DiagnoseNetworkResponse"L\xdaA\x04name\x82\xd3\xe4\x93\x02?\x12=/v1/{name=projects/*/locations/*/zones/*/networks/*}:diagnose\x12\xe4\x01\n\rCreateNetwork\x121.google.cloud.edgenetwork.v1.CreateNetworkRequest\x1a\x1d.google.longrunning.Operation"\x80\x01\xcaA\x1c\n\x07Network\x12\x11OperationMetadata\xdaA\x19parent,network,network_id\x82\xd3\xe4\x93\x02?"4/v1/{parent=projects/*/locations/*/zones/*}/networks:\x07network\x12\xd3\x01\n\rDeleteNetwork\x121.google.cloud.edgenetwork.v1.DeleteNetworkRequest\x1a\x1d.google.longrunning.Operation"p\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x026*4/v1/{name=projects/*/locations/*/zones/*/networks/*}\x12\xb6\x01\n\x0bListSubnets\x12/.google.cloud.edgenetwork.v1.ListSubnetsRequest\x1a0.google.cloud.edgenetwork.v1.ListSubnetsResponse"D\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*/zones/*}/subnets\x12\xa3\x01\n\tGetSubnet\x12-.google.cloud.edgenetwork.v1.GetSubnetRequest\x1a#.google.cloud.edgenetwork.v1.Subnet"B\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/zones/*/subnets/*}\x12\xdc\x01\n\x0cCreateSubnet\x120.google.cloud.edgenetwork.v1.CreateSubnetRequest\x1a\x1d.google.longrunning.Operation"{\xcaA\x1b\n\x06Subnet\x12\x11OperationMetadata\xdaA\x17parent,subnet,subnet_id\x82\xd3\xe4\x93\x02="3/v1/{parent=projects/*/locations/*/zones/*}/subnets:\x06subnet\x12\xde\x01\n\x0cUpdateSubnet\x120.google.cloud.edgenetwork.v1.UpdateSubnetRequest\x1a\x1d.google.longrunning.Operation"}\xcaA\x1b\n\x06Subnet\x12\x11OperationMetadata\xdaA\x12subnet,update_mask\x82\xd3\xe4\x93\x02D2:/v1/{subnet.name=projects/*/locations/*/zones/*/subnets/*}:\x06subnet\x12\xd0\x01\n\x0cDeleteSubnet\x120.google.cloud.edgenetwork.v1.DeleteSubnetRequest\x1a\x1d.google.longrunning.Operation"o\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/zones/*/subnets/*}\x12\xce\x01\n\x11ListInterconnects\x125.google.cloud.edgenetwork.v1.ListInterconnectsRequest\x1a6.google.cloud.edgenetwork.v1.ListInterconnectsResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/zones/*}/interconnects\x12\xbb\x01\n\x0fGetInterconnect\x123.google.cloud.edgenetwork.v1.GetInterconnectRequest\x1a).google.cloud.edgenetwork.v1.Interconnect"H\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/zones/*/interconnects/*}\x12\xde\x01\n\x14DiagnoseInterconnect\x128.google.cloud.edgenetwork.v1.DiagnoseInterconnectRequest\x1a9.google.cloud.edgenetwork.v1.DiagnoseInterconnectResponse"Q\xdaA\x04name\x82\xd3\xe4\x93\x02D\x12B/v1/{name=projects/*/locations/*/zones/*/interconnects/*}:diagnose\x12\xf6\x01\n\x1bListInterconnectAttachments\x12?.google.cloud.edgenetwork.v1.ListInterconnectAttachmentsRequest\x1a@.google.cloud.edgenetwork.v1.ListInterconnectAttachmentsResponse"T\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1/{parent=projects/*/locations/*/zones/*}/interconnectAttachments\x12\xe3\x01\n\x19GetInterconnectAttachment\x12=.google.cloud.edgenetwork.v1.GetInterconnectAttachmentRequest\x1a3.google.cloud.edgenetwork.v1.InterconnectAttachment"R\xdaA\x04name\x82\xd3\xe4\x93\x02E\x12C/v1/{name=projects/*/locations/*/zones/*/interconnectAttachments/*}\x12\xd0\x02\n\x1cCreateInterconnectAttachment\x12@.google.cloud.edgenetwork.v1.CreateInterconnectAttachmentRequest\x1a\x1d.google.longrunning.Operation"\xce\x01\xcaA+\n\x16InterconnectAttachment\x12\x11OperationMetadata\xdaA9parent,interconnect_attachment,interconnect_attachment_id\x82\xd3\xe4\x93\x02^"C/v1/{parent=projects/*/locations/*/zones/*}/interconnectAttachments:\x17interconnect_attachment\x12\x80\x02\n\x1cDeleteInterconnectAttachment\x12@.google.cloud.edgenetwork.v1.DeleteInterconnectAttachmentRequest\x1a\x1d.google.longrunning.Operation"\x7f\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02E*C/v1/{name=projects/*/locations/*/zones/*/interconnectAttachments/*}\x12\xb6\x01\n\x0bListRouters\x12/.google.cloud.edgenetwork.v1.ListRoutersRequest\x1a0.google.cloud.edgenetwork.v1.ListRoutersResponse"D\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*/zones/*}/routers\x12\xa3\x01\n\tGetRouter\x12-.google.cloud.edgenetwork.v1.GetRouterRequest\x1a#.google.cloud.edgenetwork.v1.Router"B\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/zones/*/routers/*}\x12\xc6\x01\n\x0eDiagnoseRouter\x122.google.cloud.edgenetwork.v1.DiagnoseRouterRequest\x1a3.google.cloud.edgenetwork.v1.DiagnoseRouterResponse"K\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v1/{name=projects/*/locations/*/zones/*/routers/*}:diagnose\x12\xdc\x01\n\x0cCreateRouter\x120.google.cloud.edgenetwork.v1.CreateRouterRequest\x1a\x1d.google.longrunning.Operation"{\xcaA\x1b\n\x06Router\x12\x11OperationMetadata\xdaA\x17parent,router,router_id\x82\xd3\xe4\x93\x02="3/v1/{parent=projects/*/locations/*/zones/*}/routers:\x06router\x12\xde\x01\n\x0cUpdateRouter\x120.google.cloud.edgenetwork.v1.UpdateRouterRequest\x1a\x1d.google.longrunning.Operation"}\xcaA\x1b\n\x06Router\x12\x11OperationMetadata\xdaA\x12router,update_mask\x82\xd3\xe4\x93\x02D2:/v1/{router.name=projects/*/locations/*/zones/*/routers/*}:\x06router\x12\xd0\x01\n\x0cDeleteRouter\x120.google.cloud.edgenetwork.v1.DeleteRouterRequest\x1a\x1d.google.longrunning.Operation"o\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/zones/*/routers/*}\x1aN\xcaA\x1aedgenetwork.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xd1\x01\n\x1fcom.google.cloud.edgenetwork.v1B\x0cServiceProtoP\x01ZAcloud.google.com/go/edgenetwork/apiv1/edgenetworkpb;edgenetworkpb\xaa\x02\x1bGoogle.Cloud.EdgeNetwork.V1\xca\x02\x1bGoogle\\Cloud\\EdgeNetwork\\V1\xea\x02\x1eGoogle::Cloud::EdgeNetwork::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.edgenetwork.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1fcom.google.cloud.edgenetwork.v1B\x0cServiceProtoP\x01ZAcloud.google.com/go/edgenetwork/apiv1/edgenetworkpb;edgenetworkpb\xaa\x02\x1bGoogle.Cloud.EdgeNetwork.V1\xca\x02\x1bGoogle\\Cloud\\EdgeNetwork\\V1\xea\x02\x1eGoogle::Cloud::EdgeNetwork::V1'
    _globals['_LISTZONESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTZONESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1fedgenetwork.googleapis.com/Zone'
    _globals['_LISTZONESREQUEST']._loaded_options = None
    _globals['_LISTZONESREQUEST']._serialized_options = b'\x18\x01'
    _globals['_LISTZONESRESPONSE']._loaded_options = None
    _globals['_LISTZONESRESPONSE']._serialized_options = b'\x18\x01'
    _globals['_GETZONEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETZONEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fedgenetwork.googleapis.com/Zone'
    _globals['_GETZONEREQUEST']._loaded_options = None
    _globals['_GETZONEREQUEST']._serialized_options = b'\x18\x01'
    _globals['_LISTNETWORKSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTNETWORKSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"edgenetwork.googleapis.com/Network'
    _globals['_GETNETWORKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETNETWORKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"edgenetwork.googleapis.com/Network'
    _globals['_CREATENETWORKREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATENETWORKREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"edgenetwork.googleapis.com/Network'
    _globals['_CREATENETWORKREQUEST'].fields_by_name['network_id']._loaded_options = None
    _globals['_CREATENETWORKREQUEST'].fields_by_name['network_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATENETWORKREQUEST'].fields_by_name['network']._loaded_options = None
    _globals['_CREATENETWORKREQUEST'].fields_by_name['network']._serialized_options = b'\xe0A\x02'
    _globals['_CREATENETWORKREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATENETWORKREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_DELETENETWORKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETENETWORKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"edgenetwork.googleapis.com/Network'
    _globals['_DELETENETWORKREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETENETWORKREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSUBNETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSUBNETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Subnet'
    _globals['_GETSUBNETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSUBNETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Subnet'
    _globals['_CREATESUBNETREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESUBNETREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Subnet'
    _globals['_CREATESUBNETREQUEST'].fields_by_name['subnet_id']._loaded_options = None
    _globals['_CREATESUBNETREQUEST'].fields_by_name['subnet_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESUBNETREQUEST'].fields_by_name['subnet']._loaded_options = None
    _globals['_CREATESUBNETREQUEST'].fields_by_name['subnet']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESUBNETREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATESUBNETREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESUBNETREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATESUBNETREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESUBNETREQUEST'].fields_by_name['subnet']._loaded_options = None
    _globals['_UPDATESUBNETREQUEST'].fields_by_name['subnet']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESUBNETREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATESUBNETREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_DELETESUBNETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESUBNETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Subnet'
    _globals['_DELETESUBNETREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETESUBNETREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTINTERCONNECTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINTERCONNECTSREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'edgenetwork.googleapis.com/Interconnect"
    _globals['_GETINTERCONNECTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINTERCONNECTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'edgenetwork.googleapis.com/Interconnect"
    _globals['_LISTINTERCONNECTATTACHMENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINTERCONNECTATTACHMENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA3\x121edgenetwork.googleapis.com/InterconnectAttachment'
    _globals['_GETINTERCONNECTATTACHMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINTERCONNECTATTACHMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA3\n1edgenetwork.googleapis.com/InterconnectAttachment'
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA3\x121edgenetwork.googleapis.com/InterconnectAttachment'
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['interconnect_attachment_id']._loaded_options = None
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['interconnect_attachment_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['interconnect_attachment']._loaded_options = None
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['interconnect_attachment']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA3\n1edgenetwork.googleapis.com/InterconnectAttachment'
    _globals['_DELETEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETEINTERCONNECTATTACHMENTREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTROUTERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTROUTERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Router'
    _globals['_GETROUTERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETROUTERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Router'
    _globals['_CREATEROUTERREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEROUTERREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\x12!edgenetwork.googleapis.com/Router'
    _globals['_CREATEROUTERREQUEST'].fields_by_name['router_id']._loaded_options = None
    _globals['_CREATEROUTERREQUEST'].fields_by_name['router_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEROUTERREQUEST'].fields_by_name['router']._loaded_options = None
    _globals['_CREATEROUTERREQUEST'].fields_by_name['router']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEROUTERREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATEROUTERREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEROUTERREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEROUTERREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEROUTERREQUEST'].fields_by_name['router']._loaded_options = None
    _globals['_UPDATEROUTERREQUEST'].fields_by_name['router']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEROUTERREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATEROUTERREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEROUTERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEROUTERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Router'
    _globals['_DELETEROUTERREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETEROUTERREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_DIAGNOSENETWORKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DIAGNOSENETWORKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"edgenetwork.googleapis.com/Network'
    _globals['_DIAGNOSEINTERCONNECTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DIAGNOSEINTERCONNECTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'edgenetwork.googleapis.com/Interconnect"
    _globals['_DIAGNOSEROUTERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DIAGNOSEROUTERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!edgenetwork.googleapis.com/Router'
    _globals['_INITIALIZEZONEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_INITIALIZEZONEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fedgenetwork.googleapis.com/Zone'
    _globals['_EDGENETWORK']._loaded_options = None
    _globals['_EDGENETWORK']._serialized_options = b'\xcaA\x1aedgenetwork.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_EDGENETWORK'].methods_by_name['InitializeZone']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['InitializeZone']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/zones/*}:initialize:\x01*'
    _globals['_EDGENETWORK'].methods_by_name['ListZones']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['ListZones']._serialized_options = b'\x88\x02\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02+\x12)/v1/{parent=projects/*/locations/*}/zones'
    _globals['_EDGENETWORK'].methods_by_name['GetZone']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['GetZone']._serialized_options = b'\x88\x02\x01\xdaA\x04name\x82\xd3\xe4\x93\x02+\x12)/v1/{name=projects/*/locations/*/zones/*}'
    _globals['_EDGENETWORK'].methods_by_name['ListNetworks']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['ListNetworks']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x026\x124/v1/{parent=projects/*/locations/*/zones/*}/networks'
    _globals['_EDGENETWORK'].methods_by_name['GetNetwork']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['GetNetwork']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x026\x124/v1/{name=projects/*/locations/*/zones/*/networks/*}'
    _globals['_EDGENETWORK'].methods_by_name['DiagnoseNetwork']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['DiagnoseNetwork']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02?\x12=/v1/{name=projects/*/locations/*/zones/*/networks/*}:diagnose'
    _globals['_EDGENETWORK'].methods_by_name['CreateNetwork']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['CreateNetwork']._serialized_options = b'\xcaA\x1c\n\x07Network\x12\x11OperationMetadata\xdaA\x19parent,network,network_id\x82\xd3\xe4\x93\x02?"4/v1/{parent=projects/*/locations/*/zones/*}/networks:\x07network'
    _globals['_EDGENETWORK'].methods_by_name['DeleteNetwork']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['DeleteNetwork']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x026*4/v1/{name=projects/*/locations/*/zones/*/networks/*}'
    _globals['_EDGENETWORK'].methods_by_name['ListSubnets']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['ListSubnets']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*/zones/*}/subnets'
    _globals['_EDGENETWORK'].methods_by_name['GetSubnet']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['GetSubnet']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/zones/*/subnets/*}'
    _globals['_EDGENETWORK'].methods_by_name['CreateSubnet']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['CreateSubnet']._serialized_options = b'\xcaA\x1b\n\x06Subnet\x12\x11OperationMetadata\xdaA\x17parent,subnet,subnet_id\x82\xd3\xe4\x93\x02="3/v1/{parent=projects/*/locations/*/zones/*}/subnets:\x06subnet'
    _globals['_EDGENETWORK'].methods_by_name['UpdateSubnet']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['UpdateSubnet']._serialized_options = b'\xcaA\x1b\n\x06Subnet\x12\x11OperationMetadata\xdaA\x12subnet,update_mask\x82\xd3\xe4\x93\x02D2:/v1/{subnet.name=projects/*/locations/*/zones/*/subnets/*}:\x06subnet'
    _globals['_EDGENETWORK'].methods_by_name['DeleteSubnet']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['DeleteSubnet']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/zones/*/subnets/*}'
    _globals['_EDGENETWORK'].methods_by_name['ListInterconnects']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['ListInterconnects']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/zones/*}/interconnects'
    _globals['_EDGENETWORK'].methods_by_name['GetInterconnect']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['GetInterconnect']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/zones/*/interconnects/*}'
    _globals['_EDGENETWORK'].methods_by_name['DiagnoseInterconnect']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['DiagnoseInterconnect']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02D\x12B/v1/{name=projects/*/locations/*/zones/*/interconnects/*}:diagnose'
    _globals['_EDGENETWORK'].methods_by_name['ListInterconnectAttachments']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['ListInterconnectAttachments']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1/{parent=projects/*/locations/*/zones/*}/interconnectAttachments'
    _globals['_EDGENETWORK'].methods_by_name['GetInterconnectAttachment']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['GetInterconnectAttachment']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02E\x12C/v1/{name=projects/*/locations/*/zones/*/interconnectAttachments/*}'
    _globals['_EDGENETWORK'].methods_by_name['CreateInterconnectAttachment']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['CreateInterconnectAttachment']._serialized_options = b'\xcaA+\n\x16InterconnectAttachment\x12\x11OperationMetadata\xdaA9parent,interconnect_attachment,interconnect_attachment_id\x82\xd3\xe4\x93\x02^"C/v1/{parent=projects/*/locations/*/zones/*}/interconnectAttachments:\x17interconnect_attachment'
    _globals['_EDGENETWORK'].methods_by_name['DeleteInterconnectAttachment']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['DeleteInterconnectAttachment']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02E*C/v1/{name=projects/*/locations/*/zones/*/interconnectAttachments/*}'
    _globals['_EDGENETWORK'].methods_by_name['ListRouters']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['ListRouters']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1/{parent=projects/*/locations/*/zones/*}/routers'
    _globals['_EDGENETWORK'].methods_by_name['GetRouter']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['GetRouter']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1/{name=projects/*/locations/*/zones/*/routers/*}'
    _globals['_EDGENETWORK'].methods_by_name['DiagnoseRouter']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['DiagnoseRouter']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v1/{name=projects/*/locations/*/zones/*/routers/*}:diagnose'
    _globals['_EDGENETWORK'].methods_by_name['CreateRouter']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['CreateRouter']._serialized_options = b'\xcaA\x1b\n\x06Router\x12\x11OperationMetadata\xdaA\x17parent,router,router_id\x82\xd3\xe4\x93\x02="3/v1/{parent=projects/*/locations/*/zones/*}/routers:\x06router'
    _globals['_EDGENETWORK'].methods_by_name['UpdateRouter']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['UpdateRouter']._serialized_options = b'\xcaA\x1b\n\x06Router\x12\x11OperationMetadata\xdaA\x12router,update_mask\x82\xd3\xe4\x93\x02D2:/v1/{router.name=projects/*/locations/*/zones/*/routers/*}:\x06router'
    _globals['_EDGENETWORK'].methods_by_name['DeleteRouter']._loaded_options = None
    _globals['_EDGENETWORK'].methods_by_name['DeleteRouter']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1/{name=projects/*/locations/*/zones/*/routers/*}'
    _globals['_LISTZONESREQUEST']._serialized_start = 368
    _globals['_LISTZONESREQUEST']._serialized_end = 520
    _globals['_LISTZONESRESPONSE']._serialized_start = 522
    _globals['_LISTZONESRESPONSE']._serialized_end = 641
    _globals['_GETZONEREQUEST']._serialized_start = 643
    _globals['_GETZONEREQUEST']._serialized_end = 718
    _globals['_LISTNETWORKSREQUEST']._serialized_start = 721
    _globals['_LISTNETWORKSREQUEST']._serialized_end = 875
    _globals['_LISTNETWORKSRESPONSE']._serialized_start = 877
    _globals['_LISTNETWORKSRESPONSE']._serialized_end = 1001
    _globals['_GETNETWORKREQUEST']._serialized_start = 1003
    _globals['_GETNETWORKREQUEST']._serialized_end = 1080
    _globals['_CREATENETWORKREQUEST']._serialized_start = 1083
    _globals['_CREATENETWORKREQUEST']._serialized_end = 1275
    _globals['_DELETENETWORKREQUEST']._serialized_start = 1277
    _globals['_DELETENETWORKREQUEST']._serialized_end = 1382
    _globals['_LISTSUBNETSREQUEST']._serialized_start = 1385
    _globals['_LISTSUBNETSREQUEST']._serialized_end = 1537
    _globals['_LISTSUBNETSRESPONSE']._serialized_start = 1539
    _globals['_LISTSUBNETSRESPONSE']._serialized_end = 1660
    _globals['_GETSUBNETREQUEST']._serialized_start = 1662
    _globals['_GETSUBNETREQUEST']._serialized_end = 1737
    _globals['_CREATESUBNETREQUEST']._serialized_start = 1740
    _globals['_CREATESUBNETREQUEST']._serialized_end = 1927
    _globals['_UPDATESUBNETREQUEST']._serialized_start = 1930
    _globals['_UPDATESUBNETREQUEST']._serialized_end = 2088
    _globals['_DELETESUBNETREQUEST']._serialized_start = 2090
    _globals['_DELETESUBNETREQUEST']._serialized_end = 2193
    _globals['_LISTINTERCONNECTSREQUEST']._serialized_start = 2196
    _globals['_LISTINTERCONNECTSREQUEST']._serialized_end = 2360
    _globals['_LISTINTERCONNECTSRESPONSE']._serialized_start = 2363
    _globals['_LISTINTERCONNECTSRESPONSE']._serialized_end = 2502
    _globals['_GETINTERCONNECTREQUEST']._serialized_start = 2504
    _globals['_GETINTERCONNECTREQUEST']._serialized_end = 2591
    _globals['_LISTINTERCONNECTATTACHMENTSREQUEST']._serialized_start = 2594
    _globals['_LISTINTERCONNECTATTACHMENTSREQUEST']._serialized_end = 2778
    _globals['_LISTINTERCONNECTATTACHMENTSRESPONSE']._serialized_start = 2781
    _globals['_LISTINTERCONNECTATTACHMENTSRESPONSE']._serialized_end = 2951
    _globals['_GETINTERCONNECTATTACHMENTREQUEST']._serialized_start = 2953
    _globals['_GETINTERCONNECTATTACHMENTREQUEST']._serialized_end = 3060
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST']._serialized_start = 3063
    _globals['_CREATEINTERCONNECTATTACHMENTREQUEST']._serialized_end = 3332
    _globals['_DELETEINTERCONNECTATTACHMENTREQUEST']._serialized_start = 3335
    _globals['_DELETEINTERCONNECTATTACHMENTREQUEST']._serialized_end = 3470
    _globals['_LISTROUTERSREQUEST']._serialized_start = 3473
    _globals['_LISTROUTERSREQUEST']._serialized_end = 3625
    _globals['_LISTROUTERSRESPONSE']._serialized_start = 3627
    _globals['_LISTROUTERSRESPONSE']._serialized_end = 3748
    _globals['_GETROUTERREQUEST']._serialized_start = 3750
    _globals['_GETROUTERREQUEST']._serialized_end = 3825
    _globals['_CREATEROUTERREQUEST']._serialized_start = 3828
    _globals['_CREATEROUTERREQUEST']._serialized_end = 4015
    _globals['_UPDATEROUTERREQUEST']._serialized_start = 4018
    _globals['_UPDATEROUTERREQUEST']._serialized_end = 4176
    _globals['_DELETEROUTERREQUEST']._serialized_start = 4178
    _globals['_DELETEROUTERREQUEST']._serialized_end = 4281
    _globals['_OPERATIONMETADATA']._serialized_start = 4284
    _globals['_OPERATIONMETADATA']._serialized_end = 4540
    _globals['_DIAGNOSENETWORKREQUEST']._serialized_start = 4542
    _globals['_DIAGNOSENETWORKREQUEST']._serialized_end = 4624
    _globals['_DIAGNOSENETWORKRESPONSE']._serialized_start = 4627
    _globals['_DIAGNOSENETWORKRESPONSE']._serialized_end = 5061
    _globals['_DIAGNOSENETWORKRESPONSE_NETWORKSTATUS']._serialized_start = 4788
    _globals['_DIAGNOSENETWORKRESPONSE_NETWORKSTATUS']._serialized_end = 5061
    _globals['_DIAGNOSENETWORKRESPONSE_NETWORKSTATUS_MACSECSTATUS']._serialized_start = 4990
    _globals['_DIAGNOSENETWORKRESPONSE_NETWORKSTATUS_MACSECSTATUS']._serialized_end = 5061
    _globals['_DIAGNOSEINTERCONNECTREQUEST']._serialized_start = 5063
    _globals['_DIAGNOSEINTERCONNECTREQUEST']._serialized_end = 5155
    _globals['_DIAGNOSEINTERCONNECTRESPONSE']._serialized_start = 5158
    _globals['_DIAGNOSEINTERCONNECTRESPONSE']._serialized_end = 5307
    _globals['_DIAGNOSEROUTERREQUEST']._serialized_start = 5309
    _globals['_DIAGNOSEROUTERREQUEST']._serialized_end = 5389
    _globals['_DIAGNOSEROUTERRESPONSE']._serialized_start = 5392
    _globals['_DIAGNOSEROUTERRESPONSE']._serialized_end = 5524
    _globals['_INITIALIZEZONEREQUEST']._serialized_start = 5526
    _globals['_INITIALIZEZONEREQUEST']._serialized_end = 5604
    _globals['_INITIALIZEZONERESPONSE']._serialized_start = 5606
    _globals['_INITIALIZEZONERESPONSE']._serialized_end = 5630
    _globals['_EDGENETWORK']._serialized_start = 5633
    _globals['_EDGENETWORK']._serialized_end = 11178