"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/visionai/v1alpha1/warehouse.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .....google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from .....google.type import datetime_pb2 as google_dot_type_dot_datetime__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.google/cloud/visionai/v1alpha1/warehouse.proto\x12\x1egoogle.cloud.visionai.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a#google/longrunning/operations.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\x1a\x1agoogle/type/datetime.proto"\xb0\x01\n\x12CreateAssetRequest\x126\n\x06parent\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus\x129\n\x05asset\x18\x02 \x01(\x0b2%.google.cloud.visionai.v1alpha1.AssetB\x03\xe0A\x02\x12\x1a\n\x08asset_id\x18\x03 \x01(\tB\x03\xe0A\x01H\x00\x88\x01\x01B\x0b\n\t_asset_id"F\n\x0fGetAssetRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset"q\n\x11ListAssetsRequest\x125\n\x06parent\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\x12\x1dvisionai.googleapis.com/Asset\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"d\n\x12ListAssetsResponse\x125\n\x06assets\x18\x01 \x03(\x0b2%.google.cloud.visionai.v1alpha1.Asset\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x80\x01\n\x12UpdateAssetRequest\x129\n\x05asset\x18\x01 \x01(\x0b2%.google.cloud.visionai.v1alpha1.AssetB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"I\n\x12DeleteAssetRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset"\xb1\x01\n\x05Asset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x03ttl\x18\x02 \x01(\x0b2\x19.google.protobuf.Duration:r\xeaAo\n\x1dvisionai.googleapis.com/Asset\x12Nprojects/{project_number}/locations/{location}/corpora/{corpus}/assets/{asset}"g\n\x13CreateCorpusRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12;\n\x06corpus\x18\x02 \x01(\x0b2&.google.cloud.visionai.v1alpha1.CorpusB\x03\xe0A\x02"\x16\n\x14CreateCorpusMetadata"\xe6\x01\n\x06Corpus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x0cdisplay_name\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x18\n\x0bdescription\x18\x03 \x01(\tB\x03\xe0A\x01\x123\n\x0bdefault_ttl\x18\x05 \x01(\x0b2\x19.google.protobuf.DurationB\x03\xe0A\x02:d\xeaAa\n\x1evisionai.googleapis.com/Corpus\x12?projects/{project_number}/locations/{location}/corpora/{corpus}"H\n\x10GetCorpusRequest\x124\n\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus"\x83\x01\n\x13UpdateCorpusRequest\x12;\n\x06corpus\x18\x01 \x01(\x0b2&.google.cloud.visionai.v1alpha1.CorpusB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"P\n\x12ListCorporaRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"g\n\x13ListCorporaResponse\x127\n\x07corpora\x18\x01 \x03(\x0b2&.google.cloud.visionai.v1alpha1.Corpus\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"K\n\x13DeleteCorpusRequest\x124\n\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus"\x97\x01\n\x17CreateDataSchemaRequest\x126\n\x06parent\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus\x12D\n\x0bdata_schema\x18\x02 \x01(\x0b2*.google.cloud.visionai.v1alpha1.DataSchemaB\x03\xe0A\x02"\xfc\x01\n\nDataSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x03key\x18\x02 \x01(\tB\x03\xe0A\x02\x12I\n\x0eschema_details\x18\x03 \x01(\x0b21.google.cloud.visionai.v1alpha1.DataSchemaDetails:\x82\x01\xeaA\x7f\n"visionai.googleapis.com/DataSchema\x12Yprojects/{project_number}/locations/{location}/corpora/{corpus}/dataSchemas/{data_schema}"\xcf\x06\n\x11DataSchemaDetails\x12H\n\x04type\x18\x01 \x01(\x0e2:.google.cloud.visionai.v1alpha1.DataSchemaDetails.DataType\x12Z\n\x10proto_any_config\x18\x06 \x01(\x0b2@.google.cloud.visionai.v1alpha1.DataSchemaDetails.ProtoAnyConfig\x12R\n\x0bgranularity\x18\x05 \x01(\x0e2=.google.cloud.visionai.v1alpha1.DataSchemaDetails.Granularity\x12Y\n\x0fsearch_strategy\x18\x07 \x01(\x0b2@.google.cloud.visionai.v1alpha1.DataSchemaDetails.SearchStrategy\x1a"\n\x0eProtoAnyConfig\x12\x10\n\x08type_uri\x18\x01 \x01(\t\x1a\xcc\x01\n\x0eSearchStrategy\x12q\n\x14search_strategy_type\x18\x01 \x01(\x0e2S.google.cloud.visionai.v1alpha1.DataSchemaDetails.SearchStrategy.SearchStrategyType"G\n\x12SearchStrategyType\x12\r\n\tNO_SEARCH\x10\x00\x12\x10\n\x0cEXACT_SEARCH\x10\x01\x12\x10\n\x0cSMART_SEARCH\x10\x02"\x87\x01\n\x08DataType\x12\x19\n\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07INTEGER\x10\x01\x12\t\n\x05FLOAT\x10\x02\x12\n\n\x06STRING\x10\x03\x12\x0c\n\x08DATETIME\x10\x05\x12\x12\n\x0eGEO_COORDINATE\x10\x07\x12\r\n\tPROTO_ANY\x10\x08\x12\x0b\n\x07BOOLEAN\x10\t"h\n\x0bGranularity\x12\x1b\n\x17GRANULARITY_UNSPECIFIED\x10\x00\x12\x1b\n\x17GRANULARITY_ASSET_LEVEL\x10\x01\x12\x1f\n\x1bGRANULARITY_PARTITION_LEVEL\x10\x02"\x90\x01\n\x17UpdateDataSchemaRequest\x12D\n\x0bdata_schema\x18\x01 \x01(\x0b2*.google.cloud.visionai.v1alpha1.DataSchemaB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"P\n\x14GetDataSchemaRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"visionai.googleapis.com/DataSchema"S\n\x17DeleteDataSchemaRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"visionai.googleapis.com/DataSchema"{\n\x16ListDataSchemasRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"visionai.googleapis.com/DataSchema\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"t\n\x17ListDataSchemasResponse\x12@\n\x0cdata_schemas\x18\x01 \x03(\x0b2*.google.cloud.visionai.v1alpha1.DataSchema\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xc8\x01\n\x17CreateAnnotationRequest\x125\n\x06parent\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset\x12C\n\nannotation\x18\x02 \x01(\x0b2*.google.cloud.visionai.v1alpha1.AnnotationB\x03\xe0A\x02\x12\x1f\n\rannotation_id\x18\x03 \x01(\tB\x03\xe0A\x01H\x00\x88\x01\x01B\x10\n\x0e_annotation_id"\x8a\x02\n\nAnnotation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12Z\n\x19user_specified_annotation\x18\x02 \x01(\x0b27.google.cloud.visionai.v1alpha1.UserSpecifiedAnnotation:\x91\x01\xeaA\x8d\x01\n"visionai.googleapis.com/Annotation\x12gprojects/{project_number}/locations/{location}/corpora/{corpus}/assets/{asset}/annotations/{annotation}"\xa9\x01\n\x17UserSpecifiedAnnotation\x12\x10\n\x03key\x18\x01 \x01(\tB\x03\xe0A\x02\x12>\n\x05value\x18\x02 \x01(\x0b2/.google.cloud.visionai.v1alpha1.AnnotationValue\x12<\n\tpartition\x18\x03 \x01(\x0b2).google.cloud.visionai.v1alpha1.Partition"4\n\rGeoCoordinate\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01"\xc6\x02\n\x0fAnnotationValue\x12\x13\n\tint_value\x18\x01 \x01(\x03H\x00\x12\x15\n\x0bfloat_value\x18\x02 \x01(\x02H\x00\x12\x13\n\tstr_value\x18\x03 \x01(\tH\x00\x12\x18\n\x0edatetime_value\x18\x05 \x01(\tH\x00\x12G\n\x0egeo_coordinate\x18\x07 \x01(\x0b2-.google.cloud.visionai.v1alpha1.GeoCoordinateH\x00\x12/\n\x0fproto_any_value\x18\x08 \x01(\x0b2\x14.google.protobuf.AnyH\x00\x12\x14\n\nbool_value\x18\t \x01(\x08H\x00\x12?\n\x1ccustomized_struct_data_value\x18\n \x01(\x0b2\x17.google.protobuf.StructH\x00B\x07\n\x05value"\x83\x01\n\x16ListAnnotationsRequest\x122\n\x06parent\x18\x01 \x01(\tB"\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t"s\n\x17ListAnnotationsResponse\x12?\n\x0bannotations\x18\x01 \x03(\x0b2*.google.cloud.visionai.v1alpha1.Annotation\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"P\n\x14GetAnnotationRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"visionai.googleapis.com/Annotation"\x8f\x01\n\x17UpdateAnnotationRequest\x12C\n\nannotation\x18\x01 \x01(\x0b2*.google.cloud.visionai.v1alpha1.AnnotationB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"S\n\x17DeleteAnnotationRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"visionai.googleapis.com/Annotation"\xc2\x01\n\x19CreateSearchConfigRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$visionai.googleapis.com/SearchConfig\x12H\n\rsearch_config\x18\x02 \x01(\x0b2,.google.cloud.visionai.v1alpha1.SearchConfigB\x03\xe0A\x02\x12\x1d\n\x10search_config_id\x18\x03 \x01(\tB\x03\xe0A\x02"\x96\x01\n\x19UpdateSearchConfigRequest\x12H\n\rsearch_config\x18\x01 \x01(\x0b2,.google.cloud.visionai.v1alpha1.SearchConfigB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"T\n\x16GetSearchConfigRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$visionai.googleapis.com/SearchConfig"W\n\x19DeleteSearchConfigRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$visionai.googleapis.com/SearchConfig"\x7f\n\x18ListSearchConfigsRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\x12$visionai.googleapis.com/SearchConfig\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"z\n\x19ListSearchConfigsResponse\x12D\n\x0esearch_configs\x18\x01 \x03(\x0b2,.google.cloud.visionai.v1alpha1.SearchConfig\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xc9\x02\n\x0cSearchConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12E\n\x0efacet_property\x18\x02 \x01(\x0b2-.google.cloud.visionai.v1alpha1.FacetProperty\x12X\n\x18search_criteria_property\x18\x03 \x01(\x0b26.google.cloud.visionai.v1alpha1.SearchCriteriaProperty:\x89\x01\xeaA\x85\x01\n$visionai.googleapis.com/SearchConfig\x12]projects/{project_number}/locations/{location}/corpora/{corpus}/searchConfigs/{search_config}"\xb4\x07\n\rFacetProperty\x12e\n\x17fixed_range_bucket_spec\x18\x05 \x01(\x0b2B.google.cloud.visionai.v1alpha1.FacetProperty.FixedRangeBucketSpecH\x00\x12g\n\x18custom_range_bucket_spec\x18\x06 \x01(\x0b2C.google.cloud.visionai.v1alpha1.FacetProperty.CustomRangeBucketSpecH\x00\x12`\n\x14datetime_bucket_spec\x18\x07 \x01(\x0b2@.google.cloud.visionai.v1alpha1.FacetProperty.DateTimeBucketSpecH\x00\x12\x15\n\rmapped_fields\x18\x01 \x03(\t\x12\x14\n\x0cdisplay_name\x18\x02 \x01(\t\x12\x13\n\x0bresult_size\x18\x03 \x01(\x03\x12D\n\x0bbucket_type\x18\x04 \x01(\x0e2/.google.cloud.visionai.v1alpha1.FacetBucketType\x1a\xb6\x01\n\x14FixedRangeBucketSpec\x12@\n\x0cbucket_start\x18\x01 \x01(\x0b2*.google.cloud.visionai.v1alpha1.FacetValue\x12F\n\x12bucket_granularity\x18\x02 \x01(\x0b2*.google.cloud.visionai.v1alpha1.FacetValue\x12\x14\n\x0cbucket_count\x18\x03 \x01(\x05\x1aV\n\x15CustomRangeBucketSpec\x12=\n\tendpoints\x18\x01 \x03(\x0b2*.google.cloud.visionai.v1alpha1.FacetValue\x1a\xc1\x01\n\x12DateTimeBucketSpec\x12a\n\x0bgranularity\x18\x01 \x01(\x0e2L.google.cloud.visionai.v1alpha1.FacetProperty.DateTimeBucketSpec.Granularity"H\n\x0bGranularity\x12\x1b\n\x17GRANULARITY_UNSPECIFIED\x10\x00\x12\x08\n\x04YEAR\x10\x01\x12\t\n\x05MONTH\x10\x02\x12\x07\n\x03DAY\x10\x03B\x14\n\x12range_facet_config"/\n\x16SearchCriteriaProperty\x12\x15\n\rmapped_fields\x18\x01 \x03(\t"w\n\nFacetValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x17\n\rinteger_value\x18\x02 \x01(\x03H\x00\x12/\n\x0edatetime_value\x18\x03 \x01(\x0b2\x15.google.type.DateTimeH\x00B\x07\n\x05value"\xad\x02\n\x0bFacetBucket\x12;\n\x05value\x18\x02 \x01(\x0b2*.google.cloud.visionai.v1alpha1.FacetValueH\x00\x12B\n\x05range\x18\x04 \x01(\x0b21.google.cloud.visionai.v1alpha1.FacetBucket.RangeH\x00\x12\x10\n\x08selected\x18\x03 \x01(\x08\x1a{\n\x05Range\x129\n\x05start\x18\x01 \x01(\x0b2*.google.cloud.visionai.v1alpha1.FacetValue\x127\n\x03end\x18\x02 \x01(\x0b2*.google.cloud.visionai.v1alpha1.FacetValueB\x0e\n\x0cbucket_value"\xdb\x01\n\nFacetGroup\x12\x10\n\x08facet_id\x18\x01 \x01(\t\x12\x14\n\x0cdisplay_name\x18\x02 \x01(\t\x12<\n\x07buckets\x18\x03 \x03(\x0b2+.google.cloud.visionai.v1alpha1.FacetBucket\x12D\n\x0bbucket_type\x18\x04 \x01(\x0e2/.google.cloud.visionai.v1alpha1.FacetBucketType\x12!\n\x19fetch_matched_annotations\x18\x05 \x01(\x08"\xc6\x05\n\x12IngestAssetRequest\x12K\n\x06config\x18\x01 \x01(\x0b29.google.cloud.visionai.v1alpha1.IngestAssetRequest.ConfigH\x00\x12_\n\x11time_indexed_data\x18\x02 \x01(\x0b2B.google.cloud.visionai.v1alpha1.IngestAssetRequest.TimeIndexedDataH\x00\x1a\xf2\x02\n\x06Config\x12Y\n\nvideo_type\x18\x02 \x01(\x0b2C.google.cloud.visionai.v1alpha1.IngestAssetRequest.Config.VideoTypeH\x00\x124\n\x05asset\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset\x1a\xc9\x01\n\tVideoType\x12m\n\x10container_format\x18\x01 \x01(\x0e2S.google.cloud.visionai.v1alpha1.IngestAssetRequest.Config.VideoType.ContainerFormat"M\n\x0fContainerFormat\x12 \n\x1cCONTAINER_FORMAT_UNSPECIFIED\x10\x00\x12\x18\n\x14CONTAINER_FORMAT_MP4\x10\x01B\x0b\n\tdata_type\x1ax\n\x0fTimeIndexedData\x12\x0c\n\x04data\x18\x01 \x01(\x0c\x12W\n\x12temporal_partition\x18\x02 \x01(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartitionB\x13\n\x11streaming_request"{\n\x13IngestAssetResponse\x12d\n\x1fsuccessfully_ingested_partition\x18\x01 \x01(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartition"\xa5\x01\n\x10ClipAssetRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset\x12\\\n\x12temporal_partition\x18\x02 \x01(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartitionB\x03\xe0A\x02"\xe8\x01\n\x11ClipAssetResponse\x12[\n\x11time_indexed_uris\x18\x01 \x03(\x0b2@.google.cloud.visionai.v1alpha1.ClipAssetResponse.TimeIndexedUri\x1av\n\x0eTimeIndexedUri\x12W\n\x12temporal_partition\x18\x01 \x01(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartition\x12\x0b\n\x03uri\x18\x02 \x01(\t"\xab\x01\n\x15GenerateHlsUriRequest\x123\n\x04name\x18\x01 \x01(\tB%\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset\x12]\n\x13temporal_partitions\x18\x02 \x03(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartitionB\x03\xe0A\x02"\x7f\n\x16GenerateHlsUriResponse\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12X\n\x13temporal_partitions\x18\x02 \x03(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartition"\xe7\x02\n\x13SearchAssetsRequest\x126\n\x06corpus\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12O\n\x13content_time_ranges\x18\x05 \x01(\x0b22.google.cloud.visionai.v1alpha1.DateTimeRangeArray\x12:\n\x08criteria\x18\x04 \x03(\x0b2(.google.cloud.visionai.v1alpha1.Criteria\x12D\n\x10facet_selections\x18\x06 \x03(\x0b2*.google.cloud.visionai.v1alpha1.FacetGroup\x12\x1e\n\x16result_annotation_keys\x18\x08 \x03(\t"\x15\n\x13DeleteAssetMetadata"\xc3\x01\n\x18AnnotationMatchingResult\x12:\n\x08criteria\x18\x01 \x01(\x0b2(.google.cloud.visionai.v1alpha1.Criteria\x12G\n\x13matched_annotations\x18\x02 \x03(\x0b2*.google.cloud.visionai.v1alpha1.Annotation\x12"\n\x06status\x18\x03 \x01(\x0b2\x12.google.rpc.Status"\xec\x02\n\x10SearchResultItem\x12\r\n\x05asset\x18\x01 \x01(\t\x12Q\n\x08segments\x18\x02 \x03(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartitionB\x02\x18\x01\x12L\n\x07segment\x18\x05 \x01(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartition\x12I\n\x15requested_annotations\x18\x03 \x03(\x0b2*.google.cloud.visionai.v1alpha1.Annotation\x12]\n\x1bannotation_matching_results\x18\x04 \x03(\x0b28.google.cloud.visionai.v1alpha1.AnnotationMatchingResult"\xc1\x01\n\x14SearchAssetsResponse\x12M\n\x13search_result_items\x18\x01 \x03(\x0b20.google.cloud.visionai.v1alpha1.SearchResultItem\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12A\n\rfacet_results\x18\x03 \x03(\x0b2*.google.cloud.visionai.v1alpha1.FacetGroup"B\n\x08IntRange\x12\x12\n\x05start\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x10\n\x03end\x18\x02 \x01(\x03H\x01\x88\x01\x01B\x08\n\x06_startB\x06\n\x04_end"D\n\nFloatRange\x12\x12\n\x05start\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x10\n\x03end\x18\x02 \x01(\x02H\x01\x88\x01\x01B\x08\n\x06_startB\x06\n\x04_end"!\n\x0bStringArray\x12\x12\n\ntxt_values\x18\x01 \x03(\t"M\n\rIntRangeArray\x12<\n\nint_ranges\x18\x01 \x03(\x0b2(.google.cloud.visionai.v1alpha1.IntRange"S\n\x0fFloatRangeArray\x12@\n\x0cfloat_ranges\x18\x01 \x03(\x0b2*.google.cloud.visionai.v1alpha1.FloatRange"Y\n\rDateTimeRange\x12$\n\x05start\x18\x01 \x01(\x0b2\x15.google.type.DateTime\x12"\n\x03end\x18\x02 \x01(\x0b2\x15.google.type.DateTime"]\n\x12DateTimeRangeArray\x12G\n\x10date_time_ranges\x18\x01 \x03(\x0b2-.google.cloud.visionai.v1alpha1.DateTimeRange"G\n\nCircleArea\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x14\n\x0cradius_meter\x18\x03 \x01(\x01"T\n\x10GeoLocationArray\x12@\n\x0ccircle_areas\x18\x01 \x03(\x0b2*.google.cloud.visionai.v1alpha1.CircleArea"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08"\x86\x04\n\x08Criteria\x12A\n\ntext_array\x18\x02 \x01(\x0b2+.google.cloud.visionai.v1alpha1.StringArrayH\x00\x12H\n\x0fint_range_array\x18\x03 \x01(\x0b2-.google.cloud.visionai.v1alpha1.IntRangeArrayH\x00\x12L\n\x11float_range_array\x18\x04 \x01(\x0b2/.google.cloud.visionai.v1alpha1.FloatRangeArrayH\x00\x12S\n\x15date_time_range_array\x18\x05 \x01(\x0b22.google.cloud.visionai.v1alpha1.DateTimeRangeArrayH\x00\x12N\n\x12geo_location_array\x18\x06 \x01(\x0b20.google.cloud.visionai.v1alpha1.GeoLocationArrayH\x00\x12?\n\nbool_value\x18\x07 \x01(\x0b2).google.cloud.visionai.v1alpha1.BoolValueH\x00\x12\r\n\x05field\x18\x01 \x01(\t\x12!\n\x19fetch_matched_annotations\x18\x08 \x01(\x08B\x07\n\x05value"\xbb\x03\n\tPartition\x12W\n\x12temporal_partition\x18\x01 \x01(\x0b2;.google.cloud.visionai.v1alpha1.Partition.TemporalPartition\x12U\n\x11spatial_partition\x18\x02 \x01(\x0b2:.google.cloud.visionai.v1alpha1.Partition.SpatialPartition\x1aq\n\x11TemporalPartition\x12.\n\nstart_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x1a\x8a\x01\n\x10SpatialPartition\x12\x12\n\x05x_min\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05y_min\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x12\n\x05x_max\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x12\n\x05y_max\x18\x04 \x01(\x03H\x03\x88\x01\x01B\x08\n\x06_x_minB\x08\n\x06_y_minB\x08\n\x06_x_maxB\x08\n\x06_y_max*\xb8\x01\n\x0fFacetBucketType\x12!\n\x1dFACET_BUCKET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17FACET_BUCKET_TYPE_VALUE\x10\x01\x12\x1e\n\x1aFACET_BUCKET_TYPE_DATETIME\x10\x02\x12!\n\x1dFACET_BUCKET_TYPE_FIXED_RANGE\x10\x03\x12"\n\x1eFACET_BUCKET_TYPE_CUSTOM_RANGE\x10\x042\xcf/\n\tWarehouse\x12\xcb\x01\n\x0bCreateAsset\x122.google.cloud.visionai.v1alpha1.CreateAssetRequest\x1a%.google.cloud.visionai.v1alpha1.Asset"a\xdaA\x15parent,asset,asset_id\x82\xd3\xe4\x93\x02C":/v1alpha1/{parent=projects/*/locations/*/corpora/*}/assets:\x05asset\x12\xcd\x01\n\x0bUpdateAsset\x122.google.cloud.visionai.v1alpha1.UpdateAssetRequest\x1a%.google.cloud.visionai.v1alpha1.Asset"c\xdaA\x11asset,update_mask\x82\xd3\xe4\x93\x02I2@/v1alpha1/{asset.name=projects/*/locations/*/corpora/*/assets/*}:\x05asset\x12\xad\x01\n\x08GetAsset\x12/.google.cloud.visionai.v1alpha1.GetAssetRequest\x1a%.google.cloud.visionai.v1alpha1.Asset"I\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}\x12\xc0\x01\n\nListAssets\x121.google.cloud.visionai.v1alpha1.ListAssetsRequest\x1a2.google.cloud.visionai.v1alpha1.ListAssetsResponse"K\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v1alpha1/{parent=projects/*/locations/*/corpora/*}/assets\x12\xda\x01\n\x0bDeleteAsset\x122.google.cloud.visionai.v1alpha1.DeleteAssetRequest\x1a\x1d.google.longrunning.Operation"x\xcaA,\n\x15google.protobuf.Empty\x12\x13DeleteAssetMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02<*:/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}\x12\xd6\x01\n\x0cCreateCorpus\x123.google.cloud.visionai.v1alpha1.CreateCorpusRequest\x1a\x1d.google.longrunning.Operation"r\xcaA\x1e\n\x06Corpus\x12\x14CreateCorpusMetadata\xdaA\rparent,corpus\x82\xd3\xe4\x93\x02;"1/v1alpha1/{parent=projects/*/locations/*}/corpora:\x06corpus\x12\xa7\x01\n\tGetCorpus\x120.google.cloud.visionai.v1alpha1.GetCorpusRequest\x1a&.google.cloud.visionai.v1alpha1.Corpus"@\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1alpha1/{name=projects/*/locations/*/corpora/*}\x12\xca\x01\n\x0cUpdateCorpus\x123.google.cloud.visionai.v1alpha1.UpdateCorpusRequest\x1a&.google.cloud.visionai.v1alpha1.Corpus"]\xdaA\x12corpus,update_mask\x82\xd3\xe4\x93\x02B28/v1alpha1/{corpus.name=projects/*/locations/*/corpora/*}:\x06corpus\x12\xba\x01\n\x0bListCorpora\x122.google.cloud.visionai.v1alpha1.ListCorporaRequest\x1a3.google.cloud.visionai.v1alpha1.ListCorporaResponse"B\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1alpha1/{parent=projects/*/locations/*}/corpora\x12\x9d\x01\n\x0cDeleteCorpus\x123.google.cloud.visionai.v1alpha1.DeleteCorpusRequest\x1a\x16.google.protobuf.Empty"@\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1alpha1/{name=projects/*/locations/*/corpora/*}\x12\xe2\x01\n\x10CreateDataSchema\x127.google.cloud.visionai.v1alpha1.CreateDataSchemaRequest\x1a*.google.cloud.visionai.v1alpha1.DataSchema"i\xdaA\x12parent,data_schema\x82\xd3\xe4\x93\x02N"?/v1alpha1/{parent=projects/*/locations/*/corpora/*}/dataSchemas:\x0bdata_schema\x12\xf3\x01\n\x10UpdateDataSchema\x127.google.cloud.visionai.v1alpha1.UpdateDataSchemaRequest\x1a*.google.cloud.visionai.v1alpha1.DataSchema"z\xdaA\x17data_schema,update_mask\x82\xd3\xe4\x93\x02Z2K/v1alpha1/{data_schema.name=projects/*/locations/*/corpora/*/dataSchemas/*}:\x0bdata_schema\x12\xc1\x01\n\rGetDataSchema\x124.google.cloud.visionai.v1alpha1.GetDataSchemaRequest\x1a*.google.cloud.visionai.v1alpha1.DataSchema"N\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1alpha1/{name=projects/*/locations/*/corpora/*/dataSchemas/*}\x12\xb3\x01\n\x10DeleteDataSchema\x127.google.cloud.visionai.v1alpha1.DeleteDataSchemaRequest\x1a\x16.google.protobuf.Empty"N\xdaA\x04name\x82\xd3\xe4\x93\x02A*?/v1alpha1/{name=projects/*/locations/*/corpora/*/dataSchemas/*}\x12\xd4\x01\n\x0fListDataSchemas\x126.google.cloud.visionai.v1alpha1.ListDataSchemasRequest\x1a7.google.cloud.visionai.v1alpha1.ListDataSchemasResponse"P\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1alpha1/{parent=projects/*/locations/*/corpora/*}/dataSchemas\x12\xf7\x01\n\x10CreateAnnotation\x127.google.cloud.visionai.v1alpha1.CreateAnnotationRequest\x1a*.google.cloud.visionai.v1alpha1.Annotation"~\xdaA\x1fparent,annotation,annotation_id\x82\xd3\xe4\x93\x02V"H/v1alpha1/{parent=projects/*/locations/*/corpora/*/assets/*}/annotations:\nannotation\x12\xca\x01\n\rGetAnnotation\x124.google.cloud.visionai.v1alpha1.GetAnnotationRequest\x1a*.google.cloud.visionai.v1alpha1.Annotation"W\xdaA\x04name\x82\xd3\xe4\x93\x02J\x12H/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*/annotations/*}\x12\xdd\x01\n\x0fListAnnotations\x126.google.cloud.visionai.v1alpha1.ListAnnotationsRequest\x1a7.google.cloud.visionai.v1alpha1.ListAnnotationsResponse"Y\xdaA\x06parent\x82\xd3\xe4\x93\x02J\x12H/v1alpha1/{parent=projects/*/locations/*/corpora/*/assets/*}/annotations\x12\xfa\x01\n\x10UpdateAnnotation\x127.google.cloud.visionai.v1alpha1.UpdateAnnotationRequest\x1a*.google.cloud.visionai.v1alpha1.Annotation"\x80\x01\xdaA\x16annotation,update_mask\x82\xd3\xe4\x93\x02a2S/v1alpha1/{annotation.name=projects/*/locations/*/corpora/*/assets/*/annotations/*}:\nannotation\x12\xbc\x01\n\x10DeleteAnnotation\x127.google.cloud.visionai.v1alpha1.DeleteAnnotationRequest\x1a\x16.google.protobuf.Empty"W\xdaA\x04name\x82\xd3\xe4\x93\x02J*H/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*/annotations/*}\x12|\n\x0bIngestAsset\x122.google.cloud.visionai.v1alpha1.IngestAssetRequest\x1a3.google.cloud.visionai.v1alpha1.IngestAssetResponse"\x00(\x010\x01\x12\xbc\x01\n\tClipAsset\x120.google.cloud.visionai.v1alpha1.ClipAssetRequest\x1a1.google.cloud.visionai.v1alpha1.ClipAssetResponse"J\x82\xd3\xe4\x93\x02D"?/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}:clip:\x01*\x12\xd5\x01\n\x0eGenerateHlsUri\x125.google.cloud.visionai.v1alpha1.GenerateHlsUriRequest\x1a6.google.cloud.visionai.v1alpha1.GenerateHlsUriResponse"T\x82\xd3\xe4\x93\x02N"I/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}:generateHlsUri:\x01*\x12\x80\x02\n\x12CreateSearchConfig\x129.google.cloud.visionai.v1alpha1.CreateSearchConfigRequest\x1a,.google.cloud.visionai.v1alpha1.SearchConfig"\x80\x01\xdaA%parent,search_config,search_config_id\x82\xd3\xe4\x93\x02R"A/v1alpha1/{parent=projects/*/locations/*/corpora/*}/searchConfigs:\rsearch_config\x12\x82\x02\n\x12UpdateSearchConfig\x129.google.cloud.visionai.v1alpha1.UpdateSearchConfigRequest\x1a,.google.cloud.visionai.v1alpha1.SearchConfig"\x82\x01\xdaA\x19search_config,update_mask\x82\xd3\xe4\x93\x02`2O/v1alpha1/{search_config.name=projects/*/locations/*/corpora/*/searchConfigs/*}:\rsearch_config\x12\xc9\x01\n\x0fGetSearchConfig\x126.google.cloud.visionai.v1alpha1.GetSearchConfigRequest\x1a,.google.cloud.visionai.v1alpha1.SearchConfig"P\xdaA\x04name\x82\xd3\xe4\x93\x02C\x12A/v1alpha1/{name=projects/*/locations/*/corpora/*/searchConfigs/*}\x12\xb9\x01\n\x12DeleteSearchConfig\x129.google.cloud.visionai.v1alpha1.DeleteSearchConfigRequest\x1a\x16.google.protobuf.Empty"P\xdaA\x04name\x82\xd3\xe4\x93\x02C*A/v1alpha1/{name=projects/*/locations/*/corpora/*/searchConfigs/*}\x12\xdc\x01\n\x11ListSearchConfigs\x128.google.cloud.visionai.v1alpha1.ListSearchConfigsRequest\x1a9.google.cloud.visionai.v1alpha1.ListSearchConfigsResponse"R\xdaA\x06parent\x82\xd3\xe4\x93\x02C\x12A/v1alpha1/{parent=projects/*/locations/*/corpora/*}/searchConfigs\x12\xc6\x01\n\x0cSearchAssets\x123.google.cloud.visionai.v1alpha1.SearchAssetsRequest\x1a4.google.cloud.visionai.v1alpha1.SearchAssetsResponse"K\x82\xd3\xe4\x93\x02E"@/v1alpha1/{corpus=projects/*/locations/*/corpora/*}:searchAssets:\x01*\x1aK\xcaA\x17visionai.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xdc\x01\n"com.google.cloud.visionai.v1alpha1B\x0eWarehouseProtoP\x01Z>cloud.google.com/go/visionai/apiv1alpha1/visionaipb;visionaipb\xaa\x02\x1eGoogle.Cloud.VisionAI.V1Alpha1\xca\x02\x1eGoogle\\Cloud\\VisionAI\\V1alpha1\xea\x02!Google::Cloud::VisionAI::V1alpha1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.visionai.v1alpha1.warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n"com.google.cloud.visionai.v1alpha1B\x0eWarehouseProtoP\x01Z>cloud.google.com/go/visionai/apiv1alpha1/visionaipb;visionaipb\xaa\x02\x1eGoogle.Cloud.VisionAI.V1Alpha1\xca\x02\x1eGoogle\\Cloud\\VisionAI\\V1alpha1\xea\x02!Google::Cloud::VisionAI::V1alpha1'
    _globals['_CREATEASSETREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEASSETREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus'
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset']._loaded_options = None
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset_id']._loaded_options = None
    _globals['_CREATEASSETREQUEST'].fields_by_name['asset_id']._serialized_options = b'\xe0A\x01'
    _globals['_GETASSETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETASSETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset'
    _globals['_LISTASSETSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTASSETSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1f\x12\x1dvisionai.googleapis.com/Asset'
    _globals['_UPDATEASSETREQUEST'].fields_by_name['asset']._loaded_options = None
    _globals['_UPDATEASSETREQUEST'].fields_by_name['asset']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEASSETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEASSETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset'
    _globals['_ASSET']._loaded_options = None
    _globals['_ASSET']._serialized_options = b'\xeaAo\n\x1dvisionai.googleapis.com/Asset\x12Nprojects/{project_number}/locations/{location}/corpora/{corpus}/assets/{asset}'
    _globals['_CREATECORPUSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECORPUSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECORPUSREQUEST'].fields_by_name['corpus']._loaded_options = None
    _globals['_CREATECORPUSREQUEST'].fields_by_name['corpus']._serialized_options = b'\xe0A\x02'
    _globals['_CORPUS'].fields_by_name['display_name']._loaded_options = None
    _globals['_CORPUS'].fields_by_name['display_name']._serialized_options = b'\xe0A\x02'
    _globals['_CORPUS'].fields_by_name['description']._loaded_options = None
    _globals['_CORPUS'].fields_by_name['description']._serialized_options = b'\xe0A\x01'
    _globals['_CORPUS'].fields_by_name['default_ttl']._loaded_options = None
    _globals['_CORPUS'].fields_by_name['default_ttl']._serialized_options = b'\xe0A\x02'
    _globals['_CORPUS']._loaded_options = None
    _globals['_CORPUS']._serialized_options = b'\xeaAa\n\x1evisionai.googleapis.com/Corpus\x12?projects/{project_number}/locations/{location}/corpora/{corpus}'
    _globals['_GETCORPUSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCORPUSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus'
    _globals['_UPDATECORPUSREQUEST'].fields_by_name['corpus']._loaded_options = None
    _globals['_UPDATECORPUSREQUEST'].fields_by_name['corpus']._serialized_options = b'\xe0A\x02'
    _globals['_LISTCORPORAREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCORPORAREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_DELETECORPUSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECORPUSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus'
    _globals['_CREATEDATASCHEMAREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEDATASCHEMAREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus'
    _globals['_CREATEDATASCHEMAREQUEST'].fields_by_name['data_schema']._loaded_options = None
    _globals['_CREATEDATASCHEMAREQUEST'].fields_by_name['data_schema']._serialized_options = b'\xe0A\x02'
    _globals['_DATASCHEMA'].fields_by_name['key']._loaded_options = None
    _globals['_DATASCHEMA'].fields_by_name['key']._serialized_options = b'\xe0A\x02'
    _globals['_DATASCHEMA']._loaded_options = None
    _globals['_DATASCHEMA']._serialized_options = b'\xeaA\x7f\n"visionai.googleapis.com/DataSchema\x12Yprojects/{project_number}/locations/{location}/corpora/{corpus}/dataSchemas/{data_schema}'
    _globals['_UPDATEDATASCHEMAREQUEST'].fields_by_name['data_schema']._loaded_options = None
    _globals['_UPDATEDATASCHEMAREQUEST'].fields_by_name['data_schema']._serialized_options = b'\xe0A\x02'
    _globals['_GETDATASCHEMAREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETDATASCHEMAREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"visionai.googleapis.com/DataSchema'
    _globals['_DELETEDATASCHEMAREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEDATASCHEMAREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"visionai.googleapis.com/DataSchema'
    _globals['_LISTDATASCHEMASREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTDATASCHEMASREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"visionai.googleapis.com/DataSchema'
    _globals['_CREATEANNOTATIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEANNOTATIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset'
    _globals['_CREATEANNOTATIONREQUEST'].fields_by_name['annotation']._loaded_options = None
    _globals['_CREATEANNOTATIONREQUEST'].fields_by_name['annotation']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEANNOTATIONREQUEST'].fields_by_name['annotation_id']._loaded_options = None
    _globals['_CREATEANNOTATIONREQUEST'].fields_by_name['annotation_id']._serialized_options = b'\xe0A\x01'
    _globals['_ANNOTATION']._loaded_options = None
    _globals['_ANNOTATION']._serialized_options = b'\xeaA\x8d\x01\n"visionai.googleapis.com/Annotation\x12gprojects/{project_number}/locations/{location}/corpora/{corpus}/assets/{asset}/annotations/{annotation}'
    _globals['_USERSPECIFIEDANNOTATION'].fields_by_name['key']._loaded_options = None
    _globals['_USERSPECIFIEDANNOTATION'].fields_by_name['key']._serialized_options = b'\xe0A\x02'
    _globals['_LISTANNOTATIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTANNOTATIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset'
    _globals['_GETANNOTATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETANNOTATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"visionai.googleapis.com/Annotation'
    _globals['_UPDATEANNOTATIONREQUEST'].fields_by_name['annotation']._loaded_options = None
    _globals['_UPDATEANNOTATIONREQUEST'].fields_by_name['annotation']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEANNOTATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEANNOTATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"visionai.googleapis.com/Annotation'
    _globals['_CREATESEARCHCONFIGREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESEARCHCONFIGREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$visionai.googleapis.com/SearchConfig'
    _globals['_CREATESEARCHCONFIGREQUEST'].fields_by_name['search_config']._loaded_options = None
    _globals['_CREATESEARCHCONFIGREQUEST'].fields_by_name['search_config']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESEARCHCONFIGREQUEST'].fields_by_name['search_config_id']._loaded_options = None
    _globals['_CREATESEARCHCONFIGREQUEST'].fields_by_name['search_config_id']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESEARCHCONFIGREQUEST'].fields_by_name['search_config']._loaded_options = None
    _globals['_UPDATESEARCHCONFIGREQUEST'].fields_by_name['search_config']._serialized_options = b'\xe0A\x02'
    _globals['_GETSEARCHCONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSEARCHCONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$visionai.googleapis.com/SearchConfig'
    _globals['_DELETESEARCHCONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESEARCHCONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$visionai.googleapis.com/SearchConfig'
    _globals['_LISTSEARCHCONFIGSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSEARCHCONFIGSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\x12$visionai.googleapis.com/SearchConfig'
    _globals['_SEARCHCONFIG']._loaded_options = None
    _globals['_SEARCHCONFIG']._serialized_options = b'\xeaA\x85\x01\n$visionai.googleapis.com/SearchConfig\x12]projects/{project_number}/locations/{location}/corpora/{corpus}/searchConfigs/{search_config}'
    _globals['_INGESTASSETREQUEST_CONFIG'].fields_by_name['asset']._loaded_options = None
    _globals['_INGESTASSETREQUEST_CONFIG'].fields_by_name['asset']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset'
    _globals['_CLIPASSETREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CLIPASSETREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset'
    _globals['_CLIPASSETREQUEST'].fields_by_name['temporal_partition']._loaded_options = None
    _globals['_CLIPASSETREQUEST'].fields_by_name['temporal_partition']._serialized_options = b'\xe0A\x02'
    _globals['_GENERATEHLSURIREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GENERATEHLSURIREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1f\n\x1dvisionai.googleapis.com/Asset'
    _globals['_GENERATEHLSURIREQUEST'].fields_by_name['temporal_partitions']._loaded_options = None
    _globals['_GENERATEHLSURIREQUEST'].fields_by_name['temporal_partitions']._serialized_options = b'\xe0A\x02'
    _globals['_SEARCHASSETSREQUEST'].fields_by_name['corpus']._loaded_options = None
    _globals['_SEARCHASSETSREQUEST'].fields_by_name['corpus']._serialized_options = b'\xe0A\x02\xfaA \n\x1evisionai.googleapis.com/Corpus'
    _globals['_SEARCHRESULTITEM'].fields_by_name['segments']._loaded_options = None
    _globals['_SEARCHRESULTITEM'].fields_by_name['segments']._serialized_options = b'\x18\x01'
    _globals['_WAREHOUSE']._loaded_options = None
    _globals['_WAREHOUSE']._serialized_options = b'\xcaA\x17visionai.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_WAREHOUSE'].methods_by_name['CreateAsset']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['CreateAsset']._serialized_options = b'\xdaA\x15parent,asset,asset_id\x82\xd3\xe4\x93\x02C":/v1alpha1/{parent=projects/*/locations/*/corpora/*}/assets:\x05asset'
    _globals['_WAREHOUSE'].methods_by_name['UpdateAsset']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['UpdateAsset']._serialized_options = b'\xdaA\x11asset,update_mask\x82\xd3\xe4\x93\x02I2@/v1alpha1/{asset.name=projects/*/locations/*/corpora/*/assets/*}:\x05asset'
    _globals['_WAREHOUSE'].methods_by_name['GetAsset']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['GetAsset']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}'
    _globals['_WAREHOUSE'].methods_by_name['ListAssets']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['ListAssets']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v1alpha1/{parent=projects/*/locations/*/corpora/*}/assets'
    _globals['_WAREHOUSE'].methods_by_name['DeleteAsset']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['DeleteAsset']._serialized_options = b'\xcaA,\n\x15google.protobuf.Empty\x12\x13DeleteAssetMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02<*:/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}'
    _globals['_WAREHOUSE'].methods_by_name['CreateCorpus']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['CreateCorpus']._serialized_options = b'\xcaA\x1e\n\x06Corpus\x12\x14CreateCorpusMetadata\xdaA\rparent,corpus\x82\xd3\xe4\x93\x02;"1/v1alpha1/{parent=projects/*/locations/*}/corpora:\x06corpus'
    _globals['_WAREHOUSE'].methods_by_name['GetCorpus']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['GetCorpus']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x023\x121/v1alpha1/{name=projects/*/locations/*/corpora/*}'
    _globals['_WAREHOUSE'].methods_by_name['UpdateCorpus']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['UpdateCorpus']._serialized_options = b'\xdaA\x12corpus,update_mask\x82\xd3\xe4\x93\x02B28/v1alpha1/{corpus.name=projects/*/locations/*/corpora/*}:\x06corpus'
    _globals['_WAREHOUSE'].methods_by_name['ListCorpora']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['ListCorpora']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x023\x121/v1alpha1/{parent=projects/*/locations/*}/corpora'
    _globals['_WAREHOUSE'].methods_by_name['DeleteCorpus']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['DeleteCorpus']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x023*1/v1alpha1/{name=projects/*/locations/*/corpora/*}'
    _globals['_WAREHOUSE'].methods_by_name['CreateDataSchema']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['CreateDataSchema']._serialized_options = b'\xdaA\x12parent,data_schema\x82\xd3\xe4\x93\x02N"?/v1alpha1/{parent=projects/*/locations/*/corpora/*}/dataSchemas:\x0bdata_schema'
    _globals['_WAREHOUSE'].methods_by_name['UpdateDataSchema']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['UpdateDataSchema']._serialized_options = b'\xdaA\x17data_schema,update_mask\x82\xd3\xe4\x93\x02Z2K/v1alpha1/{data_schema.name=projects/*/locations/*/corpora/*/dataSchemas/*}:\x0bdata_schema'
    _globals['_WAREHOUSE'].methods_by_name['GetDataSchema']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['GetDataSchema']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1alpha1/{name=projects/*/locations/*/corpora/*/dataSchemas/*}'
    _globals['_WAREHOUSE'].methods_by_name['DeleteDataSchema']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['DeleteDataSchema']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02A*?/v1alpha1/{name=projects/*/locations/*/corpora/*/dataSchemas/*}'
    _globals['_WAREHOUSE'].methods_by_name['ListDataSchemas']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['ListDataSchemas']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1alpha1/{parent=projects/*/locations/*/corpora/*}/dataSchemas'
    _globals['_WAREHOUSE'].methods_by_name['CreateAnnotation']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['CreateAnnotation']._serialized_options = b'\xdaA\x1fparent,annotation,annotation_id\x82\xd3\xe4\x93\x02V"H/v1alpha1/{parent=projects/*/locations/*/corpora/*/assets/*}/annotations:\nannotation'
    _globals['_WAREHOUSE'].methods_by_name['GetAnnotation']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['GetAnnotation']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02J\x12H/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*/annotations/*}'
    _globals['_WAREHOUSE'].methods_by_name['ListAnnotations']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['ListAnnotations']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02J\x12H/v1alpha1/{parent=projects/*/locations/*/corpora/*/assets/*}/annotations'
    _globals['_WAREHOUSE'].methods_by_name['UpdateAnnotation']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['UpdateAnnotation']._serialized_options = b'\xdaA\x16annotation,update_mask\x82\xd3\xe4\x93\x02a2S/v1alpha1/{annotation.name=projects/*/locations/*/corpora/*/assets/*/annotations/*}:\nannotation'
    _globals['_WAREHOUSE'].methods_by_name['DeleteAnnotation']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['DeleteAnnotation']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02J*H/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*/annotations/*}'
    _globals['_WAREHOUSE'].methods_by_name['ClipAsset']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['ClipAsset']._serialized_options = b'\x82\xd3\xe4\x93\x02D"?/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}:clip:\x01*'
    _globals['_WAREHOUSE'].methods_by_name['GenerateHlsUri']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['GenerateHlsUri']._serialized_options = b'\x82\xd3\xe4\x93\x02N"I/v1alpha1/{name=projects/*/locations/*/corpora/*/assets/*}:generateHlsUri:\x01*'
    _globals['_WAREHOUSE'].methods_by_name['CreateSearchConfig']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['CreateSearchConfig']._serialized_options = b'\xdaA%parent,search_config,search_config_id\x82\xd3\xe4\x93\x02R"A/v1alpha1/{parent=projects/*/locations/*/corpora/*}/searchConfigs:\rsearch_config'
    _globals['_WAREHOUSE'].methods_by_name['UpdateSearchConfig']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['UpdateSearchConfig']._serialized_options = b'\xdaA\x19search_config,update_mask\x82\xd3\xe4\x93\x02`2O/v1alpha1/{search_config.name=projects/*/locations/*/corpora/*/searchConfigs/*}:\rsearch_config'
    _globals['_WAREHOUSE'].methods_by_name['GetSearchConfig']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['GetSearchConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02C\x12A/v1alpha1/{name=projects/*/locations/*/corpora/*/searchConfigs/*}'
    _globals['_WAREHOUSE'].methods_by_name['DeleteSearchConfig']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['DeleteSearchConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02C*A/v1alpha1/{name=projects/*/locations/*/corpora/*/searchConfigs/*}'
    _globals['_WAREHOUSE'].methods_by_name['ListSearchConfigs']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['ListSearchConfigs']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02C\x12A/v1alpha1/{parent=projects/*/locations/*/corpora/*}/searchConfigs'
    _globals['_WAREHOUSE'].methods_by_name['SearchAssets']._loaded_options = None
    _globals['_WAREHOUSE'].methods_by_name['SearchAssets']._serialized_options = b'\x82\xd3\xe4\x93\x02E"@/v1alpha1/{corpus=projects/*/locations/*/corpora/*}:searchAssets:\x01*'
    _globals['_FACETBUCKETTYPE']._serialized_start = 12692
    _globals['_FACETBUCKETTYPE']._serialized_end = 12876
    _globals['_CREATEASSETREQUEST']._serialized_start = 473
    _globals['_CREATEASSETREQUEST']._serialized_end = 649
    _globals['_GETASSETREQUEST']._serialized_start = 651
    _globals['_GETASSETREQUEST']._serialized_end = 721
    _globals['_LISTASSETSREQUEST']._serialized_start = 723
    _globals['_LISTASSETSREQUEST']._serialized_end = 836
    _globals['_LISTASSETSRESPONSE']._serialized_start = 838
    _globals['_LISTASSETSRESPONSE']._serialized_end = 938
    _globals['_UPDATEASSETREQUEST']._serialized_start = 941
    _globals['_UPDATEASSETREQUEST']._serialized_end = 1069
    _globals['_DELETEASSETREQUEST']._serialized_start = 1071
    _globals['_DELETEASSETREQUEST']._serialized_end = 1144
    _globals['_ASSET']._serialized_start = 1147
    _globals['_ASSET']._serialized_end = 1324
    _globals['_CREATECORPUSREQUEST']._serialized_start = 1326
    _globals['_CREATECORPUSREQUEST']._serialized_end = 1429
    _globals['_CREATECORPUSMETADATA']._serialized_start = 1431
    _globals['_CREATECORPUSMETADATA']._serialized_end = 1453
    _globals['_CORPUS']._serialized_start = 1456
    _globals['_CORPUS']._serialized_end = 1686
    _globals['_GETCORPUSREQUEST']._serialized_start = 1688
    _globals['_GETCORPUSREQUEST']._serialized_end = 1760
    _globals['_UPDATECORPUSREQUEST']._serialized_start = 1763
    _globals['_UPDATECORPUSREQUEST']._serialized_end = 1894
    _globals['_LISTCORPORAREQUEST']._serialized_start = 1896
    _globals['_LISTCORPORAREQUEST']._serialized_end = 1976
    _globals['_LISTCORPORARESPONSE']._serialized_start = 1978
    _globals['_LISTCORPORARESPONSE']._serialized_end = 2081
    _globals['_DELETECORPUSREQUEST']._serialized_start = 2083
    _globals['_DELETECORPUSREQUEST']._serialized_end = 2158
    _globals['_CREATEDATASCHEMAREQUEST']._serialized_start = 2161
    _globals['_CREATEDATASCHEMAREQUEST']._serialized_end = 2312
    _globals['_DATASCHEMA']._serialized_start = 2315
    _globals['_DATASCHEMA']._serialized_end = 2567
    _globals['_DATASCHEMADETAILS']._serialized_start = 2570
    _globals['_DATASCHEMADETAILS']._serialized_end = 3417
    _globals['_DATASCHEMADETAILS_PROTOANYCONFIG']._serialized_start = 2932
    _globals['_DATASCHEMADETAILS_PROTOANYCONFIG']._serialized_end = 2966
    _globals['_DATASCHEMADETAILS_SEARCHSTRATEGY']._serialized_start = 2969
    _globals['_DATASCHEMADETAILS_SEARCHSTRATEGY']._serialized_end = 3173
    _globals['_DATASCHEMADETAILS_SEARCHSTRATEGY_SEARCHSTRATEGYTYPE']._serialized_start = 3102
    _globals['_DATASCHEMADETAILS_SEARCHSTRATEGY_SEARCHSTRATEGYTYPE']._serialized_end = 3173
    _globals['_DATASCHEMADETAILS_DATATYPE']._serialized_start = 3176
    _globals['_DATASCHEMADETAILS_DATATYPE']._serialized_end = 3311
    _globals['_DATASCHEMADETAILS_GRANULARITY']._serialized_start = 3313
    _globals['_DATASCHEMADETAILS_GRANULARITY']._serialized_end = 3417
    _globals['_UPDATEDATASCHEMAREQUEST']._serialized_start = 3420
    _globals['_UPDATEDATASCHEMAREQUEST']._serialized_end = 3564
    _globals['_GETDATASCHEMAREQUEST']._serialized_start = 3566
    _globals['_GETDATASCHEMAREQUEST']._serialized_end = 3646
    _globals['_DELETEDATASCHEMAREQUEST']._serialized_start = 3648
    _globals['_DELETEDATASCHEMAREQUEST']._serialized_end = 3731
    _globals['_LISTDATASCHEMASREQUEST']._serialized_start = 3733
    _globals['_LISTDATASCHEMASREQUEST']._serialized_end = 3856
    _globals['_LISTDATASCHEMASRESPONSE']._serialized_start = 3858
    _globals['_LISTDATASCHEMASRESPONSE']._serialized_end = 3974
    _globals['_CREATEANNOTATIONREQUEST']._serialized_start = 3977
    _globals['_CREATEANNOTATIONREQUEST']._serialized_end = 4177
    _globals['_ANNOTATION']._serialized_start = 4180
    _globals['_ANNOTATION']._serialized_end = 4446
    _globals['_USERSPECIFIEDANNOTATION']._serialized_start = 4449
    _globals['_USERSPECIFIEDANNOTATION']._serialized_end = 4618
    _globals['_GEOCOORDINATE']._serialized_start = 4620
    _globals['_GEOCOORDINATE']._serialized_end = 4672
    _globals['_ANNOTATIONVALUE']._serialized_start = 4675
    _globals['_ANNOTATIONVALUE']._serialized_end = 5001
    _globals['_LISTANNOTATIONSREQUEST']._serialized_start = 5004
    _globals['_LISTANNOTATIONSREQUEST']._serialized_end = 5135
    _globals['_LISTANNOTATIONSRESPONSE']._serialized_start = 5137
    _globals['_LISTANNOTATIONSRESPONSE']._serialized_end = 5252
    _globals['_GETANNOTATIONREQUEST']._serialized_start = 5254
    _globals['_GETANNOTATIONREQUEST']._serialized_end = 5334
    _globals['_UPDATEANNOTATIONREQUEST']._serialized_start = 5337
    _globals['_UPDATEANNOTATIONREQUEST']._serialized_end = 5480
    _globals['_DELETEANNOTATIONREQUEST']._serialized_start = 5482
    _globals['_DELETEANNOTATIONREQUEST']._serialized_end = 5565
    _globals['_CREATESEARCHCONFIGREQUEST']._serialized_start = 5568
    _globals['_CREATESEARCHCONFIGREQUEST']._serialized_end = 5762
    _globals['_UPDATESEARCHCONFIGREQUEST']._serialized_start = 5765
    _globals['_UPDATESEARCHCONFIGREQUEST']._serialized_end = 5915
    _globals['_GETSEARCHCONFIGREQUEST']._serialized_start = 5917
    _globals['_GETSEARCHCONFIGREQUEST']._serialized_end = 6001
    _globals['_DELETESEARCHCONFIGREQUEST']._serialized_start = 6003
    _globals['_DELETESEARCHCONFIGREQUEST']._serialized_end = 6090
    _globals['_LISTSEARCHCONFIGSREQUEST']._serialized_start = 6092
    _globals['_LISTSEARCHCONFIGSREQUEST']._serialized_end = 6219
    _globals['_LISTSEARCHCONFIGSRESPONSE']._serialized_start = 6221
    _globals['_LISTSEARCHCONFIGSRESPONSE']._serialized_end = 6343
    _globals['_SEARCHCONFIG']._serialized_start = 6346
    _globals['_SEARCHCONFIG']._serialized_end = 6675
    _globals['_FACETPROPERTY']._serialized_start = 6678
    _globals['_FACETPROPERTY']._serialized_end = 7626
    _globals['_FACETPROPERTY_FIXEDRANGEBUCKETSPEC']._serialized_start = 7138
    _globals['_FACETPROPERTY_FIXEDRANGEBUCKETSPEC']._serialized_end = 7320
    _globals['_FACETPROPERTY_CUSTOMRANGEBUCKETSPEC']._serialized_start = 7322
    _globals['_FACETPROPERTY_CUSTOMRANGEBUCKETSPEC']._serialized_end = 7408
    _globals['_FACETPROPERTY_DATETIMEBUCKETSPEC']._serialized_start = 7411
    _globals['_FACETPROPERTY_DATETIMEBUCKETSPEC']._serialized_end = 7604
    _globals['_FACETPROPERTY_DATETIMEBUCKETSPEC_GRANULARITY']._serialized_start = 7532
    _globals['_FACETPROPERTY_DATETIMEBUCKETSPEC_GRANULARITY']._serialized_end = 7604
    _globals['_SEARCHCRITERIAPROPERTY']._serialized_start = 7628
    _globals['_SEARCHCRITERIAPROPERTY']._serialized_end = 7675
    _globals['_FACETVALUE']._serialized_start = 7677
    _globals['_FACETVALUE']._serialized_end = 7796
    _globals['_FACETBUCKET']._serialized_start = 7799
    _globals['_FACETBUCKET']._serialized_end = 8100
    _globals['_FACETBUCKET_RANGE']._serialized_start = 7961
    _globals['_FACETBUCKET_RANGE']._serialized_end = 8084
    _globals['_FACETGROUP']._serialized_start = 8103
    _globals['_FACETGROUP']._serialized_end = 8322
    _globals['_INGESTASSETREQUEST']._serialized_start = 8325
    _globals['_INGESTASSETREQUEST']._serialized_end = 9035
    _globals['_INGESTASSETREQUEST_CONFIG']._serialized_start = 8522
    _globals['_INGESTASSETREQUEST_CONFIG']._serialized_end = 8892
    _globals['_INGESTASSETREQUEST_CONFIG_VIDEOTYPE']._serialized_start = 8678
    _globals['_INGESTASSETREQUEST_CONFIG_VIDEOTYPE']._serialized_end = 8879
    _globals['_INGESTASSETREQUEST_CONFIG_VIDEOTYPE_CONTAINERFORMAT']._serialized_start = 8802
    _globals['_INGESTASSETREQUEST_CONFIG_VIDEOTYPE_CONTAINERFORMAT']._serialized_end = 8879
    _globals['_INGESTASSETREQUEST_TIMEINDEXEDDATA']._serialized_start = 8894
    _globals['_INGESTASSETREQUEST_TIMEINDEXEDDATA']._serialized_end = 9014
    _globals['_INGESTASSETRESPONSE']._serialized_start = 9037
    _globals['_INGESTASSETRESPONSE']._serialized_end = 9160
    _globals['_CLIPASSETREQUEST']._serialized_start = 9163
    _globals['_CLIPASSETREQUEST']._serialized_end = 9328
    _globals['_CLIPASSETRESPONSE']._serialized_start = 9331
    _globals['_CLIPASSETRESPONSE']._serialized_end = 9563
    _globals['_CLIPASSETRESPONSE_TIMEINDEXEDURI']._serialized_start = 9445
    _globals['_CLIPASSETRESPONSE_TIMEINDEXEDURI']._serialized_end = 9563
    _globals['_GENERATEHLSURIREQUEST']._serialized_start = 9566
    _globals['_GENERATEHLSURIREQUEST']._serialized_end = 9737
    _globals['_GENERATEHLSURIRESPONSE']._serialized_start = 9739
    _globals['_GENERATEHLSURIRESPONSE']._serialized_end = 9866
    _globals['_SEARCHASSETSREQUEST']._serialized_start = 9869
    _globals['_SEARCHASSETSREQUEST']._serialized_end = 10228
    _globals['_DELETEASSETMETADATA']._serialized_start = 10230
    _globals['_DELETEASSETMETADATA']._serialized_end = 10251
    _globals['_ANNOTATIONMATCHINGRESULT']._serialized_start = 10254
    _globals['_ANNOTATIONMATCHINGRESULT']._serialized_end = 10449
    _globals['_SEARCHRESULTITEM']._serialized_start = 10452
    _globals['_SEARCHRESULTITEM']._serialized_end = 10816
    _globals['_SEARCHASSETSRESPONSE']._serialized_start = 10819
    _globals['_SEARCHASSETSRESPONSE']._serialized_end = 11012
    _globals['_INTRANGE']._serialized_start = 11014
    _globals['_INTRANGE']._serialized_end = 11080
    _globals['_FLOATRANGE']._serialized_start = 11082
    _globals['_FLOATRANGE']._serialized_end = 11150
    _globals['_STRINGARRAY']._serialized_start = 11152
    _globals['_STRINGARRAY']._serialized_end = 11185
    _globals['_INTRANGEARRAY']._serialized_start = 11187
    _globals['_INTRANGEARRAY']._serialized_end = 11264
    _globals['_FLOATRANGEARRAY']._serialized_start = 11266
    _globals['_FLOATRANGEARRAY']._serialized_end = 11349
    _globals['_DATETIMERANGE']._serialized_start = 11351
    _globals['_DATETIMERANGE']._serialized_end = 11440
    _globals['_DATETIMERANGEARRAY']._serialized_start = 11442
    _globals['_DATETIMERANGEARRAY']._serialized_end = 11535
    _globals['_CIRCLEAREA']._serialized_start = 11537
    _globals['_CIRCLEAREA']._serialized_end = 11608
    _globals['_GEOLOCATIONARRAY']._serialized_start = 11610
    _globals['_GEOLOCATIONARRAY']._serialized_end = 11694
    _globals['_BOOLVALUE']._serialized_start = 11696
    _globals['_BOOLVALUE']._serialized_end = 11722
    _globals['_CRITERIA']._serialized_start = 11725
    _globals['_CRITERIA']._serialized_end = 12243
    _globals['_PARTITION']._serialized_start = 12246
    _globals['_PARTITION']._serialized_end = 12689
    _globals['_PARTITION_TEMPORALPARTITION']._serialized_start = 12435
    _globals['_PARTITION_TEMPORALPARTITION']._serialized_end = 12548
    _globals['_PARTITION_SPATIALPARTITION']._serialized_start = 12551
    _globals['_PARTITION_SPATIALPARTITION']._serialized_end = 12689
    _globals['_WAREHOUSE']._serialized_start = 12879
    _globals['_WAREHOUSE']._serialized_end = 18974