"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/datastream/v1/datastream.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.datastream.v1 import datastream_resources_pb2 as google_dot_cloud_dot_datastream_dot_v1_dot_datastream__resources__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+google/cloud/datastream/v1/datastream.proto\x12\x1agoogle.cloud.datastream.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a5google/cloud/datastream/v1/datastream_resources.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xd1\x05\n DiscoverConnectionProfileRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+datastream.googleapis.com/ConnectionProfile\x12L\n\x12connection_profile\x18\xc8\x01 \x01(\x0b2-.google.cloud.datastream.v1.ConnectionProfileH\x00\x12"\n\x17connection_profile_name\x18\xc9\x01 \x01(\tH\x00\x12\x18\n\x0efull_hierarchy\x18\x03 \x01(\x08H\x01\x12\x19\n\x0fhierarchy_depth\x18\x04 \x01(\x05H\x01\x12?\n\x0coracle_rdbms\x18d \x01(\x0b2\'.google.cloud.datastream.v1.OracleRdbmsH\x02\x12=\n\x0bmysql_rdbms\x18e \x01(\x0b2&.google.cloud.datastream.v1.MysqlRdbmsH\x02\x12G\n\x10postgresql_rdbms\x18f \x01(\x0b2+.google.cloud.datastream.v1.PostgresqlRdbmsH\x02\x12F\n\x10sql_server_rdbms\x18g \x01(\x0b2*.google.cloud.datastream.v1.SqlServerRdbmsH\x02\x12C\n\x0esalesforce_org\x18h \x01(\x0b2).google.cloud.datastream.v1.SalesforceOrgH\x02\x12E\n\x0fmongodb_cluster\x18i \x01(\x0b2*.google.cloud.datastream.v1.MongodbClusterH\x02B\x08\n\x06targetB\x0b\n\thierarchyB\r\n\x0bdata_object"\xcf\x03\n!DiscoverConnectionProfileResponse\x12?\n\x0coracle_rdbms\x18d \x01(\x0b2\'.google.cloud.datastream.v1.OracleRdbmsH\x00\x12=\n\x0bmysql_rdbms\x18e \x01(\x0b2&.google.cloud.datastream.v1.MysqlRdbmsH\x00\x12G\n\x10postgresql_rdbms\x18f \x01(\x0b2+.google.cloud.datastream.v1.PostgresqlRdbmsH\x00\x12F\n\x10sql_server_rdbms\x18g \x01(\x0b2*.google.cloud.datastream.v1.SqlServerRdbmsH\x00\x12C\n\x0esalesforce_org\x18h \x01(\x0b2).google.cloud.datastream.v1.SalesforceOrgH\x00\x12E\n\x0fmongodb_cluster\x18i \x01(\x0b2*.google.cloud.datastream.v1.MongodbClusterH\x00B\r\n\x0bdata_object"w\n\x15FetchStaticIpsRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"E\n\x16FetchStaticIpsResponse\x12\x12\n\nstatic_ips\x18\x01 \x03(\t\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xad\x01\n\x1dListConnectionProfilesRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+datastream.googleapis.com/ConnectionProfile\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"\x9a\x01\n\x1eListConnectionProfilesResponse\x12J\n\x13connection_profiles\x18\x01 \x03(\x0b2-.google.cloud.datastream.v1.ConnectionProfile\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"`\n\x1bGetConnectionProfileRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+datastream.googleapis.com/ConnectionProfile"\xa2\x02\n\x1eCreateConnectionProfileRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+datastream.googleapis.com/ConnectionProfile\x12"\n\x15connection_profile_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12N\n\x12connection_profile\x18\x03 \x01(\x0b2-.google.cloud.datastream.v1.ConnectionProfileB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x05 \x01(\x08B\x03\xe0A\x01\x12\x12\n\x05force\x18\x06 \x01(\x08B\x03\xe0A\x01"\xef\x01\n\x1eUpdateConnectionProfileRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12N\n\x12connection_profile\x18\x02 \x01(\x0b2-.google.cloud.datastream.v1.ConnectionProfileB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01\x12\x12\n\x05force\x18\x05 \x01(\x08B\x03\xe0A\x01"|\n\x1eDeleteConnectionProfileRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+datastream.googleapis.com/ConnectionProfile\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\x97\x01\n\x12ListStreamsRequest\x128\n\x06parent\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\x12 datastream.googleapis.com/Stream\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"x\n\x13ListStreamsResponse\x123\n\x07streams\x18\x01 \x03(\x0b2".google.cloud.datastream.v1.Stream\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"J\n\x10GetStreamRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream"\xe9\x01\n\x13CreateStreamRequest\x128\n\x06parent\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\x12 datastream.googleapis.com/Stream\x12\x16\n\tstream_id\x18\x02 \x01(\tB\x03\xe0A\x02\x127\n\x06stream\x18\x03 \x01(\x0b2".google.cloud.datastream.v1.StreamB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x05 \x01(\x08B\x03\xe0A\x01\x12\x12\n\x05force\x18\x06 \x01(\x08B\x03\xe0A\x01"\xcd\x01\n\x13UpdateStreamRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x127\n\x06stream\x18\x02 \x01(\x0b2".google.cloud.datastream.v1.StreamB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x04 \x01(\x08B\x03\xe0A\x01\x12\x12\n\x05force\x18\x05 \x01(\x08B\x03\xe0A\x01"f\n\x13DeleteStreamRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\xa2\x01\n\x10RunStreamRequest\x126\n\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream\x12B\n\x0ccdc_strategy\x18\x02 \x01(\x0b2\'.google.cloud.datastream.v1.CdcStrategyB\x03\xe0A\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"V\n\x16GetStreamObjectRequest\x12<\n\x04name\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&datastream.googleapis.com/StreamObject"\xb0\x01\n\x19LookupStreamObjectRequest\x128\n\x06parent\x18\x01 \x01(\tB(\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream\x12Y\n\x18source_object_identifier\x18\x02 \x01(\x0b22.google.cloud.datastream.v1.SourceObjectIdentifierB\x03\xe0A\x02"Y\n\x17StartBackfillJobRequest\x12>\n\x06object\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&datastream.googleapis.com/StreamObject"T\n\x18StartBackfillJobResponse\x128\n\x06object\x18\x01 \x01(\x0b2(.google.cloud.datastream.v1.StreamObject"X\n\x16StopBackfillJobRequest\x12>\n\x06object\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\n&datastream.googleapis.com/StreamObject"S\n\x17StopBackfillJobResponse\x128\n\x06object\x18\x01 \x01(\x0b2(.google.cloud.datastream.v1.StreamObject"\x81\x01\n\x18ListStreamObjectsRequest\x12>\n\x06parent\x18\x01 \x01(\tB.\xe0A\x02\xfaA(\x12&datastream.googleapis.com/StreamObject\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"v\n\x19ListStreamObjectsResponse\x12@\n\x0estream_objects\x18\x01 \x03(\x0b2(.google.cloud.datastream.v1.StreamObject\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xce\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x03\x12L\n\x11validation_result\x18\x08 \x01(\x0b2,.google.cloud.datastream.v1.ValidationResultB\x03\xe0A\x03"\xa2\x02\n\x1eCreatePrivateConnectionRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+datastream.googleapis.com/PrivateConnection\x12"\n\x15private_connection_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12N\n\x12private_connection\x18\x03 \x01(\x0b2-.google.cloud.datastream.v1.PrivateConnectionB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05force\x18\x06 \x01(\x08B\x03\xe0A\x01\x12\x1a\n\rvalidate_only\x18\x08 \x01(\x08B\x03\xe0A\x01"\xad\x01\n\x1dListPrivateConnectionsRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+datastream.googleapis.com/PrivateConnection\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"\x9a\x01\n\x1eListPrivateConnectionsResponse\x12J\n\x13private_connections\x18\x01 \x03(\x0b2-.google.cloud.datastream.v1.PrivateConnection\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\x90\x01\n\x1eDeletePrivateConnectionRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+datastream.googleapis.com/PrivateConnection\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05force\x18\x03 \x01(\x08B\x03\xe0A\x01"`\n\x1bGetPrivateConnectionRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+datastream.googleapis.com/PrivateConnection"\xb4\x01\n\x12CreateRouteRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1fdatastream.googleapis.com/Route\x12\x15\n\x08route_id\x18\x02 \x01(\tB\x03\xe0A\x02\x125\n\x05route\x18\x03 \x01(\x0b2!.google.cloud.datastream.v1.RouteB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01"\x95\x01\n\x11ListRoutesRequest\x127\n\x06parent\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\x12\x1fdatastream.googleapis.com/Route\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"u\n\x12ListRoutesResponse\x121\n\x06routes\x18\x01 \x03(\x0b2!.google.cloud.datastream.v1.Route\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"d\n\x12DeleteRouteRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fdatastream.googleapis.com/Route\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"H\n\x0fGetRouteRequest\x125\n\x04name\x18\x01 \x01(\tB\'\xe0A\x02\xfaA!\n\x1fdatastream.googleapis.com/Route2\xb2,\n\nDatastream\x12\xd8\x01\n\x16ListConnectionProfiles\x129.google.cloud.datastream.v1.ListConnectionProfilesRequest\x1a:.google.cloud.datastream.v1.ListConnectionProfilesResponse"G\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/locations/*}/connectionProfiles\x12\xc5\x01\n\x14GetConnectionProfile\x127.google.cloud.datastream.v1.GetConnectionProfileRequest\x1a-.google.cloud.datastream.v1.ConnectionProfile"E\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/locations/*/connectionProfiles/*}\x12\xa4\x02\n\x17CreateConnectionProfile\x12:.google.cloud.datastream.v1.CreateConnectionProfileRequest\x1a\x1d.google.longrunning.Operation"\xad\x01\xcaA&\n\x11ConnectionProfile\x12\x11OperationMetadata\xdaA/parent,connection_profile,connection_profile_id\x82\xd3\xe4\x93\x02L"6/v1/{parent=projects/*/locations/*}/connectionProfiles:\x12connection_profile\x12\xa6\x02\n\x17UpdateConnectionProfile\x12:.google.cloud.datastream.v1.UpdateConnectionProfileRequest\x1a\x1d.google.longrunning.Operation"\xaf\x01\xcaA&\n\x11ConnectionProfile\x12\x11OperationMetadata\xdaA\x1econnection_profile,update_mask\x82\xd3\xe4\x93\x02_2I/v1/{connection_profile.name=projects/*/locations/*/connectionProfiles/*}:\x12connection_profile\x12\xe8\x01\n\x17DeleteConnectionProfile\x12:.google.cloud.datastream.v1.DeleteConnectionProfileRequest\x1a\x1d.google.longrunning.Operation"r\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/locations/*/connectionProfiles/*}\x12\xe4\x01\n\x19DiscoverConnectionProfile\x12<.google.cloud.datastream.v1.DiscoverConnectionProfileRequest\x1a=.google.cloud.datastream.v1.DiscoverConnectionProfileResponse"J\x82\xd3\xe4\x93\x02D"?/v1/{parent=projects/*/locations/*}/connectionProfiles:discover:\x01*\x12\xac\x01\n\x0bListStreams\x12..google.cloud.datastream.v1.ListStreamsRequest\x1a/.google.cloud.datastream.v1.ListStreamsResponse"<\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=projects/*/locations/*}/streams\x12\x99\x01\n\tGetStream\x12,.google.cloud.datastream.v1.GetStreamRequest\x1a".google.cloud.datastream.v1.Stream":\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1/{name=projects/*/locations/*/streams/*}\x12\xd3\x01\n\x0cCreateStream\x12/.google.cloud.datastream.v1.CreateStreamRequest\x1a\x1d.google.longrunning.Operation"s\xcaA\x1b\n\x06Stream\x12\x11OperationMetadata\xdaA\x17parent,stream,stream_id\x82\xd3\xe4\x93\x025"+/v1/{parent=projects/*/locations/*}/streams:\x06stream\x12\xd5\x01\n\x0cUpdateStream\x12/.google.cloud.datastream.v1.UpdateStreamRequest\x1a\x1d.google.longrunning.Operation"u\xcaA\x1b\n\x06Stream\x12\x11OperationMetadata\xdaA\x12stream,update_mask\x82\xd3\xe4\x93\x02<22/v1/{stream.name=projects/*/locations/*/streams/*}:\x06stream\x12\xc7\x01\n\x0cDeleteStream\x12/.google.cloud.datastream.v1.DeleteStreamRequest\x1a\x1d.google.longrunning.Operation"g\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1/{name=projects/*/locations/*/streams/*}\x12\xb2\x01\n\tRunStream\x12,.google.cloud.datastream.v1.RunStreamRequest\x1a\x1d.google.longrunning.Operation"X\xcaA\x1b\n\x06Stream\x12\x11OperationMetadata\x82\xd3\xe4\x93\x024"//v1/{name=projects/*/locations/*/streams/*}:run:\x01*\x12\xb5\x01\n\x0fGetStreamObject\x122.google.cloud.datastream.v1.GetStreamObjectRequest\x1a(.google.cloud.datastream.v1.StreamObject"D\xdaA\x04name\x82\xd3\xe4\x93\x027\x125/v1/{name=projects/*/locations/*/streams/*/objects/*}\x12\xbe\x01\n\x12LookupStreamObject\x125.google.cloud.datastream.v1.LookupStreamObjectRequest\x1a(.google.cloud.datastream.v1.StreamObject"G\x82\xd3\xe4\x93\x02A"</v1/{parent=projects/*/locations/*/streams/*}/objects:lookup:\x01*\x12\xc8\x01\n\x11ListStreamObjects\x124.google.cloud.datastream.v1.ListStreamObjectsRequest\x1a5.google.cloud.datastream.v1.ListStreamObjectsResponse"F\xdaA\x06parent\x82\xd3\xe4\x93\x027\x125/v1/{parent=projects/*/locations/*/streams/*}/objects\x12\xdb\x01\n\x10StartBackfillJob\x123.google.cloud.datastream.v1.StartBackfillJobRequest\x1a4.google.cloud.datastream.v1.StartBackfillJobResponse"\\\xdaA\x06object\x82\xd3\xe4\x93\x02M"H/v1/{object=projects/*/locations/*/streams/*/objects/*}:startBackfillJob:\x01*\x12\xd7\x01\n\x0fStopBackfillJob\x122.google.cloud.datastream.v1.StopBackfillJobRequest\x1a3.google.cloud.datastream.v1.StopBackfillJobResponse"[\xdaA\x06object\x82\xd3\xe4\x93\x02L"G/v1/{object=projects/*/locations/*/streams/*/objects/*}:stopBackfillJob:\x01*\x12\xb8\x01\n\x0eFetchStaticIps\x121.google.cloud.datastream.v1.FetchStaticIpsRequest\x1a2.google.cloud.datastream.v1.FetchStaticIpsResponse"?\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*}:fetchStaticIps\x12\xa4\x02\n\x17CreatePrivateConnection\x12:.google.cloud.datastream.v1.CreatePrivateConnectionRequest\x1a\x1d.google.longrunning.Operation"\xad\x01\xcaA&\n\x11PrivateConnection\x12\x11OperationMetadata\xdaA/parent,private_connection,private_connection_id\x82\xd3\xe4\x93\x02L"6/v1/{parent=projects/*/locations/*}/privateConnections:\x12private_connection\x12\xc5\x01\n\x14GetPrivateConnection\x127.google.cloud.datastream.v1.GetPrivateConnectionRequest\x1a-.google.cloud.datastream.v1.PrivateConnection"E\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/locations/*/privateConnections/*}\x12\xd8\x01\n\x16ListPrivateConnections\x129.google.cloud.datastream.v1.ListPrivateConnectionsRequest\x1a:.google.cloud.datastream.v1.ListPrivateConnectionsResponse"G\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/locations/*}/privateConnections\x12\xe8\x01\n\x17DeletePrivateConnection\x12:.google.cloud.datastream.v1.DeletePrivateConnectionRequest\x1a\x1d.google.longrunning.Operation"r\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/locations/*/privateConnections/*}\x12\xe2\x01\n\x0bCreateRoute\x12..google.cloud.datastream.v1.CreateRouteRequest\x1a\x1d.google.longrunning.Operation"\x83\x01\xcaA\x1a\n\x05Route\x12\x11OperationMetadata\xdaA\x15parent,route,route_id\x82\xd3\xe4\x93\x02H"?/v1/{parent=projects/*/locations/*/privateConnections/*}/routes:\x05route\x12\xaa\x01\n\x08GetRoute\x12+.google.cloud.datastream.v1.GetRouteRequest\x1a!.google.cloud.datastream.v1.Route"N\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1/{name=projects/*/locations/*/privateConnections/*/routes/*}\x12\xbd\x01\n\nListRoutes\x12-.google.cloud.datastream.v1.ListRoutesRequest\x1a..google.cloud.datastream.v1.ListRoutesResponse"P\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/locations/*/privateConnections/*}/routes\x12\xd9\x01\n\x0bDeleteRoute\x12..google.cloud.datastream.v1.DeleteRouteRequest\x1a\x1d.google.longrunning.Operation"{\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02A*?/v1/{name=projects/*/locations/*/privateConnections/*/routes/*}\x1aM\xcaA\x19datastream.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xcd\x01\n\x1ecom.google.cloud.datastream.v1B\x0fDatastreamProtoP\x01Z>cloud.google.com/go/datastream/apiv1/datastreampb;datastreampb\xaa\x02\x1aGoogle.Cloud.Datastream.V1\xca\x02\x1aGoogle\\Cloud\\Datastream\\V1\xea\x02\x1dGoogle::Cloud::Datastream::V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.datastream.v1.datastream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1ecom.google.cloud.datastream.v1B\x0fDatastreamProtoP\x01Z>cloud.google.com/go/datastream/apiv1/datastreampb;datastreampb\xaa\x02\x1aGoogle.Cloud.Datastream.V1\xca\x02\x1aGoogle\\Cloud\\Datastream\\V1\xea\x02\x1dGoogle::Cloud::Datastream::V1'
    _globals['_DISCOVERCONNECTIONPROFILEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_DISCOVERCONNECTIONPROFILEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+datastream.googleapis.com/ConnectionProfile'
    _globals['_FETCHSTATICIPSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_FETCHSTATICIPSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTCONNECTIONPROFILESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCONNECTIONPROFILESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+datastream.googleapis.com/ConnectionProfile'
    _globals['_GETCONNECTIONPROFILEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCONNECTIONPROFILEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+datastream.googleapis.com/ConnectionProfile'
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+datastream.googleapis.com/ConnectionProfile'
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['connection_profile_id']._loaded_options = None
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['connection_profile_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['connection_profile']._loaded_options = None
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['connection_profile']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_CREATECONNECTIONPROFILEREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['connection_profile']._loaded_options = None
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['connection_profile']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_UPDATECONNECTIONPROFILEREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_DELETECONNECTIONPROFILEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECONNECTIONPROFILEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+datastream.googleapis.com/ConnectionProfile'
    _globals['_DELETECONNECTIONPROFILEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETECONNECTIONPROFILEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSTREAMSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSTREAMSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA"\x12 datastream.googleapis.com/Stream'
    _globals['_GETSTREAMREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSTREAMREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream'
    _globals['_CREATESTREAMREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESTREAMREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA"\x12 datastream.googleapis.com/Stream'
    _globals['_CREATESTREAMREQUEST'].fields_by_name['stream_id']._loaded_options = None
    _globals['_CREATESTREAMREQUEST'].fields_by_name['stream_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESTREAMREQUEST'].fields_by_name['stream']._loaded_options = None
    _globals['_CREATESTREAMREQUEST'].fields_by_name['stream']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESTREAMREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATESTREAMREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CREATESTREAMREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATESTREAMREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_CREATESTREAMREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_CREATESTREAMREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['stream']._loaded_options = None
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['stream']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_UPDATESTREAMREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_DELETESTREAMREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESTREAMREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream'
    _globals['_DELETESTREAMREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETESTREAMREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_RUNSTREAMREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RUNSTREAMREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream'
    _globals['_RUNSTREAMREQUEST'].fields_by_name['cdc_strategy']._loaded_options = None
    _globals['_RUNSTREAMREQUEST'].fields_by_name['cdc_strategy']._serialized_options = b'\xe0A\x01'
    _globals['_RUNSTREAMREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_RUNSTREAMREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_GETSTREAMOBJECTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSTREAMOBJECTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA(\n&datastream.googleapis.com/StreamObject'
    _globals['_LOOKUPSTREAMOBJECTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LOOKUPSTREAMOBJECTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA"\n datastream.googleapis.com/Stream'
    _globals['_LOOKUPSTREAMOBJECTREQUEST'].fields_by_name['source_object_identifier']._loaded_options = None
    _globals['_LOOKUPSTREAMOBJECTREQUEST'].fields_by_name['source_object_identifier']._serialized_options = b'\xe0A\x02'
    _globals['_STARTBACKFILLJOBREQUEST'].fields_by_name['object']._loaded_options = None
    _globals['_STARTBACKFILLJOBREQUEST'].fields_by_name['object']._serialized_options = b'\xe0A\x02\xfaA(\n&datastream.googleapis.com/StreamObject'
    _globals['_STOPBACKFILLJOBREQUEST'].fields_by_name['object']._loaded_options = None
    _globals['_STOPBACKFILLJOBREQUEST'].fields_by_name['object']._serialized_options = b'\xe0A\x02\xfaA(\n&datastream.googleapis.com/StreamObject'
    _globals['_LISTSTREAMOBJECTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSTREAMOBJECTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA(\x12&datastream.googleapis.com/StreamObject'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['validation_result']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['validation_result']._serialized_options = b'\xe0A\x03'
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+datastream.googleapis.com/PrivateConnection'
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['private_connection_id']._loaded_options = None
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['private_connection_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['private_connection']._loaded_options = None
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['private_connection']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_CREATEPRIVATECONNECTIONREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPRIVATECONNECTIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTPRIVATECONNECTIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+datastream.googleapis.com/PrivateConnection'
    _globals['_DELETEPRIVATECONNECTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEPRIVATECONNECTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+datastream.googleapis.com/PrivateConnection'
    _globals['_DELETEPRIVATECONNECTIONREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETEPRIVATECONNECTIONREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEPRIVATECONNECTIONREQUEST'].fields_by_name['force']._loaded_options = None
    _globals['_DELETEPRIVATECONNECTIONREQUEST'].fields_by_name['force']._serialized_options = b'\xe0A\x01'
    _globals['_GETPRIVATECONNECTIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPRIVATECONNECTIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+datastream.googleapis.com/PrivateConnection'
    _globals['_CREATEROUTEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEROUTEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1fdatastream.googleapis.com/Route'
    _globals['_CREATEROUTEREQUEST'].fields_by_name['route_id']._loaded_options = None
    _globals['_CREATEROUTEREQUEST'].fields_by_name['route_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEROUTEREQUEST'].fields_by_name['route']._loaded_options = None
    _globals['_CREATEROUTEREQUEST'].fields_by_name['route']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEROUTEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATEROUTEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_LISTROUTESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTROUTESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA!\x12\x1fdatastream.googleapis.com/Route'
    _globals['_DELETEROUTEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEROUTEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fdatastream.googleapis.com/Route'
    _globals['_DELETEROUTEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETEROUTEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_GETROUTEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETROUTEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA!\n\x1fdatastream.googleapis.com/Route'
    _globals['_DATASTREAM']._loaded_options = None
    _globals['_DATASTREAM']._serialized_options = b'\xcaA\x19datastream.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_DATASTREAM'].methods_by_name['ListConnectionProfiles']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['ListConnectionProfiles']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/locations/*}/connectionProfiles'
    _globals['_DATASTREAM'].methods_by_name['GetConnectionProfile']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['GetConnectionProfile']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/locations/*/connectionProfiles/*}'
    _globals['_DATASTREAM'].methods_by_name['CreateConnectionProfile']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['CreateConnectionProfile']._serialized_options = b'\xcaA&\n\x11ConnectionProfile\x12\x11OperationMetadata\xdaA/parent,connection_profile,connection_profile_id\x82\xd3\xe4\x93\x02L"6/v1/{parent=projects/*/locations/*}/connectionProfiles:\x12connection_profile'
    _globals['_DATASTREAM'].methods_by_name['UpdateConnectionProfile']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['UpdateConnectionProfile']._serialized_options = b'\xcaA&\n\x11ConnectionProfile\x12\x11OperationMetadata\xdaA\x1econnection_profile,update_mask\x82\xd3\xe4\x93\x02_2I/v1/{connection_profile.name=projects/*/locations/*/connectionProfiles/*}:\x12connection_profile'
    _globals['_DATASTREAM'].methods_by_name['DeleteConnectionProfile']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['DeleteConnectionProfile']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/locations/*/connectionProfiles/*}'
    _globals['_DATASTREAM'].methods_by_name['DiscoverConnectionProfile']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['DiscoverConnectionProfile']._serialized_options = b'\x82\xd3\xe4\x93\x02D"?/v1/{parent=projects/*/locations/*}/connectionProfiles:discover:\x01*'
    _globals['_DATASTREAM'].methods_by_name['ListStreams']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['ListStreams']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=projects/*/locations/*}/streams'
    _globals['_DATASTREAM'].methods_by_name['GetStream']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['GetStream']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1/{name=projects/*/locations/*/streams/*}'
    _globals['_DATASTREAM'].methods_by_name['CreateStream']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['CreateStream']._serialized_options = b'\xcaA\x1b\n\x06Stream\x12\x11OperationMetadata\xdaA\x17parent,stream,stream_id\x82\xd3\xe4\x93\x025"+/v1/{parent=projects/*/locations/*}/streams:\x06stream'
    _globals['_DATASTREAM'].methods_by_name['UpdateStream']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['UpdateStream']._serialized_options = b'\xcaA\x1b\n\x06Stream\x12\x11OperationMetadata\xdaA\x12stream,update_mask\x82\xd3\xe4\x93\x02<22/v1/{stream.name=projects/*/locations/*/streams/*}:\x06stream'
    _globals['_DATASTREAM'].methods_by_name['DeleteStream']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['DeleteStream']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1/{name=projects/*/locations/*/streams/*}'
    _globals['_DATASTREAM'].methods_by_name['RunStream']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['RunStream']._serialized_options = b'\xcaA\x1b\n\x06Stream\x12\x11OperationMetadata\x82\xd3\xe4\x93\x024"//v1/{name=projects/*/locations/*/streams/*}:run:\x01*'
    _globals['_DATASTREAM'].methods_by_name['GetStreamObject']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['GetStreamObject']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x027\x125/v1/{name=projects/*/locations/*/streams/*/objects/*}'
    _globals['_DATASTREAM'].methods_by_name['LookupStreamObject']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['LookupStreamObject']._serialized_options = b'\x82\xd3\xe4\x93\x02A"</v1/{parent=projects/*/locations/*/streams/*}/objects:lookup:\x01*'
    _globals['_DATASTREAM'].methods_by_name['ListStreamObjects']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['ListStreamObjects']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x027\x125/v1/{parent=projects/*/locations/*/streams/*}/objects'
    _globals['_DATASTREAM'].methods_by_name['StartBackfillJob']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['StartBackfillJob']._serialized_options = b'\xdaA\x06object\x82\xd3\xe4\x93\x02M"H/v1/{object=projects/*/locations/*/streams/*/objects/*}:startBackfillJob:\x01*'
    _globals['_DATASTREAM'].methods_by_name['StopBackfillJob']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['StopBackfillJob']._serialized_options = b'\xdaA\x06object\x82\xd3\xe4\x93\x02L"G/v1/{object=projects/*/locations/*/streams/*/objects/*}:stopBackfillJob:\x01*'
    _globals['_DATASTREAM'].methods_by_name['FetchStaticIps']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['FetchStaticIps']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*}:fetchStaticIps'
    _globals['_DATASTREAM'].methods_by_name['CreatePrivateConnection']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['CreatePrivateConnection']._serialized_options = b'\xcaA&\n\x11PrivateConnection\x12\x11OperationMetadata\xdaA/parent,private_connection,private_connection_id\x82\xd3\xe4\x93\x02L"6/v1/{parent=projects/*/locations/*}/privateConnections:\x12private_connection'
    _globals['_DATASTREAM'].methods_by_name['GetPrivateConnection']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['GetPrivateConnection']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1/{name=projects/*/locations/*/privateConnections/*}'
    _globals['_DATASTREAM'].methods_by_name['ListPrivateConnections']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['ListPrivateConnections']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1/{parent=projects/*/locations/*}/privateConnections'
    _globals['_DATASTREAM'].methods_by_name['DeletePrivateConnection']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['DeletePrivateConnection']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1/{name=projects/*/locations/*/privateConnections/*}'
    _globals['_DATASTREAM'].methods_by_name['CreateRoute']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['CreateRoute']._serialized_options = b'\xcaA\x1a\n\x05Route\x12\x11OperationMetadata\xdaA\x15parent,route,route_id\x82\xd3\xe4\x93\x02H"?/v1/{parent=projects/*/locations/*/privateConnections/*}/routes:\x05route'
    _globals['_DATASTREAM'].methods_by_name['GetRoute']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['GetRoute']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02A\x12?/v1/{name=projects/*/locations/*/privateConnections/*/routes/*}'
    _globals['_DATASTREAM'].methods_by_name['ListRoutes']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['ListRoutes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02A\x12?/v1/{parent=projects/*/locations/*/privateConnections/*}/routes'
    _globals['_DATASTREAM'].methods_by_name['DeleteRoute']._loaded_options = None
    _globals['_DATASTREAM'].methods_by_name['DeleteRoute']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02A*?/v1/{name=projects/*/locations/*/privateConnections/*/routes/*}'
    _globals['_DISCOVERCONNECTIONPROFILEREQUEST']._serialized_start = 379
    _globals['_DISCOVERCONNECTIONPROFILEREQUEST']._serialized_end = 1100
    _globals['_DISCOVERCONNECTIONPROFILERESPONSE']._serialized_start = 1103
    _globals['_DISCOVERCONNECTIONPROFILERESPONSE']._serialized_end = 1566
    _globals['_FETCHSTATICIPSREQUEST']._serialized_start = 1568
    _globals['_FETCHSTATICIPSREQUEST']._serialized_end = 1687
    _globals['_FETCHSTATICIPSRESPONSE']._serialized_start = 1689
    _globals['_FETCHSTATICIPSRESPONSE']._serialized_end = 1758
    _globals['_LISTCONNECTIONPROFILESREQUEST']._serialized_start = 1761
    _globals['_LISTCONNECTIONPROFILESREQUEST']._serialized_end = 1934
    _globals['_LISTCONNECTIONPROFILESRESPONSE']._serialized_start = 1937
    _globals['_LISTCONNECTIONPROFILESRESPONSE']._serialized_end = 2091
    _globals['_GETCONNECTIONPROFILEREQUEST']._serialized_start = 2093
    _globals['_GETCONNECTIONPROFILEREQUEST']._serialized_end = 2189
    _globals['_CREATECONNECTIONPROFILEREQUEST']._serialized_start = 2192
    _globals['_CREATECONNECTIONPROFILEREQUEST']._serialized_end = 2482
    _globals['_UPDATECONNECTIONPROFILEREQUEST']._serialized_start = 2485
    _globals['_UPDATECONNECTIONPROFILEREQUEST']._serialized_end = 2724
    _globals['_DELETECONNECTIONPROFILEREQUEST']._serialized_start = 2726
    _globals['_DELETECONNECTIONPROFILEREQUEST']._serialized_end = 2850
    _globals['_LISTSTREAMSREQUEST']._serialized_start = 2853
    _globals['_LISTSTREAMSREQUEST']._serialized_end = 3004
    _globals['_LISTSTREAMSRESPONSE']._serialized_start = 3006
    _globals['_LISTSTREAMSRESPONSE']._serialized_end = 3126
    _globals['_GETSTREAMREQUEST']._serialized_start = 3128
    _globals['_GETSTREAMREQUEST']._serialized_end = 3202
    _globals['_CREATESTREAMREQUEST']._serialized_start = 3205
    _globals['_CREATESTREAMREQUEST']._serialized_end = 3438
    _globals['_UPDATESTREAMREQUEST']._serialized_start = 3441
    _globals['_UPDATESTREAMREQUEST']._serialized_end = 3646
    _globals['_DELETESTREAMREQUEST']._serialized_start = 3648
    _globals['_DELETESTREAMREQUEST']._serialized_end = 3750
    _globals['_RUNSTREAMREQUEST']._serialized_start = 3753
    _globals['_RUNSTREAMREQUEST']._serialized_end = 3915
    _globals['_GETSTREAMOBJECTREQUEST']._serialized_start = 3917
    _globals['_GETSTREAMOBJECTREQUEST']._serialized_end = 4003
    _globals['_LOOKUPSTREAMOBJECTREQUEST']._serialized_start = 4006
    _globals['_LOOKUPSTREAMOBJECTREQUEST']._serialized_end = 4182
    _globals['_STARTBACKFILLJOBREQUEST']._serialized_start = 4184
    _globals['_STARTBACKFILLJOBREQUEST']._serialized_end = 4273
    _globals['_STARTBACKFILLJOBRESPONSE']._serialized_start = 4275
    _globals['_STARTBACKFILLJOBRESPONSE']._serialized_end = 4359
    _globals['_STOPBACKFILLJOBREQUEST']._serialized_start = 4361
    _globals['_STOPBACKFILLJOBREQUEST']._serialized_end = 4449
    _globals['_STOPBACKFILLJOBRESPONSE']._serialized_start = 4451
    _globals['_STOPBACKFILLJOBRESPONSE']._serialized_end = 4534
    _globals['_LISTSTREAMOBJECTSREQUEST']._serialized_start = 4537
    _globals['_LISTSTREAMOBJECTSREQUEST']._serialized_end = 4666
    _globals['_LISTSTREAMOBJECTSRESPONSE']._serialized_start = 4668
    _globals['_LISTSTREAMOBJECTSRESPONSE']._serialized_end = 4786
    _globals['_OPERATIONMETADATA']._serialized_start = 4789
    _globals['_OPERATIONMETADATA']._serialized_end = 5123
    _globals['_CREATEPRIVATECONNECTIONREQUEST']._serialized_start = 5126
    _globals['_CREATEPRIVATECONNECTIONREQUEST']._serialized_end = 5416
    _globals['_LISTPRIVATECONNECTIONSREQUEST']._serialized_start = 5419
    _globals['_LISTPRIVATECONNECTIONSREQUEST']._serialized_end = 5592
    _globals['_LISTPRIVATECONNECTIONSRESPONSE']._serialized_start = 5595
    _globals['_LISTPRIVATECONNECTIONSRESPONSE']._serialized_end = 5749
    _globals['_DELETEPRIVATECONNECTIONREQUEST']._serialized_start = 5752
    _globals['_DELETEPRIVATECONNECTIONREQUEST']._serialized_end = 5896
    _globals['_GETPRIVATECONNECTIONREQUEST']._serialized_start = 5898
    _globals['_GETPRIVATECONNECTIONREQUEST']._serialized_end = 5994
    _globals['_CREATEROUTEREQUEST']._serialized_start = 5997
    _globals['_CREATEROUTEREQUEST']._serialized_end = 6177
    _globals['_LISTROUTESREQUEST']._serialized_start = 6180
    _globals['_LISTROUTESREQUEST']._serialized_end = 6329
    _globals['_LISTROUTESRESPONSE']._serialized_start = 6331
    _globals['_LISTROUTESRESPONSE']._serialized_end = 6448
    _globals['_DELETEROUTEREQUEST']._serialized_start = 6450
    _globals['_DELETEROUTEREQUEST']._serialized_end = 6550
    _globals['_GETROUTEREQUEST']._serialized_start = 6552
    _globals['_GETROUTEREQUEST']._serialized_end = 6624
    _globals['_DATASTREAM']._serialized_start = 6627
    _globals['_DATASTREAM']._serialized_end = 12309