# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetMdbMysqlDatabaseResult',
    'AwaitableGetMdbMysqlDatabaseResult',
    'get_mdb_mysql_database',
    'get_mdb_mysql_database_output',
]

@pulumi.output_type
class GetMdbMysqlDatabaseResult:
    """
    A collection of values returned by getMdbMysqlDatabase.
    """
    def __init__(__self__, cluster_id=None, id=None, name=None):
        if cluster_id and not isinstance(cluster_id, str):
            raise TypeError("Expected argument 'cluster_id' to be a str")
        pulumi.set(__self__, "cluster_id", cluster_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> _builtins.str:
        """
        The MySQL cluster ID.
        """
        return pulumi.get(self, "cluster_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the database.
        """
        return pulumi.get(self, "name")


class AwaitableGetMdbMysqlDatabaseResult(GetMdbMysqlDatabaseResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMdbMysqlDatabaseResult(
            cluster_id=self.cluster_id,
            id=self.id,
            name=self.name)


def get_mdb_mysql_database(cluster_id: Optional[_builtins.str] = None,
                           name: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMdbMysqlDatabaseResult:
    """
    Get details from MySQL database at MySQL Cluster.

    ## Example Usage

    ```python
    import pulumi
    ```


    :param _builtins.str cluster_id: The MySQL cluster ID.
    :param _builtins.str name: The name of the database.
    """
    __args__ = dict()
    __args__['clusterId'] = cluster_id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('yandex:index/getMdbMysqlDatabase:getMdbMysqlDatabase', __args__, opts=opts, typ=GetMdbMysqlDatabaseResult).value

    return AwaitableGetMdbMysqlDatabaseResult(
        cluster_id=pulumi.get(__ret__, 'cluster_id'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_mdb_mysql_database_output(cluster_id: Optional[pulumi.Input[_builtins.str]] = None,
                                  name: Optional[pulumi.Input[_builtins.str]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMdbMysqlDatabaseResult]:
    """
    Get details from MySQL database at MySQL Cluster.

    ## Example Usage

    ```python
    import pulumi
    ```


    :param _builtins.str cluster_id: The MySQL cluster ID.
    :param _builtins.str name: The name of the database.
    """
    __args__ = dict()
    __args__['clusterId'] = cluster_id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('yandex:index/getMdbMysqlDatabase:getMdbMysqlDatabase', __args__, opts=opts, typ=GetMdbMysqlDatabaseResult)
    return __ret__.apply(lambda __response__: GetMdbMysqlDatabaseResult(
        cluster_id=pulumi.get(__response__, 'cluster_id'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
