# coding: utf-8

"""
    Phoenix API

    Base API for Glumanda and other services.

    The version of the OpenAPI document: Alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "noahENERGY-phoenix_sdk"
VERSION = "v3.2.1-rc.1"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Phoenix API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="https://gitlab.com/smart-building-solutions/phoenix",
    keywords=["OpenAPI", "OpenAPI-Generator", "Phoenix API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Base API for Glumanda and other services.
    """,  # noqa: E501
    package_data={"phoenix_sdk": ["py.typed"]},
)
