"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'google/cloud/channel/v1/service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.channel.v1 import billing_accounts_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_billing__accounts__pb2
from .....google.cloud.channel.v1 import channel_partner_links_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_channel__partner__links__pb2
from .....google.cloud.channel.v1 import common_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_common__pb2
from .....google.cloud.channel.v1 import customers_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_customers__pb2
from .....google.cloud.channel.v1 import entitlement_changes_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_entitlement__changes__pb2
from .....google.cloud.channel.v1 import entitlements_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_entitlements__pb2
from .....google.cloud.channel.v1 import offers_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_offers__pb2
from .....google.cloud.channel.v1 import operations_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_operations__pb2
from .....google.cloud.channel.v1 import products_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_products__pb2
from .....google.cloud.channel.v1 import repricing_pb2 as google_dot_cloud_dot_channel_dot_v1_dot_repricing__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%google/cloud/channel/v1/service.proto\x12\x17google.cloud.channel.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a.google/cloud/channel/v1/billing_accounts.proto\x1a3google/cloud/channel/v1/channel_partner_links.proto\x1a$google/cloud/channel/v1/common.proto\x1a\'google/cloud/channel/v1/customers.proto\x1a1google/cloud/channel/v1/entitlement_changes.proto\x1a*google/cloud/channel/v1/entitlements.proto\x1a$google/cloud/channel/v1/offers.proto\x1a(google/cloud/channel/v1/operations.proto\x1a&google/cloud/channel/v1/products.proto\x1a\'google/cloud/channel/v1/repricing.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto"t\n&CheckCloudIdentityAccountsExistRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x13\n\x06domain\x18\x02 \x01(\tB\x03\xe0A\x02\x12 \n\x13primary_admin_email\x18\x04 \x01(\tB\x03\xe0A\x01"\xf5\x01\n\x1cCloudIdentityCustomerAccount\x12\x10\n\x08existing\x18\x01 \x01(\x08\x12\r\n\x05owned\x18\x02 \x01(\x08\x12\x15\n\rcustomer_name\x18\x03 \x01(\t\x12"\n\x1acustomer_cloud_identity_id\x18\x04 \x01(\t\x12N\n\rcustomer_type\x18\x05 \x01(\x0e27.google.cloud.channel.v1.CloudIdentityInfo.CustomerType\x12)\n!channel_partner_cloud_identity_id\x18\x06 \x01(\t"\x81\x01\n\'CheckCloudIdentityAccountsExistResponse\x12V\n\x17cloud_identity_accounts\x18\x01 \x03(\x0b25.google.cloud.channel.v1.CloudIdentityCustomerAccount"q\n\x14ListCustomersRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"f\n\x15ListCustomersResponse\x124\n\tcustomers\x18\x01 \x03(\x0b2!.google.cloud.channel.v1.Customer\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"P\n\x12GetCustomerRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer"f\n\x15CreateCustomerRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x128\n\x08customer\x18\x02 \x01(\x0b2!.google.cloud.channel.v1.CustomerB\x03\xe0A\x02"\x82\x01\n\x15UpdateCustomerRequest\x128\n\x08customer\x18\x02 \x01(\x0b2!.google.cloud.channel.v1.CustomerB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x03 \x01(\x0b2\x1a.google.protobuf.FieldMask"S\n\x15DeleteCustomerRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer"\xba\x02\n\x15ImportCustomerRequest\x12\x15\n\x06domain\x18\x02 \x01(\tB\x03\xe0A\x02H\x00\x12 \n\x11cloud_identity_id\x18\x03 \x01(\tB\x03\xe0A\x02H\x00\x12"\n\x13primary_admin_email\x18\x08 \x01(\tB\x03\xe0A\x02H\x00\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nauth_token\x18\x04 \x01(\tB\x03\xe0A\x01\x12 \n\x13overwrite_if_exists\x18\x05 \x01(\x08B\x03\xe0A\x02\x12\x1f\n\x12channel_partner_id\x18\x06 \x01(\tB\x03\xe0A\x01\x12>\n\x08customer\x18\x07 \x01(\tB,\xe0A\x01\xfaA&\n$cloudchannel.googleapis.com/CustomerB\x13\n\x11customer_identity"\xf1\x01\n\x1dProvisionCloudIdentityRequest\x12>\n\x08customer\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12G\n\x13cloud_identity_info\x18\x02 \x01(\x0b2*.google.cloud.channel.v1.CloudIdentityInfo\x120\n\x04user\x18\x03 \x01(\x0b2".google.cloud.channel.v1.AdminUser\x12\x15\n\rvalidate_only\x18\x04 \x01(\x08"\x88\x01\n\x17ListEntitlementsRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"o\n\x18ListEntitlementsResponse\x12:\n\x0centitlements\x18\x01 \x03(\x0b2$.google.cloud.channel.v1.Entitlement\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xe0\x01\n\x1bListTransferableSkusRequest\x12\x1b\n\x11cloud_identity_id\x18\x04 \x01(\tH\x00\x12\x17\n\rcustomer_name\x18\x07 \x01(\tH\x00\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x17\n\nauth_token\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x15\n\rlanguage_code\x18\x06 \x01(\tB\x1f\n\x1dtransferred_customer_identity"|\n\x1cListTransferableSkusResponse\x12C\n\x11transferable_skus\x18\x01 \x03(\x0b2(.google.cloud.channel.v1.TransferableSku\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xfe\x01\n\x1dListTransferableOffersRequest\x12\x1b\n\x11cloud_identity_id\x18\x04 \x01(\tH\x00\x12\x17\n\rcustomer_name\x18\x05 \x01(\tH\x00\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x03sku\x18\x06 \x01(\tB\x03\xe0A\x02\x12\x1a\n\rlanguage_code\x18\x07 \x01(\tB\x03\xe0A\x01\x12\x1c\n\x0fbilling_account\x18\x08 \x01(\tB\x03\xe0A\x01B\x1f\n\x1dtransferred_customer_identity"\x82\x01\n\x1eListTransferableOffersResponse\x12G\n\x13transferable_offers\x18\x01 \x03(\x0b2*.google.cloud.channel.v1.TransferableOffer\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"B\n\x11TransferableOffer\x12-\n\x05offer\x18\x01 \x01(\x0b2\x1e.google.cloud.channel.v1.Offer"V\n\x15GetEntitlementRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'cloudchannel.googleapis.com/Entitlement"\xaa\x01\n\x1eListChannelPartnerLinksRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12B\n\x04view\x18\x04 \x01(\x0e2/.google.cloud.channel.v1.ChannelPartnerLinkViewB\x03\xe0A\x01"\x86\x01\n\x1fListChannelPartnerLinksResponse\x12J\n\x15channel_partner_links\x18\x01 \x03(\x0b2+.google.cloud.channel.v1.ChannelPartnerLink\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"u\n\x1cGetChannelPartnerLinkRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12B\n\x04view\x18\x02 \x01(\x0e2/.google.cloud.channel.v1.ChannelPartnerLinkViewB\x03\xe0A\x01"\x86\x01\n\x1fCreateChannelPartnerLinkRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12N\n\x14channel_partner_link\x18\x02 \x01(\x0b2+.google.cloud.channel.v1.ChannelPartnerLinkB\x03\xe0A\x02"\xba\x01\n\x1fUpdateChannelPartnerLinkRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12N\n\x14channel_partner_link\x18\x02 \x01(\x0b2+.google.cloud.channel.v1.ChannelPartnerLinkB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x03 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"n\n!GetCustomerRepricingConfigRequest\x12I\n\x04name\x18\x01 \x01(\tB;\xe0A\x02\xfaA5\n3cloudchannel.googleapis.com/CustomerRepricingConfig"\xa9\x01\n#ListCustomerRepricingConfigsRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"\x95\x01\n$ListCustomerRepricingConfigsResponse\x12T\n\x1acustomer_repricing_configs\x18\x01 \x03(\x0b20.google.cloud.channel.v1.CustomerRepricingConfig\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xbe\x01\n$CreateCustomerRepricingConfigRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12X\n\x19customer_repricing_config\x18\x02 \x01(\x0b20.google.cloud.channel.v1.CustomerRepricingConfigB\x03\xe0A\x02"\x80\x01\n$UpdateCustomerRepricingConfigRequest\x12X\n\x19customer_repricing_config\x18\x01 \x01(\x0b20.google.cloud.channel.v1.CustomerRepricingConfigB\x03\xe0A\x02"q\n$DeleteCustomerRepricingConfigRequest\x12I\n\x04name\x18\x01 \x01(\tB;\xe0A\x02\xfaA5\n3cloudchannel.googleapis.com/CustomerRepricingConfig"z\n\'GetChannelPartnerRepricingConfigRequest\x12O\n\x04name\x18\x01 \x01(\tBA\xe0A\x02\xfaA;\n9cloudchannel.googleapis.com/ChannelPartnerRepricingConfig"\xb9\x01\n)ListChannelPartnerRepricingConfigsRequest\x12F\n\x06parent\x18\x01 \x01(\tB6\xe0A\x02\xfaA0\n.cloudchannel.googleapis.com/ChannelPartnerLink\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"\xa8\x01\n*ListChannelPartnerRepricingConfigsResponse\x12a\n!channel_partner_repricing_configs\x18\x01 \x03(\x0b26.google.cloud.channel.v1.ChannelPartnerRepricingConfig\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xdb\x01\n*CreateChannelPartnerRepricingConfigRequest\x12F\n\x06parent\x18\x01 \x01(\tB6\xe0A\x02\xfaA0\n.cloudchannel.googleapis.com/ChannelPartnerLink\x12e\n channel_partner_repricing_config\x18\x02 \x01(\x0b26.google.cloud.channel.v1.ChannelPartnerRepricingConfigB\x03\xe0A\x02"\x93\x01\n*UpdateChannelPartnerRepricingConfigRequest\x12e\n channel_partner_repricing_config\x18\x01 \x01(\x0b26.google.cloud.channel.v1.ChannelPartnerRepricingConfigB\x03\xe0A\x02"}\n*DeleteChannelPartnerRepricingConfigRequest\x12O\n\x04name\x18\x01 \x01(\tBA\xe0A\x02\xfaA;\n9cloudchannel.googleapis.com/ChannelPartnerRepricingConfig"\\\n\x14ListSkuGroupsRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"\x90\x01\n\x1fListSkuGroupBillableSkusRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/SkuGroup\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"g\n\x15ListSkuGroupsResponse\x125\n\nsku_groups\x18\x01 \x03(\x0b2!.google.cloud.channel.v1.SkuGroup\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"x\n ListSkuGroupBillableSkusResponse\x12;\n\rbillable_skus\x18\x01 \x03(\x0b2$.google.cloud.channel.v1.BillableSku\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\x83\x01\n\x08SkuGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cdisplay_name\x18\x02 \x01(\t:S\xeaAP\n$cloudchannel.googleapis.com/SkuGroup\x12(accounts/{account}/skuGroups/{sku_group}"c\n\x0bBillableSku\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x18\n\x10sku_display_name\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x1c\n\x14service_display_name\x18\x04 \x01(\t"\xb1\x01\n\x18CreateEntitlementRequest\x12<\n\x06parent\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12>\n\x0bentitlement\x18\x02 \x01(\x0b2$.google.cloud.channel.v1.EntitlementB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x05 \x01(\tB\x03\xe0A\x01"\xa0\x01\n\x1bTransferEntitlementsRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12?\n\x0centitlements\x18\x02 \x03(\x0b2$.google.cloud.channel.v1.EntitlementB\x03\xe0A\x02\x12\x12\n\nauth_token\x18\x04 \x01(\t\x12\x17\n\nrequest_id\x18\x06 \x01(\tB\x03\xe0A\x01"Z\n\x1cTransferEntitlementsResponse\x12:\n\x0centitlements\x18\x01 \x03(\x0b2$.google.cloud.channel.v1.Entitlement"\x94\x01\n#TransferEntitlementsToGoogleRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12?\n\x0centitlements\x18\x02 \x03(\x0b2$.google.cloud.channel.v1.EntitlementB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"\xa2\x01\n\x17ChangeParametersRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12;\n\nparameters\x18\x02 \x03(\x0b2".google.cloud.channel.v1.ParameterB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x1e\n\x11purchase_order_id\x18\x05 \x01(\tB\x03\xe0A\x01"\x93\x01\n\x1cChangeRenewalSettingsRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12G\n\x10renewal_settings\x18\x04 \x01(\x0b2(.google.cloud.channel.v1.RenewalSettingsB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x05 \x01(\tB\x03\xe0A\x01"\xf5\x01\n\x12ChangeOfferRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x128\n\x05offer\x18\x02 \x01(\tB)\xe0A\x02\xfaA#\n!cloudchannel.googleapis.com/Offer\x12;\n\nparameters\x18\x03 \x03(\x0b2".google.cloud.channel.v1.ParameterB\x03\xe0A\x01\x12\x1e\n\x11purchase_order_id\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x17\n\nrequest_id\x18\x06 \x01(\tB\x03\xe0A\x01\x12\x1c\n\x0fbilling_account\x18\x07 \x01(\tB\x03\xe0A\x01"E\n\x17StartPaidServiceRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"F\n\x18CancelEntitlementRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"G\n\x19SuspendEntitlementRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"H\n\x1aActivateEntitlementRequest\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x03 \x01(\tB\x03\xe0A\x01"Z\n\x12LookupOfferRequest\x12D\n\x0bentitlement\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'cloudchannel.googleapis.com/Entitlement"x\n\x13ListProductsRequest\x12\x14\n\x07account\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rlanguage_code\x18\x04 \x01(\tB\x03\xe0A\x01"c\n\x14ListProductsResponse\x122\n\x08products\x18\x01 \x03(\x0b2 .google.cloud.channel.v1.Product\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb1\x01\n\x0fListSkusRequest\x12;\n\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#cloudchannel.googleapis.com/Product\x12\x14\n\x07account\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x16\n\tpage_size\x18\x03 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rlanguage_code\x18\x05 \x01(\tB\x03\xe0A\x01"W\n\x10ListSkusResponse\x12*\n\x04skus\x18\x01 \x03(\x0b2\x1c.google.cloud.channel.v1.Sku\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xab\x01\n\x11ListOffersRequest\x12\x13\n\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rlanguage_code\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x1f\n\x12show_future_offers\x18\x07 \x01(\x08B\x03\xe0A\x01"]\n\x12ListOffersResponse\x12.\n\x06offers\x18\x01 \x03(\x0b2\x1e.google.cloud.channel.v1.Offer\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb6\x05\n\x1aListPurchasableSkusRequest\x12t\n\x1bcreate_entitlement_purchase\x18\x02 \x01(\x0b2M.google.cloud.channel.v1.ListPurchasableSkusRequest.CreateEntitlementPurchaseH\x00\x12h\n\x15change_offer_purchase\x18\x03 \x01(\x0b2G.google.cloud.channel.v1.ListPurchasableSkusRequest.ChangeOfferPurchaseH\x00\x12>\n\x08customer\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12\x16\n\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rlanguage_code\x18\x06 \x01(\tB\x03\xe0A\x01\x1a1\n\x19CreateEntitlementPurchase\x12\x14\n\x07product\x18\x01 \x01(\tB\x03\xe0A\x02\x1a\xe4\x01\n\x13ChangeOfferPurchase\x12\x18\n\x0bentitlement\x18\x01 \x01(\tB\x03\xe0A\x02\x12l\n\x0bchange_type\x18\x02 \x01(\x0e2R.google.cloud.channel.v1.ListPurchasableSkusRequest.ChangeOfferPurchase.ChangeTypeB\x03\xe0A\x02"E\n\nChangeType\x12\x1b\n\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07UPGRADE\x10\x01\x12\r\n\tDOWNGRADE\x10\x02B\x11\n\x0fpurchase_option"y\n\x1bListPurchasableSkusResponse\x12A\n\x10purchasable_skus\x18\x01 \x03(\x0b2\'.google.cloud.channel.v1.PurchasableSku\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t";\n\x0ePurchasableSku\x12)\n\x03sku\x18\x01 \x01(\x0b2\x1c.google.cloud.channel.v1.Sku"\xd4\x04\n\x1cListPurchasableOffersRequest\x12v\n\x1bcreate_entitlement_purchase\x18\x02 \x01(\x0b2O.google.cloud.channel.v1.ListPurchasableOffersRequest.CreateEntitlementPurchaseH\x00\x12j\n\x15change_offer_purchase\x18\x03 \x01(\x0b2I.google.cloud.channel.v1.ListPurchasableOffersRequest.ChangeOfferPurchaseH\x00\x12>\n\x08customer\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12\x16\n\tpage_size\x18\x04 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rlanguage_code\x18\x06 \x01(\tB\x03\xe0A\x01\x1aK\n\x19CreateEntitlementPurchase\x12\x10\n\x03sku\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x1c\n\x0fbilling_account\x18\x02 \x01(\tB\x03\xe0A\x01\x1ac\n\x13ChangeOfferPurchase\x12\x18\n\x0bentitlement\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x14\n\x07new_sku\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x1c\n\x0fbilling_account\x18\x03 \x01(\tB\x03\xe0A\x01B\x11\n\x0fpurchase_option"\x7f\n\x1dListPurchasableOffersResponse\x12E\n\x12purchasable_offers\x18\x01 \x03(\x0b2).google.cloud.channel.v1.PurchasableOffer\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"A\n\x10PurchasableOffer\x12-\n\x05offer\x18\x01 \x01(\x0b2\x1e.google.cloud.channel.v1.Offer"x\n#QueryEligibleBillingAccountsRequest\x12>\n\x08customer\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer\x12\x11\n\x04skus\x18\x02 \x03(\tB\x03\xe0A\x02"n\n$QueryEligibleBillingAccountsResponse\x12F\n\x13sku_purchase_groups\x18\x01 \x03(\x0b2).google.cloud.channel.v1.SkuPurchaseGroup"}\n\x10SkuPurchaseGroup\x12\x0c\n\x04skus\x18\x01 \x03(\t\x12[\n\x1ebilling_account_purchase_infos\x18\x02 \x03(\x0b23.google.cloud.channel.v1.BillingAccountPurchaseInfo"^\n\x1aBillingAccountPurchaseInfo\x12@\n\x0fbilling_account\x18\x01 \x01(\x0b2\'.google.cloud.channel.v1.BillingAccount"O\n\x19RegisterSubscriberRequest\x12\x14\n\x07account\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x1c\n\x0fservice_account\x18\x02 \x01(\tB\x03\xe0A\x02"+\n\x1aRegisterSubscriberResponse\x12\r\n\x05topic\x18\x01 \x01(\t"Q\n\x1bUnregisterSubscriberRequest\x12\x14\n\x07account\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x1c\n\x0fservice_account\x18\x02 \x01(\tB\x03\xe0A\x02"-\n\x1cUnregisterSubscriberResponse\x12\r\n\x05topic\x18\x01 \x01(\t"_\n\x16ListSubscribersRequest\x12\x14\n\x07account\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"[\n\x17ListSubscribersResponse\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x18\n\x10service_accounts\x18\x02 \x03(\t\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t"\xa6\x01\n\x1dListEntitlementChangesRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'cloudchannel.googleapis.com/Entitlement\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"\x82\x01\n\x1eListEntitlementChangesResponse\x12G\n\x13entitlement_changes\x18\x01 \x03(\x0b2*.google.cloud.channel.v1.EntitlementChange\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xc5R\n\x13CloudChannelService\x12\xd4\x01\n\rListCustomers\x12-.google.cloud.channel.v1.ListCustomersRequest\x1a..google.cloud.channel.v1.ListCustomersResponse"d\x82\xd3\xe4\x93\x02^\x12!/v1/{parent=accounts/*}/customersZ9\x127/v1/{parent=accounts/*/channelPartnerLinks/*}/customers\x12\xca\x01\n\x0bGetCustomer\x12+.google.cloud.channel.v1.GetCustomerRequest\x1a!.google.cloud.channel.v1.Customer"k\xdaA\x04name\x82\xd3\xe4\x93\x02^\x12!/v1/{name=accounts/*/customers/*}Z9\x127/v1/{name=accounts/*/channelPartnerLinks/*/customers/*}\x12\xe8\x01\n\x1fCheckCloudIdentityAccountsExist\x12?.google.cloud.channel.v1.CheckCloudIdentityAccountsExistRequest\x1a@.google.cloud.channel.v1.CheckCloudIdentityAccountsExistResponse"B\x82\xd3\xe4\x93\x02<"7/v1/{parent=accounts/*}:checkCloudIdentityAccountsExist:\x01*\x12\xdd\x01\n\x0eCreateCustomer\x12..google.cloud.channel.v1.CreateCustomerRequest\x1a!.google.cloud.channel.v1.Customer"x\x82\xd3\xe4\x93\x02r"!/v1/{parent=accounts/*}/customers:\x08customerZC"7/v1/{parent=accounts/*/channelPartnerLinks/*}/customers:\x08customer\x12\xf1\x01\n\x0eUpdateCustomer\x12..google.cloud.channel.v1.UpdateCustomerRequest\x1a!.google.cloud.channel.v1.Customer"\x8b\x01\x82\xd3\xe4\x93\x02\x84\x012*/v1/{customer.name=accounts/*/customers/*}:\x08customerZL2@/v1/{customer.name=accounts/*/channelPartnerLinks/*/customers/*}:\x08customer\x12\xc5\x01\n\x0eDeleteCustomer\x12..google.cloud.channel.v1.DeleteCustomerRequest\x1a\x16.google.protobuf.Empty"k\xdaA\x04name\x82\xd3\xe4\x93\x02^*!/v1/{name=accounts/*/customers/*}Z9*7/v1/{name=accounts/*/channelPartnerLinks/*/customers/*}\x12\xdd\x01\n\x0eImportCustomer\x12..google.cloud.channel.v1.ImportCustomerRequest\x1a!.google.cloud.channel.v1.Customer"x\x82\xd3\xe4\x93\x02r"(/v1/{parent=accounts/*}/customers:import:\x01*ZC">/v1/{parent=accounts/*/channelPartnerLinks/*}/customers:import:\x01*\x12\xd8\x01\n\x16ProvisionCloudIdentity\x126.google.cloud.channel.v1.ProvisionCloudIdentityRequest\x1a\x1d.google.longrunning.Operation"g\xcaA\x1d\n\x08Customer\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02A"</v1/{customer=accounts/*/customers/*}:provisionCloudIdentity:\x01*\x12\xb1\x01\n\x10ListEntitlements\x120.google.cloud.channel.v1.ListEntitlementsRequest\x1a1.google.cloud.channel.v1.ListEntitlementsResponse"8\x82\xd3\xe4\x93\x022\x120/v1/{parent=accounts/*/customers/*}/entitlements\x12\xbc\x01\n\x14ListTransferableSkus\x124.google.cloud.channel.v1.ListTransferableSkusRequest\x1a5.google.cloud.channel.v1.ListTransferableSkusResponse"7\x82\xd3\xe4\x93\x021",/v1/{parent=accounts/*}:listTransferableSkus:\x01*\x12\xc4\x01\n\x16ListTransferableOffers\x126.google.cloud.channel.v1.ListTransferableOffersRequest\x1a7.google.cloud.channel.v1.ListTransferableOffersResponse"9\x82\xd3\xe4\x93\x023"./v1/{parent=accounts/*}:listTransferableOffers:\x01*\x12\xa0\x01\n\x0eGetEntitlement\x12..google.cloud.channel.v1.GetEntitlementRequest\x1a$.google.cloud.channel.v1.Entitlement"8\x82\xd3\xe4\x93\x022\x120/v1/{name=accounts/*/customers/*/entitlements/*}\x12\xc5\x01\n\x11CreateEntitlement\x121.google.cloud.channel.v1.CreateEntitlementRequest\x1a\x1d.google.longrunning.Operation"^\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x025"0/v1/{parent=accounts/*/customers/*}/entitlements:\x01*\x12\xd4\x01\n\x10ChangeParameters\x120.google.cloud.channel.v1.ChangeParametersRequest\x1a\x1d.google.longrunning.Operation"o\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02F"A/v1/{name=accounts/*/customers/*/entitlements/*}:changeParameters:\x01*\x12\xe3\x01\n\x15ChangeRenewalSettings\x125.google.cloud.channel.v1.ChangeRenewalSettingsRequest\x1a\x1d.google.longrunning.Operation"t\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02K"F/v1/{name=accounts/*/customers/*/entitlements/*}:changeRenewalSettings:\x01*\x12\xc5\x01\n\x0bChangeOffer\x12+.google.cloud.channel.v1.ChangeOfferRequest\x1a\x1d.google.longrunning.Operation"j\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02A"</v1/{name=accounts/*/customers/*/entitlements/*}:changeOffer:\x01*\x12\xd4\x01\n\x10StartPaidService\x120.google.cloud.channel.v1.StartPaidServiceRequest\x1a\x1d.google.longrunning.Operation"o\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02F"A/v1/{name=accounts/*/customers/*/entitlements/*}:startPaidService:\x01*\x12\xcf\x01\n\x12SuspendEntitlement\x122.google.cloud.channel.v1.SuspendEntitlementRequest\x1a\x1d.google.longrunning.Operation"f\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02="8/v1/{name=accounts/*/customers/*/entitlements/*}:suspend:\x01*\x12\xd6\x01\n\x11CancelEntitlement\x121.google.cloud.channel.v1.CancelEntitlementRequest\x1a\x1d.google.longrunning.Operation"o\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02<"7/v1/{name=accounts/*/customers/*/entitlements/*}:cancel:\x01*\x12\xd2\x01\n\x13ActivateEntitlement\x123.google.cloud.channel.v1.ActivateEntitlementRequest\x1a\x1d.google.longrunning.Operation"g\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02>"9/v1/{name=accounts/*/customers/*/entitlements/*}:activate:\x01*\x12\xe4\x01\n\x14TransferEntitlements\x124.google.cloud.channel.v1.TransferEntitlementsRequest\x1a\x1d.google.longrunning.Operation"w\xcaA1\n\x1cTransferEntitlementsResponse\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02="8/v1/{parent=accounts/*/customers/*}:transferEntitlements:\x01*\x12\xf5\x01\n\x1cTransferEntitlementsToGoogle\x12<.google.cloud.channel.v1.TransferEntitlementsToGoogleRequest\x1a\x1d.google.longrunning.Operation"x\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02E"@/v1/{parent=accounts/*/customers/*}:transferEntitlementsToGoogle:\x01*\x12\xc1\x01\n\x17ListChannelPartnerLinks\x127.google.cloud.channel.v1.ListChannelPartnerLinksRequest\x1a8.google.cloud.channel.v1.ListChannelPartnerLinksResponse"3\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=accounts/*}/channelPartnerLinks\x12\xb0\x01\n\x15GetChannelPartnerLink\x125.google.cloud.channel.v1.GetChannelPartnerLinkRequest\x1a+.google.cloud.channel.v1.ChannelPartnerLink"3\x82\xd3\xe4\x93\x02-\x12+/v1/{name=accounts/*/channelPartnerLinks/*}\x12\xcc\x01\n\x18CreateChannelPartnerLink\x128.google.cloud.channel.v1.CreateChannelPartnerLinkRequest\x1a+.google.cloud.channel.v1.ChannelPartnerLink"I\x82\xd3\xe4\x93\x02C"+/v1/{parent=accounts/*}/channelPartnerLinks:\x14channel_partner_link\x12\xb9\x01\n\x18UpdateChannelPartnerLink\x128.google.cloud.channel.v1.UpdateChannelPartnerLinkRequest\x1a+.google.cloud.channel.v1.ChannelPartnerLink"6\x82\xd3\xe4\x93\x0202+/v1/{name=accounts/*/channelPartnerLinks/*}:\x01*\x12\xd7\x01\n\x1aGetCustomerRepricingConfig\x12:.google.cloud.channel.v1.GetCustomerRepricingConfigRequest\x1a0.google.cloud.channel.v1.CustomerRepricingConfig"K\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v1/{name=accounts/*/customers/*/customerRepricingConfigs/*}\x12\xea\x01\n\x1cListCustomerRepricingConfigs\x12<.google.cloud.channel.v1.ListCustomerRepricingConfigsRequest\x1a=.google.cloud.channel.v1.ListCustomerRepricingConfigsResponse"M\xdaA\x06parent\x82\xd3\xe4\x93\x02>\x12</v1/{parent=accounts/*/customers/*}/customerRepricingConfigs\x12\x95\x02\n\x1dCreateCustomerRepricingConfig\x12=.google.cloud.channel.v1.CreateCustomerRepricingConfigRequest\x1a0.google.cloud.channel.v1.CustomerRepricingConfig"\x82\x01\xdaA parent,customer_repricing_config\x82\xd3\xe4\x93\x02Y"</v1/{parent=accounts/*/customers/*}/customerRepricingConfigs:\x19customer_repricing_config\x12\xa8\x02\n\x1dUpdateCustomerRepricingConfig\x12=.google.cloud.channel.v1.UpdateCustomerRepricingConfigRequest\x1a0.google.cloud.channel.v1.CustomerRepricingConfig"\x95\x01\xdaA\x19customer_repricing_config\x82\xd3\xe4\x93\x02s2V/v1/{customer_repricing_config.name=accounts/*/customers/*/customerRepricingConfigs/*}:\x19customer_repricing_config\x12\xc3\x01\n\x1dDeleteCustomerRepricingConfig\x12=.google.cloud.channel.v1.DeleteCustomerRepricingConfigRequest\x1a\x16.google.protobuf.Empty"K\xdaA\x04name\x82\xd3\xe4\x93\x02>*</v1/{name=accounts/*/customers/*/customerRepricingConfigs/*}\x12\xf9\x01\n GetChannelPartnerRepricingConfig\x12@.google.cloud.channel.v1.GetChannelPartnerRepricingConfigRequest\x1a6.google.cloud.channel.v1.ChannelPartnerRepricingConfig"[\xdaA\x04name\x82\xd3\xe4\x93\x02N\x12L/v1/{name=accounts/*/channelPartnerLinks/*/channelPartnerRepricingConfigs/*}\x12\x8c\x02\n"ListChannelPartnerRepricingConfigs\x12B.google.cloud.channel.v1.ListChannelPartnerRepricingConfigsRequest\x1aC.google.cloud.channel.v1.ListChannelPartnerRepricingConfigsResponse"]\xdaA\x06parent\x82\xd3\xe4\x93\x02N\x12L/v1/{parent=accounts/*/channelPartnerLinks/*}/channelPartnerRepricingConfigs\x12\xc5\x02\n#CreateChannelPartnerRepricingConfig\x12C.google.cloud.channel.v1.CreateChannelPartnerRepricingConfigRequest\x1a6.google.cloud.channel.v1.ChannelPartnerRepricingConfig"\xa0\x01\xdaA\'parent,channel_partner_repricing_config\x82\xd3\xe4\x93\x02p"L/v1/{parent=accounts/*/channelPartnerLinks/*}/channelPartnerRepricingConfigs: channel_partner_repricing_config\x12\xe0\x02\n#UpdateChannelPartnerRepricingConfig\x12C.google.cloud.channel.v1.UpdateChannelPartnerRepricingConfigRequest\x1a6.google.cloud.channel.v1.ChannelPartnerRepricingConfig"\xbb\x01\xdaA channel_partner_repricing_config\x82\xd3\xe4\x93\x02\x91\x012m/v1/{channel_partner_repricing_config.name=accounts/*/channelPartnerLinks/*/channelPartnerRepricingConfigs/*}: channel_partner_repricing_config\x12\xdf\x01\n#DeleteChannelPartnerRepricingConfig\x12C.google.cloud.channel.v1.DeleteChannelPartnerRepricingConfigRequest\x1a\x16.google.protobuf.Empty"[\xdaA\x04name\x82\xd3\xe4\x93\x02N*L/v1/{name=accounts/*/channelPartnerLinks/*/channelPartnerRepricingConfigs/*}\x12\xa2\x01\n\rListSkuGroups\x12-.google.cloud.channel.v1.ListSkuGroupsRequest\x1a..google.cloud.channel.v1.ListSkuGroupsResponse"2\xdaA\x06parent\x82\xd3\xe4\x93\x02#\x12!/v1/{parent=accounts/*}/skuGroups\x12\xd2\x01\n\x18ListSkuGroupBillableSkus\x128.google.cloud.channel.v1.ListSkuGroupBillableSkusRequest\x1a9.google.cloud.channel.v1.ListSkuGroupBillableSkusResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=accounts/*/skuGroups/*}/billableSkus\x12\xa7\x01\n\x0bLookupOffer\x12+.google.cloud.channel.v1.LookupOfferRequest\x1a\x1e.google.cloud.channel.v1.Offer"K\x82\xd3\xe4\x93\x02E\x12C/v1/{entitlement=accounts/*/customers/*/entitlements/*}:lookupOffer\x12\x81\x01\n\x0cListProducts\x12,.google.cloud.channel.v1.ListProductsRequest\x1a-.google.cloud.channel.v1.ListProductsResponse"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/v1/products\x12\x85\x01\n\x08ListSkus\x12(.google.cloud.channel.v1.ListSkusRequest\x1a).google.cloud.channel.v1.ListSkusResponse"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/{parent=products/*}/skus\x12\x8d\x01\n\nListOffers\x12*.google.cloud.channel.v1.ListOffersRequest\x1a+.google.cloud.channel.v1.ListOffersResponse"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/{parent=accounts/*}/offers\x12\xc3\x01\n\x13ListPurchasableSkus\x123.google.cloud.channel.v1.ListPurchasableSkusRequest\x1a4.google.cloud.channel.v1.ListPurchasableSkusResponse"A\x82\xd3\xe4\x93\x02;\x129/v1/{customer=accounts/*/customers/*}:listPurchasableSkus\x12\xcb\x01\n\x15ListPurchasableOffers\x125.google.cloud.channel.v1.ListPurchasableOffersRequest\x1a6.google.cloud.channel.v1.ListPurchasableOffersResponse"C\x82\xd3\xe4\x93\x02=\x12;/v1/{customer=accounts/*/customers/*}:listPurchasableOffers\x12\xe7\x01\n\x1cQueryEligibleBillingAccounts\x12<.google.cloud.channel.v1.QueryEligibleBillingAccountsRequest\x1a=.google.cloud.channel.v1.QueryEligibleBillingAccountsResponse"J\x82\xd3\xe4\x93\x02D\x12B/v1/{customer=accounts/*/customers/*}:queryEligibleBillingAccounts\x12\xab\x01\n\x12RegisterSubscriber\x122.google.cloud.channel.v1.RegisterSubscriberRequest\x1a3.google.cloud.channel.v1.RegisterSubscriberResponse",\x82\xd3\xe4\x93\x02&"!/v1/{account=accounts/*}:register:\x01*\x12\xb3\x01\n\x14UnregisterSubscriber\x124.google.cloud.channel.v1.UnregisterSubscriberRequest\x1a5.google.cloud.channel.v1.UnregisterSubscriberResponse".\x82\xd3\xe4\x93\x02("#/v1/{account=accounts/*}:unregister:\x01*\x12\xa6\x01\n\x0fListSubscribers\x12/.google.cloud.channel.v1.ListSubscribersRequest\x1a0.google.cloud.channel.v1.ListSubscribersResponse"0\x82\xd3\xe4\x93\x02*\x12(/v1/{account=accounts/*}:listSubscribers\x12\xe5\x01\n\x16ListEntitlementChanges\x126.google.cloud.channel.v1.ListEntitlementChangesRequest\x1a7.google.cloud.channel.v1.ListEntitlementChangesResponse"Z\xdaA\x06parent\x82\xd3\xe4\x93\x02K\x12I/v1/{parent=accounts/*/customers/*/entitlements/*}:listEntitlementChanges\x1aK\xcaA\x1bcloudchannel.googleapis.com\xd2A*https://www.googleapis.com/auth/apps.orderBd\n\x1bcom.google.cloud.channel.v1B\x0cServiceProtoP\x01Z5cloud.google.com/go/channel/apiv1/channelpb;channelpbb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.channel.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1bcom.google.cloud.channel.v1B\x0cServiceProtoP\x01Z5cloud.google.com/go/channel/apiv1/channelpb;channelpb'
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST'].fields_by_name['domain']._loaded_options = None
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST'].fields_by_name['domain']._serialized_options = b'\xe0A\x02'
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST'].fields_by_name['primary_admin_email']._loaded_options = None
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST'].fields_by_name['primary_admin_email']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCUSTOMERSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_GETCUSTOMERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCUSTOMERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_CREATECUSTOMERREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECUSTOMERREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECUSTOMERREQUEST'].fields_by_name['customer']._loaded_options = None
    _globals['_CREATECUSTOMERREQUEST'].fields_by_name['customer']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECUSTOMERREQUEST'].fields_by_name['customer']._loaded_options = None
    _globals['_UPDATECUSTOMERREQUEST'].fields_by_name['customer']._serialized_options = b'\xe0A\x02'
    _globals['_DELETECUSTOMERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECUSTOMERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['domain']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['domain']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['cloud_identity_id']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['cloud_identity_id']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['primary_admin_email']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['primary_admin_email']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['auth_token']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['auth_token']._serialized_options = b'\xe0A\x01'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['overwrite_if_exists']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['overwrite_if_exists']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['channel_partner_id']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['channel_partner_id']._serialized_options = b'\xe0A\x01'
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['customer']._loaded_options = None
    _globals['_IMPORTCUSTOMERREQUEST'].fields_by_name['customer']._serialized_options = b'\xe0A\x01\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_PROVISIONCLOUDIDENTITYREQUEST'].fields_by_name['customer']._loaded_options = None
    _globals['_PROVISIONCLOUDIDENTITYREQUEST'].fields_by_name['customer']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTENTITLEMENTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTTRANSFERABLESKUSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTTRANSFERABLESKUSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_LISTTRANSFERABLESKUSREQUEST'].fields_by_name['auth_token']._loaded_options = None
    _globals['_LISTTRANSFERABLESKUSREQUEST'].fields_by_name['auth_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['sku']._loaded_options = None
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['sku']._serialized_options = b'\xe0A\x02'
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['language_code']._loaded_options = None
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['language_code']._serialized_options = b'\xe0A\x01'
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['billing_account']._loaded_options = None
    _globals['_LISTTRANSFERABLEOFFERSREQUEST'].fields_by_name['billing_account']._serialized_options = b'\xe0A\x01'
    _globals['_GETENTITLEMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETENTITLEMENTREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'cloudchannel.googleapis.com/Entitlement"
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['view']._loaded_options = None
    _globals['_LISTCHANNELPARTNERLINKSREQUEST'].fields_by_name['view']._serialized_options = b'\xe0A\x01'
    _globals['_GETCHANNELPARTNERLINKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCHANNELPARTNERLINKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_GETCHANNELPARTNERLINKREQUEST'].fields_by_name['view']._loaded_options = None
    _globals['_GETCHANNELPARTNERLINKREQUEST'].fields_by_name['view']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECHANNELPARTNERLINKREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECHANNELPARTNERLINKREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_CREATECHANNELPARTNERLINKREQUEST'].fields_by_name['channel_partner_link']._loaded_options = None
    _globals['_CREATECHANNELPARTNERLINKREQUEST'].fields_by_name['channel_partner_link']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECHANNELPARTNERLINKREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UPDATECHANNELPARTNERLINKREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECHANNELPARTNERLINKREQUEST'].fields_by_name['channel_partner_link']._loaded_options = None
    _globals['_UPDATECHANNELPARTNERLINKREQUEST'].fields_by_name['channel_partner_link']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECHANNELPARTNERLINKREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATECHANNELPARTNERLINKREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_GETCUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA5\n3cloudchannel.googleapis.com/CustomerRepricingConfig'
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_CREATECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['customer_repricing_config']._loaded_options = None
    _globals['_CREATECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['customer_repricing_config']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['customer_repricing_config']._loaded_options = None
    _globals['_UPDATECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['customer_repricing_config']._serialized_options = b'\xe0A\x02'
    _globals['_DELETECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECUSTOMERREPRICINGCONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA5\n3cloudchannel.googleapis.com/CustomerRepricingConfig'
    _globals['_GETCHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA;\n9cloudchannel.googleapis.com/ChannelPartnerRepricingConfig'
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA0\n.cloudchannel.googleapis.com/ChannelPartnerLink'
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_CREATECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA0\n.cloudchannel.googleapis.com/ChannelPartnerLink'
    _globals['_CREATECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['channel_partner_repricing_config']._loaded_options = None
    _globals['_CREATECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['channel_partner_repricing_config']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['channel_partner_repricing_config']._loaded_options = None
    _globals['_UPDATECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['channel_partner_repricing_config']._serialized_options = b'\xe0A\x02'
    _globals['_DELETECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETECHANNELPARTNERREPRICINGCONFIGREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA;\n9cloudchannel.googleapis.com/ChannelPartnerRepricingConfig'
    _globals['_LISTSKUGROUPSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSKUGROUPSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_LISTSKUGROUPSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTSKUGROUPSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSKUGROUPSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTSKUGROUPSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/SkuGroup'
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_SKUGROUP']._loaded_options = None
    _globals['_SKUGROUP']._serialized_options = b'\xeaAP\n$cloudchannel.googleapis.com/SkuGroup\x12(accounts/{account}/skuGroups/{sku_group}'
    _globals['_CREATEENTITLEMENTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEENTITLEMENTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_CREATEENTITLEMENTREQUEST'].fields_by_name['entitlement']._loaded_options = None
    _globals['_CREATEENTITLEMENTREQUEST'].fields_by_name['entitlement']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEENTITLEMENTREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATEENTITLEMENTREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_TRANSFERENTITLEMENTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_TRANSFERENTITLEMENTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_TRANSFERENTITLEMENTSREQUEST'].fields_by_name['entitlements']._loaded_options = None
    _globals['_TRANSFERENTITLEMENTSREQUEST'].fields_by_name['entitlements']._serialized_options = b'\xe0A\x02'
    _globals['_TRANSFERENTITLEMENTSREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_TRANSFERENTITLEMENTSREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST'].fields_by_name['entitlements']._loaded_options = None
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST'].fields_by_name['entitlements']._serialized_options = b'\xe0A\x02'
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['parameters']._loaded_options = None
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['parameters']._serialized_options = b'\xe0A\x02'
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['purchase_order_id']._loaded_options = None
    _globals['_CHANGEPARAMETERSREQUEST'].fields_by_name['purchase_order_id']._serialized_options = b'\xe0A\x01'
    _globals['_CHANGERENEWALSETTINGSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CHANGERENEWALSETTINGSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_CHANGERENEWALSETTINGSREQUEST'].fields_by_name['renewal_settings']._loaded_options = None
    _globals['_CHANGERENEWALSETTINGSREQUEST'].fields_by_name['renewal_settings']._serialized_options = b'\xe0A\x02'
    _globals['_CHANGERENEWALSETTINGSREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CHANGERENEWALSETTINGSREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['offer']._loaded_options = None
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['offer']._serialized_options = b'\xe0A\x02\xfaA#\n!cloudchannel.googleapis.com/Offer'
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['parameters']._loaded_options = None
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['parameters']._serialized_options = b'\xe0A\x01'
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['purchase_order_id']._loaded_options = None
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['purchase_order_id']._serialized_options = b'\xe0A\x01'
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['billing_account']._loaded_options = None
    _globals['_CHANGEOFFERREQUEST'].fields_by_name['billing_account']._serialized_options = b'\xe0A\x01'
    _globals['_STARTPAIDSERVICEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_STARTPAIDSERVICEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_STARTPAIDSERVICEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_STARTPAIDSERVICEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_CANCELENTITLEMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CANCELENTITLEMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_CANCELENTITLEMENTREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CANCELENTITLEMENTREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_SUSPENDENTITLEMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_SUSPENDENTITLEMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_SUSPENDENTITLEMENTREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_SUSPENDENTITLEMENTREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_ACTIVATEENTITLEMENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ACTIVATEENTITLEMENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_ACTIVATEENTITLEMENTREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_ACTIVATEENTITLEMENTREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_LOOKUPOFFERREQUEST'].fields_by_name['entitlement']._loaded_options = None
    _globals['_LOOKUPOFFERREQUEST'].fields_by_name['entitlement']._serialized_options = b"\xe0A\x02\xfaA)\n'cloudchannel.googleapis.com/Entitlement"
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['account']._loaded_options = None
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['account']._serialized_options = b'\xe0A\x02'
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['language_code']._loaded_options = None
    _globals['_LISTPRODUCTSREQUEST'].fields_by_name['language_code']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSKUSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSKUSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\n#cloudchannel.googleapis.com/Product'
    _globals['_LISTSKUSREQUEST'].fields_by_name['account']._loaded_options = None
    _globals['_LISTSKUSREQUEST'].fields_by_name['account']._serialized_options = b'\xe0A\x02'
    _globals['_LISTSKUSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTSKUSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSKUSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTSKUSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSKUSREQUEST'].fields_by_name['language_code']._loaded_options = None
    _globals['_LISTSKUSREQUEST'].fields_by_name['language_code']._serialized_options = b'\xe0A\x01'
    _globals['_LISTOFFERSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTOFFERSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02'
    _globals['_LISTOFFERSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTOFFERSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTOFFERSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTOFFERSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTOFFERSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTOFFERSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTOFFERSREQUEST'].fields_by_name['language_code']._loaded_options = None
    _globals['_LISTOFFERSREQUEST'].fields_by_name['language_code']._serialized_options = b'\xe0A\x01'
    _globals['_LISTOFFERSREQUEST'].fields_by_name['show_future_offers']._loaded_options = None
    _globals['_LISTOFFERSREQUEST'].fields_by_name['show_future_offers']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLESKUSREQUEST_CREATEENTITLEMENTPURCHASE'].fields_by_name['product']._loaded_options = None
    _globals['_LISTPURCHASABLESKUSREQUEST_CREATEENTITLEMENTPURCHASE'].fields_by_name['product']._serialized_options = b'\xe0A\x02'
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['entitlement']._loaded_options = None
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['entitlement']._serialized_options = b'\xe0A\x02'
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['change_type']._loaded_options = None
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['change_type']._serialized_options = b'\xe0A\x02'
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['customer']._loaded_options = None
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['customer']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['language_code']._loaded_options = None
    _globals['_LISTPURCHASABLESKUSREQUEST'].fields_by_name['language_code']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CREATEENTITLEMENTPURCHASE'].fields_by_name['sku']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CREATEENTITLEMENTPURCHASE'].fields_by_name['sku']._serialized_options = b'\xe0A\x02'
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CREATEENTITLEMENTPURCHASE'].fields_by_name['billing_account']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CREATEENTITLEMENTPURCHASE'].fields_by_name['billing_account']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['entitlement']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['entitlement']._serialized_options = b'\xe0A\x02'
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['new_sku']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['new_sku']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['billing_account']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE'].fields_by_name['billing_account']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['customer']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['customer']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['language_code']._loaded_options = None
    _globals['_LISTPURCHASABLEOFFERSREQUEST'].fields_by_name['language_code']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSREQUEST'].fields_by_name['customer']._loaded_options = None
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSREQUEST'].fields_by_name['customer']._serialized_options = b'\xe0A\x02\xfaA&\n$cloudchannel.googleapis.com/Customer'
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSREQUEST'].fields_by_name['skus']._loaded_options = None
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSREQUEST'].fields_by_name['skus']._serialized_options = b'\xe0A\x02'
    _globals['_REGISTERSUBSCRIBERREQUEST'].fields_by_name['account']._loaded_options = None
    _globals['_REGISTERSUBSCRIBERREQUEST'].fields_by_name['account']._serialized_options = b'\xe0A\x02'
    _globals['_REGISTERSUBSCRIBERREQUEST'].fields_by_name['service_account']._loaded_options = None
    _globals['_REGISTERSUBSCRIBERREQUEST'].fields_by_name['service_account']._serialized_options = b'\xe0A\x02'
    _globals['_UNREGISTERSUBSCRIBERREQUEST'].fields_by_name['account']._loaded_options = None
    _globals['_UNREGISTERSUBSCRIBERREQUEST'].fields_by_name['account']._serialized_options = b'\xe0A\x02'
    _globals['_UNREGISTERSUBSCRIBERREQUEST'].fields_by_name['service_account']._loaded_options = None
    _globals['_UNREGISTERSUBSCRIBERREQUEST'].fields_by_name['service_account']._serialized_options = b'\xe0A\x02'
    _globals['_LISTSUBSCRIBERSREQUEST'].fields_by_name['account']._loaded_options = None
    _globals['_LISTSUBSCRIBERSREQUEST'].fields_by_name['account']._serialized_options = b'\xe0A\x02'
    _globals['_LISTSUBSCRIBERSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTSUBSCRIBERSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTSUBSCRIBERSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTSUBSCRIBERSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\n'cloudchannel.googleapis.com/Entitlement"
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTENTITLEMENTCHANGESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_CLOUDCHANNELSERVICE']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE']._serialized_options = b'\xcaA\x1bcloudchannel.googleapis.com\xd2A*https://www.googleapis.com/auth/apps.order'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListCustomers']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListCustomers']._serialized_options = b'\x82\xd3\xe4\x93\x02^\x12!/v1/{parent=accounts/*}/customersZ9\x127/v1/{parent=accounts/*/channelPartnerLinks/*}/customers'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetCustomer']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetCustomer']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02^\x12!/v1/{name=accounts/*/customers/*}Z9\x127/v1/{name=accounts/*/channelPartnerLinks/*/customers/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CheckCloudIdentityAccountsExist']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CheckCloudIdentityAccountsExist']._serialized_options = b'\x82\xd3\xe4\x93\x02<"7/v1/{parent=accounts/*}:checkCloudIdentityAccountsExist:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateCustomer']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateCustomer']._serialized_options = b'\x82\xd3\xe4\x93\x02r"!/v1/{parent=accounts/*}/customers:\x08customerZC"7/v1/{parent=accounts/*/channelPartnerLinks/*}/customers:\x08customer'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateCustomer']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateCustomer']._serialized_options = b'\x82\xd3\xe4\x93\x02\x84\x012*/v1/{customer.name=accounts/*/customers/*}:\x08customerZL2@/v1/{customer.name=accounts/*/channelPartnerLinks/*/customers/*}:\x08customer'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['DeleteCustomer']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['DeleteCustomer']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02^*!/v1/{name=accounts/*/customers/*}Z9*7/v1/{name=accounts/*/channelPartnerLinks/*/customers/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ImportCustomer']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ImportCustomer']._serialized_options = b'\x82\xd3\xe4\x93\x02r"(/v1/{parent=accounts/*}/customers:import:\x01*ZC">/v1/{parent=accounts/*/channelPartnerLinks/*}/customers:import:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ProvisionCloudIdentity']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ProvisionCloudIdentity']._serialized_options = b'\xcaA\x1d\n\x08Customer\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02A"</v1/{customer=accounts/*/customers/*}:provisionCloudIdentity:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListEntitlements']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListEntitlements']._serialized_options = b'\x82\xd3\xe4\x93\x022\x120/v1/{parent=accounts/*/customers/*}/entitlements'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListTransferableSkus']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListTransferableSkus']._serialized_options = b'\x82\xd3\xe4\x93\x021",/v1/{parent=accounts/*}:listTransferableSkus:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListTransferableOffers']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListTransferableOffers']._serialized_options = b'\x82\xd3\xe4\x93\x023"./v1/{parent=accounts/*}:listTransferableOffers:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetEntitlement']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetEntitlement']._serialized_options = b'\x82\xd3\xe4\x93\x022\x120/v1/{name=accounts/*/customers/*/entitlements/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateEntitlement']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateEntitlement']._serialized_options = b'\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x025"0/v1/{parent=accounts/*/customers/*}/entitlements:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ChangeParameters']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ChangeParameters']._serialized_options = b'\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02F"A/v1/{name=accounts/*/customers/*/entitlements/*}:changeParameters:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ChangeRenewalSettings']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ChangeRenewalSettings']._serialized_options = b'\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02K"F/v1/{name=accounts/*/customers/*/entitlements/*}:changeRenewalSettings:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ChangeOffer']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ChangeOffer']._serialized_options = b'\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02A"</v1/{name=accounts/*/customers/*/entitlements/*}:changeOffer:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['StartPaidService']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['StartPaidService']._serialized_options = b'\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02F"A/v1/{name=accounts/*/customers/*/entitlements/*}:startPaidService:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['SuspendEntitlement']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['SuspendEntitlement']._serialized_options = b'\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02="8/v1/{name=accounts/*/customers/*/entitlements/*}:suspend:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CancelEntitlement']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CancelEntitlement']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02<"7/v1/{name=accounts/*/customers/*/entitlements/*}:cancel:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ActivateEntitlement']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ActivateEntitlement']._serialized_options = b'\xcaA \n\x0bEntitlement\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02>"9/v1/{name=accounts/*/customers/*/entitlements/*}:activate:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['TransferEntitlements']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['TransferEntitlements']._serialized_options = b'\xcaA1\n\x1cTransferEntitlementsResponse\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02="8/v1/{parent=accounts/*/customers/*}:transferEntitlements:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['TransferEntitlementsToGoogle']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['TransferEntitlementsToGoogle']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02E"@/v1/{parent=accounts/*/customers/*}:transferEntitlementsToGoogle:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListChannelPartnerLinks']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListChannelPartnerLinks']._serialized_options = b'\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=accounts/*}/channelPartnerLinks'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetChannelPartnerLink']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetChannelPartnerLink']._serialized_options = b'\x82\xd3\xe4\x93\x02-\x12+/v1/{name=accounts/*/channelPartnerLinks/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateChannelPartnerLink']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateChannelPartnerLink']._serialized_options = b'\x82\xd3\xe4\x93\x02C"+/v1/{parent=accounts/*}/channelPartnerLinks:\x14channel_partner_link'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateChannelPartnerLink']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateChannelPartnerLink']._serialized_options = b'\x82\xd3\xe4\x93\x0202+/v1/{name=accounts/*/channelPartnerLinks/*}:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetCustomerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetCustomerRepricingConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v1/{name=accounts/*/customers/*/customerRepricingConfigs/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListCustomerRepricingConfigs']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListCustomerRepricingConfigs']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02>\x12</v1/{parent=accounts/*/customers/*}/customerRepricingConfigs'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateCustomerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateCustomerRepricingConfig']._serialized_options = b'\xdaA parent,customer_repricing_config\x82\xd3\xe4\x93\x02Y"</v1/{parent=accounts/*/customers/*}/customerRepricingConfigs:\x19customer_repricing_config'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateCustomerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateCustomerRepricingConfig']._serialized_options = b'\xdaA\x19customer_repricing_config\x82\xd3\xe4\x93\x02s2V/v1/{customer_repricing_config.name=accounts/*/customers/*/customerRepricingConfigs/*}:\x19customer_repricing_config'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['DeleteCustomerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['DeleteCustomerRepricingConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02>*</v1/{name=accounts/*/customers/*/customerRepricingConfigs/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetChannelPartnerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['GetChannelPartnerRepricingConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02N\x12L/v1/{name=accounts/*/channelPartnerLinks/*/channelPartnerRepricingConfigs/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListChannelPartnerRepricingConfigs']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListChannelPartnerRepricingConfigs']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02N\x12L/v1/{parent=accounts/*/channelPartnerLinks/*}/channelPartnerRepricingConfigs'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateChannelPartnerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['CreateChannelPartnerRepricingConfig']._serialized_options = b'\xdaA\'parent,channel_partner_repricing_config\x82\xd3\xe4\x93\x02p"L/v1/{parent=accounts/*/channelPartnerLinks/*}/channelPartnerRepricingConfigs: channel_partner_repricing_config'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateChannelPartnerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UpdateChannelPartnerRepricingConfig']._serialized_options = b'\xdaA channel_partner_repricing_config\x82\xd3\xe4\x93\x02\x91\x012m/v1/{channel_partner_repricing_config.name=accounts/*/channelPartnerLinks/*/channelPartnerRepricingConfigs/*}: channel_partner_repricing_config'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['DeleteChannelPartnerRepricingConfig']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['DeleteChannelPartnerRepricingConfig']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02N*L/v1/{name=accounts/*/channelPartnerLinks/*/channelPartnerRepricingConfigs/*}'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSkuGroups']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSkuGroups']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02#\x12!/v1/{parent=accounts/*}/skuGroups'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSkuGroupBillableSkus']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSkuGroupBillableSkus']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=accounts/*/skuGroups/*}/billableSkus'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['LookupOffer']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['LookupOffer']._serialized_options = b'\x82\xd3\xe4\x93\x02E\x12C/v1/{entitlement=accounts/*/customers/*/entitlements/*}:lookupOffer'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListProducts']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListProducts']._serialized_options = b'\x82\xd3\xe4\x93\x02\x0e\x12\x0c/v1/products'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSkus']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSkus']._serialized_options = b'\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/{parent=products/*}/skus'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListOffers']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListOffers']._serialized_options = b'\x82\xd3\xe4\x93\x02 \x12\x1e/v1/{parent=accounts/*}/offers'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListPurchasableSkus']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListPurchasableSkus']._serialized_options = b'\x82\xd3\xe4\x93\x02;\x129/v1/{customer=accounts/*/customers/*}:listPurchasableSkus'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListPurchasableOffers']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListPurchasableOffers']._serialized_options = b'\x82\xd3\xe4\x93\x02=\x12;/v1/{customer=accounts/*/customers/*}:listPurchasableOffers'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['QueryEligibleBillingAccounts']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['QueryEligibleBillingAccounts']._serialized_options = b'\x82\xd3\xe4\x93\x02D\x12B/v1/{customer=accounts/*/customers/*}:queryEligibleBillingAccounts'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['RegisterSubscriber']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['RegisterSubscriber']._serialized_options = b'\x82\xd3\xe4\x93\x02&"!/v1/{account=accounts/*}:register:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UnregisterSubscriber']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['UnregisterSubscriber']._serialized_options = b'\x82\xd3\xe4\x93\x02("#/v1/{account=accounts/*}:unregister:\x01*'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSubscribers']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListSubscribers']._serialized_options = b'\x82\xd3\xe4\x93\x02*\x12(/v1/{account=accounts/*}:listSubscribers'
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListEntitlementChanges']._loaded_options = None
    _globals['_CLOUDCHANNELSERVICE'].methods_by_name['ListEntitlementChanges']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02K\x12I/v1/{parent=accounts/*/customers/*/entitlements/*}:listEntitlementChanges'
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST']._serialized_start = 717
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTREQUEST']._serialized_end = 833
    _globals['_CLOUDIDENTITYCUSTOMERACCOUNT']._serialized_start = 836
    _globals['_CLOUDIDENTITYCUSTOMERACCOUNT']._serialized_end = 1081
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTRESPONSE']._serialized_start = 1084
    _globals['_CHECKCLOUDIDENTITYACCOUNTSEXISTRESPONSE']._serialized_end = 1213
    _globals['_LISTCUSTOMERSREQUEST']._serialized_start = 1215
    _globals['_LISTCUSTOMERSREQUEST']._serialized_end = 1328
    _globals['_LISTCUSTOMERSRESPONSE']._serialized_start = 1330
    _globals['_LISTCUSTOMERSRESPONSE']._serialized_end = 1432
    _globals['_GETCUSTOMERREQUEST']._serialized_start = 1434
    _globals['_GETCUSTOMERREQUEST']._serialized_end = 1514
    _globals['_CREATECUSTOMERREQUEST']._serialized_start = 1516
    _globals['_CREATECUSTOMERREQUEST']._serialized_end = 1618
    _globals['_UPDATECUSTOMERREQUEST']._serialized_start = 1621
    _globals['_UPDATECUSTOMERREQUEST']._serialized_end = 1751
    _globals['_DELETECUSTOMERREQUEST']._serialized_start = 1753
    _globals['_DELETECUSTOMERREQUEST']._serialized_end = 1836
    _globals['_IMPORTCUSTOMERREQUEST']._serialized_start = 1839
    _globals['_IMPORTCUSTOMERREQUEST']._serialized_end = 2153
    _globals['_PROVISIONCLOUDIDENTITYREQUEST']._serialized_start = 2156
    _globals['_PROVISIONCLOUDIDENTITYREQUEST']._serialized_end = 2397
    _globals['_LISTENTITLEMENTSREQUEST']._serialized_start = 2400
    _globals['_LISTENTITLEMENTSREQUEST']._serialized_end = 2536
    _globals['_LISTENTITLEMENTSRESPONSE']._serialized_start = 2538
    _globals['_LISTENTITLEMENTSRESPONSE']._serialized_end = 2649
    _globals['_LISTTRANSFERABLESKUSREQUEST']._serialized_start = 2652
    _globals['_LISTTRANSFERABLESKUSREQUEST']._serialized_end = 2876
    _globals['_LISTTRANSFERABLESKUSRESPONSE']._serialized_start = 2878
    _globals['_LISTTRANSFERABLESKUSRESPONSE']._serialized_end = 3002
    _globals['_LISTTRANSFERABLEOFFERSREQUEST']._serialized_start = 3005
    _globals['_LISTTRANSFERABLEOFFERSREQUEST']._serialized_end = 3259
    _globals['_LISTTRANSFERABLEOFFERSRESPONSE']._serialized_start = 3262
    _globals['_LISTTRANSFERABLEOFFERSRESPONSE']._serialized_end = 3392
    _globals['_TRANSFERABLEOFFER']._serialized_start = 3394
    _globals['_TRANSFERABLEOFFER']._serialized_end = 3460
    _globals['_GETENTITLEMENTREQUEST']._serialized_start = 3462
    _globals['_GETENTITLEMENTREQUEST']._serialized_end = 3548
    _globals['_LISTCHANNELPARTNERLINKSREQUEST']._serialized_start = 3551
    _globals['_LISTCHANNELPARTNERLINKSREQUEST']._serialized_end = 3721
    _globals['_LISTCHANNELPARTNERLINKSRESPONSE']._serialized_start = 3724
    _globals['_LISTCHANNELPARTNERLINKSRESPONSE']._serialized_end = 3858
    _globals['_GETCHANNELPARTNERLINKREQUEST']._serialized_start = 3860
    _globals['_GETCHANNELPARTNERLINKREQUEST']._serialized_end = 3977
    _globals['_CREATECHANNELPARTNERLINKREQUEST']._serialized_start = 3980
    _globals['_CREATECHANNELPARTNERLINKREQUEST']._serialized_end = 4114
    _globals['_UPDATECHANNELPARTNERLINKREQUEST']._serialized_start = 4117
    _globals['_UPDATECHANNELPARTNERLINKREQUEST']._serialized_end = 4303
    _globals['_GETCUSTOMERREPRICINGCONFIGREQUEST']._serialized_start = 4305
    _globals['_GETCUSTOMERREPRICINGCONFIGREQUEST']._serialized_end = 4415
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST']._serialized_start = 4418
    _globals['_LISTCUSTOMERREPRICINGCONFIGSREQUEST']._serialized_end = 4587
    _globals['_LISTCUSTOMERREPRICINGCONFIGSRESPONSE']._serialized_start = 4590
    _globals['_LISTCUSTOMERREPRICINGCONFIGSRESPONSE']._serialized_end = 4739
    _globals['_CREATECUSTOMERREPRICINGCONFIGREQUEST']._serialized_start = 4742
    _globals['_CREATECUSTOMERREPRICINGCONFIGREQUEST']._serialized_end = 4932
    _globals['_UPDATECUSTOMERREPRICINGCONFIGREQUEST']._serialized_start = 4935
    _globals['_UPDATECUSTOMERREPRICINGCONFIGREQUEST']._serialized_end = 5063
    _globals['_DELETECUSTOMERREPRICINGCONFIGREQUEST']._serialized_start = 5065
    _globals['_DELETECUSTOMERREPRICINGCONFIGREQUEST']._serialized_end = 5178
    _globals['_GETCHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_start = 5180
    _globals['_GETCHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_end = 5302
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST']._serialized_start = 5305
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSREQUEST']._serialized_end = 5490
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSRESPONSE']._serialized_start = 5493
    _globals['_LISTCHANNELPARTNERREPRICINGCONFIGSRESPONSE']._serialized_end = 5661
    _globals['_CREATECHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_start = 5664
    _globals['_CREATECHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_end = 5883
    _globals['_UPDATECHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_start = 5886
    _globals['_UPDATECHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_end = 6033
    _globals['_DELETECHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_start = 6035
    _globals['_DELETECHANNELPARTNERREPRICINGCONFIGREQUEST']._serialized_end = 6160
    _globals['_LISTSKUGROUPSREQUEST']._serialized_start = 6162
    _globals['_LISTSKUGROUPSREQUEST']._serialized_end = 6254
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST']._serialized_start = 6257
    _globals['_LISTSKUGROUPBILLABLESKUSREQUEST']._serialized_end = 6401
    _globals['_LISTSKUGROUPSRESPONSE']._serialized_start = 6403
    _globals['_LISTSKUGROUPSRESPONSE']._serialized_end = 6506
    _globals['_LISTSKUGROUPBILLABLESKUSRESPONSE']._serialized_start = 6508
    _globals['_LISTSKUGROUPBILLABLESKUSRESPONSE']._serialized_end = 6628
    _globals['_SKUGROUP']._serialized_start = 6631
    _globals['_SKUGROUP']._serialized_end = 6762
    _globals['_BILLABLESKU']._serialized_start = 6764
    _globals['_BILLABLESKU']._serialized_end = 6863
    _globals['_CREATEENTITLEMENTREQUEST']._serialized_start = 6866
    _globals['_CREATEENTITLEMENTREQUEST']._serialized_end = 7043
    _globals['_TRANSFERENTITLEMENTSREQUEST']._serialized_start = 7046
    _globals['_TRANSFERENTITLEMENTSREQUEST']._serialized_end = 7206
    _globals['_TRANSFERENTITLEMENTSRESPONSE']._serialized_start = 7208
    _globals['_TRANSFERENTITLEMENTSRESPONSE']._serialized_end = 7298
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST']._serialized_start = 7301
    _globals['_TRANSFERENTITLEMENTSTOGOOGLEREQUEST']._serialized_end = 7449
    _globals['_CHANGEPARAMETERSREQUEST']._serialized_start = 7452
    _globals['_CHANGEPARAMETERSREQUEST']._serialized_end = 7614
    _globals['_CHANGERENEWALSETTINGSREQUEST']._serialized_start = 7617
    _globals['_CHANGERENEWALSETTINGSREQUEST']._serialized_end = 7764
    _globals['_CHANGEOFFERREQUEST']._serialized_start = 7767
    _globals['_CHANGEOFFERREQUEST']._serialized_end = 8012
    _globals['_STARTPAIDSERVICEREQUEST']._serialized_start = 8014
    _globals['_STARTPAIDSERVICEREQUEST']._serialized_end = 8083
    _globals['_CANCELENTITLEMENTREQUEST']._serialized_start = 8085
    _globals['_CANCELENTITLEMENTREQUEST']._serialized_end = 8155
    _globals['_SUSPENDENTITLEMENTREQUEST']._serialized_start = 8157
    _globals['_SUSPENDENTITLEMENTREQUEST']._serialized_end = 8228
    _globals['_ACTIVATEENTITLEMENTREQUEST']._serialized_start = 8230
    _globals['_ACTIVATEENTITLEMENTREQUEST']._serialized_end = 8302
    _globals['_LOOKUPOFFERREQUEST']._serialized_start = 8304
    _globals['_LOOKUPOFFERREQUEST']._serialized_end = 8394
    _globals['_LISTPRODUCTSREQUEST']._serialized_start = 8396
    _globals['_LISTPRODUCTSREQUEST']._serialized_end = 8516
    _globals['_LISTPRODUCTSRESPONSE']._serialized_start = 8518
    _globals['_LISTPRODUCTSRESPONSE']._serialized_end = 8617
    _globals['_LISTSKUSREQUEST']._serialized_start = 8620
    _globals['_LISTSKUSREQUEST']._serialized_end = 8797
    _globals['_LISTSKUSRESPONSE']._serialized_start = 8799
    _globals['_LISTSKUSRESPONSE']._serialized_end = 8886
    _globals['_LISTOFFERSREQUEST']._serialized_start = 8889
    _globals['_LISTOFFERSREQUEST']._serialized_end = 9060
    _globals['_LISTOFFERSRESPONSE']._serialized_start = 9062
    _globals['_LISTOFFERSRESPONSE']._serialized_end = 9155
    _globals['_LISTPURCHASABLESKUSREQUEST']._serialized_start = 9158
    _globals['_LISTPURCHASABLESKUSREQUEST']._serialized_end = 9852
    _globals['_LISTPURCHASABLESKUSREQUEST_CREATEENTITLEMENTPURCHASE']._serialized_start = 9553
    _globals['_LISTPURCHASABLESKUSREQUEST_CREATEENTITLEMENTPURCHASE']._serialized_end = 9602
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE']._serialized_start = 9605
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE']._serialized_end = 9833
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE_CHANGETYPE']._serialized_start = 9764
    _globals['_LISTPURCHASABLESKUSREQUEST_CHANGEOFFERPURCHASE_CHANGETYPE']._serialized_end = 9833
    _globals['_LISTPURCHASABLESKUSRESPONSE']._serialized_start = 9854
    _globals['_LISTPURCHASABLESKUSRESPONSE']._serialized_end = 9975
    _globals['_PURCHASABLESKU']._serialized_start = 9977
    _globals['_PURCHASABLESKU']._serialized_end = 10036
    _globals['_LISTPURCHASABLEOFFERSREQUEST']._serialized_start = 10039
    _globals['_LISTPURCHASABLEOFFERSREQUEST']._serialized_end = 10635
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CREATEENTITLEMENTPURCHASE']._serialized_start = 10440
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CREATEENTITLEMENTPURCHASE']._serialized_end = 10515
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE']._serialized_start = 10517
    _globals['_LISTPURCHASABLEOFFERSREQUEST_CHANGEOFFERPURCHASE']._serialized_end = 10616
    _globals['_LISTPURCHASABLEOFFERSRESPONSE']._serialized_start = 10637
    _globals['_LISTPURCHASABLEOFFERSRESPONSE']._serialized_end = 10764
    _globals['_PURCHASABLEOFFER']._serialized_start = 10766
    _globals['_PURCHASABLEOFFER']._serialized_end = 10831
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSREQUEST']._serialized_start = 10833
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSREQUEST']._serialized_end = 10953
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSRESPONSE']._serialized_start = 10955
    _globals['_QUERYELIGIBLEBILLINGACCOUNTSRESPONSE']._serialized_end = 11065
    _globals['_SKUPURCHASEGROUP']._serialized_start = 11067
    _globals['_SKUPURCHASEGROUP']._serialized_end = 11192
    _globals['_BILLINGACCOUNTPURCHASEINFO']._serialized_start = 11194
    _globals['_BILLINGACCOUNTPURCHASEINFO']._serialized_end = 11288
    _globals['_REGISTERSUBSCRIBERREQUEST']._serialized_start = 11290
    _globals['_REGISTERSUBSCRIBERREQUEST']._serialized_end = 11369
    _globals['_REGISTERSUBSCRIBERRESPONSE']._serialized_start = 11371
    _globals['_REGISTERSUBSCRIBERRESPONSE']._serialized_end = 11414
    _globals['_UNREGISTERSUBSCRIBERREQUEST']._serialized_start = 11416
    _globals['_UNREGISTERSUBSCRIBERREQUEST']._serialized_end = 11497
    _globals['_UNREGISTERSUBSCRIBERRESPONSE']._serialized_start = 11499
    _globals['_UNREGISTERSUBSCRIBERRESPONSE']._serialized_end = 11544
    _globals['_LISTSUBSCRIBERSREQUEST']._serialized_start = 11546
    _globals['_LISTSUBSCRIBERSREQUEST']._serialized_end = 11641
    _globals['_LISTSUBSCRIBERSRESPONSE']._serialized_start = 11643
    _globals['_LISTSUBSCRIBERSRESPONSE']._serialized_end = 11734
    _globals['_LISTENTITLEMENTCHANGESREQUEST']._serialized_start = 11737
    _globals['_LISTENTITLEMENTCHANGESREQUEST']._serialized_end = 11903
    _globals['_LISTENTITLEMENTCHANGESRESPONSE']._serialized_start = 11906
    _globals['_LISTENTITLEMENTCHANGESRESPONSE']._serialized_end = 12036
    _globals['_CLOUDCHANNELSERVICE']._serialized_start = 12039
    _globals['_CLOUDCHANNELSERVICE']._serialized_end = 22604