"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    patch_v2_webhooks_webhook_id_op as models_patch_v2_webhooks_webhook_id_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PatchV2WebhooksWebhookIDNotFoundErrorData(BaseModel):
    status_code: float

    type: models_patch_v2_webhooks_webhook_id_op.PatchV2WebhooksWebhookIDType

    code: models_patch_v2_webhooks_webhook_id_op.PatchV2WebhooksWebhookIDCode

    message: str


@dataclass(frozen=True)
class PatchV2WebhooksWebhookIDNotFoundError(SDKError):
    r"""Not Found"""

    data: PatchV2WebhooksWebhookIDNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PatchV2WebhooksWebhookIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
